Repository cvc5/cvc5, pull requests merged in 2018-09, with the labels that each got.

#2411 Refactor ceg conjecture initialization
  src/theory/quantifiers/sygus/ce_guided_conjecture.cpp
  src/theory/quantifiers/sygus/ce_guided_conjecture.h
  src/theory/quantifiers/sygus/ce_guided_instantiation.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.h
Labels: moderate, normal

#2421 Transfer ownership of learned literals from SMT engine to circuit propagator.
  src/smt/smt_engine.cpp
  src/theory/booleans/circuit_propagator.h
Labels: normal, simple

#2099 Make quantifiers strategies exit immediately when in conflict
  src/theory/quantifiers/ematching/inst_match_generator.cpp
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/quant_conflict_find.h
  test/regress/Makefile.tests
  test/regress/regress0/quantifiers/issue2035.smt2
Labels: minor, simple

#2408 Minor improvements to theory model builder interface
  src/theory/theory_engine.cpp
  src/theory/theory_model_builder.cpp
  src/theory/theory_model_builder.h
Labels: minor, simple

#2413 Remove unused options file
  src/options/smt_options
Labels: minor, simple

#2420 Update INSTALL instructions
  INSTALL
Labels: minor, simple

#2422 Remove redundant strings rewrite
  src/theory/strings/theory_strings_rewriter.cpp
Labels: normal, simple

#2428 Add HAVE_CLOCK_GETTIME guard to clock_gettime.c
  src/lib/clock_gettime.c
Labels: major, simple

#2427 Extended rewriter for string equalities
  src/theory/quantifiers/extended_rewrite.cpp
  src/theory/quantifiers/extended_rewrite.h
  src/theory/strings/theory_strings_rewriter.cpp
  test/regress/Makefile.tests
  test/regress/regress0/strings/str_unsound_ext_rew_eq.smt2
Labels: moderate, normal

#2426 Add regex grammar to rewriter verification tests
  test/regress/Makefile.tests
  test/regress/regress1/rr-verify/regex.sy
Labels: minor, simple

#2403 Finer-grained inference of substitutions in incremental mode
  src/expr/node_algorithm.cpp
  src/expr/node_algorithm.h
  src/smt/smt_engine.cpp
Labels: moderate, normal

#2430 Remove printing support for sygus enumeration types
  src/printer/smt2/smt2_printer.cpp
Labels: minor, simple

#2432 Use std::unique_ptr for d_eq_infer to make Coverity happy.
  src/theory/arith/congruence_manager.cpp
  src/theory/arith/congruence_manager.h
Labels: minor, simple

#2433 Eliminate select over store in quantifier bodies
  src/theory/quantifiers/quantifiers_rewriter.cpp
Labels: normal, simple

#2431 More extended rewrites for strings equality
  src/theory/quantifiers/extended_rewrite.cpp
Labels: major, moderate

#2435 Minor improvements to interface for rep set
  src/theory/rep_set.cpp
  src/theory/rep_set.h
Labels: normal, simple

#2424 Refactor and document quantifiers variable elimination and conditional splitting
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
  test/regress/Makefile.tests
  test/regress/regress0/quantifiers/cond-var-elim-binary.smt2
Labels: moderate, normal

#2437 Further simplify and fix initialization of ce guided instantiation
  src/theory/quantifiers/sygus/ce_guided_conjecture.cpp
  src/theory/quantifiers/sygus/ce_guided_conjecture.h
  src/theory/quantifiers/sygus/ce_guided_instantiation.cpp
  src/theory/quantifiers/sygus/ce_guided_instantiation.h
Labels: major, simple

#2434 Make isClosedEnumerable a member of TypeNode
  src/expr/type_node.cpp
  src/expr/type_node.h
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/first_order_model.cpp
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/term_enumeration.cpp
  src/theory/quantifiers/term_enumeration.h
Labels: moderate, normal

#2436 Remove clock_gettime() replacement for macOS.
  src/lib/clock_gettime.c
  src/lib/clock_gettime.h
Labels: normal, simple

#2439 Replace boost::integer_traits with std::numeric_limits.
  src/options/options_handler.cpp
  src/util/dense_map.h
Labels: normal, simple

#2441 Add (str.replace (str.replace y w y) y z) rewrite
  src/theory/strings/theory_strings_rewriter.cpp
  test/regress/Makefile.tests
  test/regress/regress2/strings/repl-repl.smt2
  test/unit/theory/theory_strings_rewriter_white.h
Labels: moderate, normal

#2423 Squash implementation of counterexample-guided instantiation
  src/theory/quantifiers/cegqi/inst_strategy_cbqi.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cbqi.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: moderate, normal

#2425 Refactor non-clausal simplify preprocessing pass.
  src/Makefile.am
  src/preprocessing/passes/non_clausal_simp.cpp
  src/preprocessing/passes/non_clausal_simp.h
  src/preprocessing/preprocessing_pass_context.cpp
  src/preprocessing/preprocessing_pass_context.h
  src/smt/smt_engine.cpp
Labels: moderate, normal

#2440 Using a single condition enumerator in sygus-unif
  src/options/quantifiers_options.toml
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/cegis_unif.h
  src/theory/quantifiers/sygus/sygus_unif_rl.cpp
  src/theory/quantifiers/sygus/sygus_unif_rl.h
Labels: moderate, normal

#2445 Set NodeManager to nullptr when exporting vars
  src/expr/expr_template.cpp
Labels: major, simple

#2449 Fix global negate
  src/preprocessing/passes/global_negate.cpp
  test/regress/Makefile.tests
  test/regress/regress2/quantifiers/gn-wrong-091018.smt2
Labels: major, simple

#2450 avoid calling size() every iteration in global-negate
  src/preprocessing/passes/global_negate.cpp
Labels: minor

#2407 Support model cores via option --produce-model-cores.
  src/Makefile.am
  src/options/smt_options.toml
  src/printer/printer.cpp
  src/smt/model.h
  src/smt/model_core_builder.cpp
  src/smt/model_core_builder.h
  src/smt/smt_engine.cpp
  src/theory/bv/theory_bv_utils.cpp
  src/theory/bv/theory_bv_utils.h
  src/theory/quantifiers/term_util.cpp
  src/theory/quantifiers/term_util.h
  src/theory/subs_minimize.cpp
  src/theory/subs_minimize.h
  src/theory/theory_model.cpp
  src/theory/theory_model.h
  test/regress/Makefile.tests
  test/regress/regress0/model-core.smt2
Labels: major, moderate

#2453 Fix compiler warning in line_buffer.cpp.
  src/parser/line_buffer.cpp
Labels: normal, simple

#2456 Fix for when strings process loop is disabled.
  src/theory/strings/theory_strings.cpp
Labels: normal, simple

#2447 Initial infrastructure for theory decision manager
  src/Makefile.am
  src/theory/decision_manager.cpp
  src/theory/decision_manager.h
  src/theory/decision_strategy.cpp
  src/theory/decision_strategy.h
  src/theory/theory.cpp
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: do not merge, moderate, normal

#2461 Examples: Remove obsolete flag CVC4_MAKE_EXAMPLES.
  examples/api/Makefile.am
  examples/api/helloworld-new.cpp
  examples/api/helloworld.cpp
Labels: normal, simple

#2454 New C++ API: Try to fix (false positive) Coverity warnings.
  src/api/cvc4cpp.cpp
Labels: normal, simple

#2460 Decision strategy: incorporate CEGQI
  src/theory/arith/theory_arith_private.h
  src/theory/quantifiers/cegqi/inst_strategy_cbqi.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cbqi.h
Labels: normal, simple

#2458 Simplify storing of transcendental function applications that occur in assertions
  src/theory/arith/nonlinear_extension.cpp
  src/theory/arith/nonlinear_extension.h
Labels: moderate, normal

#2451 Uses information gain heuristic for building better solutions from DTs
  src/options/quantifiers_options.toml
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/sygus_unif_rl.cpp
  src/theory/quantifiers/sygus/sygus_unif_rl.h
  test/regress/Makefile.tests
  test/regress/regress1/sygus/car_3.lus.sy
Labels: moderate, normal

#2463 Fix #include for minisat headers in bvminisat.
  src/prop/bvminisat/core/Dimacs.h
  src/prop/bvminisat/core/Main.cc
  src/prop/bvminisat/core/Solver.cc
  src/prop/bvminisat/mtl/Sort.h
  src/prop/bvminisat/simp/Main.cc
  src/prop/bvminisat/simp/SimpSolver.cc
  src/prop/bvminisat/utils/Options.cc
  src/prop/bvminisat/utils/System.cc
  src/prop/bvminisat/utils/System.h
Labels: major, simple

#2340 Generalize CandidateRewriteDatabase to ExprMiner
  src/Makefile.am
  src/options/quantifiers_options.toml
  src/theory/quantifiers/candidate_rewrite_database.cpp
  src/theory/quantifiers/candidate_rewrite_database.h
  src/theory/quantifiers/expr_miner.cpp
  src/theory/quantifiers/expr_miner.h
  src/theory/quantifiers/expr_miner_manager.cpp
  src/theory/quantifiers/expr_miner_manager.h
  src/theory/quantifiers/sygus/ce_guided_conjecture.cpp
  src/theory/quantifiers/sygus/ce_guided_conjecture.h
  test/regress/regress1/rr-verify/bv-term.sy
Labels: moderate, normal

#2457 Add Skolem cache for strings, refactor length registration
  src/Makefile.am
  src/theory/strings/skolem_cache.cpp
  src/theory/strings/skolem_cache.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: moderate, normal

#2396 Refactor how assertions are added to decision engine
  src/Makefile.am
  src/api/cvc4cpp.cpp
  src/decision/decision_engine.cpp
  src/decision/decision_engine.h
  src/decision/decision_strategy.h
  src/decision/justification_heuristic.cpp
  src/decision/justification_heuristic.h
  src/include/cvc4_private_library.h
  src/preprocessing/assertion_pipeline.cpp
  src/preprocessing/assertion_pipeline.h
  src/preprocessing/passes/apply_substs.cpp
  src/preprocessing/passes/miplib_trick.cpp
  src/preprocessing/passes/non_clausal_simp.cpp
  src/preprocessing/preprocessing_pass.cpp
  src/preprocessing/preprocessing_pass.h
  src/preprocessing/preprocessing_pass_context.cpp
  src/preprocessing/preprocessing_pass_context.h
  src/smt/smt_engine.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cbqi.cpp
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/sygus/sygus_repair_const.cpp
  src/theory/theory_engine.cpp
  test/unit/preprocessing/pass_bv_gauss_white.h
Labels: moderate, normal

#2462 Decision strategy: incorporate sygus feasible and sygus stream feasible
  src/theory/quantifiers/sygus/ce_guided_conjecture.cpp
  src/theory/quantifiers/sygus/ce_guided_conjecture.h
Labels: normal, simple

#2476 Decision strategy: incorporate UF with cardinality constraints
  src/theory/uf/kinds
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf.h
  src/theory/uf/theory_uf_strong_solver.cpp
  src/theory/uf/theory_uf_strong_solver.h
Labels: moderate, normal

#2472 Remove unnecessary tracing from preprocessing
  src/smt/smt_engine.cpp
Labels: minor, simple

#2470 Remove broken dumping support from portfolio build
  configure.ac
  src/smt/dump.h
Labels: minor, simple

#2471 Follow redirects with cURL in contrib/get* scripts
  contrib/get-script-header.sh
Labels: minor, simple

#2444 Make strings model construction robust to lengths that are not propagated equal
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  test/regress/Makefile.tests
  test/regress/regress1/strings/issue2429-code.smt2
  test/regress/regress3/issue2429.smt2
Labels: major, moderate

#2478 More aggressive skolem caching for strings, document and clean preprocessor
  src/options/strings_options.toml
  src/theory/strings/skolem_cache.cpp
  src/theory/strings/skolem_cache.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/theory_strings_preprocess.h
Labels: moderate, normal

#2481 Decision strategy: incorporate bounded integers
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/fmf/bounded_integers.h
Labels: normal, simple

#2482 Decision strategy: incorporate cegis unif
  src/theory/quantifiers/sygus/ce_guided_conjecture.cpp
  src/theory/quantifiers/sygus/ce_guided_conjecture.h
  src/theory/quantifiers/sygus/ce_guided_instantiation.cpp
  src/theory/quantifiers/sygus/ce_guided_instantiation.h
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/cegis_unif.h
  src/theory/quantifiers/sygus/sygus_module.h
Labels: moderate, normal

#2477 Move inst_strategy_cbqi to inst_strategy_cegqi
  src/Makefile.am
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.h
  src/theory/quantifiers_engine.cpp
Labels: minor, simple

#2459 Improvements and fixes for symmetry detection and breaking
  src/preprocessing/passes/symmetry_breaker.cpp
  src/preprocessing/passes/symmetry_detect.cpp
  src/preprocessing/passes/symmetry_detect.h
  src/theory/quantifiers/term_util.cpp
  test/regress/Makefile.tests
  test/regress/regress1/sym/q-constant.smt2
  test/regress/regress1/sym/q-function.smt2
  test/regress/regress1/sym/qf-function.smt2
  test/regress/regress1/sym/sb-wrong.smt2
  test/regress/regress1/sym/sym-setAB.smt2
Labels: minor, moderate

#2484 Clean remaining references to getNextDecisionRequest in quantifiers
  src/theory/quantifiers/kinds
  src/theory/quantifiers/quant_util.h
  src/theory/quantifiers/theory_quantifiers.cpp
  src/theory/quantifiers/theory_quantifiers.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: normal, simple

#2487 Fix assertion error in model core computation
  src/smt/model_core_builder.cpp
Labels: normal, simple

#2488 Move and rename sygus solver classes
  src/Makefile.am
  src/smt/smt_engine.cpp
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/datatypes/datatypes_sygus.h
  src/theory/quantifiers/candidate_rewrite_database.cpp
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.h
  src/theory/quantifiers/sygus/ce_guided_single_inv_sol.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv_sol.h
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/cegis.h
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/cegis_unif.h
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.h
  src/theory/quantifiers/sygus/sygus_grammar_norm.cpp
  src/theory/quantifiers/sygus/sygus_invariance.cpp
  src/theory/quantifiers/sygus/sygus_invariance.h
  src/theory/quantifiers/sygus/sygus_module.cpp
  src/theory/quantifiers/sygus/sygus_module.h
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/sygus/sygus_pbe.h
  src/theory/quantifiers/sygus/sygus_process_conj.cpp
  src/theory/quantifiers/sygus/sygus_process_conj.h
  src/theory/quantifiers/sygus/sygus_unif_rl.cpp
  src/theory/quantifiers/sygus/sygus_unif_rl.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus/synth_engine.h
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: normal, simple

#2491 More aggressive caching of string skolems.
  src/theory/strings/theory_strings_preprocess.cpp
Labels: moderate, normal

#2485 Decision strategy: incorporate strings fmf.
  src/theory/decision_manager.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: major, moderate

#2493 Fix issue with str.idof in evaluator
  src/theory/evaluator.cpp
  test/unit/theory/evaluator_white.h
Labels: major, simple

#2480 Refactor strings extended functions inferences
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: moderate, normal

#2492 Add two rewrites for string contains character
  src/theory/strings/theory_strings_rewriter.cpp
Labels: moderate, normal

#2494 Decision strategy: incorporate separation logic.
  src/theory/sep/kinds
  src/theory/sep/theory_sep.cpp
  src/theory/sep/theory_sep.h
Labels: moderate, normal

#2496 Add rewrites for str.contains + str.replace/substr
  src/theory/strings/theory_strings_rewriter.cpp
  test/unit/theory/theory_strings_rewriter_white.h
Labels: moderate, normal

#2495 Decision strategy: incorporate arrays.
  src/theory/arrays/kinds
  src/theory/arrays/theory_arrays.cpp
  src/theory/arrays/theory_arrays.h
Labels: moderate, normal

#2502 Fix strings benchmark in regress2
  test/regress/regress2/strings/cmu-disagree-0707-dd.smt2
Labels: major, simple

#2455 New C++ API: Add checks for Terms/OpTerms.
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/expr/expr_template.h
Labels: normal, simple

#2515 cmake: Add program prefix option.
  CMakeLists.txt
  configure.sh
  src/main/CMakeLists.txt
Labels: major, simple

#2516 cmake: Fix and simplify git version info.
  cmake/GetGitRevisionDescription.cmake
  cmake/GetGitRevisionDescription.cmake.in
  src/base/CMakeLists.txt
Labels: major, simple

#2520 Make string rewriter unit tests more robust
  test/unit/theory/theory_strings_rewriter_white.h
Labels: normal, simple

#2518 cmake: Fix theory order.
  src/theory/CMakeLists.txt
Labels: major, simple

#2512 Unify rewrites related to (str.contains x y) --> (= x y)
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
  test/unit/theory/theory_strings_rewriter_white.h
Labels: moderate, normal

#2523 cmake: Fix git version info (again).
  src/base/CMakeLists.txt
Labels: major, simple

#2504 Fix wiki urls.
  doc/libcvc4.3.in
  src/expr/expr_template.h
  src/expr/node.h
  src/expr/node_manager.h
Labels: normal, simple

#2524 cmake: Fix dependencies for code generation.
  src/base/CMakeLists.txt
  src/expr/CMakeLists.txt
  src/theory/CMakeLists.txt
Labels: major, simple

#2513 Refactor strings equality rewriting
  src/theory/quantifiers/extended_rewrite.cpp
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
Labels: moderate, normal

#2497 Improve non-linear check model error handling
  src/theory/arith/nonlinear_extension.cpp
  src/theory/arith/nonlinear_extension.h
Labels: moderate, normal

#2511 Infrastructure for variable agnostic sygus enumerators
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
Labels: minor, moderate

#2499 Allow partial models for multiple sygus enumerators
  src/theory/datatypes/datatypes_rewriter.h
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/sygus_module.h
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/sygus/sygus_pbe.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/synth_engine.cpp
Labels: minor, moderate

#2521 Fix warnings uncovered by cmake build
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/quantifiers/extended_rewrite.cpp
Labels: minor, simple

#2529 cmake: Fix tag code generation dependencies.
  src/base/CMakeLists.txt
Labels: major, simple

#2505 carefully printing trusted assertions in proofs
  src/proof/proof_manager.cpp
  src/proof/proof_manager.h
Labels: bug

#2534 examples/hashsmt/sha1_inversion: Fix includes for newer Boost version.
  examples/hashsmt/sha1_inversion.cpp
Labels: major, simple

#2533 cmake: Add check for GCC 4.5.1 and warn user.
  CMakeLists.txt
Labels: normal, simple

#2531 Eagerly ensure literal on active guards for sygus enumerators
  src/theory/quantifiers/sygus/term_database_sygus.cpp
Labels: major, simple

#2536 cmake: New INSTALL.md for build and testing instructions.
  INSTALL
  INSTALL.md
  examples/README
Labels: major, simple

#2527 Symmetry breaking for variable agnostic enumerators
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/datatypes/datatypes_sygus.h
Labels: moderate, normal

#2539 Enable quantified array regression.
  test/regress/CMakeLists.txt
  test/regress/Makefile.tests
Labels: minor, simple

#2540 cmake: Fix test target dependency issues.
  CMakeLists.txt
  test/CMakeLists.txt
  test/java/CMakeLists.txt
  test/regress/CMakeLists.txt
  test/system/CMakeLists.txt
  test/unit/CMakeLists.txt
Labels: major, simple

#2509 Makes SyGuS parsing more robust in invariant problems
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  test/regress/CMakeLists.txt
  test/regress/Makefile.tests
  test/regress/regress0/sygus/inv-different-var-order.sy
Labels: minor, simple

#2543 cmake: Only print dumping warning if not disabled by user.
  cmake/ConfigDebug.cmake
  cmake/ConfigProduction.cmake
  cmake/ConfigTesting.cmake
Labels: minor, simple

#2538 Fix Taylor overapproximation for large exponentials
  src/theory/arith/nonlinear_extension.cpp
  src/theory/arith/nonlinear_extension.h
  test/regress/CMakeLists.txt
  test/regress/Makefile.tests
  test/regress/regress1/nl/exp-approx.smt2
Labels: major, moderate

#2541 Incorporate all sygus-unif enumerators into getTermList.
  src/theory/quantifiers/sygus/cegis_unif.cpp
Labels: moderate, normal

#2547 Infrastructure for using active enumerators in sygus modules
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/cegis.h
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/sygus/sygus_unif_io.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
Labels: moderate, normal

#2549 Remove assertion related to sygus enumerators
  src/theory/quantifiers/sygus/synth_conjecture.cpp
Labels: major, simple

#2542 cmake: Add CxxTest finder module to allow custom paths.
  CMakeLists.txt
  cmake/FindCxxTest.cmake
  configure.sh
  test/unit/CMakeLists.txt
Labels: major, moderate

#2551 cmake: Only do Java tests when unit testing on
  test/CMakeLists.txt
Labels: minor, simple

#2546 Rewrites for (= "" _) and (= (str.replace _) _)
  src/theory/quantifiers/extended_rewrite.cpp
  src/theory/strings/theory_strings_rewriter.cpp
  test/unit/theory/theory_strings_rewriter_white.h
Labels: moderate, normal

#2526 Stream concrete values for variable agnostic enumerators
  src/CMakeLists.txt
  src/Makefile.am
  src/theory/quantifiers/sygus/enum_stream_substitution.cpp
  src/theory/quantifiers/sygus/enum_stream_substitution.h
Labels: moderate, normal

#2532 Add rewrite for solving stoi
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
  test/regress/CMakeLists.txt
  test/regress/Makefile.tests
  test/regress/regress0/strings/stoi-solve.smt2
Labels: moderate, normal
