Repository cvc5/cvc5, pull requests merged in 2018-11, with the labels that each got.

#2679 fixes to regression docs
  INSTALL.md
  test/regress/README.md
Labels: do not merge, minor, simple

#2681 Refactor default grammars construction
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.h
Labels: normal, simple

#2686 Implement option to turn off symmetry breaking for basic enumerators
  src/theory/quantifiers/sygus/sygus_enumerator.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
Labels: normal, simple

#2611 configure.sh: Fix option parsing to match --help
  configure.sh
Labels: minor, simple

#2680 API: Fix assignment operators
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  test/unit/api/CMakeLists.txt
  test/unit/api/term_black.h
Labels: moderate, normal

#2688 New C++ API: Split unit tests.
  test/unit/api/CMakeLists.txt
  test/unit/api/api_guards_black.h
  test/unit/api/solver_black.h
  test/unit/api/sort_black.h
Labels: normal, simple

#2687 Fix coverity warnings in sygus enumerator
  src/theory/quantifiers/sygus/sygus_enumerator.cpp
Labels: minor, simple

#2689 Change default sygus enumeration mode to auto
  src/options/options_handler.cpp
  src/options/quantifiers_modes.h
  src/options/quantifiers_options.toml
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
Labels: moderate, normal

#2690 Incorporate static PBE symmetry breaking lemmas into SygusEnumerator
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/quantifiers/sygus/sygus_enumerator.cpp
  src/theory/quantifiers/sygus/sygus_enumerator.h
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
Labels: moderate, normal

#2685 Adding default SyGuS grammar construction for arrays
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/sygus/array-grammar-select.sy
  test/regress/regress0/sygus/array-grammar-store.sy
Labels: normal, simple

#2696 Evaluator: add support for str.code
  src/theory/evaluator.cpp
  test/unit/theory/evaluator_white.h
Labels: major, simple

#2698 cmake: Add option to explicitely enable/disable static binaries.
  CMakeLists.txt
  configure.sh
  src/main/CMakeLists.txt
Labels: major, simple

#2710 cmake: Require boost 1.50.0 for examples.
  examples/CMakeLists.txt
Labels: major, simple

#2707 Expand definitions prior to model core computation
  src/smt/smt_engine.cpp
Labels: normal, simple

#2708 Fix E-matching for case where candidate generator is not properly initialized
  src/theory/quantifiers/ematching/inst_match_generator.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/rel-trigger-unusable.smt2
Labels: minor, simple

#2711 Clausify context-dependent simplifications in ext theory
  src/theory/ext_theory.cpp
Labels: normal, simple

#2712 Change lemma proof step storage & iterators
  src/proof/lemma_proof.cpp
  src/proof/lemma_proof.h
Labels: minor, refactor

#2716 Fix real2int regression.
  test/regress/CMakeLists.txt
  test/regress/regress2/arith/real2int-test.smt2
Labels: major, simple

#2717 Fix type enumerator for FP
  src/theory/fp/type_enumerator.h
Labels: normal, simple

#2704 Support string replace all
  src/parser/cvc/Cvc.g
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/strings/kinds
  src/theory/strings/skolem_cache.cpp
  src/theory/strings/skolem_cache.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/replaceall-eval.smt2
  test/regress/regress1/strings/replaceall-len.smt2
  test/regress/regress1/strings/replaceall-replace.smt2
  test/regress/regress2/strings/replaceall-diffrange.smt2
  test/regress/regress2/strings/replaceall-len-c.smt2
Labels: moderate, normal

#2699 Cache evaluations for PBE
  src/theory/quantifiers/sygus/sygus_enumerator.cpp
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/sygus/sygus_pbe.h
  src/theory/quantifiers/sygus/sygus_unif_io.cpp
  src/theory/quantifiers/sygus/sygus_unif_io.h
Labels: moderate, normal

#2695 Add rewrite for (str.substr s x y) --> ""
  src/theory/strings/theory_strings_rewriter.cpp
  test/unit/theory/theory_strings_rewriter_white.h
Labels: normal, simple

#2703 Move ss-combine rewrite to extended rewriter
  src/theory/quantifiers/extended_rewrite.cpp
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
Labels: normal, simple

#2701 Use https for antlr3.org downloads
  contrib/get-antlr-3.4
Labels: do not merge, minor, simple

#2713 LRA proof signature fixes and a first proof for linear polynomials
  proofs/signatures/th_lra.plf
  proofs/signatures/th_lra_test.plf
  proofs/signatures/th_real.plf
Labels: do not merge

#2721 Reduce lookahead when parsing string literals
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.h
Labels: major, moderate

#2633 Lazy model construction in TheoryEngine
  src/smt/smt_engine.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: complex, major

#2553 Fix coverity warnings in datatypes
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
Labels: moderate, normal

#2489 Make TNodeTrie a general utility
  src/expr/CMakeLists.txt
  src/expr/node_trie.cpp
  src/expr/node_trie.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
  src/theory/quantifiers/cegqi/ceg_epr_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_epr_instantiator.h
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/conjecture_generator.h
  src/theory/quantifiers/ematching/candidate_generator.cpp
  src/theory/quantifiers/ematching/inst_match_generator.cpp
  src/theory/quantifiers/ematching/inst_match_generator.h
  src/theory/quantifiers/inst_propagator.h
  src/theory/quantifiers/local_theory_ext.cpp
  src/theory/quantifiers/local_theory_ext.h
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/quant_conflict_find.h
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers/term_database.h
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf.h
Labels: minor, moderate

#2697 Generalize sygus stream solution filtering to logical strength
  src/options/options_handler.cpp
  src/options/options_handler.h
  src/options/quantifiers_modes.h
  src/options/quantifiers_options.toml
  src/theory/quantifiers/expr_miner.cpp
  src/theory/quantifiers/expr_miner.h
  src/theory/quantifiers/expr_miner_manager.cpp
  src/theory/quantifiers/expr_miner_manager.h
  src/theory/quantifiers/solution_filter.cpp
  src/theory/quantifiers/solution_filter.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
Labels: minor, moderate

#2723 Improve skolem caching by normalizing skolem args
  src/theory/strings/skolem_cache.cpp
  src/theory/strings/skolem_cache.h
  test/unit/theory/CMakeLists.txt
  test/unit/theory/theory_strings_skolem_cache_black.h
Labels: moderate, normal

#2725 Optimize re-elim for re.allchar components
  src/theory/strings/regexp_elim.cpp
  test/regress/CMakeLists.txt
  test/regress/regress2/strings/small-1.smt2
Labels: major, moderate

#2719 Information gain heuristic for PBE
  src/theory/quantifiers/sygus/sygus_unif.cpp
  src/theory/quantifiers/sygus/sygus_unif.h
  src/theory/quantifiers/sygus/sygus_unif_io.cpp
  src/theory/quantifiers/sygus/sygus_unif_io.h
Labels: moderate, normal

#2727 Improve interface for sygus grammar cons
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.h
Labels: minor, simple

#2726 Combine sygus stream with PBE
  src/smt/smt_engine.cpp
  src/theory/quantifiers/sygus/sygus_unif.cpp
  src/theory/quantifiers/sygus/sygus_unif.h
  src/theory/quantifiers/sygus/sygus_unif_io.cpp
  src/theory/quantifiers/sygus/sygus_unif_io.h
Labels: moderate, normal
