Repository cvc5/cvc5, pull requests merged in 2018-03, with the labels that each got.

#1632 Create infrastructure for sygus modules
  src/Makefile.am
  src/theory/quantifiers/sygus/ce_guided_conjecture.cpp
  src/theory/quantifiers/sygus/ce_guided_conjecture.h
  src/theory/quantifiers/sygus/ce_guided_instantiation.cpp
  src/theory/quantifiers/sygus/ce_guided_instantiation.h
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/cegis.h
  src/theory/quantifiers/sygus/sygus_module.cpp
  src/theory/quantifiers/sygus/sygus_module.h
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/sygus/sygus_pbe.h
Labels: moderate, normal

#1635 Print candidate rewrites in terms of original grammar
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/quantifiers/sygus/ce_guided_conjecture.cpp
  src/theory/quantifiers/sygus_sampler.cpp
  src/theory/quantifiers/sygus_sampler.h
Labels: normal, simple

#1634 Simplify sygus wrt miniscoping
  src/theory/quantifiers/sygus/ce_guided_conjecture.cpp
  src/theory/quantifiers/sygus/ce_guided_conjecture.h
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/cegis.h
  src/theory/quantifiers/sygus/sygus_module.h
Labels: normal, simple

#1636 Optimization for sygus streaming mode
  src/theory/quantifiers/sygus/ce_guided_conjecture.cpp
  src/theory/quantifiers/sygus/ce_guided_conjecture.h
Labels: normal, simple

#1638 Add uniform way to serialize containers of Expr to stream.
  src/expr/expr_template.cpp
  src/expr/expr_template.h
  src/expr/node.h
  src/util/utility.h
Labels: normal, simple

#1644 Add CVC4_PUBLIC keyword to overloads of << for Expr containers.
  src/expr/expr_template.h
Labels: normal, simple

#1637 Add support for check-sat-assuming.
  examples/api/bitvectors.cpp
  src/expr/expr_template.cpp
  src/expr/expr_template.h
  src/parser/smt2/Smt2.g
  src/printer/ast/ast_printer.cpp
  src/printer/cvc/cvc_printer.cpp
  src/printer/smt2/smt2_printer.cpp
  src/smt/command.cpp
  src/smt/command.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  test/regress/regress0/push-pop/Makefile.am
  test/regress/regress0/push-pop/bug821-check_sat_assuming.smt2
Labels: complex, normal

#1639 Fix sampler filtering
  src/theory/quantifiers/sygus_sampler.cpp
  src/theory/quantifiers/sygus_sampler.h
Labels: normal, simple

#1630 Update semantics for string indexof and replace
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
  test/regress/regress0/strings/idof-sem.smt2
  test/regress/regress0/strings/repl-rewrites2.smt2
  test/regress/regress1/strings/Makefile.am
  test/regress/regress1/strings/double-replace.smt2
  test/regress/regress1/strings/repl-empty-sem.smt2
  test/regress/regress1/strings/repl-soundness-sem.smt2
  test/regress/regress1/strings/rew-020618.smt2
  test/regress/regress1/strings/string-unsound-sem.smt2
  test/regress/regress2/strings/Makefile.am
  test/regress/regress2/strings/cmu-disagree-0707-dd.smt2
Labels: major, moderate

#1629 Remove printf from output utilities
  src/base/output.cpp
  src/base/output.h
  test/unit/util/output_black.h
Labels: minor, refactor

#1640 Refactor symmetry breaking in datatypes sygus
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/datatypes/datatypes_sygus.h
  src/theory/quantifiers/sygus/ce_guided_conjecture.cpp
  src/theory/quantifiers/sygus/sygus_explain.cpp
  src/theory/quantifiers/sygus/sygus_explain.h
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
Labels: moderate, normal

#1641 Simplify initialization of quantifiers engine
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
  src/theory/theory_engine.cpp
Labels: minor, simple

#1647 Make statistics output consistent.
  examples/sets-translate/sets_translate.cpp
  src/expr/kind_template.cpp
  src/expr/kind_template.h
  src/expr/mkkind
  src/main/command_executor.cpp
  src/parser/smt2/smt2.cpp
  src/proof/array_proof.cpp
  src/proof/proof_manager.cpp
  src/proof/theory_proof.cpp
  src/prop/bvminisat/bvminisat.cpp
  src/smt/smt_engine.cpp
  src/theory/arrays/kinds
  src/theory/arrays/theory_arrays.cpp
  src/theory/bv/abstraction.cpp
  src/theory/bv/bv_quick_check.cpp
  src/theory/bv/bv_quick_check.h
  src/theory/bv/bv_subtheory_algebraic.cpp
  src/theory/bv/bv_subtheory_bitblast.cpp
  src/theory/bv/bv_subtheory_bitblast.h
  src/theory/bv/bv_subtheory_core.cpp
  src/theory/bv/bv_to_bool.cpp
  src/theory/bv/lazy_bitblaster.cpp
  src/theory/bv/slicer.cpp
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/fp/theory_fp.cpp
  src/theory/logic_info.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/theory.cpp
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/uf/theory_uf.cpp
  src/util/statistics.cpp
Labels: moderate, normal

#1651 Fix Travis for unit test compilation errors.
  .travis.yml
  src/theory/theory.cpp
  test/regress/Makefile.levels
  test/unit/Makefile.am
  test/unit/theory/logic_info_white.h
  test/unit/theory/theory_engine_white.h
Labels: major, simple

#1652 Cleanup Cryptominisat SAT wrapper.
  contrib/get-cryptominisat4
  src/prop/cryptominisat.cpp
  src/prop/cryptominisat.h
  src/prop/sat_solver_factory.cpp
Labels: minor, refactor, simple

#1656 Skip (get-unsat-assumptions) tests not supported
  test/regress/run_regression
Labels: major, simple

#1653 Add support for SMT-LIB v2.5 command get-unsat-assumptions
  src/options/smt_options
  src/parser/smt2/Smt2.g
  src/printer/smt2/smt2_printer.cpp
  src/smt/command.cpp
  src/smt/command.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  test/regress/regress0/push-pop/bug821-check_sat_assuming.smt2
Labels: moderate, normal

#1663 Some minor cleanup in bv::utils.
  src/theory/bv/theory_bv_utils.cpp
Labels: normal, simple

#1654 Printers are now managed as unique_ptr (fix mem leak).
  src/printer/printer.cpp
  src/printer/printer.h
Labels: normal, simple

#1665 SmtEngine::getModel() is now public.
  src/smt/smt_engine.h
Labels: normal, simple

#1664 Use Cryptominisat version 5.0.2 (instead of 4.2.0).
  config/cryptominisat.m4
  contrib/Makefile.am
  contrib/cryptominisat-4.2.0.patch
  contrib/cryptominisat-4.2.0.second.patch
  contrib/get-cryptominisat
  src/prop/cryptominisat.cpp
Labels: moderate, normal

#1642 Document inferences for strings
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: minor, simple

#1674 Enable CEGQI for non-linear
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.h
  src/theory/quantifiers/cegqi/ceg_t_instantiator.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cbqi.cpp
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/ematching/trigger.h
  test/regress/regress0/quantifiers/Makefile.am
  test/regress/regress0/quantifiers/cegqi-nl-simp.cvc
  test/regress/regress0/quantifiers/cegqi-nl-sq.smt2
Labels: normal, simple

#1669 correct instruction for running example
  proofs/signatures/example-arrays.plf
Labels: minor, simple

#1676 Add parameterized datatypes example.
  examples/api/datatypes.cpp
Labels: normal, simple

#1678 Minor fix and addition to sygus sampler
  src/theory/quantifiers/sygus_sampler.cpp
  src/theory/quantifiers/sygus_sampler.h
Labels: normal, simple

#1672 Fix datatype dump regression
  test/regress/regress0/datatypes/Makefile.am
  test/regress/regress0/datatypes/datatype-dump.cvc
Labels: minor, simple

#1633 Internally remove redundant assertions and infer equalities in NonLinearExtension
  src/theory/arith/nonlinear_extension.cpp
  src/theory/arith/nonlinear_extension.h
  test/regress/regress1/nl/Makefile.am
  test/regress/regress1/nl/nl-eq-infer.smt2
Labels: moderate, normal

#1673 Minor refactor datatypes sygus
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/datatypes/datatypes_sygus.h
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
Labels: minor, simple

#1675 Add support for CaDiCaL as eager BV SAT solver.
  COPYING
  config/cadical.m4
  config/cryptominisat.m4
  configure.ac
  contrib/get-cadical
  src/Makefile.am
  src/base/configuration.cpp
  src/base/configuration.h
  src/base/configuration_private.h
  src/options/bv_bitblast_mode.h
  src/options/options_handler.cpp
  src/prop/cadical.cpp
  src/prop/cadical.h
  src/prop/cryptominisat.cpp
  src/prop/cryptominisat.h
  src/prop/sat_solver_factory.cpp
  src/prop/sat_solver_factory.h
  src/theory/bv/eager_bitblaster.cpp
Labels: moderate, normal

#1679 Fix for string disequality processing
  src/theory/strings/theory_strings.cpp
  test/regress/regress1/strings/Makefile.am
  test/regress/regress1/strings/goodAI.smt2
Labels: major, simple

#1648 More rewrites for indexof
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
Labels: moderate, normal

#1681 Add bit-vector extract example.
  examples/api/bitvectors.cpp
Labels: normal, simple

#1683 Fix 'make regress'
  test/regress/Makefile.am
Labels: major, simple

#1703 Enable post-condition strenghtening by default for non-syntax restricted invariant synthesis
  src/options/quantifiers_options.toml
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.h
Labels: normal, simple

#1701 Minor reorganization for ematching
  src/Makefile.am
  src/theory/quantifiers/ematching/candidate_generator.cpp
  src/theory/quantifiers/ematching/candidate_generator.h
  src/theory/quantifiers/ematching/inst_match_generator.cpp
  src/theory/quantifiers/ematching/inst_match_generator.h
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/ematching/trigger.h
Labels: minor, simple

#1700 Remove unused code
  src/Makefile.am
  src/options/quantifiers_options.toml
  src/options/uf_options.toml
  src/theory/quantifiers/fun_def_engine.cpp
  src/theory/quantifiers/fun_def_engine.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/quant_equality_engine.cpp
  src/theory/quantifiers/quant_equality_engine.h
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers/term_util.cpp
  src/theory/quantifiers/term_util.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  src/theory/uf/theory_uf_strong_solver.cpp
  src/theory/uf/theory_uf_strong_solver.h
Labels: minor, simple

#1702 Add a few quantifiers regressions to improve coverage
  test/regress/Makefile.tests
  test/regress/regress1/fmf/Hoare-z3.931718.smt
  test/regress/regress1/fmf/nlp042+1.smt2
  test/regress/regress1/quantifiers/inst-prop-simp.smt2
  test/regress/regress1/quantifiers/smtlibe99bbe.smt2
Labels: minor, simple

#1696 Remove doc/libcvc4.3 from options/Makefile.am.
  src/options/Makefile.am
Labels: bug, major, simple

#1692 Cleanup various exit calls
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/quantifiers/fmf/ambqi_builder.cpp
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/quantifiers/fun_def_process.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/uf/theory_uf_strong_solver.cpp
Labels: normal, simple

#1694 Check model only when sat
  src/smt/smt_engine.cpp
Labels: minor, simple

#1712 Rewrites for substr of strings of length one
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
  test/unit/Makefile.am
  test/unit/theory/theory_strings_rewriter_white.h
Labels: moderate, normal

#1717 Abort when sygus-verify finds unsoundness.
  src/options/quantifiers_options.toml
  src/theory/datatypes/datatypes_sygus.cpp
Labels: normal, simple

#1691 Synth-check and accelerate options for sygus-rr
  src/options/quantifiers_options.toml
  src/theory/quantifiers/sygus/ce_guided_conjecture.cpp
Labels: moderate, normal

#1709 Make Java bindings work with newer build envs
  config/bindings.m4
  src/bindings/Makefile.am
  src/bindings/compat/java/Makefile.am
  src/bindings/compat/java/create_impl.py
Labels: major, normal

#1710 Fix memory leak in bvminisat
  src/prop/bvminisat/bvminisat.cpp
  src/prop/bvminisat/bvminisat.h
Labels: minor, simple

#1711 Add support for filtering regressions with regex
  test/regress/Makefile.levels
Labels: normal, simple

#1714 Regression level 0 for distcheck on Travis
  .travis.yml
Labels: minor, simple

#1677 Documentation and simplifications for PBE
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/sygus/sygus_pbe.h
Labels: normal, simple

#1719 Better normalization of string concatenation
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
  test/unit/theory/theory_strings_rewriter_white.h
Labels: moderate, normal

#1682 Filter candidate rewrites based on matching
  src/theory/quantifiers/dynamic_rewrite.cpp
  src/theory/quantifiers/dynamic_rewrite.h
  src/theory/quantifiers/sygus_sampler.cpp
  src/theory/quantifiers/sygus_sampler.h
Labels: moderate, normal

#1720 Make sygus unif utility
  src/Makefile.am
  src/theory/quantifiers/sygus/sygus_invariance.cpp
  src/theory/quantifiers/sygus/sygus_invariance.h
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/sygus/sygus_pbe.h
  src/theory/quantifiers/sygus/sygus_unif.cpp
  src/theory/quantifiers/sygus/sygus_unif.h
Labels: normal, simple

#1723 Fix for --sygus-rr-synth
  src/options/quantifiers_options.toml
  src/theory/quantifiers/sygus_sampler.cpp
Labels: major, simple

#1724 Make sygus pbe use sygus unif utility
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/sygus/sygus_pbe.h
  src/theory/quantifiers/sygus/sygus_unif.cpp
  src/theory/quantifiers/sygus/sygus_unif.h
Labels: normal, simple

#1726 Simplify sygus unif so that it is one-to-one with functions to synthesize
  src/theory/quantifiers/sygus/sygus_unif.cpp
  src/theory/quantifiers/sygus/sygus_unif.h
Labels: normal, simple

#1707 Do not use factoring inference for transcendental functions
  src/theory/arith/nonlinear_extension.cpp
  src/theory/arith/nonlinear_extension.h
Labels: normal, simple

#1730 Split strategy representation from SygusUnif
  src/Makefile.am
  src/theory/quantifiers/sygus/sygus_unif.cpp
  src/theory/quantifiers/sygus/sygus_unif.h
  src/theory/quantifiers/sygus/sygus_unif_strat.cpp
  src/theory/quantifiers/sygus/sygus_unif_strat.h
Labels: normal, simple

#1731 Disable datatype dump regression
  test/regress/Makefile.tests
Labels: major, simple
