Repository cvc5/cvc5, pull requests merged in 2018-10, with the labels that each got.

#2468 Refactor preprocessing pass registration
  src/preprocessing/passes/apply_substs.cpp
  src/preprocessing/passes/apply_to_const.cpp
  src/preprocessing/passes/bool_to_bv.cpp
  src/preprocessing/passes/bv_abstraction.cpp
  src/preprocessing/passes/bv_ackermann.cpp
  src/preprocessing/passes/bv_eager_atoms.cpp
  src/preprocessing/passes/bv_gauss.cpp
  src/preprocessing/passes/bv_intro_pow2.cpp
  src/preprocessing/passes/bv_to_bool.cpp
  src/preprocessing/passes/extended_rewriter_pass.cpp
  src/preprocessing/passes/global_negate.cpp
  src/preprocessing/passes/int_to_bv.cpp
  src/preprocessing/passes/ite_removal.cpp
  src/preprocessing/passes/ite_simp.cpp
  src/preprocessing/passes/miplib_trick.cpp
  src/preprocessing/passes/nl_ext_purify.cpp
  src/preprocessing/passes/non_clausal_simp.cpp
  src/preprocessing/passes/pseudo_boolean_processor.cpp
  src/preprocessing/passes/quantifier_macros.cpp
  src/preprocessing/passes/quantifiers_preprocess.cpp
  src/preprocessing/passes/real_to_int.cpp
  src/preprocessing/passes/rewrite.cpp
  src/preprocessing/passes/sep_skolem_emp.cpp
  src/preprocessing/passes/sort_infer.cpp
  src/preprocessing/passes/sort_infer.h
  src/preprocessing/passes/static_learning.cpp
  src/preprocessing/passes/sygus_inference.cpp
  src/preprocessing/passes/symmetry_breaker.cpp
  src/preprocessing/passes/symmetry_detect.cpp
  src/preprocessing/passes/synth_rew_rules.cpp
  src/preprocessing/passes/theory_preprocess.cpp
  src/preprocessing/passes/unconstrained_simplifier.cpp
  src/preprocessing/preprocessing_pass_registry.cpp
  src/preprocessing/preprocessing_pass_registry.h
  src/smt/smt_engine.cpp
Labels: moderate, normal

#2469 Fix dumping pre/post preprocessing passes
  src/preprocessing/preprocessing_pass.cpp
  src/smt/dump.cpp
  src/smt/smt_engine.cpp
Labels: normal, simple

#2555 Fix compiler warnings.
  src/prop/bvminisat/core/Solver.cc
  src/prop/bvminisat/simp/SimpSolver.cc
  src/prop/minisat/core/Solver.cc
  src/prop/minisat/simp/SimpSolver.cc
  src/theory/arith/constraint.cpp
Labels: normal, simple

#2554 init scalar class members (coverity issues 1473720 and 1473721)
  src/theory/quantifiers/sygus/enum_stream_substitution.cpp
Labels: normal, simple

#2558 cmake: Add build target build-tests to build all test dependencies.
  CMakeLists.txt
  test/CMakeLists.txt
  test/java/CMakeLists.txt
  test/regress/CMakeLists.txt
  test/system/CMakeLists.txt
  test/unit/CMakeLists.txt
Labels: major, simple

#2559 cmake: Generate compile_commands.json on configure.
  CMakeLists.txt
Labels: normal, simple

#2556 Fix "catching polymorphic type by value" warnings
  test/unit/context/cdlist_black.h
  test/unit/context/cdmap_black.h
  test/unit/context/cdmap_white.h
  test/unit/context/context_black.h
  test/unit/context/context_mm_black.h
  test/unit/expr/expr_manager_public.h
  test/unit/expr/expr_public.h
  test/unit/expr/kind_map_black.h
  test/unit/expr/node_black.h
  test/unit/expr/node_builder_black.h
  test/unit/expr/node_manager_black.h
  test/unit/expr/node_manager_white.h
  test/unit/expr/symbol_table_black.h
  test/unit/theory/logic_info_white.h
  test/unit/theory/type_enumerator_white.h
  test/unit/util/array_store_all_black.h
  test/unit/util/assert_white.h
  test/unit/util/bitvector_black.h
  test/unit/util/boolean_simplification_black.h
  test/unit/util/cardinality_public.h
  test/unit/util/datatype_black.h
  test/unit/util/integer_black.h
Labels: normal, simple

#2562 cmake: Add examples to build-tests, warning for disabling static build.
  CMakeLists.txt
  test/CMakeLists.txt
Labels: major, simple

#2564 Make registration of preprocessing passes explicit
  src/preprocessing/passes/apply_substs.cpp
  src/preprocessing/passes/apply_to_const.cpp
  src/preprocessing/passes/bool_to_bv.cpp
  src/preprocessing/passes/bv_abstraction.cpp
  src/preprocessing/passes/bv_ackermann.cpp
  src/preprocessing/passes/bv_eager_atoms.cpp
  src/preprocessing/passes/bv_gauss.cpp
  src/preprocessing/passes/bv_intro_pow2.cpp
  src/preprocessing/passes/bv_to_bool.cpp
  src/preprocessing/passes/extended_rewriter_pass.cpp
  src/preprocessing/passes/global_negate.cpp
  src/preprocessing/passes/int_to_bv.cpp
  src/preprocessing/passes/ite_removal.cpp
  src/preprocessing/passes/ite_simp.cpp
  src/preprocessing/passes/miplib_trick.cpp
  src/preprocessing/passes/nl_ext_purify.cpp
  src/preprocessing/passes/non_clausal_simp.cpp
  src/preprocessing/passes/pseudo_boolean_processor.cpp
  src/preprocessing/passes/quantifier_macros.cpp
  src/preprocessing/passes/quantifiers_preprocess.cpp
  src/preprocessing/passes/real_to_int.cpp
  src/preprocessing/passes/rewrite.cpp
  src/preprocessing/passes/sep_skolem_emp.cpp
  src/preprocessing/passes/sort_infer.cpp
  src/preprocessing/passes/static_learning.cpp
  src/preprocessing/passes/sygus_inference.cpp
  src/preprocessing/passes/symmetry_breaker.cpp
  src/preprocessing/passes/synth_rew_rules.cpp
  src/preprocessing/passes/theory_preprocess.cpp
  src/preprocessing/passes/unconstrained_simplifier.cpp
  src/preprocessing/preprocessing_pass_registry.cpp
  src/preprocessing/preprocessing_pass_registry.h
Labels: major, simple

#2561 unit: Fix ASAN detection for GCC.
  test/unit/memory.h
Labels: normal, simple

#2566 Allow (_ to_fp ...) in strict parsing mode
  src/parser/smt2/smt2.cpp
  test/regress/CMakeLists.txt
  test/regress/Makefile.tests
  test/regress/regress0/parser/to_fp.smt2
Labels: minor, simple

#2567 cmake: Display skipped tests as not run
  test/regress/CMakeLists.txt
  test/regress/run_regression.py
Labels: normal, simple

#2570 Eliminate partial operators within lambdas during grammar normalization
  src/theory/quantifiers/sygus/sygus_grammar_norm.cpp
  src/theory/quantifiers/sygus/sygus_grammar_norm.h
  test/regress/CMakeLists.txt
  test/regress/Makefile.tests
  test/regress/regress2/sygus/multi-udiv.sy
Labels: major, moderate

#2572 Fix stale op list in sets
  src/theory/sets/theory_sets_private.cpp
  test/regress/CMakeLists.txt
  test/regress/Makefile.tests
  test/regress/regress1/sets/issue2568.smt2
Labels: major, simple

#2565 Make CegisUnif with condition independent robust to var agnostic
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/cegis_unif.h
Labels: normal, simple

#2552 Add actively generated sygus enumerators
  src/options/quantifiers_options.toml
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/datatypes/datatypes_sygus.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/cegis.h
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/enum_stream_substitution.cpp
  src/theory/quantifiers/sygus/enum_stream_substitution.h
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/term_database_sygus.cpp
Labels: moderate, normal

#2575 Fix set regression option
  test/regress/regress1/sets/issue2568.smt2
Labels: major, simple

#2573 Simplify datatypes printing
  src/expr/datatype.cpp
  src/expr/datatype.h
Labels: normal, simple

#2589 Fix mem leak in sets_translate example.
  examples/sets-translate/sets_translate.cpp
Labels: major, simple

#2588 Fix mem leak in sha1_collision example.
  examples/hashsmt/sha1_collision.cpp
Labels: major, simple

#2500 Clean remaining references to getNextDecisionRequest and simplify
  src/theory/builtin/kinds
  src/theory/decision_manager.cpp
  src/theory/decision_manager.h
  src/theory/mktheorytraits
  src/theory/strings/kinds
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: moderate, normal

#2571 Fix end constraint for regexp elimination
  src/theory/strings/regexp_elim.cpp
  test/regress/CMakeLists.txt
  test/regress/Makefile.tests
  test/regress/regress1/strings/nt6-dd.smt2
Labels: do not merge, major, moderate

#2519 New C++ API: Add checks for Sorts.
  examples/api/bitvectors-new.cpp
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/expr/type.cpp
  src/expr/type.h
  src/expr/type_node.cpp
  src/options/options.h
  test/unit/CMakeLists.txt
  test/unit/api/CMakeLists.txt
  test/unit/api/api_guards_black.h
Labels: normal, simple

#2591 Fix candidate rewrite rule filtering
  src/theory/quantifiers/candidate_rewrite_database.cpp
Labels: normal, simple

#2586 Update default options for sygus
  src/options/quantifiers_options.toml
  src/smt/smt_engine.cpp
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  test/regress/regress0/sygus/check-generic-red.sy
  test/regress/regress1/sygus/array_search_5-Q-easy.sy
  test/regress/regress1/sygus/car_3.lus.sy
  test/regress/regress1/sygus/clock-inc-tuple.sy
  test/regress/regress1/sygus/commutative-stream.sy
  test/regress/regress1/sygus/logiccell_help.sy
  test/regress/regress1/sygus/sygus-dt.sy
Labels: normal, simple

#2592 Fix cache for sygus post-condition inference
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.h
  test/regress/CMakeLists.txt
  test/regress/Makefile.tests
  test/regress/regress1/sygus/inv-missed-sol-true.sy
Labels: normal, simple

#2550 Fix unif trace
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/cegis_unif.cpp
Labels: minor, simple

#2594 Disable extended rewriter when applicable with var agnostic enumeration
  src/theory/quantifiers/sygus/enum_stream_substitution.cpp
Labels: normal, simple

#2598 Address slow sygus regressions
  test/regress/CMakeLists.txt
  test/regress/Makefile.tests
  test/regress/regress2/sygus/vcb.sy
  test/regress/regress3/sixfuncs.sy
Labels: major, simple

#2597 Fix string register extended terms
  src/theory/ext_theory.cpp
  src/theory/strings/theory_strings.cpp
Labels: major, simple

#2603 BV inverter: Factor out util functions.
  src/CMakeLists.txt
  src/Makefile.am
  src/theory/quantifiers/bv_inverter.cpp
  src/theory/quantifiers/bv_inverter_utils.cpp
  src/theory/quantifiers/bv_inverter_utils.h
  test/unit/theory/theory_quantifiers_bv_inverter_white.h
Labels: major, simple

#2604 BV instantiator: Factor out util functions.
  src/CMakeLists.txt
  src/Makefile.am
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_bv_instantiator_utils.cpp
  src/theory/quantifiers/cegqi/ceg_bv_instantiator_utils.h
  test/unit/theory/theory_quantifiers_bv_instantiator_white.h
Labels: major, simple

#2601 Fix compiler warnings.
  src/api/cvc4cpp.cpp
  src/smt/smt_engine.cpp
Labels: normal, simple

#2593 Allow multiple synthesis conjectures.
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus/synth_engine.h
Labels: moderate, normal

#2595 Random: support URNG interface
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.cpp
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching.cpp
  src/theory/quantifiers/sygus/sygus_unif.cpp
  src/theory/quantifiers/sygus/sygus_unif_io.cpp
  src/util/random.cpp
  src/util/random.h
Labels: normal, simple

#2606 Support for basic actively-generated enumerators
  src/options/options_handler.cpp
  src/options/options_handler.h
  src/options/quantifiers_modes.h
  src/options/quantifiers_options.toml
  src/theory/datatypes/datatypes_rewriter.h
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.h
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/sygus_module.h
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/sygus/sygus_pbe.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus/synth_engine.h
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
  test/regress/regress1/sygus/trivial-stream.sy
Labels: moderate, normal

#2610 Add length-based rewrites for (str.substr _ _ _)
  src/theory/strings/theory_strings_rewriter.cpp
  test/unit/theory/theory_strings_rewriter_white.h
Labels: normal, simple

#2612 Optimize regular expression elimination
  src/theory/strings/regexp_elim.cpp
  test/regress/CMakeLists.txt
  test/regress/Makefile.tests
  test/regress/regress2/strings/non_termination_regular_expression6.smt2
Labels: moderate, normal

#2614 Fix cegis so that evaluation unfolding is not interleaved with candidate checking
  src/theory/quantifiers/sygus/cegis.cpp
Labels: normal, simple

#2608 Synthesize rewrite rules from inputs
  src/expr/datatype.cpp
  src/expr/datatype.h
  src/options/quantifiers_options.toml
  src/options/smt_options.toml
  src/preprocessing/passes/synth_rew_rules.cpp
  src/preprocessing/passes/synth_rew_rules.h
  src/smt/smt_engine.cpp
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/quantifiers/candidate_rewrite_database.cpp
  src/theory/quantifiers/expr_miner.cpp
  src/theory/quantifiers/sygus/cegis_unif.h
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.h
  src/theory/quantifiers/sygus/sygus_grammar_norm.cpp
Labels: moderate, normal

#2602 Fix compiler warnings
  src/expr/datatype.cpp
  src/theory/quantifiers/sygus/cegis_unif.h
  src/theory/strings/theory_strings.h
Labels: minor, simple

#2605 Fix default setting of CegisUnif options
  src/options/quantifiers_options.toml
  src/smt/smt_engine.cpp
Labels: minor, simple

#2618 Fix string ext inference for rewrites that introduce negation
  src/theory/strings/theory_strings.cpp
  test/regress/CMakeLists.txt
  test/regress/Makefile.tests
  test/regress/regress1/strings/timeout-no-resp.smt2
Labels: major, simple

#2620 Fix partial operator elimination in sygus grammar normalization
  src/theory/quantifiers/sygus/sygus_grammar_norm.cpp
Labels: major, simple

#2615 Improve reasoning about empty strings in rewriter
  src/theory/strings/theory_strings_rewriter.cpp
  test/unit/theory/theory_strings_rewriter_white.h
Labels: moderate, normal

#2609 Refactor printing of parameterized operators in smt2
  src/printer/smt2/smt2_printer.cpp
Labels: normal, simple

#2622 Fix heuristic for string length approximation
  src/theory/strings/theory_strings_rewriter.cpp
Labels: moderate, normal

#2625 Improvements to rewrite rules from inputs
  src/expr/node_algorithm.cpp
  src/expr/node_algorithm.h
  src/options/quantifiers_options.toml
  src/preprocessing/passes/synth_rew_rules.cpp
  src/theory/quantifiers/candidate_rewrite_filter.cpp
  src/theory/quantifiers/sygus_sampler.cpp
  src/theory/quantifiers/sygus_sampler.h
Labels: moderate, normal

#2624 Reset input language for ExprMiner subsolver
  src/options/quantifiers_options.toml
  src/smt/smt_engine.cpp
  src/theory/quantifiers/expr_miner.cpp
  test/regress/CMakeLists.txt
  test/regress/Makefile.tests
  test/regress/regress1/rr-verify/fp-arith.sy
  test/regress/regress1/rr-verify/fp-bool.sy
Labels: major, simple

#2631 Fix fp-bool.sy grammar and require symfpu
  test/regress/regress1/rr-verify/fp-arith.sy
  test/regress/regress1/rr-verify/fp-bool.sy
Labels: major, simple

#2628 Add more (str.replace x y z) rewrites
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
  test/unit/theory/theory_strings_rewriter_white.h
Labels: moderate, normal

#2621 Delay initialization of theory engine
  src/options/options_handler.cpp
  src/smt/smt_engine.cpp
  test/unit/prop/cnf_stream_white.h
  test/unit/theory/theory_arith_white.h
  test/unit/theory/theory_bv_white.h
  test/unit/theory/theory_engine_white.h
  test/unit/theory/theory_white.h
Labels: moderate, normal

#2640 cmake: Generate git_versioninfo.cpp at build time.
  src/CMakeLists.txt
  src/base/CMakeLists.txt
  src/base/GitInfo.cmake.in
Labels: major, simple

#2587 Option for shuffling condition pool in CegisUnif
  src/options/quantifiers_options.toml
  src/theory/quantifiers/sygus/sygus_unif_rl.cpp
  src/theory/quantifiers/sygus/sygus_unif_rl.h
Labels: normal, simple

#2629 Improve reduction for int.to.str
  src/theory/strings/theory_strings_preprocess.cpp
Labels: moderate, normal

#2642 cmake: Add CxxTest include directory to unit test includes.
  test/unit/CMakeLists.txt
Labels: bug, simple

#2643 BV rewrites (mined): Rule 35: ConcatPullUp (BITVECTOR_OR) with special const.
  src/theory/bv/theory_bv_rewrite_rules.h
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
  src/theory/bv/theory_bv_rewriter.cpp
Labels: normal, simple

#2644 Fix context-dependent for positive contains reduction
  src/theory/strings/theory_strings.cpp
Labels: major, simple

#2465 Sygus query generator
  src/CMakeLists.txt
  src/Makefile.am
  src/options/quantifiers_options.toml
  src/smt/smt_engine.cpp
  src/theory/quantifiers/expr_miner_manager.cpp
  src/theory/quantifiers/expr_miner_manager.h
  src/theory/quantifiers/query_generator.cpp
  src/theory/quantifiers/query_generator.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
Labels: moderate, normal

#2646 Constant length regular expression elimination
  src/theory/strings/regexp_elim.cpp
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
  test/regress/CMakeLists.txt
  test/regress/regress2/strings/issue918.smt2
Labels: moderate, normal

#2627 Introducing internal commands for SyGuS commands
  src/bindings/java/CMakeLists.txt
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/smt/command.cpp
  src/smt/command.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
Labels: moderate, normal

#2636 Improve reduction for str.to.int
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/theory_strings_preprocess.h
  test/regress/CMakeLists.txt
  test/regress/Makefile.tests
  test/regress/regress1/strings/stoi-400million.smt2
Labels: moderate, normal

#2652 Non-contributing find replace rewrite
  src/theory/strings/theory_strings_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/ncontrib-rewrites.smt2
Labels: moderate, normal

#2466 Add OptionException handling during initialization
  src/options/CMakeLists.txt
  src/options/Makefile.am
  src/options/option_exception.cpp
  src/options/option_exception.h
  src/options/options_template.cpp
  src/smt/smt_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/Makefile.tests
  test/regress/regress0/options/invalid_dump.smt2
Labels: moderate, normal

#2654 Add helper to detect length one string terms
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
  test/unit/theory/theory_strings_rewriter_white.h
Labels: normal, simple

#2655 Fix util::Random for macOS builds
  src/util/random.h
Labels: major, simple

#2660 Sygus streaming non-implied predicates
  src/CMakeLists.txt
  src/options/quantifiers_options.toml
  src/smt/smt_engine.cpp
  src/theory/quantifiers/expr_miner_manager.cpp
  src/theory/quantifiers/expr_miner_manager.h
  src/theory/quantifiers/solution_filter.cpp
  src/theory/quantifiers/solution_filter.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus/synth_engine.h
Labels: moderate, normal

#2663 Travis: run examples and avoid building them twice
  .travis.yml
Labels: minor, simple

#2662 Disable dumping test for non-dumping builds
  test/regress/regress0/options/invalid_dump.smt2
Labels: major, simple

#2664 Remove antlr_undefines.h.
  cmake/ConfigureCVC4.cmake
  cvc4autoconfig.h.in
  src/base/configuration.cpp
  src/parser/CMakeLists.txt
  src/parser/antlr_input.cpp
  src/parser/antlr_input.h
  src/parser/antlr_input_imports.cpp
  src/parser/antlr_line_buffered_input.cpp
  src/parser/antlr_line_buffered_input.h
  src/parser/antlr_undefines.h
  src/parser/cvc/Cvc.g
  src/parser/cvc/cvc_input.cpp
  src/parser/smt1/Smt1.g
  src/parser/smt1/smt1_input.cpp
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2_input.cpp
  src/parser/smt2/sygus_input.cpp
  src/parser/tptp/Tptp.g
  src/parser/tptp/tptp_input.cpp
Labels: minor, simple

#2667 Recover from wrong use of get-info :reason-unknown
  src/smt/command.cpp
  src/smt/smt_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/smtlib/reason-unknown.smt2
Labels: normal, simple

#2657 Only build CryptoMiniSat library, no binary
  cmake/FindCryptoMiniSat.cmake
  contrib/get-cryptominisat
Labels: normal, simple

#2666 CMake: Set PORTFOLIO_BUILD when building pcvc4
  src/main/CMakeLists.txt
  src/main/driver_unified.cpp
Labels: normal, simple

#2671 CMake: Set RPATH on installed binary
  CMakeLists.txt
Labels: normal, simple

#2675 Minor improvement to sygus trace
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
Labels: minor, simple

#2678 Record assumption info in AssertionPipeline
  src/preprocessing/assertion_pipeline.cpp
  src/preprocessing/assertion_pipeline.h
  src/smt/smt_engine.cpp
Labels: moderate, normal
