Repository cvc5/cvc5, pull requests merged in 2018-08, with the labels that each got.

#2239 Remove hasAssertions() method from eager BV solver.
  src/theory/bv/bv_eager_solver.cpp
  src/theory/bv/bv_eager_solver.h
  src/theory/bv/theory_bv.cpp
Labels: major, simple

#2236 Make candidate rewrite match filtering handle polymorphic operators properly
  src/theory/quantifiers/candidate_rewrite_filter.cpp
  src/theory/quantifiers/candidate_rewrite_filter.h
  src/theory/quantifiers/dynamic_rewrite.cpp
  src/theory/quantifiers/dynamic_rewrite.h
Labels: minor, moderate

#2172 Make conjecture generator's uf term enumeration safer
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/conjecture_generator.h
Labels: moderate, normal

#2246 Fix assertion in conjecture generator
  src/theory/quantifiers/conjecture_generator.cpp
Labels: major, simple

#2243 New C++ API: Fixed ownership of options object.
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
Labels: normal, simple

#2244 InteractiveShell: Remove redundant options argument.
  src/main/driver_unified.cpp
  src/main/interactive_shell.cpp
  src/main/interactive_shell.h
  test/unit/main/interactive_shell_black.h
Labels: normal, simple

#2251 Fix bool-to-bv preprocessing pass for non-{bv,bool} equalities.
  src/preprocessing/passes/bool_to_bv.cpp
Labels: major, simple

#2252 Fix wrong evaluation of STRING_STOI
  src/theory/evaluator.cpp
Labels: normal, simple

#2213 Fix issues with printing parametric datatypes in smt2
  src/expr/expr_manager_template.cpp
  src/expr/expr_manager_template.h
  src/expr/node_manager.cpp
  src/expr/node_manager.h
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/Smt2.g
  src/printer/smt2/smt2_printer.cpp
  src/smt/smt_engine.cpp
Labels: moderate, normal

#2245 Remove outdated references to TLS
  AUTHORS
  contrib/depgraph
  src/base/configuration.cpp
  src/base/configuration.h
  src/base/configuration_private.h
  src/options/options_handler.cpp
  src/smt/smt_engine_scope.cpp
Labels: minor, simple

#2247 Improvements and fixes in cegqi arithmetic
  src/theory/quantifiers/cegqi/ceg_arith_instantiator.cpp
  test/regress/Makefile.tests
  test/regress/regress1/quantifiers/RND_4_1-existing-inst.smt2
  test/regress/regress1/quantifiers/repair-const-nterm.smt2
Labels: moderate, normal

#2248 Fix ExprManager call for regular expressions
  src/expr/expr_manager_template.cpp
Labels: major, simple

#2250 Remove Subversion build info
  src/Makefile.am
  src/base/configuration.cpp
  src/base/configuration.h
  src/main/driver_unified.cpp
  src/options/options_handler.cpp
Labels: minor, simple

#2258 Remove references to deprecated propagate as decision feature
  src/prop/minisat/core/Solver.cc
  src/theory/theory_engine.h
  src/theory/uf/theory_uf_strong_solver.cpp
Labels: minor, simple

#2259 Add rewrites for BV ITE and BV COMP with const condition/child.
  src/theory/bv/theory_bv_rewrite_rules.h
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
  src/theory/bv/theory_bv_rewriter.cpp
  src/theory/bv/theory_bv_utils.cpp
Labels: major, simple

#2255 Make strings robust to regular expression variables.
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings_rewriter.cpp
Labels: major, simple

#2256 Fix candidate rewrite utilities for non-first-class types
  src/theory/quantifiers/candidate_rewrite_filter.cpp
  src/theory/quantifiers/dynamic_rewrite.cpp
Labels: normal, simple

#2254 Improve CEGQI heuristics involving equality and multiple instantiations
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.h
  src/theory/quantifiers/cegqi/ceg_dt_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_dt_instantiator.h
  src/theory/quantifiers/cegqi/ceg_epr_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_epr_instantiator.h
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.h
  test/regress/regress1/quantifiers/nra-interleave-inst.smt2
Labels: moderate, normal

#2257 Parse standard separation logic inputs
  src/parser/smt2/Smt2.g
  test/regress/Makefile.tests
  test/regress/regress0/sep/dispose-1.smt2
  test/regress/regress0/sep/dup-nemp.smt2
  test/regress/regress0/sep/nemp.smt2
  test/regress/regress0/sep/sep-simp-unsat-emp.smt2
  test/regress/regress0/sep/skolem_emp.smt2
  test/regress/regress0/sep/trees-1.smt2
  test/regress/regress0/sep/wand-crash.smt2
  test/regress/regress1/sep/emp2-quant-unsat.smt2
  test/regress/regress1/sep/finite-witness-sat.smt2
  test/regress/regress1/sep/fmf-nemp-2.smt2
  test/regress/regress1/sep/quant_wand.smt2
  test/regress/regress1/sep/sl-standard.smt2
  test/regress/regress1/sep/split-find-unsat-w-emp.smt2
  test/regress/regress1/sep/wand-0526-sat.smt2
  test/regress/regress1/sep/wand-nterm-simp.smt2
  test/regress/regress1/sep/wand-nterm-simp2.smt2
  test/regress/regress1/sep/wand-simp-unsat.smt2
Labels: normal, simple

#2265 Add timer for BV inequality solver.
  src/theory/bv/bv_subtheory_algebraic.cpp
  src/theory/bv/bv_subtheory_inequality.cpp
  src/theory/bv/bv_subtheory_inequality.h
Labels: normal, simple

#2267 Fix printing statistics in case of signals.
  src/util/statistics.cpp
Labels: normal, simple

#2262 Eliminate option for sygus UF evaluation functions
  src/expr/datatype.cpp
  src/expr/datatype.h
  src/options/datatypes_options.toml
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/datatypes_rewriter.h
  src/theory/quantifiers/sygus/sygus_eval_unfold.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/sygus/sygus_repair_const.cpp
  src/theory/quantifiers/sygus/sygus_unif_rl.cpp
  src/theory/quantifiers/sygus/sygus_unif_strat.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
Labels: normal, simple

#2268 Add rewrite for BITVECTOR_ITE with term_then == term_else.
  src/theory/bv/theory_bv_rewrite_rules.h
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
  src/theory/bv/theory_bv_rewriter.cpp
Labels: normal, simple

#2271 Add rewrite for BITVECTOR_ITE with const children.
  src/theory/bv/theory_bv_rewrite_rules.h
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
  src/theory/bv/theory_bv_rewriter.cpp
  src/theory/bv/theory_bv_utils.cpp
  src/theory/bv/theory_bv_utils.h
Labels: normal, simple

#2272 Add rewrite for nested BITVECTOR_ITE with cond_outer == cond_inner.
  src/theory/bv/theory_bv_rewrite_rules.h
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
  src/theory/bv/theory_bv_rewriter.cpp
Labels: normal, simple

#2260 Fix degenerate case of sygus grammar construction for 0-argument Bools
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  test/regress/Makefile.tests
  test/regress/regress1/sygus/constant-dec-tree-bug.sy
Labels: normal, simple

#2261 Fixes and improvements for single invocation inference
  src/theory/quantifiers/single_inv_partition.cpp
  src/theory/quantifiers/single_inv_partition.h
  test/regress/Makefile.tests
  test/regress/regress1/sygus/constant-bool-si-all.sy
Labels: normal, simple

#2238 Fixes for sygus inference
  src/smt/smt_engine.cpp
  src/theory/quantifiers/sygus_inference.cpp
Labels: minor, simple

#2264 Remove support for Enum sygus syntax
  src/parser/smt2/Smt2.g
  test/regress/regress1/sygus/enum-test.sy
Labels: minor, simple

#2269 Move sygus quantifier elimination step for non-ground-single-invocation to sygus
  src/smt/smt_engine.cpp
  src/theory/quantifiers/sygus/ce_guided_instantiation.cpp
Labels: minor, simple

#2276 Add RegLan to smt2/sygus parsers
  src/parser/smt2/smt2.cpp
  test/regress/Makefile.tests
  test/regress/regress1/sygus/simple-regexp.sy
Labels: normal, simple

#2277 Make flat form inferences optional in strings
  src/options/strings_options.toml
  src/theory/strings/theory_strings.cpp
Labels: minor, simple

#2280 Make output for flushInformation and safeFlushInformation consistent.
  src/util/statistics.cpp
  src/util/statistics_registry.h
Labels: minor, simple

#2237 Fix inference of pre and post conditions for non variable arguments.
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.h
  test/regress/Makefile.tests
  test/regress/regress0/quantifiers/horn-ground-pre-post.smt2
Labels: moderate, normal

#2282 Wait to do sygus qe preprocess until full effort check
  src/theory/quantifiers/sygus/ce_guided_instantiation.cpp
  src/theory/quantifiers/sygus/ce_guided_instantiation.h
Labels: major, simple

#1794 Delete functions instead of using CVC4_UNDEFINED
  .travis.yml
  config/bindings.m4
  src/api/cvc4cpp.h
  src/base/exception.h
  src/base/listener.h
  src/context/cdhashmap.h
  src/context/cdhashset.h
  src/context/cdinsert_hashmap.h
  src/context/cdlist.h
  src/context/cdo.h
  src/context/context.h
  src/expr/expr_manager_template.h
  src/expr/node_manager.h
  src/include/cvc4_public.h
  src/main/portfolio_util.h
  src/options/options.h
  src/parser/antlr_input.h
  src/parser/input.h
  src/printer/printer.h
  src/prop/bvminisat/bvminisat.h
  src/smt/smt_engine.h
  src/smt_util/boolean_simplification.h
  src/smt_util/lemma_channels.h
  src/theory/rewriter.h
  src/theory/theory.h
  src/util/bin_heap.h
  src/util/resource_manager.h
  src/util/statistics_registry.h
Labels: minor, simple

#2281 Fix simple reg exp consume rewrite
  src/theory/strings/theory_strings_rewriter.cpp
  test/regress/Makefile.tests
  test/regress/regress1/strings/re-unsound-080718.smt2
Labels: major, simple

#2233 Document/refactor datatypes sygus simple symmetry breaking
  src/Makefile.am
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/datatypes/datatypes_sygus.h
  src/theory/datatypes/sygus_simple_sym.cpp
  src/theory/datatypes/sygus_simple_sym.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
Labels: minor, moderate

#2266 Simplify and improve the sygus parser
  src/parser/smt2/Smt2.g
Labels: normal, simple

#2286 Do beta-reduction in expandDefinitions
  src/smt/smt_engine.cpp
Labels: major, simple

#2095 Move uf model code from uf to quantifiers
  src/theory/quantifiers/first_order_model.cpp
  src/theory/quantifiers/first_order_model.h
  src/theory/quantifiers/fmf/model_builder.cpp
  src/theory/quantifiers/fmf/model_builder.h
  src/theory/uf/theory_uf_model.cpp
  src/theory/uf/theory_uf_model.h
Labels: minor, moderate

#2287 Add debug test for sygus subcall verify calls.
  src/theory/quantifiers/sygus/ce_guided_conjecture.cpp
Labels: minor, simple

#2288 Disable argument relevance for sygus by default
  src/options/quantifiers_options.toml
  src/theory/quantifiers/sygus/sygus_process_conj.cpp
  test/regress/regress1/sygus/process-10-vars.sy
  test/regress/regress2/sygus/process-10-vars-2fun.sy
  test/regress/regress2/sygus/process-arg-invariance.sy
Labels: minor, simple

#2232 Proposal for adding map utility functions to CVC4.
  src/base/Makefile.am
  src/base/map_util.h
  src/context/cdhashmap.h
  src/theory/quantifiers/fmf/bounded_integers.cpp
  test/unit/Makefile.am
  test/unit/base/map_util_black.h
Labels: complex, normal

#2289 Fixing documentation nit from PR#2232.
  src/theory/quantifiers/fmf/bounded_integers.cpp
Labels: minor, simple

#2290 Fix documentation of regression tests
  test/regress/README.md
Labels: minor, simple

#2275 Fix char overflow issues in regular expression solver
  src/api/cvc4cpp.cpp
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/regexp_operation.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
  src/theory/strings/theory_strings_type_rules.h
  src/theory/strings/type_enumerator.h
  src/util/regexp.cpp
  src/util/regexp.h
  test/regress/Makefile.tests
  test/regress/regress1/strings/nterm-re-inter-sigma.smt2
Labels: complex, major

#2294 Fix portfolio command executor for changes from #2240.
  src/main/command_executor_portfolio.cpp
  src/main/command_executor_portfolio.h
  src/main/driver_unified.cpp
  src/main/portfolio_util.h
  src/util/channel.h
Labels: major, simple

#2295 Make attributes robust to static init orderings
  src/expr/attribute_internals.h
Labels: normal, simple

#2297 Removing support for T* and const T* attributes.
  src/expr/attribute.cpp
  src/expr/attribute.h
  src/expr/attribute_internals.h
  src/expr/attribute_unique_id.h
  test/unit/expr/attribute_black.h
Labels: complex, normal

#2301 Fix get-unsat-assumptions output
  src/smt/command.cpp
  src/util/utility.h
  test/regress/Makefile.tests
  test/regress/regress0/push-pop/bug821-check_sat_assuming.smt2
  test/regress/regress0/smtlib/get-unsat-assumptions.smt2
Labels: minor, simple

#2302 Fix dumping of get-unsat-assumptions
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
Labels: minor, simple

#2309 Make sort inference a preprocessing pass
  src/Makefile.am
  src/preprocessing/passes/sort_infer.cpp
  src/preprocessing/passes/sort_infer.h
  src/smt/smt_engine.cpp
  src/theory/sort_inference.cpp
  src/theory/sort_inference.h
  test/regress/Makefile.tests
  test/regress/regress0/fmf/sort-inf-int.smt2
  test/regress/regress1/fmf/ALG008-1.smt2
Labels: minor, moderate

#2312 Remove unused class DynamicArray
  src/util/Makefile.am
  src/util/dynamic_array.h
Labels: minor, simple

#2313 Remove unused tuple classes
  src/smt/smt_engine.cpp
  src/theory/arrays/array_info.h
  src/theory/arrays/theory_arrays.cpp
  src/theory/arrays/theory_arrays.h
  src/util/Makefile.am
  src/util/ntuple.h
Labels: minor, simple

#2292 Add contrib/get-gmp script.
  contrib/get-gmp
  contrib/get-win-dependencies
Labels: normal, simple

#2300 Removing attribute cleanups.
  src/expr/attribute.h
  src/expr/attribute_internals.h
  src/expr/node_manager.h
Labels: complex, normal

#2315 Switching an Assert to a CVC4_CHECK to test if it resolves CID 1459595.
  src/theory/quantifiers/fmf/ambqi_builder.cpp
Labels: normal, simple

#2316 Refactor apply2const
  src/Makefile.am
  src/preprocessing/passes/apply_to_const.cpp
  src/preprocessing/passes/apply_to_const.h
  src/smt/smt_engine.cpp
  test/regress/Makefile.tests
  test/regress/regress0/arith/apply2const-test.smt2
Labels: minor, simple

#2324 Refactor extended rewriter preprocessing pass
  src/Makefile.am
  src/preprocessing/passes/extended_rewriter_pass.cpp
  src/preprocessing/passes/extended_rewriter_pass.h
  src/smt/smt_engine.cpp
  test/regress/Makefile.tests
  test/regress/regress0/fp/ext-rew-test.smt2
  test/regress/regress0/nl/ext-rew-aggr-test.smt2
Labels: minor, simple

#2306 Minor fixes and improvement for sygus to builtin
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/datatypes_rewriter.h
Labels: minor, simple

#2311 Move node algorithms to separate file
  src/expr/Makefile.am
  src/expr/expr_template.cpp
  src/expr/node.cpp
  src/expr/node.h
  src/expr/node_algorithm.cpp
  src/expr/node_algorithm.h
  src/smt/term_formula_removal.cpp
  src/theory/arith/arith_static_learner.cpp
  src/theory/arith/nonlinear_extension.cpp
  src/theory/arith/theory_arith_private.cpp
  src/theory/arrays/theory_arrays.cpp
  src/theory/booleans/circuit_propagator.cpp
  src/theory/builtin/theory_builtin_rewriter.cpp
  src/theory/bv/bv_subtheory_algebraic.cpp
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv_rewrite_rules_normalization.h
  src/theory/quantifiers/cegqi/ceg_arith_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_dt_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_epr_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cbqi.cpp
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv_sol.cpp
  src/theory/quantifiers/term_util.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/substitutions.cpp
  src/theory/theory.cpp
  src/theory/theory_engine.cpp
Labels: moderate, normal

#1793 Refactor IteRemoval preprocessing pass
  src/Makefile.am
  src/preprocessing/passes/ite_removal.cpp
  src/preprocessing/passes/ite_removal.h
  src/preprocessing/preprocessing_pass.h
  src/preprocessing/preprocessing_pass_context.cpp
  src/preprocessing/preprocessing_pass_context.h
  src/smt/smt_engine.cpp
Labels: moderate, normal

#2320 Removing coverity warnings from theory_sep.cpp
  src/theory/sep/theory_sep.cpp
Labels: minor, simple

#2322 Make quantifiers-preprocess preprocessing pass
  src/Makefile.am
  src/preprocessing/passes/quantifiers_preprocess.cpp
  src/preprocessing/passes/quantifiers_preprocess.h
  src/smt/smt_engine.cpp
Labels: minor, simple

#2328 Adding support for bitvector SyGuS problems without grammars
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.h
Labels: normal, simple

#2327 Cleaning unnecessary timers/dumps in smt_engine
  src/smt/smt_engine.cpp
Labels: minor, simple

#2318 Refactor eager atoms preprocessing pass.
  src/Makefile.am
  src/preprocessing/passes/bv_eager_atoms.cpp
  src/preprocessing/passes/bv_eager_atoms.h
  src/smt/smt_engine.cpp
Labels: normal, simple

#2323 Eliminate partial operators in sygus grammar normalization
  src/smt/smt_engine.cpp
  src/theory/quantifiers/sygus/sygus_grammar_norm.cpp
  test/regress/Makefile.tests
  test/regress/regress1/sygus/bvudiv-by-2.sy
Labels: major, simple

#2329 Fix arithmetic division by zero in sygus repair constant module
  src/theory/quantifiers/sygus/sygus_repair_const.cpp
Labels: major, simple

#2331 Fix spurious warning in sort inference
  src/theory/sort_inference.cpp
  test/regress/Makefile.tests
  test/regress/regress1/fmf/sort-inf-int-real.smt2
  test/regress/regress1/fmf/sort-inf-int.smt2
Labels: minor, simple

#2307 Split sygus grammar to its own ANTLR grammar
  src/parser/smt2/Smt2.g
Labels: moderate, normal

#2330 Add sygus stream regressions
  test/regress/Makefile.tests
  test/regress/regress1/sygus/commutative-stream.sy
  test/regress/regress1/sygus/trivial-stream.sy
Labels: minor, simple

#2333 Remove miscellaneous unused code
  src/theory/quantifiers/equality_query.cpp
  src/theory/quantifiers/equality_query.h
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/quant_conflict_find.h
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
  src/theory/sets/theory_sets_rels.cpp
  src/theory/sets/theory_sets_rels.h
  src/theory/sets/theory_sets_rewriter.cpp
Labels: minor, simple

#2319 Remove support for flipDecision
  src/proof/proof_output_channel.cpp
  src/proof/proof_output_channel.h
  src/prop/minisat/core/Solver.cc
  src/prop/minisat/core/Solver.h
  src/prop/minisat/minisat.cpp
  src/prop/minisat/minisat.h
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/sat_solver.h
  src/theory/output_channel.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/theory_test_utils.h
  test/unit/theory/theory_engine_white.h
  test/unit/theory/theory_white.h
Labels: minor, simple

#2336 run-regress script: Exit with exit code > 0 on failure.
  test/regress/run_regression.py
Labels: normal, simple

#2326 Minor improvements to the interface for sygus sampler
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus_sampler.cpp
  src/theory/quantifiers/sygus_sampler.h
Labels: minor, simple

#2337 Add regressions that increase coverage
  test/regress/Makefile.tests
  test/regress/regress0/datatypes/data-nested-codata.smt2
  test/regress/regress1/quantifiers/arith-snorm.smt2
  test/regress/regress1/quantifiers/dump-inst-i.smt2
  test/regress/regress1/quantifiers/dump-inst.smt2
  test/regress/regress1/quantifiers/infer-arith-trigger-eq.smt2
  test/regress/regress1/quantifiers/quant-wf-int-ind.smt2
  test/regress/regress1/sygus/phone-1-long.sy
Labels: minor, simple

#2338 Remove support for prototype (non-sygus) synthesis
  src/parser/smt2/Smt2.g
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers/quantifiers_attributes.h
  src/theory/quantifiers/sygus/ce_guided_conjecture.cpp
  src/theory/quantifiers/sygus/ce_guided_conjecture.h
  src/theory/quantifiers/sygus/ce_guided_instantiation.cpp
  src/theory/quantifiers/theory_quantifiers.cpp
Labels: minor, simple

#2342 Remove disabled system test cvc3_george.
  test/system/Makefile.am
  test/system/cvc3_george.cpp
  test/system/cvc3_george.h
  test/system/cvc3_main.cpp
Labels: normal, simple

#2343 Fix initialization of d_smt in ValidityChecker for changes from #2240.
  src/compat/cvc3_compat.cpp
Labels: normal, simple

#2346 Use cbqi-full for sygus
  src/smt/smt_engine.cpp
  src/theory/quantifiers/sygus/ce_guided_instantiation.cpp
  test/regress/Makefile.tests
  test/regress/regress1/sygus/max2-bv.sy
Labels: major, simple

#2314 Add constexpr annotations to help coverity understand constant ...
  src/theory/bv/theory_bv.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv_sol.cpp
Labels: minor, simple

#2350 Move d_realAssertionsEnd from SmtEnginePrivate to AssertionPipeline.
  src/preprocessing/preprocessing_pass.cpp
  src/preprocessing/preprocessing_pass.h
  src/smt/smt_engine.cpp
Labels: major, simple

#2335 Makes the new row propagation system default
  src/options/arith_options.toml
  test/regress/regress0/nl/ext-rew-aggr-test.smt2
  test/regress/regress1/nl/metitarski-1025.smt2
  test/regress/regress1/nl/metitarski-3-4.smt2
Labels: major, simple

#2352 Warn and enable quantifiers when using sygus + logics with QF
  src/parser/smt2/smt2.cpp
Labels: normal, simple

#2351 Fix processing of nested Variable construct in sygus let bodies
  src/parser/smt2/smt2.cpp
  test/regress/Makefile.tests
  test/regress/regress1/sygus/abv.sy
  test/regress/regress1/sygus/let-bug-simp.sy
Labels: normal, simple

#2349 Fix invalid iterator comparisons
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/sets/theory_sets_private.cpp
Labels: minor, simple

#2345 Adds regression test for automatic generation of SyGuS BV grammars
  test/regress/Makefile.tests
  test/regress/regress0/sygus/hd-05-d1-prog-nogrammar.sy
Labels: minor, simple

#2353 Fix option for real2int regression.
  test/regress/regress1/arith/real2int-test.smt2
Labels: major, simple

#2356 Wrapping TheorySetsPrivate in a unique_ptr.
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
Labels: minor, moderate

#2253 Adding less consistency lemmas in bv-ackermann preprocessing pass
  src/preprocessing/passes/bv_ackermann.cpp
  src/preprocessing/passes/bv_ackermann.h
  test/regress/Makefile.tests
  test/regress/regress0/bv/ackermann1.smt2
  test/regress/regress0/bv/ackermann2.smt2
Labels: do not merge

#2358 More unused code elimination
  src/options/uf_options.toml
  src/theory/quantifiers/inst_match.cpp
  src/theory/quantifiers/inst_match.h
  src/theory/quantifiers/quant_relevance.cpp
  src/theory/quantifiers/quant_relevance.h
  src/theory/quantifiers/sygus/sygus_unif.cpp
  src/theory/quantifiers/sygus/sygus_unif.h
  src/theory/quantifiers_engine.cpp
  src/theory/uf/theory_uf_strong_solver.cpp
  src/theory/uf/theory_uf_strong_solver.h
Labels: minor, simple

#2354 More regressions that increase coverage
  test/regress/Makefile.tests
  test/regress/regress1/quantifiers/dump-inst-proof.smt2
  test/regress/regress1/quantifiers/lra-vts-inf.smt2
  test/regress/regress1/quantifiers/qe-partial.smt2
  test/regress/regress1/quantifiers/qe.smt2
Labels: minor, simple

#2361 Use "filename" instead of "name" in SmtEngine::setInfo()
  src/parser/tptp/Tptp.g
  src/smt/smt_engine.cpp
Labels: minor, simple

#2360 Refactor ITE simplification preprocessing pass.
  src/Makefile.am
  src/preprocessing/passes/ite_simp.cpp
  src/preprocessing/passes/ite_simp.h
  src/preprocessing/preprocessing_pass_context.h
  src/preprocessing/util/ite_utilities.cpp
  src/preprocessing/util/ite_utilities.h
  src/smt/smt_engine.cpp
  src/theory/arith/arith_ite_utils.cpp
  src/theory/arith/arith_ite_utils.h
  src/theory/arith/theory_arith_private.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: moderate, normal

#2364 Fix regression requiring proof build
  test/regress/regress1/quantifiers/dump-inst-proof.smt2
Labels: major, simple

#2357 Fixing some coverity warnings
  src/theory/quantifiers/ematching/inst_match_generator.cpp
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.h
  src/theory/quantifiers/sygus/sygus_invariance.h
  src/theory/quantifiers/sygus/sygus_unif_io.cpp
  src/theory/quantifiers/sygus/sygus_unif_io.h
  src/theory/quantifiers/sygus/sygus_unif_rl.h
  src/theory/quantifiers/sygus/sygus_unif_strat.h
  src/theory/strings/theory_strings.cpp
Labels: minor, simple

#2366 Makes the filename be set in the SMT engine by default
  src/main/command_executor.h
  src/main/driver_unified.cpp
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
Labels: minor, simple

#2362 Add missing overrides in unit tests
  test/unit/base/map_util_black.h
  test/unit/context/cdlist_black.h
  test/unit/context/cdmap_black.h
  test/unit/context/cdmap_white.h
  test/unit/context/cdo_black.h
  test/unit/context/context_black.h
  test/unit/context/context_mm_black.h
  test/unit/context/context_white.h
  test/unit/expr/attribute_black.h
  test/unit/expr/attribute_white.h
  test/unit/expr/expr_manager_public.h
  test/unit/expr/expr_public.h
  test/unit/expr/kind_black.h
  test/unit/expr/node_black.h
  test/unit/expr/node_builder_black.h
  test/unit/expr/node_manager_black.h
  test/unit/expr/node_manager_white.h
  test/unit/expr/node_self_iterator_black.h
  test/unit/expr/node_white.h
  test/unit/expr/symbol_table_black.h
  test/unit/expr/type_cardinality_public.h
  test/unit/expr/type_node_white.h
  test/unit/main/interactive_shell_black.h
  test/unit/parser/parser_black.h
  test/unit/parser/parser_builder_black.h
  test/unit/preprocessing/pass_bv_gauss_white.h
  test/unit/prop/cnf_stream_white.h
  test/unit/theory/evaluator_white.h
  test/unit/theory/theory_arith_white.h
  test/unit/theory/theory_black.h
  test/unit/theory/theory_bv_white.h
  test/unit/theory/theory_quantifiers_bv_instantiator_white.h
  test/unit/theory/theory_strings_rewriter_white.h
  test/unit/theory/theory_white.h
  test/unit/theory/type_enumerator_white.h
  test/unit/util/array_store_all_black.h
  test/unit/util/binary_heap_black.h
  test/unit/util/bitvector_black.h
  test/unit/util/datatype_black.h
  test/unit/util/exception_black.h
  test/unit/util/listener_black.h
  test/unit/util/output_black.h
Labels: minor, simple

#2369 New C++ API: Add checks for kind arguments.
  src/api/cvc4cpp.cpp
  src/api/cvc4cppkind.h
Labels: normal, simple

#2234 Do not print internally generated datatypes in external outputs with sygus
  src/expr/expr_manager_template.cpp
  src/expr/expr_manager_template.h
  src/expr/node_manager.h
  src/smt/smt_engine.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_grammar_norm.cpp
Labels: minor, moderate

#2344 Add tests that enumerate and verify rewrite rules
  src/theory/datatypes/datatypes_sygus.cpp
  test/regress/Makefile.tests
  test/regress/regress1/rr-verify/bool-crci.sy
  test/regress/regress1/rr-verify/bv-term-32.sy
  test/regress/regress1/rr-verify/bv-term.sy
  test/regress/regress1/rr-verify/string-term.sy
  test/regress/regress1/sygus/commutative-stream.sy
  test/regress/regress1/sygus/trivial-stream.sy
  test/regress/run_regression.py
Labels: minor, simple

#2368 Remove spurious disabling of cbqi-all
  src/smt/smt_engine.cpp
  test/regress/Makefile.tests
  test/regress/regress1/quantifiers/nl-pow-trick.smt2
Labels: minor, simple

#2372 Fix more simple coverity warnings
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cbqi.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cbqi.h
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/conjecture_generator.h
  src/theory/quantifiers/ematching/candidate_generator.cpp
  src/theory/quantifiers/first_order_model.cpp
  src/theory/quantifiers/first_order_model.h
  src/theory/quantifiers/fmf/model_builder.cpp
  src/theory/quantifiers/fmf/model_builder.h
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
Labels: minor, simple

#2371 Clean up quantifiers engine initialization.
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: minor, simple

#1840 Refactor quantifier macros preprocessing pass
  src/Makefile.am
  src/preprocessing/passes/quantifier_macros.cpp
  src/preprocessing/passes/quantifier_macros.h
  src/smt/smt_engine.cpp
  src/theory/quantifiers/macros.h
Labels: moderate, normal

#2374 Refactor unconstrained simplification pass
  src/Makefile.am
  src/preprocessing/passes/unconstrained_simplifier.cpp
  src/preprocessing/passes/unconstrained_simplifier.h
  src/preprocessing/preprocessing_pass.h
  src/preprocessing/preprocessing_pass_context.h
  src/smt/smt_engine.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: moderate, normal

#2381 Use uniform length limit for String constants
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/regexp_operation.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  src/theory/strings/theory_strings_rewriter.cpp
  src/util/regexp.cpp
Labels: major, simple

#2367 Make division chainable in the smt2 parser
  src/expr/expr_manager_template.cpp
  src/expr/expr_manager_template.h
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/Smt2.g
  test/regress/Makefile.tests
  test/regress/regress0/arith/div-chainable.smt2
Labels: moderate, normal

#1964 Resolution proof: separate printing from proof
  src/Makefile.am
  src/proof/bitvector_proof.cpp
  src/proof/bitvector_proof.h
  src/proof/lfsc_proof_printer.cpp
  src/proof/lfsc_proof_printer.h
  src/proof/proof_manager.cpp
  src/proof/proof_manager.h
  src/proof/sat_proof.h
  src/proof/sat_proof_implementation.h
Labels: moderate, normal

#2384 New C++ API: Fix isDefinedKind() to not be ambigious with respect to …
  src/api/cvc4cppkind.h
Labels: complex, normal

#2387 Refactor extended rewriter, move rewrites to aggressive
  src/theory/quantifiers/extended_rewrite.cpp
  src/theory/quantifiers/extended_rewrite.h
  test/regress/regress0/fp/ext-rew-test.smt2
Labels: major, moderate

#2389 Remove dead code in evaluator
  src/theory/evaluator.cpp
Labels: minor, simple

#2391 Fix warning for unused variable in sygus io
  src/theory/quantifiers/sygus/sygus_unif_io.cpp
Labels: minor, simple

#2394 Address more coverity warnings
  src/theory/datatypes/sygus_simple_sym.cpp
  src/theory/quantifiers/candidate_rewrite_database.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/conjecture_generator.h
  src/theory/quantifiers/ematching/candidate_generator.cpp
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/inst_propagator.cpp
  src/theory/quantifiers/sygus/sygus_unif_rl.h
Labels: minor, simple

#2393 Fix sort inference for quantified variables of interpreted types
  src/theory/sort_inference.cpp
  test/regress/Makefile.tests
  test/regress/regress0/fmf/sort-infer-typed-082718.smt2
Labels: major, simple

#2388 Remove dead code in fp_converter
  src/theory/fp/fp_converter.cpp
Labels: minor, simple

#2392 Remove throw specifiers in FP type checker
  src/theory/fp/theory_fp_type_rules.h
Labels: minor, simple

#2399 Fix for get constraints method in fmf-fun
  src/theory/quantifiers/fun_def_process.cpp
  src/theory/quantifiers/fun_def_process.h
  test/regress/Makefile.tests
  test/regress/regress1/fmf/fmf-fun-divisor-pp.smt2
Labels: major, moderate

#2398 Split term canonize utility to own file and document
  src/Makefile.am
  src/theory/quantifiers/alpha_equivalence.cpp
  src/theory/quantifiers/anti_skolem.cpp
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/conjecture_generator.h
  src/theory/quantifiers/term_canonize.cpp
  src/theory/quantifiers/term_canonize.h
  src/theory/quantifiers/term_util.cpp
  src/theory/quantifiers/term_util.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: minor, simple

#2365 Fix printing of total bitvectors operators for SMT-LIB 2.6
  src/printer/smt2/smt2_printer.cpp
Labels: minor, simple

#2370 Forcing attribute_internals.h to use uint64_t's for shift operations.
  src/expr/attribute_internals.h
Labels: moderate, normal

#2359 Refactor MipLibTrick preprocessing pass.
  src/Makefile.am
  src/preprocessing/passes/miplib_trick.cpp
  src/preprocessing/passes/miplib_trick.h
  src/preprocessing/preprocessing_pass_context.cpp
  src/preprocessing/preprocessing_pass_context.h
  src/smt/logic_request.cpp
  src/smt/logic_request.h
  src/smt/smt_engine.cpp
Labels: moderate, normal

#2400 Add regular expression elimination module
  src/Makefile.am
  src/options/strings_options.toml
  src/theory/strings/regexp_elim.cpp
  src/theory/strings/regexp_elim.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  src/theory/strings/theory_strings_rewriter.cpp
  test/regress/Makefile.tests
  test/regress/regress0/strings/rewrites-re-concat.smt2
  test/regress/regress1/strings/issue1684-regex.smt2
  test/regress/regress1/strings/non_termination_regular_expression4.smt2
  test/regress/regress1/strings/norn-13.smt2
  test/regress/regress1/strings/policy_variable.smt2
  test/regress/regress1/strings/re-elim-exact.smt2
Labels: moderate, normal

#2395 Refactor theory preprocess into preprocessing pass.
  src/Makefile.am
  src/preprocessing/passes/theory_preprocess.cpp
  src/preprocessing/passes/theory_preprocess.h
  src/smt/smt_engine.cpp
Labels: normal, simple

#2409 Fix export of bound variables
  src/expr/expr_template.cpp
Labels: normal, simple

#2412 Allows SAT checks of repair const to have different options
  src/options/quantifiers_options.toml
  src/theory/quantifiers/sygus/sygus_repair_const.cpp
  src/theory/quantifiers/sygus/sygus_repair_const.h
Labels: moderate, normal
