Repository cvc5/cvc5, pull requests merged in 2018-06, with the labels that each got.

#2025 Reduce quantifiers before preregister
  src/theory/quantifiers_engine.cpp
Labels: normal, simple

#2038 Use monomial sum utility to solve for quantifiers macros
  src/theory/quantifiers/macros.cpp
  test/regress/Makefile.tests
  test/regress/regress0/quantifiers/issue2033-macro-arith.smt2
Labels: major, simple

#2027 Apply preprocessing to counterexample lemmas in CEGQI
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  test/regress/Makefile.tests
  test/regress/regress1/quantifiers/015-psyco-pp.smt2
  test/regress/regress1/quantifiers/smtcomp-qbv-053118.smt2
Labels: major, simple

#2043 Fix quantifiers conflict lemma handling
  src/theory/quantifiers_engine.cpp
Labels: major, simple

#2039 Fix quantified bv variable elimination
  src/theory/quantifiers/quantifiers_rewriter.cpp
  test/regress/Makefile.tests
  test/regress/regress0/quantifiers/issue2031-bv-var-elim.smt2
Labels: major, simple

#2047 Fix preinitialization pass for finite model finding
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/quantifiers/fmf/full_model_check.h
  test/regress/Makefile.tests
  test/regress/regress1/fmf/issue2034-preinit.smt2
Labels: major, simple

#2042 Fix BV-abstraction check to consider SKOLEM.
  src/theory/bv/abstraction.cpp
  src/theory/bv/bitblast/aig_bitblaster.cpp
  src/theory/bv/bitblast/aig_bitblaster.h
  test/regress/Makefile.tests
  test/regress/regress0/bv/bv-abstr-bug2.smt2
Labels: major, simple

#2046 Fix corner case of mixed int/real cegqi.
  src/theory/arith/arith_msum.cpp
  src/theory/quantifiers/cegqi/ceg_t_instantiator.cpp
Labels: normal, simple

#2050 Fix assertion involving unassigned Boolean eqc in model
  src/theory/theory_model_builder.cpp
Labels: normal, simple

#2044 Regressions: Support for requiring CVC4 features
  test/regress/Makefile.tests
  test/regress/README.md
  test/regress/regress0/fp/simple.smt2
  test/regress/run_regression.py
Labels: normal, simple

#2023 Enable cegqi (with model values) for floating point by default
  src/smt/smt_engine.cpp
  src/theory/fp/theory_fp_rewriter.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  test/regress/Makefile.tests
  test/regress/regress1/quantifiers/fp-cegqi-unsat.smt2
Labels: normal, simple

#2022 [SMT-COMP] Add new logics to run-scripts
  contrib/run-script-smtcomp2018
  contrib/run-script-smtcomp2018-application
  contrib/run-script-smtcomp2018-unsat-cores
Labels: major, simple

#2051 Move assertion in arrays
  src/theory/arrays/theory_arrays.cpp
Labels: minor, simple

#2052 Only enable transcendentals if logic is N[I]RAT
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/theory/logic_info.cpp
  src/theory/logic_info.h
  test/regress/Makefile.tests
  test/regress/regress0/nl/nta/cos-sig-value.smt2
  test/regress/regress0/nl/nta/exp-n0.5-lb.smt2
  test/regress/regress0/nl/nta/exp-n0.5-ub.smt2
  test/regress/regress0/nl/nta/exp1-ub.smt2
  test/regress/regress0/nl/nta/sin-sym.smt2
  test/regress/regress0/nl/nta/sqrt-simple.smt2
  test/regress/regress0/nl/nta/tan-rewrite.smt2
  test/regress/regress0/parser/shadow_fun_symbol_all.smt2
  test/regress/regress0/parser/shadow_fun_symbol_nirat.smt2
  test/regress/regress1/nl/NAVIGATION2.smt2
  test/regress/regress1/nl/arctan2-expdef.smt2
  test/regress/regress1/nl/arrowsmith-050317.smt2
  test/regress/regress1/nl/bad-050217.smt2
  test/regress/regress1/nl/cos-bound.smt2
  test/regress/regress1/nl/cos1-tc.smt2
  test/regress/regress1/nl/dumortier_llibre_artes_ex_5_13.transcendental.k2.smt2
  test/regress/regress1/nl/exp-4.5-lt.smt2
  test/regress/regress1/nl/exp1-lb.smt2
  test/regress/regress1/nl/exp_monotone.smt2
  test/regress/regress1/nl/mirko-050417.smt2
  test/regress/regress1/nl/sin-compare-across-phase.smt2
  test/regress/regress1/nl/sin-compare.smt2
  test/regress/regress1/nl/sin-init-tangents.smt2
  test/regress/regress1/nl/sin-sign.smt2
  test/regress/regress1/nl/sin-sym2.smt2
  test/regress/regress1/nl/sin1-deq-sat.smt2
  test/regress/regress1/nl/sin1-lb.smt2
  test/regress/regress1/nl/sin1-sat.smt2
  test/regress/regress1/nl/sin1-ub.smt2
  test/regress/regress1/nl/sin2-lb.smt2
  test/regress/regress1/nl/sin2-ub.smt2
  test/regress/regress1/nl/sugar-ident-2.smt2
  test/regress/regress1/nl/sugar-ident-3.smt2
  test/regress/regress1/nl/sugar-ident.smt2
  test/regress/regress1/nl/tan-rewrite2.smt2
  test/unit/theory/logic_info_white.h
Labels: major, simple

#2056 Clear pending inferences during datatypes splitting
  src/theory/datatypes/theory_datatypes.cpp
Labels: normal, simple

#2058 Look for cryptominisat5_simple, not cryptominisat5
  config/cryptominisat.m4
Labels: major, simple

#2059 Reset decisions at SAT level after solving
  src/prop/minisat/core/Solver.cc
  src/prop/minisat/core/Solver.h
  src/prop/minisat/minisat.cpp
  src/prop/minisat/minisat.h
  src/prop/minisat/simp/SimpSolver.cc
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/sat_solver.h
  src/smt/smt_engine.cpp
  test/regress/Makefile.tests
  test/regress/regress0/push-pop/bug1990.smt2
Labels: complex, major

#2062 Add flag to skip regression if feature enabled
  test/regress/README.md
  test/regress/regress1/arrayinuf_error.smt2
  test/regress/regress1/datatypes/error.cvc
  test/regress/regress1/errorcrash.smt2
  test/regress/run_regression.py
Labels: major, simple

#2063 Disable test that fails in competition mode
  test/regress/regress1/error.cvc
Labels: major, simple

#2064 Fix equality conflicts reported by FP
  src/theory/fp/theory_fp.cpp
  test/regress/Makefile.tests
  test/regress/regress1/wrong-qfabvfp-smtcomp2018.smt2
Labels: major, simple

#2067 Fix strip constant endpoint for ITOS in strings rewriter
  src/theory/strings/theory_strings_rewriter.cpp
  test/regress/Makefile.tests
  test/regress/regress0/strings/strip-endpoint-itos.smt2
Labels: normal, simple

#1976 Disable unconstrainedSimp pass when proofs enabled
  src/smt/smt_engine.cpp
Labels: do not merge, minor, simple

#2066 Fix simple regexp consume
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
  test/regress/Makefile.tests
  test/regress/regress1/strings/issue2060.smt2
Labels: normal, simple

#1962 Workaround for incremental unsat cores
  src/prop/minisat/core/Solver.cc
Labels: major, simple

#2070 Disable solving non-linear BV literals by default
  src/options/quantifiers_options.toml
  src/theory/quantifiers/bv_inverter.cpp
  src/theory/quantifiers/bv_inverter.h
  src/theory/quantifiers/cegqi/ceg_t_instantiator.cpp
  test/regress/Makefile.tests
  test/regress/regress1/quantifiers/qbv-subcall.smt2
  test/regress/regress1/sygus/logiccell_help.sy
Labels: normal, simple

#2077 Resolve CVC4_USE_SYMFPU in headers at config-time
  configure.ac
  src/Makefile.am
  src/util/Makefile.am
  src/util/floatingpoint.h.in
Labels: major, simple

#1955 Check unsat cores in regressions also without LFSC
  configure.ac
  test/regress/run_regression.py
Labels: moderate, normal

#2079 Fix warnings and enable -Wnon-virtual-dtor warning
  configure.ac
  src/theory/bv/abstraction.cpp
  src/theory/quantifiers/dynamic_rewrite.cpp
  src/theory/quantifiers/dynamic_rewrite.h
  src/theory/quantifiers/sygus/cegis.h
  src/theory/quantifiers/sygus/cegis_unif.h
  src/theory/quantifiers/sygus/sygus_module.h
  src/theory/quantifiers/sygus/sygus_unif_strat.h
  src/theory/quantifiers/sygus_sampler.h
Labels: major, simple

#2082 Remove parentheses for prefix ops without args
  src/printer/cvc/cvc_printer.cpp
Labels: minor, simple

#2089 Minor improvements in SMT2 and CVC printers
  src/printer/cvc/cvc_printer.cpp
  src/printer/smt2/smt2_printer.cpp
Labels: minor, simple

#2092 Remove unnecessary code in register quantifier internal
  src/theory/quantifiers_engine.cpp
Labels: minor, simple

#2093 Do not dagify printing over binders
  src/printer/dagification_visitor.cpp
Labels: normal, simple

#2096 Fix assertion for relational triggers
  src/theory/quantifiers/ematching/inst_match_generator.cpp
Labels: minor, simple

#2091 Disable uf symmetry breaker in incremental mode
  src/smt/smt_engine.cpp
Labels: minor, simple

#2100 Add casc j9 tfn script
  contrib/run-script-cascj9-tfn-nr
Labels: minor, simple

#2090 sygusComp2018: Add evaluator
  src/Makefile.am
  src/options/quantifiers_options.toml
  src/theory/evaluator.cpp
  src/theory/evaluator.h
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
  test/unit/Makefile.am
  test/unit/theory/evaluator_white.h
Labels: moderate, normal

#2103 sygusComp2018: add competition scripts
  contrib/run-script-sygusComp2018-CLIA
  contrib/run-script-sygusComp2018-GENERAL
  contrib/run-script-sygusComp2018-INV
  contrib/run-script-sygusComp2018-PBE_BitVec
  contrib/run-script-sygusComp2018-PBE_Strings
Labels: minor, simple

#1918 Synthesize candidate-rewrites from standard inputs
  src/Makefile.am
  src/options/smt_options.toml
  src/preprocessing/passes/synth_rew_rules.cpp
  src/preprocessing/passes/synth_rew_rules.h
  src/smt/smt_engine.cpp
  src/theory/quantifiers/candidate_rewrite_database.cpp
  src/theory/quantifiers/candidate_rewrite_database.h
  src/theory/quantifiers/dynamic_rewrite.cpp
  src/theory/quantifiers/dynamic_rewrite.h
  src/theory/quantifiers/sygus/ce_guided_conjecture.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
  src/theory/quantifiers/sygus_sampler.cpp
  src/theory/quantifiers/sygus_sampler.h
Labels: minor, moderate

#1697 Header for new C++ API.
  examples/api/bitvectors-new.cpp
  examples/api/bitvectors_and_arrays-new.cpp
  examples/api/combination-new.cpp
  examples/api/datatypes-new.cpp
  examples/api/extract-new.cpp
  examples/api/helloworld-new.cpp
  examples/api/linear_arith-new.cpp
  examples/api/sets-new.cpp
  examples/api/strings-new.cpp
  src/api/cvc4cpp.h
  src/api/cvc4cppkind.h
Labels: complex, normal

#2094 Split and document ceg theory instantiators
  src/Makefile.am
  src/theory/quantifiers/cegqi/ceg_arith_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_arith_instantiator.h
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.h
  src/theory/quantifiers/cegqi/ceg_dt_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_dt_instantiator.h
  src/theory/quantifiers/cegqi/ceg_epr_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_epr_instantiator.h
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_t_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_t_instantiator.h
  src/theory/quantifiers_engine.cpp
  test/unit/theory/theory_quantifiers_bv_instantiator_white.h
Labels: minor, moderate

#2098 Do not rename uninterpreted constants
  src/expr/uninterpreted_constant.cpp
  src/printer/smt2/smt2_printer.cpp
Labels: normal, simple

#2113 Fix stale reference in MiniSat when generating UC
  src/prop/minisat/core/Solver.cc
  test/regress/Makefile.tests
  test/regress/regress2/push-pop/DRAGON_4_e2_2799_e3_1915.lus.ic3.1.min.smt2
Labels: major, simple

#2104 sygusComp2018: optimization for invariance test
  src/theory/quantifiers/sygus/sygus_invariance.cpp
  src/theory/quantifiers/sygus/sygus_invariance.h
Labels: minor, simple

#2118 Remove comment about model value hack
  src/theory/theory_engine.cpp
Labels: minor, simple

#2112 New C++ API: Implementation of Result.
  src/Makefile.am
  src/api/cvc4cpp.cpp
  src/api/cvc4cppkind.h
Labels: moderate, normal

#2117 Use evaluator in sygus sampler.
  src/theory/quantifiers/sygus_sampler.cpp
  src/theory/quantifiers/sygus_sampler.h
Labels: normal, simple
