Repository cvc5/cvc5, pull requests merged in 2018-02, with the labels that each got.

#1585 Replacing an incorrect reference to an injected class name...
  src/proof/sat_proof.h
Labels: bug, moderate

#1590 Renaming CHECK to CVC4_CHECK. This avoids name collisions with other …
  src/base/cvc4_check.h
  src/util/statistics_registry.cpp
  test/unit/util/check_white.h
Labels: major, simple

#1588 Class to reduce printing of redundant candidate rewrites
  src/Makefile.am
  src/theory/quantifiers/ce_guided_conjecture.cpp
  src/theory/quantifiers/dynamic_rewrite.cpp
  src/theory/quantifiers/dynamic_rewrite.h
  src/theory/quantifiers/sygus_grammar_red.h
  src/theory/quantifiers/sygus_invariance.h
  src/theory/quantifiers/sygus_sampler.cpp
  src/theory/quantifiers/sygus_sampler.h
Labels: moderate, normal

#1582 Removing an always true comparison (unsigned) >= 0u.
  src/theory/bv/bvgauss.cpp
Labels: normal, simple

#1587 Clean up bv utils (part two).
  src/theory/bv/abstraction.cpp
  src/theory/bv/bitblast_strategies_template.h
  src/theory/bv/bv_inequality_graph.cpp
  src/theory/bv/bv_subtheory_algebraic.cpp
  src/theory/bv/bv_subtheory_core.cpp
  src/theory/bv/bv_subtheory_inequality.cpp
  src/theory/bv/bv_to_bool.cpp
  src/theory/bv/eager_bitblaster.cpp
  src/theory/bv/lazy_bitblaster.cpp
  src/theory/bv/slicer.cpp
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv_rewrite_rules_normalization.h
  src/theory/bv/theory_bv_rewrite_rules_operator_elimination.h
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
  src/theory/bv/theory_bv_utils.cpp
  src/theory/bv/theory_bv_utils.h
Labels: normal, simple

#1589 Clean up bv::utils (part three).
  src/proof/proof_utils.h
  src/theory/bv/bvgauss.cpp
  src/theory/bv/theory_bv_rewrite_rules_normalization.h
  src/theory/bv/theory_bv_utils.cpp
  src/theory/bv/theory_bv_utils.h
  src/theory/quantifiers/bv_inverter.cpp
  src/util/bitvector.h
Labels: normal, simple

#1597 More minor improvements to synth-rr
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/quantifiers/ce_guided_conjecture.cpp
  src/theory/quantifiers/ce_guided_instantiation.cpp
  src/theory/quantifiers/ce_guided_instantiation.h
Labels: minor, simple

#1594 Move (unrecursified) bv::utils::numNodes to lazy_bitblaster.cpp.
  src/theory/bv/lazy_bitblaster.cpp
  src/theory/bv/theory_bv_utils.cpp
  src/theory/bv/theory_bv_utils.h
Labels: normal, simple

#1598 Minor improvements to sygus sampler
  src/theory/quantifiers/ce_guided_conjecture.cpp
  src/theory/quantifiers/ce_guided_instantiation.cpp
  src/theory/quantifiers/ce_guided_instantiation.h
  src/theory/quantifiers/dynamic_rewrite.cpp
  src/theory/quantifiers/dynamic_rewrite.h
  src/theory/quantifiers/sygus_sampler.cpp
  src/theory/quantifiers/sygus_sampler.h
Labels: minor, simple

#1600 Option to use extended rewriter as a preprocessing pass
  src/options/smt_options
  src/smt/smt_engine.cpp
  src/theory/quantifiers/extended_rewrite.cpp
  src/theory/quantifiers/extended_rewrite.h
  src/theory/quantifiers/term_database_sygus.cpp
Labels: minor, simple

#1603 Skip header for determining top contributors list.
  contrib/get-authors
Labels: normal, simple

#1602 Moved (unrecursified) bv::utils::collectVars.
  src/theory/bv/bv_subtheory_algebraic.cpp
  src/theory/bv/theory_bv_utils.cpp
  src/theory/bv/theory_bv_utils.h
Labels: normal, simple

#1604 Provide a uniform way to serialize node containers to output stream.
  src/expr/node.h
Labels: normal, simple

#1609 Fix context memory manager unit test
  test/unit/context/context_mm_black.h
Labels: normal, simple

#1601 Fix corner case for rewrite of mult by pow 2
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
  test/regress/regress0/bv/Makefile.am
  test/regress/regress0/bv/mult-pow2-negative.smt2
Labels: major, simple

#1610 Removed bv::utils::mkConjunction (redundant).
  src/theory/bv/bv_quick_check.cpp
  src/theory/bv/bv_subtheory_bitblast.cpp
  src/theory/bv/theory_bv_utils.cpp
  src/theory/bv/theory_bv_utils.h
Labels: normal, simple

#1611 Make regress1 default, only test regress0 on Travis.
  .travis.yml
  test/regress/Makefile.am
Labels: normal, simple

#1613 bv::utils::mk(And|Or): Do not return true if given vector is empty.
  src/theory/bv/bv_subtheory_core.cpp
  src/theory/bv/theory_bv_utils.h
Labels: normal, simple

#1605 Unrecursified and merged bv::utils::is(Core|Equality)Term.
  src/theory/bv/theory_bv_utils.cpp
  src/theory/bv/theory_bv_utils.h
Labels: normal, simple

#1614 Moved and simplified bv::utils::intersect.
  src/theory/bv/slicer.cpp
  src/theory/bv/theory_bv_utils.cpp
Labels: normal, simple

#1619 Disable BV equality slicer if not pure QF_BV.
  src/theory/theory_engine.cpp
Labels: bug, normal, simple

#1623 Fix condition for disabling the BV equality slicer for quantifiers.
  src/theory/theory_engine.cpp
Labels: major, simple

#1572 Minor improvements to string rewriter
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
  test/regress/regress1/strings/Makefile.am
  test/regress/regress1/strings/rew-020618.smt2
Labels: normal, simple

#1624 Fix cd-simplification for strings
  src/theory/strings/theory_strings.cpp
  test/regress/regress1/strings/Makefile.am
  test/regress/regress1/strings/double-replace.smt2
Labels: major, simple

#1615 Split and document bitvector.h.
  src/util/Makefile.am
  src/util/bitvector.cpp
  src/util/bitvector.h
Labels: moderate, normal

#1622 Unit tests for BitVector
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
  src/util/bitvector.cpp
  test/unit/util/bitvector_black.h
Labels: refactor, simple

#1621 Improvements to sygus sampling
  src/options/quantifiers_options
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/datatypes/datatypes_sygus.h
  src/theory/quantifiers/sygus_sampler.cpp
Labels: normal, simple

#1620 Option to not use partial function semantics for arithmetic div by zero
  src/options/arith_options
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
Labels: major, simple

#1592 Improve rewriter for string indexof
  src/theory/strings/theory_strings_rewriter.cpp
  src/util/regexp.cpp
  src/util/regexp.h
  test/regress/regress0/strings/Makefile.am
  test/regress/regress0/strings/idof-sem.smt2
Labels: major, moderate

#1627 Remove unused code in pushDefineFunRecScop in smt2.cpp.
  src/parser/smt2/smt2.cpp
Labels: normal, simple

#1616 Minor fixes for rec-fun
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  test/regress/regress1/quantifiers/Makefile.am
  test/regress/regress1/quantifiers/arith-rec-fun.smt2
Labels: normal, simple

#1628 SmtEngine::getAssignment now returns a vector of assignments.
  src/smt/command.cpp
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
Labels: normal, simple
