Repository cvc5/cvc5, pull requests merged in 2019-04, with the labels that each got.

#2909 Modify strategy in sets+cardinality
  src/theory/sets/theory_sets_private.cpp
Labels: major, simple

#2913 Move slow string regression to regress3
  test/regress/CMakeLists.txt
  test/regress/regress3/strings/extf_d_perf.smt2
Labels: major, simple

#2878 Fix RewriteITEBv to ensure rewrite to fixpoint
  src/theory/bv/theory_bv_rewriter.cpp
  test/unit/theory/CMakeLists.txt
  test/unit/theory/theory_bv_rewriter_white.h
Labels: major, moderate

#2910 FP: Fix wrong model due to partial assignment
  src/theory/fp/theory_fp.cpp
  src/theory/theory_model_builder.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/fp/wrong-model.smt2
Labels: complex, major

#2930 Fix combination of datatypes + strings in PBE
  src/theory/quantifiers/sygus/sygus_unif_io.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/issue2914.sy
Labels: major, simple

#2931 Ignoring FP benchmarks with "unsafe" sizes unless option
  src/options/fp_options.toml
  src/theory/fp/theory_fp.cpp
  test/regress/regress0/fp/abs-unsound.smt2
  test/regress/regress0/fp/abs-unsound2.smt2
  test/regress/regress0/fp/wrong-model.smt2
Labels: do not merge, normal, simple

#2916 SatClauseSetHashFunction
  src/prop/sat_solver_types.h
Labels: do not merge, simple

#2940 Fix fp issue
  src/theory/fp/theory_fp.cpp
  test/regress/regress1/rr-verify/fp-arith.sy
  test/regress/regress1/rr-verify/fp-bool.sy
  test/regress/regress2/sygus/min_IC_1.sy
Labels: major, simple

#2938 Fix another corner case of datatypes+PBE
  src/theory/quantifiers/sygus/sygus_unif_io.cpp
  src/theory/quantifiers/sygus/sygus_unif_io.h
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/issue2935.sy
Labels: major, simple

#2941 prerelease -> release
  CMakeLists.txt
Labels: normal, simple

#2942 fix copyright year in configuration file
  src/base/configuration.cpp
Labels: normal, simple

#2944 "prerelease -> release" in INSTALL
  INSTALL.md
Labels: normal, simple

#2949 Eliminate Boolean ITE within terms, fixes 2947
  src/smt/term_formula_removal.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/uf/issue2947.smt2
Labels: major, simple

#2943 Referring to prerelease 1.8
  CMakeLists.txt
  INSTALL.md
Labels: normal, simple

#2951 Initial version of run scripts for SMT-COMP 2019
  contrib/run-script-smtcomp2019
  contrib/run-script-smtcomp2019-application
  contrib/run-script-smtcomp2019-unsat-cores
Labels: normal, simple

#2854 Check for rt library in configuration -- support for glibc<2.17
  cmake/ConfigureCVC4.cmake
  src/CMakeLists.txt
Labels: simple

#2953 Minor simplifications to theory quantifiers
  src/options/quantifiers_options.toml
  src/theory/quantifiers/theory_quantifiers.cpp
  src/theory/quantifiers/theory_quantifiers.h
  test/regress/regress0/quantifiers/ARI176e1.smt2
  test/regress/regress0/quantifiers/nested-delta.smt2
  test/regress/regress0/quantifiers/nested-inf.smt2
Labels: minor, simple

#2954 Stratify enumerative instantiation
  src/options/quantifiers_options.toml
  src/theory/quantifiers/inst_strategy_enumerative.cpp
  src/theory/quantifiers/inst_strategy_enumerative.h
  test/regress/CMakeLists.txt
  test/regress/regress2/quantifiers/syn874-1.smt2
Labels: moderate, normal

#2955 Make bv{add,mul,and,or,xor,xnor} left-associative
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.h
  test/regress/CMakeLists.txt
  test/regress/regress0/parser/bv_arity_smt2.6.smt2
Labels: normal, simple

#2956 Add interface for term enumeration
  src/theory/quantifiers/term_enumeration.cpp
  src/theory/quantifiers/term_enumeration.h
Labels: minor, simple

#2960 Fix extended function decomposition
  src/theory/strings/theory_strings.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/issue2958.smt2
Labels: major, simple

#2959 More use of isClosure
  src/expr/expr_manager_template.h
  src/expr/node.h
  src/expr/node_algorithm.cpp
  src/preprocessing/passes/synth_rew_rules.cpp
  src/printer/dagification_visitor.cpp
  src/smt/term_formula_removal.cpp
  src/theory/quantifiers/term_database.cpp
  src/theory/substitutions.cpp
  src/theory/term_registration_visitor.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_model_builder.cpp
  src/theory/uf/theory_uf.cpp
Labels: minor, simple

#2937 Cache explanations in the equality engine
  src/theory/uf/equality_engine.cpp
  src/theory/uf/equality_engine.h
Labels: moderate, normal

#2964 Less aggressive caching in equality engine when proofs are enabled
  src/proof/uf_proof.cpp
  src/theory/uf/equality_engine.cpp
Labels: major, moderate

#2939 Fail fast strategy for propagating instances
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/quant_conflict_find.h
  src/theory/quantifiers/quant_util.cpp
  src/theory/quantifiers/quant_util.h
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers/term_database.h
Labels: moderate, normal

#2968 Add CONTRIBUTING file.
  CONTRIBUTING.md
  README.md
Labels: normal, simple

#2897 Refactor normal forms in strings
  src/CMakeLists.txt
  src/theory/strings/normal_form.cpp
  src/theory/strings/normal_form.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: moderate, normal

#2915 [BV] An option for SAT proof optimization
  src/options/bv_bitblast_mode.cpp
  src/options/bv_bitblast_mode.h
  src/options/bv_options.toml
  src/options/options_handler.cpp
  src/options/options_handler.h
Labels: simple

#2975 Fix compiler warning.
  src/preprocessing/passes/synth_rew_rules.cpp
Labels: normal, simple

#2977 New C++ API: Clean up API: mkVar vs mkConst vs mkBoundVar.
  examples/api/bitvectors-new.cpp
  examples/api/bitvectors_and_arrays-new.cpp
  examples/api/combination-new.cpp
  examples/api/datatypes-new.cpp
  examples/api/extract-new.cpp
  examples/api/linear_arith-new.cpp
  examples/api/sets-new.cpp
  examples/api/strings-new.cpp
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/api/cvc4cppkind.h
  src/parser/smt2/Smt2.g
  test/unit/api/solver_black.h
Labels: normal, simple

#2979 Optimization for evaluation with unfolding
  src/theory/quantifiers/sygus/term_database_sygus.cpp
Labels: moderate, normal

#2976 Eliminate APPLY kind
  src/api/cvc4cpp.cpp
  src/api/cvc4cppkind.h
  src/expr/node.h
  src/parser/parser.cpp
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/printer/cvc/cvc_printer.cpp
  src/printer/smt2/smt2_printer.cpp
  src/smt/command.cpp
  src/smt/smt_engine.cpp
  src/theory/builtin/kinds
  src/theory/builtin/theory_builtin_type_rules.h
  src/theory/datatypes/datatypes_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/define-fun-model.smt2
Labels: moderate, normal

#2984 Fix use of APPLY kind in examples
  examples/sets-translate/sets_translate.cpp
Labels: major, simple

#2985 Remove stoi solve rewrite
  src/theory/strings/theory_strings_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue2981.smt2
  test/regress/regress1/strings/stoi-solve.smt2
Labels: major, simple

#2983 Fix concat-find regexp elimination
  src/theory/strings/regexp_elim.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue2982.smt2
Labels: major, simple
