Repository cvc5/cvc5, pull requests merged in 2019-06, with the labels that each got.

#3029 Fix rewriter for regular expression consume
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/simple-re-consume.smt2
Labels: major, moderate

#3031 Require that FMF model basis terms are variables
  src/theory/quantifiers/first_order_model.cpp
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers/term_database.h
Labels: major, simple

#3033 Update QF_BV options for SMT-COMP 2019.
  contrib/run-script-smtcomp2019
  contrib/run-script-smtcomp2019-model-validation
Labels: major, simple

#3035 Add check for limit of number of node children
  src/expr/node_builder.h
Labels: major, simple

#3034 [SMT-COMP 2019] Update run script for unsat cores
  contrib/run-script-smtcomp2019-unsat-cores
Labels: major, simple

#3036 Enable SymFPU assertions in production
  contrib/run-script-smtcomp2019
  contrib/run-script-smtcomp2019-unsat-cores
  src/theory/fp/fp_converter.cpp
  src/util/floatingpoint.cpp
Labels: major, simple

#3037 [SMT-COMP 2019] Use lazy BV as backup for QF_UFBV
  contrib/run-script-smtcomp2019
Labels: major, simple

#3038 [SMT-COMP] Increase sequential portfolio timeouts
  contrib/run-script-smtcomp2019
Labels: major, simple

#3039 [SMT-COMP] No unconstrained simp for QF_LIA UC
  contrib/run-script-smtcomp2019-unsat-cores
Labels: major, simple

#3028 Add check that result matches benchmark status
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  test/regress/CMakeLists.txt
  test/regress/regress0/bv/ackermann1.smt2
  test/regress/regress0/bv/ackermann4.smt2
  test/regress/regress0/fmf/Arrow_Order-smtlib.778341.smt
  test/regress/regress0/quantifiers/qbv-test-invert-bvxor.smt2
  test/regress/regress0/sets/mar2014/sharing-preregister.smt2
  test/regress/regress0/smtlib/set-info-status.smt2
  test/regress/regress1/quantifiers/qbv-test-invert-bvcomp.smt2
  test/regress/regress1/quantifiers/qe.smt2
Labels: normal, simple

#2928 Enable proof checking for QF_LRA benchmarks
  proofs/signatures/CMakeLists.txt
  src/smt/smt_engine.cpp
  src/theory/logic_info.cpp
  test/regress/regress0/lemmas/sc_init_frame_gap.induction.smt
  test/regress/regress0/uflra/constants0.smt
  test/regress/regress0/uflra/pb_real_10_0200_10_22.smt
  test/regress/regress0/uflra/pb_real_10_0200_10_26.smt
  test/regress/regress1/lemmas/pursuit-safety-8.smt
  test/regress/regress1/lemmas/simple_startup_9nodes.abstract.base.smt
  test/regress/regress2/arith/pursuit-safety-11.smt
  test/regress/regress2/arith/pursuit-safety-12.smt
  test/unit/theory/logic_info_white.h
Labels: normal, simple

#3041 Add support for SWIG 4
  src/bindings/java/CMakeLists.txt
  src/smt/smt_engine.i
Labels: normal, simple

#3042 Prevent letification from shadowing variables
  src/expr/node_algorithm.cpp
  src/expr/node_algorithm.h
  src/printer/dagification_visitor.cpp
  src/printer/dagification_visitor.h
  test/regress/CMakeLists.txt
  test/regress/regress0/printer/let_shadowing.smt2
Labels: major, moderate

#3047 Optimization for strings normalize disequalities
  src/theory/strings/theory_strings.cpp
Labels: moderate, normal

#3048 Optimization for negative concatenation membership.
  src/theory/strings/regexp_operation.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/re-neg-concat-reduct.smt2
  test/regress/regress2/strings/norn-dis-0707-3.smt2
Labels: moderate, normal

#3052 Fix spurious assertion in get-value
  src/smt/smt_engine.cpp
Labels: minor, simple

#3049 Do not require sygus constructors to be flattened
  src/parser/smt2/Smt2.g
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/datatypes_rewriter.h
  src/theory/quantifiers/sygus/sygus_eval_unfold.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_grammar_red.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
  test/regress/regress1/sygus/sygus-dt.sy
Labels: moderate, normal

#2966 Minor cleaning of conflict-based instantiation
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/quant_conflict_find.h
  src/theory/quantifiers/rewrite_engine.cpp
Labels: minor, moderate

#3050 NA Tangent reverse implication
  src/theory/arith/nonlinear_extension.cpp
Labels: moderate, normal

#3045 Fix compilation issue for Java bindings + CLN
  src/bindings/java/CMakeLists.txt
Labels: normal, simple

#3046 Disable dumping regression for non-dumping builds
  src/base/configuration.cpp
  src/smt/dump.cpp
  test/regress/regress0/printer/let_shadowing.smt2
Labels: normal, simple

#2936 Refactor parser to define fewer tokens for symbols
  src/expr/symbol_table.cpp
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  test/regress/regress0/bv/core/constant_core.smt2
  test/regress/regress0/expect/scrub.08.sy
  test/regress/regress0/nl/nta/real-pi.smt2
  test/regress/regress0/strings/bug613.smt2
  test/regress/regress0/strings/str004.smt2
  test/regress/regress0/strings/type001.smt2
  test/regress/regress0/strings/unsound-0908.smt2
  test/regress/regress1/strings/artemis-0512-nonterm.smt2
  test/regress/regress1/strings/at001.smt2
  test/regress/regress1/strings/fmf002.smt2
  test/regress/regress1/strings/issue2429-code.smt2
  test/regress/regress1/strings/kaluza-fl.smt2
  test/regress/regress1/strings/loop005.smt2
  test/regress/regress1/strings/loop007.smt2
  test/regress/regress1/strings/loop008.smt2
  test/regress/regress1/strings/re-agg-total1.smt2
  test/regress/regress1/strings/reloop.smt2
  test/regress/regress1/strings/substr001.smt2
  test/regress/regress1/strings/type002.smt2
  test/regress/regress1/strings/type003.smt2
  test/unit/parser/parser_black.h
Labels: moderate, normal

#3053 Fix warning
  src/proof/er/er_proof.cpp
Labels: minor, simple

#3051 Shorten explanation for strings inference I_Norm_S
  src/theory/strings/theory_strings.cpp
Labels: normal, simple

#3054 Add lemma for the range of values of str.indexof
  src/theory/strings/theory_strings.cpp
Labels: normal, simple

#3059 Use Ubuntu 16.04 on Travis
  .travis.yml
Labels: normal, simple

#2761 Strings: More aggressive skolem normalization
  src/theory/strings/skolem_cache.cpp
  src/theory/strings/theory_strings.cpp
Labels: moderate, normal

#2849 Use TMPDIR environment variable for temp files
  src/proof/clausal_bitvector_proof.cpp
  src/proof/er/er_proof.cpp
  src/proof/lrat/lrat_proof.cpp
  src/util/CMakeLists.txt
  src/util/utility.cpp
  src/util/utility.h
  test/unit/proof/lrat_proof_black.h
Labels: normal, simple

#3062 Fix and simplify handling of --force-logic
  src/api/cvc4cpp.cpp
  src/options/options.h
  src/options/options_handler.cpp
  src/options/options_handler.h
  src/options/options_template.cpp
  src/options/parser_options.toml
  src/options/smt_options.toml
  src/parser/CMakeLists.txt
  src/parser/cvc/cvc.cpp
  src/parser/cvc/cvc.h
  src/parser/parser.h
  src/parser/parser_builder.cpp
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/parser/tptp/tptp.cpp
  src/parser/tptp/tptp.h
  src/smt/smt_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/bv/eager-force-logic.smt2
  test/regress/regress0/parser/force_logic_set_logic.smt2
  test/unit/api/solver_black.h
Labels: major, normal

#3063 Add floating-point support in the Java API
  examples/api/java/CMakeLists.txt
  examples/api/java/FloatingPointArith.java
  src/bindings/java/CMakeLists.txt
  src/cvc4.i
  src/expr/expr.i
  src/expr/expr_manager.i
  src/util/floatingpoint.i
Labels: moderate, normal

#3068 Fix memory leak in unit test
  test/unit/parser/parser_black.h
Labels: major, simple

#3067 Stratify unfolding of regular expressions based on polarity
  src/theory/strings/regexp_solver.cpp
  src/theory/strings/theory_strings.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/regexp-strat-fix.smt2
Labels: moderate, normal

#3071 Variable elimination rewrite for quantified strings
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue2970-string-var-elim.smt2
Labels: moderate, normal

#3072 Make mkOpTerm const
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
Labels: simple
