Repository cvc5/cvc5, pull requests merged in 2019-08, with the labels that each got.

#3134 Regular expression intersection modes
  src/options/CMakeLists.txt
  src/options/options_handler.cpp
  src/options/options_handler.h
  src/options/strings_modes.cpp
  src/options/strings_modes.h
  src/options/strings_options.toml
  src/smt/smt_engine.cpp
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/regexp_operation.h
  src/theory/strings/regexp_solver.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/re-all-char-hard.smt2
Labels: moderate, normal

#3139 Move some generic utilities out of quantifiers
  src/CMakeLists.txt
  src/expr/CMakeLists.txt
  src/expr/match_trie.cpp
  src/expr/match_trie.h
  src/expr/term_canonize.cpp
  src/expr/term_canonize.h
  src/preprocessing/passes/symmetry_detect.h
  src/preprocessing/passes/synth_rew_rules.cpp
  src/theory/quantifiers/alpha_equivalence.cpp
  src/theory/quantifiers/alpha_equivalence.h
  src/theory/quantifiers/anti_skolem.cpp
  src/theory/quantifiers/candidate_rewrite_filter.cpp
  src/theory/quantifiers/candidate_rewrite_filter.h
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: minor, simple

#3141 Fix memory leak in rewriter (debug mode).
  src/theory/rewriter.cpp
Labels: normal, simple

#3117 Use python realpath instead of relying on shell realpath
  contrib/get-antlr-3.4
Labels: simple

#3144 Enable sygus logic when produce-abducts is true
  src/smt/smt_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/opt-abd-no-use.smt2
Labels: major, simple

#3142 Fix BVGauss unit tests.
  src/preprocessing/passes/bv_gauss.cpp
  src/preprocessing/passes/bv_gauss.h
  test/unit/preprocessing/pass_bv_gauss_white.h
Labels: major, simple

#3143 Fix solution filtering for streaming abducts
  src/theory/quantifiers/solution_filter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus-abduct-ex1-grammar.smt2
Labels: major, simple

#3145 Throw option exception when track inst lemmas is not enabled
  src/theory/quantifiers/instantiate.cpp
Labels: normal, simple

#3148 Support default sygus grammar for strings
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/strings-no-syntax.sy
  test/regress/regress2/sygus/strings-no-syntax-len.sy
Labels: moderate, normal

#3147 Remove simplification specialized for sygus si solution reconstruction
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv_sol.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv_sol.h
  test/regress/CMakeLists.txt
Labels: normal, simple

#3149 Move basic sygus enumerator to its own file
  src/CMakeLists.txt
  src/theory/quantifiers/sygus/sygus_enumerator_basic.cpp
  src/theory/quantifiers/sygus/sygus_enumerator_basic.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
Labels: minor, simple

#3150 Add better Python detection for contrib scripts.
  contrib/get-antlr-3.4
  contrib/get-script-header.sh
Labels: major, simple

#3153 Flip the polarity of the argument of get-abduct
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  test/regress/regress1/sygus-abduct-ex1-grammar.smt2
  test/regress/regress1/sygus-abduct-test-user.smt2
  test/regress/regress1/sygus-abduct-test.smt2
Labels: major, simple

#3137 Update CaDiCaL to version 1.0.3.
  cmake/ConfigureCVC4.cmake
  contrib/get-cadical
  src/options/options_handler.cpp
  src/prop/cadical.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/bv/eager-inc-cadical.smt2
Labels: normal, simple

#3140 Collapse @ chains in SMT2 printer
  src/options/printer_options.toml
  src/printer/smt2/smt2_printer.cpp
Labels: minor, simple

#3154 Fix printing issue related to nested quotes
  src/expr/uninterpreted_constant.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/theory_model_builder.cpp
Labels: normal, simple

#3155 Fix regression script for incremental SMT-LIB v2 benchmarks.
  test/regress/regress0/simple-uf.smt
  test/regress/run_regression.py
Labels: major, simple

#3160 Fix drat signature wrt side condition return types
  proofs/signatures/drat.plf
Labels: major, simple

#3163 Scripts for CASC-27
  contrib/run-script-casc27-fnt
  contrib/run-script-casc27-fof
  contrib/run-script-casc27-tfa
  contrib/run-script-casc27-thf
Labels: normal, simple

#3111 Properly parse qualified identifiers
  src/parser/parser.cpp
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/issue2832-qualId.smt2
Labels: complex, normal

#3161 New C++ API: Fix branch prediction in CHECK macros.
  src/api/cvc4cpp.cpp
  src/base/cvc4_check.h
Labels: normal, simple

#3121 New C++ API: Introduce macros for try-catch blocks in Solver.
  src/api/cvc4cpp.cpp
  src/smt/smt_engine.h
  test/unit/api/solver_black.h
Labels: do not merge, normal, simple

#3166 Fix issues with Ninja build system and add configure option.
  CMakeLists.txt
  configure.sh
  examples/CMakeLists.txt
  src/base/CMakeLists.txt
  test/CMakeLists.txt
  test/regress/CMakeLists.txt
  test/system/CMakeLists.txt
  test/unit/CMakeLists.txt
Labels: normal, simple

#3169 Reorganize includes for quantifiers engine
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: moderate, normal

#3173 Add option to only dump unsolved queries for --sygus-query-gen
  src/options/options_handler.cpp
  src/options/options_handler.h
  src/options/quantifiers_modes.h
  src/options/quantifiers_options.toml
  src/theory/quantifiers/query_generator.cpp
  src/theory/quantifiers/query_generator.h
Labels: minor, simple

#3177 Simplify how defined functions are tracked during parsing
  src/expr/symbol_table.cpp
  src/expr/symbol_table.h
  src/parser/cvc/Cvc.g
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/tptp/Tptp.g
Labels: moderate, normal

#3073 New C++ API: Add templated getIndices method for OpTerm
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  test/unit/api/opterm_black.h
  test/unit/api/solver_black.h
Labels: feature, simple

#3178 New C++ API: Add documentation/guidelines for API guards.
  src/api/cvc4cpp.cpp
Labels: normal, simple

#3174 Give rewrite engine pointer to conflict-based instantiation module
  src/theory/quantifiers/rewrite_engine.cpp
  src/theory/quantifiers/rewrite_engine.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: minor, moderate

#3172 Clean smt2 parsing of named attributes
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
Labels: minor, simple

#3165 Introduce smt2 parsing utility ParseOp and refactor
  src/parser/CMakeLists.txt
  src/parser/smt2/Smt2.g
  src/parser/smt2/parse_op.h
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
Labels: moderate, normal

#3152 Implement check abduct feature
  src/options/smt_options.toml
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  test/regress/run_regression.py
Labels: minor, moderate

#3176 Properly implement logic info for separation logic
  src/theory/logic_info.cpp
  src/theory/logic_info.h
  test/regress/regress0/sep/nemp.smt2
  test/regress/regress1/sep/sep-find2.smt2
  test/unit/theory/logic_info_white.h
Labels: minor, simple

#3167 Add string rewrite involving allchar stars
  src/theory/strings/theory_strings_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/rew-check1.smt2
Labels: moderate, normal

#3180 Update option to disable symbolic definitions in strings
  src/theory/strings/theory_strings.cpp
Labels: minor, simple

#3170 New C++ API: Add checks and tests for Solver::simplify.
  src/api/cvc4cpp.cpp
  test/unit/api/solver_black.h
Labels: normal, simple

#3183 SmtEngine: Reorganize class according to guidelines and some clean up.
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
Labels: normal, simple

#3157 Fix issue related to higher-order purification in term database
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers/term_database.h
Labels: normal, simple

#3159 Minor cleaning of sygus term database
  src/theory/quantifiers/sygus/ce_guided_single_inv_sol.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv_sol.h
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
Labels: minor, simple

#3064 Enable Clang-Format for Java
  .clang-format
Labels: minor, simple

#3179 cmake: Export CVC4 library interface.
  CMakeLists.txt
  cmake/CVC4Config.cmake.in
  src/CMakeLists.txt
  src/parser/CMakeLists.txt
Labels: feature, normal, simple

#3151 Call separate SMT engine for single invocation sygus
  src/options/quantifiers_options.toml
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/synth_engine.cpp
Labels: moderate, normal

#3175 Update to standard implementation of getting free variables
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/single_inv_partition.cpp
  src/theory/quantifiers/term_util.cpp
  src/theory/quantifiers/term_util.h
  test/regress/CMakeLists.txt
Labels: minor, simple

#3189 Remove option --continued-execution.
  src/main/command_executor.cpp
  src/main/driver_unified.cpp
  src/options/didyoumean_test.cpp
  src/options/main_options.toml
  src/options/options.h
  src/options/options_public_functions.cpp
  src/smt/smt_engine.cpp
Labels: minor, simple

#3191 cmake: Use ExactVersion instead of SameMinorVersion.
  CMakeLists.txt
Labels: major

#3193 Fix for when to apply single invocation techniques
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
Labels: major, simple

#3190 Mark symbols introduced by named attributes as defined.
  src/parser/smt2/smt2.cpp
Labels: normal, simple

#3186 Move quantifiers relevance module inside E-matching module
  src/theory/quantifiers/ematching/inst_strategy_e_matching.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching.h
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  src/theory/quantifiers/ematching/instantiation_engine.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: minor, simple

#3192 Cleaning make bound var in smt2 parser
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/Smt2.g
Labels: minor, simple

#3168 Context-independent regular expression unfolding
  src/theory/strings/regexp_solver.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/query4674.smt2
  test/regress/regress1/strings/query8485.smt2
Labels: moderate, normal

#3197 New C++ API: Add checks for Solver::checkValid and Solver::checkValidAssuming.
  src/api/cvc4cpp.cpp
  src/smt/smt_engine.h
  test/unit/api/solver_black.h
Labels: normal, simple

#3202 Fixes for sygus inference on quantifier free problems
  src/preprocessing/passes/sygus_inference.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/issue3199.smt2
  test/regress/regress1/sygus/issue3200.smt2
  test/regress/regress1/sygus/issue3201.smt2
Labels: normal, simple

#3204 Local substitutions for context-depdendent simplification in strings
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  test/regress/CMakeLists.txt
  test/regress/regress2/strings/issue3203.smt2
Labels: major, moderate

#3212 Pass synthesis conjecture to sygus modules
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/cegis.h
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/cegis_unif.h
  src/theory/quantifiers/sygus/sygus_module.h
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/sygus/sygus_pbe.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
Labels: normal, simple

#3208 Minor update to term util
  src/theory/quantifiers/term_util.cpp
Labels: minor, simple

#3216 Fix argument in nonlinear extension
  src/theory/arith/nonlinear_extension.cpp
Labels: minor, simple

#3162 Update dynamic splitting strategy for quantifiers
  src/options/quantifiers_options.toml
  src/theory/quantifiers/quant_split.cpp
  src/theory/quantifiers/quant_split.h
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/f993-loss-easy.smt2
  test/regress/regress1/quantifiers/issue993.smt2
Labels: minor, moderate

#3210 Exclude redundant lemmas when tracking inst lemmas.
  src/theory/quantifiers/inst_match_trie.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/issue3205.smt2
Labels: normal, simple

#3207 Document transition inference utility
  src/CMakeLists.txt
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.h
  src/theory/quantifiers/sygus/transition_inference.cpp
  src/theory/quantifiers/sygus/transition_inference.h
Labels: moderate, normal

#3219 Fixes for sygus regressions
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/quant_split.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
Labels: major, simple

#3218 Infer emptiness instead of splitting when a string equality rewrites to a constant
  src/theory/strings/infer_info.cpp
  src/theory/strings/infer_info.h
  src/theory/strings/inference_manager.cpp
  src/theory/strings/theory_strings.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue3217.smt2
Labels: major, moderate

#2795 fix mismatch between "delete" and "new []"
  src/theory/arith/approx_simplex.cpp
Labels: normal, simple

#3232 Removing comments related to question issues
  src/smt/smt_engine.cpp
  src/theory/sets/theory_sets_private.h
  src/theory/theory.h
  src/theory/theory_model_builder.cpp
Labels: minor, simple

#3234 Infer conflicts based on regular expression inclusion
  cmake/FindCxxTest.cmake
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/regexp_operation.h
  src/theory/strings/regexp_solver.cpp
  src/theory/strings/regexp_solver.h
  src/theory/strings/theory_strings_utils.cpp
  src/theory/strings/theory_strings_utils.h
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/regexp_inclusion.smt2
  test/regress/regress0/strings/regexp_inclusion_reduction.smt2
  test/unit/theory/CMakeLists.txt
  test/unit/theory/regexp_operation_black.h
Labels: do not merge, major, moderate

#3220 Better heuristic for str.code/re.range
  src/theory/strings/inference_manager.cpp
  src/theory/strings/theory_strings.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/code-perf.smt2
  test/regress/regress2/strings/range-perf.smt2
Labels: do not merge, normal, simple

#3240 Undo unintential change to FindCxxTest
  cmake/FindCxxTest.cmake
Labels: normal, simple

#3242 Fix out-of-bounds access in regexp inclusion test
  src/theory/strings/regexp_operation.cpp
Labels: major, simple
