Repository cvc5/cvc5, pull requests merged in 2019-11, with the labels that each got.

#3417 Rename datatypes sygus solver
  src/CMakeLists.txt
  src/theory/datatypes/sygus_extension.cpp
  src/theory/datatypes/sygus_extension.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
Labels: minor, simple

#3418 Eagerly beta reduce during sygus to builtin term conversion
  src/theory/datatypes/theory_datatypes_utils.cpp
  src/theory/datatypes/theory_datatypes_utils.h
  src/theory/quantifiers/sygus/sygus_grammar_red.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
  src/theory/quantifiers/sygus/type_info.cpp
Labels: major, moderate

#3326 Fix and refactor TheoryStrings::checkFlatForms()
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: minor, moderate, project

#3369 Fix non-termination in datatype type enumerator
  src/expr/datatype.cpp
  src/expr/datatype.h
  src/expr/type.cpp
  src/expr/type.h
  src/expr/type_node.cpp
  src/expr/type_node.h
  src/theory/datatypes/type_enumerator.cpp
  src/theory/datatypes/type_enumerator.h
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/theory_model_builder.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/datatypes/issue-variant-dt-zero.smt2
  test/regress/regress1/quantifiers/issue3316.smt2
Labels: major, moderate, project

#3431 Eliminate deprecated utility function from sygus
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
Labels: minor, simple

#3306 Make getSynthSolution return a Bool
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus/synth_engine.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  test/regress/regress1/sygus/find_sc_bvult_bvnot.sy
Labels: moderate, normal

#3434 Avoid non-well-founded sygus grammars
  src/parser/smt2/Smt2.g
  test/regress/CMakeLists.txt
  test/regress/regress0/sygus/sygus-no-wf.sy
  test/regress/regress0/sygus/sygus-uf.sy
Labels: major, simple

#3435 Fix ho extensionality in collect model info
  src/theory/uf/ho_extension.cpp
  src/theory/uf/ho_extension.h
Labels: major, moderate

#3432 Make check synth solution robust to auxiliary assertions
  src/smt/smt_engine.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus/synth_engine.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: moderate, normal

#3436 [Regressions] Support for running w/ default args
  test/regress/run_regression.py
Labels: normal, simple

#3439 Refactor type matcher utility
  src/expr/CMakeLists.txt
  src/expr/datatype.cpp
  src/expr/matcher.h
  src/expr/type_matcher.cpp
  src/expr/type_matcher.h
  src/theory/datatypes/theory_datatypes_type_rules.h
  src/theory/quantifiers/theory_quantifiers_type_rules.h
Labels: normal, simple

#3426 Separate model object in non-linear extension
  src/CMakeLists.txt
  src/theory/arith/nl_model.cpp
  src/theory/arith/nl_model.h
  src/theory/arith/nonlinear_extension.cpp
  src/theory/arith/nonlinear_extension.h
Labels: major, moderate

#3420 Remove casts to subclasses of Type in API
  src/api/cvc4cpp.cpp
Labels: moderate, normal

#3433 Support for SyGuS PBE + recursive functions
  src/CMakeLists.txt
  src/options/quantifiers_options.toml
  src/theory/quantifiers/fun_def_evaluator.cpp
  src/theory/quantifiers/fun_def_evaluator.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus/synth_engine.h
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/rec-fun-sygus.sy
Labels: moderate, normal

#3443 Migrate more datatype methods to the Node level
  src/expr/datatype.cpp
  src/expr/type_matcher.cpp
  src/expr/type_matcher.h
  src/expr/type_node.cpp
  src/expr/type_node.h
  src/theory/datatypes/theory_datatypes_type_rules.h
Labels: normal, simple

#3398 Move more string utility functions
  src/theory/strings/infer_info.h
  src/theory/strings/inference_manager.cpp
  src/theory/strings/inference_manager.h
  src/theory/strings/solver_state.cpp
  src/theory/strings/solver_state.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: moderate, normal, project

#3446 cmake: Disable C++ GNU extensions.
  CMakeLists.txt
  src/prop/cnf_stream.h
  src/smt/smt_statistics_registry.h
  src/util/statistics_registry.h
Labels: minor, simple

#3449 Fixes in relations related to datatypes not passed by reference
  src/theory/sets/rels_utils.h
  src/theory/sets/theory_sets_rels.cpp
  src/theory/sets/theory_sets_rewriter.cpp
Labels: normal, simple

#3448 Fix bugs related to sygus higher-order + recursive functions
  src/theory/quantifiers/fun_def_evaluator.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/list_recursor.sy
Labels: moderate, normal

#3450 Eliminate remaining references to type/expr in datatype type rules
  src/theory/datatypes/theory_datatypes_type_rules.h
Labels: normal, simple

#3438 Update README according to the new website
  README.md
Labels: minor

#3447 Fix mkConst<RoundingMode>() for Python bindings
  src/expr/expr_manager.i
Labels: normal, simple

#3451 Add missing utilities for Node-level Datatype API
  src/expr/node_manager.cpp
  src/expr/node_manager.h
  src/expr/type_node.cpp
  src/expr/type_node.h
Labels: normal, simple

#3452 Refactor non-linear extension for model-based refinement
  src/theory/arith/nl_model.cpp
  src/theory/arith/nl_model.h
  src/theory/arith/nonlinear_extension.cpp
  src/theory/arith/nonlinear_extension.h
Labels: moderate, normal

#3454 Distinguish unknown status for model printing
  src/printer/tptp/tptp_printer.cpp
  src/smt/model.cpp
  src/smt/model.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
Labels: moderate, normal

#3457 Allow (set-logic ...) after (reset)
  src/parser/smt2/smt2.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/smtlib/reset-force-logic.smt2
  test/regress/regress0/smtlib/reset-set-logic.smt2
Labels: normal, simple

#3463 Fix wrong kind in sygus version 1 parser
  src/parser/smt2/smt2.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/issue3461.sy
Labels: normal, simple

#3465 Introduce SyGuS datatype API
  src/expr/CMakeLists.txt
  src/expr/sygus_datatype.cpp
  src/expr/sygus_datatype.h
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/sygus_extension.cpp
  src/theory/datatypes/theory_datatypes_utils.cpp
  src/theory/datatypes/theory_datatypes_utils.h
  src/theory/quantifiers/sygus/sygus_grammar_norm.cpp
  src/theory/quantifiers/sygus/sygus_grammar_norm.h
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/type_info.cpp
Labels: moderate, normal

#3466 Use standard interface for sygus default grammar construction
  src/expr/sygus_datatype.cpp
  src/expr/sygus_datatype.h
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.h
  src/theory/quantifiers/sygus/sygus_grammar_norm.cpp
Labels: moderate, normal

#3467 Add support for ThreadSanitizer instrumentation
  CMakeLists.txt
  configure.sh
  src/base/configuration.cpp
  src/base/configuration.h
  src/base/configuration_private.h
  src/options/options_handler.cpp
Labels: normal, simple

#3459 Updates to the unit tests, api, and examples for datatypes
  examples/api/datatypes-new.cpp
  examples/api/datatypes.cpp
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  test/unit/api/solver_black.h
  test/unit/util/datatype_black.h
Labels: moderate, normal

#3473 Improve interface for sygus datatype, fix utilities
  src/expr/sygus_datatype.cpp
  src/expr/sygus_datatype.h
  src/theory/quantifiers/sygus/sygus_grammar_norm.cpp
  src/theory/quantifiers/sygus/sygus_grammar_red.cpp
Labels: moderate, normal

#3471 Use standard sygus interface for abduction and rewrite rule synthesis
  src/preprocessing/passes/synth_rew_rules.cpp
  src/theory/quantifiers/sygus/sygus_abduct.cpp
Labels: minor, moderate

#3464 Use -Wimplicit-fallthrough
  CMakeLists.txt
  src/base/check.h
  src/parser/smt2/smt2.cpp
  src/preprocessing/passes/unconstrained_simplifier.cpp
  src/printer/smt2/smt2_printer.cpp
  src/proof/theory_proof.cpp
  src/prop/cnf_stream.cpp
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_static_learner.cpp
  src/theory/arith/theory_arith_private.cpp
  src/theory/uf/symmetry_breaker.cpp
  src/util/sampler.cpp
  test/unit/theory/theory_arith_white.h
Labels: normal, simple

#3476 Signature documentation update
  proofs/signatures/drat.plf
Labels: minor, simple

#3477 Add a few comments to ProofManager
  src/proof/proof_manager.cpp
Labels: minor, simple

#3478 Fix reduction of `sqrt`
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/issue3475.smt2
  test/regress/regress0/nl/sqrt.smt2
Labels: major, simple

#3482 Lazy evaluation via rec-funs of ITE expressions
  src/theory/quantifiers/fun_def_evaluator.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/rec-fun-while-1.sy
  test/regress/regress1/sygus/rec-fun-while-2.sy
Labels: normal, simple

#3483 Evaluation unfolding for symbolic SyGuS constructors
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/cegis.h
  src/theory/quantifiers/sygus/sygus_eval_unfold.cpp
  src/theory/quantifiers/sygus/sygus_eval_unfold.h
  src/theory/quantifiers/sygus/sygus_unif_rl.cpp
  src/theory/quantifiers/sygus/sygus_unif_strat.cpp
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
Labels: moderate, normal

#3485 Introduce a hard limit for rec-fun evaluation in SyGuS
  src/options/quantifiers_options.toml
  src/theory/quantifiers/fun_def_evaluator.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/rec-fun-while-infinite.sy
Labels: normal, simple

#3489 Minor refactoring of compute model value for nl
  src/theory/arith/nl_model.cpp
Labels: minor, simple

#3496 Better front-end type checking for SyGuS
  src/parser/smt2/smt2.cpp
  src/theory/quantifiers/sygus/type_info.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/sygus/pLTL-sygus-syntax-err.sy
Labels: normal, simple

#3499 Fix indexof range lemma
  src/theory/strings/theory_strings.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/issue3497.smt2
Labels: major, simple

#3502 Enable sygusRecFun by default and fixes SyGuS+RecFun+HO issues
  src/options/quantifiers_options.toml
  src/smt/smt_engine.cpp
  src/theory/quantifiers/fun_def_evaluator.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/list_recursor.sy
  test/regress/regress1/sygus/rec-fun-swap.sy
  test/regress/regress1/sygus/rec-fun-sygus.sy
  test/regress/regress1/sygus/rec-fun-while-1.sy
  test/regress/regress1/sygus/rec-fun-while-2.sy
  test/regress/regress1/sygus/rec-fun-while-infinite.sy
Labels: moderate, normal

#3500 Fix sygus inference for choice functions introduced at preprocess
  src/preprocessing/passes/sygus_inference.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/issue3498.smt2
Labels: normal, simple

#3504 Check free variables in assertions when using SyGuS
  src/options/language.cpp
  src/options/language.h
  src/parser/smt2/Smt2.g
  src/smt/smt_engine.cpp
Labels: moderate, normal

#3501 Fix fast SyGuS enumeration for interpreted constants
  src/theory/quantifiers/sygus/sygus_enumerator.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/once_2.sy
Labels: normal, simple

#3511 Competition build: Skip parsing error regression
  test/regress/regress0/sygus/pLTL-sygus-syntax-err.sy
Labels: major, simple

#3510 improving parsing error messages related to HOL
  src/base/exception.h
  src/expr/node_manager.h
  src/parser/smt2/Smt2.g
Labels: minor, simple
