Repository cvc5/cvc5, pull requests merged in 2019-02, with the labels that each got.

#2824 Fix corner case in stripConstantEndpoints
  src/theory/strings/theory_strings_rewriter.cpp
  test/unit/theory/theory_strings_rewriter_white.h
Labels: minor, simple

#2828 Add rewrite for contains + const strings replace
  src/theory/strings/theory_strings_rewriter.cpp
  src/util/regexp.h
  test/unit/theory/theory_strings_rewriter_white.h
Labels: minor, simple

#2830 Make stripConstantEndpoints() less aggressive
  src/theory/strings/theory_strings_rewriter.cpp
  test/unit/theory/theory_strings_rewriter_white.h
Labels: minor, simple

#2831 New C++ API: Unit tests for declare* functions.
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  test/unit/api/solver_black.h
Labels: normal, simple

#2834 Delete temporary proof files when terminating CVC4
  src/smt/smt_engine_check_proof.cpp
Labels: major, simple

#2836 New C++ API: Remove redundant mkTerm function.
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/api/cvc4cppkind.h
  test/unit/api/solver_black.h
Labels: normal, simple

#2827 Rewrite simple regexp pattern to str.contains
  src/theory/strings/theory_strings_rewriter.cpp
  test/unit/theory/theory_strings_rewriter_white.h
Labels: minor, simple

#2837 New C++ API: Remove redundant declareFun function.
  examples/api/datatypes-new.cpp
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  test/unit/api/solver_black.h
Labels: normal, simple

#2842 ClangFormat: Disable DerivePointerAlignment
  .clang-format
Labels: minor, simple

#2841 Use string stream for proofs instead of tmp files
  src/smt/smt_engine_check_proof.cpp
Labels: major, simple
