Repository cvc5/cvc5, pull requests merged in 2019-05, with the labels that each got.

#2986 Use total versions of div/mod in re-elim-agg
  src/theory/strings/regexp_elim.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/re-agg-total1.smt2
  test/regress/regress1/strings/re-agg-total2.smt2
Labels: normal, simple

#2987 Fix re-elim-agg regressions
  test/regress/regress1/strings/re-agg-total1.smt2
  test/regress/regress1/strings/re-agg-total2.smt2
Labels: major, simple

#2988 Simple optimizations to core strings theory and fix for extf handling
  src/theory/strings/theory_strings.cpp
Labels: normal, simple

#2980 Add support for re.all
  src/parser/smt2/smt2.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/re.all.smt2
Labels: normal, simple

#2967 Fixes for relational triggers
  src/options/quantifiers_options.toml
  src/theory/quantifiers/ematching/candidate_generator.cpp
  src/theory/quantifiers/ematching/inst_match_generator.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching.cpp
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/ematching/trigger.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers/term_database.h
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/nl-pow-trick.smt2
  test/regress/regress1/quantifiers/seu169+1.smt2
  test/regress/regress1/quantifiers/var-eq-trigger-simple.smt2
  test/regress/regress1/quantifiers/var-eq-trigger.smt2
  test/regress/regress2/quantifiers/specsharp-WindowsCard.15.RTE.Terminate_System.Int32.smt2
Labels: moderate, normal

#2994 Disable relational triggers by default
  src/options/quantifiers_options.toml
Labels: major, simple

#2963 Fix printing of bvurem
  src/printer/smt2/smt2_printer.cpp
  test/regress/CMakeLists.txt
  test/regress/regress2/sygus/pbe_bvurem.sy
Labels: normal, simple

#2998 Fix model of Boolean vars with eager bit-blaster
  src/theory/bv/bitblast/eager_bitblaster.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/bv/bool-model.smt2
Labels: major, simple

#3001 BV: Do not enable abstraction when eager bit-blasting by default.
  src/options/options_handler.cpp
Labels: major, simple

#3002 cmake: Install JAR and JNI files for Java bindings.
  src/bindings/java/CMakeLists.txt
Labels: normal, simple

#3000 Fix iterators in Java API
  examples/api/java/CMakeLists.txt
  examples/api/java/Statistics.java
  examples/api/java/UnsatCores.java
  src/bindings/java/CMakeLists.txt
  src/bindings/java_iterator_adapter.h
  src/expr/datatype.i
  src/expr/expr.i
  src/proof/unsat_core.i
  src/smt/command.i
  src/util/statistics.i
Labels: moderate, normal

#3004 Fix BV ITE rewrite
  src/theory/bv/theory_bv_rewriter.cpp
  test/unit/theory/theory_bv_rewriter_white.h
Labels: major, simple

#3006 Support for incremental bit-blasting with CaDiCaL
  cmake/ConfigureCVC4.cmake
  contrib/run-script-smtcomp2019-application
  src/options/options_handler.cpp
  src/prop/cadical.cpp
  src/prop/cadical.h
Labels: normal, simple

#3010 [SMT-COMP 2019] Better strings configuration
  contrib/run-script-smtcomp2019
Labels: normal, simple

#3012 Update QF_NIA strategy for smt comp 2019
  contrib/run-script-smtcomp2019
Labels: normal, simple

#3013 FP: Fix regression test and enable SymFPU on Travis.
  .travis.yml
  test/regress/regress0/fp/down-cast-RNA.smt2
Labels: do not merge, major, simple

#3018 [SMT-COMP 2019] Update run scripts to match tracks
  contrib/run-script-smtcomp2019
  contrib/run-script-smtcomp2019-incremental
  contrib/run-script-smtcomp2019-model-validation
  contrib/run-script-smtcomp2019-unsat-cores
Labels: normal, simple

#3022 Avoid substituting Boolean term variables
  src/theory/theory.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/arrays/bug3020.smt2
Labels: major, moderate

#3025 Quote symbol when printing empty symbol name
  src/printer/smt2/smt2_printer.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/printer/empty_symbol_name.smt2
Labels: major, simple
