Repository cvc5/cvc5, pull requests merged in 2019-01, with the labels that each got.

#2764 New C++ API: Add tests for mk-functions in solver object.
  examples/api/combination-new.cpp
  examples/api/datatypes-new.cpp
  examples/api/linear_arith-new.cpp
  examples/api/sets-new.cpp
  examples/api/strings-new.cpp
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/api/cvc4cppkind.h
  test/unit/api/solver_black.h
  test/unit/api/term_black.h
Labels: normal, simple

#2770 C++ API: Reintroduce zero-value mkBitVector method
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  test/unit/api/solver_black.h
Labels: major, simple

#2674 API/Smt2 parser: refactor termAtomic
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/Smt2.g
  test/unit/api/CMakeLists.txt
  test/unit/api/datatype_api_black.h
  test/unit/api/solver_black.h
Labels: moderate, normal

#2737 [LRAT] A C++ data structure for LRAT.
  src/CMakeLists.txt
  src/proof/lrat/lrat_proof.cpp
  src/proof/lrat/lrat_proof.h
Labels: moderate, normal

#2775 cmake: Disable unit tests for static builds.
  CMakeLists.txt
Labels: normal, simple

#2767 [DRAT] DRAT data structure
  src/CMakeLists.txt
  src/proof/drat/drat_proof.cpp
  src/proof/drat/drat_proof.h
  test/unit/CMakeLists.txt
  test/unit/proof/CMakeLists.txt
  test/unit/proof/drat_proof_black.h
Labels: do not merge

#2773 New C++ API: Add missing getType() calls to kick off type checking.
  src/api/cvc4cpp.cpp
  test/unit/api/solver_black.h
Labels: normal, simple

#2780 Do not rewrite 1-constructor sygus testers to true
  src/theory/datatypes/datatypes_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress2/sygus/min_IC_1.sy
Labels: normal, simple

#2783 New C++ API: Get rid of mkConst functions (simplify API).
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/api/cvc4cppkind.h
  src/parser/smt2/Smt2.g
  test/unit/api/solver_black.h
Labels: normal, simple

#2782 New C++ API: Add unit tests for setInfo, setLogic, setOption.
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/smt/smt_engine.h
  test/unit/api/solver_black.h
Labels: normal, simple

#2793 Only check disequal terms with sygus-rr-verify
  src/theory/datatypes/datatypes_sygus.cpp
Labels: minor, simple

#2798 CMake: Fix search for static libraries
  CMakeLists.txt
Labels: normal, simple

#2799 Fix constant contains ITOS rewrite
  src/theory/strings/theory_strings_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/itos-entail.smt2
  test/regress/regress0/strings/rewrites-v2.smt2
Labels: major, simple

#2805 Add option to print BV constants in binary
  src/options/bv_options.toml
  src/printer/smt2/smt2_printer.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/printer/bv_consts_bin.smt2
  test/regress/regress0/printer/bv_consts_dec.smt2
Labels: minor, simple

#2808 Fix ABC build
  src/smt/smt_engine.cpp
  src/theory/bv/bitblast/aig_bitblaster.cpp
  src/theory/bv/bitblast/aig_bitblaster.h
  src/theory/bv/bitblast/bitblaster.h
Labels: major, simple

#2809 Strings: Introduce checkEntailContains()
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
Labels: major, moderate

#2811 Fix missing-override warning
  src/theory/bv/bitblast/lazy_bitblaster.cpp
  src/theory/bv/bitblast/lazy_bitblaster.h
Labels: minor, simple

#2819 Fix parsing of overloaded parametric datatype selectors
  src/expr/symbol_table.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/datatypes/repeated-selectors-2769.smt2
Labels: normal, simple

#2818 Fix tuple and record CVC printing
  src/printer/cvc/cvc_printer.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/datatypes/tree-get-value.cvc
  test/regress/regress0/printer/tuples_and_records.cvc
Labels: minor, moderate

#2817 Strings: Strengthen multiset reasoning
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
  test/unit/theory/theory_strings_rewriter_white.h
Labels: moderate, normal

#2814 Avoid using ProofManager in non-proof CMS build
  src/prop/cryptominisat.cpp
Labels: major, simple

#2815 Extended DRAT signature to operational DRAT
  proofs/signatures/drat.plf
  proofs/signatures/drat_test.plf
Labels: do not merge

#2822 Strings: Remove redundant replace rewrite
  src/theory/strings/theory_strings_rewriter.cpp
  test/unit/theory/theory_strings_rewriter_white.h
Labels: minor, simple

#2820 New C++ API: Fix checks for mkTerm.
  examples/api/bitvectors-new.cpp
  examples/api/datatypes-new.cpp
  examples/api/extract-new.cpp
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/api/cvc4cppkind.h
  src/expr/expr_manager_template.cpp
  test/unit/api/solver_black.h
Labels: normal, simple

#2821 Fix warning due to catching polymorphic exceptions
  test/unit/proof/drat_proof_black.h
Labels: minor, simple
