Repository cvc5/cvc5, pull requests merged in 2019-12, with the labels that each got.

#3512 Prevent ref count from reaching zero in BV instantiator
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.h
  src/theory/quantifiers/cegqi/ceg_bv_instantiator_utils.cpp
  src/theory/quantifiers/cegqi/ceg_bv_instantiator_utils.h
  test/unit/theory/theory_quantifiers_bv_instantiator_white.h
Labels: moderate, normal

#3515 Ensure quantifiers options are set with --no-strings-lazy-pp
  src/smt/smt_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/issue3440.smt2
Labels: normal, simple

#3509 Fix case of higher-order + sygus inference
  src/preprocessing/passes/sygus_inference.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/issue3507.smt2
Labels: minor, simple

#3493 Update ownership policy for dynamic quantifiers splitting
  src/theory/quantifiers/quant_split.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue3481.smt2
Labels: normal, simple

#3355 OpTerm Refactor: Allow retrieving OpTerm used to create Term in public C++ API
  examples/api/bitvectors-new.cpp
  examples/api/datatypes-new.cpp
  examples/api/extract-new.cpp
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/api/cvc4cppkind.h
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/preprocessing/passes/ackermann.cpp
  src/preprocessing/passes/ackermann.h
  src/smt/smt_engine.cpp
  src/theory/arith/arith_rewriter.cpp
  test/unit/api/opterm_black.h
  test/unit/api/solver_black.h
  test/unit/api/term_black.h
Labels: complex, refactor

#3517 [SMT2 Printer] Quote symbols starting with digit
  src/printer/smt2/smt2_printer.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/printer/symbol_starting_w_digit.smt2
Labels: normal, simple

#3521 Minor refactor: rename opterm_black to op_black
  test/unit/api/CMakeLists.txt
  test/unit/api/op_black.h
Labels: minor, refactor

#3520 Add isNullHelper for API tracing requirements
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
Labels: minor, refactor

#3519 Rewrite `str.contains` used for character matching
  src/theory/strings/theory_strings_rewriter.cpp
  test/unit/theory/theory_strings_rewriter_white.h
Labels: moderate, normal

#3523 Fix clang-format file for brace wrapping with case labels.
  .clang-format
Labels: major, simple

#3518 Improve flexibility of lemma output in non-linear solver
  src/theory/arith/nonlinear_extension.cpp
  src/theory/arith/nonlinear_extension.h
Labels: moderate, normal

#3524 Fix corner case in model construction of strings
  src/theory/strings/theory_strings.cpp
Labels: do not merge, major, moderate

#3516 Fix single invocation solution construction for multiple function case
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/issue3514.smt2
Labels: normal, simple

#3492 Fixes for SyGuS PBE + templated string concatenations + datatypes
  src/theory/evaluator.h
  src/theory/quantifiers/sygus/sygus_unif_io.cpp
  src/theory/quantifiers/sygus/sygus_unif_strat.cpp
Labels: moderate, normal

#3530 Fix regression
  test/regress/regress1/sygus/issue3514.smt2
Labels: major, simple

#3486 New grammar construction modes for SyGuS
  src/options/options_handler.cpp
  src/options/options_handler.h
  src/options/quantifiers_modes.h
  src/options/quantifiers_options.toml
  src/theory/datatypes/theory_datatypes_utils.cpp
  src/theory/datatypes/theory_datatypes_utils.h
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/sygus_explain.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/int-any-const.sy
  test/regress/regress1/sygus/real-any-const.sy
  test/regress/regress1/sygus/strings-any-term1.sy
  test/regress/regress3/strings-any-term.sy
Labels: moderate, normal

#3494 Fix the subtyping relation for functions
  src/expr/type_node.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/ho/fun-subtyping.smt2
Labels: moderate, normal

#3522 Add mkOp for a single Kind
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  test/unit/api/op_black.h
Labels: minor

#3532 Bi-directional unrolling of R* regular expressions
  src/theory/strings/regexp_operation.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/bidir_star.smt2
Labels: moderate, normal

#3531 Refactor mode options for Unif+PI
  src/options/options_handler.cpp
  src/options/options_handler.h
  src/options/quantifiers_modes.h
  src/options/quantifiers_options.toml
  src/smt/smt_engine.cpp
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/cegis_unif.h
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_unif_rl.cpp
  src/theory/quantifiers/sygus/sygus_unif_rl.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  test/regress/regress0/sygus/let-ringer.sy
  test/regress/regress1/quantifiers/horn-simple.smt2
  test/regress/regress1/sygus/car_3.lus.sy
  test/regress/regress1/sygus/cegis-unif-inv-eq-fair.sy
  test/regress/regress1/sygus/cegisunif-depth1.sy
  test/regress/regress1/sygus/constant-dec-tree-bug.sy
  test/regress/regress1/sygus/planning-unif.sy
  test/regress/regress2/sygus/cegisunif-depth1-bv.sy
Labels: normal, simple

#3525 Make nonlinear solver intercept model assignments from the linear arithmetic solver
  src/theory/arith/nl_model.cpp
  src/theory/arith/nl_model.h
  src/theory/arith/nonlinear_extension.cpp
  src/theory/arith/nonlinear_extension.h
  src/theory/arith/theory_arith_private.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/issue3003.smt2
  test/regress/regress0/nl/issue3411.smt2
  test/regress/regress0/nl/sin-cos-346-b-chunk-0169.smt2
  test/regress/regress1/nl/issue3441.smt2
Labels: moderate, normal

#3462 Introduce the Node-level Datatypes API
  src/expr/CMakeLists.txt
  src/expr/datatype.cpp
  src/expr/datatype.h
  src/expr/dtype.cpp
  src/expr/dtype.h
  src/expr/dtype_cons.cpp
  src/expr/dtype_cons.h
  src/expr/dtype_selector.cpp
  src/expr/dtype_selector.h
  src/expr/node_manager.cpp
  src/expr/node_manager.h
  src/expr/type_node.cpp
  src/expr/type_node.h
Labels: complex, normal

#3534 contrib: Setup all dependencies in deps/ directory.
  CMakeLists.txt
  cmake/FindABC.cmake
  cmake/FindANTLR.cmake
  cmake/FindCaDiCaL.cmake
  cmake/FindCryptoMiniSat.cmake
  cmake/FindDrat2Er.cmake
  cmake/FindGLPK.cmake
  cmake/FindGMP.cmake
  cmake/FindLFSC.cmake
  cmake/FindSymFPU.cmake
  contrib/get-abc
  contrib/get-antlr-3.4
  contrib/get-cadical
  contrib/get-cryptominisat
  contrib/get-drat2er
  contrib/get-glpk-cut-log
  contrib/get-gmp
  contrib/get-lfsc-checker
  contrib/get-script-header.sh
  contrib/get-symfpu
Labels: normal, simple

#3535 Add ExprManager as argument to Datatype
  examples/api/datatypes-new.cpp
  examples/api/datatypes.cpp
  examples/api/java/Datatypes.java
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/expr/datatype.cpp
  src/expr/datatype.h
  src/expr/node_manager.cpp
  src/expr/sygus_datatype.cpp
  src/parser/cvc/Cvc.g
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  test/unit/api/datatype_api_black.h
  test/unit/api/solver_black.h
  test/unit/api/sort_black.h
  test/unit/expr/expr_public.h
  test/unit/theory/type_enumerator_white.h
  test/unit/util/datatype_black.h
Labels: moderate, normal

#3255 New algorithm for interpolation and abduction based on unsat cores
  src/CMakeLists.txt
  src/options/quantifiers_options.toml
  src/options/smt_options.toml
  src/smt/smt_engine.cpp
  src/theory/quantifiers/sygus/cegis_core_connective.cpp
  src/theory/quantifiers/sygus/cegis_core_connective.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus-abduct-test-ccore.smt2
  test/regress/regress1/sygus-abduct-test-user.smt2
  test/regress/regress1/sygus/abd-simple-conj-4.smt2
Labels: moderate, normal

#3529 Optimize the rewriter for DT_SYGUS_EVAL
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/theory_datatypes_utils.cpp
  src/theory/datatypes/theory_datatypes_utils.h
  src/theory/quantifiers/sygus/term_database_sygus.cpp
Labels: moderate, normal

#3541 Add lemma for str.to.int/int.to.str
  src/theory/strings/theory_strings_preprocess.cpp
Labels: moderate, normal

#3542 Throw exception instead of warning for approximate models
  src/smt/smt_engine.cpp
Labels: normal, simple

#3544 Use str.subtr in str.to.int/int.to.str reduction
  src/theory/strings/theory_strings_preprocess.cpp
Labels: moderate, normal

#3545 Simplify rewrite for character matching
  src/theory/strings/theory_strings_rewriter.cpp
  test/unit/theory/theory_strings_rewriter_white.h
Labels: normal, simple

#3546 [Regressions] Require proof support for abduction
  test/regress/regress1/sygus-abduct-test-ccore.smt2
  test/regress/regress1/sygus/abd-simple-conj-4.smt2
Labels: major, simple

#3547 Make theory rewriters non-static
  src/CMakeLists.txt
  src/theory/arith/arith_rewriter.h
  src/theory/arrays/theory_arrays_rewriter.h
  src/theory/booleans/theory_bool_rewriter.h
  src/theory/builtin/theory_builtin_rewriter.cpp
  src/theory/builtin/theory_builtin_rewriter.h
  src/theory/bv/theory_bv_rewriter.cpp
  src/theory/bv/theory_bv_rewriter.h
  src/theory/datatypes/datatypes_rewriter.h
  src/theory/fp/theory_fp_rewriter.cpp
  src/theory/fp/theory_fp_rewriter.h
  src/theory/mkrewriter
  src/theory/quantifiers/quantifiers_rewriter.h
  src/theory/rewriter.cpp
  src/theory/rewriter.h
  src/theory/rewriter_tables_template.h
  src/theory/sep/theory_sep_rewriter.h
  src/theory/sets/theory_sets_rewriter.h
  src/theory/strings/regexp_elim.cpp
  src/theory/strings/theory_strings_rewriter.h
  src/theory/theory_rewriter.h
  src/theory/uf/theory_uf_rewriter.h
Labels: moderate, normal

#3543 Fix case of uninterpreted constant instantiation in FMF
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/rep_set.cpp
  src/theory/rep_set.h
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue3537.smt2
Labels: major, simple

#3539 Disable sygus inference when combined with incremental and proofs
  src/smt/smt_engine.cpp
Labels: minor, simple

#3550 Allow unsat cores with sygus inference
  src/smt/smt_engine.cpp
  test/regress/regress1/quantifiers/issue3537.smt2
Labels: major, simple

#3551 Fix ufho issues
  src/options/options.h
  src/options/options_public_functions.cpp
  src/parser/smt2/smt2.cpp
  test/regress/regress0/declare-fun-is-match.smt2
Labels: normal, simple

#3549 Incorporate rewriting on demand in the evaluator
  src/theory/evaluator.cpp
  src/theory/evaluator.h
Labels: moderate, normal

#3553 Support symbolic unfolding in UNIF+PI
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_unif_rl.cpp
Labels: minor, moderate

#3324 Do not substitute beneath arithmetic terms in the non-linear solver
  src/theory/arith/arith_utilities.cpp
  src/theory/arith/arith_utilities.h
  src/theory/arith/nl_model.cpp
  src/theory/arith/nonlinear_extension.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/nl/issue3307.smt2
Labels: moderate, normal

#3540 Activate node-level datatype API
  src/expr/datatype.cpp
  src/expr/datatype.h
  src/expr/expr_manager_template.cpp
  src/expr/node_manager.cpp
Labels: moderate, normal

#3555 Fix CEGIS refinement for recursive functions evaluation
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/node-discrete.sy
Labels: normal, simple

#3557 Fixes for regressions
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/node-discrete.sy
Labels: major, simple

#3556 Use the node-level datatypes API
  src/expr/datatype.cpp
  src/expr/expr_manager_template.cpp
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/sygus_extension.cpp
  src/theory/datatypes/sygus_simple_sym.cpp
  src/theory/datatypes/sygus_simple_sym.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
  src/theory/datatypes/theory_datatypes_type_rules.h
  src/theory/datatypes/theory_datatypes_utils.cpp
  src/theory/datatypes/theory_datatypes_utils.h
  src/theory/datatypes/type_enumerator.cpp
  src/theory/datatypes/type_enumerator.h
  src/theory/quantifiers/cegqi/ceg_dt_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/ematching/candidate_generator.cpp
  src/theory/quantifiers/ematching/candidate_generator.h
  src/theory/quantifiers/ematching/inst_match_generator.cpp
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/quant_split.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/skolemize.cpp
  src/theory/quantifiers/skolemize.h
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv_sol.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv_sol.h
  src/theory/quantifiers/sygus/cegis_core_connective.cpp
  src/theory/quantifiers/sygus/enum_stream_substitution.cpp
  src/theory/quantifiers/sygus/sygus_abduct.cpp
  src/theory/quantifiers/sygus/sygus_enumerator.cpp
  src/theory/quantifiers/sygus/sygus_eval_unfold.cpp
  src/theory/quantifiers/sygus/sygus_explain.cpp
  src/theory/quantifiers/sygus/sygus_grammar_red.cpp
  src/theory/quantifiers/sygus/sygus_grammar_red.h
  src/theory/quantifiers/sygus/sygus_repair_const.cpp
  src/theory/quantifiers/sygus/sygus_unif_strat.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
  src/theory/quantifiers/sygus/type_info.cpp
  src/theory/quantifiers/sygus_sampler.cpp
  src/theory/sets/rels_utils.h
  src/theory/sets/theory_sets_rels.cpp
  src/theory/sets/theory_sets_rewriter.cpp
  src/theory/theory_model_builder.cpp
Labels: moderate, normal

#3558 Fix Unif+PI algorithm with symbolic unfolding
  src/theory/quantifiers/sygus/sygus_unif_rl.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/unifpi-solve-car_1.lus.sy
Labels: normal, simple

#3559 Make CEGIS sampling robust to non-vanilla CEGIS
  src/theory/quantifiers/sygus/cegis.cpp
  test/regress/CMakeLists.txt
  test/regress/regress2/sygus/DRAGON_1.lus.sy
Labels: normal, simple

#3563 FP converter: convert: Use std::vector as instead of std::stack.
  src/theory/fp/fp_converter.cpp
Labels: normal, simple

#3560 Disable check-synth-sol in regression with recursive functions
  test/regress/regress1/sygus/node-discrete.sy
Labels: major, simple

#3312 Add support for set comprehension
  src/expr/node.h
  src/parser/parser.h
  src/parser/smt2/Smt2.g
  src/printer/smt2/smt2_printer.cpp
  src/theory/sets/kinds
  src/theory/sets/solver_state.cpp
  src/theory/sets/solver_state.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
  src/theory/sets/theory_sets_type_rules.h
  test/regress/CMakeLists.txt
  test/regress/regress0/sets/comp-qf-error.smt2
  test/regress/regress1/sets/comp-intersect.smt2
  test/regress/regress1/sets/comp-odd.smt2
  test/regress/regress1/sets/comp-pos-member.smt2
  test/regress/regress1/sets/comp-positive.smt2
  test/regress/regress1/sets/set-comp-sat.smt2
Labels: moderate, normal

#3569 Simple optimizations for the core rewriter
  src/expr/mkexpr
  src/expr/node.cpp
  src/expr/type_checker.h
  src/expr/type_checker_template.cpp
  src/theory/rewriter.cpp
Labels: minor, moderate

#3570 Minor improvement to evaluator
  src/theory/evaluator.cpp
Labels: normal, simple

#3574 Revert evaluate as node
  src/theory/evaluator.cpp
Labels: major, simple

#3575 Fix evaluator for non-evaluatable nodes
  src/theory/evaluator.cpp
  src/theory/evaluator.h
  src/theory/quantifiers/sygus/term_database_sygus.cpp
Labels: moderate, normal

#3568 Move Datatype management to ExprManager
  src/expr/expr_manager_template.cpp
  src/expr/expr_manager_template.h
  src/expr/node_manager.cpp
  src/expr/node_manager.h
  src/expr/type.cpp
  src/printer/cvc/cvc_printer.cpp
  src/printer/smt2/smt2_printer.cpp
Labels: moderate, normal

#3372 Ackermann Task2: Support ackermannization on uninterpreted sorts in BV
  src/preprocessing/passes/ackermann.cpp
  src/preprocessing/passes/ackermann.h
  src/smt/smt_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/bv/ackermann5.smt2
  test/regress/regress0/bv/ackermann6.smt2
  test/regress/regress0/bv/ackermann7.smt2
  test/regress/regress0/bv/ackermann8.smt2
  test/unit/theory/theory_bv_white.h
Labels: moderate, normal

#3377 Extend model construction with assignment exclusion set
  src/theory/theory_model.cpp
  src/theory/theory_model.h
  src/theory/theory_model_builder.cpp
  src/theory/theory_model_builder.h
Labels: complex, normal

#3576 Use the evaluator utility in the function definition evaluator
  src/theory/evaluator.cpp
  src/theory/evaluator.h
  src/theory/quantifiers/fun_def_evaluator.cpp
  src/theory/quantifiers/fun_def_evaluator.h
Labels: moderate, normal

#3554 Fix spurious parse error for rational real array constants
  src/parser/smt2/smt2.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/array-const-real-parse.smt2
Labels: normal, simple

#3548 Avoid calling rewriter from type checker
  src/theory/builtin/theory_builtin_rewriter.h
  src/theory/builtin/theory_builtin_type_rules.h
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp_rewriter.cpp
  src/theory/theory_rewriter.h
  test/regress/CMakeLists.txt
  test/regress/regress0/fp/issue3536.smt2
Labels: moderate, normal

#3577 Increment Taylor degree for tangent and secant plane inferences for transcendentals
  src/theory/arith/nonlinear_extension.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/nl/exp-soundness-bound.smt2
Labels: major, simple

#3579 Fix typo in smt_options.toml.
  src/options/smt_options.toml
Labels: bug, major

#3578 Define all options modified by ENABLE_BEST using cvc4_option
  CMakeLists.txt
Labels: do not merge

#3581 Initial support for string reverse
  src/parser/cvc/Cvc.g
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/strings/kinds
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
  src/util/regexp.h
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/parser-syms.cvc
  test/regress/regress0/strings/str-rev-simple.smt2
  test/regress/regress1/strings/rev-conv1.smt2
  test/regress/regress1/strings/rev-ex1.smt2
  test/regress/regress1/strings/rev-ex2.smt2
  test/regress/regress1/strings/rev-ex3.smt2
  test/regress/regress1/strings/rev-ex4.smt2
  test/regress/regress1/strings/rev-ex5.smt2
  test/regress/regress1/strings/str-rev-simple-s.smt2
Labels: minor, moderate

#3484 [proof] ITE translation fix
  src/proof/arith_proof.cpp
  src/proof/arith_proof.h
  src/proof/theory_proof.cpp
  src/proof/theory_proof.h
  test/regress/CMakeLists.txt
  test/regress/regress0/arith/ite-lift.smt2
Labels: bug, minor, simple
