Repository cvc5/cvc5, pull requests merged in 2019-09, with the labels that each got.

#3227 Remove duplicate regression tests.
  test/regress/CMakeLists.txt
  test/regress/regress0/bug374.delta01.smt
  test/regress/regress0/datatypes/boolean-terms-parametric-datatype-2.cvc
  test/regress/regress0/expect/scrub.04.smt2
  test/regress/regress0/hung10_itesdk_output2.smt2
  test/regress/regress0/hung13sdk_output2.smt2
  test/regress/regress0/quantifiers/qbv-test-invert-bvlshr-0-neq.smt2
  test/regress/regress0/queries0.cvc
  test/regress/regress1/bug216.smt2
  test/regress/regress1/rels/join-eq-structure_0_1.cvc
  test/regress/regress1/rels/strat_0_1.cvc
  test/regress/regress2/arith/qlock-4-10-9.base.cvc.smt2
  test/regress/regress2/quantifiers/mutualrec2.cvc
  test/regress/regress2/xs-09-16-3-4-1-5.decn.smt
  test/regress/regress3/incorrect2.smt
Labels: normal, simple

#3231 Fixes related to destructing null
  src/base/exception.cpp
  src/theory/arith/cut_log.cpp
  src/theory/arith/cut_log.h
  src/theory/type_set.cpp
Labels: minor, simple

#3233 Fix DAGification for printer.
  src/printer/dagification_visitor.cpp
Labels: bug, normal

#3238 Move getCounterexampleLiteral out of term utilities
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.h
  src/theory/quantifiers/term_util.cpp
  src/theory/quantifiers/term_util.h
Labels: minor, simple

#3244 More details in substitution function documentation
  src/expr/node_algorithm.h
Labels: minor, simple

#3195 Towards incremental SyGuS in SMT engine
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
Labels: moderate, normal, project

#3239 Refactoring CEGQI interface
  src/theory/quantifiers/cegqi/ceg_arith_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_arith_instantiator.h
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.h
  src/theory/quantifiers/cegqi/ceg_dt_instantiator.h
  src/theory/quantifiers/cegqi/ceg_epr_instantiator.h
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.h
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: moderate, normal

#3209 Explicitly pass current sygus solution to exclude
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
Labels: moderate, normal

#3243 Model API for domain elements
  src/printer/smt2/smt2_printer.cpp
  src/smt/model.h
  src/theory/theory_model.cpp
  src/theory/theory_model.h
Labels: moderate, normal

#3256 Make CEGQI term type to enum
  src/theory/quantifiers/cegqi/ceg_arith_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_arith_instantiator.h
  src/theory/quantifiers/cegqi/ceg_epr_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.h
Labels: minor, simple

#3260 Remove parsing/printing of meta-info command.
  src/parser/smt2/Smt2.g
  src/printer/smt2/smt2_printer.cpp
Labels: minor, simple

#3236 Remove portfolio
  CMakeLists.txt
  cmake/ConfigDebug.cmake
  cmake/ConfigProduction.cmake
  cmake/ConfigTesting.cmake
  configure.sh
  doc/CMakeLists.txt
  licenses/channel.h-LICENSE
  src/CMakeLists.txt
  src/expr/CMakeLists.txt
  src/expr/expr_manager_template.h
  src/expr/expr_template.h
  src/expr/node.h
  src/expr/pickle_data.cpp
  src/expr/pickle_data.h
  src/expr/pickler.cpp
  src/expr/pickler.h
  src/main/CMakeLists.txt
  src/main/command_executor_portfolio.cpp
  src/main/command_executor_portfolio.h
  src/main/driver_unified.cpp
  src/main/portfolio.cpp
  src/main/portfolio.h
  src/main/portfolio_util.cpp
  src/main/portfolio_util.h
  src/options/didyoumean_test.cpp
  src/options/main_options.toml
  src/options/options.h
  src/options/options_public_functions.cpp
  src/options/options_template.cpp
  src/prop/prop_engine.cpp
  src/smt/dump.h
  src/smt_util/lemma_output_channel.h
  src/util/CMakeLists.txt
  src/util/channel.h
Labels: normal, simple

#3265 Fix helper function in cegqi for strict bounds
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
Labels: major, simple

#3267 Fix issue related to enum in cegqi
  src/theory/quantifiers/cegqi/ceg_arith_instantiator.cpp
Labels: major, simple

#3246 Fix constructor type printing
  src/printer/smt2/smt2_printer.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/datatypes/dt-param-2.6-print.smt2
Labels: normal, simple

#3262 Infrastructure for instantiation rewriter
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/instantiate.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: minor, simple

#3252 Fix type assertion in getSynthSolutions
  src/theory/quantifiers/sygus/synth_conjecture.cpp
Labels: minor, simple

#2778 Fix not to output all warnings
  src/base/exception.h
  src/context/cdlist_forward.h
  src/expr/datatype.h
Labels: minor, simple

#3261 Refactoring finite bounds in Quantifiers Engine
  src/CMakeLists.txt
  src/theory/quantifiers/first_order_model.cpp
  src/theory/quantifiers/first_order_model.h
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/fmf/bounded_integers.h
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/quantifiers/fmf/model_builder.cpp
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/quant_rep_bound_ext.cpp
  src/theory/quantifiers/quant_rep_bound_ext.h
  src/theory/quantifiers/quant_util.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
  src/theory/rep_set.h
Labels: minor, moderate

#3085 Split, refactor and document the theory of sets
  src/CMakeLists.txt
  src/theory/sets/cardinality_extension.cpp
  src/theory/sets/cardinality_extension.h
  src/theory/sets/inference_manager.cpp
  src/theory/sets/inference_manager.h
  src/theory/sets/solver_state.cpp
  src/theory/sets/solver_state.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
  src/theory/sets/theory_sets_rels.cpp
  src/theory/sets/theory_sets_rels.h
Labels: moderate, normal

#3280 Move higher-order matching predicate
  src/theory/quantifiers/ematching/ho_trigger.cpp
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers/term_database.h
  src/theory/quantifiers/term_util.cpp
  src/theory/quantifiers/term_util.h
  src/theory/uf/ho_extension.cpp
Labels: minor, project, simple

#3259 Disallow let in sygus grammars, check for free variables in sygus constructors
  src/expr/datatype.cpp
  src/parser/parser.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/printer/sygus_print_callback.cpp
  src/printer/sygus_print_callback.h
  test/regress/regress0/sygus/let-ringer.sy
  test/regress/regress0/sygus/let-simp.sy
  test/regress/regress1/sygus/abv.sy
  test/regress/regress1/sygus/let-bug-simp.sy
  test/regress/regress1/sygus/tester.sy
  test/regress/regress1/sygus/twolets2-orig.sy
Labels: moderate, normal

#3285 parser: Improve error message for unrecognized input file format.
  src/parser/antlr_input.cpp
Labels: normal, simple

#3289 Initialize fields in sets inference manager
  src/theory/sets/inference_manager.cpp
Labels: minor, simple

#3291 Adding new scripts for CASC/TPTP
  contrib/competitions/casc/run-script-casc27-tfn-nr
  contrib/competitions/casc/run-script-casc27-thf-sat-nr
Labels: minor, simple

#3284 Fix compiler warning in options.cpp.
  src/options/options_template.cpp
Labels: normal, simple

#3283 Return RecoverableModalException when model is not available.
  src/smt/smt_engine.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: moderate, normal

#3278 Move virtual term substitution utilities to own file and document
  src/CMakeLists.txt
  src/theory/quantifiers/cegqi/ceg_arith_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_arith_instantiator.h
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.h
  src/theory/quantifiers/cegqi/vts_term_cache.cpp
  src/theory/quantifiers/cegqi/vts_term_cache.h
  src/theory/quantifiers/term_util.cpp
  src/theory/quantifiers/term_util.h
Labels: minor, project, simple

#3158 Fix HO model construction for functions having Boolean arguments
  src/theory/builtin/theory_builtin_rewriter.cpp
  src/theory/theory_model.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/ho/issue3136-fconst-bool-bool.smt2
Labels: moderate, normal

#3187 Sygus type info class
  src/CMakeLists.txt
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/datatypes/sygus_simple_sym.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv_sol.cpp
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/enum_stream_substitution.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
  src/theory/quantifiers/sygus/type_info.cpp
  src/theory/quantifiers/sygus/type_info.h
  src/theory/quantifiers/sygus/type_node_id_trie.cpp
  src/theory/quantifiers/sygus/type_node_id_trie.h
Labels: moderate, normal, project

#3279 Move specific attributes out of term util
  src/theory/quantifiers/fmf/bounded_integers.h
  src/theory/quantifiers/fmf/model_builder.cpp
  src/theory/quantifiers/fun_def_process.h
  src/theory/quantifiers/local_theory_ext.h
  src/theory/quantifiers/rewrite_engine.h
  src/theory/quantifiers/sygus/sygus_abduct.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.h
  src/theory/quantifiers/term_util.h
Labels: minor, project, simple

#3282 Remove equality inference option for quantifiers
  src/options/quantifiers_options.toml
  src/theory/quantifiers/equality_query.cpp
  src/theory/quantifiers/equality_query.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  test/regress/regress1/quantifiers/infer-arith-trigger-eq.smt2
Labels: minor, project, simple

#3294 Fix spurious meta-info in regression
  test/regress/regress1/ho/issue3136-fconst-bool-bool.smt2
Labels: major, simple

#3290 Remove parameterized check
  src/expr/node_builder.h
Labels: minor, simple

#3268 Avoid computing cardinality when constructing models
  src/expr/datatype.cpp
  src/expr/type.cpp
  src/expr/type.h
  src/expr/type_node.cpp
  src/expr/type_node.h
  src/theory/theory_model_builder.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/datatypes/issue3266-small.smt2
Labels: moderate, normal

#3293 Encapsulate relevant domain
  src/theory/quantifiers/inst_strategy_enumerative.cpp
  src/theory/quantifiers/inst_strategy_enumerative.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: minor, project, simple

#3295 Minor cleaning in expr_manager_template
  src/expr/expr_manager_template.cpp
  src/expr/expr_manager_template.h
Labels: minor, simple

#3297 Decouple fmf-bound and finite-model-find
  src/smt/smt_engine.cpp
  src/theory/quantifiers_engine.cpp
  test/regress/regress0/fmf/fmf-strange-bounds-2.smt2
  test/regress/regress1/fmf/bound-int-alt.smt2
  test/regress/regress2/quantifiers/net-policy-no-time.smt2
Labels: minor, simple

#3296 Add support for creating constant arrays to the new C++ API
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  test/unit/api/solver_black.h
Labels: feature, simple

#3281 Support context-(in)dependent decision strategies.
  src/theory/arrays/theory_arrays.cpp
  src/theory/arrays/theory_arrays.h
  src/theory/decision_manager.cpp
  src/theory/decision_manager.h
  src/theory/strings/theory_strings.cpp
  src/theory/theory_engine.cpp
  src/theory/uf/cardinality_extension.cpp
  test/regress/CMakeLists.txt
  test/regress/regress2/strings/repl-repl-i-no-push.smt2
Labels: moderate, normal, project

#3304 Return choice functions for approximate values in get-value
  src/printer/smt2/smt2_printer.cpp
  src/smt/smt_engine.cpp
  src/theory/theory_model.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/sqrt2-value.smt2
Labels: major, moderate

#3305 Fix printing of instantiation patterns
  src/printer/smt2/smt2_printer.cpp
Labels: minor, simple

#3226 Add Windows cross-compiling instructions to INSTALL.md.
  INSTALL.md
Labels: normal, simple

#3303 Add isParameterized function to Expr
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/expr/expr_template.cpp
  src/expr/expr_template.h
  src/parser/smt2/smt2.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/concat_extract_example.sy
Labels: major, simple

#3273 Fix off by one error in strings flat form explanation
  src/theory/strings/theory_strings.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue3272.smt2
Labels: major, simple

#3323 CVC print support for recoverable failure
  src/printer/cvc/cvc_printer.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/cvc-rerror-print.cvc
Labels: minor, simple

#2474 Make substitution index context-independent
  src/preprocessing/assertion_pipeline.cpp
  src/preprocessing/assertion_pipeline.h
  src/preprocessing/passes/apply_substs.cpp
  src/preprocessing/passes/non_clausal_simp.cpp
  src/preprocessing/preprocessing_pass_context.cpp
  src/preprocessing/preprocessing_pass_context.h
  src/smt/smt_engine.cpp
Labels: moderate, normal

#3254 Fix case of disjunctive conclusion in strings
  src/theory/strings/inference_manager.cpp
  src/theory/strings/theory_strings.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/issue3247.smt2
Labels: moderate, normal

#3258 Support smt2 language "match" term
  src/expr/node.h
  src/parser/smt2/Smt2.g
  src/printer/smt2/smt2_printer.cpp
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/kinds
  src/theory/datatypes/theory_datatypes_type_rules.h
  test/regress/regress1/datatypes/dt-color-2.6.smt2
Labels: complex, normal, project

#2835 Introduce template classes for simple type rules
  src/expr/type_checker_template.cpp
  src/expr/type_checker_util.h
  src/theory/arith/kinds
  src/theory/arith/theory_arith_type_rules.h
  src/theory/bv/kinds
  src/theory/bv/theory_bv_type_rules.h
  src/theory/strings/kinds
  src/theory/strings/theory_strings_type_rules.h
Labels: moderate, normal

#3322 Fail single invocation techniques when utility inference fails.
  src/theory/quantifiers/single_inv_partition.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/issue3320-quant.sy
Labels: major, simple

#3301 Avoid cases of empty sygus grammars
  src/parser/smt2/Smt2.g
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/only-const-grammar.sy
Labels: moderate, normal

#3318 Add help message for sygus 2.0
  src/options/options_template.cpp
Labels: normal, simple

#2957 Add rewrite for splitting equalities
  src/theory/strings/theory_strings_rewriter.cpp
  test/unit/theory/theory_strings_rewriter_white.h
Labels: moderate, normal, project
