Repository cvc5/cvc5, pull requests merged in 2019-10, with the labels that each got.

#3328 Trivial solve method for single invocation sygus
  src/theory/quantifiers/quantifiers_rewriter.h
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.h
  test/regress/CMakeLists.txt
  test/regress/regress0/sygus/cegqi-si-string-triv-2fun.sy
  test/regress/regress0/sygus/cegqi-si-string-triv.sy
Labels: moderate, normal

#3333 [SMT-COMP] Remove --unconstrained-simp for incremental QF_LIA
  contrib/competitions/smt-comp/run-script-smtcomp-current-incremental
Labels: minor, simple

#3348 Fix compiler warning.
  src/api/cvc4cpp.cpp
Labels: normal, simple

#3330 Add missing type definitions to CDHashMap iterator
  src/context/cdhashmap.h
Labels: major, simple

#3351 Travis: Reenable building and running of examples.
  .travis.yml
  examples/CMakeLists.txt
Labels: major, simple

#3310 Avoid duplicate lemmas in datatypes
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
Labels: moderate, normal

#3358 Fix str to int reduction
  src/theory/strings/theory_strings_preprocess.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue3357.smt2
Labels: major, simple

#3359 Fix typo in regression
  test/regress/regress1/strings/issue3357.smt2
Labels: major, simple

#3334 [SMT2 Parser] Move code of `rewriterulesCommand`
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
Labels: do not merge, moderate, normal

#3360 New C++ API: Add Term::getId().
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/expr/expr_template.cpp
  src/expr/expr_template.h
  src/expr/metakind_template.h
  src/expr/node.h
  src/expr/node_value.h
  test/unit/api/term_black.h
Labels: major, project, simple

#3365 Build system: Add build type for incremental competition builds.
  CMakeLists.txt
  configure.sh
Labels: normal, simple

#3332 Disallow --proof and --incremental
  src/smt/smt_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/options/invalid_option_inc_proofs.smt2
Labels: minor, simple

#3346 [CVC Parser] Add support for regular expressions
  src/parser/cvc/Cvc.g
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/regexp-native-simple.cvc
Labels: normal, simple

#3371 Fix method for getting arithmetic function definition body
  src/theory/quantifiers/quantifiers_attributes.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue3317.smt2
Labels: normal, simple

#3370 Limit cases of sygus inference based on type
  src/preprocessing/passes/sygus_inference.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.h
  test/regress/CMakeLists.txt
  test/regress/regress0/sygus/issue3356-syg-inf-usort.smt2
  test/regress/regress1/quantifiers/issue3250-syg-inf-q.smt2
Labels: minor, simple

#3364 New C++ API: Term: Add missing checks for null.
  src/api/cvc4cpp.cpp
  test/unit/api/term_black.h
Labels: normal, project, simple

#3373 cmake: Fix include of CVC4JavaTargets.cmake.
  cmake/CVC4Config.cmake.in
Labels: bug, major, simple

#3363 Avoid printing success for `--force-logic`
  src/parser/smt2/smt2.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/parser/force_logic_success.smt2
Labels: major, simple

#3378 test: Add TS_UTILS_EXPECT_ABORT macro for unit tests.
  test/unit/test_utils.h
  test/unit/util/check_white.h
Labels: major, simple

#3380 Warning instead of assertion for failing propagating instance
  src/theory/quantifiers/quant_conflict_find.cpp
Labels: minor, simple

#3379 Make order of theories explicit in the source code.
  src/CMakeLists.txt
  src/cvc4.i
  src/expr/expr_template.h
  src/expr/kind_template.cpp
  src/expr/kind_template.h
  src/expr/mkkind
  src/parser/smt2/smt2.cpp
  src/theory/mktheorytraits
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/theory_id.cpp
  src/theory/theory_id.h
  src/theory/theory_id.i
  src/theory/theory_traits_template.h
Labels: normal, simple

#3382 Add support for UBSan instrumentation
  CMakeLists.txt
  configure.sh
  src/base/configuration.cpp
  src/base/configuration.h
  src/base/configuration_private.h
  src/options/options_handler.cpp
  src/theory/bv/bitblast/aig_bitblaster.h
Labels: normal, simple

#3384 Check that logic is set when synth-fun command is encountered
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/sygus/no-logic.sy
Labels: major, simple

#2929 Eliminate negative constant coefficients in div/mod
  src/theory/arith/arith_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/arith/issue1399.smt2
Labels: moderate, normal

#3387 Minor refactor in strings rewriter
  src/theory/strings/theory_strings_rewriter.cpp
Labels: minor, simple

#3385 Ensure lemmas from sygus repair const are guarded
  src/theory/quantifiers/sygus/cegis.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/repair-const-unk.sy
Labels: normal, simple

#3386 Apply sygus repair constant techniques restricted to refinement lemmas
  src/smt/smt_engine.cpp
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/cegis.h
  src/theory/quantifiers/sygus/sygus_repair_const.cpp
  src/theory/quantifiers/sygus/sygus_repair_const.h
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/coeff-solve-inv.sy
  test/regress/regress1/sygus/repair-const-rl.sy
Labels: minor, moderate

#3319 Support UF in default sygus grammars
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/sygus_abduct.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/transition_inference.cpp
  src/theory/quantifiers/sygus/transition_inference.h
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/ho-sygus.sy
  test/regress/regress1/sygus/uf-abduct.smt2
Labels: moderate, normal, project

#3389 Remove spurious sygus regression
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/repair-const-unk.sy
Labels: major, simple

#3388 Disable regression test for competition build
  test/regress/regress0/sygus/no-logic.sy
Labels: major, simple

#3393 Fix regression
  test/regress/regress0/sygus/no-logic.sy
Labels: major, simple

#3383 Fix OOB access
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: normal, simple

#3390 Remove remaining references to Boost and Autotools
  CMakeLists.txt
  COPYING
Labels: minor, simple

#3391 Fix line numbers in templates
  src/expr/expr_template.h
  src/expr/kind_template.cpp
  src/expr/kind_template.h
Labels: minor, simple

#3181 Solver state for theory of strings
  src/CMakeLists.txt
  src/theory/strings/inference_manager.cpp
  src/theory/strings/inference_manager.h
  src/theory/strings/regexp_solver.cpp
  src/theory/strings/regexp_solver.h
  src/theory/strings/solver_state.cpp
  src/theory/strings/solver_state.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  src/theory/strings/theory_strings_utils.cpp
  src/theory/strings/theory_strings_utils.h
Labels: normal, project, simple

#3397 Move datatype utility functions to own file
  src/CMakeLists.txt
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/datatypes_rewriter.h
  src/theory/datatypes/datatypes_sygus.cpp
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes_utils.cpp
  src/theory/datatypes/theory_datatypes_utils.h
  src/theory/datatypes/type_enumerator.cpp
  src/theory/quantifiers/sygus/sygus_enumerator.cpp
  src/theory/quantifiers/sygus/sygus_eval_unfold.cpp
  src/theory/quantifiers/sygus/sygus_explain.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_grammar_norm.cpp
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/sygus/sygus_process_conj.cpp
  src/theory/quantifiers/sygus/sygus_repair_const.cpp
  src/theory/quantifiers/sygus/sygus_unif.cpp
  src/theory/quantifiers/sygus/sygus_unif_io.cpp
  src/theory/quantifiers/sygus/sygus_unif_rl.cpp
  src/theory/quantifiers/sygus/sygus_unif_strat.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/type_info.cpp
Labels: major, project, simple

#3396 Update overflow check to handle negative numbers
  src/api/cvc4cpp.cpp
  test/unit/api/solver_black.h
Labels: simple

#3400 NodeValue: Eliminate redundant NBITS macros.
  src/api/cvc4cppkind.h
  src/expr/metakind_template.h
  src/expr/mkmetakind
  src/expr/node_builder.h
  src/expr/node_value.h
  src/theory/booleans/theory_bool_rewriter.cpp
Labels: do not merge, normal, simple

#3381 Refactoring skolems for sets
  src/theory/sets/skolem_cache.cpp
  src/theory/sets/skolem_cache.h
  src/theory/sets/solver_state.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_rels.cpp
Labels: moderate, normal, project

#3313 Fixes for SyGuS + regular expressions
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/regexp_operation.h
  src/theory/strings/regexp_solver.cpp
  src/theory/strings/regexp_solver.h
  src/theory/strings/theory_strings_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/re-concat.sy
Labels: moderate, normal

#3403 Fix global-declarations support
  src/parser/parser.cpp
  src/parser/parser.h
  test/regress/CMakeLists.txt
  test/regress/regress0/datatypes/bug597-rbt.smt2
  test/regress/regress0/smtlib/global-decls.smt2
Labels: normal, simple

#3409 Fix collect model info for higher-order
  src/theory/theory_model_builder.cpp
  src/theory/uf/ho_extension.cpp
  src/theory/uf/theory_uf.cpp
Labels: major, moderate

#3415 Fix integer division rewrite
  src/theory/arith/arith_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/arith/issue3412.smt2
  test/regress/regress0/arith/issue3413.smt2
Labels: major, simple

#3410 Fix for non-linear models
  src/theory/arith/nonlinear_extension.cpp
  src/theory/theory_model.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/issue3407.smt2
Labels: major, moderate

#3419 Split some generic utilities from the non-linear extension
  src/CMakeLists.txt
  src/theory/arith/arith_utilities.cpp
  src/theory/arith/arith_utilities.h
  src/theory/arith/nonlinear_extension.cpp
  src/theory/arith/nonlinear_extension.h
Labels: normal, simple

#3424 Fix Unimplemented() macros missed in #3366.
  src/prop/cadical.cpp
  src/prop/cryptominisat.cpp
  src/theory/arith/arith_rewriter.cpp
  src/theory/uf/cardinality_extension.cpp
Labels: major
