Repository cvc5/cvc5, pull requests merged in 2020-10, with the labels that each got.

#5173 BitVector: Extend interface of setBit to set it to a specific value.
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
  src/util/bitvector.cpp
  src/util/bitvector.h
  src/util/integer_cln_imp.cpp
  src/util/integer_cln_imp.h
  src/util/integer_gmp_imp.cpp
  src/util/integer_gmp_imp.h
  test/unit/util/bitvector_black.h
Labels: major, simple

#5175 Add GH action to cancel previous pending/running CI builds.
  .github/workflows/ci.yml
Labels: major, simple

#5172 Make SygusSolver use sygus attributes directly
  src/smt/sygus_solver.cpp
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers/theory_quantifiers.cpp
Labels: normal, simple

#5164 (proof-new) Preprocessing passes use proper interfaces to assertions pipeline
  src/preprocessing/assertion_pipeline.h
  src/preprocessing/passes/ackermann.cpp
  src/preprocessing/passes/bv_gauss.cpp
  src/preprocessing/passes/global_negate.cpp
  src/preprocessing/passes/global_negate.h
  src/preprocessing/passes/ho_elim.cpp
  src/preprocessing/passes/ite_removal.cpp
  src/preprocessing/passes/ite_simp.cpp
  src/preprocessing/passes/nl_ext_purify.cpp
  src/preprocessing/passes/non_clausal_simp.cpp
  src/preprocessing/passes/quantifier_macros.cpp
  src/preprocessing/passes/quantifier_macros.h
  src/preprocessing/passes/sygus_inference.cpp
  src/preprocessing/passes/sygus_inference.h
  src/preprocessing/passes/synth_rew_rules.cpp
  src/preprocessing/passes/unconstrained_simplifier.cpp
  src/preprocessing/util/ite_utilities.cpp
  src/preprocessing/util/ite_utilities.h
  src/smt/process_assertions.cpp
Labels: moderate, normal

#5177 Allow to use the initial assignment for CAD
  src/options/arith_options.toml
  src/theory/arith/nl/cad/cdcac.cpp
  src/theory/arith/nl/cad_solver.cpp
Labels: moderate, normal

#5174 FloatingPoint: Add utility functions for largest and smallest normal.
  src/util/floatingpoint.cpp
  src/util/floatingpoint.h.in
  test/unit/util/floatingpoint_black.h
Labels: major, simple

#5178 Update theory of arithmetic to standard check
  src/theory/arith/nl/nl_solver.h
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
Labels: major, moderate

#5167 Add additional ground terms to SyGuS instantiation grammar
  src/options/quantifiers_options.toml
  src/theory/quantifiers/sygus_inst.cpp
  src/theory/quantifiers/sygus_inst.h
  src/theory/quantifiers_engine.cpp
Labels: major, simple

#5112 (proof-new) Make arrays proof producing
  src/CMakeLists.txt
  src/theory/arrays/inference_manager.cpp
  src/theory/arrays/inference_manager.h
  src/theory/arrays/theory_arrays.cpp
  src/theory/arrays/theory_arrays.h
Labels: moderate, normal

#5185 SyGuS: Add min/max (sub)normal constants to FP default grammar.
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
Labels: major, simple

#5183 Remove duplicate declarations in th_bv.plf
  proofs/signatures/th_bv.plf
Labels: minor, simple

#5176 (proof-new) New proofs in arith::Constraint::externalExplain
  src/theory/arith/congruence_manager.cpp
  src/theory/arith/congruence_manager.h
  src/theory/arith/constraint.cpp
  src/theory/arith/constraint.h
  src/theory/arith/theory_arith_private.cpp
Labels: do not merge, minor, moderate

#5184 Decouple modules from TheoryArithPrivate
  src/CMakeLists.txt
  src/theory/arith/callbacks.h
  src/theory/arith/congruence_manager.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
  src/theory/arith/theory_arith_private_forward.h
Labels: moderate, normal

#5111 Allow for theory combination of strings with nonlinear real arithmetic.
  src/smt/set_defaults.cpp
Labels: bug, minor, simple

#5169 (proof-new) Make shared solver proof producing
  src/theory/combination_engine.cpp
  src/theory/combination_engine.h
  src/theory/shared_solver.cpp
  src/theory/shared_solver.h
  src/theory/shared_solver_distributed.cpp
  src/theory/shared_solver_distributed.h
  src/theory/shared_terms_database.cpp
  src/theory/shared_terms_database.h
Labels: moderate, normal

#5171 (proof-new) Fixes for theory preprocessing proofs
  src/expr/term_context.cpp
  src/expr/term_context.h
  src/smt/term_formula_removal.cpp
  src/smt/term_formula_removal.h
  src/theory/theory_preprocessor.cpp
  src/theory/theory_preprocessor.h
Labels: moderate, normal

#5180 Minor simplifications to substitution map class
  src/theory/substitutions.cpp
  src/theory/substitutions.h
Labels: minor, simple

#5181 Standardization of Theory
  src/theory/arith/congruence_manager.cpp
  src/theory/arith/congruence_manager.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/arith/theory_arith_private.cpp
  src/theory/arrays/theory_arrays.cpp
  src/theory/bv/theory_bv.cpp
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp.h
  src/theory/model_manager_distributed.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/theory.cpp
  src/theory/theory.h
  src/theory/theory_model.cpp
  src/theory/theory_model.h
  test/unit/theory/theory_engine_white.h
Labels: moderate, normal

#5194 Fix theory white unit test
  test/unit/theory/theory_white.h
Labels: major, simple

#5191 sygus-inst: Add more special BV values.
  src/theory/quantifiers/sygus_inst.cpp
Labels: major, simple

#5179 Remove subtyping for sets theory
  examples/api/python/sets.py
  examples/api/sets.cpp
  src/CMakeLists.txt
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/api/python/cvc4.pxd
  src/api/python/cvc4.pxi
  src/expr/node_manager.cpp
  src/expr/node_manager.h
  src/parser/cvc/Cvc.g
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/sep/theory_sep_rewriter.cpp
  src/theory/sets/cardinality_extension.cpp
  src/theory/sets/kinds
  src/theory/sets/normal_form.h
  src/theory/sets/singleton_op.cpp
  src/theory/sets/singleton_op.h
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_rels.cpp
  src/theory/sets/theory_sets_rels.h
  src/theory/sets/theory_sets_rewriter.cpp
  src/theory/sets/theory_sets_type_enumerator.cpp
  src/theory/sets/theory_sets_type_rules.h
  test/regress/regress0/sets/sets-poly-int-real.smt2
  test/unit/theory/CMakeLists.txt
  test/unit/theory/theory_bags_type_rules_black.h
  test/unit/theory/theory_sets_type_rules_white.h
Labels: moderate, normal

#5190 Integer: GMP: Move implementation of member functions to .cpp file.
  src/util/integer_gmp_imp.cpp
  src/util/integer_gmp_imp.h
Labels: normal, simple

#5206 SyGuS: Add fp.sub to default FP grammar.
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
Labels: major, simple

#5204 cmake: Add warning when unit testing is disabled due to assertions being disabled.
  CMakeLists.txt
  INSTALL.md
Labels: major, simple

#5205 Remove subtyping for sets
  src/expr/type_node.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
  src/theory/sets/theory_sets_type_rules.h
  test/regress/regress0/sets/int-real-univ-unsat.smt2
  test/regress/regress0/sets/int-real-univ.smt2
  test/regress/regress0/sets/sets-of-sets-subtypes.smt2
  test/regress/regress0/sets/sets-poly-nonint.smt2
  test/unit/api/python/test_sort.py
  test/unit/api/sort_black.h
  test/unit/theory/theory_sets_type_rules_white.h
Labels: normal, simple

#5203 Replace calls to SmtEngine with calls to Solver.
  src/api/cvc4cpp.cpp
  src/smt/command.cpp
  src/smt/command.h
  test/regress/regress0/smtlib/set-info-status.smt2
Labels: normal, simple

#5188 Add arithmetic preprocess module
  src/CMakeLists.txt
  src/theory/arith/arith_preprocess.cpp
  src/theory/arith/arith_preprocess.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
Labels: moderate, normal

#5186 Add operators bag.from_set, bag.to_set to the theory of bags
  src/api/cvc4cpp.cpp
  src/api/cvc4cppkind.h
  src/parser/smt2/smt2.cpp
  src/theory/bags/bags_rewriter.cpp
  src/theory/bags/bags_rewriter.h
  src/theory/bags/kinds
  src/theory/bags/rewrites.cpp
  src/theory/bags/rewrites.h
  src/theory/bags/theory_bags.cpp
  src/theory/bags/theory_bags_type_rules.h
  test/unit/theory/theory_bags_rewriter_black.h
  test/unit/theory/theory_bags_type_rules_black.h
Labels: normal, simple

#5196 (proof-new) Allow null proofs from generators in LazyCDProof
  src/expr/lazy_proof.cpp
  src/expr/proof_node_manager.cpp
Labels: minor, simple

#5193 (proof-new) Add interface for trusted substitution and update ppAssert
  src/CMakeLists.txt
  src/preprocessing/passes/miplib_trick.cpp
  src/preprocessing/passes/non_clausal_simp.cpp
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
  src/theory/arrays/theory_arrays.cpp
  src/theory/arrays/theory_arrays.h
  src/theory/booleans/theory_bool.cpp
  src/theory/booleans/theory_bool.h
  src/theory/bv/bv_solver.h
  src/theory/bv/bv_solver_lazy.cpp
  src/theory/bv/bv_solver_lazy.h
  src/theory/bv/bv_solver_simple.h
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv.h
  src/theory/sep/theory_sep.cpp
  src/theory/sep/theory_sep.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
  src/theory/theory.cpp
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/trust_substitutions.cpp
  src/theory/trust_substitutions.h
Labels: moderate, normal

#5207 (proof-new) proofs for ArithCongMan -> ee facts
  src/theory/arith/congruence_manager.cpp
  src/theory/arith/congruence_manager.h
  src/theory/arith/constraint.h
Labels: minor, moderate

#5208 bv-to-int: change order of passes
  src/smt/process_assertions.cpp
  test/regress/CMakeLists.txt
  test/regress/regress2/bv_to_int_5095.smt2
  test/regress/regress2/bv_to_int_5095_2.smt2
Labels: bug

#5213 Process pending inferences at the beginning of datatypes post check
  src/theory/datatypes/inference_manager.cpp
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/inference_manager_buffered.cpp
  src/theory/inference_manager_buffered.h
Labels: normal, simple

#4903 (proof-new) Add the strings proof constructor
  src/CMakeLists.txt
  src/theory/strings/infer_info.h
  src/theory/strings/infer_proof_cons.cpp
  src/theory/strings/infer_proof_cons.h
  src/theory/strings/sequences_stats.cpp
  src/theory/strings/sequences_stats.h
Labels: moderate, normal

#5219 Make sure conflicts are not rewritten (in arithmetic)
  src/theory/arith/bound_inference.cpp
  src/theory/arith/inference_id.cpp
  src/theory/arith/inference_manager.cpp
  src/theory/arith/nl/icp/icp_solver.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/arith/issue5219-conflict-rewrite.smt2
Labels: moderate, normal

#5211 New C++ API: Rename Term::isConst() to Term::isValue().
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/api/python/cvc4.pxd
  src/api/python/cvc4.pxi
  src/parser/cvc/Cvc.g
  src/parser/smt2/smt2.cpp
  test/unit/api/python/test_term.py
  test/unit/api/python/test_to_python_obj.py
  test/unit/api/term_black.h
Labels: normal, simple

#5215 (proof-new) proofs in ee -> arith pipeline
  src/theory/arith/callbacks.cpp
  src/theory/arith/callbacks.h
  src/theory/arith/congruence_manager.cpp
  src/theory/arith/congruence_manager.h
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
Labels: minor, simple

#5212 fix unit failures on debug without symfpu
  test/unit/api/sort_black.h
  test/unit/theory/logic_info_white.h
  test/unit/util/CMakeLists.txt
Labels: bug

#5197 (proof-new) Fixes and improvements for smt proof postprocessor
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/smt/proof_post_processor.cpp
  src/smt/proof_post_processor.h
  src/theory/builtin/proof_checker.cpp
Labels: minor, moderate

#5195 (proof-new) Theory engine proof producing
  src/smt/smt_solver.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: moderate, normal

#5221 (proof-new) Add lazy proof set utility
  src/expr/CMakeLists.txt
  src/expr/lazy_proof_set.cpp
  src/expr/lazy_proof_set.h
Labels: normal, simple

#5223 Simplify approach for collapsed selectors over non-closed enumerable types
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
  src/theory/datatypes/type_enumerator.cpp
Labels: moderate, normal

#5229 reset-assertions: Remove all non-global symbols in the parser
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/preprocessing/passes/ho_elim.cpp
  src/preprocessing/passes/ho_elim.h
  test/regress/CMakeLists.txt
  test/regress/regress0/parser/issue5163.smt2
  test/regress/regress0/smtlib/issue4077.smt2
  test/regress/regress0/smtlib/reset-assertions1.smt2
  test/regress/regress1/sygus/interpol_cosa_1.smt2
Labels: do not merge, moderate, normal

#5224 (proof-new) proofs for arith-constraint explanations
  src/theory/arith/arith_utilities.h
  src/theory/arith/constraint.cpp
  src/theory/arith/constraint.h
  src/theory/arith/theory_arith_private.cpp
Labels: minor, simple

#5231 use right arith explanation fn to fix regressions
  src/theory/arith/theory_arith_private.cpp
Labels: major, simple

#5232 Remove deprecated add-path commands and use $GITHUB_PATH instead.
  .github/workflows/ci.yml
Labels: major, simple

#5227 bv2int: bvand translation code move
  src/CMakeLists.txt
  src/preprocessing/passes/bv_to_int.cpp
  src/preprocessing/passes/bv_to_int.h
  src/theory/arith/nl/iand_solver.cpp
  src/theory/arith/nl/iand_table.cpp
  src/theory/arith/nl/iand_table.h
Labels: refactor

#5222 Provide API version of some SMT Commands.
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/api/cvc4cppkind.h
  src/smt/command.cpp
  src/smt/command.h
  src/smt/smt_engine.cpp
  test/unit/api/solver_black.h
Labels: moderate, normal

#5218 Add conversion of poly polynomial to cvc node.
  src/theory/arith/nl/poly_conversion.cpp
  src/theory/arith/nl/poly_conversion.h
Labels: moderate, normal

#5228 SyGuS instantiation modes
  src/expr/node.h
  src/options/quantifiers_options.toml
  src/theory/quantifiers/sygus_inst.cpp
  src/theory/quantifiers/sygus_inst.h
Labels: major, simple

#5248 Ensure uninterpreted sort owner is UF if uf-ho or finite-model-find is enabled.
  src/smt/set_defaults.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/ho/issue5233-part1-usort-owner.smt2
Labels: normal, simple

#5249 (proof-new) Added addTrustedConflict() for arithmetic inference manager
  src/theory/arith/inference_manager.cpp
  src/theory/arith/inference_manager.h
Labels: normal, simple

#5240 Eliminate uses of Expr in SmtEngine interface
  src/api/cvc4cpp.cpp
  src/preprocessing/passes/bv_to_int.cpp
  src/preprocessing/passes/quantifier_macros.cpp
  src/preprocessing/passes/real_to_int.cpp
  src/preprocessing/passes/sygus_inference.cpp
  src/smt/abduction_solver.cpp
  src/smt/defined_function.h
  src/smt/interpolation_solver.cpp
  src/smt/interpolation_solver.h
  src/smt/model_blocker.cpp
  src/smt/model_blocker.h
  src/smt/model_core_builder.cpp
  src/smt/model_core_builder.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/theory_model.cpp
  src/theory/theory_model.h
  test/unit/expr/type_node_white.h
Labels: moderate, normal

#5252 (proof-new) Make circuit-propagator proof producing
  src/CMakeLists.txt
  src/preprocessing/passes/non_clausal_simp.cpp
  src/smt/preprocessor.cpp
  src/smt/preprocessor.h
  src/theory/booleans/circuit_propagator.cpp
  src/theory/booleans/circuit_propagator.h
  src/theory/booleans/proof_circuit_propagator.h
Labels: moderate, normal

#5251 Remove uf-ss-totality option
  src/options/uf_options.toml
  src/theory/uf/cardinality_extension.cpp
  src/theory/uf/cardinality_extension.h
  test/regress/CMakeLists.txt
  test/regress/regress0/fmf/issue4872-qf_ufc.smt2
  test/regress/regress0/fmf/issue5239-uf-ss-tot.smt2
  test/regress/regress1/fmf/issue4068-si-qf.smt2
Labels: minor, simple

#5255 (proof-new) Update proof generation of circuit-propagator
  src/smt/preprocessor.cpp
  src/theory/booleans/circuit_propagator.cpp
  src/theory/booleans/circuit_propagator.h
  src/theory/booleans/proof_circuit_propagator.h
Labels: moderate, normal

#5242 (proof-new) Change merge policy for proof node updater
  src/expr/proof_node_updater.cpp
  src/expr/proof_node_updater.h
Labels: minor, moderate

#5243 (proof-new) New rules for Booleans
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/booleans/proof_checker.cpp
Labels: minor, simple

#5241 (proof-new) Miscellaneous minor improvements and fixes to proofs in theory files.
  src/theory/eager_proof_generator.cpp
  src/theory/rewriter_tables_template.h
  src/theory/theory.cpp
  src/theory/theory.h
  src/theory/theory_preprocessor.cpp
  src/theory/theory_proof_step_buffer.cpp
  src/theory/theory_proof_step_buffer.h
  src/theory/theory_test_utils.h
  src/theory/trust_node.cpp
Labels: minor, simple

#5244 (proof-new) Simplifications for proof rule checker interface
  src/expr/proof_checker.cpp
  src/expr/proof_checker.h
  src/theory/builtin/proof_checker.cpp
  src/theory/strings/proof_checker.cpp
Labels: minor, simple

#5245 (proof-new) Generalize preprocess proof generator
  src/smt/preprocess_proof_generator.cpp
  src/smt/preprocess_proof_generator.h
  src/smt/proof_manager.cpp
Labels: minor, simple

#5254 (proof-new) Prove lemmas in Constraint
  src/theory/arith/constraint.cpp
  src/theory/arith/constraint.h
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
Labels: minor, simple

#5261 [proof-new] Using NOT_NOT_ELIM rather than macros to do double-neg elimination
  src/prop/proof_cnf_stream.cpp
  src/theory/theory_proof_step_buffer.cpp
Labels: normal, simple

#5263 bv2int: rewritings and unsat cores
  src/preprocessing/passes/bv_to_int.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/bv/bv_to_int1.smt2
  test/regress/regress0/bv/bv_to_int_5230_binary.smt2
  test/regress/regress0/bv/bv_to_int_5230_missing_op.smt2
  test/regress/regress0/bv/bv_to_int_5230_shift_const.smt2
  test/regress/regress0/bv/bv_to_int_zext.smt2
  test/regress/regress2/bv_to_int_ashr.smt2
  test/regress/regress2/bv_to_int_mask_array_3.smt2
  test/regress/regress2/bv_to_int_shifts.smt2
  test/regress/regress3/bv_to_int_signed_sub_or.smt2
Labels: bug, refactor

#5247 Guard uses of printing approximations for constants
  src/theory/arith/arith_utilities.cpp
  src/theory/arith/nl/nl_model.cpp
Labels: normal, simple

#5258 (proof-new) pfs in TheoryArith(Private) explanations
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
Labels: minor, simple

#5259 (proof-new) debug statements & docs for INT_TRUST
  src/theory/arith/proof_checker.cpp
Labels: minor, refactor, simple

#5270 Fix issue #5269
  src/theory/sets/theory_sets_rels.cpp
Labels: bug, major, simple

#5250 (proof-new) Infrastructure for CAD proofs
  src/CMakeLists.txt
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/arith/nl/cad/cdcac.cpp
  src/theory/arith/nl/cad/cdcac.h
  src/theory/arith/nl/cad/proof_checker.cpp
  src/theory/arith/nl/cad/proof_checker.h
  src/theory/arith/nl/cad_solver.cpp
  src/theory/arith/nl/cad_solver.h
  src/theory/arith/nl/nonlinear_extension.cpp
Labels: moderate, normal

#5273 (proof-new) Finishing work on circuit-propagator
  src/CMakeLists.txt
  src/preprocessing/passes/non_clausal_simp.cpp
  src/theory/booleans/circuit_propagator.cpp
  src/theory/booleans/circuit_propagator.h
  src/theory/booleans/proof_circuit_propagator.cpp
  src/theory/booleans/proof_circuit_propagator.h
  test/regress/regress0/preprocess/circuit-prop.smt2
Labels: do not merge

#5267 (proof-new) TheoryArithPrivate: farkas lemma proof
  src/theory/arith/theory_arith_private.cpp
Labels: minor, simple

#5275 Add inference enumeration to datatypes
  src/CMakeLists.txt
  src/theory/datatypes/inference.cpp
  src/theory/datatypes/inference.h
  src/theory/datatypes/inference_manager.cpp
  src/theory/datatypes/inference_manager.h
  src/theory/datatypes/theory_datatypes.cpp
Labels: moderate, normal

#5283 bv2int: caching introduced terms
  src/preprocessing/passes/bv_to_int.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/bv/bv_to_int_5281.smt2
Labels: bug

#5284 (proof-new) Add proofs for CAD
  src/CMakeLists.txt
  src/expr/proof_rule.h
  src/theory/arith/nl/cad/cdcac.cpp
  src/theory/arith/nl/cad/cdcac.h
  src/theory/arith/nl/cad/proof_generator.cpp
  src/theory/arith/nl/cad/proof_generator.h
  src/theory/arith/nl/cad_solver.cpp
Labels: moderate, normal

#5285 Catch more cases of nested recursion in datatypes
  src/theory/datatypes/theory_datatypes.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/datatypes/issue5280-no-nrec.smt2
Labels: normal, simple

#5277 Refactor SMT-level model object
  src/api/cvc4cpp.cpp
  src/printer/ast/ast_printer.cpp
  src/printer/ast/ast_printer.h
  src/printer/cvc/cvc_printer.cpp
  src/printer/cvc/cvc_printer.h
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/printer/tptp/tptp_printer.cpp
  src/printer/tptp/tptp_printer.h
  src/smt/command.h
  src/smt/model.cpp
  src/smt/model.h
  src/smt/model_blocker.cpp
  src/smt/model_core_builder.cpp
  src/smt/model_core_builder.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/theory/theory_model.cpp
  src/theory/theory_model.h
  src/theory/theory_model_builder.cpp
  src/theory/theory_model_builder.h
Labels: moderate, normal

#5292 (proof-new) Improvements for theory engine
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: minor, simple

#5246 (proof-new) More features for SMT proof post-processor
  src/smt/proof_post_processor.cpp
  src/smt/proof_post_processor.h
  src/theory/builtin/proof_checker.cpp
  src/theory/builtin/proof_checker.h
Labels: minor, moderate

#5276 (proof-new) Implementation of trust substitution
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/builtin/proof_checker.cpp
  src/theory/trust_substitutions.cpp
  src/theory/trust_substitutions.h
Labels: moderate, normal

#5289 (proof-new) Witness axiom reconstruction for purification skolems
  src/expr/proof_rule.h
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/smt/witness_form.cpp
  src/smt/witness_form.h
  src/theory/quantifiers/proof_checker.cpp
Labels: minor, moderate

#5291 (proof-new) Refactoring cyclic checks
  src/expr/proof_node_algorithm.cpp
  src/expr/proof_node_algorithm.h
  src/expr/proof_node_manager.cpp
  src/expr/proof_node_to_sexpr.cpp
Labels: minor, moderate

#5286 Safer version of pending lemma processing in inference manager buffered
  src/theory/inference_manager_buffered.cpp
Labels: normal, simple

#5302 [proof-new] Improving cycle checking in lazycdproofchain
  src/expr/lazy_proof_chain.cpp
Labels: moderate, normal

#5298 (proof-new) Update preprocessing pass context for proofs
  src/preprocessing/assertion_pipeline.cpp
  src/preprocessing/passes/apply_substs.cpp
  src/preprocessing/passes/miplib_trick.cpp
  src/preprocessing/passes/non_clausal_simp.cpp
  src/preprocessing/preprocessing_pass_context.cpp
  src/preprocessing/preprocessing_pass_context.h
  src/smt/preprocessor.cpp
  src/smt/preprocessor.h
  src/smt/process_assertions.cpp
  src/smt/smt_engine.cpp
Labels: moderate, normal

#5300 (proof-new) Updates to assertions pipeline and preprocess generator
  src/preprocessing/assertion_pipeline.cpp
  src/preprocessing/assertion_pipeline.h
  src/smt/preprocess_proof_generator.cpp
  src/smt/preprocess_proof_generator.h
Labels: moderate, normal

#5262 [proof-new] Fixing resolution proof checker
  src/expr/proof_rule.h
  src/prop/proof_cnf_stream.cpp
  src/theory/booleans/proof_checker.cpp
Labels: moderate, normal

#5304 Integer: CLN: Move implementation of member functions to .cpp file.
  src/util/integer_cln_imp.cpp
  src/util/integer_cln_imp.h
  src/util/integer_gmp_imp.h
Labels: normal, simple

#5287 Expand `seq.nth` lazily
  src/theory/strings/extf_solver.cpp
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/term_registry.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/theory_strings_utils.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/seq/seq-nth-undef-unsat.smt2
  test/regress/regress0/seq/seq-nth-undef.smt2
  test/regress/regress0/seq/seq-nth.smt2
  test/regress/regress0/seq/seq-types.smt2
Labels: feature

#5306 Integer (CLN): Minor improvements.
  src/util/integer_cln_imp.cpp
Labels: normal, simple

#5303 Split CheckModels utility to its own file
  src/CMakeLists.txt
  src/smt/check_models.cpp
  src/smt/check_models.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/smt/smt_solver.cpp
  src/smt/smt_solver.h
Labels: moderate, normal

#5311 Handle rewrite to bool in BoundInference
  src/theory/arith/bound_inference.cpp
  src/theory/arith/nl/icp/icp_solver.cpp
Labels: normal, simple

#5314 Make seq.nth a trigger kind
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/term_database.cpp
Labels: major, simple

#5256 Fix miscellaneous warnings
  src/smt/listeners.cpp
  src/theory/builtin/proof_checker.cpp
  src/theory/bv/bv_subtheory_algebraic.cpp
  src/theory/uf/cardinality_extension.cpp
  src/theory/uf/cardinality_extension.h
Labels: normal, simple

#5268 Remove some Commands from the API.
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/api/python/cvc4.pxd
  src/api/python/cvc4.pxi
  src/printer/printer.cpp
  src/printer/printer.h
  src/smt/command.cpp
  src/smt/command.h
Labels: normal, simple

#5299 (proof-new) Update add lazy step interface in LazyCDProof
  src/expr/lazy_proof.cpp
  src/expr/lazy_proof.h
  src/expr/term_conversion_proof_generator.cpp
  src/expr/term_conversion_proof_generator.h
  src/preprocessing/assertion_pipeline.cpp
  src/prop/proof_cnf_stream.cpp
  src/smt/proof_post_processor.cpp
  src/smt/term_formula_removal.cpp
  src/smt/witness_form.cpp
  src/theory/quantifiers/instantiate.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_preprocessor.cpp
  src/theory/trust_substitutions.cpp
  src/theory/trust_substitutions.h
  src/theory/uf/proof_equality_engine.cpp
Labels: moderate, normal

#5297 (proof-new) Fix for CDProof::isSame
  src/expr/proof.cpp
Labels: minor, simple

#5301 (proof-new) Add proofs for circuit propagator
  src/CMakeLists.txt
  src/theory/booleans/proof_circuit_propagator.cpp
  src/theory/booleans/proof_circuit_propagator.h
Labels: moderate, normal

#5305 Fix compiler warnings.
  src/theory/rep_set.cpp
  src/theory/rep_set.h
  src/theory/uf/cardinality_extension.cpp
Labels: normal, simple

#5307 (proof-new) Fixes for proofs in rewriter
  src/expr/proof_rule.h
  src/smt/proof_post_processor.cpp
  src/theory/builtin/proof_checker.cpp
  src/theory/builtin/proof_checker.h
  src/theory/rewriter.cpp
  src/theory/rewriter.h
Labels: moderate, normal

#5316 Refactor SygusInterpol
  src/smt/interpolation_solver.cpp
  src/smt/smt_engine.cpp
  src/theory/quantifiers/sygus/sygus_interpol.cpp
  src/theory/quantifiers/sygus/sygus_interpol.h
Labels: moderate, normal

#5209 Add operator MakeBagOp for constructing bags
  src/CMakeLists.txt
  src/api/cvc4cppkind.h
  src/expr/node_manager.cpp
  src/expr/node_manager.h
  src/expr/type_node.cpp
  src/theory/bags/bags_rewriter.cpp
  src/theory/bags/kinds
  src/theory/bags/make_bag_op.cpp
  src/theory/bags/make_bag_op.h
  src/theory/bags/theory_bags_type_enumerator.cpp
  src/theory/bags/theory_bags_type_rules.h
  test/unit/theory/CMakeLists.txt
  test/unit/theory/theory_bags_rewriter_white.h
  test/unit/theory/theory_bags_type_rules_white.h
Labels: normal, simple

#5317 (proof-new) Updates to lazy proof chain
  src/expr/lazy_proof_chain.cpp
  src/expr/lazy_proof_chain.h
Labels: moderate, normal

#5320 (proof-new) arith: dedup literals in flattenImpl
  src/theory/arith/theory_arith_private.cpp
Labels: minor, simple

#5321 (proof-new) Add arith proof macros file to CMake
  src/CMakeLists.txt
Labels: minor, simple

#5322 Implement bags evaluator
  src/theory/bags/bags_rewriter.cpp
  src/theory/bags/normal_form.cpp
  src/theory/bags/normal_form.h
  src/theory/bags/theory_bags_type_rules.h
  test/unit/theory/CMakeLists.txt
  test/unit/theory/theory_bags_normal_form_white.h
  test/unit/theory/theory_bags_type_rules_white.h
Labels: moderate, normal

#5318 (proof-new) Make circuit propagator proof producing
  src/preprocessing/passes/non_clausal_simp.cpp
  src/theory/booleans/circuit_propagator.cpp
  src/theory/booleans/circuit_propagator.h
Labels: moderate, normal

#5296 (proof-new) Make theory preprocessor user-context dependent
  src/preprocessing/passes/theory_preprocess.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/theory_preprocessor.cpp
  src/theory/theory_preprocessor.h
Labels: moderate, normal

#5327 Fix issue 5309
  src/theory/sets/theory_sets_private.cpp
  src/theory/theory_model_builder.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sets/issue5309.smt2
Labels: normal, simple

#5319 Remove unused equality engine types
  src/theory/uf/equality_engine_types.h
Labels: minor, simple

#5326 Use theoryof-mode=type for QF_NRA
  src/smt/set_defaults.cpp
Labels: moderate, normal

#5331 Fix related to preregistering boolean term variables in strings
  src/theory/strings/term_registry.cpp
  src/theory/uf/equality_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/seq/issue4370-bool-terms.smt2
Labels: minor, simple

#5325 Change datatypes lemma policy for equalities not coming from instantiate
  src/theory/datatypes/inference.cpp
  src/theory/datatypes/inference.h
Labels: moderate, normal

#5324 Apply alpha equivalence to annotated quantified formulas
  src/theory/quantifiers/alpha_equivalence.cpp
Labels: normal, simple

#5332 [proof-new] Fix n-ary kind handling in EqEngine explanations
  src/theory/uf/equality_engine.cpp
Labels: normal, simple

#5335 Fix issue 5271
  src/theory/sets/theory_sets_private.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sets/issue5271.smt2
Labels: bug, simple

#5346 Send external equalities from collapse selector as lemmas
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/theory.cpp
Labels: major, simple

#5340 (proof-new) Add datatypes proof checker
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/datatypes/proof_checker.cpp
  src/theory/datatypes/proof_checker.h
Labels: moderate, normal

#5336 Add DUPICATE_REMOVAL operator to bags
  src/api/cvc4cpp.cpp
  src/api/cvc4cppkind.h
  src/parser/smt2/smt2.cpp
  src/theory/bags/bags_rewriter.cpp
  src/theory/bags/bags_rewriter.h
  src/theory/bags/kinds
  src/theory/bags/make_bag_op.cpp
  src/theory/bags/normal_form.cpp
  src/theory/bags/normal_form.h
  src/theory/bags/rewrites.cpp
  src/theory/bags/rewrites.h
  src/theory/bags/theory_bags.cpp
  src/theory/bags/theory_bags_type_rules.h
  test/unit/theory/theory_bags_normal_form_white.h
  test/unit/theory/theory_bags_rewriter_white.h
  test/unit/theory/theory_bags_type_rules_white.h
Labels: normal, simple

#5350 Disable --nl-cad option by default
  src/options/arith_options.toml
  src/smt/set_defaults.cpp
Labels: major, simple

#5290 Add missing methods involving datatype sorts to the API
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/expr/type_node.cpp
  src/expr/type_node.h
  test/unit/api/sort_black.h
Labels: normal, simple

#5334 Refactor DeclareSygusVarCommand and SynthFunCommand to use the API.
  src/api/cvc4cpp.cpp
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/smt/command.cpp
  src/smt/smt_engine.cpp
  src/theory/quantifiers/sygus/sygus_interpol.cpp
  test/unit/api/solver_black.h
Labels: moderate, normal

#5353 run_regression: Add --skip-timeout option, lower timeout to 600 seconds.
  test/regress/run_regression.py
Labels: major, simple

#5352 Add rewrites for div/mod in the arithmetic rewriter
  src/CMakeLists.txt
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_rewriter.h
  src/theory/arith/rewrites.cpp
  src/theory/arith/rewrites.h
Labels: moderate, normal

#5315 Split NlSolver in multiple subsolvers
  src/CMakeLists.txt
  src/theory/arith/nl/ext/constraint.cpp
  src/theory/arith/nl/ext/constraint.h
  src/theory/arith/nl/ext/ext_state.cpp
  src/theory/arith/nl/ext/ext_state.h
  src/theory/arith/nl/ext/factoring_check.cpp
  src/theory/arith/nl/ext/factoring_check.h
  src/theory/arith/nl/ext/monomial.cpp
  src/theory/arith/nl/ext/monomial.h
  src/theory/arith/nl/ext/monomial_bounds_check.cpp
  src/theory/arith/nl/ext/monomial_bounds_check.h
  src/theory/arith/nl/ext/monomial_check.cpp
  src/theory/arith/nl/ext/monomial_check.h
  src/theory/arith/nl/ext/split_zero_check.cpp
  src/theory/arith/nl/ext/split_zero_check.h
  src/theory/arith/nl/ext/tangent_plane_check.cpp
  src/theory/arith/nl/ext/tangent_plane_check.h
  src/theory/arith/nl/nl_solver.cpp
  src/theory/arith/nl/nl_solver.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
Labels: moderate, normal

#5355 Convert symbol table from Expr-level to Term-level
  src/api/cvc4cpp.cpp
  src/expr/symbol_table.cpp
  src/expr/symbol_table.h
  src/parser/parser.cpp
  src/parser/parser.h
  test/regress/CMakeLists.txt
  test/unit/expr/symbol_table_black.h
Labels: moderate, normal

#5351 Fixes for unconstrained variables in nonlinear model
  src/theory/arith/nl/nl_model.cpp
  src/theory/arith/nl/nl_model.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/iand-no-init.smt2
Labels: moderate, normal

#5357 Remove more uses of Expr
  src/api/cvc4cpp.cpp
  src/printer/printer.cpp
  src/printer/smt2/smt2_printer.cpp
  src/printer/tptp/tptp_printer.cpp
  src/proof/proof_manager.cpp
  src/proof/proof_manager.h
  src/proof/unsat_core.h
  src/smt/command.cpp
  src/smt/command.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/smt_util/boolean_simplification.h
  src/theory/quantifiers/expr_miner.h
  src/theory/quantifiers/sygus/cegis_core_connective.cpp
  src/theory/smt_engine_subsolver.h
Labels: moderate, normal

#5264 run_regression.py to fail on invalid requirements
  test/regress/run_regression.py
Labels: feature

#5360 Add NodeManager::mkOr()
  src/expr/node_manager.h
Labels: minor, simple

#5220 (proof-new) Update the strings inference manager for proofs
  src/theory/strings/core_solver.cpp
  src/theory/strings/infer_info.cpp
  src/theory/strings/infer_info.h
  src/theory/strings/inference_manager.cpp
  src/theory/strings/inference_manager.h
  src/theory/strings/sequences_stats.cpp
  src/theory/strings/sequences_stats.h
  src/theory/strings/solver_state.cpp
  src/theory/strings/solver_state.h
  src/theory/strings/theory_strings.cpp
Labels: moderate, normal

#5274 Add mkInteger to the API
  examples/api/combination.cpp
  examples/api/datatypes.cpp
  examples/api/linear_arith.cpp
  examples/api/python/combination.py
  examples/api/python/datatypes.py
  examples/api/python/linear_arith.py
  examples/api/python/sequences.py
  examples/api/python/sets.py
  examples/api/python/strings.py
  examples/api/python/sygus-fun.py
  examples/api/python/sygus-grammar.py
  examples/api/python/sygus-inv.py
  examples/api/sequences.cpp
  examples/api/sets.cpp
  examples/api/strings.cpp
  examples/api/sygus-fun.cpp
  examples/api/sygus-grammar.cpp
  examples/api/sygus-inv.cpp
  examples/simple_vc_cxx.cpp
  examples/simple_vc_quant_cxx.cpp
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/api/python/cvc4.pxd
  src/api/python/cvc4.pxi
  src/expr/array_store_all.cpp
  src/parser/cvc/Cvc.g
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/tptp/Tptp.g
  src/printer/cvc/cvc_printer.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/kinds
  src/theory/arith/theory_arith_type_rules.h
  test/api/reset_assertions.cpp
  test/api/sep_log_api.cpp
  test/regress/regress0/get-value-reals-ints.smt2
  test/regress/regress0/get-value-reals.smt2
  test/unit/api/grammar_black.h
  test/unit/api/python/test_grammar.py
  test/unit/api/python/test_term.py
  test/unit/api/python/test_to_python_obj.py
  test/unit/api/solver_black.h
  test/unit/api/term_black.h
  test/unit/theory/theory_sets_type_rules_white.h
Labels: complex, do not merge, normal

#5364 Set strings pending conflict flag
  src/theory/strings/solver_state.cpp
Labels: major, simple

#5363 Update api::Sort to use TypeNode instead of Type
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/expr/CMakeLists.txt
  src/expr/ascription_type.cpp
  src/expr/ascription_type.h
  src/expr/dtype_cons.cpp
  src/expr/type.h
  src/expr/type_node.cpp
  src/expr/type_node.h
  src/parser/cvc/Cvc.g
  src/parser/parser.cpp
  src/printer/cvc/cvc_printer.cpp
  src/printer/smt2/smt2_printer.cpp
  src/smt/abstract_values.cpp
  src/smt/command.cpp
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/theory_datatypes_type_rules.h
  src/theory/datatypes/theory_datatypes_utils.cpp
  src/theory/datatypes/type_enumerator.cpp
  test/unit/api/sort_black.h
Labels: moderate, normal

#5359 Use BoundInference in nonlinear extension
  src/theory/arith/bound_inference.cpp
  src/theory/arith/bound_inference.h
  src/theory/arith/inference_manager.cpp
  src/theory/arith/inference_manager.h
  src/theory/arith/nl/cad_solver.cpp
  src/theory/arith/nl/icp/contraction_origins.cpp
  src/theory/arith/nl/icp/contraction_origins.h
  src/theory/arith/nl/icp/icp_solver.cpp
  src/theory/arith/nl/icp/icp_solver.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/nl/poly_conversion.cpp
Labels: moderate, normal
