Repository cvc5/cvc5, pull requests merged in 2020-02, with the labels that each got.

#3691 Handle `expectedType` in TheoryProofEngine
  src/proof/theory_proof.cpp
  src/proof/theory_proof.h
Labels: minor, simple

#3670 Example inference utility
  src/CMakeLists.txt
  src/theory/quantifiers/quant_util.cpp
  src/theory/quantifiers/sygus/example_infer.cpp
  src/theory/quantifiers/sygus/example_infer.h
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  test/regress/CMakeLists.txt
  test/regress/regress2/sygus/examples-deq.sy
Labels: moderate, normal

#3690 Fix corner case of empty domains in bounded fmf
  src/theory/rep_set.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/fmf/issue3689.smt2
Labels: normal, simple

#3693 Fix invariant template inference for trivially infeasible conjecture
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/sygus/pbe-pred-contra.sy
Labels: normal, simple

#3668 Split on model values when repaired model from non-linear is inconsisent
  src/theory/arith/nonlinear_extension.cpp
  src/theory/arith/theory_arith_private.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/nl/issue3617.smt2
Labels: normal, simple

#3702 Fixes to regressions
  test/regress/regress0/sygus/pbe-pred-contra.sy
  test/regress/regress1/nl/issue3617.smt2
Labels: major, simple

#3703 Utility function for getting component types
  src/expr/node_algorithm.cpp
  src/expr/node_algorithm.h
Labels: normal, simple

#3706 Fix corner case - might need to REWRITE_AGAIN
  src/theory/arrays/theory_arrays_rewriter.h
Labels: simple

#3704 Increase regression test time limit to 1200s.
  test/regress/run_regression.py
Labels: minor, simple

#3701 Regression tests for arithmetic proofs.
  test/regress/CMakeLists.txt
  test/regress/regress0/arith/arith-eq.smt2
  test/regress/regress0/arith/arith-mixed-types-no-tighten.smt2
  test/regress/regress0/arith/arith-mixed-types-tighten.smt2
  test/regress/regress0/arith/arith-mixed.smt2
  test/regress/regress0/arith/arith-strict.smt2
  test/regress/regress0/arith/arith-tighten-1.smt2
Labels: minor, simple

#3711 Revert semantic change from refactoring
  src/theory/strings/theory_strings.cpp
Labels: minor, simple

#3680 Split base solver from the theory of strings
  src/CMakeLists.txt
  src/theory/strings/base_solver.cpp
  src/theory/strings/base_solver.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: moderate, normal

#3660 Fix header installation on MacOS.
  src/fix-install-headers.sh
Labels: normal, simple

#3709 --fp-exp: Better warning message.
  src/theory/fp/theory_fp.cpp
Labels: minor, simple

#3700 Articulate proof-related debug statements in arith
  src/theory/arith/constraint.cpp
  src/theory/arith/constraint.h
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
Labels: minor, simple

#3714 Fix a markdown link in INSTALL.md
  INSTALL.md
Labels: minor

#3715 Fix QF_NIA smt comp script
  contrib/competitions/smt-comp/run-script-smtcomp-current-unsat-cores
Labels: minor, simple

#3722 Generalize containsQuantifiers to hasClosure
  src/expr/node_algorithm.cpp
  src/expr/node_algorithm.h
  src/smt/smt_engine.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
Labels: minor, simple

#3721 Fix case where approximation for sqrt is exact
  src/theory/arith/nl_model.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/issue3719.smt2
Labels: major, simple

#3698 Example evaluation cache utility
  src/theory/quantifiers/sygus/example_eval_cache.cpp
  src/theory/quantifiers/sygus/example_eval_cache.h
Labels: moderate, normal

#3699 Statistics for fast enumerator
  src/theory/quantifiers/sygus/sygus_enumerator.cpp
  src/theory/quantifiers/sygus/sygus_enumerator.h
  src/theory/quantifiers/sygus/sygus_stats.cpp
  src/theory/quantifiers/sygus/sygus_stats.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
Labels: minor, simple

#3716 Add `ArithProof::{printInteger,getLfscFunction}`
  src/proof/arith_proof.cpp
  src/proof/arith_proof.h
Labels: minor, simple

#3717 Propagate expected types through UF arguments
  src/proof/uf_proof.cpp
Labels: minor, simple

#3723 Refactor check-model handling in SmtEngine
  src/smt/smt_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/issue3718.smt2
  test/regress/regress1/rewriterules/datatypes_sat.smt2
  test/regress/regress1/rewriterules/length_gen_020_sat.smt2
Labels: minor, moderate

#3712 Univeset Cardinality constraints for infinite types
  src/theory/sets/cardinality_extension.cpp
  src/theory/sets/cardinality_extension.h
  src/theory/sets/solver_state.h
  src/theory/sets/theory_sets_private.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sets/infinite-type/sets-card-array-int-1.smt2
  test/regress/regress1/sets/infinite-type/sets-card-array-int-2.smt2
  test/regress/regress1/sets/infinite-type/sets-card-int-1.smt2
  test/regress/regress1/sets/infinite-type/sets-card-int-2.smt2
  test/regress/regress1/sets/infinite-type/sets-card-neg-mem-union-2.smt2
  test/regress/regress1/sets/issue2904.smt2
Labels: minor, simple

#3726 Interface for example evaluation cache utilities
  src/CMakeLists.txt
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/cegis.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
Labels: moderate, normal

#3713 Split core solver from the theory of strings
  src/CMakeLists.txt
  src/theory/strings/core_solver.cpp
  src/theory/strings/core_solver.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: moderate, normal

#3727 Split strings finite model finding strategy
  src/CMakeLists.txt
  src/theory/strings/strings_fmf.cpp
  src/theory/strings/strings_fmf.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: minor, moderate

#3728 Make "unknown" non-critical for unsat cores check
  src/smt/smt_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/arith/issue3480.smt2
  test/regress/regress0/quantifiers/issue3655.smt2
Labels: minor, simple

#3734 Fix rewrite rules sat regressions
  test/regress/regress1/rewriterules/datatypes_sat.smt2
  test/regress/regress1/rewriterules/length_gen_020_sat.smt2
Labels: major, simple

#3731 Add more IntReal predicates
  proofs/signatures/th_lira.plf
Labels: minor, simple

#3738 cmake: Use ld.gold if available for faster link times.
  CMakeLists.txt
Labels: normal, simple

#3732 Add function for tightening literals
  src/proof/arith_proof.cpp
  src/proof/arith_proof.h
Labels: minor, moderate

#3740 Implement LFSCArithProof::equalityType.
  src/proof/arith_proof.cpp
  src/proof/arith_proof.h
  src/proof/theory_proof.cpp
Labels: minor, simple

#3733 Use example evaluation cache instead of sygus PBE
  src/theory/datatypes/sygus_extension.cpp
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/cegis.h
  src/theory/quantifiers/sygus/example_eval_cache.cpp
  src/theory/quantifiers/sygus/sygus_enumerator.cpp
  src/theory/quantifiers/sygus/sygus_enumerator.h
  src/theory/quantifiers/sygus/sygus_invariance.cpp
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/sygus/sygus_pbe.h
  src/theory/quantifiers/sygus/sygus_unif_io.cpp
  src/theory/quantifiers/sygus/sygus_unif_io.h
Labels: moderate, normal

#3736 Refactor `CoreSolver::processSimpleNEq()`
  src/theory/strings/core_solver.cpp
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
Labels: moderate, normal

#3743 Remove `--strings-binary-csp` option
  src/options/strings_options.toml
  src/theory/strings/core_solver.cpp
  src/theory/strings/infer_info.cpp
  src/theory/strings/infer_info.h
  src/theory/strings/skolem_cache.h
Labels: normal, simple

#3746 Fix term simplification based on entailment in quantifiers rewriter
  src/theory/quantifiers/quantifiers_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue3724-quant.smt2
Labels: normal, simple

#3739 Fix non-linear equality solving that involves mixed real/integer arithmetic
  src/theory/arith/nl_model.cpp
Labels: normal, simple

#3750 run_regression: Distinguish between timeout and failure.
  test/regress/run_regression.py
Labels: normal, refactor

#3681 Ensure ext rewrites for associative ops dont throw assertions for kind arities
  src/theory/quantifiers/extended_rewrite.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/bv/issue3654.smt2
  test/regress/regress1/sygus/issue3649.sy
Labels: minor, simple

#3752 Rename Java package to edu.stanford.CVC4
  NEWS
  examples/SimpleVC.java
  examples/api/java/BitVectors.java
  examples/api/java/BitVectorsAndArrays.java
  examples/api/java/CVC4Streams.java
  examples/api/java/Combination.java
  examples/api/java/Datatypes.java
  examples/api/java/FloatingPointArith.java
  examples/api/java/HelloWorld.java
  examples/api/java/LinearArith.java
  examples/api/java/PipedInput.java
  examples/api/java/Statistics.java
  examples/api/java/Strings.java
  examples/api/java/UnsatCores.java
  src/bindings/java/CMakeLists.txt
  src/cvc4.i
  src/expr/expr.i
  src/expr/record.i
  src/proof/unsat_core.i
  src/smt/command.i
  src/smt/smt_engine.i
Labels: normal, simple

#3753 [Python] Properly destroy CVC4 object
  src/cvc4.i
Labels: moderate, normal

#3755 Const input for sygus print callback
  src/printer/sygus_print_callback.cpp
  src/printer/sygus_print_callback.h
Labels: minor, simple

#3748 Forcing rewrite pass rather than asserting if formula has been rewritten
  src/smt/smt_engine.cpp
Labels: minor, simple

#3756 Update sygus v1 parser to use ParseOp utility
  src/CMakeLists.txt
  src/bindings/java/CMakeLists.txt
  src/expr/datatype.cpp
  src/expr/datatype.h
  src/expr/datatype.i
  src/parser/CMakeLists.txt
  src/parser/cvc4parser.i
  src/parser/parse_op.h
  src/parser/parse_op.i
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
Labels: moderate, normal

#3754 Remove quantifiers rewrite rules infrastructure
  src/CMakeLists.txt
  src/api/cvc4cppkind.h
  src/bindings/java/CMakeLists.txt
  src/options/quantifiers_options.toml
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/smt/command.cpp
  src/smt/command.h
  src/smt/smt_engine.cpp
  src/theory/quantifiers/kinds
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers/quantifiers_attributes.h
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
  src/theory/quantifiers/rewrite_engine.cpp
  src/theory/quantifiers/rewrite_engine.h
  src/theory/quantifiers/theory_quantifiers_type_rules.h
  src/theory/quantifiers_engine.cpp
  src/theory/term_registration_visitor.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/rewriterules/datatypes.smt2
  test/regress/regress0/rewriterules/datatypes_clark.smt2
  test/regress/regress0/rewriterules/length.smt2
  test/regress/regress0/rewriterules/length_gen_n.smt2
  test/regress/regress0/rewriterules/length_gen_n_lemma.smt2
  test/regress/regress0/rewriterules/length_trick.smt2
  test/regress/regress0/rewriterules/length_trick2.smt2
  test/regress/regress0/rewriterules/native_arrays.smt2
  test/regress/regress0/rewriterules/native_datatypes.smt2
  test/regress/regress0/rewriterules/relation.smt2
  test/regress/regress0/rewriterules/simulate_rewriting.smt2
  test/regress/regress1/push-pop/bug326.smt2
  test/regress/regress1/rewriterules/datatypes2.smt2
  test/regress/regress1/rewriterules/datatypes3.smt2
  test/regress/regress1/rewriterules/datatypes_clark_quantification.smt2
  test/regress/regress1/rewriterules/datatypes_sat.smt2
  test/regress/regress1/rewriterules/length_gen.smt2
  test/regress/regress1/rewriterules/length_gen_010.smt2
  test/regress/regress1/rewriterules/length_gen_010_lemma.smt2
  test/regress/regress1/rewriterules/length_gen_020.smt2
  test/regress/regress1/rewriterules/length_gen_020_sat.smt2
  test/regress/regress1/rewriterules/length_gen_040.smt2
  test/regress/regress1/rewriterules/length_gen_040_lemma.smt2
  test/regress/regress1/rewriterules/length_gen_040_lemma_trigger.smt2
  test/regress/regress1/rewriterules/length_gen_080.smt2
  test/regress/regress1/rewriterules/length_gen_160_lemma.smt2
  test/regress/regress1/rewriterules/length_gen_inv_160.smt2
  test/regress/regress1/rewriterules/length_trick3.smt2
  test/regress/regress1/rewriterules/length_trick3_int.smt2
  test/regress/regress1/rewriterules/reachability_back_to_the_future.smt2
  test/regress/regress1/rewriterules/read5.smt2
  test/regress/regress1/rewriterules/set_A_new_fast_tableau-base.smt2
  test/regress/regress1/rewriterules/set_A_new_fast_tableau-base_sat.smt2
  test/regress/regress1/rewriterules/test_guards.smt2
  test/regress/regress1/rewriterules/why3_vstte10_max_sum_harness2.smt2
Labels: minor, simple

#3758 Move proxy variables to InferenceManager in strings
  src/theory/strings/inference_manager.cpp
  src/theory/strings/inference_manager.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: minor, moderate

#3761 Disable regression that times out on competition build
  src/theory/theory_model_builder.cpp
  test/regress/CMakeLists.txt
Labels: normal, simple

#3745 Activate reverse variant of F-Split inference
  src/theory/strings/core_solver.cpp
  src/theory/strings/normal_form.cpp
  src/theory/strings/normal_form.h
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
Labels: moderate, normal

#3759 Add temporary global API conversion utilities.
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
Labels: major, moderate

#3762 Simple improvement to fast enumerator
  src/theory/quantifiers/sygus/sygus_enumerator.cpp
Labels: minor, simple

#3763 Support dumping Sygus commands.
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/Smt2.g
  src/printer/smt2/smt2_printer.cpp
  src/smt/smt_engine.cpp
Labels: moderate, normal

#3764 Using ParseOp in TPTP
  src/parser/parse_op.h
  src/parser/parser.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/tptp/Tptp.g
  src/parser/tptp/tptp.cpp
  src/parser/tptp/tptp.h
Labels: moderate, normal

#3766 Fix soundness bug in reduction of integer div/mod
  src/theory/arith/theory_arith_private.cpp
  src/theory/theory_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue3765-quant-dd.smt2
  test/regress/regress1/quantifiers/issue3765.smt2
Labels: major, simple

#3760 Option to limit the number of rounds of enumerative instantiation
  src/options/quantifiers_options.toml
  src/theory/quantifiers/inst_strategy_enumerative.cpp
  src/theory/quantifiers/inst_strategy_enumerative.h
  test/regress/regress1/quantifiers/issue3481.smt2
Labels: moderate, normal

#3757 Add missing kinds for the new API
  src/api/cvc4cpp.cpp
  src/api/cvc4cppkind.h
Labels: moderate, normal

#3773 Change datatype selector/constructor/tester to terms
  examples/api/datatypes-new.cpp
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  test/unit/api/solver_black.h
  test/unit/api/term_black.h
Labels: major, moderate

#3747 Fix approximate bounds for transcendental functions whose model values rewrite
  src/theory/arith/nonlinear_extension.cpp
Labels: minor, simple

#3778 Change Record to shared_ptr in Expr-level Datatype
  src/expr/datatype.cpp
  src/expr/datatype.h
  test/unit/api/solver_black.h
Labels: major, simple

#3774 Delay enumerative instantiation if theory engine does not need check
  src/theory/quantifiers/inst_strategy_enumerative.cpp
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue3481-unsat1.smt2
Labels: normal, simple

#2879 Add Python bindings using Cython -- see below for more details
  .travis.yml
  CMakeLists.txt
  cmake/FindCython.cmake
  cmake/FindPythonExtensions.cmake
  cmake/UseCython.cmake
  cmake/targetLinkLibrariesWithDynamicLookup.cmake
  configure.sh
  examples/api/python/bitvectors.py
  examples/api/python/bitvectors_and_arrays.py
  examples/api/python/combination.py
  examples/api/python/datatypes.py
  examples/api/python/extract.py
  examples/api/python/helloworld.py
  examples/api/python/linear_arith.py
  examples/api/python/sets.py
  examples/api/python/strings.py
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/api/python/CMakeLists.txt
  src/api/python/cvc4.pxd
  src/api/python/cvc4.pxi
  src/api/python/genkinds.py
  src/api/python/pycvc4.pyx
  src/bindings/CMakeLists.txt
  test/CMakeLists.txt
Labels: complex, feature

#3775 Fix symmetry breaking for multiple sygus types
  src/theory/datatypes/sygus_extension.cpp
  src/theory/quantifiers/sygus/example_eval_cache.cpp
  src/theory/quantifiers/sygus/example_eval_cache.h
  src/theory/quantifiers/sygus/sygus_enumerator.cpp
Labels: normal, simple

#3772 resource manager: Add statistic for every resource.
  src/bindings/java/CMakeLists.txt
  src/cvc4.i
  src/decision/decision_engine.h
  src/expr/expr_manager.i
  src/expr/node_manager.cpp
  src/options/smt_options.toml
  src/parser/parser.cpp
  src/preprocessing/passes/apply_substs.cpp
  src/preprocessing/passes/bool_to_bv.cpp
  src/preprocessing/passes/bv_to_bool.cpp
  src/preprocessing/passes/ite_removal.cpp
  src/preprocessing/passes/ite_simp.cpp
  src/preprocessing/passes/non_clausal_simp.cpp
  src/preprocessing/passes/static_learning.cpp
  src/preprocessing/passes/unconstrained_simplifier.cpp
  src/preprocessing/preprocessing_pass_context.h
  src/prop/bv_sat_solver_notify.h
  src/prop/bvminisat/bvminisat.h
  src/prop/bvminisat/core/Solver.cc
  src/prop/bvminisat/core/Solver.h
  src/prop/cnf_stream.cpp
  src/prop/minisat/core/Solver.cc
  src/prop/minisat/core/Solver.h
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
  src/smt/smt_engine.cpp
  src/theory/arith/theory_arith.cpp
  src/theory/arrays/theory_arrays.cpp
  src/theory/bv/bitblast/bitblaster.h
  src/theory/bv/bitblast/eager_bitblaster.cpp
  src/theory/bv/bitblast/lazy_bitblaster.cpp
  src/theory/bv/bitblast/lazy_bitblaster.h
  src/theory/bv/bv_eager_solver.cpp
  src/theory/bv/bv_subtheory_bitblast.cpp
  src/theory/bv/bv_subtheory_core.cpp
  src/theory/bv/bv_subtheory_inequality.cpp
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv.h
  src/theory/output_channel.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/rewriter.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/theory_test_utils.h
  src/theory/uf/theory_uf.cpp
  src/util/resource_manager.cpp
  src/util/resource_manager.h
  src/util/resource_manager.i
  test/unit/theory/theory_white.h
Labels: moderate, normal

#3779 Remove parser from bindings
  src/bindings/java/CMakeLists.txt
  src/cvc4.i
  src/expr/symbol_table.i
  src/parser/cvc4parser.i
  src/parser/input.i
  src/parser/parse_op.i
  src/parser/parser.i
  src/parser/parser_builder.i
  src/parser/parser_exception.i
  src/smt/command.i
Labels: major, moderate

#3786 Minor code removal
  src/expr/dtype.h
  src/theory/datatypes/theory_datatypes_type_rules.h
Labels: minor, simple

#3782 Remove unused code
  src/cvc4.i
  src/expr/datatype.i
  src/expr/expr_manager.i
  src/smt/command.cpp
  src/util/CMakeLists.txt
  src/util/debug.h
Labels: minor, simple

#3767 Remove front-end support for Chain
  src/CMakeLists.txt
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/api/cvc4cppkind.h
  src/expr/CMakeLists.txt
  src/expr/chain.h
  src/expr/chain.i
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/smt2.cpp
  src/parser/tptp/tptp.cpp
  src/printer/cvc/cvc_printer.cpp
  src/printer/smt2/smt2_printer.cpp
  src/proof/theory_proof.cpp
  src/theory/builtin/kinds
  src/theory/builtin/theory_builtin_rewriter.cpp
  src/theory/builtin/theory_builtin_rewriter.h
  src/theory/builtin/theory_builtin_type_rules.h
  test/regress/regress0/printer/let_shadowing.smt2
  test/unit/api/op_black.h
  test/unit/api/solver_black.h
Labels: moderate, normal

#3787 Remove IntReal tightening axioms from th_lira.plf
  proofs/signatures/th_lira.plf
  proofs/signatures/th_lira_test.plf
Labels: minor, simple

#3768 Split extended functions solver in strings
  src/CMakeLists.txt
  src/theory/strings/extf_solver.cpp
  src/theory/strings/extf_solver.h
  src/theory/strings/solver_state.cpp
  src/theory/strings/solver_state.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: moderate, normal

#3791 Simple changes towards unicode string standard
  src/parser/smt2/smt2.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/code-eval.smt2
  test/regress/regress0/strings/code-perf.smt2
  test/regress/regress0/strings/code-sat-neg-one.smt2
  test/regress/regress0/strings/re-syntax.smt2
  test/regress/regress0/strings/replaceall-eval.smt2
  test/regress/regress0/strings/std2.6.1.smt2
Labels: normal, simple

#3794 New C++ API: Remove TOTAL kinds.
  src/api/cvc4cpp.cpp
  src/api/cvc4cppkind.h
  test/unit/api/op_black.h
Labels: normal, simple

#3741 Switch to th_lira.plf
  proofs/signatures/CMakeLists.txt
  src/proof/arith_proof.cpp
  src/proof/arith_proof.h
  test/regress/CMakeLists.txt
  test/regress/regress0/arith/arith-eq.smt2
  test/regress/regress0/arith/arith-mixed-types-no-tighten.smt2
  test/regress/regress0/arith/arith-mixed-types-tighten.smt2
  test/regress/regress0/arith/arith-strict-relaxed.smt2
  test/regress/regress0/arith/arith-strict.smt2
  test/regress/regress0/arith/arith-tighten-1.smt2
  test/regress/regress0/arith/arith-tighten-2.smt2
  test/regress/regress0/arith/bug569.smt2
  test/regress/regress0/arith/integers/ackermann4.smt2
  test/regress/regress0/arith/integers/ackermann5.smt2
  test/regress/regress0/arith/integers/ackermann6.smt2
  test/regress/regress0/lemmas/sc_init_frame_gap.induction.smtv1.smt2
  test/regress/regress1/lemmas/pursuit-safety-8.smtv1.smt2
  test/regress/regress1/lemmas/simple_startup_9nodes.abstract.base.smtv1.smt2
Labels: minor, moderate

#3788 Dump boolean propagations and conflicts for decision tree org-mode viewer
  src/prop/minisat/core/Solver.cc
  src/theory/theory_engine.cpp
Labels: feature, simple

#3792 Move cardinality inference scheme to base solver in strings
  src/theory/strings/base_solver.cpp
  src/theory/strings/base_solver.h
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/regexp_operation.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
  src/theory/strings/theory_strings_utils.cpp
  src/theory/strings/theory_strings_utils.h
  src/theory/strings/type_enumerator.h
Labels: minor, moderate

#3793 Move check memberships to reg exp solver
  src/theory/strings/extf_solver.cpp
  src/theory/strings/extf_solver.h
  src/theory/strings/regexp_solver.cpp
  src/theory/strings/regexp_solver.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: minor, simple

#3796 RIP th_lra.plf
  proofs/signatures/th_lra.plf
  proofs/signatures/th_lra_test.plf
Labels: minor, simple

#3798 Minor refactoring of equality notifications
  src/theory/strings/solver_state.cpp
  src/theory/strings/solver_state.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: minor, simple

#3806 Make lambda rewriter more robust
  src/theory/booleans/theory_bool_rewriter.cpp
  src/theory/builtin/theory_builtin_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/aufbv/issue3737.smt2
Labels: moderate, normal

#3769 Add missing functions to new C++ API
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  test/unit/api/datatype_api_black.h
  test/unit/api/sort_black.h
  test/unit/api/term_black.h
Labels: moderate, normal

#3804 Fix bugs related to printing Sygus commands
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/smt/smt_engine.cpp
Labels: moderate, normal

#3809 Convert parser input interface to api::Term
  src/parser/cvc/cvc_input.cpp
  src/parser/cvc/cvc_input.h
  src/parser/input.h
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/smt2_input.cpp
  src/parser/smt2/smt2_input.h
  src/parser/smt2/sygus_input.cpp
  src/parser/smt2/sygus_input.h
  src/parser/tptp/tptp_input.cpp
  src/parser/tptp/tptp_input.h
  test/system/ouroborous.cpp
  test/unit/parser/parser_black.h
  test/unit/parser/parser_builder_black.h
Labels: normal, simple

#3797 Utilities for words
  src/CMakeLists.txt
  src/theory/strings/word.cpp
  src/theory/strings/word.h
  src/util/regexp.cpp
  src/util/regexp.h
  test/unit/theory/CMakeLists.txt
  test/unit/theory/theory_strings_word_white.h
Labels: normal, simple

#3811 Fixes for quantifiers documentation
  src/theory/quantifiers/quant_util.h
  src/theory/quantifiers/sygus/synth_conjecture.h
Labels: minor, simple

#3299 bv_to_int preprocessing pass
  src/CMakeLists.txt
  src/options/smt_options.toml
  src/preprocessing/passes/bv_to_int.cpp
  src/preprocessing/passes/bv_to_int.h
  src/preprocessing/preprocessing_pass_registry.cpp
  src/smt/smt_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/bv/bv_to_int1.smt2
  test/regress/regress0/bv/bv_to_int2.smt2
  test/regress/regress0/bv/bv_to_int_bitwise.smt2
  test/regress/regress0/bv/bv_to_int_bvmul1.smt2
  test/regress/regress0/bv/bv_to_int_bvmul2.smt2
  test/regress/regress0/bv/bv_to_int_zext.smt2
  test/regress/regress0/bv/bvuf_to_intuf.smt2
  test/regress/regress0/bv/bvuf_to_intuf_smtlib.smt2
  test/regress/regress0/bv/bvuf_to_intuf_sorts.smt2
  test/regress/regress2/bv_to_int_ashr.smt2
  test/regress/regress2/bv_to_int_shifts.smt2
  test/regress/regress3/bv_to_int_and_or.smt2
Labels: complex, feature, normal

#3815 remove redundant includes
  src/theory/uf/theory_uf.h
Labels: refactor

#3801 Embed mkAssociative utilities within the API.
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/api/cvc4cppkind.h
  src/expr/expr_manager_template.cpp
  src/expr/expr_manager_template.h
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/smt2.cpp
  src/parser/tptp/tptp.cpp
Labels: do not merge, normal, simple

#3823 Minor cleaning of smt2 parser
  src/parser/cvc/Cvc.g
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
Labels: normal, simple

#3821 Remove portfolio leftovers
  configure.sh
  src/CMakeLists.txt
  src/bindings/java/CMakeLists.txt
  src/main/command_executor.h
  src/options/main_options.toml
  src/options/options.h
  src/options/options_public_functions.cpp
  src/prop/cnf_stream.h
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/smt_util/lemma_channels.cpp
  src/smt_util/lemma_channels.h
  src/smt_util/lemma_input_channel.h
  src/smt_util/lemma_output_channel.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  test/unit/prop/cnf_stream_white.h
Labels: normal, simple

#3781 Support for witnessing choice in models
  src/options/smt_options.toml
  src/theory/arith/nl_model.cpp
  src/theory/arith/nl_model.h
  src/theory/arith/nonlinear_extension.cpp
  src/theory/arith/nonlinear_extension.h
  src/theory/theory_model.cpp
  src/theory/theory_model.h
  test/regress/CMakeLists.txt
  test/regress/regress1/nl/issue3300-approx-sqrt-witness.smt2
Labels: moderate, normal

#3799 Move equivalence class info to its own file in strings
  src/CMakeLists.txt
  src/theory/strings/eqc_info.cpp
  src/theory/strings/eqc_info.h
  src/theory/strings/solver_state.cpp
  src/theory/strings/solver_state.h
Labels: minor, simple

#3807 Use default consts when not using any const during grammar normalization
  src/theory/quantifiers/sygus/sygus_grammar_norm.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/issue3802-default-consts.sy
Labels: major, simple

#3808 Minor improvement to ParseOp
  src/parser/parse_op.h
Labels: normal, simple

#3825 Refactor type ascriptions in the parser
  src/parser/cvc/Cvc.g
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
Labels: moderate, normal

#3437 Basic support for regular expression complement
  src/api/cvc4cpp.cpp
  src/api/cvc4cppkind.h
  src/parser/cvc/Cvc.g
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/strings/kinds
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/regexp_operation.h
  src/theory/strings/theory_strings_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/complement-simple.smt2
  test/regress/regress1/strings/complement-test.smt2
Labels: major, moderate

#3812 More fixes for printing sygus commands
  src/parser/smt2/smt2.cpp
  src/printer/printer.cpp
  src/printer/smt2/smt2_printer.cpp
  src/printer/sygus_print_callback.cpp
  src/smt/smt_engine.cpp
  test/regress/regress0/sygus/sygus-uf.sy
  test/regress/regress1/sygus/constant-bool-si-all.sy
  test/regress/regress1/sygus/constant-dec-tree-bug.sy
  test/regress/regress1/sygus/sygus-uf-ex.sy
  test/regress/regress1/sygus/tester.sy
Labels: moderate, normal

#3827 Fix regression
  src/theory/bv/theory_bv.cpp
  test/regress/regress1/bv/issue3654.smt2
  test/regress/regress1/bv/issue3776.smt2
  test/regress/regress1/sygus/issue3802-default-consts.sy
Labels: major, simple

#3780 Use side effect utility for non-linear lemmas
  src/CMakeLists.txt
  src/theory/arith/nl_lemma_utils.h
  src/theory/arith/nonlinear_extension.cpp
  src/theory/arith/nonlinear_extension.h
  test/regress/CMakeLists.txt
  test/regress/regress1/nl/issue3647.smt2
Labels: moderate, normal

#3795 Infrastructure for tautological literals in nonlinear solver
  src/expr/node_algorithm.cpp
  src/expr/node_algorithm.h
  src/theory/arith/nl_model.cpp
  src/theory/arith/nl_model.h
  src/theory/arith/nonlinear_extension.cpp
Labels: moderate, normal

#3819 Some initial work on using words
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/word.cpp
  src/theory/strings/word.h
Labels: moderate, normal

#3817 Initial work towards -Wshadow
  src/api/cvc4cpp.cpp
  src/expr/node.h
  src/expr/type_node.h
  src/preprocessing/passes/int_to_bv.cpp
  src/smt_util/node_visitor.h
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/nonlinear_extension.cpp
  src/theory/arrays/theory_arrays.cpp
  src/theory/assertion.cpp
  src/theory/assertion.h
  src/theory/atom_requests.cpp
  src/theory/atom_requests.h
  src/theory/booleans/theory_bool_rewriter.cpp
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv_rewrite_rules_normalization.h
  src/theory/bv/theory_bv_rewriter.cpp
  src/theory/care_graph.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp_rewriter.cpp
  src/theory/fp/theory_fp_rewriter.h
  src/theory/idl/theory_idl.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/fun_def_process.cpp
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/sygus/cegis_core_connective.cpp
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers/theory_quantifiers.cpp
  src/theory/rewriter.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_rewriter.cpp
  src/theory/sets/theory_sets_rewriter.h
  src/theory/strings/theory_strings.cpp
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/theory_rewriter.h
  src/theory/uf/equality_engine.cpp
  src/theory/uf/equality_engine.h
  src/theory/uf/equality_engine_types.h
  src/theory/uf/theory_uf.cpp
Labels: minor, moderate

#3820 Move fix for vacuous sygus types out of the parser
  src/expr/datatype.cpp
  src/parser/smt2/Smt2.g
Labels: normal, simple

#3833 Disable regression that times out on debug
  test/regress/CMakeLists.txt
Labels: major, simple

#3828 Add support for is_digit and regular expression difference
  src/api/cvc4cpp.cpp
  src/api/cvc4cppkind.h
  src/parser/smt2/smt2.cpp
  src/theory/strings/kinds
  src/theory/strings/theory_strings_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/is_digit_simple.smt2
  test/regress/regress0/strings/re_diff.smt2
Labels: normal, simple

#3826 Fix -Wshadow warnings in common headers
  src/api/cvc4cpp.cpp
  src/expr/node.h
  src/expr/type_node.h
  src/printer/cvc/cvc_printer.cpp
  src/printer/smt2/smt2_printer.cpp
  src/proof/bitvector_proof.cpp
  src/proof/proof_utils.h
  src/theory/bv/bitblast/bitblast_strategies_template.h
  src/theory/bv/theory_bv_rewrite_rules_constant_evaluation.h
  src/theory/bv/theory_bv_rewrite_rules_operator_elimination.h
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
  src/theory/bv/theory_bv_type_rules.h
  src/theory/bv/theory_bv_utils.cpp
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.cpp
  src/util/bitvector.h
Labels: normal, simple

#3835 Fix large models for strings
  src/theory/strings/theory_strings.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/large-model.smt2
Labels: major, simple

#3830 Update purifySygusGTerm to the new API
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
Labels: moderate, normal

#3837 Changing TPTP parser to accomodate new API
  src/parser/tptp/Tptp.g
  src/parser/tptp/tptp.cpp
  src/parser/tptp/tptp.h
Labels: moderate, normal

#3831 Refactor operator applications in the parser
  src/parser/cvc/Cvc.g
  src/parser/parser.cpp
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/tptp/Tptp.g
  src/parser/tptp/tptp.cpp
Labels: moderate, normal

#3840 Use enum for quantifiers rewrite steps
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
Labels: minor, simple

#3841 Replace conditional rewrite pass in quantifiers with the extended rewriter
  src/options/quantifiers_options.toml
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
  test/regress/CMakeLists.txt
  test/regress/regress0/quantifiers/agg-rew-test-cf.smt2
  test/regress/regress0/quantifiers/agg-rew-test.smt2
  test/regress/regress1/sygus/issue3839-cond-rewrite.smt2
Labels: do not merge, major, moderate

#3843 Fix assertion related to isAssignable
  src/theory/theory_model_builder.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/arrays/issue3813-massign-assert.smt2
Labels: minor, simple

#3846 propEngine: Reorder class declaration according to code style guidelines.
  src/prop/prop_engine.h
Labels: normal, simple

#3829 Add support for str.from_code
  src/api/cvc4cpp.cpp
  src/api/cvc4cppkind.h
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/evaluator.cpp
  src/theory/strings/extf_solver.cpp
  src/theory/strings/kinds
  src/theory/strings/solver_state.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/theory_strings_rewriter.cpp
  src/theory/strings/theory_strings_rewriter.h
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/from_code.smt2
  test/unit/theory/evaluator_white.h
Labels: moderate, normal

#3844 Throw warning instead of error for non-constant values in check-model stages
  src/smt/smt_engine.cpp
  src/theory/theory_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/issue3729-cm-solved-tf.smt2
  test/regress/regress0/sep/issue3720-check-model.smt2
Labels: minor, simple

#3834 Convert more uses of string to word
  src/expr/type_node.cpp
  src/expr/type_node.h
  src/printer/smt2/smt2_printer.cpp
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/solver_state.cpp
  src/theory/strings/theory_strings_rewriter.cpp
Labels: do not merge, moderate, normal
