Repository cvc5/cvc5, pull requests merged in 2020-11, with the labels that each got.

#5368 Avoid dynamic allocation in symbol table implementation
  src/expr/symbol_table.cpp
Labels: minor, simple

#5369 Miscellaneous cleaning of parser
  src/parser/parser.h
  src/parser/smt2/Smt2.g
Labels: minor, simple

#5377 Update strings proxy variable map to be context independent
  src/theory/strings/term_registry.cpp
  src/theory/strings/term_registry.h
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue5374-proxy-i.smt2
Labels: normal, simple

#5367 contrib: Remove dependency directories.
  contrib/get-abc
  contrib/get-cadical
  contrib/get-cryptominisat
  contrib/get-drat2er
  contrib/get-glpk-cut-log
  contrib/get-gmp-dev
  contrib/get-kissat
  contrib/get-lfsc-checker
  contrib/get-poly
  contrib/get-script-header.sh
  contrib/get-symfpu
Labels: major, simple

#5375 Move sygus qe preproc to its own file
  src/CMakeLists.txt
  src/theory/quantifiers/sygus/sygus_qe_preproc.cpp
  src/theory/quantifiers/sygus/sygus_qe_preproc.h
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus/synth_engine.h
Labels: minor, simple

#5386 Reset built model flag at presolve in nonlinear
  src/theory/arith/nl/nonlinear_extension.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/nl/issue5372-2-no-m-presolve.smt2
Labels: major, simple

#5383 (proof-new) Add support for BV proofs with the simple bitblasting solver
  src/CMakeLists.txt
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/bv/bitblast/simple_bitblaster.cpp
  src/theory/bv/bitblast/simple_bitblaster.h
  src/theory/bv/bv_solver_simple.cpp
  src/theory/bv/bv_solver_simple.h
  src/theory/bv/proof_checker.cpp
  src/theory/bv/proof_checker.h
  src/theory/bv/theory_bv.cpp
Labels: simple

#5393 Add scope methods constructing types in API
  src/api/cvc4cpp.cpp
  src/expr/node_manager.cpp
  src/expr/node_manager.h
Labels: major, simple

#5391 Add constants from equality engine evaluation to model
  src/theory/strings/theory_strings.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue5330.smt2
  test/regress/regress1/strings/issue5330_2.smt2
Labels: major, moderate

#5366 Remove mkSingleton from the API
  examples/api/python/sets.py
  examples/api/sets.cpp
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/api/python/cvc4.pxd
  src/api/python/cvc4.pxi
  src/parser/cvc/Cvc.g
  src/parser/smt2/smt2.cpp
  src/theory/arith/nl/nonlinear_extension.cpp
  test/unit/theory/theory_sets_type_rules_white.h
Labels: normal, simple

#5394 Simplify printing with respect to expression types
  src/expr/expr_iomanip.cpp
  src/expr/expr_iomanip.h
  src/expr/expr_template.cpp
  src/expr/expr_template.h
  src/expr/node.h
  src/expr/node_value.cpp
  src/expr/node_value.h
  src/expr/type_node.cpp
  src/expr/type_node.h
  src/options/expr_options.toml
  src/parser/parser.cpp
  src/printer/ast/ast_printer.cpp
  src/printer/ast/ast_printer.h
  src/printer/cvc/cvc_printer.cpp
  src/printer/cvc/cvc_printer.h
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/printer/tptp/tptp_printer.cpp
  src/printer/tptp/tptp_printer.h
  src/smt/command.cpp
  src/smt/command.h
  src/smt/node_command.cpp
  src/smt/node_command.h
  src/smt/options_manager.cpp
  src/smt/update_ostream.h
  test/unit/expr/node_black.h
Labels: normal, simple

#5388 Split sygus template inference to its own file
  src/CMakeLists.txt
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.h
  src/theory/quantifiers/sygus/cegis_core_connective.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/template_infer.cpp
  src/theory/quantifiers/sygus/template_infer.h
Labels: normal, simple

#5362 (proof-new) Miscellaneous changes to strings for proofs
  src/theory/strings/arith_entail.cpp
  src/theory/strings/base_solver.cpp
  src/theory/strings/infer_proof_cons.cpp
  src/theory/strings/normal_form.cpp
  src/theory/strings/term_registry.cpp
  src/theory/strings/theory_strings_preprocess.cpp
Labels: minor, simple

#5349 Fix issue #5342
  src/theory/sets/cardinality_extension.cpp
  src/theory/sets/cardinality_extension.h
  src/theory/sets/solver_state.cpp
  src/theory/sets/solver_state.h
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sets/issue5342.smt2
  test/regress/regress1/sets/issue5342_difference_version.smt2
Labels: bug, normal, simple

#5376 Do not regress explanations of datatype lemmas
  src/theory/datatypes/inference_manager.cpp
  test/regress/CMakeLists.txt
  test/regress/regress2/sygus/policyM.sy
Labels: normal, simple

#5403 Properly reset interrupt for incremental calls to minisat
  src/prop/minisat/minisat.cpp
Labels: normal, simple

#5404 Debug fix
  src/proof/lfsc/lfsc_term_process.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/andy1.smt2
  test/regress/regress0/proofs/andy1.smt2
Labels: bug

#5401 Simplify handling of subtypes in smt2 printer
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/smt/command.cpp
  test/regress/regress0/get-value-reals-ints.smt2
  test/regress/regress0/get-value-reals.smt2
  test/regress/regress1/arith/mult.02.smt2
Labels: moderate, normal

#5380 Add symbol manager
  src/CMakeLists.txt
  src/main/command_executor.cpp
  src/main/command_executor.h
  src/main/driver_unified.cpp
  src/main/interactive_shell.cpp
  src/main/interactive_shell.h
  src/parser/CMakeLists.txt
  src/parser/cvc/cvc.h
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/parser_builder.cpp
  src/parser/parser_builder.h
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/parser/symbol_manager.cpp
  src/parser/symbol_manager.h
  src/parser/tptp/tptp.cpp
  src/parser/tptp/tptp.h
  test/api/ouroborous.cpp
  test/api/smt2_compliance.cpp
  test/unit/main/interactive_shell_black.h
  test/unit/parser/parser_black.h
  test/unit/parser/parser_builder_black.h
Labels: complex, normal

#5390 Migrate some documentation about attributes
  src/expr/attribute.h
Labels: minor, simple

#5398 Add getSubtermKinds to node algorithm
  src/expr/node_algorithm.cpp
  src/expr/node_algorithm.h
Labels: normal, simple

#5347 Make mkGroundTerm deterministic
  src/CMakeLists.txt
  src/theory/builtin/theory_builtin_type_rules.cpp
  src/theory/builtin/theory_builtin_type_rules.h
Labels: normal, simple

#5407 Do not mark extended functions as reduced based on decomposing contains
  src/smt/check_models.cpp
  src/theory/strings/extf_solver.cpp
  test/regress/CMakeLists.txt
  test/regress/regress2/strings/issue5381.smt2
Labels: normal, simple

#5411 Fix preregistration in TheorySep before declare-heap
  src/theory/sep/theory_sep.cpp
  src/theory/sep/theory_sep.h
  test/regress/CMakeLists.txt
  test/regress/regress0/sep/issue5343-err.smt2
Labels: normal, simple

#5410 Pass symbol manager to commands
  src/main/command_executor.cpp
  src/main/command_executor.h
  src/smt/command.cpp
  src/smt/command.h
  test/api/smt2_compliance.cpp
Labels: normal, simple

#5397 Add simple substitution utility
  src/expr/subs.cpp
  src/expr/subs.h
Labels: moderate, normal

#5419 Rewrite witness terms at prerewrite
  src/theory/builtin/theory_builtin_rewriter.cpp
  src/theory/builtin/theory_builtin_rewriter.h
Labels: normal, simple

#5420 Move symbol manager to src/expr/
  src/CMakeLists.txt
  src/expr/CMakeLists.txt
  src/expr/symbol_manager.cpp
  src/expr/symbol_manager.h
  src/main/command_executor.cpp
  src/main/command_executor.h
  src/main/interactive_shell.cpp
  src/main/interactive_shell.h
  src/parser/CMakeLists.txt
  src/parser/parser.h
  src/parser/parser_builder.h
  src/smt/command.cpp
  src/smt/command.h
  test/api/ouroborous.cpp
  test/api/smt2_compliance.cpp
  test/unit/main/interactive_shell_black.h
  test/unit/parser/parser_black.h
  test/unit/parser/parser_builder_black.h
Labels: normal, simple

#5423 (proof-new) Preparations for nonlinear arithmetic proofs
  src/CMakeLists.txt
  src/theory/arith/inference_manager.cpp
  src/theory/arith/inference_manager.h
  src/theory/arith/nl/ext/ext_state.cpp
  src/theory/arith/nl/ext/ext_state.h
  src/theory/arith/nl/ext/monomial_bounds_check.cpp
  src/theory/arith/nl/ext/proof_checker.cpp
  src/theory/arith/nl/ext/proof_checker.h
  src/theory/arith/nl/ext/tangent_plane_check.cpp
  src/theory/arith/nl/iand_solver.cpp
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/nl/transcendental_solver.cpp
  src/theory/theory_inference_manager.cpp
Labels: moderate, normal

#5424 Make symbol manager context dependent
  src/expr/symbol_manager.cpp
  src/expr/symbol_manager.h
  src/parser/parser.cpp
  src/parser/parser.h
Labels: moderate, normal

#5408 (proof-new) Add datatypes inference to proof constructor
  src/theory/datatypes/infer_proof_cons.cpp
  src/theory/datatypes/infer_proof_cons.h
Labels: moderate, normal

#5337 (proof-new) Improve printing and debugging for pedantic checking
  src/expr/proof_checker.cpp
  src/expr/proof_checker.h
  src/options/smt_options.toml
  src/smt/proof_post_processor.cpp
Labels: minor, moderate

#5338 (proof-new) Fix true explanations of propagations in pf equality engine
  src/expr/proof_node_manager.cpp
  src/expr/proof_node_manager.h
  src/theory/uf/proof_equality_engine.cpp
Labels: minor, moderate

#5339 (proof-new) Proofs for skolemization
  src/theory/quantifiers/proof_checker.cpp
  src/theory/quantifiers/skolemize.cpp
  src/theory/quantifiers/skolemize.h
  src/theory/quantifiers_engine.cpp
Labels: minor, moderate

#5399 Fix handling of redundant refinement lemmas in sygus solver
  src/theory/quantifiers/sygus/synth_conjecture.cpp
Labels: normal, simple

#5356 (proof-new) Separate explanation stages in proof equality engine
  src/theory/uf/proof_equality_engine.cpp
  src/theory/uf/proof_equality_engine.h
Labels: minor, moderate

#5415 Models standard
  NEWS
  src/printer/smt2/smt2_printer.cpp
  test/regress/regress0/datatypes/dt-param-2.6-print.smt2
  test/regress/regress0/parser/strings20.smt2
  test/regress/regress0/parser/strings25.smt2
  test/regress/regress0/simple-dump-model.smt2
  test/regress/regress0/smt2output.smt2
Labels: bug

#5425 Fix printing of define named function
  src/smt/command.cpp
Labels: minor, simple

#5389 Simplify sygus solver and sygus stream
  src/theory/decision_manager.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/synth_engine.cpp
Labels: moderate, normal

#5430 Make regular expression difference left associative
  src/api/cvc4cpp.cpp
  src/theory/strings/kinds
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/issue5428-re-diff-assoc.smt2
Labels: normal, simple

#5429 (proof-new) Add proof for NL_SIGN lemma.
  src/theory/arith/nl/ext/ext_state.cpp
  src/theory/arith/nl/ext/ext_state.h
  src/theory/arith/nl/ext/monomial_check.cpp
  src/theory/arith/nl/ext/monomial_check.h
  src/theory/arith/nl/nonlinear_extension.cpp
Labels: moderate, normal

#5438 (proof-new) Add proofs for NL_SPLIT_ZERO lemma
  src/theory/arith/nl/ext/split_zero_check.cpp
  src/theory/arith/nl/ext/split_zero_check.h
Labels: moderate, normal

#5437 (proof-new) Add proofs for factoring lemmas.
  src/theory/arith/nl/ext/factoring_check.cpp
  src/theory/arith/nl/ext/factoring_check.h
  src/theory/arith/nl/nonlinear_extension.cpp
Labels: moderate, normal

#5434 Add more features to symbol manager
  src/expr/symbol_manager.cpp
  src/expr/symbol_manager.h
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/Smt2.g
Labels: moderate, normal

#5436 (proof-new) Enable proofs for datatypes
  src/CMakeLists.txt
  src/theory/datatypes/inference.cpp
  src/theory/datatypes/inference.h
  src/theory/datatypes/inference_manager.cpp
  src/theory/datatypes/inference_manager.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
Labels: moderate, normal

#5440 (proof-new) Prepare transcendental solver for proofs
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/transcendental_solver.cpp
  src/theory/arith/nl/transcendental_solver.h
Labels: minor, moderate

#5409 (proof-new) Proofs for non-clausal simplification
  src/preprocessing/passes/non_clausal_simp.cpp
  src/preprocessing/passes/non_clausal_simp.h
Labels: moderate, normal

#5435 Stop on conflict in extended string solver
  src/theory/strings/extf_solver.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/issue5384-double-conflict.smt2
Labels: minor, simple

#4763 Improve accuracy of resource limitation
  contrib/learn_resource_weights.py
  src/options/smt_options.toml
  src/prop/bvminisat/core/Solver.cc
  src/prop/cnf_stream.cpp
  src/prop/cnf_stream.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/theory_arith_private.cpp
  src/theory/rewriter.cpp
  src/theory/rewriter.h
  src/util/resource_manager.cpp
  src/util/resource_manager.h
Labels: feature, minor, moderate

#5442 Cleaning up scopes in preparation for symbol manager
  src/expr/symbol_manager.cpp
  src/expr/symbol_manager.h
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
Labels: moderate, normal

#5449 Refactor tangent plane lemmas
  src/theory/arith/nl/ext/tangent_plane_check.cpp
Labels: moderate, normal

#5455 Fix tangent plane lemmas
  src/theory/arith/nl/ext/tangent_plane_check.cpp
Labels: bug, major, moderate

#5453 FloatingPoint: Clean up and document header, format.
  src/api/cvc4cpp.cpp
  src/expr/type_node.h
  src/printer/smt2/smt2_printer.cpp
  src/theory/fp/fp_converter.cpp
  src/theory/fp/theory_fp_rewriter.cpp
  src/theory/fp/theory_fp_type_rules.h
  src/util/floatingpoint.cpp
  src/util/floatingpoint.h.in
Labels: normal, simple

#5457 Fix asan issues related to solver and symbol manager
  src/main/command_executor.cpp
  src/main/command_executor.h
  test/unit/main/interactive_shell_black.h
Labels: major, simple

#5451 Use symbol manager for get assignment
  src/api/cvc4cpp.cpp
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/printer/ast/ast_printer.cpp
  src/printer/ast/ast_printer.h
  src/printer/cvc/cvc_printer.cpp
  src/printer/cvc/cvc_printer.h
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/smt/command.cpp
  src/smt/command.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  test/regress/CMakeLists.txt
  test/regress/regress0/named-expr-use.smt2
Labels: moderate, normal

#5433 Do not expand definitions of extended arithmetic operators
  src/smt/process_assertions.cpp
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/arith/theory_arith_private.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/arith/div.02.smt2
  test/regress/regress0/nl/issue3475.smt2
  test/regress/regress0/quantifiers/issue4476-ext-rew.smt2
  test/regress/regress1/arith/div.06.smt2
  test/regress/regress1/arith/mod.03.smt2
  test/regress/regress1/nl/div-mod-partial.smt2
  test/regress/regress1/quantifiers/issue3664.smt2
  test/regress/regress1/quantifiers/issue4062-cegqi-aux.smt2
  test/regress/regress1/quantifiers/issue4685-wrewrite.smt2
  test/regress/regress1/quantifiers/lia-witness-div-pp.smt2
  test/regress/regress1/sets/issue4391-card-lasso.smt2
  test/regress/regress1/sygus/issue3634.smt2
Labels: moderate, normal

#5450 Minor cleanup of SmtEngine
  src/preprocessing/passes/unconstrained_simplifier.cpp
  src/preprocessing/passes/unconstrained_simplifier.h
  src/preprocessing/preprocessing_pass_context.h
  src/smt/preprocessor.cpp
  src/smt/preprocessor.h
  src/smt/process_assertions.cpp
  src/smt/process_assertions.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
Labels: minor, simple

#5431 (proof-new) Make sure CAD proofs are properly closed.
  src/theory/arith/nl/cad/cdcac.cpp
  src/theory/arith/nl/cad/cdcac.h
  src/theory/arith/nl/cad/proof_generator.h
  src/theory/arith/nl/cad_solver.cpp
Labels: minor, simple

#5444 Add let binding utility
  src/CMakeLists.txt
  src/printer/let_binding.cpp
  src/printer/let_binding.h
Labels: moderate, normal

#5467 Disable slow nl regression
  test/regress/CMakeLists.txt
Labels: normal, simple

#5464 Add -> operator overload for cd* iterators.
  src/context/cdhashmap.h
  src/context/cdhashset.h
  src/context/cdlist.h
Labels: normal, simple

#5465 (proof-new) Fix CAD proofs (again)
  src/theory/arith/nl/cad/cdcac.cpp
  src/theory/arith/nl/cad/cdcac.h
  src/theory/arith/nl/cad/proof_generator.cpp
  src/theory/arith/nl/cad/proof_generator.h
  src/theory/arith/nl/cad_solver.cpp
  src/theory/arith/nl/cad_solver.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/lazy_tree_proof_generator.cpp
  src/theory/lazy_tree_proof_generator.h
Labels: moderate, normal

#5468 Use symbol manager for unsat cores
  src/CMakeLists.txt
  src/expr/symbol_manager.cpp
  src/parser/smt2/Smt2.g
  src/parser/tptp/Tptp.g
  src/printer/smt2/smt2_printer.cpp
  src/printer/tptp/tptp_printer.cpp
  src/proof/unsat_core.cpp
  src/proof/unsat_core.h
  src/smt/command.cpp
  src/smt/command.h
  src/smt/expr_names.cpp
  src/smt/expr_names.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
Labels: moderate, normal

#5475 Fix issues related to eliminating extended arithmetic operators
  src/theory/arith/theory_arith.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/theory_preprocessor.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue5469-aext.smt2
  test/regress/regress1/quantifiers/issue5470-aext.smt2
  test/regress/regress1/quantifiers/issue5471-aext.smt2
Labels: moderate, normal

#5474 (proof-new) Add new templated CDProofSet
  src/expr/CMakeLists.txt
  src/expr/lazy_proof_set.cpp
  src/expr/lazy_proof_set.h
  src/expr/proof_set.h
  src/smt/preprocess_proof_generator.cpp
  src/smt/preprocess_proof_generator.h
  src/theory/arith/nl/cad/cdcac.cpp
  src/theory/arith/nl/cad/proof_generator.cpp
  src/theory/arith/nl/cad/proof_generator.h
  src/theory/arith/nl/ext/ext_state.cpp
  src/theory/arith/nl/ext/ext_state.h
  src/theory/arith/nl/ext/factoring_check.cpp
  src/theory/arith/nl/ext/factoring_check.h
  src/theory/arith/nl/ext/monomial_check.cpp
  src/theory/arith/nl/ext/split_zero_check.cpp
  src/theory/arith/nl/ext/split_zero_check.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/trust_substitutions.cpp
  src/theory/trust_substitutions.h
Labels: moderate, normal

#5476 Include stddef.h (needed for size_t) in cvc4_public.h
  src/context/cdhashmap.h
  src/expr/attribute.h
  src/expr/attribute_internals.h
  src/expr/attribute_unique_id.h
  src/expr/expr_template.h
  src/expr/kind_map.h
  src/expr/node.h
  src/expr/node_builder.h
  src/expr/node_traversal.h
  src/expr/node_value.h
  src/expr/type.h
  src/expr/type_node.h
  src/include/cvc4_public.h
  src/options/options_template.cpp
  src/parser/antlr_input.cpp
  src/parser/cvc/Cvc.g
  src/parser/memory_mapped_input_buffer.cpp
  src/parser/parser.cpp
  src/parser/smt2/Smt2.g
  src/parser/tptp/Tptp.g
  src/proof/sat_proof.h
  src/prop/sat_solver.h
  src/theory/arith/bound_counts.h
  src/theory/arith/fc_simplex.h
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/soi_simplex.h
  src/theory/arith/tableau_sizes.h
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
  src/theory/strings/theory_strings_preprocess.cpp
  src/util/bitvector.h
  src/util/gmp_util.h
  src/util/hash.h
  src/util/iand.h
  src/util/index.cpp
  src/util/index.h
  src/util/rational_gmp_imp.h
  src/util/regexp.h
  src/util/resource_manager.h
  src/util/safe_print.h
  src/util/statistics_registry.h
  src/util/string.h
Labels: major, simple

#5472 Use new let binding utility in smt2 printer
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  test/regress/regress0/printer/let_shadowing.smt2
  test/regress/regress1/quantifiers/dump-inst-i.smt2
  test/regress/regress1/quantifiers/dump-inst-proof.smt2
  test/regress/regress1/quantifiers/dump-inst.smt2
Labels: moderate, normal

#5477 Enable new implementation of CEGQI based on nested quantifier elimination
  src/smt/quant_elim_solver.cpp
  src/smt/set_defaults.cpp
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.h
  src/theory/quantifiers/inst_match_trie.cpp
  src/theory/quantifiers/inst_match_trie.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue4433-nqe.smt2
  test/regress/regress1/quantifiers/issue4849-nqe.smt2
  test/regress/regress1/quantifiers/issue5279-nqe.smt2
  test/regress/regress1/quantifiers/issue5365-nqe.smt2
Labels: moderate, normal

#5439 (proof-new) Add proofs for NL_TANGENT_PLANE
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/arith/nl/ext/proof_checker.cpp
  src/theory/arith/nl/ext/tangent_plane_check.cpp
Labels: moderate, normal

#5488 (proof-new) Allow to pass ProofGenerator to arithmetic inference manager.
  src/theory/arith/inference_manager.cpp
  src/theory/arith/inference_manager.h
  src/theory/arith/nl/ext/monomial_bounds_check.cpp
  src/theory/arith/nl/ext/tangent_plane_check.cpp
  src/theory/arith/nl/iand_solver.cpp
  src/theory/arith/nl/transcendental_solver.cpp
Labels: moderate, normal

#5487 (proof-new) Replace LazyCDProofSet by generic CDProofSet
  src/expr/CMakeLists.txt
  src/expr/lazy_proof_set.cpp
  src/expr/lazy_proof_set.h
  src/expr/proof_set.h
  src/smt/preprocess_proof_generator.cpp
  src/smt/preprocess_proof_generator.h
  src/theory/trust_substitutions.cpp
  src/theory/trust_substitutions.h
Labels: moderate, normal

#5479 Fix use of declaration sequence command in cvc parser
  src/parser/cvc/Cvc.g
Labels: normal, simple

#5493 Fix compiler warnings.
  src/theory/arith/theory_arith_private.cpp
  src/theory/rewriter.cpp
Labels: normal, simple

#5481 Updates to API in preparation for using symbol manager for model
  examples/api/combination.cpp
  examples/api/python/combination.py
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/api/python/cvc4.pxd
  src/api/python/cvc4.pxi
  test/unit/api/solver_black.h
Labels: normal, simple

#5490 Support nested quantifier elimination for get-qe command
  src/smt/quant_elim_solver.cpp
  src/theory/quantifiers/cegqi/nested_qe.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue5484-qe.smt2
  test/regress/regress1/quantifiers/issue5484b-qe.smt2
Labels: moderate, normal

#5495 Fix #5493.
  src/theory/arith/theory_arith_private.cpp
Labels: normal, simple

#5492 FloatingPoint: Separate out symFPU glue code.
  src/theory/fp/fp_converter.cpp
  src/theory/fp/fp_converter.h
  src/theory/fp/theory_fp_rewriter.cpp
  src/theory/fp/theory_fp_type_rules.h
  src/util/floatingpoint.cpp
  src/util/floatingpoint.h.in
  src/util/roundingmode.h
  src/util/symfpu_literal.cpp
  src/util/symfpu_literal.h.in
Labels: moderate, normal

#5494 RoundingMode: Rename enum values to conform to code style guidelines.
  src/api/cvc4cpp.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/fp/fp_converter.cpp
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp_rewriter.cpp
  src/theory/fp/type_enumerator.h
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/util/roundingmode.h
  src/util/symfpu_literal.cpp
Labels: normal, simple

#5497 Fix remove term formula policy for terms beneath quantifiers
  src/smt/term_formula_removal.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_preprocessor.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue5482-rtf-no-fv.smt2
Labels: major, simple

#5500 Rename floatingpoint.h.in -> floatingpoin.h.
  src/CMakeLists.txt
  src/util/CMakeLists.txt
  src/util/floatingpoint.h
Labels: normal, simple

#5502 Rename symfpu_literal.(h.in|cpp) -> floatingpoint_literal_symfpu.(h.in|cpp).
  src/CMakeLists.txt
  src/theory/fp/fp_converter.cpp
  src/util/CMakeLists.txt
  src/util/floatingpoint.cpp
  src/util/floatingpoint_literal_symfpu.cpp
  src/util/floatingpoint_literal_symfpu.h.in
Labels: normal, simple

#5498 Add posRewriteEqual to bags rewriter
  src/theory/bags/bags_rewriter.cpp
  src/theory/bags/bags_rewriter.h
  src/theory/bags/rewrites.cpp
  src/theory/bags/rewrites.h
  test/unit/theory/theory_bags_rewriter_white.h
Labels: normal, simple

#5491 Fix quantifiers scope issue in strings preprocessor
  src/theory/strings/theory_strings_preprocess.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue5483-pp-leq.smt2
Labels: normal, simple

#5485 Add get-info :time
  src/smt/smt_engine.cpp
Labels: normal, simple

#5480 Add declare model symbol methods to SymbolManager and Model
  src/expr/symbol_manager.cpp
  src/expr/symbol_manager.h
  src/smt/model.cpp
  src/smt/model.h
Labels: moderate, normal

#5445 (proof-new) Miscellaneous changes from proof-new
  src/expr/term_conversion_proof_generator.cpp
  src/expr/type_node.cpp
  src/smt/preprocessor.cpp
Labels: minor, simple

#5466 Fix for sygusToBuiltinEval for non-ground composite terms
  src/theory/datatypes/sygus_datatype_utils.cpp
  src/theory/datatypes/sygus_datatype_utils.h
  src/theory/quantifiers/sygus/sygus_eval_unfold.cpp
  src/theory/quantifiers/sygus/sygus_repair_const.cpp
Labels: moderate, normal

#5499 Change UF ho to ppRewrite instead of expand definition
  src/theory/uf/ho_extension.cpp
  src/theory/uf/ho_extension.h
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf.h
  test/regress/regress1/ho/NUM925^1.p
  test/regress/regress1/ho/nested_lambdas-AGT034^2.smt2
  test/regress/regress2/ho/involved_parsing_ALG248^3.p
Labels: normal, simple

#5518 Fix regular expression consume for nested star
  src/theory/strings/regexp_entail.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue5510-re-consume.smt2
Labels: major, simple

#5514 Refactor transcendental solver
  src/CMakeLists.txt
  src/theory/arith/nl/nl_lemma_utils.h
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/nl/transcendental/exponential_solver.cpp
  src/theory/arith/nl/transcendental/exponential_solver.h
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/arith/nl/transcendental/sine_solver.h
  src/theory/arith/nl/transcendental/taylor_generator.cpp
  src/theory/arith/nl/transcendental/taylor_generator.h
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
  src/theory/arith/nl/transcendental/transcendental_solver.h
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  src/theory/arith/nl/transcendental/transcendental_state.h
  src/theory/arith/nl/transcendental_solver.cpp
  src/theory/arith/nl/transcendental_solver.h
Labels: moderate, normal

#5523 Allow printing of null node in let binder
  src/printer/let_binding.cpp
Labels: normal, simple

#5516 Use symbol manager for printing responses get-model
  src/parser/parser.cpp
  src/printer/ast/ast_printer.cpp
  src/printer/ast/ast_printer.h
  src/printer/cvc/cvc_printer.cpp
  src/printer/cvc/cvc_printer.h
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/printer/tptp/tptp_printer.cpp
  src/printer/tptp/tptp_printer.h
  src/smt/command.cpp
  src/smt/node_command.cpp
  test/regress/regress0/datatypes/dt-param-2.6-print.smt2
  test/unit/parser/parser_black.h
Labels: moderate, normal

#5525 Fix transcendental secant plane lemmas
  src/theory/arith/nl/transcendental/exponential_solver.cpp
  src/theory/arith/nl/transcendental/exponential_solver.h
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/arith/nl/transcendental/sine_solver.h
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  src/theory/arith/nl/transcendental/transcendental_state.h
Labels: moderate, normal

#5526 Add regressions for closed issues
  test/regress/CMakeLists.txt
  test/regress/regress1/arith/issue4985-model-success.smt2
  test/regress/regress1/arith/issue4985b-model-success.smt2
  test/regress/regress1/quantifiers/issue5378-witness.smt2
  test/regress/regress1/strings/issue5520-re-consume.smt2
Labels: minor, simple

#5521 Disable fact vs lemma optimization in datatypes for now
  src/theory/datatypes/theory_datatypes.cpp
  test/regress/CMakeLists.txt
Labels: normal, simple

#5531 Fix missed case of theory preprocessing
  src/theory/theory_preprocessor.cpp
Labels: normal, simple

#5532 Fully decouple SmtEngine and the Expr layer
  src/api/cvc4cpp.cpp
  src/expr/type.h
  src/smt/command.cpp
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/theory/smt_engine_subsolver.cpp
  test/unit/expr/attribute_white.h
  test/unit/expr/type_node_white.h
  test/unit/preprocessing/pass_bv_gauss_white.h
  test/unit/prop/cnf_stream_white.h
  test/unit/theory/evaluator_white.h
  test/unit/theory/sequences_rewriter_white.h
  test/unit/theory/theory_arith_white.h
  test/unit/theory/theory_bags_normal_form_white.h
  test/unit/theory/theory_bags_rewriter_white.h
  test/unit/theory/theory_bags_type_rules_white.h
  test/unit/theory/theory_bv_rewriter_white.h
  test/unit/theory/theory_bv_white.h
  test/unit/theory/theory_engine_white.h
  test/unit/theory/theory_quantifiers_bv_instantiator_white.h
  test/unit/theory/theory_quantifiers_bv_inverter_white.h
  test/unit/theory/theory_sets_type_enumerator_white.h
  test/unit/theory/theory_sets_type_rules_white.h
  test/unit/theory/theory_strings_skolem_cache_black.h
  test/unit/theory/theory_strings_word_white.h
  test/unit/theory/theory_white.h
  test/unit/theory/type_enumerator_white.h
Labels: moderate, normal

#5528 Move expand definitions to its own file
  src/CMakeLists.txt
  src/smt/expand_definitions.cpp
  src/smt/expand_definitions.h
  src/smt/preprocessor.cpp
  src/smt/preprocessor.h
  src/smt/process_assertions.cpp
  src/smt/process_assertions.h
Labels: moderate, normal

#5527 Removing infrastructure related to SMT model
  src/smt/check_models.cpp
  src/smt/command.cpp
  src/smt/command.h
  src/smt/dump_manager.cpp
  src/smt/dump_manager.h
  src/smt/model.cpp
  src/smt/model.h
  src/smt/node_command.cpp
  src/smt/node_command.h
  src/smt/smt_engine.cpp
Labels: moderate, normal

#5535 Make CAD solver work for empty set of assertions
  src/theory/arith/nl/cad_solver.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/issue5534-no-assertions.smt2
Labels: normal, simple

#5361 (proof-new) Proofs for regular expression elimination
  src/expr/proof_rule.h
  src/theory/strings/proof_checker.cpp
  src/theory/strings/regexp_elim.cpp
  src/theory/strings/regexp_elim.h
  src/theory/strings/theory_strings.cpp
Labels: minor, moderate

#5536 Remove includes for old API from internal code
  src/CMakeLists.txt
  src/expr/CMakeLists.txt
  src/expr/array.h
  src/expr/symbol_table.h
  src/expr/type.h
  src/expr/type_properties_template.h
  src/smt/command.cpp
  src/smt/command.h
  src/smt/dump_manager.cpp
  src/smt/listeners.cpp
  src/smt/model_blocker.h
  src/smt/model_core_builder.h
  src/smt/proof_manager.h
  src/smt_util/boolean_simplification.h
  src/theory/arith/arith_static_learner.cpp
  src/theory/datatypes/type_enumerator.h
  src/theory/fp/fp_converter.h
  src/theory/quantifiers/expr_miner.h
  src/theory/quantifiers/sygus/sygus_abduct.h
  src/theory/quantifiers/sygus/sygus_grammar_norm.h
  src/theory/quantifiers/sygus/sygus_interpol.h
  src/theory/quantifiers/sygus/sygus_qe_preproc.h
  src/theory/smt_engine_subsolver.h
Labels: normal, simple

#5496 Eliminate uses of SExpr from the parser.
  src/api/cvc4cpp.cpp
  src/main/driver_unified.cpp
  src/parser/cvc/Cvc.g
  src/parser/parser.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/parser/tptp/Tptp.g
  src/smt/command.cpp
  src/smt/command.h
  src/smt/smt_engine.cpp
Labels: moderate, normal

#5503 floatingpoint: Use unique_ptr for FloatingPointLiteral pointer.
  src/util/floatingpoint.cpp
  src/util/floatingpoint.h
Labels: normal, simple

#5538 (proof-new) First step for transcendental proofs
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/arith/nl/ext/proof_checker.cpp
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
  src/theory/arith/nl/transcendental/transcendental_solver.h
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  src/theory/arith/nl/transcendental/transcendental_state.h
Labels: moderate, normal

#5529 Use new let binding in AST printer
  src/printer/ast/ast_printer.cpp
  src/printer/ast/ast_printer.h
  src/printer/smt2/smt2_printer.cpp
Labels: minor, simple

#5501 fp_converter: Properly separate out symbolic glue code.
  src/theory/fp/fp_converter.cpp
  src/theory/fp/fp_converter.h
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp.h
Labels: normal, simple
