Repository cvc5/cvc5, pull requests merged in 2020-09, with the labels that each got.

#4968 Add the inference manager for datatypes
  src/CMakeLists.txt
  src/theory/datatypes/inference_manager.cpp
  src/theory/datatypes/inference_manager.h
  src/theory/inference_manager_buffered.cpp
  src/theory/inference_manager_buffered.h
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
Labels: moderate, normal

#4978 'fix-install-headers.sh' should respect DESTDIR environment variable
  src/fix-install-headers.sh
Labels: simple

#4991 CMS: Update to version 5.8.0.
  contrib/get-cryptominisat
Labels: normal, simple

#4990 Add TheoryInference base class
  src/CMakeLists.txt
  src/theory/datatypes/inference_manager.cpp
  src/theory/datatypes/inference_manager.h
  src/theory/inference_manager_buffered.cpp
  src/theory/inference_manager_buffered.h
  src/theory/theory_inference.cpp
  src/theory/theory_inference.h
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
Labels: moderate, normal

#4986 (new theory) Update TheoryDatatypes to the new standard
  src/theory/datatypes/inference_manager.cpp
  src/theory/datatypes/inference_manager.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
Labels: moderate, normal

#4943 [API] Fix Python Examples
  CMakeLists.txt
  cmake/CVC4Config.cmake.in
  examples/api/python/CMakeLists.txt
  examples/api/python/exceptions.py
  examples/api/python/floating_point.py
  examples/api/python/sygus-fun.py
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/api/python/cvc4.pxd
  src/api/python/cvc4.pxi
  src/parser/smt2/smt2.cpp
  src/theory/logic_info.cpp
  test/regress/regress1/quantifiers/issue3481-unsat1.smt2
  test/regress/regress1/quantifiers/issue3481.smt2
  test/unit/api/python/test_sort.py
  test/unit/api/solver_black.h
Labels: moderate, normal

#4951 (new theory) Update TheorySets to the new interface
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
Labels: moderate, normal

#4960 Add ArithLemma and arith::InferenceManager
  src/CMakeLists.txt
  src/theory/arith/arith_lemma.cpp
  src/theory/arith/arith_lemma.h
  src/theory/arith/inference_manager.cpp
  src/theory/arith/inference_manager.h
  src/theory/arith/nl/cad_solver.cpp
  src/theory/arith/nl/nl_lemma_utils.cpp
  src/theory/arith/nl/nl_lemma_utils.h
  src/theory/arith/nl/nl_model.cpp
  src/theory/arith/nl/nl_solver.cpp
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/nl/transcendental_solver.cpp
  src/theory/inference_manager_buffered.cpp
  src/theory/inference_manager_buffered.h
Labels: simple

#5003 Use std::unique_ptr instead of std::shared_ptr for inference manager
  src/theory/arith/inference_manager.cpp
  src/theory/arith/inference_manager.h
  src/theory/datatypes/inference_manager.cpp
  src/theory/inference_manager_buffered.cpp
  src/theory/inference_manager_buffered.h
Labels: simple

#5000 (new theory) Update TheoryArrays to the new standard
  src/CMakeLists.txt
  src/theory/arrays/static_fact_manager.cpp
  src/theory/arrays/static_fact_manager.h
  src/theory/arrays/theory_arrays.cpp
  src/theory/arrays/theory_arrays.h
Labels: moderate, normal

#5004 Minor updates to theory inference manager
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/inference_manager_buffered.cpp
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
Labels: normal, simple

#4988 Introduce an internal version of Commands.
  src/CMakeLists.txt
  src/printer/ast/ast_printer.cpp
  src/printer/ast/ast_printer.h
  src/printer/cvc/cvc_printer.cpp
  src/printer/cvc/cvc_printer.h
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/printer/tptp/tptp_printer.cpp
  src/printer/tptp/tptp_printer.h
  src/smt/dump.h
  src/smt/dump_manager.cpp
  src/smt/dump_manager.h
  src/smt/listeners.cpp
  src/smt/model.cpp
  src/smt/model.h
  src/smt/node_command.cpp
  src/smt/node_command.h
  src/smt/smt_engine.cpp
Labels: moderate, normal

#4972 (proof-new) Make term conversion proof generator optionally term-context sensitive
  src/expr/CMakeLists.txt
  src/expr/term_conversion_proof_generator.cpp
  src/expr/term_conversion_proof_generator.h
Labels: moderate, normal

#4995 Use SMT-COMP configuration for competition build
  CMakeLists.txt
  NEWS
  cmake/ConfigCompetition.cmake
  cmake/Helpers.cmake
Labels: minor, simple

#5002 (proof-new) Add proof support in TheoryUF
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/uf/ho_extension.cpp
  src/theory/uf/ho_extension.h
  src/theory/uf/proof_checker.cpp
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf.h
  src/theory/uf/theory_uf_rewriter.h
Labels: do not merge, moderate, normal

#4962 (proof-new) Updates to builtin proof checker
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/builtin/proof_checker.cpp
  src/theory/builtin/proof_checker.h
  src/theory/rewriter.cpp
  src/theory/rewriter.h
Labels: moderate, normal

#5005 Remove #line directives from generated files.
  src/expr/expr_manager_template.cpp
  src/expr/expr_manager_template.h
  src/expr/expr_template.cpp
  src/expr/expr_template.h
  src/expr/kind_template.cpp
  src/expr/kind_template.h
  src/expr/metakind_template.h
  src/expr/mkexpr
  src/expr/mkkind
  src/expr/mkmetakind
  src/expr/type_checker_template.cpp
  src/expr/type_properties_template.h
  src/theory/mkrewriter
  src/theory/mktheorytraits
  src/theory/theory_traits_template.h
  src/theory/type_enumerator_template.cpp
Labels: moderate

#4998 [Python API] Add missing methods to Datatype/Term
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/api/python/cvc4.pxd
  src/api/python/cvc4.pxi
  test/unit/api/python/test_datatype_api.py
  test/unit/api/python/test_term.py
Labels: moderate, normal

#5006 Fix CryptoMiniSat build, regression
  src/prop/cryptominisat.cpp
  test/regress/regress1/sygus-abduct-test-user.smt2
Labels: major, simple

#4984 (proof-new) Improve debugging infrastructure for open proofs
  src/expr/proof_generator.cpp
  src/expr/proof_generator.h
  src/expr/proof_node_manager.cpp
Labels: minor, moderate

#5001 (proof-new) Support proofs of quantifier instantiation
  src/preprocessing/passes/quantifiers_preprocess.cpp
  src/preprocessing/passes/sygus_inference.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/instantiate.h
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
  src/theory/theory_engine.cpp
Labels: moderate, normal

#5010 Make ExtTheory independent of Theory
  src/CMakeLists.txt
  src/theory/arith/nl/ext_theory_callback.cpp
  src/theory/arith/nl/ext_theory_callback.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
  src/theory/bv/bv_subtheory_core.cpp
  src/theory/bv/bv_subtheory_core.h
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
  src/theory/ext_theory.cpp
  src/theory/ext_theory.h
  src/theory/strings/extf_solver.cpp
  src/theory/strings/extf_solver.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  src/theory/theory.h
Labels: major, moderate

#4996 Make nonlinear extension (more) deterministic
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/engine_output_channel.cpp
Labels: simple

#4999 Basic integration of arith::InferenceManager
  src/CMakeLists.txt
  src/theory/arith/arith_lemma.h
  src/theory/arith/inference_id.cpp
  src/theory/arith/inference_id.h
  src/theory/arith/inference_manager.cpp
  src/theory/arith/inference_manager.h
  src/theory/arith/nl/cad_solver.cpp
  src/theory/arith/nl/iand_solver.cpp
  src/theory/arith/nl/inference.cpp
  src/theory/arith/nl/nl_lemma_utils.h
  src/theory/arith/nl/nl_solver.cpp
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/nl/stats.h
  src/theory/arith/nl/transcendental_solver.cpp
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
Labels: do not merge, moderate

#5007 Update sets inference manager to inherit from InferenceManagerBuffered
  src/theory/inference_manager_buffered.cpp
  src/theory/inference_manager_buffered.h
  src/theory/sets/cardinality_extension.cpp
  src/theory/sets/cardinality_extension.h
  src/theory/sets/inference_manager.cpp
  src/theory/sets/inference_manager.h
  src/theory/sets/solver_state.cpp
  src/theory/sets/solver_state.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
  src/theory/sets/theory_sets_rels.cpp
  src/theory/sets/theory_sets_rels.h
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
Labels: moderate, normal

#5016 Add interfaces for making trust nodes in TheoryInferenceManager.
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
  src/theory/uf/proof_equality_engine.cpp
  src/theory/uf/proof_equality_engine.h
Labels: moderate, normal

#5009 Split lazy bit-vector solver from TheoryBV
  src/CMakeLists.txt
  src/theory/bv/bitblast/eager_bitblaster.cpp
  src/theory/bv/bitblast/eager_bitblaster.h
  src/theory/bv/bitblast/lazy_bitblaster.cpp
  src/theory/bv/bitblast/lazy_bitblaster.h
  src/theory/bv/bv_eager_solver.cpp
  src/theory/bv/bv_eager_solver.h
  src/theory/bv/bv_quick_check.cpp
  src/theory/bv/bv_quick_check.h
  src/theory/bv/bv_solver.h
  src/theory/bv/bv_solver_lazy.cpp
  src/theory/bv/bv_solver_lazy.h
  src/theory/bv/bv_subtheory.h
  src/theory/bv/bv_subtheory_algebraic.cpp
  src/theory/bv/bv_subtheory_algebraic.h
  src/theory/bv/bv_subtheory_bitblast.cpp
  src/theory/bv/bv_subtheory_bitblast.h
  src/theory/bv/bv_subtheory_core.cpp
  src/theory/bv/bv_subtheory_core.h
  src/theory/bv/bv_subtheory_inequality.cpp
  src/theory/bv/bv_subtheory_inequality.h
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv.h
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
  src/theory/theory_state.cpp
  src/theory/theory_state.h
  test/unit/theory/theory_bv_white.h
Labels: major, moderate

#4989 Change the unavailable mercury repository for ABC to the GitHub code base
  contrib/get-abc
Labels: do not merge

#5015 Use arith::InferenceManager for CAD lemmas
  src/theory/arith/inference_manager.cpp
  src/theory/arith/inference_manager.h
  src/theory/arith/nl/cad_solver.cpp
  src/theory/arith/nl/cad_solver.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/sets/cardinality_extension.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
Labels: normal, simple

#5026 Use Result::Sat instead of BenchmarkStatus in printers.
  src/printer/ast/ast_printer.cpp
  src/printer/ast/ast_printer.h
  src/printer/cvc/cvc_printer.cpp
  src/printer/cvc/cvc_printer.h
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/smt/command.cpp
Labels: minor, simple

#5028 Fix non-lib-poly-build issues
  src/theory/arith/nl/cad_solver.cpp
Labels: major, simple

#5025 (new theory) Update TheoryBV to new standard for collectModelValues
  src/theory/bv/bitblast/lazy_bitblaster.cpp
  src/theory/bv/bitblast/lazy_bitblaster.h
  src/theory/bv/bv_quick_check.cpp
  src/theory/bv/bv_quick_check.h
  src/theory/bv/bv_solver.h
  src/theory/bv/bv_solver_lazy.cpp
  src/theory/bv/bv_solver_lazy.h
  src/theory/bv/bv_subtheory.h
  src/theory/bv/bv_subtheory_algebraic.cpp
  src/theory/bv/bv_subtheory_algebraic.h
  src/theory/bv/bv_subtheory_bitblast.cpp
  src/theory/bv/bv_subtheory_bitblast.h
  src/theory/bv/bv_subtheory_core.cpp
  src/theory/bv/bv_subtheory_core.h
  src/theory/bv/bv_subtheory_inequality.cpp
  src/theory/bv/bv_subtheory_inequality.h
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv.h
Labels: moderate, normal

#5029 Fix regression issues related to BV proofs
  test/regress/regress0/bv/ackermann2.smt2
  test/regress/regress0/bv/core/slice-12.smtv1.smt2
  test/regress/regress1/sygus-abduct-test-user.smt2
Labels: major, simple

#5030 Add asLemma flag to theory inference process
  src/theory/arith/nl/nl_lemma_utils.cpp
  src/theory/arith/nl/nl_lemma_utils.h
  src/theory/datatypes/inference_manager.cpp
  src/theory/datatypes/inference_manager.h
  src/theory/inference_manager_buffered.cpp
  src/theory/theory_inference.cpp
  src/theory/theory_inference.h
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
Labels: normal, simple

#5039 Eliminate a custom use of TheorySep in quantifiers engine for EPR
  src/smt/set_defaults.cpp
  src/theory/quantifiers_engine.cpp
  src/theory/sep/theory_sep.cpp
Labels: normal, simple

#4997 Make CVC/API BV div/mod semantics match SMT-LIB
  NEWS
  src/api/cvc4cppkind.h
  src/options/bv_options.toml
  src/smt/set_defaults.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/bv/div_mod.cvc
Labels: moderate, normal

#5041 Fix printing of fp values.
  src/util/floatingpoint.cpp
Labels: major, simple

#5037 Split term registry from theory state in sets
  src/CMakeLists.txt
  src/theory/sets/cardinality_extension.cpp
  src/theory/sets/cardinality_extension.h
  src/theory/sets/solver_state.cpp
  src/theory/sets/solver_state.h
  src/theory/sets/term_registry.cpp
  src/theory/sets/term_registry.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
  src/theory/sets/theory_sets_rels.cpp
  src/theory/sets/theory_sets_rels.h
Labels: moderate, normal

#5033 Add is_singleton operator to the theory of sets
  src/api/cvc4cpp.cpp
  src/api/cvc4cppkind.h
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/sets/kinds
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
  src/theory/sets/theory_sets_rewriter.cpp
  src/theory/sets/theory_sets_type_rules.h
  test/regress/CMakeLists.txt
  test/regress/regress1/sets/is_singleton1.smt2
Labels: normal, simple

#5044 Fixes for regular expressions + sygus
  src/printer/smt2/smt2_printer.cpp
  src/theory/quantifiers/fmf/full_model_check.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/rex-strings-alarm.sy
Labels: normal, simple

#5046 (proof-new) Generalize single step helper in eager proof generator
  src/theory/combination_care_graph.cpp
  src/theory/eager_proof_generator.cpp
  src/theory/eager_proof_generator.h
  src/theory/strings/term_registry.cpp
Labels: normal, simple

#5008 (proof-new) Make proofs in term formula removal term context sensitive
  src/smt/term_formula_removal.cpp
  src/smt/term_formula_removal.h
Labels: moderate, normal

#5011 (proof-new) Minor changes to proof node updater
  src/CMakeLists.txt
  src/expr/proof_node_updater.cpp
  src/expr/proof_node_updater.h
  src/smt/smt_engine.h
Labels: moderate, normal

#5036 Use state and inference manager in UF CardinalityExtension
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
  src/theory/uf/cardinality_extension.cpp
  src/theory/uf/cardinality_extension.h
  src/theory/uf/theory_uf.cpp
Labels: moderate, normal

#5049 Parser error for wrong number of datatypes
  src/parser/smt2/Smt2.g
Labels: minor, simple

#5051 bv2int: refactoring the main translation loop
  src/preprocessing/passes/bv_to_int.cpp
  src/preprocessing/passes/bv_to_int.h
Labels: refactor

#5057 Add witness to cvc printer
  src/printer/cvc/cvc_printer.cpp
Labels: minor, simple

#5013 (proof-new) Use deep copy for base lemma steps in proof equality engine
  src/expr/proof_generator.cpp
  src/expr/proof_generator.h
  src/theory/uf/proof_equality_engine.cpp
Labels: minor, moderate

#5012 (proof-new) Handle mismatched assumptions in proof equality engine during mkScope
  src/expr/proof_node_manager.cpp
  src/theory/uf/proof_equality_engine.cpp
  src/theory/uf/proof_equality_engine.h
Labels: minor, moderate

#5050 Move finite model minimization to UF last call effort
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/theory_state.cpp
  src/theory/theory_state.h
  src/theory/uf/cardinality_extension.cpp
  src/theory/uf/cardinality_extension.h
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf.h
  src/theory/valuation.h
  test/regress/regress0/fmf/issue4850-force-card.smt2
Labels: moderate, normal

#5056 (proof-new) Update TheoryEngine lemma and conflict to TrustNode
  src/prop/theory_proxy.cpp
  src/theory/combination_engine.cpp
  src/theory/engine_output_channel.cpp
  src/theory/shared_terms_database.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: moderate, normal

#5054 (proof-new) Add SMT proof manager
  src/CMakeLists.txt
  src/options/smt_options.toml
  src/preprocessing/assertion_pipeline.cpp
  src/smt/assertions.cpp
  src/smt/assertions.h
  src/smt/proof_manager.cpp
  src/smt/proof_manager.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/smt/smt_solver.cpp
  src/smt/smt_solver.h
Labels: moderate, normal

#5035 Standardize uses of inference manager in datatypes
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
  src/theory/theory_inference_manager.cpp
  src/theory/uf/proof_equality_engine.cpp
Labels: major, moderate

#5062 Fix type for Windows build
  src/preprocessing/passes/bv_to_int.cpp
Labels: major, simple

#4856 Refactoring the rewriter of sets
  src/theory/sep/theory_sep.cpp
  src/theory/sets/normal_form.h
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_rewriter.cpp
  src/theory/sets/theory_sets_rewriter.h
  test/regress/CMakeLists.txt
  test/regress/regress0/sep/simple-080420-const-sets.smt2
  test/unit/theory/theory_sets_type_enumerator_white.h
Labels: moderate, normal

#5063 Interpolation: Add implementation for SyGuS interpolation module (final)
  src/CMakeLists.txt
  src/smt/interpolation_solver.cpp
  src/smt/interpolation_solver.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/smt/smt_engine_state.cpp
  src/smt/smt_engine_state.h
  src/theory/quantifiers/sygus/sygus_interpol.cpp
  src/theory/quantifiers/sygus/sygus_interpol.h
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/interpol1.smt2
  test/regress/regress1/sygus/interpol2.smt2
  test/regress/regress1/sygus/interpol3.smt2
  test/regress/regress1/sygus/interpol_arr1.smt2
  test/regress/regress1/sygus/interpol_arr2.smt2
  test/regress/regress1/sygus/interpol_cosa_1.smt2
  test/regress/regress1/sygus/interpol_dt.smt2
  test/regress/regress1/sygus/interpol_from_pono_1.smt2
  test/regress/regress1/sygus/interpol_from_pono_2.smt2
  test/regress/regress1/sygus/interpol_from_pono_3.smt2
Labels: moderate, normal

#5061 Fix ABC build
  src/theory/bv/bitblast/aig_bitblaster.cpp
Labels: major, simple

#5042 Standard equality engine notify class for Theory
  src/CMakeLists.txt
  src/theory/theory_eq_notify.h
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf.h
Labels: moderate, normal

#5048 Fix needsModel method for CEGQI
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/first_order_model.cpp
  src/theory/quantifiers/first_order_model.h
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue5019-cegqi-i.smt2
Labels: normal, simple

#5053 Move quantifiers engine private to own file
  src/CMakeLists.txt
  src/theory/quantifiers/quantifiers_modules.cpp
  src/theory/quantifiers/quantifiers_modules.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
  src/theory/theory_engine.cpp
Labels: moderate, normal

#5066 Rename system tests to api tests and remove obsolete Java test.
  src/main/CMakeLists.txt
  test/CMakeLists.txt
  test/api/CMakeLists.txt
  test/api/boilerplate.cpp
  test/api/interactive_shell.py
  test/api/ouroborous.cpp
  test/api/reset_assertions.cpp
  test/api/sep_log_api.cpp
  test/api/smt2_compliance.cpp
  test/api/statistics.cpp
  test/api/two_solvers.cpp
  test/system/CMakeLists.txt
  test/system/CVC4JavaTest.java
Labels: major, simple

#5045 Move sets member propagation to SolverState
  src/theory/sets/solver_state.cpp
  src/theory/sets/solver_state.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
Labels: moderate, normal

#5059 (proof-new) Make proofs mandatory in proof equality engine
  src/theory/uf/proof_equality_engine.cpp
  src/theory/uf/proof_equality_engine.h
Labels: moderate, normal

#5069 [proof-new] A simple proof generator for buffered proof steps
  src/expr/CMakeLists.txt
  src/expr/buffered_proof_generator.cpp
  src/expr/buffered_proof_generator.h
  src/theory/uf/proof_equality_engine.cpp
  src/theory/uf/proof_equality_engine.h
Labels: normal, simple

#5070 [proof-new] Resolution rules and checkers
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/booleans/proof_checker.cpp
Labels: moderate, normal

#5071 [proof-new] Extending EqProof conversion to HO congruence
  src/theory/uf/eq_proof.cpp
Labels: moderate, normal

#5068 bv2int: support models in tests
  src/preprocessing/passes/bv_to_int.cpp
  src/preprocessing/passes/bv_to_int.h
  test/regress/regress0/bv/bv_to_int1.smt2
  test/regress/regress0/bv/bv_to_int2.smt2
  test/regress/regress0/bv/bv_to_int_bitwise.smt2
  test/regress/regress0/bv/bv_to_int_bvmul1.smt2
  test/regress/regress0/bv/bv_to_int_bvmul2.smt2
  test/regress/regress0/bv/bv_to_int_bvuf_to_intuf.smt2
  test/regress/regress0/bv/bv_to_int_bvuf_to_intuf_sorts.smt2
  test/regress/regress0/bv/bv_to_int_elim_err.smt2
  test/regress/regress0/bv/bv_to_int_zext.smt2
  test/regress/regress2/bv_to_int_ashr.smt2
  test/regress/regress2/bv_to_int_mask_array_1.smt2
  test/regress/regress2/bv_to_int_mask_array_2.smt2
  test/regress/regress2/bv_to_int_mask_array_3.smt2
  test/regress/regress2/bv_to_int_shifts.smt2
  test/regress/regress3/bv_to_int_and_or.smt2
Labels: refactor

#5027 Refactor collectModelInfo in TheoryArith
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
Labels: moderate, normal

#5060 [proof-new] Adds Lazy CDProof chain data-structure
  src/expr/CMakeLists.txt
  src/expr/lazy_proof_chain.cpp
  src/expr/lazy_proof_chain.h
  src/expr/proof_node_algorithm.cpp
  src/expr/proof_node_algorithm.h
  src/expr/proof_node_manager.cpp
Labels: do not merge, moderate, normal

#5038 Add buffered inference manager to TheorySep
  src/theory/sep/theory_sep.cpp
  src/theory/sep/theory_sep.h
Labels: moderate, normal

#5040 Dump commands in internal code using command printing functions.
  src/CMakeLists.txt
  src/main/command_executor.h
  src/main/main.cpp
  src/parser/antlr_input.cpp
  src/parser/cvc/cvc.cpp
  src/parser/cvc/cvc.h
  src/parser/input.cpp
  src/parser/smt2/smt2.h
  src/parser/tptp/tptp.cpp
  src/parser/tptp/tptp.h
  src/preprocessing/preprocessing_pass.cpp
  src/printer/ast/ast_printer.cpp
  src/printer/cvc/cvc_printer.cpp
  src/printer/smt2/smt2_printer.cpp
  src/proof/unsat_core.cpp
  src/prop/cnf_stream.cpp
  src/prop/cnf_stream.h
  src/prop/minisat/core/Solver.cc
  src/prop/minisat/core/Solver.h
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
  src/smt/command.cpp
  src/smt/dump.cpp
  src/smt/dump.h
  src/smt/dump_manager.cpp
  src/smt/dump_manager.h
  src/smt/listeners.cpp
  src/smt/listeners.h
  src/smt/output_manager.cpp
  src/smt/output_manager.h
  src/smt/preprocessor.cpp
  src/smt/process_assertions.cpp
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/smt/smt_solver.cpp
  src/smt/sygus_solver.cpp
  src/smt/sygus_solver.h
  src/smt/term_formula_removal.h
  src/theory/arrays/theory_arrays.cpp
  src/theory/bv/abstraction.cpp
  src/theory/bv/bitblast/eager_bitblaster.cpp
  src/theory/bv/bitblast/lazy_bitblaster.cpp
  src/theory/bv/bv_subtheory_algebraic.cpp
  src/theory/bv/theory_bv_rewrite_rules.h
  src/theory/quantifiers/skolemize.h
  src/theory/quantifiers/sygus/ce_guided_single_inv_sol.cpp
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  test/unit/parser/parser_builder_black.h
  test/unit/prop/cnf_stream_white.h
Labels: moderate, normal

#5075 Only rewrite replace_re(_all) if regexp is const
  src/theory/strings/sequences_rewriter.cpp
  test/api/CMakeLists.txt
  test/api/issue5074.cpp
Labels: normal, simple

#5077 Dumping internal define-funs with no arguments
  src/smt/node_command.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/print_define_fun_internal.smt2
Labels: bug, minor, simple

#5076 Further standardization of datatypes
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
Labels: moderate, normal

#4784 Do not allow to build Python bindings if building statically
  CMakeLists.txt
Labels: normal, simple

#5022 Use new inference manager in transcendental solver
  src/theory/arith/inference_manager.cpp
  src/theory/arith/inference_manager.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/transcendental_solver.cpp
  src/theory/arith/nl/transcendental_solver.h
Labels: moderate

#5052 Reduce recursion in term formula removal
  src/smt/term_formula_removal.cpp
  src/smt/term_formula_removal.h
  test/api/CMakeLists.txt
  test/api/issue4889.cpp
  test/regress/regress0/arith/issue3480.smt2
Labels: moderate, normal

#5085 (cad-solver) Fix square-free-basis computation
  src/theory/arith/nl/cad/cdcac.cpp
  src/theory/arith/nl/cad/cdcac_utils.cpp
  src/theory/arith/nl/cad/cdcac_utils.h
  src/theory/arith/nl/cad/projections.cpp
  src/theory/arith/nl/cad/projections.h
Labels: moderate

#5086 [proof-new] Have mkScope agnostic to True assumptions
  src/expr/proof_node_manager.cpp
  src/expr/proof_node_manager.h
Labels: do not merge, normal, simple

#5087 (proof-new) Fixes for theory engine proof generator
  src/theory/theory_engine_proof_generator.cpp
  src/theory/theory_engine_proof_generator.h
Labels: minor, simple

#5072 (proof-new) Rewrites involving operators in term conversion proof generator
  src/expr/term_context.cpp
  src/expr/term_context.h
  src/expr/term_context_stack.cpp
  src/expr/term_context_stack.h
  src/expr/term_conversion_proof_generator.cpp
  src/expr/term_conversion_proof_generator.h
  src/smt/witness_form.cpp
Labels: moderate, normal

#5088 (proof-new) Updates to proof node updater algorithm
  src/expr/proof_node_updater.cpp
  src/expr/proof_node_updater.h
  src/smt/proof_post_processor.cpp
  src/smt/proof_post_processor.h
Labels: minor, moderate

#5092 [Strings] Fix extended equality rewriter
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/strings_entail.cpp
  src/theory/strings/strings_entail.h
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/issue5090.smt2
Labels: major, moderate

#5073 Logic exception for arrays indexed by arrays
  src/theory/arrays/theory_arrays.cpp
Labels: moderate, normal

#5089 [proof-new] Proof utilities for normalizing clauses at the Node level
  src/theory/theory_proof_step_buffer.cpp
  src/theory/theory_proof_step_buffer.h
Labels: moderate, normal

#5093 Fix muzzled builds
  src/smt/dump.cpp
  src/smt/dump.h
Labels: major, simple

#5080 bv2int: quantifiers support
  src/preprocessing/passes/bv_to_int.cpp
  src/preprocessing/passes/bv_to_int.h
  test/regress/CMakeLists.txt
  test/regress/regress3/bv_to_int_check_bvsge_bvashr0_4bit.smt2.minimized.smt2
  test/regress/regress3/bv_to_int_check_ne_bvlshr0_4bit.smt2.minimized.smt2
  test/regress/regress3/bv_to_int_input_mouser_detect.c.smt2.minimized.smt2
Labels: feature

#4982 Add the shared solver
  src/CMakeLists.txt
  src/theory/shared_solver.cpp
  src/theory/shared_solver.h
  src/theory/shared_solver_distributed.cpp
  src/theory/shared_solver_distributed.h
  src/theory/shared_terms_database.cpp
  src/theory/shared_terms_database.h
  src/theory/theory_engine.h
Labels: moderate, normal

#5084 Fix assertion list for globally defined recursive functions
  src/smt/assertions.cpp
Labels: minor, simple

#5098 Standardize equality engine notifications in sets
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
Labels: minor, simple

#4976 More flexible design for model manager distributed
  src/theory/combination_engine.cpp
  src/theory/ee_manager.cpp
  src/theory/ee_manager.h
  src/theory/ee_manager_distributed.cpp
  src/theory/ee_manager_distributed.h
  src/theory/model_manager.cpp
  src/theory/model_manager.h
  src/theory/model_manager_distributed.cpp
  src/theory/model_manager_distributed.h
  src/theory/theory_model.cpp
  src/theory/theory_model.h
Labels: moderate, normal

#5047 (proof-new) Add the arrays proof checker
  src/CMakeLists.txt
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/arrays/proof_checker.cpp
  src/theory/arrays/proof_checker.h
  src/theory/arrays/skolem_cache.cpp
  src/theory/arrays/skolem_cache.h
  src/theory/arrays/theory_arrays.cpp
  src/theory/arrays/theory_arrays.h
Labels: moderate, normal

#5017 ICP-based solver for nonlinear arithmetic
  src/CMakeLists.txt
  src/options/arith_options.toml
  src/theory/arith/inference_id.h
  src/theory/arith/nl/icp/candidate.cpp
  src/theory/arith/nl/icp/candidate.h
  src/theory/arith/nl/icp/contraction_origins.cpp
  src/theory/arith/nl/icp/contraction_origins.h
  src/theory/arith/nl/icp/icp_solver.cpp
  src/theory/arith/nl/icp/icp_solver.h
  src/theory/arith/nl/icp/intersection.cpp
  src/theory/arith/nl/icp/intersection.h
  src/theory/arith/nl/icp/interval.h
  src/theory/arith/nl/icp/variable_bounds.cpp
  src/theory/arith/nl/icp/variable_bounds.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/nl/poly_conversion.cpp
  src/theory/arith/nl/poly_conversion.h
  src/theory/arith/normal_form.cpp
  src/theory/arith/normal_form.h
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
Labels: moderate

#5083 Add method to get Python object from constant value term in Python API
  src/api/python/cvc4.pxi
  test/unit/api/python/test_to_python_obj.py
Labels: simple

#5118 Fix compilation without LibPoly
  .github/workflows/ci.yml
  src/theory/arith/nl/icp/icp_solver.cpp
  src/theory/arith/nl/icp/icp_solver.h
Labels: major, simple

#5100 Add skeleton for theory of bags (multisets)
  src/CMakeLists.txt
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/api/cvc4cppkind.h
  src/expr/CMakeLists.txt
  src/expr/emptybag.cpp
  src/expr/emptybag.h
  src/expr/node_manager.cpp
  src/expr/node_manager.h
  src/expr/type_node.cpp
  src/expr/type_node.h
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/smt/set_defaults.cpp
  src/theory/bags/inference_manager.cpp
  src/theory/bags/inference_manager.h
  src/theory/bags/kinds
  src/theory/bags/normal_form.cpp
  src/theory/bags/normal_form.h
  src/theory/bags/solver_state.cpp
  src/theory/bags/solver_state.h
  src/theory/bags/term_registry.cpp
  src/theory/bags/term_registry.h
  src/theory/bags/theory_bags.cpp
  src/theory/bags/theory_bags.h
  src/theory/bags/theory_bags_rewriter.cpp
  src/theory/bags/theory_bags_rewriter.h
  src/theory/bags/theory_bags_type_enumerator.cpp
  src/theory/bags/theory_bags_type_enumerator.h
  src/theory/bags/theory_bags_type_rules.h
  src/theory/logic_info.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_id.cpp
  src/theory/theory_id.h
  test/unit/api/solver_black.h
  test/unit/api/sort_black.h
  test/unit/theory/CMakeLists.txt
  test/unit/theory/logic_info_white.h
  test/unit/theory/theory_bags_type_rules_black.h
Labels: do not merge, moderate, normal

#5119 FP: Use Assert instead of PRECONDITION macro in converter.
  src/theory/fp/fp_converter.cpp
Labels: major, simple

#5120 [Python API] Conversion to/from Unicode strings
  src/api/python/cvc4.pxi
  src/util/string.cpp
  test/unit/api/python/test_to_python_obj.py
Labels: moderate, normal

#5107 Fix type issue with term formula removal
  src/smt/term_formula_removal.h
Labels: minor, simple

#5105 Refactor Commands to use the Public API.
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/main/command_executor.cpp
  src/main/command_executor.h
  src/main/driver_unified.cpp
  src/main/interactive_shell.cpp
  src/parser/cvc/Cvc.g
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/tptp/Tptp.g
  src/parser/tptp/tptp.cpp
  src/smt/command.cpp
  src/smt/command.h
  src/smt/smt_engine.h
  test/api/smt2_compliance.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/smtlib/get-unsat-assumptions.smt2
Labels: moderate, normal

#5121 FP: Use Assert instead of AlwaysAssert in traits::(pre|post)condition.
  src/theory/fp/fp_converter.cpp
  src/util/floatingpoint.cpp
Labels: normal, simple

#5122 New C++ API: Catch and throw recoverable exception.
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  test/unit/api/solver_black.h
Labels: normal, simple

#5117 Allow E-matching by default when strings are enabled
  src/smt/set_defaults.cpp
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  src/theory/quantifiers/ematching/instantiation_engine.h
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers/quantifiers_attributes.h
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/theory_strings_preprocess.h
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/seq-solved-enum.smt2
  test/regress/regress1/quantifiers/seq-unsolved-ematch.smt2
Labels: moderate, normal

#5126 Make IAND solver use inference manager.
  src/theory/arith/nl/iand_solver.cpp
  src/theory/arith/nl/iand_solver.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/theory_arith.cpp
Labels: moderate, normal

#5124 Disable cegqi-bv when using sygus
  src/smt/set_defaults.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/find_inv_eq_bvmul_4bit_withoutgrammar-v2.sy
  test/regress/regress1/sygus/max2-bv.sy
Labels: normal, simple

#5115 Modify lemma vs fact policy for datatype equalities
  src/expr/dtype_cons.cpp
  src/expr/dtype_cons.h
  src/theory/datatypes/inference_manager.cpp
  src/theory/datatypes/inference_manager.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/inference_manager_buffered.cpp
  src/theory/inference_manager_buffered.h
  test/regress/CMakeLists.txt
  test/regress/regress0/datatypes/dt-different-params.smt2
  test/regress/regress0/datatypes/list-bool.smt2
Labels: moderate, normal

#5064 Function definition fmf preprocessing pass
  src/CMakeLists.txt
  src/preprocessing/passes/fun_def_fmf.cpp
  src/preprocessing/passes/fun_def_fmf.h
  src/preprocessing/preprocessing_pass_registry.cpp
  src/smt/process_assertions.cpp
  src/smt/process_assertions.h
  src/theory/quantifiers/fmf/model_builder.cpp
  src/theory/quantifiers/fun_def_process.cpp
  src/theory/quantifiers/fun_def_process.h
  src/theory/quantifiers/quantifiers_attributes.h
Labels: moderate, normal

#5133 SyGuS: Add default grammar for FP.
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.h
  src/theory/theory_model_builder.cpp
Labels: normal, simple

#5134 Cleaning and documenting cnf stream
  src/prop/cnf_stream.cpp
  src/prop/cnf_stream.h
  src/prop/prop_engine.cpp
  src/theory/bv/bitblast/eager_bitblaster.cpp
  src/theory/bv/bitblast/lazy_bitblaster.cpp
  test/unit/prop/cnf_stream_white.h
Labels: moderate, normal

#5102 Make sygus refinement step more robust to unevaluatable counterexamples
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/synth_engine.cpp
Labels: moderate, normal

#5138 Restrict bvxnor to only allow two operands (was n-ary).
  NEWS
  src/api/cvc4cpp.cpp
  test/regress/regress0/parser/bv_arity_smt2.6.smt2
Labels: major, simple

#5129 Use original quantified formula for single invocation reconstruction
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/ground-ite-free-constant-si.sy
Labels: normal, simple

#5103 Connect the shared solver to theory engine
  src/theory/combination_engine.cpp
  src/theory/combination_engine.h
  src/theory/ee_manager.cpp
  src/theory/ee_manager.h
  src/theory/ee_manager_distributed.cpp
  src/theory/ee_manager_distributed.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: moderate, normal

#5125 Use inference manager for nl_solver
  src/theory/arith/inference_manager.cpp
  src/theory/arith/inference_manager.h
  src/theory/arith/nl/nl_solver.cpp
  src/theory/arith/nl/nl_solver.h
  src/theory/arith/nl/nonlinear_extension.cpp
Labels: moderate, normal

#5130 Fix sygus quantifier elimination preprocess for multiple functions
  src/theory/quantifiers/sygus/synth_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/replicate-mod.sy
Labels: normal, simple

#5132 Implement bags rewriter
  src/CMakeLists.txt
  src/theory/bags/bags_rewriter.cpp
  src/theory/bags/bags_rewriter.h
  src/theory/bags/bags_statistics.cpp
  src/theory/bags/bags_statistics.h
  src/theory/bags/kinds
  src/theory/bags/normal_form.cpp
  src/theory/bags/normal_form.h
  src/theory/bags/rewrites.cpp
  src/theory/bags/rewrites.h
  src/theory/bags/theory_bags.cpp
  src/theory/bags/theory_bags.h
  src/theory/bags/theory_bags_rewriter.h
  src/theory/bags/theory_bags_type_enumerator.h
  src/theory/bags/theory_bags_type_rules.h
  test/unit/theory/CMakeLists.txt
  test/unit/theory/theory_bags_rewriter_black.h
Labels: moderate, normal

#5140 [proof-new] Adds a proof manager for the SAT solver
  src/CMakeLists.txt
  src/expr/lazy_proof_chain.cpp
  src/expr/lazy_proof_chain.h
  src/prop/minisat/core/Solver.h
  src/prop/sat_proof_manager.cpp
  src/prop/sat_proof_manager.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
Labels: complex, normal

#5151 (proof-new) Minor updates to quantifiers proofs
  src/expr/proof_rule.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/proof_checker.cpp
Labels: minor, simple

#5142 Disable regression that is timing out
  test/regress/CMakeLists.txt
Labels: major, simple

#5154 [proof-new] Adds a proof node hash function
  src/expr/proof_node.h
Labels: normal, simple

#5155 Removing spurious forward declaration in CnfStream
  src/prop/cnf_stream.h
Labels: minor, simple

#5157 Add utilities for arith/proof_checker and build it
  src/CMakeLists.txt
  src/theory/arith/arith_utilities.cpp
  src/theory/arith/arith_utilities.h
Labels: minor, simple

#5153 Reset assertions on resetAssertions
  src/smt/smt_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/issue5144-resetAssertions.smt2
Labels: normal, simple

#5149 Clean up nonlinear extension
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
Labels: moderate, normal

#5137 [proof-new] Adds a proof-producing CNF converter
  src/CMakeLists.txt
  src/prop/cnf_stream.h
  src/prop/proof_cnf_stream.cpp
  src/prop/proof_cnf_stream.h
Labels: moderate, normal

#5156 [proof-new] Updates to proof node updater
  src/expr/proof_node_updater.cpp
  src/expr/proof_node_updater.h
  src/smt/proof_post_processor.cpp
  src/smt/proof_post_processor.h
Labels: normal, simple

#5161 [proof-new] Adds a proof post processor for the Prop Engine
  src/CMakeLists.txt
  src/prop/proof_post_processor.cpp
  src/prop/proof_post_processor.h
Labels: moderate, normal

#5136 (proof-new) Fixes for preprocess proof generator and proofs in assertion pipeline
  src/preprocessing/assertion_pipeline.cpp
  src/preprocessing/assertion_pipeline.h
  src/smt/preprocess_proof_generator.cpp
  src/smt/preprocess_proof_generator.h
  src/smt/proof_manager.cpp
  src/smt/proof_manager.h
  src/smt/smt_engine.cpp
  src/theory/trust_node.cpp
  src/theory/trust_node.h
Labels: moderate, normal

#5159 (proof-new) Add proof managers and eager gens to arith
  src/theory/arith/congruence_manager.cpp
  src/theory/arith/congruence_manager.h
  src/theory/arith/constraint.cpp
  src/theory/arith/constraint.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
Labels: minor, simple

#5165 Fix bags headers
  src/theory/bags/bags_rewriter.cpp
  src/theory/bags/bags_rewriter.h
Labels: minor, simple

#5162 [proof-new] Adds a proof manager for prop engine
  src/CMakeLists.txt
  src/prop/prop_proof_manager.cpp
  src/prop/prop_proof_manager.h
Labels: normal, simple

#5097 (proof-new) Add the term conversion sequence generator
  src/expr/CMakeLists.txt
  src/expr/proof_node_manager.cpp
  src/expr/proof_node_manager.h
  src/expr/tconv_seq_proof_generator.cpp
  src/expr/tconv_seq_proof_generator.h
Labels: moderate, normal

#5152 Dynamic allocation of equality engine for shared solver
  src/theory/ee_manager_distributed.cpp
  src/theory/ee_manager_distributed.h
  src/theory/shared_solver_distributed.cpp
  src/theory/shared_terms_database.cpp
  src/theory/shared_terms_database.h
Labels: moderate, normal

#5160 Add strategy for nonlinear extension
  src/CMakeLists.txt
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/nl/strategy.cpp
  src/theory/arith/nl/strategy.h
Labels: do not merge, moderate, normal

#5170 Add missing includes.
  src/theory/arith/nl/strategy.cpp
  src/theory/arith/nl/strategy.h
Labels: major, simple

#5168 Remove too strict assertion to allow for approximate models
  src/smt/smt_engine.cpp
  src/theory/arith/theory_arith.cpp
Labels: normal, simple

#5166 FloatingPoint: Add utility functions for largest and smallest subnormal.
  src/util/bitvector.cpp
  src/util/bitvector.h
  src/util/floatingpoint.cpp
  src/util/floatingpoint.h.in
  test/unit/util/CMakeLists.txt
  test/unit/util/floatingpoint_black.h
Labels: major, simple
