Repository cvc5/cvc5, pull requests merged in 2020-04, with the labels that each got.

#4196 Fix install for ANTLR contrib script.
  .github/workflows/ci.yml
  contrib/get-antlr-3.4
Labels: major, simple

#4188 Support char smt-lib syntax
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/parser/smt2/Smt2.g
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/char-representations.smt2
  test/regress/regress0/strings/unicode-esc.smt2
  test/unit/api/solver_black.h
Labels: moderate, normal

#4197 Initialize theory rewriters in theories
  src/preprocessing/passes/bv_gauss.cpp
  src/preprocessing/passes/bv_gauss.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/arrays/theory_arrays.cpp
  src/theory/arrays/theory_arrays.h
  src/theory/booleans/theory_bool.cpp
  src/theory/booleans/theory_bool.h
  src/theory/builtin/theory_builtin.cpp
  src/theory/builtin/theory_builtin.h
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp.h
  src/theory/mkrewriter
  src/theory/quantifiers/theory_quantifiers.cpp
  src/theory/quantifiers/theory_quantifiers.h
  src/theory/rewriter.cpp
  src/theory/rewriter.h
  src/theory/rewriter_tables_template.h
  src/theory/sep/theory_sep.cpp
  src/theory/sep/theory_sep.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf.h
  test/unit/preprocessing/pass_bv_gauss_white.h
  test/unit/theory/evaluator_white.h
  test/unit/theory/regexp_operation_black.h
  test/unit/theory/sequences_rewriter_white.h
  test/unit/theory/theory_black.h
  test/unit/theory/theory_bv_rewriter_white.h
  test/unit/theory/theory_engine_white.h
  test/unit/theory/theory_quantifiers_bv_instantiator_white.h
  test/unit/theory/theory_sets_type_enumerator_white.h
  test/unit/theory/theory_strings_skolem_cache_black.h
  test/unit/theory/theory_white.h
  test/unit/theory/type_enumerator_white.h
Labels: moderate, normal

#4195 Introduce enums for all string inferences, excluding the core solver
  src/theory/strings/base_solver.cpp
  src/theory/strings/extf_solver.cpp
  src/theory/strings/extf_solver.h
  src/theory/strings/infer_info.cpp
  src/theory/strings/infer_info.h
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/regexp_solver.cpp
  src/theory/strings/regexp_solver.h
  src/theory/strings/sequences_stats.cpp
  src/theory/strings/sequences_stats.h
  src/theory/strings/theory_strings.cpp
Labels: moderate, normal

#4177 Remove undocumented/uncommon aliases
  src/options/base_options.toml
  src/options/expr_options.toml
  src/options/main_options.toml
  src/options/parser_options.toml
  src/options/smt_options.toml
  test/unit/expr/expr_public.h
  test/unit/expr/node_black.h
Labels: normal, simple

#4194 Split sequences rewriter
  src/CMakeLists.txt
  src/theory/strings/arith_entail.cpp
  src/theory/strings/arith_entail.h
  src/theory/strings/core_solver.cpp
  src/theory/strings/regexp_elim.cpp
  src/theory/strings/regexp_entail.cpp
  src/theory/strings/regexp_entail.h
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/regexp_operation.h
  src/theory/strings/regexp_solver.cpp
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/sequences_rewriter.h
  src/theory/strings/skolem_cache.cpp
  src/theory/strings/strings_entail.cpp
  src/theory/strings/strings_entail.h
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/theory_strings_utils.cpp
  src/theory/strings/theory_strings_utils.h
  src/theory/strings/word.cpp
  src/theory/strings/word.h
  test/unit/theory/sequences_rewriter_white.h
Labels: moderate, normal

#4203 Only rewrite lambdas via array representations when constant
  src/theory/builtin/theory_builtin_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress3/issue4170.smt2
Labels: normal, simple

#4202 Update theory rewriter ownership, add stats to strings
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/arith/theory_arith_private.h
  src/theory/arrays/theory_arrays.cpp
  src/theory/arrays/theory_arrays.h
  src/theory/booleans/theory_bool.cpp
  src/theory/booleans/theory_bool.h
  src/theory/builtin/theory_builtin.cpp
  src/theory/builtin/theory_builtin.h
  src/theory/builtin/theory_builtin_rewriter.cpp
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp.h
  src/theory/quantifiers/candidate_rewrite_database.cpp
  src/theory/quantifiers/candidate_rewrite_database.h
  src/theory/quantifiers/extended_rewrite.cpp
  src/theory/quantifiers/theory_quantifiers.cpp
  src/theory/quantifiers/theory_quantifiers.h
  src/theory/rewriter.cpp
  src/theory/rewriter.h
  src/theory/sep/theory_sep.cpp
  src/theory/sep/theory_sep.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
  src/theory/sets/theory_sets_private.h
  src/theory/strings/arith_entail.cpp
  src/theory/strings/extf_solver.cpp
  src/theory/strings/extf_solver.h
  src/theory/strings/regexp_entail.cpp
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/sequences_rewriter.h
  src/theory/strings/sequences_stats.cpp
  src/theory/strings/sequences_stats.h
  src/theory/strings/strings_entail.cpp
  src/theory/strings/strings_entail.h
  src/theory/strings/strings_rewriter.cpp
  src/theory/strings/strings_rewriter.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/theory.cpp
  src/theory/theory.h
  src/theory/theory_engine.h
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf.h
  test/unit/theory/sequences_rewriter_white.h
  test/unit/theory/theory_engine_white.h
  test/unit/theory/theory_white.h
Labels: do not merge, moderate, normal

#4208 New C++ API: Remove Op::getSort().
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/api/python/cvc4.pxi
  src/parser/smt2/Smt2.g
  test/unit/api/op_black.h
Labels: normal, simple

#4205 Type-independent preregistration of empty word
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: normal, simple

#4213 Add safe_print() support for Kind enum
  src/expr/kind_template.cpp
  src/expr/kind_template.h
  src/expr/mkkind
  test/unit/expr/kind_black.h
Labels: normal, simple

#4214 Add missing stat for lemmas based on inferences
  src/theory/strings/inference_manager.cpp
Labels: normal, simple

#4209 Refactor disequality processing in string solver
  src/theory/strings/core_solver.cpp
  src/theory/strings/core_solver.h
  src/theory/strings/infer_info.cpp
  src/theory/strings/infer_info.h
  src/theory/strings/inference_manager.cpp
  src/theory/strings/inference_manager.h
Labels: moderate, normal

#4201 Remove links field in all toml files
  contrib/cvc4_strict_smtlib
  src/options/base_options.toml
  src/options/bv_options.toml
  src/options/options_public_functions.cpp
  src/options/smt_options.toml
  src/smt/set_defaults.cpp
  src/smt/smt_engine.cpp
Labels: moderate, normal

#4220 Enum for all remaining string inferences
  src/theory/strings/base_solver.cpp
  src/theory/strings/core_solver.cpp
  src/theory/strings/extf_solver.cpp
  src/theory/strings/infer_info.cpp
  src/theory/strings/infer_info.h
  src/theory/strings/inference_manager.cpp
  src/theory/strings/inference_manager.h
  src/theory/strings/theory_strings.cpp
Labels: moderate, normal

#4221 Disable slow regression
  test/regress/CMakeLists.txt
Labels: major, simple

#4215 Cleanup deprecated quantifiers attribute features
  src/printer/smt2/smt2_printer.cpp
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers/quantifiers_attributes.h
  src/theory/quantifiers/theory_quantifiers.cpp
Labels: minor, simple

#4227 Eliminate call to currentNM within NodeManager
  src/expr/node_manager.cpp
  src/expr/node_manager.h
Labels: minor, simple

#4230 Fix dump models and dump proofs
  src/main/command_executor.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/simple-dump-model.smt2
Labels: normal, simple

#4044 Perform theory widening eagerly
  src/smt/set_defaults.cpp
  src/smt/smt_engine.cpp
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  src/theory/theory.h
  src/theory/theory_engine.h
  src/theory/theory_id.cpp
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf.h
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/issue3971.smt2
  test/regress/regress0/nl/issue3991.smt2
Labels: moderate, normal

#4211 Added CHOOSE operator for sets
  src/api/cvc4cpp.cpp
  src/api/cvc4cppkind.h
  src/parser/cvc/Cvc.g
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/sets/kinds
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
  src/theory/sets/theory_sets_type_rules.h
  test/regress/CMakeLists.txt
  test/regress/regress1/fmf/agree466.smt2
  test/regress/regress1/fmf/agree467.smt2
  test/regress/regress1/sets/choose.cvc
  test/regress/regress1/sets/choose1.smt2
  test/regress/regress1/sets/choose2.smt2
  test/regress/regress1/sets/choose3.smt2
  test/regress/regress1/sets/choose4.smt2
Labels: normal, simple

#4210 Split ProcessAssertions module from SmtEngine
  src/CMakeLists.txt
  src/options/arith_options.toml
  src/smt/defined_function.h
  src/smt/process_assertions.cpp
  src/smt/process_assertions.h
  src/smt/set_defaults.cpp
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/smt/smt_engine_stats.cpp
  src/smt/smt_engine_stats.h
Labels: moderate, normal

#4232 Disable slow sygus regression
  test/regress/CMakeLists.txt
Labels: major, simple

#4233 Towards proper use of resource managers
  src/decision/decision_engine.cpp
  src/decision/decision_engine.h
  src/preprocessing/passes/bool_to_bv.cpp
  src/preprocessing/passes/bv_to_bool.cpp
  src/prop/cnf_stream.cpp
  src/prop/cnf_stream.h
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/smt/smt_engine.cpp
  src/theory/bv/bitblast/eager_bitblaster.cpp
  src/theory/bv/bitblast/lazy_bitblaster.cpp
  test/unit/prop/cnf_stream_white.h
Labels: normal, simple

#4252 Add a few stats to strings
  src/theory/strings/sequences_stats.cpp
  src/theory/strings/sequences_stats.h
  src/theory/strings/theory_strings.cpp
Labels: normal, simple

#4257 Explain non-emptiness by non-zero length in strings
  src/theory/strings/core_solver.cpp
  src/theory/strings/solver_state.cpp
  src/theory/strings/solver_state.h
Labels: moderate, normal

#4219 Split the non-linear solver
  src/CMakeLists.txt
  src/theory/arith/nl_constraint.cpp
  src/theory/arith/nl_constraint.h
  src/theory/arith/nl_lemma_utils.h
  src/theory/arith/nl_monomial.cpp
  src/theory/arith/nl_monomial.h
  src/theory/arith/nl_solver.cpp
  src/theory/arith/nl_solver.h
  src/theory/arith/nonlinear_extension.cpp
  src/theory/arith/nonlinear_extension.h
  src/theory/arith/transcendental_solver.h
Labels: minor, moderate

#4270 Ensure exported sygus solutions match grammar
  src/expr/dtype_cons.h
  src/theory/datatypes/theory_datatypes_utils.cpp
  src/theory/datatypes/theory_datatypes_utils.h
  src/theory/quantifiers/sygus/sygus_grammar_norm.cpp
  src/theory/quantifiers/sygus/sygus_grammar_norm.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/yoni-true-sol.smt2
Labels: moderate, normal

#4222 Add skip predicate to node traversal.
  src/expr/node_traversal.cpp
  src/expr/node_traversal.h
  test/unit/expr/node_traversal_black.h
Labels: minor, simple

#4276 Move slow nl regression to regress3
  test/regress/CMakeLists.txt
  test/regress/regress3/siegel-nl-bases.smt2
Labels: major, simple

#4278 Fixes for extended rewriter
  src/expr/node.h
  src/theory/quantifiers/extended_rewrite.cpp
  src/theory/quantifiers/extended_rewrite.h
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/issue4273-ext-rew-cache.smt2
Labels: normal, simple

#4256 Fix SyGuS define-fun printing from benchmarks coming from v1 parser
  src/parser/smt2/smt2.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/sygus/print-define-fun.sy
Labels: major, simple

#4303 Fix dump-unsat-cores-full
  src/options/options_public_functions.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/dump-unsat-core-full.smt2
Labels: normal, simple

#4305 Remove mergePredicates from EqualityEngine interface
  src/theory/theory_model.cpp
  src/theory/uf/equality_engine.cpp
  src/theory/uf/equality_engine.h
Labels: minor, simple

#4223 Remove argument extender
  src/CMakeLists.txt
  src/options/CMakeLists.txt
  src/options/argument_extender.h
  src/options/argument_extender_implementation.cpp
  src/options/argument_extender_implementation.h
  src/options/options.h
  src/options/options_template.cpp
Labels: normal, simple

#4234 Remove early type check option
  src/expr/node_builder.h
  src/expr/node_manager.cpp
  src/options/expr_options.toml
Labels: minor, simple

#4294 Remove a few spurious assertions
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/sygus/sygus_process_conj.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue4290-cegqi-r.smt2
Labels: minor, simple

#4295 Remove a few options
  src/options/quantifiers_options.toml
  src/options/strings_options.toml
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/quantifiers/fmf/model_builder.cpp
  src/theory/strings/inference_manager.cpp
Labels: minor, simple

#4235 Fix relevant domain computation for nested quantifiers coming from CEGQI
  src/theory/quantifiers/inst_strategy_enumerative.cpp
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/instantiate.h
  src/theory/quantifiers/relevant_domain.cpp
  src/theory/quantifiers/term_util.cpp
  src/theory/quantifiers/term_util.h
Labels: minor, simple

#4266 Disable macros when higher-order
  src/smt/set_defaults.cpp
Labels: minor, simple

#4251 Disable preregistration of instantiations for cegqi in incremental
  src/smt/set_defaults.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue4243-prereg-inc.smt2
Labels: minor, simple

#4271 Fix combinations of cegqi and non-standard triggers
  src/theory/quantifiers/ematching/inst_match_generator.cpp
  src/theory/quantifiers/ematching/inst_match_generator.h
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/inst_match.cpp
  src/theory/quantifiers/inst_match.h
Labels: minor, simple

#4279 Always assign function values in higher order
  src/smt/set_defaults.cpp
  src/theory/theory_model.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/fp/issue4277-assign-func.smt2
Labels: minor, simple

#4280 Do not normalize to representatives for variable equalities in conflict-based instantiation
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/quant_conflict_find.h
  test/regress/CMakeLists.txt
  test/regress/regress0/quantifiers/issue4275-qcf-cegqi-rep.smt2
Labels: normal, simple

#4297 Always flush lemmas from downwards closure in sets
  src/theory/sets/inference_manager.cpp
  src/theory/sets/theory_sets_private.cpp
Labels: minor, simple

#4298 Abort if in conflict in enumerative instantiation
  src/theory/quantifiers/inst_strategy_enumerative.cpp
  src/theory/quantifiers_engine.cpp
Labels: minor, simple

#4206 Convert more cases of strings to words
  src/theory/quantifiers/sygus/sygus_unif.cpp
  src/theory/quantifiers/sygus/sygus_unif.h
  src/theory/quantifiers/sygus/sygus_unif_io.cpp
  src/theory/quantifiers/sygus/sygus_unif_io.h
  src/theory/strings/inference_manager.cpp
  src/theory/strings/inference_manager.h
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/regexp_solver.cpp
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/strings_entail.cpp
  src/theory/strings/strings_rewriter.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/word.cpp
  src/theory/strings/word.h
  src/theory/subs_minimize.cpp
  src/util/string.h
Labels: moderate, normal

#4313 Fix assertion in enumerative instantiation
  src/theory/quantifiers/inst_strategy_enumerative.cpp
Labels: major, simple

#4306 Do not mark string extended functions as eliminated after reduction lemmas
  src/theory/strings/extf_solver.cpp
  src/theory/strings/extf_solver.h
Labels: normal, simple

#4312 Split TermRegistry object from TheoryStrings
  src/CMakeLists.txt
  src/theory/strings/core_solver.cpp
  src/theory/strings/core_solver.h
  src/theory/strings/extf_solver.cpp
  src/theory/strings/extf_solver.h
  src/theory/strings/inference_manager.cpp
  src/theory/strings/inference_manager.h
  src/theory/strings/strings_fmf.cpp
  src/theory/strings/strings_fmf.h
  src/theory/strings/term_registry.cpp
  src/theory/strings/term_registry.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: major, moderate

#4309 Change option names --default-dag-thresh and --default-expr-depth
  contrib/cvc4_strict_smtlib
  examples/api/combination-new.cpp
  examples/api/combination.cpp
  examples/api/java/Combination.java
  examples/api/python/combination.py
  examples/translator.cpp
  src/options/README
  src/options/expr_options.toml
  src/options/options_handler.cpp
  test/java/Combination.java
Labels: minor, simple

#4310 Move regular expression inclusion test to RegExpEntail
  src/theory/strings/regexp_entail.cpp
  src/theory/strings/regexp_entail.h
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/regexp_operation.h
Labels: minor, simple

#4311 Add ProofNode data structure
  src/expr/CMakeLists.txt
  src/expr/proof_node.cpp
  src/expr/proof_node.h
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
Labels: complex, major

#4315 Eliminate remaining references to parent TheoryStrings object
  src/theory/strings/extf_solver.cpp
  src/theory/strings/extf_solver.h
  src/theory/strings/inference_manager.cpp
  src/theory/strings/inference_manager.h
  src/theory/strings/regexp_solver.cpp
  src/theory/strings/regexp_solver.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: moderate, normal

#4317 Add ProofNodeManager and ProofChecker
  src/expr/CMakeLists.txt
  src/expr/proof_checker.cpp
  src/expr/proof_checker.h
  src/expr/proof_node.h
  src/expr/proof_node_manager.cpp
  src/expr/proof_node_manager.h
Labels: major, moderate

#4324 antlr: Use relative path in ANTLR script.
  contrib/get-antlr-3.4
Labels: major, simple

#4323 Add (context-dependent) Proof
  src/expr/CMakeLists.txt
  src/expr/proof.cpp
  src/expr/proof.h
Labels: major, moderate

#4329 Improving EqProof printing
  src/theory/uf/equality_engine.cpp
Labels: minor, simple

#4331 Track inference id for pending facts in strings
  src/theory/strings/inference_manager.cpp
  src/theory/strings/inference_manager.h
Labels: moderate, normal

#4330 Disable unsat cores on nec regression
  test/regress/regress2/arith/prp-13-24.smt2
Labels: major, simple

#4332 Add SCOPE proof rule
  src/expr/proof.cpp
  src/expr/proof_checker.cpp
  src/expr/proof_node.cpp
  src/expr/proof_node.h
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
Labels: normal, simple

#4363 Refactor inference manager in strings to be amenable to proofs
  src/theory/strings/core_solver.cpp
  src/theory/strings/core_solver.h
  src/theory/strings/infer_info.cpp
  src/theory/strings/infer_info.h
  src/theory/strings/inference_manager.cpp
  src/theory/strings/inference_manager.h
Labels: major, moderate

#4204 Introduce a public interface for Sygus commands.
  examples/api/CMakeLists.txt
  examples/api/sygus-fun.cpp
  examples/api/sygus-inv.cpp
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  test/unit/api/CMakeLists.txt
  test/unit/api/grammar_black.h
  test/unit/api/solver_black.h
Labels: complex, normal

#4368 Fix for parse options related to binary name
  src/options/options_template.cpp
Labels: major, simple

#4372 Update to sygus version 2 by default
  src/main/driver_unified.cpp
Labels: major, simple

#4377 Reinstantiate support for conjunctions in facts
  src/theory/strings/inference_manager.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/issue4376.smt2
Labels: major, simple

#4319 Convert v2.5 smt2 regressions to v2.6.
  test/regress/regress0/bug484.smt2
  test/regress/regress0/bug541.smt2
  test/regress/regress0/datatypes/conqueue-dt-enum-iloop.smt2
  test/regress/regress0/datatypes/dt-param-card4-bool-sat.smt2
  test/regress/regress0/datatypes/example-dailler-min.smt2
  test/regress/regress0/datatypes/pair-real-bool.smt2
  test/regress/regress0/fmf/sc_bad_model_1221.smt2
  test/regress/regress0/issue1063-overloading-dt-cons.smt2
  test/regress/regress0/issue1063-overloading-dt-fun.smt2
  test/regress/regress0/issue1063-overloading-dt-sel.smt2
  test/regress/regress0/push-pop/bug654-dd.smt2
  test/regress/regress0/quantifiers/cbqi-lia-dt-simp.smt2
  test/regress/regress0/quantifiers/rew-to-scala.smt2
  test/regress/regress1/arith/bug716.0.smt2
  test/regress/regress1/bug296.smt2
  test/regress/regress1/bug507.smt2
  test/regress/regress1/bug567.smt2
  test/regress/regress1/bug681.smt2
  test/regress/regress1/bug694-Unapply1.scala-0.smt2
  test/regress/regress1/datatypes/dt-param-card4-unsat.smt2
  test/regress/regress1/datatypes/manos-model.smt2
  test/regress/regress1/fmf/LeftistHeap.scala-8-ncm.smt2
  test/regress/regress1/fmf/agree466.smt2
  test/regress/regress1/fmf/agree467.smt2
  test/regress/regress1/fmf/bug0909.smt2
  test/regress/regress1/fmf/bug651.smt2
  test/regress/regress1/fmf/bug723-irrelevant-funs.smt2
  test/regress/regress1/fmf/bug764.smt2
  test/regress/regress1/fmf/constr-ground-to.smt2
  test/regress/regress1/fmf/datatypes-ufinite.smt2
  test/regress/regress1/fmf/forall_unit_data.smt2
  test/regress/regress1/fmf/fore19-exp2-core.smt2
  test/regress/regress1/fmf/german169.smt2
  test/regress/regress1/fmf/german73.smt2
  test/regress/regress1/fmf/jasmin-cdt-crash.smt2
  test/regress/regress1/fmf/loopy_coda.smt2
  test/regress/regress1/fmf/lst-no-self-rev-exp.smt2
  test/regress/regress1/fmf/nun-0208-to.smt2
  test/regress/regress1/fmf/sc-crash-052316.smt2
  test/regress/regress1/fmf/with-ind-104-core.smt2
  test/regress/regress1/quantifiers/bug_743.smt2
  test/regress/regress1/quantifiers/cdt-0208-to.smt2
  test/regress/regress1/quantifiers/parametric-lists.smt2
  test/regress/regress1/quantifiers/stream-x2014-09-18-unsat.smt2
  test/regress/regress1/quantifiers/subtype-param-unk.smt2
  test/regress/regress1/quantifiers/subtype-param.smt2
  test/regress/regress1/sets/issue2568.smt2
  test/regress/regress2/bug765.smt2
  test/regress/regress2/quantifiers/ForElimination-scala-9.smt2
  test/regress/regress2/quantifiers/nunchaku2309663.nun.min.smt2
Labels: moderate, normal

#4373 Allow eager bitblasting with solve bv as int in QF_NIA
  contrib/competitions/smt-comp/run-script-smtcomp-current
  src/smt/set_defaults.cpp
Labels: major, simple

#4380 Ensure disequality splits are processed as lemmas
  src/theory/strings/core_solver.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue4379.smt2
Labels: major, simple

#4381 Strings: Register skolems before sending lemma
  src/theory/strings/inference_manager.cpp
Labels: major, simple

#4382 Introduce best content heuristic for strings
  src/theory/strings/base_solver.cpp
  src/theory/strings/base_solver.h
  src/theory/strings/extf_solver.cpp
Labels: major, moderate

#4392 Fix sets cardinality cycle rule
  src/theory/sets/cardinality_extension.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sets/issue4391-card-lasso.smt2
Labels: major, moderate

#4371 Disambiguate call in testSynthFun unit test
  test/unit/api/solver_black.h
Labels: major, simple

#4402 Update cardinality in strings to unicode standard
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings_utils.cpp
  test/regress/CMakeLists.txt
  test/regress/regress2/strings/cmi-split-cm-fail.smt2
Labels: major, simple

#4407 contrib/get-gmp: Rename and update install instructions with a warning.
  INSTALL.md
  contrib/get-gmp-dev
  contrib/get-win-dependencies
Labels: normal, simple

#4404 update Haniel's affiliation
  AUTHORS
Labels: minor, simple

#4406 Updates to SMT COMP script for 20 minute timeout
  contrib/competitions/smt-comp/run-script-smtcomp-current
Labels: major, simple

#4408 Send lemma for lower bound when registering str.to_int
  src/theory/strings/term_registry.cpp
Labels: major, simple

#4413 Fix strings 2.6 regression
  test/regress/regress1/strings/issue4379.smt2
Labels: major, simple

#4417 SMT-COMP 2020: Use --no-type-checking instead of --no-checking.
  contrib/competitions/smt-comp/run-script-smtcomp-current
  contrib/competitions/smt-comp/run-script-smtcomp-current-incremental
  contrib/competitions/smt-comp/run-script-smtcomp-current-model-validation
  contrib/competitions/smt-comp/run-script-smtcomp-current-unsat-cores
Labels: major, simple

#4419 Do not mark congruent terms as reduced in strings
  src/theory/strings/base_solver.cpp
Labels: major, simple

#4423 Remove skolem share involving pre_first_ctn.
  src/theory/strings/skolem_cache.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/pre_ctn_no_skolem_share.smt2
  test/unit/theory/theory_strings_skolem_cache_black.h
Labels: major, simple
