Repository cvc5/cvc5, pull requests merged in 2020-12, with the labels that each got.

#5533 More fixes for quantifier elimination
  src/smt/quant_elim_solver.cpp
  src/smt/quant_elim_solver.h
  src/smt/smt_engine.cpp
  src/theory/quantifiers_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue5506-qe.smt2
  test/regress/regress1/quantifiers/issue5507-qe.smt2
Labels: normal, simple

#5555 Add regressions for #4707.
  test/regress/CMakeLists.txt
  test/regress/regress0/issue4707-bv-to-bool-small.smt2
  test/regress/regress2/issue4707-bv-to-bool-large.smt2
Labels: minor, simple

#5554 Add regression for #4335.
  test/regress/CMakeLists.txt
  test/regress/regress1/issue4335-unsat-core.smt2
Labels: minor, simple

#5557 Add regressions from #5099
  test/regress/CMakeLists.txt
  test/regress/regress0/issue5099-model-1.smt2
  test/regress/regress0/issue5099-model-2.smt2
Labels: minor, simple

#5539 Refactor transcendental solver
  src/theory/arith/nl/transcendental/exponential_solver.cpp
  src/theory/arith/nl/transcendental/exponential_solver.h
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/arith/nl/transcendental/sine_solver.h
  src/theory/arith/nl/transcendental/taylor_generator.cpp
  src/theory/arith/nl/transcendental/taylor_generator.h
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  src/theory/arith/nl/transcendental/transcendental_state.h
Labels: moderate, normal

#4848 Improve rewriting of str.<=
  src/theory/strings/strings_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/leq.smt2
  test/unit/theory/CMakeLists.txt
  test/unit/theory/strings_rewriter_white.h
Labels: minor, simple

#5560 Fix issues related to model declarations
  src/smt/model.cpp
  src/smt/smt_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/issue5540-2-dump-model.smt2
  test/regress/regress0/issue5540-model-decls.smt2
Labels: major, simple

#5548 google test: Infrastructure and first api test.
  .github/workflows/ci.yml
  CMakeLists.txt
  INSTALL.md
  test/unit/CMakeLists.txt
  test/unit/api/CMakeLists.txt
  test/unit/api/datatype_api_black.cpp
  test/unit/base/CMakeLists.txt
  test/unit/context/CMakeLists.txt
  test/unit/expr/CMakeLists.txt
  test/unit/main/CMakeLists.txt
  test/unit/parser/CMakeLists.txt
  test/unit/preprocessing/CMakeLists.txt
  test/unit/printer/CMakeLists.txt
  test/unit/prop/CMakeLists.txt
  test/unit/test_api.h
  test/unit/theory/CMakeLists.txt
  test/unit/util/CMakeLists.txt
Labels: normal, simple

#5559 Remove assertion related to CEGQI dependency lemmas
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
Labels: major, simple

#5565 Remove use of this-> in FP literal.
  src/util/floatingpoint_literal_symfpu.cpp
  src/util/floatingpoint_literal_symfpu.h.in
Labels: normal, simple

#5569 google test: api: Migrate result_black.
  test/unit/api/CMakeLists.txt
  test/unit/api/result_black.cpp
  test/unit/api/result_black.h
Labels: normal, simple

#5553 Add regressions from #3687.
  test/regress/CMakeLists.txt
  test/regress/regress0/aufbv/issue3687-check-models-small.smt2
  test/regress/regress2/issue3687-check-models.smt2
Labels: minor, simple

#5562 (proof-new) Proofs for expand definitions
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/smt/expand_definitions.cpp
  src/smt/expand_definitions.h
  src/smt/preprocessor.cpp
  src/theory/builtin/proof_checker.cpp
Labels: moderate, normal

#5573 Remove rewrite that breaks MACRO_SR_PRED_TRANSFORM
  src/theory/arith/nl/ext/factoring_check.cpp
Labels: normal, simple

#5561 Use new let binding for cvc printer
  src/printer/cvc/cvc_printer.cpp
  src/printer/cvc/cvc_printer.h
  test/unit/expr/node_black.h
Labels: normal, simple

#5566 google test: api: Migrate grammar_black.
  test/unit/api/CMakeLists.txt
  test/unit/api/grammar_black.cpp
  test/unit/api/grammar_black.h
Labels: normal, simple

#5567 google test: api: Migrate op_black.
  test/unit/api/CMakeLists.txt
  test/unit/api/op_black.cpp
  test/unit/test_api.h
Labels: normal, simple

#5530 Add associative utilities to node manager
  src/expr/node_manager.cpp
  src/expr/node_manager.h
Labels: normal, simple

#5568 google test: api: Use individual fixture for datatype_black.
  test/unit/api/datatype_api_black.cpp
Labels: normal, simple

#5571 google test: api: Migrate term_black.
  test/unit/api/CMakeLists.txt
  test/unit/api/term_black.cpp
  test/unit/api/term_black.h
Labels: normal, simple

#5574 Remove dagification visitor
  src/CMakeLists.txt
  src/printer/dagification_visitor.cpp
  src/printer/dagification_visitor.h
  src/printer/smt2/smt2_printer.cpp
Labels: minor, simple

#5576 Rename macro Message to CVC4Message.
  src/base/output.h
  src/main/driver_unified.cpp
  src/parser/antlr_tracing.h
  src/parser/cvc/Cvc.g
  src/preprocessing/passes/unconstrained_simplifier.cpp
  src/smt/managed_ostreams.cpp
  src/smt/options_manager.cpp
  src/smt/update_ostream.h
  src/theory/arith/approx_simplex.cpp
  src/theory/arith/attempt_solution_simplex.cpp
  src/theory/arith/constraint.cpp
  src/theory/arith/dio_solver.cpp
  src/theory/arith/dual_simplex.cpp
  src/theory/arith/fc_simplex.cpp
  src/theory/arith/linear_equality.cpp
  src/theory/arith/soi_simplex.cpp
  src/theory/arith/theory_arith_private.cpp
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/substitutions.cpp
  src/theory/uf/cardinality_extension.cpp
  test/unit/util/output_black.h
Labels: major, simple

#5575 Remove Record object and convert to Node-level API
  src/api/cvc4cpp.cpp
  src/expr/node_manager.cpp
  src/expr/record.cpp
  src/expr/record.h
Labels: normal, simple

#5578 Fix RoundingMode mapping in API.
  src/api/cvc4cpp.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/fp/issue-5524.smt2
Labels: major, simple

#5580 google test: base: Migrate map_util_black.
  test/unit/CMakeLists.txt
  test/unit/base/CMakeLists.txt
  test/unit/base/map_util_black.cpp
  test/unit/base/map_util_black.h
  test/unit/test.h
Labels: normal, simple

#5588 Make run_regression.py executable.
  test/regress/run_regression.py
Labels: major, simple

#5577 Refactor handling of global declarations
  src/expr/symbol_manager.cpp
  src/expr/symbol_manager.h
  src/expr/symbol_table.cpp
  src/expr/symbol_table.h
  src/parser/antlr_input.cpp
  src/parser/cvc/Cvc.g
  src/parser/cvc/cvc_input.cpp
  src/parser/input.cpp
  src/parser/input.h
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/parser_builder.cpp
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/parser/smt2/smt2_input.cpp
  src/parser/smt2/sygus_input.cpp
  src/parser/tptp/tptp.cpp
  src/parser/tptp/tptp_input.cpp
  src/smt/command.cpp
Labels: moderate, normal

#5581 Models as
  src/options/smt_options.toml
  src/printer/smt2/smt2_printer.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/models-print-1.smt2
  test/regress/regress0/models-print-2.smt2
  test/regress/regress0/printer/empty_sort.smt2
Labels: bug

#5551 Use mkAnd where the number of children may be less than two.
  src/theory/uf/cardinality_extension.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/issue5550-num-children.smt2
Labels: normal, simple

#5570 google test: api: Migrate solver_black.
  test/unit/api/CMakeLists.txt
  test/unit/api/solver_black.cpp
  test/unit/api/solver_black.h
Labels: normal, simple

#5446 (proof-new) Updates to SMT proof manager and SmtEngine
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/smt/proof_manager.cpp
  src/smt/proof_manager.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
Labels: moderate, normal

#5597 update-copyright: Preserve file permissions.
  contrib/update-copyright.pl
Labels: simple

#5595 Use NodeDfsIterable for BVToInt::makeBinary
  src/preprocessing/passes/bv_to_int.cpp
Labels: minor, refactor, simple

#5582 google test: context: Migrate cdlist_black.
  test/unit/context/CMakeLists.txt
  test/unit/context/cdlist_black.cpp
  test/unit/context/cdlist_black.h
  test/unit/memory.h
Labels: normal, simple

#5584 google test: context: Migrate cdmap_black.
  test/unit/context/CMakeLists.txt
  test/unit/context/cdmap_black.cpp
  test/unit/context/cdmap_black.h
Labels: normal, simple

#5594 google test: api: Migrate sort_black.
  test/unit/api/CMakeLists.txt
  test/unit/api/sort_black.cpp
Labels: normal, simple

#5600 Fix bug in hasBoundVar
  src/expr/node_algorithm.cpp
Labels: normal, simple

#5585 google test: context: Migrate cdmap_white.
  test/unit/context/CMakeLists.txt
  test/unit/context/cdmap_white.cpp
  test/unit/context/cdmap_white.h
Labels: normal, simple

#5586 google test: context: Migrate cdo_black.
  test/unit/context/CMakeLists.txt
  test/unit/context/cdo_black.cpp
  test/unit/context/cdo_black.h
Labels: normal, simple

#5598 google test: expr: Migrate attribute_black.
  test/unit/expr/CMakeLists.txt
  test/unit/expr/attribute_black.cpp
  test/unit/expr/attribute_black.h
  test/unit/test_expr.h
Labels: simple

#5601 Fix bugs in getFreeVariables
  src/expr/node_algorithm.cpp
  src/expr/node_algorithm.h
Labels: moderate, normal

#5556 Add regression from #4927
  test/regress/CMakeLists.txt
  test/regress/regress0/arrays/issue4927-unsat-cores.smt2
Labels: minor, simple

#5522 (proof-new) Split proof ensure closed checks to own file
  src/expr/CMakeLists.txt
  src/expr/lazy_proof.cpp
  src/expr/lazy_proof_chain.cpp
  src/expr/proof_ensure_closed.cpp
  src/expr/proof_ensure_closed.h
  src/expr/proof_generator.cpp
  src/expr/proof_generator.h
  src/expr/proof_node_updater.cpp
  src/prop/prop_proof_manager.cpp
  src/theory/theory_engine.cpp
  src/theory/trust_node.cpp
Labels: minor, simple

#5544 Do not expand theory definitions at the beginning of preprocessing
  src/smt/process_assertions.cpp
  src/theory/arith/arith_preprocess.cpp
  src/theory/arith/arith_preprocess.h
  src/theory/arith/operator_elim.cpp
  src/theory/arith/operator_elim.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/arrays/theory_arrays.cpp
  src/theory/bv/theory_bv.cpp
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/fp/theory_fp.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/quant_split.cpp
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
  src/theory/strings/theory_strings.cpp
  src/theory/theory_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/arith/div-chainable.smt2
  test/regress/regress0/arith/issue3413.smt2
  test/regress/regress0/bug484.smt2
  test/regress/regress0/datatypes/issue2838.cvc
  test/regress/regress0/fmf/fmc_unsound_model.smt2
  test/regress/regress0/fmf/sc_bad_model_1221.smt2
  test/regress/regress1/arith/issue4985-model-success.smt2
  test/regress/regress1/arith/issue4985b-model-success.smt2
  test/regress/regress1/fmf/LeftistHeap.scala-8-ncm.smt2
  test/regress/regress1/fmf/german169.smt2
  test/regress/regress1/fmf/issue3626.smt2
  test/regress/regress1/fmf/jasmin-cdt-crash.smt2
  test/regress/regress1/fmf/loopy_coda.smt2
  test/regress/regress1/fmf/lst-no-self-rev-exp.smt2
  test/regress/regress1/fmf/memory_model-R_cpp-dd.cvc
  test/regress/regress1/fmf/nun-0208-to.smt2
  test/regress/regress1/ho/issue4065-no-rep.smt2
  test/regress/regress1/quantifiers/issue5470-aext.smt2
  test/regress/regress1/quantifiers/qbv-test-invert-bvudiv-0.smt2
  test/regress/regress1/quantifiers/qbv-test-invert-bvudiv-1.smt2
  test/regress/regress1/quantifiers/qbv-test-invert-bvurem-1-neq.smt2
  test/regress/regress1/quantifiers/qbv-test-invert-bvurem-1.smt2
  test/regress/regress1/quantifiers/qbv-test-urem-rewrite.smt2
  test/regress/regress1/sets/is_singleton1.smt2
  test/regress/regress1/sets/issue5271.smt2
  test/regress/regress1/sets/sets-tuple-poly.cvc
  test/regress/regress1/sets/univ-set-uf-elim.smt2
  test/regress/regress1/sygus/issue3944-div-rewrite.smt2
  test/regress/regress1/trim.cvc
  test/regress/regress2/bv_to_int_5095_2.smt2
  test/regress/regress2/quantifiers/net-policy-no-time.smt2
Labels: moderate, normal

#5599 Refactor initial phase of transcendental solver
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/transcendental/exponential_solver.cpp
  src/theory/arith/nl/transcendental/exponential_solver.h
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/arith/nl/transcendental/sine_solver.h
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
  src/theory/arith/nl/transcendental/transcendental_solver.h
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  src/theory/arith/nl/transcendental/transcendental_state.h
Labels: moderate, normal

#5602 Fix issue with free variables introduced by quantifier rewriter
  src/options/quantifiers_options.toml
  src/smt/set_defaults.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
  test/regress/CMakeLists.txt
  test/regress/regress0/quantifiers/ufnia-fv-delta.smt2
Labels: normal, simple

#5615 (proof-new) Fix nl factoring lemma proof
  src/theory/arith/nl/ext/factoring_check.cpp
Labels: normal, simple

#5614 Fix and reenable fact vs lemma optimization in datatypes
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/dt-tc-opt-small.smt2
Labels: moderate, normal

#5603 Add support for BV proofs with the simple bitblasting solver.
  src/CMakeLists.txt
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/bv/bitblast/simple_bitblaster.cpp
  src/theory/bv/bitblast/simple_bitblaster.h
  src/theory/bv/bv_solver_simple.cpp
  src/theory/bv/bv_solver_simple.h
  src/theory/bv/proof_checker.cpp
  src/theory/bv/proof_checker.h
  src/theory/bv/theory_bv.cpp
Labels: major, simple

#5612 [proof-new] Adding MACRO_RESOLUTION rule and updating proof checker
  src/expr/proof_rule.h
  src/theory/booleans/proof_checker.cpp
Labels: moderate, normal

#5579 Fix collect model values for sequences of sequences
  src/theory/strings/theory_strings.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/seq/issue5543-unit-cmv.smt2
Labels: moderate, normal

#5616 Proper implementation of expand definitions for sequences
  src/theory/strings/kinds
  src/theory/strings/rewrites.cpp
  src/theory/strings/rewrites.h
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/skolem_cache.cpp
  src/theory/strings/skolem_cache.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/seq/seq-expand-defs.smt2
  test/regress/regress0/seq/seq-nth-undef-unsat.smt2
  test/regress/regress0/seq/seq-types.smt2
Labels: moderate, normal

#5589 Make term indices in the strings base solver aware of types
  src/theory/strings/base_solver.cpp
  src/theory/strings/base_solver.h
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/issue5542-strings-seq-mix.smt2
Labels: moderate, normal

#5620 bv-to-int: Expand definitions of bvudiv and bvurem during bv-to-int preprocessing pass
  src/preprocessing/passes/bv_to_int.cpp
  test/regress/CMakeLists.txt
Labels: performance, simple

#5613 [proof-new] Updating SAT proof to use MACRO_RESOLUTION
  src/prop/sat_proof_manager.cpp
  src/prop/sat_proof_manager.h
  src/theory/booleans/proof_checker.cpp
Labels: moderate, normal

#5512 Fix a bug with synth-fun printer
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/smt/command.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/sygus/issue5512-vvv.sy
Labels: normal, simple

#5552 Add regression from #1978.
  test/regress/CMakeLists.txt
  test/regress/regress0/bool/issue1978.smt2
  test/regress/regress0/issue4707-bv-to-bool-small.smt2
  test/regress/regress2/issue4707-bv-to-bool-large.smt2
Labels: minor, simple

#5587 google test: context: Migrate context_black.
  test/unit/context/CMakeLists.txt
  test/unit/context/context_black.cpp
  test/unit/context/context_black.h
Labels: normal, simple

#5592 google test: context: Migrate context_mm_black.
  test/unit/context/CMakeLists.txt
  test/unit/context/context_mm_black.cpp
  test/unit/context/context_mm_black.h
Labels: normal, simple

#5619 Update help message for `--bv-div-zero-const` option
  src/options/bv_options.toml
Labels: minor, simple

#5627 Do not check FP at last call if not necessary
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp.h
Labels: minor, simple

#5628 Ensure CEGQI is applied for parametric datatypes when applicable
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/quantifiers/cegqi-par-dt-simple.smt2
Labels: normal, simple

#5631 Delete obsolete unit tests for Expr and ExprManager.
  test/unit/expr/CMakeLists.txt
  test/unit/expr/expr_manager_public.h
  test/unit/expr/expr_public.h
Labels: normal, simple

#5622 Split initial exp lemma into separate lemmas.
  src/theory/arith/nl/transcendental/exponential_solver.cpp
Labels: moderate, normal

#5630 google test: context: Migrate context_white.
  test/unit/context/CMakeLists.txt
  test/unit/context/context_white.cpp
  test/unit/context/context_white.h
Labels: normal, simple

#5626 Make decision engine independent of AssertionsPipeline
  src/decision/decision_engine.cpp
  src/decision/decision_engine.h
  src/decision/decision_strategy.h
  src/decision/justification_heuristic.cpp
  src/decision/justification_heuristic.h
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/smt/smt_solver.cpp
  src/theory/theory_engine.cpp
  test/regress/regress1/issue4335-unsat-core.smt2
Labels: major, moderate

#5632 google test: expr: Migrate attribute_white.
  test/unit/expr/CMakeLists.txt
  test/unit/expr/attribute_black.cpp
  test/unit/expr/attribute_white.cpp
  test/unit/expr/attribute_white.h
  test/unit/test_expr.h
Labels: normal, simple

#5641 kind_map: Remove unused Accessor class.
  src/expr/kind_map.h
Labels: normal, simple

#5636 (proof-new) Add initial refinement proofs for exponentials
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/arith/nl/transcendental/exponential_solver.cpp
  src/theory/arith/nl/transcendental/proof_checker.cpp
Labels: moderate, normal

#5640 google test: expr: Migrate kind_map_black.
  src/expr/kind_map.h
  test/unit/expr/CMakeLists.txt
  test/unit/expr/kind_map_black.cpp
  test/unit/expr/kind_map_black.h
Labels: normal, simple

#5642 (proof-new) Make theory preprocessor proofs self contained
  src/theory/theory_engine.cpp
  src/theory/theory_preprocessor.cpp
  src/theory/theory_preprocessor.h
Labels: normal, simple

#5644 Fix compiler warnings.
  src/theory/strings/sequences_rewriter.cpp
Labels: normal, simple

#5634 google test: expr: Migrate kind_black.
  test/unit/expr/CMakeLists.txt
  test/unit/expr/kind_black.cpp
  test/unit/expr/kind_black.h
Labels: normal, simple

#5646 Refactor KindMap
  src/expr/kind_map.h
  src/theory/uf/equality_engine.cpp
  src/theory/uf/equality_engine.h
  test/unit/expr/kind_map_black.cpp
Labels: minor, moderate

#5625 (proof-new) Add proofs for secant lemmas for exponential functions
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/arith/nl/transcendental/proof_checker.cpp
  src/theory/arith/nl/transcendental/taylor_generator.cpp
  src/theory/arith/nl/transcendental/taylor_generator.h
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
  src/theory/arith/nl/transcendental/transcendental_state.cpp
Labels: moderate, normal

#5623 Fix length assumption for deq norm emp rule
  src/theory/strings/core_solver.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue5611-deq-norm-emp.smt2
Labels: normal, simple

#5652 Flush statistics through NodeManager in SmtEngine
  src/main/command_executor.cpp
  src/main/command_executor.h
  src/main/driver_unified.cpp
  src/main/main.cpp
  src/main/main.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
Labels: normal, simple

#5564 Fix SAT-context dependent issue in strings preregistration
  src/theory/strings/term_registry.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/seq/issue5547-seq-len-unit.smt2
  test/regress/regress0/seq/issue5547-small-seq-len-unit.smt2
Labels: normal, simple

#5563 Fix and improve evaluator
  src/theory/evaluator.cpp
Labels: moderate, normal

#5655 (proof-new) Add bound variable manager
  src/expr/bound_var_manager.cpp
  src/expr/bound_var_manager.h
Labels: moderate, normal

#5664 [proof-new] Updating interfaces between prop engine and minisat
  src/decision/decision_engine.h
  src/prop/minisat/core/Solver.cc
  src/prop/minisat/core/Solver.h
  src/prop/minisat/minisat.cpp
  src/prop/minisat/minisat.h
  src/prop/minisat/simp/SimpSolver.cc
  src/prop/minisat/simp/SimpSolver.h
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/prop_proof_manager.cpp
  src/prop/prop_proof_manager.h
  src/prop/sat_solver.h
  src/prop/sat_solver_factory.cpp
  src/prop/sat_solver_factory.h
  src/smt/smt_solver.cpp
Labels: moderate, normal

#5624 Properly implement datatype selector triggers
  src/options/quantifiers_options.toml
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/theory/quantifiers/ematching/candidate_generator.cpp
  src/theory/quantifiers/ematching/candidate_generator.h
  src/theory/quantifiers/ematching/inst_match_generator.cpp
  src/theory/quantifiers/ematching/trigger.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/quantifiers/selector-trigger.smt2
Labels: moderate, normal

#5667 [proof-new] Make prop engine proof producing
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
Labels: normal, simple

#5669 [proof-new] Making the CDCL(T) Minisat proof producing
  src/prop/minisat/core/Solver.cc
  src/prop/minisat/core/Solver.h
Labels: moderate, normal

#5675 (proof-new) Add proofs for the sine tangent lemma.
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/arith/nl/transcendental/proof_checker.cpp
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/arith/nl/transcendental/sine_solver.h
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
Labels: moderate, normal

#5674 (proof-new) Add proofs for sine secant lemmas.
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/arith/nl/transcendental/proof_checker.cpp
  src/theory/arith/nl/transcendental/transcendental_state.cpp
Labels: moderate, normal

#5656 (proof-new) Add proof for exponential tangent plane lemmas
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/arith/nl/transcendental/exponential_solver.cpp
  src/theory/arith/nl/transcendental/exponential_solver.h
  src/theory/arith/nl/transcendental/proof_checker.cpp
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
Labels: moderate, normal

#5677 Add getters to retrieve constants from api::Term
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/util/integer_gmp_imp.cpp
  src/util/string.cpp
  src/util/string.h
  test/unit/api/term_black.cpp
Labels: moderate, normal

#5672 Remove bv divide by zero option
  src/options/bv_options.toml
  src/smt/set_defaults.cpp
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv_rewrite_rules_operator_elimination.h
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
  src/theory/bv/theory_bv_rewriter.cpp
  test/regress/regress0/bv/divtest_2_5.smt2
  test/regress/regress0/bv/pr4993-bvugt-bvurem-a.smt2
  test/regress/regress0/bv/pr4993-bvugt-bvurem-b.smt2
  test/regress/regress1/ho/issue4065-no-rep.smt2
  test/regress/regress1/quantifiers/qbv-test-invert-bvudiv-1-neq.smt2
  test/regress/regress1/quantifiers/qbv-test-invert-bvudiv-1.smt2
Labels: normal, simple

#5671 Fix datatypes compute ground value
  src/expr/dtype.cpp
  src/expr/dtype_cons.cpp
  src/theory/type_enumerator.h
Labels: normal, simple

#5421 Consolidate basic sygus utilities regarding sygus conjectures
  src/CMakeLists.txt
  src/preprocessing/passes/sygus_inference.cpp
  src/preprocessing/passes/synth_rew_rules.cpp
  src/theory/quantifiers/sygus/sygus_abduct.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.h
  src/theory/quantifiers/sygus/sygus_utils.cpp
  src/theory/quantifiers/sygus/sygus_utils.h
  src/theory/quantifiers/sygus/template_infer.cpp
Labels: moderate, normal

#5676 Proper expand definitions for sets
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
Labels: minor, simple

#5678 Improvements related to quantifiers printing
  src/printer/smt2/smt2_printer.cpp
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers/quantifiers_attributes.h
Labels: minor, simple

#5680 Move trigger trie to own file
  src/CMakeLists.txt
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/ematching/trigger.h
  src/theory/quantifiers/ematching/trigger_trie.cpp
  src/theory/quantifiers/ematching/trigger_trie.h
  src/theory/quantifiers_engine.h
Labels: minor, simple

#5681 Use uint64 utility when parsing tuple selectors in smt2
  src/parser/smt2/smt2.cpp
Labels: normal, simple

#5670 Move ownership of term formula removal to theory preprocessor
  src/preprocessing/passes/ite_removal.cpp
  src/preprocessing/preprocessing_pass_context.cpp
  src/preprocessing/preprocessing_pass_context.h
  src/smt/check_models.cpp
  src/smt/preprocessor.cpp
  src/smt/preprocessor.h
  src/smt/smt_solver.cpp
  src/smt/term_formula_removal.cpp
  src/smt/term_formula_removal.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/theory_preprocessor.cpp
  src/theory/theory_preprocessor.h
Labels: moderate, normal

#5679 (proof-new) Use bound variable manager
  src/expr/CMakeLists.txt
  src/expr/bound_var_manager.cpp
  src/expr/node_manager.cpp
  src/expr/node_manager.h
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/theory/arrays/skolem_cache.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
  src/theory/strings/skolem_cache.cpp
Labels: moderate, normal

#5683 Renamed InferInfo::getAntecedant to InferInfo::getAntecedent
  src/theory/strings/infer_info.cpp
  src/theory/strings/infer_info.h
  src/theory/strings/inference_manager.cpp
Labels: minor, simple

#5682 Simplify synth-fun printer
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/smt/command.cpp
  src/smt/smt_engine.cpp
Labels: normal, simple

#5684 Mark quantifier instantiations as needs justify
  src/theory/quantifiers_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/quantifiers/cegqi-needs-justify.smt2
Labels: normal, simple

#5647 Simplify preprocessing
  src/options/smt_options.toml
  src/preprocessing/passes/unconstrained_simplifier.cpp
  src/smt/process_assertions.cpp
  src/smt/process_assertions.h
  src/smt/set_defaults.cpp
  test/regress/regress0/unconstrained/4481.smt2
Labels: moderate, normal

#5688 [proof-new] Only use old proof code for unsat cores if no new proofs
  src/prop/minisat/core/Solver.cc
Labels: normal, simple

#5685 Simplify and fix check models
  src/smt/check_models.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/datatypes/issue1433.smt2
  test/regress/regress0/decision/quant-ex1.smt2
  test/regress/regress0/fmf/QEpres-uf.855035.smtv1.smt2
  test/regress/regress0/fp/issue3536.smt2
  test/regress/regress0/fp/issue3619.smt2
  test/regress/regress0/parser/to_fp.smt2
  test/regress/regress0/quantifiers/issue5645-dt-cm-spurious.smt2
  test/regress/regress1/arith/arith-brab-test.smt2
  test/regress/regress1/bug507.smt2
  test/regress/regress1/fmf/Hoare-z3.931718.smtv1.smt2
  test/regress/regress1/fmf/am-bad-model.cvc
  test/regress/regress1/fmf/refcount24.cvc.smt2
  test/regress/regress1/quantifiers/intersection-example-onelane.proof-node22337.smt2
  test/regress/regress1/sets/choose3.smt2
  test/regress/regress1/wrong-qfabvfp-smtcomp2018.smt2
  test/regress/regress2/issue3687-check-models.smt2
Labels: moderate, normal

#5695 Simplify term formula removal interface
  src/smt/term_formula_removal.cpp
  src/smt/term_formula_removal.h
Labels: normal, simple

#5697 (proof-new) Prepare nonlinear extension and nl-ext for proofs.
  src/CMakeLists.txt
  src/theory/arith/nl/ext/ext_state.cpp
  src/theory/arith/nl/ext/ext_state.h
  src/theory/arith/nl/ext/proof_checker.cpp
  src/theory/arith/nl/ext/proof_checker.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/theory_arith.cpp
Labels: moderate, normal

#5696 Cache rewritten lemmas in TheoryInferenceManager
  src/theory/arith/inference_manager.cpp
  src/theory/theory_inference_manager.cpp
Labels: moderate, normal

#5691 (proof-new) Minor updates to term conversion proof generator
  src/expr/term_conversion_proof_generator.cpp
Labels: minor, simple

#5699 (proof-new) Add proof for split zero check.
  src/theory/arith/nl/ext/split_zero_check.cpp
  src/theory/arith/nl/ext/split_zero_check.h
  src/theory/arith/nl/nonlinear_extension.cpp
Labels: moderate, normal

#5700 (proof-new) Add proof for tangent plane lemmas
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/arith/nl/ext/tangent_plane_check.cpp
Labels: moderate, normal

#5702 Bugfix: proofs for props of non-normal arith lits
  src/theory/arith/constraint.cpp
  src/theory/arith/constraint.h
  src/theory/arith/theory_arith_private.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/arith/non-normal.smt2
Labels: bug, normal, simple

#5704 (proof-new) Add proof checker for tangent plane lemma
  src/theory/arith/nl/ext/proof_checker.cpp
Labels: minor, moderate

#5687 Simplify internal API for sygus
  src/api/cvc4cpp.cpp
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/smt/sygus_solver.cpp
  src/smt/sygus_solver.h
  src/theory/quantifiers/sygus/sygus_interpol.cpp
Labels: minor, simple

#5703 (proof-new) Setup proof infrastructure for transcendental solver
  src/CMakeLists.txt
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/transcendental/proof_checker.cpp
  src/theory/arith/nl/transcendental/proof_checker.h
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
  src/theory/arith/nl/transcendental/transcendental_solver.h
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  src/theory/arith/nl/transcendental/transcendental_state.h
Labels: minor, moderate

#5689 Fix issue with selector triggers
  src/theory/quantifiers/ematching/candidate_generator.cpp
  src/theory/quantifiers/ematching/candidate_generator.h
Labels: normal, simple

#5701 Eliminate recursion from the internals of term formula removal
  src/smt/term_formula_removal.cpp
  src/smt/term_formula_removal.h
  src/theory/theory_preprocessor.cpp
  test/regress/regress1/nl/nl_uf_lalt.smt2
Labels: moderate, normal

#5698 (proof-new) Make nl-ext factoring lemmas proof producing.
  src/theory/arith/nl/ext/factoring_check.cpp
  src/theory/arith/nl/ext/factoring_check.h
  src/theory/arith/nl/nonlinear_extension.cpp
Labels: moderate, normal

#5690 Move ownership of theory preprocessor to TheoryProxy
  src/preprocessing/passes/ite_removal.cpp
  src/preprocessing/passes/theory_preprocess.cpp
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
  src/smt/process_assertions.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/theory_preprocessor.h
Labels: moderate, normal

#5712 Have unsat core regression agnostic to number of assertions in core
  test/regress/regress1/issue4335-unsat-core.smt2
Labels: normal, simple

#5709 (proof-new) Add proof for pi bound lemma
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/arith/nl/transcendental/proof_checker.cpp
  src/theory/arith/nl/transcendental/transcendental_state.cpp
Labels: moderate, normal

#5713 Remove preregister instantiation heuristic
  src/options/quantifiers_options.toml
  src/smt/set_defaults.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.h
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.h
  test/regress/regress0/sygus/aig-si.sy
  test/regress/regress1/quantifiers/issue4243-prereg-inc.smt2
  test/regress/regress1/sygus/parity-si-rcons.sy
Labels: normal, simple

#5711 Make theory preprocess rewrite equalities a preprocessing pass
  src/CMakeLists.txt
  src/preprocessing/passes/theory_rewrite_eq.cpp
  src/preprocessing/passes/theory_rewrite_eq.h
  src/preprocessing/preprocessing_pass_registry.cpp
  src/smt/process_assertions.cpp
  src/theory/arith/theory_arith.cpp
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/theory_preprocessor.cpp
  test/regress/regress1/quantifiers/qbv-simple-2vars-vo.smt2
  test/regress/regress1/quantifiers/qbv-subcall.smt2
  test/regress/regress1/quantifiers/smtcomp-qbv-053118.smt2
Labels: moderate, normal

#5715 Move slow regression to regress3
  test/regress/CMakeLists.txt
  test/regress/regress3/issue4476-ext-rew.smt2
Labels: normal, simple

#5718 Delete duplicated code
  src/theory/term_registration_visitor.cpp
Labels: minor, performance, refactor, simple

#5719 Minor simplification to Theory::theoryOf
  src/theory/theory.cpp
Labels: minor, simple

#5707 (proof-new) Add proofs for nonlinear sign lemmas.
  src/theory/arith/nl/ext/monomial_check.cpp
Labels: moderate, normal

#5714 (proof-new) Miscelleneous fixes from proof-new
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/trust_substitutions.cpp
  src/theory/trust_substitutions.h
Labels: normal, simple

#5723 [proof-new] Adding a manager for the new unsat cores
  src/CMakeLists.txt
  src/smt/unsat_core_manager.cpp
  src/smt/unsat_core_manager.h
Labels: moderate, normal

#5716 Remove quant EPR option
  src/CMakeLists.txt
  src/options/quantifiers_options.toml
  src/smt/set_defaults.cpp
  src/theory/quantifiers/cegqi/ceg_epr_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_epr_instantiator.h
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/quant_epr.cpp
  src/theory/quantifiers/quant_epr.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
  src/theory/sep/theory_sep.cpp
  src/theory/sep/theory_sep.h
  test/regress/CMakeLists.txt
Labels: minor, simple

#5708 Add option to track and notify from CNF stream
  src/prop/cnf_stream.cpp
  src/prop/cnf_stream.h
  src/prop/minisat/core/Solver.cc
  src/prop/minisat/core/Solver.h
  src/prop/prop_engine.cpp
  src/theory/bv/bitblast/eager_bitblaster.cpp
  src/theory/bv/bitblast/lazy_bitblaster.cpp
  src/theory/bv/bv_eager_solver.cpp
  src/theory/bv/theory_bv.cpp
Labels: moderate, normal

#5724 Dumping unsat cores after check-sat-assuming/QUERY
  src/main/command_executor.cpp
  src/options/options.h
  src/options/options_public_functions.cpp
  src/options/smt_options.toml
  src/theory/quantifiers/sygus/synth_conjecture.cpp
Labels: normal, simple

#5725 [proof-new] Only use old proofs for unsat cores if no proof new
  src/preprocessing/assertion_pipeline.cpp
  src/preprocessing/passes/apply_substs.cpp
  src/preprocessing/passes/ite_removal.cpp
  src/preprocessing/passes/ite_simp.cpp
  src/preprocessing/passes/miplib_trick.cpp
  src/preprocessing/passes/non_clausal_simp.cpp
  src/preprocessing/passes/quantifier_macros.cpp
  src/prop/minisat/core/Solver.cc
  src/prop/minisat/minisat.cpp
  src/prop/minisat/simp/SimpSolver.cc
  src/prop/prop_engine.cpp
  src/prop/theory_proxy.cpp
  src/smt/assertions.cpp
  src/smt/process_assertions.cpp
  src/smt/set_defaults.cpp
  src/theory/quantifiers/instantiate.cpp
  src/theory/strings/theory_strings_preprocess.cpp
Labels: moderate, normal
