Repository cvc5/cvc5, pull requests merged in 2021-08, with the labels that each got.

#6961 bv: Enable equality engine for bitblast-internal.
  src/theory/bv/bv_solver_bitblast_internal.cpp
  src/theory/bv/bv_solver_bitblast_internal.h
  src/theory/theory.cpp
  test/regress/regress2/bug349.smtv1.smt2
Labels: normal, simple

#6966 Add 'REQUIRES: poly' to regression.
  test/regress/regress1/nl/factor_agg_s.smt2
Labels: normal, simple

#6967 Properly honor --stats-all and --stats-expert when printing statistics
  src/main/command_executor.cpp
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
Labels: moderate, normal

#6964 Remove "inUnsatCore" flag throughout
  src/parser/smt2/Smt2.g
  src/parser/tptp/Tptp.g
  src/parser/tptp/tptp.cpp
  src/parser/tptp/tptp.h
  src/smt/assertions.cpp
  src/smt/assertions.h
  src/smt/command.cpp
  src/smt/command.h
  src/smt/quant_elim_solver.cpp
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/smt/smt_solver.cpp
  src/smt/smt_solver.h
  src/smt/sygus_solver.cpp
Labels: minor, simple

#6960 Refactor shared solver to use theory builtin inference manager
  src/theory/builtin/theory_builtin.cpp
  src/theory/builtin/theory_builtin.h
  src/theory/ee_manager_central.cpp
  src/theory/engine_output_channel.cpp
  src/theory/engine_output_channel.h
  src/theory/output_channel.cpp
  src/theory/output_channel.h
  src/theory/shared_solver.cpp
  src/theory/shared_solver.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  test/unit/test_smt.h
  test/unit/theory/theory_white.cpp
Labels: minor, moderate

#6970 Use int64_t or uint64_t for all integer options
  src/options/arith_options.toml
  src/options/arrays_options.toml
  src/options/base_options.toml
  src/options/bv_options.toml
  src/options/datatypes_options.toml
  src/options/decision_options.toml
  src/options/expr_options.toml
  src/options/mkoptions.py
  src/options/proof_options.toml
  src/options/prop_options.toml
  src/options/quantifiers_options.toml
  src/options/smt_options.toml
  src/options/uf_options.toml
Labels: normal, simple

#6965 Remove dependencies on smt engine in smt solver
  src/prop/cnf_stream.cpp
  src/prop/cnf_stream.h
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/smt/smt_engine.cpp
  src/smt/smt_solver.cpp
  src/smt/smt_solver.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  test/unit/prop/cnf_stream_white.cpp
Labels: normal, simple

#6951 Add IEEE-BV-to-FP to external-to-internal mapping in C++ API
  src/api/cpp/cvc5.cpp
Labels: bug, minor, simple

#6974 [proof] Add getProof to API and use it in GetProofCommand
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/smt/command.cpp
  test/unit/api/solver_black.cpp
Labels: normal, simple

#6962 Add missing inference identifiers
  src/theory/arith/theory_arith_private.cpp
  src/theory/arrays/theory_arrays.cpp
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/term_database.cpp
  src/theory/sets/cardinality_extension.cpp
  src/theory/sets/theory_sets_rels.cpp
Labels: normal, simple

#6976 Replace numeric predicates by explicit minimum and maximum
  src/options/mkoptions.py
  src/options/options_handler.h
  src/options/prop_options.toml
Labels: moderate, normal

#6971 Add API function to get list of option names
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/options/mkoptions.py
  src/options/options_public.h
  src/options/options_public_template.cpp
  test/unit/api/solver_black.cpp
Labels: moderate, normal

#6950 Add optional debug information for dumping instantiations
  src/main/command_executor.cpp
  src/options/main_options.toml
  src/printer/printer.cpp
  src/smt/proof_post_processor.cpp
  src/smt/proof_post_processor.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/smt/unsat_core_manager.cpp
  src/smt/unsat_core_manager.h
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/instantiation_list.cpp
  src/theory/quantifiers/instantiation_list.h
Labels: moderate, normal

#6978 syqi: Add debug information for dumping instantiations.
  src/theory/quantifiers/sygus_inst.cpp
Labels: major, simple

#6982 Improve error messages for UF catching higher-order.
  src/theory/uf/theory_uf.cpp
Labels: normal, simple

#6977 Add inference ids for remainder of sygus solver
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/cegis.h
  src/theory/quantifiers/sygus/cegis_core_connective.cpp
  src/theory/quantifiers/sygus/cegis_core_connective.h
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/cegis_unif.h
  src/theory/quantifiers/sygus/sygus_module.h
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/sygus/sygus_pbe.h
  src/theory/quantifiers/sygus/sygus_stats.cpp
  src/theory/quantifiers/sygus/sygus_stats.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/synth_engine.cpp
Labels: moderate, normal

#6983 Fix comments on dot printer
  src/proof/dot/dot_printer.cpp
Labels: minor, simple

#6981 Fix policy for merging subproofs
  src/proof/proof_node_updater.cpp
  src/proof/proof_node_updater.h
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/open-pf-merge.smt2
Labels: moderate, normal

#6975 Proper printing of proofs in the internal calculus
  src/proof/proof_node_to_sexpr.cpp
  src/proof/proof_node_to_sexpr.h
Labels: moderate, normal

#6986 Consolidate solver resets
  src/main/command_executor.cpp
  src/main/command_executor.h
  src/smt/command.cpp
  src/smt/command.h
Labels: moderate, normal

#6985 Avoid calling api::Solver constructor with Options
  test/api/smt2_compliance.cpp
  test/unit/parser/parser_black.cpp
Labels: normal, simple

#6916 Fix policy for rewriting string equalities
  src/theory/strings/extf_solver.cpp
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/sequences_rewriter.h
  src/theory/strings/strings_entail.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/theory_inference_manager.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue6101-2.smt2
  test/regress/regress1/strings/issue6101.smt2
  test/regress/regress1/strings/issue6913.smt2
Labels: normal, moderate, do not merge

#6990 [Unit Tests] Add missing include
  test/unit/api/solver_black.cpp
Labels: major, simple

#6895 Generalize term canonizer for type classes
  src/expr/term_canonize.cpp
  src/expr/term_canonize.h
Labels: minor, moderate

#6955 Normalize val in BitVector(val_str, base)
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/util/bitvector.h
  test/unit/api/solver_black.cpp
  test/unit/util/bitvector_black.cpp
Labels: bug, minor, simple

#6991 Clear options manager
  src/options/base_options.toml
  src/options/expr_options.toml
  src/options/mkoptions.py
  src/options/options_handler.cpp
  src/options/options_handler.h
  src/options/options_public_template.cpp
  src/options/options_template.cpp
  src/options/options_template.h
  src/options/smt_options.toml
  src/smt/options_manager.cpp
Labels: normal, moderate

#6989 Merge options cmake into general cmake file
  src/CMakeLists.txt
  src/options/CMakeLists.txt
  src/options/mkoptions.py
  src/options/module_template.cpp
  src/options/module_template.h
Labels: normal, moderate

#7003 Support older CMake versions
  .github/workflows/ci.yml
  src/CMakeLists.txt
Labels: major, simple

#6995 Simplify generation of option module code.
  src/options/mkoptions.py
  src/options/module_template.cpp
  src/options/module_template.h
Labels: normal, moderate

#7004 Disable external initialization of `thread_local` variables
  CMakeLists.txt
Labels: normal, simple

#6994 Refactor setDefaults to use an options object
  src/smt/options_manager.cpp
  src/smt/set_defaults.cpp
  src/smt/set_defaults.h
Labels: normal, moderate

#7007 [Strings] Make fact detection more robust
  src/theory/strings/infer_info.cpp
Labels: normal, simple

#7011 Make Theory class use Env
  src/smt/env.cpp
  src/smt/env.h
  src/smt/smt_solver.cpp
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/arrays/theory_arrays.cpp
  src/theory/arrays/theory_arrays.h
  src/theory/bags/theory_bags.cpp
  src/theory/bags/theory_bags.h
  src/theory/booleans/theory_bool.cpp
  src/theory/booleans/theory_bool.h
  src/theory/builtin/theory_builtin.cpp
  src/theory/builtin/theory_builtin.h
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp.h
  src/theory/quantifiers/theory_quantifiers.cpp
  src/theory/quantifiers/theory_quantifiers.h
  src/theory/sep/theory_sep.cpp
  src/theory/sep/theory_sep.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  src/theory/theory.cpp
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf.h
  test/unit/test_smt.h
  test/unit/theory/theory_white.cpp
Labels: normal, moderate

#7006 Use InferenceManager in ExtTheory
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/ext_theory.cpp
  src/theory/ext_theory.h
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: normal, moderate

#7012 Push Env class into TheoryState
  src/theory/arith/arith_state.cpp
  src/theory/arith/arith_state.h
  src/theory/arith/theory_arith.cpp
  src/theory/arrays/theory_arrays.cpp
  src/theory/bags/solver_state.cpp
  src/theory/bags/solver_state.h
  src/theory/bags/theory_bags.cpp
  src/theory/builtin/theory_builtin.cpp
  src/theory/bv/theory_bv.cpp
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/fp/theory_fp.cpp
  src/theory/quantifiers/quantifiers_state.cpp
  src/theory/quantifiers/quantifiers_state.h
  src/theory/quantifiers/theory_quantifiers.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/sets/solver_state.cpp
  src/theory/sets/solver_state.h
  src/theory/sets/theory_sets.cpp
  src/theory/strings/solver_state.cpp
  src/theory/strings/solver_state.h
  src/theory/strings/theory_strings.cpp
  src/theory/theory_state.cpp
  src/theory/theory_state.h
  src/theory/uf/theory_uf.cpp
  test/unit/test_smt.h
Labels: normal, moderate

#7021 Initial refactoring of set defaults
  src/CMakeLists.txt
  src/smt/options_manager.cpp
  src/smt/options_manager.h
  src/smt/set_defaults.cpp
  src/smt/set_defaults.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
Labels: normal, simple

#7019 Improve conversion to skolems in expression miner
  src/theory/quantifiers/expr_miner.cpp
  src/theory/quantifiers/expr_miner.h
Labels: minor, simple

#7020 Cosmetic improvements to theory datatypes
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
Labels: minor, simple

#7025 Make theory BV use central eq engine when option is enabled
  src/theory/theory.cpp
Labels: normal, simple

#7017 Fix policy for eliminating quantified formulas
  src/options/quantifiers_options.toml
  src/smt/set_defaults.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching.cpp
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers/quantifiers_attributes.h
  src/theory/quantifiers/quantifiers_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/quantifiers/issue6996-trivial-elim.smt2
Labels: normal, simple

#7026 Refactoring theory-specific variable elimination in quantifiers rewriter
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
Labels: normal, simple

#7028 Make SmtEngineState use Env
  src/smt/env.cpp
  src/smt/env.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine_state.cpp
  src/smt/smt_engine_state.h
  src/smt/smt_solver.cpp
Labels: normal, simple

#7005 Replace `Maybe` with `std::optional`
  src/preprocessing/passes/pseudo_boolean_processor.cpp
  src/preprocessing/passes/pseudo_boolean_processor.h
  src/theory/arith/approx_simplex.cpp
  src/theory/arith/approx_simplex.h
  src/theory/arith/infer_bounds.cpp
  src/theory/arith/infer_bounds.h
  src/theory/arith/linear_equality.cpp
  src/theory/arith/linear_equality.h
  src/theory/arith/nl/poly_conversion.cpp
  src/theory/arith/simplex_update.cpp
  src/theory/arith/simplex_update.h
  src/theory/arith/theory_arith_private.cpp
  src/util/CMakeLists.txt
  src/util/maybe.h
  src/util/poly_util.cpp
  src/util/poly_util.h
  src/util/rational_cln_imp.cpp
  src/util/rational_cln_imp.h
  src/util/rational_gmp_imp.cpp
  src/util/rational_gmp_imp.h
  src/util/utility.h
Labels: normal, moderate

#7031 Make TheoryProxy use Env, simplify initialization of PropEngine
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
  src/smt/env.cpp
  src/smt/env.h
  src/smt/smt_engine.cpp
  src/smt/smt_solver.cpp
  src/smt/smt_solver.h
Labels: normal, moderate

#7033 Minor fixes of policy for eliminating quantifiers
  src/options/mkoptions.py
  src/options/quantifiers_options.toml
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  test/regress/regress0/use_approx/bug812_approx.smt2
Labels: major, simple

#7018 Move collectAssertedTerms to the Theory class
  src/theory/model_manager.cpp
  src/theory/model_manager.h
  src/theory/model_manager_distributed.cpp
  src/theory/theory.cpp
  src/theory/theory.h
Labels: normal, moderate

#7034 [unsat cores] [proofs] Revert test about when to explain propagations
  src/prop/theory_proxy.cpp
Labels: normal, simple

#7032 Start using Options via Env in arithmetic
  src/theory/arith/nl/ext/ext_state.cpp
  src/theory/arith/nl/ext/ext_state.h
  src/theory/arith/nl/ext/monomial_bounds_check.cpp
  src/theory/arith/nl/ext/split_zero_check.cpp
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
  src/theory/arith/nl/transcendental/transcendental_solver.h
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  src/theory/arith/nl/transcendental/transcendental_state.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
  src/theory/theory.h
  src/theory/theory_state.h
Labels: normal, moderate

#7029 Refactor proof output for TPTP
  src/options/options_handler.cpp
  src/options/options_handler.h
  src/options/printer_options.toml
  src/options/proof_options.toml
  src/smt/command.cpp
  src/smt/proof_manager.cpp
  src/smt/proof_manager.h
  src/smt/smt_engine.cpp
Labels: normal, simple

#6984 Split proof final callback to its own file
  src/CMakeLists.txt
  src/smt/proof_final_callback.cpp
  src/smt/proof_final_callback.h
  src/smt/proof_post_processor.cpp
  src/smt/proof_post_processor.h
Labels: minor, simple

#6993 Catch cases where recursive functions reference functions-to-synthesize
  src/smt/assertions.cpp
  src/theory/theory_engine.cpp
Labels: normal, simple

#7022 Remove `--(no-)interactive-prompt`
  src/main/driver_unified.cpp
  src/main/interactive_shell.cpp
  src/options/main_options.toml
Labels: normal, simple

#6992 Add CVC5ApiOptionException
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/main/driver_unified.cpp
  src/main/main.cpp
  src/options/option_exception.h
  src/options/options_public_template.cpp
Labels: normal, moderate

#7039 Use Env class in nonlinear extension
  src/theory/arith/branch_and_bound.cpp
  src/theory/arith/inference_manager.cpp
  src/theory/arith/nl/cad/cdcac.cpp
  src/theory/arith/nl/cad/cdcac.h
  src/theory/arith/nl/cad_solver.cpp
  src/theory/arith/nl/cad_solver.h
  src/theory/arith/nl/iand_solver.cpp
  src/theory/arith/nl/iand_solver.h
  src/theory/arith/nl/nl_model.cpp
  src/theory/arith/nl/nl_model.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/strategy.cpp
  src/theory/arith/nl/strategy.h
  src/theory/arith/theory_arith.cpp
  test/unit/theory/theory_arith_cad_white.cpp
Labels: normal, moderate

#7038 Eliminate eager model building
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: normal, moderate

#7040 Support sygus standard command syntax set-feature
  src/parser/smt2/Smt2.g
  test/regress/CMakeLists.txt
  test/regress/regress0/sygus/setFeature.sy
Labels: normal, simple

#7043 More refactoring of set defaults
  src/smt/set_defaults.cpp
  src/smt/set_defaults.h
  src/theory/quantifiers/sygus/synth_verify.cpp
Labels: normal, moderate

#6330 Add Term.java to the java API
  src/api/java/CMakeLists.txt
  src/api/java/cvc5/Term.java
  src/api/java/jni/cvc5_Term.cpp
  test/unit/api/java/cvc5/TermTest.java
Labels: normal, simple

#6930 Make driver use options from the solver
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/main/command_executor.cpp
  src/main/command_executor.h
  src/main/driver_unified.cpp
  src/main/main.cpp
  src/main/main.h
  src/smt/command.cpp
Labels: normal, moderate

#7048 Prenex quantified formulas with user annotations by default
  src/theory/quantifiers/ematching/inst_strategy_e_matching.cpp
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers/quantifiers_attributes.h
  src/theory/quantifiers/quantifiers_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/ddatv-delta2.smt2
Labels: normal, simple

#7049 Simplify model printing modes
  src/CMakeLists.txt
  src/options/options_handler.h
  src/options/printer_modes.cpp
  src/options/printer_modes.h
  src/options/smt_options.toml
  src/printer/cvc/cvc_printer.cpp
  src/printer/smt2/smt2_printer.cpp
Labels: normal, simple

#7053 Use options correctly in competition mode
  src/main/main.cpp
Labels: major, simple

#6998 api: Require size argument for mkBitVector.
  examples/api/python/floating_point.py
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/python/cvc5.pxi
  src/parser/cvc/Cvc.g
  src/parser/smt2/Smt2.g
  test/python/unit/api/test_solver.py
  test/python/unit/api/test_term.py
  test/unit/api/solver_black.cpp
  test/unit/api/term_black.cpp
Labels: normal, simple

#7054 Move options parsing code to main
  src/main/CMakeLists.txt
  src/main/driver_unified.cpp
  src/main/main.h
  src/main/options.h
  src/main/options_template.cpp
  src/options/didyoumean.h
  src/options/mkoptions.py
  src/options/option_exception.h
  src/options/options_public.h
  src/options/options_public_template.cpp
  test/unit/node/node_black.cpp
Labels: normal, moderate

#7046 Fix single invocation partition for higher-order
  src/expr/subs.cpp
  src/expr/subs.h
  src/theory/quantifiers/single_inv_partition.cpp
  src/theory/quantifiers/single_inv_partition.h
  test/regress/CMakeLists.txt
  test/regress/regress0/sygus/ho-occ-synth-fun.sy
Labels: normal, simple

#7030 Generalize inequality elimination in quantifiers rewriter
  src/theory/quantifiers/quantifiers_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/quantifiers/issue6999-deq-elim.smt2
Labels: normal, moderate

#7035 Purify substitutions in strings proof reconstruction
  src/theory/strings/infer_proof_cons.cpp
  src/theory/strings/infer_proof_cons.h
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/delta-trust-subs.smt2
Labels: normal, moderate

#7036 Fix non-deterministism in quantified datatypes expansion rewrite
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
Labels: normal, moderate

#7042 Miscellaneous changes from proof-new
  src/printer/smt2/smt2_printer.cpp
  src/proof/print_expr.h
  src/proof/proof_checker.cpp
  src/proof/proof_checker.h
  src/proof/proof_rule.cpp
  src/proof/trust_node.cpp
  src/proof/trust_node.h
  src/smt/preprocess_proof_generator.cpp
Labels: minor, simple

#7044 Uniform treatment of trusted theory inferences in proofs
  src/proof/proof_rule.cpp
  src/proof/proof_rule.h
  src/theory/arith/constraint.cpp
  src/theory/arith/pp_rewrite_eq.cpp
  src/theory/arith/proof_checker.cpp
  src/theory/arrays/inference_manager.cpp
  src/theory/arrays/proof_checker.cpp
  src/theory/arrays/theory_arrays.cpp
  src/theory/datatypes/infer_proof_cons.cpp
  src/theory/datatypes/proof_checker.cpp
  src/theory/strings/infer_proof_cons.cpp
  src/theory/strings/proof_checker.cpp
Labels: minor, simple

#7047 Top-level structure for set defaults
  src/smt/set_defaults.cpp
  src/smt/set_defaults.h
Labels: normal, simple

#6942 Refactor enumerator management in synth conjecture
  src/CMakeLists.txt
  src/theory/quantifiers/sygus/enum_value_manager.cpp
  src/theory/quantifiers/sygus/enum_value_manager.h
  src/theory/quantifiers/sygus/example_eval_cache.cpp
  src/theory/quantifiers/sygus/example_eval_cache.h
  src/theory/quantifiers/sygus/rcons_type_info.h
  src/theory/quantifiers/sygus/sygus_enumerator.cpp
  src/theory/quantifiers/sygus/sygus_enumerator.h
  src/theory/quantifiers/sygus/sygus_enumerator_callback.h
  src/theory/quantifiers/sygus/sygus_reconstruct.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus_sampler.cpp
Labels: minor, moderate

#7045 Split higher-order term database
  src/CMakeLists.txt
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/theory/quantifiers/ematching/ho_trigger.cpp
  src/theory/quantifiers/ho_term_database.cpp
  src/theory/quantifiers/ho_term_database.h
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers/term_database.h
  src/theory/quantifiers/term_registry.cpp
Labels: minor, moderate

#7060 Eliminate calls to currentSmtEngine
  src/preprocessing/passes/sort_infer.cpp
  src/theory/datatypes/sygus_extension.cpp
  src/theory/quantifiers/candidate_rewrite_database.cpp
  src/theory/quantifiers/candidate_rewrite_database.h
  src/theory/quantifiers/expr_miner.cpp
  src/theory/quantifiers/expr_miner.h
  src/theory/quantifiers/expr_miner_manager.cpp
  src/theory/quantifiers/expr_miner_manager.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/query_generator.cpp
  src/theory/quantifiers/query_generator.h
  src/theory/quantifiers/solution_filter.cpp
  src/theory/quantifiers/solution_filter.h
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.h
  src/theory/quantifiers/sygus/cegis_core_connective.cpp
  src/theory/quantifiers/sygus/enum_value_manager.cpp
  src/theory/quantifiers/sygus/enum_value_manager.h
  src/theory/quantifiers/sygus/rcons_type_info.cpp
  src/theory/quantifiers/sygus/rcons_type_info.h
  src/theory/quantifiers/sygus/sygus_enumerator_callback.cpp
  src/theory/quantifiers/sygus/sygus_enumerator_callback.h
  src/theory/quantifiers/sygus/sygus_grammar_norm.cpp
  src/theory/quantifiers/sygus/sygus_interpol.h
  src/theory/quantifiers/sygus/sygus_reconstruct.cpp
  src/theory/quantifiers/sygus/sygus_reconstruct.h
  src/theory/quantifiers/sygus/sygus_repair_const.cpp
  src/theory/quantifiers/sygus/sygus_repair_const.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/synth_verify.cpp
  src/theory/quantifiers/sygus/synth_verify.h
  src/theory/quantifiers/sygus_sampler.cpp
  src/theory/quantifiers/sygus_sampler.h
  src/theory/quantifiers_engine.cpp
Labels: normal, moderate

#7085 Fix quantifiers dynamic split module for parametric datatypes
  src/theory/datatypes/theory_datatypes_utils.cpp
  src/theory/datatypes/theory_datatypes_utils.h
  src/theory/quantifiers/quant_split.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/quantifiers/issue6838-qpdt.smt2
Labels: normal, simple

#7079 Fix proof equality engine for "no-explain" premises
  src/CMakeLists.txt
  src/proof/assumption_proof_generator.cpp
  src/proof/assumption_proof_generator.h
  src/theory/uf/proof_equality_engine.cpp
  src/theory/uf/proof_equality_engine.h
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/instance3303-delta.smt2
  test/regress/regress1/strings/instance7075-delta.smt2
Labels: major, moderate

#7088 Refactor filename handling
  src/main/driver_unified.cpp
  src/options/main_options.toml
  src/smt/env.cpp
  src/smt/env.h
  src/smt/proof_manager.cpp
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/smt/smt_engine_state.cpp
  src/smt/smt_solver.cpp
  src/util/statistics_public.cpp
Labels: normal, moderate

#7072 Further refactoring of set defaults for incompatibility methods
  src/smt/set_defaults.cpp
  src/smt/set_defaults.h
Labels: normal, moderate

#6503 Add kind BAG_MAP and its type rule to bags
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_kind.h
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/bags/bags_rewriter.cpp
  src/theory/bags/bags_rewriter.h
  src/theory/bags/kinds
  src/theory/bags/normal_form.cpp
  src/theory/bags/normal_form.h
  src/theory/bags/rewrites.cpp
  src/theory/bags/rewrites.h
  src/theory/bags/theory_bags_type_rules.cpp
  src/theory/bags/theory_bags_type_rules.h
  test/regress/regress1/bags/map.smt2
  test/unit/theory/theory_bags_rewriter_white.cpp
  test/unit/theory/theory_bags_type_rules_white.cpp
Labels: normal, moderate

#6980 Add API function to obtain information about a single option
  .github/workflows/ci.yml
  docs/api/cpp/class_hierarchy.rst
  docs/api/cpp/cpp.rst
  docs/api/cpp/optioninfo.rst
  examples/CMakeLists.txt
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/options/base_options.toml
  src/options/mkoptions.py
  src/options/options_public.h
  src/options/options_public_template.cpp
  test/unit/api/solver_black.cpp
Labels: normal, moderate

#7092 Make regular expression sort not closed enumerable
  src/expr/type_node.cpp
Labels: minor, simple

#7090 Fix normal forms context-dependent simplification for strings
  src/theory/strings/base_solver.cpp
  src/theory/strings/extf_solver.cpp
Labels: major, simple

#7097 Make sure modes are sorted in ModeInfo
  src/options/mkoptions.py
  test/unit/api/solver_black.cpp
Labels: major, simple

#7099 bv: Remove dump=bv-rewrites.
  src/smt/dump.cpp
  src/theory/bv/theory_bv_rewrite_rules.h
Labels: major, simple
