Repository cvc5/cvc5, pull requests merged in 2021-02, with the labels that each got.

#5840 Fix BagsRewriter::rewriteUnionDisjoint
  src/theory/bags/bags_rewriter.cpp
  src/theory/bags/theory_bags.cpp
  test/unit/theory/theory_bags_rewriter_white.h
Labels: normal, simple

#5842 Avoid calling the printers while converting sexpr to string.
  src/smt/command.cpp
  src/smt/command.h
  src/util/string.cpp
Labels: normal, simple

#5839 Simplify alpha equivalence module
  src/theory/quantifiers/alpha_equivalence.cpp
  src/theory/quantifiers/alpha_equivalence.h
Labels: normal, simple

#5827 Eliminate PREPROCESS lemma property
  src/theory/arith/arith_preprocess.cpp
  src/theory/arith/inference_manager.cpp
  src/theory/arith/inference_manager.h
  src/theory/arith/nl/iand_solver.cpp
  src/theory/arith/nl/transcendental/exponential_solver.cpp
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/ext_theory.cpp
  src/theory/fp/theory_fp.cpp
  src/theory/output_channel.cpp
  src/theory/output_channel.h
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers_engine.cpp
Labels: normal, simple

#5845 [proof-new] Fix bug in expansion of MACRO_RESOLUTION
  src/smt/proof_post_processor.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/proofs/macro-res-exp-crowding-lit-inside-unit.smt2
Labels: moderate, normal

#5846 Improvements for NL traces
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/transcendental/exponential_solver.cpp
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
Labels: minor, simple

#5847 Cleanup some includes
  src/preprocessing/passes/ackermann.cpp
  src/preprocessing/passes/bv_to_int.cpp
  src/preprocessing/passes/extended_rewriter_pass.cpp
  src/preprocessing/passes/int_to_bv.cpp
  src/preprocessing/passes/ite_removal.cpp
  src/preprocessing/passes/ite_simp.cpp
  src/preprocessing/passes/miplib_trick.cpp
  src/preprocessing/passes/non_clausal_simp.cpp
  src/preprocessing/passes/quantifier_macros.cpp
  src/preprocessing/passes/theory_preprocess.cpp
  src/prop/theory_proxy.cpp
  src/smt/smt_solver.cpp
  src/theory/combination_care_graph.cpp
  src/theory/model_manager.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/ematching/candidate_generator.cpp
  src/theory/quantifiers/ematching/ho_trigger.cpp
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/skolemize.cpp
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus_inst.cpp
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers/term_util.cpp
  src/theory/quantifiers_engine.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/uf/cardinality_extension.cpp
  src/theory/uf/theory_uf_model.cpp
  src/theory/uf/theory_uf_model.h
  src/theory/valuation.cpp
Labels: minor, simple

#5830 Remove quantifiers regression from decision folder
  test/regress/CMakeLists.txt
  test/regress/regress1/decision/quant-symmetric_unsat_7.smt2
Labels: minor, simple

#5835 (proof-new) Refactor theory preprocessing
  src/theory/theory_preprocessor.cpp
  src/theory/theory_preprocessor.h
Labels: moderate, normal

#5841 (proof-new) Miscellaneous fixes and regressions
  src/expr/proof_rule.cpp
  src/theory/arrays/inference_manager.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_inference_manager.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/tpp-fail-pf-012921.smt2
  test/regress/regress0/preprocess/circuit-prop.smt2
  test/regress/regress1/bv/min-pp-rewrite-error.smt2
Labels: minor, simple

#5850 [proof-new] Fix MACRO_RESOLUTION expansion for singleton clause corner case
  src/smt/proof_post_processor.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/proofs/macro-res-exp-crowding-lit-inside-unit.smt2
  test/regress/regress1/proofs/macro-res-exp-singleton-after-elimCrowd.smt2
Labels: moderate, normal

#5851 Add BV solver bitblast.
  src/CMakeLists.txt
  src/options/bv_options.toml
  src/options/options_handler.cpp
  src/prop/cadical.cpp
  src/prop/cadical.h
  src/prop/cryptominisat.cpp
  src/prop/cryptominisat.h
  src/prop/sat_solver.h
  src/smt/set_defaults.cpp
  src/theory/bv/bitblast/bitblast_strategies_template.h
  src/theory/bv/bitblast/simple_bitblaster.cpp
  src/theory/bv/bitblast/simple_bitblaster.h
  src/theory/bv/bv_solver_bitblast.cpp
  src/theory/bv/bv_solver_bitblast.h
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv.h
Labels: moderate, normal

#5853 [proof-new] Catch trivial cycles in SAT proof generation
  src/prop/sat_proof_manager.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/proofs/sat-trivial-cycle.smt2
Labels: normal, simple

#5831 Eliminate equality query dependence on quantifiers engine
  src/theory/quantifiers/equality_query.cpp
  src/theory/quantifiers/equality_query.h
  src/theory/quantifiers/first_order_model.cpp
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: minor, simple

#5829 Introduce quantifiers registry utility
  src/CMakeLists.txt
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.h
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/conjecture_generator.h
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  src/theory/quantifiers/ematching/instantiation_engine.h
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/fmf/bounded_integers.h
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/fmf/model_engine.h
  src/theory/quantifiers/inst_strategy_enumerative.cpp
  src/theory/quantifiers/inst_strategy_enumerative.h
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/quant_conflict_find.h
  src/theory/quantifiers/quant_split.cpp
  src/theory/quantifiers/quant_split.h
  src/theory/quantifiers/quant_util.cpp
  src/theory/quantifiers/quant_util.h
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers/quantifiers_attributes.h
  src/theory/quantifiers/quantifiers_modules.cpp
  src/theory/quantifiers/quantifiers_modules.h
  src/theory/quantifiers/quantifiers_registry.cpp
  src/theory/quantifiers/quantifiers_registry.h
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus/synth_engine.h
  src/theory/quantifiers/sygus_inst.cpp
  src/theory/quantifiers/sygus_inst.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: normal, simple

#5856 Adding an option to optimize polite combination for datatypes
  src/options/datatypes_options.toml
  src/theory/datatypes/theory_datatypes.cpp
Labels: feature, minor, performance, simple

#5854 Miscellaneous cleaning in theory engine
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: minor, simple

#5855 google test: expr: Migrate node_builder_black.
  test/unit/expr/CMakeLists.txt
  test/unit/expr/node_builder_black.cpp
  test/unit/expr/node_builder_black.h
  test/unit/test_node.h
Labels: normal, simple

#5862 Remove obsolete include from node_black unit test.
  test/unit/expr/node_black.cpp
Labels: normal, simple

#5864 google test: expr: Migrate node_manager_white.
  test/unit/expr/CMakeLists.txt
  test/unit/expr/node_manager_white.cpp
  test/unit/expr/node_manager_white.h
  test/unit/test_node.h
Labels: normal, simple

#5858 Minor cleaning of quantifiers engine
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: minor, simple

#5870 google test: expr: Migrate symbol_table_black.
  test/unit/expr/CMakeLists.txt
  test/unit/expr/symbol_table_black.cpp
  test/unit/expr/symbol_table_black.h
Labels: normal, simple

#5861 Do not combine theories if theory engine needs check
  src/theory/sets/theory_sets_private.cpp
  src/theory/theory_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sets/issue4124-need-check.smt2
Labels: normal, simple

#5860 Avoid spurious traversal of terms during preregistration
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/ext_theory.cpp
  src/theory/ext_theory.h
  src/theory/strings/extf_solver.cpp
  src/theory/strings/extf_solver.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: normal, simple

#5868 google test: expr: Migrate node_traversal_black.
  test/unit/expr/CMakeLists.txt
  test/unit/expr/node_traversal_black.cpp
  test/unit/expr/node_traversal_black.h
Labels: normal, simple

#5863 Use consistent names for fixtures in unit tests.
  test/unit/api/datatype_api_black.cpp
  test/unit/api/grammar_black.cpp
  test/unit/api/op_black.cpp
  test/unit/api/result_black.cpp
  test/unit/api/solver_black.cpp
  test/unit/api/sort_black.cpp
  test/unit/api/term_black.cpp
  test/unit/expr/node_black.cpp
  test/unit/expr/node_builder_black.cpp
Labels: normal, simple

#5874 Remove support for inst closure
  src/api/cvc4cpp.cpp
  src/api/cvc4cppkind.h
  src/options/quantifiers_options.toml
  src/parser/smt2/smt2.cpp
  src/theory/quantifiers/ematching/candidate_generator.cpp
  src/theory/quantifiers/equality_query.cpp
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/kinds
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers/term_database.h
  src/theory/quantifiers/theory_quantifiers.cpp
  src/theory/quantifiers/theory_quantifiers_type_rules.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: normal, simple

#5866 Fix dumping of assertions for monolithic preprocessing passes
  src/smt/dump.cpp
Labels: normal, simple

#5869 google test: expr: Migrate node_white.
  test/unit/expr/CMakeLists.txt
  test/unit/expr/node_white.cpp
  test/unit/expr/node_white.h
  test/unit/test_node.h
Labels: normal, simple

#5880 Fix disequality between seq.unit terms
  src/theory/strings/core_solver.cpp
  src/theory/strings/core_solver.h
  src/theory/strings/infer_info.cpp
  src/theory/strings/infer_info.h
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/issue5666-orig-unit-deq.smt2
  test/regress/regress0/strings/issue5666-unit-deq.smt2
Labels: moderate, normal

#5867 Use quantifiers inference manager for lemma management
  src/printer/printer.h
  src/theory/inference_manager_buffered.cpp
  src/theory/inference_manager_buffered.h
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.h
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/ematching/ho_trigger.cpp
  src/theory/quantifiers/ematching/ho_trigger.h
  src/theory/quantifiers/ematching/inst_strategy.h
  src/theory/quantifiers/ematching/inst_strategy_e_matching.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching.h
  src/theory/quantifiers/ematching/inst_strategy_e_matching_user.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching_user.h
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/ematching/trigger.h
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/inst_strategy_enumerative.cpp
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/instantiate.h
  src/theory/quantifiers/quant_conflict_find.h
  src/theory/quantifiers/quant_split.cpp
  src/theory/quantifiers/quant_util.h
  src/theory/quantifiers/quantifiers_inference_manager.cpp
  src/theory/quantifiers/quantifiers_inference_manager.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus_inst.cpp
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
  src/theory/theory_inference_manager.cpp
Labels: moderate, normal

#5872 google test: expr: Migrate type_node_white.
  test/unit/expr/CMakeLists.txt
  test/unit/expr/type_node_white.cpp
  test/unit/expr/type_node_white.h
Labels: normal, simple

#5879 [quantifiers] Fix prenex computation
  src/expr/node_algorithm.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
  test/regress/CMakeLists.txt
  test/regress/regress0/quantifiers/issue5693-prenex.smt2
  test/regress/regress1/quantifiers/prenex-scholl-smt08_RNDPRE_RNDPRE_4_6.smt2
Labels: moderate, normal

#5865 google test: expr: Migrate node_self_iterator_black.
  test/unit/expr/CMakeLists.txt
  test/unit/expr/node_self_iterator_black.cpp
  test/unit/expr/node_self_iterator_black.h
Labels: normal, simple

#5871 google test: expr: Migrate type_cardinality_black.
  test/unit/expr/CMakeLists.txt
  test/unit/expr/type_cardinality_black.cpp
  test/unit/expr/type_cardinality_public.h
Labels: normal, simple

#5878 google test: main: Migrate interactive_shell_black.
  test/unit/main/CMakeLists.txt
  test/unit/main/interactive_shell_black.cpp
  test/unit/main/interactive_shell_black.h
Labels: normal, simple

#5857 google test: expr: Migrate node_manager_black.
  test/unit/expr/CMakeLists.txt
  test/unit/expr/node_manager_black.cpp
  test/unit/expr/node_manager_black.h
Labels: normal, simple

#5877 Make term database optionally SAT-context-dependent
  src/options/quantifiers_options.toml
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers/term_database.h
  src/theory/quantifiers_engine.cpp
Labels: moderate, normal

#5882 Eliminating dependencies from inst utils
  src/theory/quantifiers/ematching/inst_match_generator_multi.cpp
  src/theory/quantifiers/inst_match_trie.cpp
  src/theory/quantifiers/inst_match_trie.h
  src/theory/quantifiers/instantiate.cpp
Labels: normal, simple

#5884 cmake: Make Python3 default and improve toml error messages.
  .github/workflows/ci.yml
  CMakeLists.txt
  INSTALL.md
  NEWS
  configure.sh
  src/options/CMakeLists.txt
Labels: normal, simple

#5859 Do not traverse quantifiers in term formula removal
  src/smt/term_formula_removal.cpp
Labels: normal, simple

#5876 Optimize get skolems method
  src/smt/term_formula_removal.cpp
  src/smt/term_formula_removal.h
Labels: normal, simple

#5883 Remove track instantiations infrastructure
  src/options/quantifiers_options.toml
  src/smt/set_defaults.cpp
  src/theory/quantifiers/inst_match_trie.cpp
  src/theory/quantifiers/inst_match_trie.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/instantiate.h
Labels: normal, simple

#5789 Simplify method for inferring proxy lemmas in strings
  src/theory/strings/inference_manager.cpp
  src/theory/strings/term_registry.cpp
  src/theory/strings/term_registry.h
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue5610-2-infer-proxy.smt2
  test/regress/regress1/strings/issue5610-infer-proxy.smt2
  test/regress/regress1/strings/issue5692-infer-proxy.smt2
Labels: moderate, normal

#5885 Fix open proof for factoring lemma
  src/theory/arith/nl/ext/factoring_check.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/nl/ufnia-factor-open-proof.smt2
Labels: moderate, normal

#5875 Refactor term registration visitors
  src/theory/shared_solver.cpp
  src/theory/shared_solver.h
  src/theory/term_registration_visitor.cpp
  src/theory/term_registration_visitor.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: moderate, normal

#5890 Simplify interface for preprocessor
  src/smt/preprocessor.cpp
  src/smt/preprocessor.h
  src/smt/smt_solver.cpp
Labels: minor, simple

#5852 Fix spurious assertion failure in regexp normalization
  src/theory/strings/regexp_solver.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/issue5816-re-kind.smt2
Labels: minor, simple

#5892 Merge InferenceIds into one enum
  src/CMakeLists.txt
  src/theory/arith/arith_lemma.h
  src/theory/arith/inference_id.cpp
  src/theory/arith/inference_id.h
  src/theory/arith/inference_manager.h
  src/theory/arith/nl/cad_solver.cpp
  src/theory/arith/nl/ext/factoring_check.cpp
  src/theory/arith/nl/ext/monomial_bounds_check.cpp
  src/theory/arith/nl/ext/monomial_check.cpp
  src/theory/arith/nl/ext/split_zero_check.cpp
  src/theory/arith/nl/ext/tangent_plane_check.cpp
  src/theory/arith/nl/iand_solver.cpp
  src/theory/arith/nl/icp/icp_solver.cpp
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/stats.h
  src/theory/arith/nl/transcendental/exponential_solver.cpp
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  src/theory/bags/infer_info.cpp
  src/theory/bags/infer_info.h
  src/theory/bags/inference_generator.cpp
  src/theory/datatypes/infer_proof_cons.cpp
  src/theory/datatypes/infer_proof_cons.h
  src/theory/datatypes/inference.cpp
  src/theory/datatypes/inference.h
  src/theory/datatypes/inference_manager.cpp
  src/theory/datatypes/inference_manager.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/strings/base_solver.cpp
  src/theory/strings/core_solver.cpp
  src/theory/strings/extf_solver.cpp
  src/theory/strings/infer_info.cpp
  src/theory/strings/infer_info.h
  src/theory/strings/infer_proof_cons.cpp
  src/theory/strings/infer_proof_cons.h
  src/theory/strings/inference_manager.cpp
  src/theory/strings/inference_manager.h
  src/theory/strings/regexp_solver.cpp
  src/theory/strings/sequences_stats.h
  src/theory/strings/solver_state.cpp
  src/theory/strings/theory_strings.cpp
Labels: moderate, normal

#5889 [proof-new] Adding a proof-producing ensure literal method
  src/prop/cnf_stream.cpp
  src/prop/cnf_stream.h
  src/prop/proof_cnf_stream.cpp
  src/prop/proof_cnf_stream.h
  src/prop/prop_engine.cpp
Labels: moderate, normal

#5894 Add InferenceId member to TheoryInference
  src/theory/arith/arith_lemma.h
  src/theory/arith/inference_manager.cpp
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/bags/infer_info.cpp
  src/theory/bags/infer_info.h
  src/theory/bags/inference_generator.cpp
  src/theory/datatypes/infer_proof_cons.cpp
  src/theory/datatypes/inference.cpp
  src/theory/datatypes/inference.h
  src/theory/inference_manager_buffered.cpp
  src/theory/strings/core_solver.cpp
  src/theory/strings/core_solver.h
  src/theory/strings/infer_info.cpp
  src/theory/strings/infer_info.h
  src/theory/strings/infer_proof_cons.cpp
  src/theory/strings/inference_manager.cpp
  src/theory/strings/solver_state.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/theory_inference.cpp
  src/theory/theory_inference.h
  src/theory/theory_inference_manager.h
Labels: moderate, normal

#5897 Make most methods of TheoryInferenceManager expect an InferenceId.
  src/theory/arith/arith_preprocess.cpp
  src/theory/arrays/inference_manager.cpp
  src/theory/bags/infer_info.cpp
  src/theory/bv/bitblast/lazy_bitblaster.cpp
  src/theory/bv/bv_solver_bitblast.cpp
  src/theory/bv/bv_solver_lazy.cpp
  src/theory/bv/bv_solver_lazy.h
  src/theory/bv/bv_solver_simple.cpp
  src/theory/bv/bv_subtheory_core.cpp
  src/theory/datatypes/inference_manager.cpp
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/sets/inference_manager.cpp
  src/theory/sets/term_registry.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/strings/inference_manager.cpp
  src/theory/theory_inference.cpp
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
  src/theory/uf/cardinality_extension.cpp
  src/theory/uf/ho_extension.cpp
  src/theory/uf/theory_uf.cpp
Labels: moderate, normal

#5886 google test: parser: Migrate parser_black.
  test/unit/parser/CMakeLists.txt
  test/unit/parser/parser_black.cpp
  test/unit/parser/parser_black.h
Labels: normal, simple

#5895 (proof-new) Option to not automatically consider symmetry in CDProof
  src/expr/proof.cpp
  src/expr/proof.h
Labels: moderate, normal

#5888 Simplify and fix decision engine's handling of skolem definitions
  src/decision/decision_engine.cpp
  src/decision/decision_engine.h
  src/decision/decision_strategy.h
  src/decision/justification_heuristic.cpp
  src/decision/justification_heuristic.h
  src/preprocessing/assertion_pipeline.h
  src/preprocessing/passes/ite_removal.cpp
  src/preprocessing/passes/theory_preprocess.cpp
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/theory_proxy.cpp
  src/smt/smt_solver.cpp
  src/smt/term_formula_removal.h
Labels: moderate, normal

#5905 Properly set up equality engine for BV bitblast solver.
  src/theory/bv/bitblast/lazy_bitblaster.cpp
  src/theory/bv/bv_solver.h
  src/theory/bv/bv_solver_bitblast.cpp
  src/theory/bv/bv_solver_bitblast.h
  src/theory/bv/bv_solver_lazy.cpp
  src/theory/bv/bv_solver_lazy.h
  src/theory/bv/bv_solver_simple.cpp
  src/theory/bv/bv_subtheory_core.cpp
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv.h
Labels: moderate, normal

#5881 Moving methods from quantifiers engine to quantifiers state
  src/CMakeLists.txt
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/ematching/inst_strategy.cpp
  src/theory/quantifiers/ematching/inst_strategy.h
  src/theory/quantifiers/ematching/inst_strategy_e_matching.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching_user.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching_user.h
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  src/theory/quantifiers/inst_strategy_enumerative.cpp
  src/theory/quantifiers/quantifiers_state.cpp
  src/theory/quantifiers/quantifiers_state.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: normal, simple

#5903 Remove now obsolete sendLemmas and inferences stat from arith::nl
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/nl/stats.cpp
  src/theory/arith/nl/stats.h
Labels: moderate, normal

#5896 google test: parser: Migrate parser_builder_black.
  test/unit/parser/CMakeLists.txt
  test/unit/parser/parser_builder_black.cpp
  test/unit/parser/parser_builder_black.h
Labels: normal, simple

#5906 Add bit-level propagation support for BV bitblast solver.
  src/prop/cadical.cpp
  src/prop/cadical.h
  src/prop/sat_solver.h
  src/smt/set_defaults.cpp
  src/theory/bv/bitblast/simple_bitblaster.cpp
  src/theory/bv/bv_solver_bitblast.cpp
  src/theory/bv/bv_solver_bitblast.h
Labels: moderate, normal

#5898 Add new IntegralHistogramStat
  src/util/statistics_registry.h
  test/unit/util/stats_black.h
Labels: moderate, normal

#5911 Add InferenceId to buffered inference manager
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/inference_manager_buffered.cpp
  src/theory/inference_manager_buffered.h
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/ematching/ho_trigger.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching.cpp
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/quant_split.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus_inst.cpp
  src/theory/quantifiers/term_database.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/sets/inference_manager.cpp
Labels: moderate, normal

#5910 Add InferenceIds for theory of arrays
  src/theory/arrays/inference_manager.cpp
  src/theory/arrays/inference_manager.h
  src/theory/arrays/theory_arrays.cpp
  src/theory/inference_id.cpp
  src/theory/inference_id.h
Labels: moderate, normal

#5901 TheoryIds for UF theory.
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/uf/cardinality_extension.cpp
  src/theory/uf/ho_extension.cpp
  src/theory/uf/theory_uf.cpp
Labels: moderate, normal

#5912 Use InferenceId in separation logic theory
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/sep/theory_sep.cpp
  src/theory/sep/theory_sep.h
Labels: moderate, normal

#5914 Compute fact or lemma in datatypes prior to buffering
  src/theory/datatypes/inference.cpp
  src/theory/datatypes/inference_manager.cpp
Labels: normal, simple

#5916 Move methods from term util to quantifiers registry
  src/CMakeLists.txt
  src/preprocessing/passes/quantifier_macros.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.h
  src/theory/quantifiers/conjecture_generator.h
  src/theory/quantifiers/ematching/ho_trigger.cpp
  src/theory/quantifiers/ematching/ho_trigger.h
  src/theory/quantifiers/ematching/inst_match_generator_multi.cpp
  src/theory/quantifiers/ematching/inst_strategy.cpp
  src/theory/quantifiers/ematching/inst_strategy.h
  src/theory/quantifiers/ematching/inst_strategy_e_matching.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching.h
  src/theory/quantifiers/ematching/inst_strategy_e_matching_user.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching_user.h
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  src/theory/quantifiers/ematching/instantiation_engine.h
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/ematching/trigger.h
  src/theory/quantifiers/extended_rewrite.cpp
  src/theory/quantifiers/first_order_model.cpp
  src/theory/quantifiers/first_order_model.h
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/fmf/bounded_integers.h
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/fmf/model_engine.h
  src/theory/quantifiers/inst_match.cpp
  src/theory/quantifiers/inst_strategy_enumerative.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/instantiate.h
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/quant_conflict_find.h
  src/theory/quantifiers/quant_module.cpp
  src/theory/quantifiers/quant_module.h
  src/theory/quantifiers/quant_split.h
  src/theory/quantifiers/quant_util.cpp
  src/theory/quantifiers/quant_util.h
  src/theory/quantifiers/quantifiers_modules.cpp
  src/theory/quantifiers/quantifiers_registry.cpp
  src/theory/quantifiers/quantifiers_registry.h
  src/theory/quantifiers/relevant_domain.cpp
  src/theory/quantifiers/relevant_domain.h
  src/theory/quantifiers/single_inv_partition.cpp
  src/theory/quantifiers/skolemize.h
  src/theory/quantifiers/sygus/synth_engine.h
  src/theory/quantifiers/sygus_inst.h
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers/term_database.h
  src/theory/quantifiers/term_util.cpp
  src/theory/quantifiers/term_util.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: moderate, normal

#5918 Move first order model for full model check to own file
  src/CMakeLists.txt
  src/theory/quantifiers/first_order_model.cpp
  src/theory/quantifiers/first_order_model.h
  src/theory/quantifiers/fmf/first_order_model_fmc.cpp
  src/theory/quantifiers/fmf/first_order_model_fmc.h
  src/theory/quantifiers/fmf/full_model_check.h
  src/theory/quantifiers_engine.cpp
Labels: minor, simple

#5919 Eliminate non-static members in term util
  src/theory/datatypes/sygus_simple_sym.cpp
  src/theory/datatypes/sygus_simple_sym.h
  src/theory/quantifiers/cegqi/ceg_arith_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/quant_module.cpp
  src/theory/quantifiers/quant_module.h
  src/theory/quantifiers/sygus/ce_guided_single_inv_sol.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.h
  src/theory/quantifiers/sygus/sygus_grammar_norm.cpp
  src/theory/quantifiers/sygus/sygus_grammar_norm.h
  src/theory/quantifiers/sygus/sygus_grammar_red.cpp
  src/theory/quantifiers/sygus/sygus_grammar_red.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/term_util.cpp
  src/theory/quantifiers/term_util.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: moderate, normal

#5917 Document UF inferences
  src/theory/inference_id.h
Labels: minor, simple

#5909 New InferenceIds for BV theory
  src/theory/bv/bitblast/lazy_bitblaster.cpp
  src/theory/bv/bv_solver_bitblast.cpp
  src/theory/bv/bv_solver_lazy.cpp
  src/theory/bv/bv_solver_lazy.h
  src/theory/bv/bv_solver_simple.cpp
  src/theory/bv/bv_subtheory_core.cpp
  src/theory/inference_id.h
Labels: moderate, normal

#5900 Add InferenceIds for sets theory.
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/sets/cardinality_extension.cpp
  src/theory/sets/inference_manager.cpp
  src/theory/sets/inference_manager.h
  src/theory/sets/term_registry.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_rels.cpp
  src/theory/sets/theory_sets_rels.h
Labels: moderate, normal

#5913 Add statistic for InferenceId to TheoryInferenceManager.
  src/theory/arith/inference_manager.cpp
  src/theory/arrays/inference_manager.cpp
  src/theory/bags/inference_manager.cpp
  src/theory/bv/theory_bv.cpp
  src/theory/datatypes/inference_manager.cpp
  src/theory/inference_manager_buffered.cpp
  src/theory/inference_manager_buffered.h
  src/theory/quantifiers/quantifiers_inference_manager.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/sets/inference_manager.cpp
  src/theory/strings/inference_manager.cpp
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
  src/theory/uf/theory_uf.cpp
Labels: moderate, normal

#5930 Add Gereon to AUTHORS list.
  AUTHORS
Labels: normal, simple

#5927 Cleanup of inferences in arithmetic theory
  src/CMakeLists.txt
  src/theory/arith/arith_lemma.cpp
  src/theory/arith/arith_lemma.h
  src/theory/arith/arith_preprocess.cpp
  src/theory/arith/inference_manager.cpp
  src/theory/arith/inference_manager.h
  src/theory/arith/nl/cad_solver.cpp
  src/theory/arith/nl/ext/factoring_check.cpp
  src/theory/arith/nl/ext/monomial_bounds_check.cpp
  src/theory/arith/nl/ext/monomial_check.cpp
  src/theory/arith/nl/ext/monomial_check.h
  src/theory/arith/nl/ext/split_zero_check.cpp
  src/theory/arith/nl/ext/tangent_plane_check.cpp
  src/theory/arith/nl/iand_solver.cpp
  src/theory/arith/nl/icp/icp_solver.cpp
  src/theory/arith/nl/nl_lemma_utils.cpp
  src/theory/arith/nl/nl_lemma_utils.h
  src/theory/arith/nl/nl_model.cpp
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/nl/transcendental/exponential_solver.cpp
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  src/theory/inference_id.cpp
  src/theory/inference_id.h
Labels: moderate, normal

#5932 Remove string stat for inferences
  src/theory/inference_id.cpp
  src/theory/strings/inference_manager.cpp
  src/theory/strings/sequences_stats.cpp
  src/theory/strings/sequences_stats.h
Labels: minor, simple

#5924 Fix rewrite for contains over replace
  src/theory/strings/sequences_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/issue5915-repl-ctn-rewrite.smt2
Labels: normal, simple

#5920 Refactoring theory inference process
  src/theory/arith/arith_preprocess.cpp
  src/theory/arith/nl/iand_solver.cpp
  src/theory/arith/nl/nl_lemma_utils.cpp
  src/theory/arith/nl/nl_lemma_utils.h
  src/theory/arrays/inference_manager.cpp
  src/theory/arrays/inference_manager.h
  src/theory/bags/bag_solver.cpp
  src/theory/bags/infer_info.cpp
  src/theory/bags/infer_info.h
  src/theory/bags/inference_generator.cpp
  src/theory/bags/inference_generator.h
  src/theory/bags/inference_manager.h
  src/theory/bags/theory_bags.cpp
  src/theory/datatypes/inference.cpp
  src/theory/datatypes/inference.h
  src/theory/datatypes/inference_manager.cpp
  src/theory/datatypes/inference_manager.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/inference_manager_buffered.cpp
  src/theory/inference_manager_buffered.h
  src/theory/sets/term_registry.cpp
  src/theory/strings/infer_info.cpp
  src/theory/strings/infer_info.h
  src/theory/strings/inference_manager.cpp
  src/theory/strings/inference_manager.h
  src/theory/theory_inference.cpp
  src/theory/theory_inference.h
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
  src/theory/uf/cardinality_extension.cpp
  src/theory/uf/theory_uf.cpp
Labels: moderate, normal

#5931 Fill in missing inference ids in datatypes theory
  src/theory/datatypes/inference_manager.cpp
  src/theory/datatypes/inference_manager.h
  src/theory/datatypes/sygus_extension.cpp
  src/theory/datatypes/sygus_extension.h
  src/theory/datatypes/sygus_simple_sym.cpp
  src/theory/datatypes/sygus_simple_sym.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/inference_id.cpp
  src/theory/inference_id.h
Labels: moderate, normal

#5926 Simplify interface to instantiate
  src/theory/quantifiers/ematching/ho_trigger.cpp
  src/theory/quantifiers/ematching/inst_match_generator.h
  src/theory/quantifiers/ematching/inst_match_generator_multi.cpp
  src/theory/quantifiers/ematching/inst_match_generator_multi.h
  src/theory/quantifiers/ematching/inst_match_generator_simple.cpp
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/inst_match_trie.cpp
  src/theory/quantifiers/inst_match_trie.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/instantiate.h
Labels: minor, simple

#5937 Fix datatypes inference manager when proofs are enabled
  src/theory/datatypes/inference_manager.cpp
Labels: minor, simple

#5950 (proof-new) Add CAD helper pruneRedundantIntervals
  src/theory/arith/nl/cad/cdcac.cpp
  src/theory/arith/nl/cad/cdcac.h
Labels: normal, simple

#5945 (proof-new) Cleanup in transcendental solver, add ApproximationBounds struct.
  src/theory/arith/nl/transcendental/taylor_generator.cpp
  src/theory/arith/nl/transcendental/taylor_generator.h
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
Labels: moderate, normal

#5952 (proof-new) Add proofs for sine lemmas in the transcendental solver
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/arith/nl/transcendental/proof_checker.cpp
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/arith/nl/transcendental/sine_solver.h
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
Labels: moderate, normal

#5949 (proof-new) Add new arithmetic kind INDEXED_ROOT_PREDICATE.
  src/printer/smt2/smt2_printer.cpp
  src/theory/arith/kinds
  src/theory/arith/theory_arith_type_rules.h
  src/util/indexed_root_predicate.h
Labels: moderate, normal

#5948 (proof-new) Add LazyTreeProofGenerator.
  src/CMakeLists.txt
  src/theory/lazy_tree_proof_generator.cpp
  src/theory/lazy_tree_proof_generator.h
Labels: moderate, normal

#5936 google test: preprocessing: Migrate pass_foreign_theory_rewrite_white.
  test/unit/preprocessing/CMakeLists.txt
  test/unit/preprocessing/pass_foreign_theory_rewrite_white.cpp
  test/unit/preprocessing/pass_foreign_theory_rewrite_white.h
  test/unit/test_smt.h
Labels: normal, simple

#5954 [proof-new] Optionally print conclusion in the AST proof
  src/expr/proof_node_to_sexpr.cpp
  src/expr/proof_node_to_sexpr.h
  src/options/proof_options.toml
Labels: minor, simple

#5939 (proof-new) Option to automatically add SYMM steps during proof node update
  src/expr/proof_node_updater.cpp
  src/expr/proof_node_updater.h
Labels: minor, simple

#5953 Require length-in-conclusion form for strings inferences
  src/options/strings_options.toml
  src/theory/strings/core_solver.cpp
  src/theory/strings/core_solver.h
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue5940-2-skc-len-conc.smt2
  test/regress/regress1/strings/issue5940-skc-len-conc.smt2
Labels: moderate, normal

#5956 (proof-new) Add proofs for exponential functions
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/arith/nl/transcendental/exponential_solver.cpp
  src/theory/arith/nl/transcendental/exponential_solver.h
  src/theory/arith/nl/transcendental/proof_checker.cpp
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
Labels: moderate, normal

#5955 (proof-new) Change proof-new option to proof
  src/expr/lazy_proof_chain.cpp
  src/expr/proof_checker.cpp
  src/expr/proof_ensure_closed.cpp
  src/expr/proof_ensure_closed.h
  src/expr/proof_node_algorithm.cpp
  src/expr/proof_node_manager.cpp
  src/expr/proof_node_to_sexpr.cpp
  src/expr/proof_node_updater.cpp
  src/options/proof_options.toml
  src/options/smt_options.toml
  src/preprocessing/passes/ite_removal.cpp
  src/preprocessing/passes/quantifier_macros.cpp
  src/prop/minisat/core/Solver.cc
  src/prop/minisat/minisat.cpp
  src/prop/prop_engine.cpp
  src/prop/sat_proof_manager.cpp
  src/prop/theory_proxy.cpp
  src/smt/preprocess_proof_generator.cpp
  src/smt/proof_manager.cpp
  src/smt/proof_post_processor.cpp
  src/smt/set_defaults.cpp
  src/smt/smt_engine.cpp
  src/theory/arith/congruence_manager.h
  src/theory/arith/constraint.cpp
  src/theory/arith/proof_macros.h
  test/regress/regress0/arith/non-normal.smt2
Labels: moderate, normal

#5929 Move quantifiers attributes to quantifiers registry
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers/quantifiers_attributes.h
  src/theory/quantifiers/quantifiers_registry.cpp
  src/theory/quantifiers/quantifiers_registry.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers/term_util.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: minor, simple

#5933 Eliminate raw use of output channel and valuation in quantifiers
  src/theory/inference_id.h
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/cegqi/vts_term_cache.cpp
  src/theory/quantifiers/cegqi/vts_term_cache.h
  src/theory/quantifiers/ematching/ho_trigger.cpp
  src/theory/quantifiers/ematching/ho_trigger.h
  src/theory/quantifiers/ematching/inst_strategy_e_matching.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching_user.cpp
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/ematching/trigger.h
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/cegis.h
  src/theory/quantifiers/sygus/cegis_core_connective.cpp
  src/theory/quantifiers/sygus/cegis_core_connective.h
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/cegis_unif.h
  src/theory/quantifiers/sygus/sygus_module.cpp
  src/theory/quantifiers/sygus/sygus_module.h
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/sygus/sygus_pbe.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus_inst.cpp
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: moderate, normal

#5935 google test: preprocessing: Migrate pass_bv_gauss_white.
  test/unit/preprocessing/CMakeLists.txt
  test/unit/preprocessing/pass_bv_gauss_white.cpp
  test/unit/preprocessing/pass_bv_gauss_white.h
  test/unit/test_node.h
Labels: normal, simple

#5951 Explanation of failure for instantiate, use in enumerative instantiation
  src/theory/quantifiers/inst_strategy_enumerative.cpp
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/instantiate.h
Labels: moderate, normal

#5957 (proof-new) Add proof for transcendental secant lemmas
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/arith/nl/transcendental/proof_checker.cpp
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
  src/theory/arith/nl/transcendental/transcendental_state.cpp
Labels: moderate, normal

#5961 [proof-new] Fix handling of removable clauses in proof cnf stream
  src/prop/proof_cnf_stream.cpp
  src/prop/proof_cnf_stream.h
Labels: moderate, normal

#5964 (proof-new) Add proof generator for CAD solver
  src/CMakeLists.txt
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/arith/nl/cad/proof_checker.cpp
  src/theory/arith/nl/cad/proof_checker.h
  src/theory/arith/nl/cad/proof_generator.cpp
  src/theory/arith/nl/cad/proof_generator.h
Labels: moderate, normal

#5965 (proof-new) Add proof for nonlinear monomial bounds check
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/arith/nl/ext/monomial_bounds_check.cpp
  src/theory/arith/nl/ext/proof_checker.cpp
Labels: moderate, normal

#5963 [proof-new] Fix dangling pointer in SAT proof generation
  src/prop/sat_proof_manager.cpp
Labels: moderate, normal

#5966 (proof-new) Add proof for lemma about the sign of monomials
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/arith/nl/ext/monomial_check.cpp
  src/theory/arith/nl/ext/proof_checker.cpp
Labels: moderate, normal

#5976 google test: theory: Migrate strings_rewriter_white.
  test/unit/theory/CMakeLists.txt
  test/unit/theory/strings_rewriter_white.cpp
  test/unit/theory/strings_rewriter_white.h
Labels: normal, simple

#5974 google test: theory: Migrate regexp_operation_black.
  test/unit/theory/CMakeLists.txt
  test/unit/theory/regexp_operation_black.cpp
  test/unit/theory/regexp_operation_black.h
Labels: normal, simple

#5959 Switch to C++17.
  CMakeLists.txt
  src/expr/node.h
  src/main/signal_handlers.cpp
  src/main/signal_handlers.h
  src/util/utility.h
Labels: normal, simple

#5967 Add interface to TheoryState for sort inference and facts
  src/preprocessing/passes/sort_infer.cpp
  src/theory/model_manager.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.h
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/fmf/bounded_integers.h
  src/theory/quantifiers/fmf/model_builder.cpp
  src/theory/quantifiers/quantifiers_modules.cpp
  src/theory/quantifiers/quantifiers_modules.h
  src/theory/quantifiers/quantifiers_state.cpp
  src/theory/quantifiers/quantifiers_state.h
  src/theory/quantifiers/skolemize.cpp
  src/theory/quantifiers/skolemize.h
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers/term_database.h
  src/theory/quantifiers/theory_quantifiers.cpp
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
  src/theory/sort_inference.cpp
  src/theory/sort_inference.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/theory_model_builder.cpp
  src/theory/theory_model_builder.h
  src/theory/theory_state.cpp
  src/theory/theory_state.h
  src/theory/uf/cardinality_extension.cpp
  src/theory/uf/cardinality_extension.h
  src/theory/valuation.cpp
  src/theory/valuation.h
Labels: moderate, normal

#5968 Add state and inference manager to inst match generator
  src/theory/quantifiers/ematching/inst_match_generator.cpp
  src/theory/quantifiers/ematching/inst_match_generator.h
  src/theory/quantifiers/ematching/inst_match_generator_multi.cpp
  src/theory/quantifiers/ematching/inst_match_generator_multi.h
  src/theory/quantifiers/ematching/inst_match_generator_multi_linear.cpp
  src/theory/quantifiers/ematching/inst_match_generator_multi_linear.h
  src/theory/quantifiers/ematching/inst_match_generator_simple.cpp
  src/theory/quantifiers/ematching/inst_match_generator_simple.h
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/ematching/var_match_generator.cpp
  src/theory/quantifiers/ematching/var_match_generator.h
Labels: moderate, normal

#5971 google test: prop: Migrate cnf_stream_white.
  test/unit/prop/CMakeLists.txt
  test/unit/prop/cnf_stream_white.cpp
  test/unit/prop/cnf_stream_white.h
  test/unit/test_smt.h
Labels: normal, simple

#5972 google test: theory: Migrate evaluator_white.
  test/unit/theory/CMakeLists.txt
  test/unit/theory/evaluator_white.cpp
  test/unit/theory/evaluator_white.h
Labels: normal, simple

#5977 google test: theory: Migrate theory_arith_white.
  test/unit/test_smt.h
  test/unit/theory/CMakeLists.txt
  test/unit/theory/theory_arith_white.cpp
  test/unit/theory/theory_arith_white.h
Labels: normal, simple

#5979 google test: theory: Migrate theory_bags_rewriter_white.
  test/unit/theory/CMakeLists.txt
  test/unit/theory/theory_bags_rewriter_white.cpp
  test/unit/theory/theory_bags_rewriter_white.h
Labels: normal, simple

#5973 google test: theory: Migrate logic_info_white.
  test/unit/theory/CMakeLists.txt
  test/unit/theory/logic_info_white.cpp
  test/unit/theory/logic_info_white.h
Labels: normal, simple

#5978 google test: theory: Migrate theory_bags_normal_form_white.
  test/unit/theory/CMakeLists.txt
  test/unit/theory/theory_bags_normal_form_white.cpp
  test/unit/theory/theory_bags_normal_form_white.h
Labels: normal, simple

#5975 google test: theory: Migrate sequences_rewriter_white.
  test/unit/theory/CMakeLists.txt
  test/unit/theory/sequences_rewriter_white.cpp
  test/unit/theory/sequences_rewriter_white.h
Labels: normal, simple

#5981 (proof-new) Add proofs for CAD solver
  src/theory/arith/nl/cad/cdcac.cpp
  src/theory/arith/nl/cad/cdcac.h
  src/theory/arith/nl/cad_solver.cpp
  src/theory/arith/nl/cad_solver.h
  src/theory/arith/nl/nonlinear_extension.cpp
Labels: moderate, normal

#5982 Ensure static-learning adds rewritten assertions.
  src/preprocessing/passes/static_learning.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/preprocess/issue5729-rewritten-assertions.smt2
Labels: moderate, normal

#5985 google test: theory: Migrate theory_black.
  test/unit/theory/CMakeLists.txt
  test/unit/theory/theory_black.cpp
  test/unit/theory/theory_black.h
Labels: normal, simple

#5988 google test: theory: Migrate theory_engine_white.
  test/unit/test_smt.h
  test/unit/theory/CMakeLists.txt
  test/unit/theory/theory_engine_white.cpp
  test/unit/theory/theory_engine_white.h
Labels: normal, simple

#5984 google test: theory: Migrate theory_bags_type_rules_white.
  test/unit/theory/CMakeLists.txt
  test/unit/theory/theory_bags_type_rules_white.cpp
  test/unit/theory/theory_bags_type_rules_white.h
Labels: normal, simple

#5969 Enable -Werror.
  CMakeLists.txt
  src/api/cvc4cpp.cpp
  src/api/python/CMakeLists.txt
  src/expr/node_trie.cpp
  src/parser/CMakeLists.txt
  src/preprocessing/passes/bv_to_int.cpp
  src/theory/arith/nl/poly_conversion.cpp
  src/theory/arrays/theory_arrays.cpp
  src/theory/booleans/circuit_propagator.cpp
  src/theory/booleans/circuit_propagator.h
  src/theory/booleans/proof_checker.cpp
  src/theory/quantifiers/ematching/inst_match_generator_simple.cpp
  src/theory/quantifiers/skolemize.cpp
  src/util/real_algebraic_number_poly_imp.cpp
  test/unit/theory/logic_info_white.cpp
Labels: major, moderate

#5970 google test: printer: Migrate smt2_printer_black.
  test/unit/printer/CMakeLists.txt
  test/unit/printer/smt2_printer_black.cpp
  test/unit/printer/smt2_printer_black.h
Labels: normal, simple

#5986 google test: theory: Migrate theory_bv_rewriter_white.
  test/unit/theory/CMakeLists.txt
  test/unit/theory/theory_bv_rewriter_white.cpp
  test/unit/theory/theory_bv_rewriter_white.h
Labels: normal, simple

#5987 google test: theory: Migrate theory_bv_white.
  test/unit/theory/CMakeLists.txt
  test/unit/theory/theory_bv_white.cpp
  test/unit/theory/theory_bv_white.h
Labels: normal, simple

#5994 Add regression
  test/regress/CMakeLists.txt
  test/regress/regress0/issue5187-div-justification.smt2
Labels: normal, simple

#5998 google test: Merge Node(Manager) fixtures.
  test/unit/expr/node_algorithm_black.cpp
  test/unit/expr/node_black.cpp
  test/unit/expr/node_builder_black.cpp
  test/unit/expr/node_manager_black.cpp
  test/unit/expr/node_manager_white.cpp
  test/unit/expr/node_self_iterator_black.cpp
  test/unit/expr/node_traversal_black.cpp
  test/unit/expr/node_white.cpp
  test/unit/expr/type_node_white.cpp
  test/unit/test_node.h
Labels: normal, simple

#5997 Datatypes lemmas: share only external types
  src/theory/datatypes/theory_datatypes.cpp
Labels: performance

#5999 Move slow regressions to regress1
  test/regress/CMakeLists.txt
  test/regress/regress1/arith/issue3480.smt2
  test/regress/regress1/aufbv/fuzz03.smtv1.smt2
  test/regress/regress1/bv/fuzz18.smtv1.smt2
  test/regress/regress1/bv/fuzz19.smtv1.smt2
  test/regress/regress1/decision/bug374a.smtv1.smt2
  test/regress/regress1/fp/rti_3_5_bug_report.smt2
  test/regress/regress1/nl/ext-rew-aggr-test.smt2
  test/regress/regress1/quantifiers/sygus-inst-nia-psyco-060.smt2
  test/regress/regress1/quantifiers/sygus-inst-ufnia-sat-t3_rw1505.smt2
  test/regress/regress1/sygus/array-grammar-store.sy
  test/regress/regress1/uflia/error1.smtv1.smt2
Labels: normal, simple

#5992 Move (optional) rewrite from TrustSubstitutionMap to SubstitutionMap.
  src/preprocessing/passes/non_clausal_simp.cpp
  src/theory/substitutions.cpp
  src/theory/substitutions.h
  src/theory/trust_substitutions.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/preprocess/issue5943-non-clausal-simp.smt2
Labels: moderate, normal

#5958 (proof-new) Fix regular expression unfolding under substitution
  src/theory/strings/infer_proof_cons.cpp
Labels: moderate, normal

#5993 Store Node instead of TNode in justification heuristic
  src/decision/justification_heuristic.h
Labels: moderate, normal

#6010 Optionally permit creation of non-flat function types
  src/expr/node_manager.cpp
  src/expr/node_manager.h
Labels: normal, simple

#6009 Minor improvement and fix to smt2 printer
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
Labels: normal, simple

#6011 google test: util: Migrate assert_white.
  test/unit/util/CMakeLists.txt
  test/unit/util/assert_white.cpp
  test/unit/util/assert_white.h
Labels: normal, simple

#6004 Fix -Werror issues with clang and use clang for debug-cln build.
  .github/workflows/ci.yml
  test/unit/CMakeLists.txt
  test/unit/theory/theory_white.h
Labels: major, simple

#6000 google test: theory: Migrate theory_sets_type_enumerator_white.
  test/unit/theory/CMakeLists.txt
  test/unit/theory/evaluator_white.cpp
  test/unit/theory/regexp_operation_black.cpp
  test/unit/theory/sequences_rewriter_white.cpp
  test/unit/theory/strings_rewriter_white.cpp
  test/unit/theory/theory_bags_normal_form_white.cpp
  test/unit/theory/theory_bags_rewriter_white.cpp
  test/unit/theory/theory_bags_type_rules_white.cpp
  test/unit/theory/theory_black.cpp
  test/unit/theory/theory_bv_rewriter_white.cpp
  test/unit/theory/theory_bv_white.cpp
  test/unit/theory/theory_engine_white.cpp
  test/unit/theory/theory_sets_type_enumerator_white.cpp
  test/unit/theory/theory_sets_type_enumerator_white.h
Labels: normal, simple

#6001 google test: theory: Migrate theory_sets_type_rules_white.
  test/unit/theory/CMakeLists.txt
  test/unit/theory/theory_sets_type_rules_white.cpp
  test/unit/theory/theory_sets_type_rules_white.h
Labels: normal, simple

#6022 Some formatting and better tracing in prop engine
  src/prop/minisat/core/Solver.cc
  src/prop/sat_solver_types.h
Labels: minor, simple

#6007 google test: theory: Migrate type_enumerator_white.
  test/unit/theory/CMakeLists.txt
  test/unit/theory/type_enumerator_white.cpp
  test/unit/theory/type_enumerator_white.h
Labels: normal, simple

#6006 google test: theory: Migrate theory_white.
  src/CMakeLists.txt
  src/theory/theory_test_utils.h
  test/unit/test_smt.h
  test/unit/theory/CMakeLists.txt
  test/unit/theory/evaluator_white.cpp
  test/unit/theory/theory_arith_white.cpp
  test/unit/theory/theory_bv_white.cpp
  test/unit/theory/theory_engine_white.cpp
  test/unit/theory/theory_white.cpp
  test/unit/theory/theory_white.h
Labels: normal, simple

#6016 google test: util: Migrate cardinality_black.
  test/unit/util/CMakeLists.txt
  test/unit/util/cardinality_black.cpp
  test/unit/util/cardinality_public.h
Labels: normal, simple

#6017 google test: util: Migrate check_white.
  test/unit/util/CMakeLists.txt
  test/unit/util/check_white.cpp
Labels: normal, simple

#6020 google test: util: Migrate exception_black.
  test/unit/util/CMakeLists.txt
  test/unit/util/exception_black.cpp
  test/unit/util/exception_black.h
Labels: normal, simple
