Repository cvc5/cvc5, pull requests merged in 2021-04, with the labels that each got.

#6172 Make ResetCommand go through APISolver
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/smt/command.cpp
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
Labels: normal, simple

#6252 Fix non-linear for unknown case
  src/theory/arith/nl/nonlinear_extension.cpp
Labels: major, simple

#6250 Add debug traces to theory inference manager
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
Labels: minor, simple

#6253 kinds: Remove non-existent properties.
  src/theory/bags/kinds
  src/theory/mktheorytraits
Labels: normal, simple

#6251 Refactor CLN dependency & Cleanup
  CMakeLists.txt
  cmake/FindANTLR3.cmake
  cmake/FindCLN.cmake
  cmake/FindCaDiCaL.cmake
  cmake/FindCryptoMiniSat.cmake
  cmake/FindDummy.cmake.template
  cmake/FindGMP.cmake
  cmake/FindGTest.cmake
  cmake/FindKissat.cmake
  cmake/FindPoly.cmake
  cmake/FindSymFPU.cmake
  cmake/deps-helper.cmake
  cmake/deps-utils/Poly-patch-cmake.patch
  configure.sh
  src/CMakeLists.txt
  src/api/python/CMakeLists.txt
  src/main/CMakeLists.txt
  test/api/CMakeLists.txt
  test/unit/CMakeLists.txt
Labels: moderate, normal

#6263 Delete hashsmt example.
  examples/CMakeLists.txt
  examples/hashsmt/CMakeLists.txt
  examples/hashsmt/sha1.hpp
  examples/hashsmt/sha1_collision.cpp
  examples/hashsmt/sha1_inversion.cpp
  examples/hashsmt/word.cpp
  examples/hashsmt/word.h
Labels: normal, simple

#6264 Add regression for issue 6191
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue6191-replace-all.smt2
Labels: minor, simple

#6257 Fix type rule for to_real
  src/api/cvc4cpp.cpp
  src/parser/tptp/tptp.cpp
  src/theory/arith/theory_arith_type_rules.h
  test/unit/api/sort_black.cpp
Labels: moderate, normal

#6246 FP: Factor out symfpu traits.
  src/api/checks.h
  src/util/CMakeLists.txt
  src/util/floatingpoint_literal_symfpu.cpp
  src/util/floatingpoint_literal_symfpu.h.in
  src/util/floatingpoint_literal_symfpu_traits.cpp
  src/util/floatingpoint_literal_symfpu_traits.h.in
Labels: normal, simple

#6262 Simplify caching of regular expression unfolding
  src/theory/strings/extf_solver.cpp
  src/theory/strings/extf_solver.h
  src/theory/strings/regexp_solver.cpp
  src/theory/strings/theory_strings.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue6203-2-re-ccache.smt2
Labels: moderate, normal

#6178 Add utility classes for new statistics
  src/base/configuration.cpp
  src/base/configuration.h
  src/base/configuration_private.h
  src/util/CMakeLists.txt
  src/util/statistics_stats.cpp
  src/util/statistics_stats.h
  src/util/statistics_value.cpp
  src/util/statistics_value.h
Labels: moderate, normal

#6272 Avoid redirect to file in CaDiCaL build
  cmake/FindCaDiCaL.cmake
Labels: major, simple

#6267 Fix case where RE unfolding generates a trivially true lemma
  src/theory/strings/regexp_solver.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/issue6203-3-unfold-trivial-true.smt2
Labels: normal, simple

#6254 Cleaning up friend relationships for commands
  src/api/cvc4cpp.h
  src/smt/command.cpp
  src/smt/command.h
Labels: minor, simple

#6273 Some refactoring of statistics in CommandExecutor and SmtEngine
  src/api/cvc4cpp.cpp
  src/main/command_executor.cpp
  src/main/command_executor.h
  src/main/main.cpp
  src/main/signal_handlers.cpp
  src/smt/env.cpp
  src/smt/env.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/smt/smt_engine_scope.cpp
Labels: moderate, normal

#6210 New statistics registry
  src/options/base_options.toml
  src/options/options_public_functions.cpp
  src/util/CMakeLists.txt
  src/util/statistics_public.cpp
  src/util/statistics_public.h
  src/util/statistics_reg.cpp
  src/util/statistics_reg.h
Labels: moderate, normal

#6269 cmake: Do not link against main object library.
  src/main/CMakeLists.txt
  src/main/command_executor.cpp
  src/main/command_executor.h
  src/main/driver_unified.cpp
  src/main/signal_handlers.cpp
Labels: major

#6265 Add cache for new dependencies folder.
  .github/workflows/ci.yml
Labels: moderate, normal

#6266 Disable substring component contains in strip endpoints
  src/theory/strings/strings_entail.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue6203-1-substr-ctn-strip.smt2
  test/unit/theory/sequences_rewriter_white.cpp
Labels: major, simple

#6213 Optimizer for BitVectors
  src/CMakeLists.txt
  src/omt/bitvector_optimizer.cpp
  src/omt/bitvector_optimizer.h
  src/omt/integer_optimizer.cpp
  src/omt/integer_optimizer.h
  src/omt/omt_optimizer.cpp
  src/omt/omt_optimizer.h
  src/smt/optimization_solver.cpp
  src/smt/optimization_solver.h
  test/unit/theory/CMakeLists.txt
  test/unit/theory/theory_bv_opt_white.cpp
  test/unit/theory/theory_int_opt_white.cpp
Labels: feature

#6256 Add interface for skolem functions in SkolemManager
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/theory/arith/operator_elim.cpp
  src/theory/arith/operator_elim.h
Labels: moderate, normal

#6278 Fix subtyping for sets care graph
  src/theory/sets/theory_sets_private.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sets/issue5705-cg-subtyping.smt2
Labels: normal, simple

#6261 Fix Issue #6260 type casting in mkBitVector
  src/api/python/cvc4.pxd
  src/api/python/cvc4.pxi
Labels: major

#6282 Enable UF when pre-skolem nested option is enabled
  src/smt/set_defaults.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue4328-nqe.smt2
Labels: minor, simple

#6275 [proof-new] Registering proof checkers uniformly from the SMT solver
  src/smt/smt_solver.cpp
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
  src/theory/arrays/theory_arrays.cpp
  src/theory/arrays/theory_arrays.h
  src/theory/bags/theory_bags.cpp
  src/theory/bags/theory_bags.h
  src/theory/booleans/theory_bool.cpp
  src/theory/booleans/theory_bool.h
  src/theory/builtin/theory_builtin.cpp
  src/theory/builtin/theory_builtin.h
  src/theory/bv/bv_solver_simple.cpp
  src/theory/bv/bv_solver_simple.h
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp.h
  src/theory/quantifiers/theory_quantifiers.cpp
  src/theory/quantifiers/theory_quantifiers.h
  src/theory/sep/theory_sep.cpp
  src/theory/sep/theory_sep.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf.h
  test/unit/test_smt.h
Labels: moderate, normal

#6287 Add benchmark for issue 4412
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue4412-cegqi-type.smt2
Labels: minor, simple

#6284 Fix spurious antecedant for symbolic regular expressions
  src/theory/strings/regexp_solver.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue6271-2-rnf.smt2
  test/regress/regress1/strings/issue6271-rnf.smt2
Labels: major, simple

#6268 Add documentation for theory_bags_type_rules.h
  src/theory/bags/theory_bags_type_rules.h
Labels: minor, simple

#6294 parsekinds: Remove DEFAULT_HEADER.
  src/api/java/genkinds.py
  src/api/parsekinds.py
  src/api/python/genkinds.py.in
Labels: normal, simple

#6280 Remove stdPrintAscii option
  src/options/strings_options.toml
  src/theory/strings/theory_strings_type_rules.h
  src/theory/strings/theory_strings_utils.cpp
  test/regress/regress1/strings/re-unsound-080718.smt2
Labels: minor, simple

#6293 genkinds: Do not use relative paths to find src directory.
  src/api/java/CMakeLists.txt
  src/api/java/genkinds.py.in
Labels: normal, simple

#6289 Fix issue with lemma during equality engine iterator in sets
  src/theory/sets/theory_sets_private.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sets/issue4370-2-lemma-ee-iter.smt2
  test/regress/regress1/sets/issue4370-4-lemma-ee-iter.smt2
Labels: normal, simple

#6297 Fix tptp parser for negative rational
  src/parser/tptp/Tptp.g
  test/regress/CMakeLists.txt
  test/regress/regress0/tptp/parse-neg-rational.p
Labels: normal, simple

#6296 Add benchmark for issue 5942
  test/regress/CMakeLists.txt
  test/regress/regress1/sets/issue5942-witness.smt2
Labels: minor, simple

#6300 cmake: Do not always regenerate cvc4kinds.{pxi,pxd}.
  src/api/python/CMakeLists.txt
Labels: normal, simple

#6295 New C++ Api: Initial setup of Api documentation.
  CMakeLists.txt
  INSTALL.md
  cmake/FindSphinx.cmake
  configure.sh
  docs/CMakeLists.txt
  docs/Doxyfile.in
  docs/conf.py
  docs/index.rst
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/cpp/cvc5_kind.h
Labels: normal, simple

#6243 Add term pools utility
  src/CMakeLists.txt
  src/theory/quantifiers/term_pools.cpp
  src/theory/quantifiers/term_pools.h
  src/theory/quantifiers/term_registry.cpp
  src/theory/quantifiers/term_registry.h
Labels: moderate, normal

#6285 (proof-new) Proper implementation of proof node cloning
  src/expr/proof_node.cpp
  src/expr/proof_node.h
  src/expr/proof_node_manager.cpp
  src/expr/proof_node_manager.h
  src/smt/proof_manager.cpp
  src/theory/uf/proof_equality_engine.cpp
Labels: moderate, normal

#6306 New C++ Api: Rename and move checks.h.
  src/CMakeLists.txt
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_checks.h
Labels: normal, simple

#6279 Fixes for abducts
  src/smt/smt_engine.cpp
  src/theory/quantifiers/sygus/sygus_abduct.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  test/regress/regress1/sygus/issue5848-3-trivial-no-abduct.smt2
Labels: minor, simple

#6281 Set incomplete if not applying ho extensionality
  src/theory/uf/ho_extension.cpp
Labels: minor, simple

#6286 Add benchmark for issue 4420
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue4420-order-sensitive.smt2
Labels: normal, simple

#6277 [proof-new] Fixing SMT post-processor's handling of assumptions
  src/expr/proof_node_updater.cpp
  src/expr/proof_node_updater.h
  src/options/proof_options.toml
  src/prop/proof_post_processor.cpp
  src/prop/proof_post_processor.h
  src/smt/proof_manager.cpp
  src/smt/proof_post_processor.cpp
  src/smt/proof_post_processor.h
  test/regress/CMakeLists.txt
  test/regress/regress0/proofs/scope.smt2
Labels: moderate, normal

#6283 Add benchmark for 6270
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue6270.smt2
Labels: minor, simple

#6302 Add cardinality class definition
  src/util/cardinality_class.cpp
  src/util/cardinality_class.h
Labels: moderate, normal

#6309 Remove old API header.
  src/include/cvc4.h
Labels: normal, simple

#6304 Initial support for parametric datatypes in sygus
  src/expr/dtype_cons.cpp
  src/parser/smt2/Smt2.g
  src/theory/quantifiers/single_inv_partition.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/sygus/issue6298-par.sy
Labels: normal, simple

#6288 Add benchmark for issue 4400
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue4400-2-already-conf.smt2
Labels: minor, simple

#6301 Add benchmark for issue 5101
  test/regress/CMakeLists.txt
  test/regress/regress1/issue5101-alira-subtypes.smt2
Labels: minor, simple

#6311 Add identifiers for sources of incompleteness
  src/CMakeLists.txt
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/theory_arith.cpp
  src/theory/engine_output_channel.cpp
  src/theory/engine_output_channel.h
  src/theory/incomplete_id.cpp
  src/theory/incomplete_id.h
  src/theory/inference_id.h
  src/theory/output_channel.h
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.h
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/fmf/model_engine.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/instantiate.h
  src/theory/quantifiers/quant_module.h
  src/theory/quantifiers/quant_util.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers_engine.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
  src/theory/strings/core_solver.cpp
  src/theory/strings/inference_manager.cpp
  src/theory/strings/inference_manager.h
  src/theory/strings/regexp_solver.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
  src/theory/uf/cardinality_extension.cpp
  src/theory/uf/ho_extension.cpp
  src/theory/uf/theory_uf.cpp
  test/unit/test_smt.h
Labels: moderate, normal

#6315 Use newer version of update-pr-branch action.
  .github/workflows/update_pr.yml
Labels: minor, simple

#6317 Fix run_regression for cvc expected outputs
  test/regress/regress0/datatypes/datatype1.cvc
  test/regress/regress0/datatypes/datatype3.cvc
  test/regress/regress0/datatypes/wrong-sel-simp.cvc
  test/regress/run_regression.py
Labels: normal, simple

#6320 Add missing InferenceIds to toString
  src/theory/inference_id.cpp
Labels: normal, simple

#6321 Enable expr miner timeout
  src/theory/quantifiers/expr_miner.cpp
Labels: normal, simple

#6318 Avoid spurious runs in run_regression.py
  test/regress/run_regression.py
Labels: minor, simple

#6323 Learn equalities involving Boolean variables
  src/theory/booleans/circuit_propagator.cpp
  src/theory/theory.cpp
  test/regress/CMakeLists.txt
Labels: normal, simple

#6305 Add regressions for issue 6214
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue6214-2-sym-re-inc.smt2
  test/regress/regress1/strings/issue6214-3-sym-re-inc.smt2
  test/regress/regress1/strings/issue6214-4-sym-re-inc.smt2
Labels: minor, simple

#6314 Add identifiers for extended function reductions
  src/theory/arith/nl/ext_theory_callback.cpp
  src/theory/arith/nl/ext_theory_callback.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/ext_theory.cpp
  src/theory/ext_theory.h
  src/theory/strings/extf_solver.cpp
  src/theory/strings/inference_manager.cpp
  src/theory/strings/inference_manager.h
  src/theory/strings/regexp_solver.cpp
Labels: moderate, normal

#6324 [proof-new] Optimizing sat proof
  src/expr/lazy_proof_chain.cpp
  src/expr/proof_rule.h
  src/prop/sat_proof_manager.cpp
  src/prop/sat_proof_manager.h
  src/smt/proof_manager.cpp
  src/smt/proof_post_processor.cpp
  src/theory/booleans/proof_checker.cpp
Labels: normal, simple

#6325 New C++ Api: Initial layout of Api documentation.
  docs/conf.py
  docs/cpp.rst
  docs/cpp/datatype.rst
  docs/cpp/datatypeconstructor.rst
  docs/cpp/datatypeconstructordecl.rst
  docs/cpp/datatypedecl.rst
  docs/cpp/datatypeselector.rst
  docs/cpp/grammar.rst
  docs/cpp/kind.rst
  docs/cpp/op.rst
  docs/cpp/result.rst
  docs/cpp/roundingmode.rst
  docs/cpp/solver.rst
  docs/cpp/sort.rst
  docs/cpp/term.rst
  docs/index.rst
  src/api/cpp/cvc5.h
Labels: normal, simple

#6331 Fix GitHub Actions macOS build
  .github/workflows/ci.yml
Labels: major, simple

#6189 Consolidate interface to prop engine
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
  src/smt/smt_solver.cpp
Labels: moderate, normal

#6332 Only require GMP 6.1
  CMakeLists.txt
Labels: minor, simple

#6322 Refactor resource manager
  src/decision/decision_engine.cpp
  src/options/mkoptions.py
  src/options/options.h
  src/options/options_handler.cpp
  src/options/options_handler.h
  src/options/options_public_functions.cpp
  src/options/smt_options.toml
  src/preprocessing/passes/apply_substs.cpp
  src/preprocessing/passes/bool_to_bv.cpp
  src/preprocessing/passes/bv_to_bool.cpp
  src/preprocessing/passes/ite_removal.cpp
  src/preprocessing/passes/ite_simp.cpp
  src/preprocessing/passes/non_clausal_simp.cpp
  src/preprocessing/passes/static_learning.cpp
  src/preprocessing/passes/theory_preprocess.cpp
  src/preprocessing/passes/unconstrained_simplifier.cpp
  src/preprocessing/preprocessing_pass_context.h
  src/prop/bv_sat_solver_notify.h
  src/prop/bvminisat/bvminisat.h
  src/prop/bvminisat/core/Solver.cc
  src/prop/bvminisat/core/Solver.h
  src/prop/cnf_stream.cpp
  src/prop/minisat/core/Solver.cc
  src/prop/minisat/core/Solver.h
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
  src/smt/expand_definitions.cpp
  src/smt/process_assertions.cpp
  src/smt/process_assertions.h
  src/smt/smt_engine.cpp
  src/smt/smt_solver.cpp
  src/theory/arith/theory_arith_private.cpp
  src/theory/bv/bitblast/bitblaster.h
  src/theory/bv/bitblast/eager_bitblaster.cpp
  src/theory/bv/bitblast/lazy_bitblaster.cpp
  src/theory/bv/bitblast/lazy_bitblaster.h
  src/theory/bv/bv_eager_solver.cpp
  src/theory/bv/bv_solver_lazy.cpp
  src/theory/bv/bv_solver_lazy.h
  src/theory/bv/bv_subtheory_bitblast.cpp
  src/theory/bv/bv_subtheory_core.cpp
  src/theory/bv/bv_subtheory_inequality.cpp
  src/theory/engine_output_channel.cpp
  src/theory/engine_output_channel.h
  src/theory/output_channel.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/rewriter.cpp
  src/theory/theory.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
  src/util/resource_manager.cpp
  src/util/resource_manager.h
  test/unit/test_smt.h
Labels: moderate, normal

#6312 Fix computation of whether a type is finite
  src/api/cpp/cvc5.cpp
  src/expr/dtype.cpp
  src/expr/dtype.h
  src/expr/dtype_cons.cpp
  src/expr/dtype_cons.h
  src/expr/type_node.cpp
  src/expr/type_node.h
  src/theory/datatypes/sygus_extension.cpp
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/type_enumerator.cpp
  src/theory/datatypes/type_enumerator.h
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/quant_bound_inference.cpp
  src/theory/quantifiers/quant_split.cpp
  src/theory/quantifiers/sygus/sygus_enumerator.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/sets/cardinality_extension.cpp
  src/theory/strings/base_solver.cpp
  src/theory/term_registration_visitor.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/theory_model_builder.cpp
  src/theory/theory_model_builder.h
  src/theory/theory_state.cpp
  src/theory/theory_state.h
  src/theory/uf/ho_extension.cpp
  src/theory/valuation.cpp
  src/theory/valuation.h
  src/util/CMakeLists.txt
  test/regress/regress0/fmf/issue4260-arrays-card-one.smt2
Labels: moderate, normal

#6334 Strings: Move implementation of type rules from header to .cpp file.
  src/CMakeLists.txt
  src/theory/strings/theory_strings_type_rules.cpp
  src/theory/strings/theory_strings_type_rules.h
Labels: normal, simple

#6336 Bags: Move more implementation of type rule from header to .cpp.
  src/theory/bags/theory_bags_type_rules.cpp
  src/theory/bags/theory_bags_type_rules.h
Labels: normal, simple

#6329 Fix sexpr bug with AST output language.
  src/api/cpp/cvc5.cpp
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  test/regress/CMakeLists.txt
  test/regress/regress0/options/ast-and-sexpr.smt2
Labels: bug, normal, simple

#6328 Avoid using substitute's input cache after the method call.
  src/theory/quantifiers/sygus/sygus_reconstruct.cpp
Labels: bug, normal, simple

#6335 API docs: Add custom target to build for GH pages.
  INSTALL.md
  docs/CMakeLists.txt
Labels: normal, simple

#6307 Formalize more skolems
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/theory/datatypes/infer_proof_cons.cpp
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
  src/theory/strings/skolem_cache.cpp
  src/theory/strings/skolem_cache.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings_preprocess.cpp
Labels: moderate, normal

#6347 ci: Use CVC5_REGRESSION_ARGS.
  .github/workflows/ci.yml
Labels: major, simple

#6348 Refactor quantifiers macros
  src/preprocessing/passes/quantifier_macros.cpp
  src/preprocessing/passes/quantifier_macros.h
  test/regress/CMakeLists.txt
  test/regress/regress0/quantifiers/macro-back-subs-sat.smt2
Labels: moderate, normal

#6308 Add pool instantiation strategy
  src/CMakeLists.txt
  src/options/quantifiers_options.toml
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/quantifiers/inst_strategy_pool.cpp
  src/theory/quantifiers/inst_strategy_pool.h
  src/theory/quantifiers/quant_util.h
  src/theory/quantifiers/quantifiers_modules.cpp
  src/theory/quantifiers/quantifiers_modules.h
  src/theory/quantifiers/term_tuple_enumerator.cpp
  src/theory/quantifiers/term_tuple_enumerator.h
Labels: moderate, normal

#6354 Fix libpoly build and use new release
  cmake/FindPoly.cmake
Labels: major, simple

#6342 [proof-new] Miscellaneous improvements to dot printer
  src/proof/dot/dot_printer.cpp
Labels: minor, simple

#6346 [proof-new] Fix explanation of literals in SAT proof manager
  src/expr/buffered_proof_generator.cpp
  src/expr/buffered_proof_generator.h
  src/prop/sat_proof_manager.cpp
Labels: moderate, normal

#6345 Warn about infeasible SyGuS conjectures
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  test/regress/regress0/sygus/pbe-pred-contra.sy
  test/regress/regress0/sygus/univ_3-long-repeat-conflict.sy
  test/regress/regress1/issue3970-nl-ext-purify.smt2
  test/regress/regress1/sygus/issue3201.smt2
  test/regress/regress1/sygus/issue3247.smt2
  test/regress/regress1/sygus/issue3649.sy
  test/regress/regress1/sygus/issue4009-qep.smt2
  test/regress/regress1/sygus/issue4083-var-shadow.smt2
Labels: normal, simple

#6353 Merge equivalent sub-obligations instead of discarding them.
  src/theory/quantifiers/sygus/rcons_obligation_info.cpp
  src/theory/quantifiers/sygus/rcons_obligation_info.h
  src/theory/quantifiers/sygus/sygus_reconstruct.cpp
  src/theory/quantifiers/sygus/sygus_reconstruct.h
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/eq-sub-obs.sy
Labels: moderate, normal

#5131 Add interface for getting relevant assertions
  src/theory/relevance_manager.cpp
  src/theory/relevance_manager.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: minor, simple

#6350 Add internal API methods for pool-based instantiation
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/theory/quantifiers/inst_strategy_pool.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers/quantifiers_attributes.h
  src/theory/quantifiers/quantifiers_inference_manager.cpp
  src/theory/quantifiers/skolemize.cpp
  src/theory/quantifiers/skolemize.h
  src/theory/quantifiers/term_pools.cpp
  src/theory/quantifiers/term_pools.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: moderate, normal

#6356 [unsat-cores] Improving new unsat cores
  src/api/cpp/cvc5.cpp
  src/options/smt_options.toml
  src/preprocessing/assertion_pipeline.cpp
  src/preprocessing/passes/ite_removal.cpp
  src/preprocessing/passes/quantifier_macros.cpp
  src/prop/minisat/core/Solver.cc
  src/prop/proof_cnf_stream.cpp
  src/prop/proof_cnf_stream.h
  src/prop/prop_engine.cpp
  src/prop/theory_proxy.cpp
  src/smt/assertions.cpp
  src/smt/proof_manager.cpp
  src/smt/proof_manager.h
  src/smt/set_defaults.cpp
  src/smt/smt_engine.cpp
  src/smt/smt_solver.cpp
  src/smt/smt_solver.h
  src/theory/theory_engine.cpp
Labels: moderate, normal

#6357 Extend conversion
  src/CMakeLists.txt
  src/expr/proof_rule.h
  src/options/proof_options.toml
  src/proof/verit/verit_post_processor.cpp
  src/proof/verit/verit_post_processor.h
  src/proof/verit/verit_printer.cpp
  src/proof/verit/verit_printer.h
  src/proof/verit/verit_proof_rule.cpp
  src/proof/verit/verit_proof_rule.h
  src/smt/proof_manager.cpp
Labels: normal

#6340 Improve documentation for API exceptions
  docs/cpp.rst
  docs/cpp/exceptions.rst
  src/api/cpp/cvc5.h
Labels: moderate, normal

#6341 Improve documentation of API kinds
  docs/CMakeLists.txt
  docs/cpp/kind.rst
  src/api/cpp/cvc5_kind.h
Labels: moderate, normal

#6343 Improve documentation for FP rounding mode, add bibliography
  docs/conf.py
  docs/cpp/roundingmode.rst
  docs/index.rst
  docs/references.bib
  docs/references.rst
  src/api/cpp/cvc5.h
Labels: moderate, normal

#6349 Fix type rule for relations join image
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_type_rules.h
Labels: minor, simple

#6367 Reenable regression for minimizing instantiations
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/dump-inst-proof.smt2
Labels: normal, simple

#6362 Fix printing of stats when aborted.
  src/api/cpp/cvc5.cpp
  src/expr/kind_template.cpp
  src/expr/kind_template.h
  src/expr/mkkind
  src/options/base_options.toml
  src/options/options_handler.cpp
  src/options/options_handler.h
  src/util/statistics_registry.cpp
  src/util/statistics_value.h
Labels: moderate, normal

#6366 Clean up interaction of resource manager and its options
  src/options/smt_options.toml
  src/smt/options_manager.cpp
  src/smt/options_manager.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/util/resource_manager.cpp
  src/util/resource_manager.h
Labels: minor, moderate

#6368 Build support library from base and context.
  src/CMakeLists.txt
  src/base/CMakeLists.txt
  src/context/CMakeLists.txt
  src/prop/bvminisat/mtl/config.mk
  src/prop/bvminisat/mtl/template.mk
  src/prop/minisat/mtl/config.mk
  src/prop/minisat/mtl/template.mk
Labels: normal, simple

#6370 preprocessing context: Add wrapper for model substitutions.
  src/preprocessing/passes/bv_eager_atoms.cpp
  src/preprocessing/passes/miplib_trick.cpp
  src/preprocessing/passes/non_clausal_simp.cpp
  src/preprocessing/preprocessing_pass_context.cpp
  src/preprocessing/preprocessing_pass_context.h
  test/regress/CMakeLists.txt
  test/regress/regress0/datatypes/v3l60006.cvc
  test/regress/regress0/issue5473.smt2
Labels: normal, simple

#6374 cmake: Build object libraries for base and context.
  src/CMakeLists.txt
  src/base/CMakeLists.txt
  src/context/CMakeLists.txt
Labels: major, simple

#6363 Replace SExpr class by simpler conversion routines
  src/api/cpp/cvc5.cpp
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/util/sexpr.cpp
  src/util/sexpr.h
Labels: moderate, normal

#6355 Refactor cmake: auto-download and default-on dependencies
  .github/workflows/ci.yml
  CMakeLists.txt
  cmake/FindANTLR3.cmake
  cmake/FindCLN.cmake
  cmake/FindCaDiCaL.cmake
  cmake/FindCryptoMiniSat.cmake
  cmake/FindGMP.cmake
  cmake/FindGTest.cmake
  cmake/FindKissat.cmake
  cmake/FindPoly.cmake
  cmake/FindSymFPU.cmake
  cmake/deps-helper.cmake
  configure.sh
Labels: moderate, normal

#5887 Add assumption-based unsat cores.
  src/expr/proof_rule.h
  src/options/smt_options.toml
  src/prop/minisat/core/Solver.cc
  src/prop/minisat/core/Solver.h
  src/prop/minisat/minisat.cpp
  src/prop/minisat/minisat.h
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/smt/set_defaults.cpp
  src/smt/smt_engine.cpp
  src/theory/booleans/proof_checker.cpp
  test/regress/run_regression.py
Labels: major, moderate

#6372 Fix term conversion generator policy ONCE for post-rewrite
  src/expr/term_conversion_proof_generator.cpp
Labels: normal, simple

#6378 Fix dependencies for stats options
  src/options/options_handler.cpp
Labels: normal, simple

#6376 Remove linking against gmp and cln in tests and parser
  src/parser/CMakeLists.txt
  src/parser/antlr_input.h
  src/parser/cvc/Cvc.g
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/parser/tptp/Tptp.g
  test/api/CMakeLists.txt
Labels: normal, simple

#6394 Fully incorporate quantifiers macros into ppAssert / non-clausal simplification
  src/CMakeLists.txt
  src/preprocessing/passes/quantifier_macros.cpp
  src/preprocessing/passes/quantifier_macros.h
  src/preprocessing/preprocessing_pass_registry.cpp
  src/smt/process_assertions.cpp
  src/theory/quantifiers/quantifiers_macros.cpp
  src/theory/quantifiers/quantifiers_macros.h
  src/theory/quantifiers/theory_quantifiers.cpp
  src/theory/quantifiers/theory_quantifiers.h
  src/theory/theory_model.cpp
  test/regress/regress0/quantifiers/issue2033-macro-arith.smt2
  test/regress/regress0/quantifiers/macro-back-subs-sat.smt2
Labels: moderate, normal

#6361 python API sorts: adding functions and tests
  src/api/python/cvc4.pxd
  src/api/python/cvc4.pxi
  test/api/python/CMakeLists.txt
  test/api/python/test_sort.py
  test/python/CMakeLists.txt
  test/python/unit/api/test_sort.py
Labels: feature

#6399 Fix `ANTLR3_COMMAND` for system ANTLR3 JAR
  cmake/FindANTLR3.cmake
Labels: normal, simple

#6375 Add guards to disable clang-format around placeholders in templates.
  src/expr/kind_template.cpp
  src/expr/kind_template.h
  src/expr/metakind_template.cpp
  src/expr/metakind_template.h
  src/expr/type_checker_template.cpp
  src/expr/type_properties_template.h
  src/options/options_template.cpp
  src/theory/rewriter_tables_template.h
  src/theory/theory_traits_template.h
  src/theory/type_enumerator_template.cpp
Labels: normal, simple

#6383 Basic setup for examples in documentation
  docs/conf.py
  docs/examples/datatypes.rst
  docs/examples/examples.rst
  docs/examples/helloworld.rst
  docs/examples/lineararith.rst
  docs/ext/examples.py
  docs/index.rst
Labels: moderate, normal

#6369 Remove support for CVC3 language.
  examples/api/combination.cpp
  examples/api/python/combination.py
  src/options/language.cpp
  src/options/language.h
  src/options/options_template.cpp
  src/printer/printer.cpp
  test/api/ouroborous.cpp
Labels: normal, simple

#6365 Split C++ API docs from general docs
  docs/CMakeLists.txt
  docs/cpp.rst
  docs/cpp/CMakeLists.txt
  docs/cpp/Doxyfile.in
  docs/cpp/cpp.rst
  docs/index.rst
Labels: moderate, normal

#6339 Add InferenceId as resources
  src/smt/env.cpp
  src/smt/env.h
  src/smt/smt_engine.cpp
  src/theory/theory_inference_manager.cpp
  src/util/resource_manager.cpp
  src/util/resource_manager.h
Labels: moderate, normal

#6404 Quantifiers: Move implementation of type rules to cpp.
  src/CMakeLists.txt
  src/theory/quantifiers/theory_quantifiers_type_rules.cpp
  src/theory/quantifiers/theory_quantifiers_type_rules.h
Labels: normal, simple

#6402 Sep: Move implementation of type rules to cpp.
  src/CMakeLists.txt
  src/theory/sep/theory_sep_type_rules.cpp
  src/theory/sep/theory_sep_type_rules.h
Labels: normal, simple

#6360 BV: Move implementation of type rules from header to .cpp.
  src/CMakeLists.txt
  src/theory/bv/theory_bv_type_rules.cpp
  src/theory/bv/theory_bv_type_rules.h
Labels: normal, simple

#6392 Split FP expand definitions to own module
  src/CMakeLists.txt
  src/theory/fp/fp_expand_defs.cpp
  src/theory/fp/fp_expand_defs.h
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp.h
  src/theory/fp/theory_fp_rewriter.cpp
  src/theory/fp/theory_fp_rewriter.h
Labels: moderate, normal

#6386 Add getNumIndices to Op
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  test/unit/api/op_black.cpp
Labels: normal, simple

#6333 Add basic utilities for new implementation of justification heuristic
  src/CMakeLists.txt
  src/decision/justify_info.cpp
  src/decision/justify_info.h
  src/decision/justify_stack.cpp
  src/decision/justify_stack.h
  src/decision/justify_stats.cpp
  src/decision/justify_stats.h
Labels: moderate, normal

#6400 Add unit test for abduction
  test/unit/api/solver_black.cpp
Labels: normal, simple

#6407 Arrays: Move implementation of type rules to cpp.
  src/CMakeLists.txt
  src/theory/arrays/theory_arrays_type_rules.cpp
  src/theory/arrays/theory_arrays_type_rules.h
Labels: normal, simple

#6401 Sets: Move implementation of type rules to cpp.
  src/CMakeLists.txt
  src/theory/sets/theory_sets_type_rules.cpp
  src/theory/sets/theory_sets_type_rules.h
Labels: normal, simple

#6406 cmake: Add optional module name argument to check_python_module.
  cmake/Helpers.cmake
  docs/CMakeLists.txt
Labels: normal, simple

#6418 Datatypes: Move implementation of type rules to cpp.
  src/CMakeLists.txt
  src/expr/type_node.cpp
  src/theory/datatypes/theory_datatypes_type_rules.cpp
  src/theory/datatypes/theory_datatypes_type_rules.h
Labels: normal, simple

#6411 Pass GMP to libpoly
  cmake/FindPoly.cmake
Labels: moderate, normal

#6410 Add explicit dependencies for base library
  src/base/CMakeLists.txt
Labels: moderate, normal

#6403 UF: Move implementation of type rules to cpp.
  src/CMakeLists.txt
  src/theory/uf/theory_uf_type_rules.cpp
  src/theory/uf/theory_uf_type_rules.h
Labels: normal, simple

#6419 Arithmetic: Move implementation of type rules to cpp.
  src/CMakeLists.txt
  src/theory/arith/theory_arith_type_rules.cpp
  src/theory/arith/theory_arith_type_rules.h
Labels: normal, simple

#6408 Move expand definition from Theory to TheoryRewriter
  src/smt/expand_definitions.cpp
  src/theory/arith/arith_preprocess.cpp
  src/theory/arith/arith_preprocess.h
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_rewriter.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/arrays/theory_arrays.cpp
  src/theory/arrays/theory_arrays.h
  src/theory/arrays/theory_arrays_rewriter.cpp
  src/theory/arrays/theory_arrays_rewriter.h
  src/theory/bags/bags_rewriter.h
  src/theory/bags/theory_bags.cpp
  src/theory/bags/theory_bags.h
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv.h
  src/theory/bv/theory_bv_rewriter.cpp
  src/theory/bv/theory_bv_rewriter.h
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/datatypes_rewriter.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp.h
  src/theory/fp/theory_fp_rewriter.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/sequences_rewriter.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  src/theory/theory.h
  src/theory/theory_rewriter.cpp
  src/theory/theory_rewriter.h
Labels: moderate, normal

#6409 Allow in-place construction of `CDList` items
  src/context/cdlist.h
  test/unit/context/cdlist_black.cpp
Labels: moderate, normal

#6405 Reconciling proofs and unsat cores
  src/api/cpp/cvc5.cpp
  src/options/smt_options.toml
  src/preprocessing/assertion_pipeline.cpp
  src/preprocessing/passes/ite_removal.cpp
  src/preprocessing/passes/ite_simp.cpp
  src/preprocessing/passes/miplib_trick.cpp
  src/preprocessing/passes/non_clausal_simp.cpp
  src/preprocessing/passes/theory_preprocess.cpp
  src/proof/proof_manager.cpp
  src/prop/minisat/core/Solver.cc
  src/prop/prop_engine.cpp
  src/prop/theory_proxy.cpp
  src/smt/assertions.cpp
  src/smt/proof_manager.cpp
  src/smt/proof_manager.h
  src/smt/set_defaults.cpp
  src/smt/smt_engine.cpp
  src/smt/smt_solver.cpp
  src/smt/smt_solver.h
  test/regress/regress2/strings/issue3203.smt2
Labels: moderate, normal

#6421 Fix models for sygus-inference, bv2int, real2int
  src/preprocessing/passes/bv_to_int.cpp
  src/preprocessing/passes/real_to_int.cpp
  src/preprocessing/passes/real_to_int.h
  src/preprocessing/passes/sygus_inference.cpp
  src/preprocessing/preprocessing_pass_context.cpp
  src/preprocessing/preprocessing_pass_context.h
  test/regress/regress0/push-pop/real-as-int-incremental.smt2
  test/regress/regress0/quantifiers/horn-ground-pre-post.smt2
  test/regress/regress1/quantifiers/horn-simple.smt2
  test/regress/regress2/sygus/issue4022-conjecture-gen.smt2
Labels: normal, simple

#6415 Reorganizing use of skolem definition manager in prop engine
  src/decision/decision_engine.cpp
  src/decision/decision_engine.h
  src/decision/decision_strategy.h
  src/decision/justification_heuristic.cpp
  src/decision/justification_heuristic.h
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/skolem_def_manager.cpp
  src/prop/skolem_def_manager.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
Labels: moderate, normal

#6422 Remove unused stuff from options setup
  CMakeLists.txt
  doc/CMakeLists.txt
  doc/SmtEngine.3cvc_template.in
  doc/cvc5.1_template.in
  doc/cvc5.5.in
  doc/find_public_interface.sh
  doc/libcvc5.3.in
  doc/libcvc5parser.3.in
  doc/options.3cvc_template.in
  src/options/CMakeLists.txt
  src/options/README
  src/options/mkoptions.py
Labels: moderate, normal

#6364 Add API documentation for statistics
  docs/_static/custom.css
  docs/conf.py
  docs/cpp/cpp.rst
  docs/cpp/statistics.rst
  docs/ext/.gitignore
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
Labels: minor, moderate

#6412 Update INSTALL.md
  INSTALL.md
Labels: minor, moderate

#6417 cmake: Do not require --auto-download for already downloaded dependencies.
  CMakeLists.txt
  cmake/FindANTLR3.cmake
  cmake/FindCLN.cmake
  cmake/FindCaDiCaL.cmake
  cmake/FindCryptoMiniSat.cmake
  cmake/FindGMP.cmake
  cmake/FindGTest.cmake
  cmake/FindKissat.cmake
  cmake/FindPoly.cmake
  cmake/FindSymFPU.cmake
  cmake/deps-helper.cmake
Labels: normal, simple

#6425 Minor changes to unsat core default setting
  src/smt/set_defaults.cpp
Labels: minor, simple

#6380 Minor simplifications to substitutions
  src/theory/substitutions.cpp
  src/theory/substitutions.h
  src/theory/theory_model.cpp
Labels: normal, simple

#6379 Make trust substitution map generate proofs lazily
  src/theory/trust_substitutions.cpp
  src/theory/trust_substitutions.h
Labels: moderate, normal

#6393 Move implementation of UF rewriter to cpp
  src/CMakeLists.txt
  src/theory/uf/theory_uf_rewriter.cpp
  src/theory/uf/theory_uf_rewriter.h
Labels: minor, simple

#6424 Enable strings exp by default for strings specific logics
  src/smt/set_defaults.cpp
  src/theory/quantifiers/fmf/full_model_check.cpp
Labels: normal, simple

#6430 Make sure a ReferenceStat is set to values of the correct type
  src/prop/bvminisat/core/Solver.cc
  src/prop/bvminisat/core/Solver.h
  src/prop/bvminisat/simp/SimpSolver.h
  src/prop/minisat/core/Solver.cc
  src/prop/minisat/core/Solver.h
  src/util/statistics_stats.h
Labels: moderate, normal

#6429 Add new substitution apply methods fixpoint, sequential, simultaneous
  src/expr/term_conversion_proof_generator.cpp
  src/expr/term_conversion_proof_generator.h
  src/smt/proof_post_processor.cpp
  src/theory/builtin/proof_checker.cpp
  src/theory/builtin/proof_checker.h
  src/theory/strings/infer_proof_cons.cpp
  src/theory/theory_proof_step_buffer.cpp
  src/theory/theory_proof_step_buffer.h
  src/theory/trust_substitutions.cpp
Labels: moderate, normal

#6416 (proof-new) Proofs for sets purification lemmas
  src/theory/sets/skolem_cache.cpp
  src/theory/sets/term_registry.cpp
  src/theory/sets/term_registry.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
Labels: moderate, simple

#6431 Add missing dependency for CaDiCaL
  cmake/FindCaDiCaL.cmake
Labels: major, simple

#6427 Add assumption-based unsat cores.
  src/expr/proof_rule.h
  src/prop/minisat/core/Solver.cc
  src/prop/minisat/core/Solver.h
  src/prop/minisat/minisat.cpp
  src/prop/minisat/minisat.h
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/smt/smt_engine.cpp
  src/theory/booleans/proof_checker.cpp
Labels: major, moderate

#6436 Improve getValue for non-evaluated operators
  src/theory/theory_model.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/arith/div-chainable.smt2
  test/regress/regress0/arith/issue3413.smt2
  test/regress/regress0/bug484.smt2
  test/regress/regress0/bv/bv_to_int_5293_2.smt2
  test/regress/regress0/decision/quant-ex1.smt2
  test/regress/regress0/fmf/QEpres-uf.855035.smtv1.smt2
  test/regress/regress0/fmf/fmc_unsound_model.smt2
  test/regress/regress0/fmf/sc_bad_model_1221.smt2
  test/regress/regress0/fp/issue3619.smt2
  test/regress/regress0/push-pop/real-as-int-incremental.smt2
  test/regress/regress0/quantifiers/horn-ground-pre-post.smt2
  test/regress/regress0/quantifiers/issue2033-macro-arith.smt2
  test/regress/regress0/quantifiers/macro-back-subs-sat.smt2
  test/regress/regress1/arith/issue4985-model-success.smt2
  test/regress/regress1/arith/issue4985b-model-success.smt2
  test/regress/regress1/fmf/Hoare-z3.931718.smtv1.smt2
  test/regress/regress1/fmf/LeftistHeap.scala-8-ncm.smt2
  test/regress/regress1/fmf/am-bad-model.cvc
  test/regress/regress1/fmf/german169.smt2
  test/regress/regress1/fmf/issue3626.smt2
  test/regress/regress1/fmf/jasmin-cdt-crash.smt2
  test/regress/regress1/fmf/loopy_coda.smt2
  test/regress/regress1/fmf/lst-no-self-rev-exp.smt2
  test/regress/regress1/fmf/memory_model-R_cpp-dd.cvc
  test/regress/regress1/fmf/nun-0208-to.smt2
  test/regress/regress1/fmf/refcount24.cvc.smt2
  test/regress/regress1/quantifiers/horn-simple.smt2
  test/regress/regress1/quantifiers/intersection-example-onelane.proof-node22337.smt2
  test/regress/regress1/quantifiers/issue3664.smt2
  test/regress/regress1/quantifiers/issue4849-nqe.smt2
  test/regress/regress1/quantifiers/issue5470-aext.smt2
  test/regress/regress1/quantifiers/qbv-test-invert-bvudiv-0.smt2
  test/regress/regress1/quantifiers/qbv-test-invert-bvudiv-1.smt2
  test/regress/regress1/quantifiers/qbv-test-invert-bvurem-1-neq.smt2
  test/regress/regress1/quantifiers/qbv-test-invert-bvurem-1.smt2
  test/regress/regress1/quantifiers/qbv-test-urem-rewrite.smt2
  test/regress/regress1/sets/is_singleton1.smt2
  test/regress/regress1/sets/issue5271.smt2
  test/regress/regress1/sets/sets-tuple-poly.cvc
  test/regress/regress1/strings/issue3657-unexpectedUnsatCVC4.smt2
  test/regress/regress1/sygus/issue3944-div-rewrite.smt2
  test/regress/regress1/trim.cvc
  test/regress/regress2/issue3687-check-models.smt2
  test/regress/regress2/quantifiers/net-policy-no-time.smt2
  test/regress/regress2/sygus/issue4022-conjecture-gen.smt2
Labels: moderate, normal

#6440 Use fast enumeration by default for Boolean predicate synthesis
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/type_info.cpp
  src/theory/quantifiers/sygus/type_info.h
Labels: moderate, normal

#6434 Do not process looping word equations over sequences
  src/theory/strings/core_solver.cpp
Labels: major, simple

#6443 Fix assertions in SAT solver
  src/prop/minisat/core/Solver.cc
Labels: normal, simple

#6435 Enable print-inst-full by default
  src/options/printer_options.toml
Labels: minor, simple

#6438 Ensure proofs track dependencies for trusted substitutions
  src/theory/trust_substitutions.cpp
  src/theory/trust_substitutions.h
Labels: normal, simple

#6423 New design in DOT representation, nodes colored based on visions(basic and propositional)
  src/proof/dot/dot_printer.cpp
  src/proof/dot/dot_printer.h
Labels: moderate, normal

#6444 Fix theoryOf for Boolean equalities
  src/theory/theory.cpp
Labels: major, simple

#6428 First part of options refactoring
  src/options/bv_options.toml
  src/options/mkoptions.py
  src/options/module_template.cpp
  src/options/open_ostream.cpp
  src/options/options.h
  src/options/options_handler.cpp
  src/options/options_public_functions.cpp
  src/options/options_template.cpp
  src/printer/printer.cpp
  src/prop/minisat/simp/SimpSolver.cc
  src/smt/env.h
  src/smt/managed_ostreams.cpp
  src/smt/options_manager.cpp
  src/smt/set_defaults.cpp
  src/smt/smt_engine.cpp
  src/smt/update_ostream.h
  src/theory/arith/theory_arith_private.cpp
  src/theory/quantifiers/expr_miner.cpp
  src/theory/quantifiers/sygus/sygus_repair_const.cpp
Labels: moderate, normal
