Repository cvc5/cvc5, pull requests merged in 2021-10, with the labels that each got.

#7266 Use the proper evaluator for optimized SyGuS datatype rewriting
  src/smt/env.cpp
  src/smt/env.h
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/datatypes_rewriter.h
  src/theory/datatypes/sygus_datatype_utils.cpp
  src/theory/datatypes/sygus_datatype_utils.h
  src/theory/datatypes/theory_datatypes.cpp
Labels: normal, moderate

#7196 Add the print benchmark utility
  src/smt/print_benchmark.cpp
  src/smt/print_benchmark.h
Labels: normal, moderate

#7158 Add the LFSC printer
  src/CMakeLists.txt
  src/proof/lfsc/lfsc_printer.cpp
  src/proof/lfsc/lfsc_printer.h
Labels: normal, moderate

#7293 Fix some python docstrings which lead to sphinx warnings
  src/api/python/cvc5.pxi
Labels: minor, simple

#7201 Clean options handlers
  src/main/driver_unified.cpp
  src/main/options.h
  src/main/options_template.cpp
  src/options/base_options.toml
  src/options/main_options.toml
  src/options/options_handler.cpp
  src/options/options_handler.h
  src/options/quantifiers_options.toml
Labels: minor, moderate

#7294 Remove (apparently obsolete) checks in cms config
  cmake/FindCryptoMiniSat.cmake
Labels: normal, moderate

#7292 Make preregistration safe for uninterpreted constants
  src/theory/uf/theory_uf.cpp
Labels: normal, simple

#7290 Fix ascription check for return types on ordinary functions
  src/parser/parser.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/parser/issue7274.smt2
Labels: normal, simple

#7288 Update theory preprocessor to use Env
  src/prop/theory_proxy.cpp
  src/smt/term_formula_removal.cpp
  src/smt/term_formula_removal.h
  src/theory/theory_preprocessor.cpp
  src/theory/theory_preprocessor.h
Labels: normal, moderate

#7225 Update java examples using the new Java API
  docs/examples/extract.rst
  docs/examples/quickstart.rst
  docs/examples/relations.rst
  docs/examples/sequences.rst
  docs/examples/sets.rst
  docs/examples/sygus-fun.rst
  docs/examples/sygus-grammar.rst
  docs/examples/sygus-inv.rst
  examples/api/cpp/CMakeLists.txt
  examples/api/cpp/floating_point_arith.cpp
  examples/api/java/BitVectors.java
  examples/api/java/BitVectorsAndArrays.java
  examples/api/java/CVC4Streams.java
  examples/api/java/Combination.java
  examples/api/java/Datatypes.java
  examples/api/java/Exceptions.java
  examples/api/java/Extract.java
  examples/api/java/FloatingPointArith.java
  examples/api/java/HelloWorld.java
  examples/api/java/LinearArith.java
  examples/api/java/PipedInput.java
  examples/api/java/QuickStart.java
  examples/api/java/Relations.java
  examples/api/java/Sequences.java
  examples/api/java/Sets.java
  examples/api/java/Statistics.java
  examples/api/java/Strings.java
  examples/api/java/SygusFun.java
  examples/api/java/SygusGrammar.java
  examples/api/java/SygusInv.java
  examples/api/java/Transcendentals.java
  examples/api/java/UnsatCores.java
  src/api/java/cvc5/Grammar.java
  src/api/java/cvc5/Term.java
  src/api/java/jni/cvc5_Grammar.cpp
  test/unit/api/java/cvc5/SolverTest.java
Labels: normal, simple

#7302 Eliminating static calls to rewriter from strings
  src/preprocessing/passes/strings_eager_pp.cpp
  src/theory/strings/arith_entail.cpp
  src/theory/strings/arith_entail.h
  src/theory/strings/core_solver.cpp
  src/theory/strings/proof_checker.cpp
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/regexp_operation.h
  src/theory/strings/regexp_solver.cpp
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/skolem_cache.cpp
  src/theory/strings/skolem_cache.h
  src/theory/strings/term_registry.cpp
  test/unit/theory/regexp_operation_black.cpp
  test/unit/theory/theory_strings_skolem_cache_black.cpp
Labels: minor, simple

#7301 Eliminating static calls to rewriter in quantifiers
  src/theory/quantifiers/candidate_rewrite_database.cpp
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus_inst.cpp
  src/theory/quantifiers/term_database.cpp
Labels: minor, simple

#7296 No longer build docs by default. Use make docs.
  INSTALL.rst
  docs/CMakeLists.txt
  docs/api/cpp/CMakeLists.txt
Labels: minor, simple

#7300 Make decision engine use env
  src/decision/decision_engine.cpp
  src/decision/decision_engine.h
  src/decision/decision_engine_old.cpp
  src/decision/decision_engine_old.h
  src/decision/decision_strategy.h
  src/decision/justification_heuristic.cpp
  src/decision/justification_heuristic.h
  src/decision/justification_strategy.cpp
  src/decision/justification_strategy.h
  src/prop/prop_engine.cpp
  src/smt/env.cpp
  src/smt/env_obj.cpp
  src/smt/env_obj.h
Labels: normal, simple

#7287 Move isFiniteType from theory engine to Env
  src/smt/env.cpp
  src/smt/env.h
  src/theory/datatypes/sygus_extension.cpp
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/quant_split.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/sets/cardinality_extension.cpp
  src/theory/shared_solver.cpp
  src/theory/strings/base_solver.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/term_registration_visitor.cpp
  src/theory/term_registration_visitor.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/theory_model_builder.cpp
  src/theory/theory_model_builder.h
  src/theory/theory_state.cpp
  src/theory/theory_state.h
  src/theory/uf/ho_extension.cpp
  src/theory/valuation.cpp
  src/theory/valuation.h
Labels: normal, moderate

#7291 Refactor internally generated bounded quantified formulas
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/fmf/bounded_integers.h
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers/quantifiers_attributes.h
  src/theory/strings/theory_strings_utils.cpp
Labels: normal, moderate

#7283 Various improvements to documentation
  docs/CMakeLists.txt
  docs/api/java/CMakeLists.txt
  docs/api/java/index.rst
  docs/conf.py.in
  docs/ext/examples.py
  docs/ext/include_build_file.py
  src/api/python/CMakeLists.txt
  src/api/python/__init__.py.in
  src/api/python/cvc5.pxi
Labels: minor, moderate

#7303 Add sygus examples to documentation
  docs/examples/sygus-fun.rst
  docs/examples/sygus-grammar.rst
  docs/examples/sygus-inv.rst
  docs/ext/examples.py
  examples/api/smtlib/sygus-fun.sy
  examples/api/smtlib/sygus-grammar.sy
  examples/api/smtlib/sygus-inv.sy
  src/api/cpp/cvc5.h
Labels: minor, simple

#7295 Finish refactoring on option handlers
  src/options/options_handler.cpp
  src/options/options_handler.h
  src/options/smt_options.toml
  src/smt/dump.cpp
  test/regress/regress1/fmf/forall_unit_data.smt2
Labels: normal, moderate

#7305 Reformulate cmake message when GPL is disabled
  CMakeLists.txt
Labels: normal, simple

#7255 First round of refactoring on NlModel
  src/expr/subs.cpp
  src/expr/subs.h
  src/theory/arith/arith_utilities.cpp
  src/theory/arith/arith_utilities.h
  src/theory/arith/nl/cad_solver.cpp
  src/theory/arith/nl/ext/monomial_check.cpp
  src/theory/arith/nl/nl_lemma_utils.cpp
  src/theory/arith/nl/nl_model.cpp
  src/theory/arith/nl/nl_model.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/poly_conversion.h
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
Labels: normal, moderate

#7317 Replace doubles by rationals in C++ quickstart
  docs/api/cpp/quickstart.rst
  examples/api/cpp/quickstart.cpp
Labels: minor, moderate

#7285 Finish the LFSC printer
  src/proof/lfsc/lfsc_printer.cpp
Labels: normal, moderate

#7326 Add argument to distinguish lemmas and input assertions
  src/decision/decision_engine.cpp
  src/decision/decision_engine.h
  src/decision/decision_engine_old.cpp
  src/decision/decision_engine_old.h
  src/decision/justification_strategy.cpp
  src/decision/justification_strategy.h
  src/prop/prop_engine.cpp
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
Labels: minor, simple

#7327 Make skolem definition manager robust to function skolems
  src/prop/skolem_def_manager.cpp
Labels: normal, simple

#7330 Remove static accesses to options where EnvObj is used
  src/smt/abduction_solver.cpp
  src/smt/assertions.cpp
  src/smt/preprocessor.cpp
  src/smt/process_assertions.cpp
  src/smt/proof_manager.cpp
  src/smt/proof_post_processor.cpp
  src/smt/smt_engine_state.cpp
  src/smt/sygus_solver.cpp
  src/theory/quantifiers/ematching/inst_strategy.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching.cpp
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/quantifiers_state.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/enum_value_manager.cpp
Labels: normal, moderate

#7286 Add cardinality constraint utilities
  src/expr/CMakeLists.txt
  src/expr/cardinality_constraint.cpp
  src/expr/cardinality_constraint.h
Labels: normal, moderate

#7331 Simplify skolemization in sygus solver
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
Labels: minor, moderate

#7349 Clean up occurrences of SmtEngine in comments.
  src/expr/node_manager.cpp
  src/expr/node_manager.h
  src/smt/command.h
  src/smt/process_assertions.cpp
  src/theory/bv/theory_bv_rewrite_rules.h
Labels: normal, simple

#7336 Make (proof) equality engine use Env
  src/theory/arith/congruence_manager.cpp
  src/theory/arrays/theory_arrays.cpp
  src/theory/ee_manager.cpp
  src/theory/ee_manager_central.cpp
  src/theory/ee_manager_distributed.cpp
  src/theory/quantifiers/candidate_rewrite_database.cpp
  src/theory/quantifiers/candidate_rewrite_filter.cpp
  src/theory/quantifiers/candidate_rewrite_filter.h
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/dynamic_rewrite.cpp
  src/theory/quantifiers/dynamic_rewrite.h
  src/theory/shared_terms_database.cpp
  src/theory/theory.cpp
  src/theory/theory_inference_manager.cpp
  src/theory/uf/equality_engine.cpp
  src/theory/uf/equality_engine.h
  src/theory/uf/proof_equality_engine.cpp
  src/theory/uf/proof_equality_engine.h
Labels: normal, moderate

#7357 Fix GLPK linking -- second try
  src/CMakeLists.txt
Labels: major, simple

#7358 Fix quantifiers variable elimination for parametric datatypes
  src/theory/quantifiers/quantifiers_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/quantifiers/issue7353-var-elim-par-dt.smt2
Labels: normal, simple

#7347 Also test older cmake versions
  .github/actions/run-tests/action.yml
  .github/workflows/ci.yml
  .github/workflows/cmake-version.yml
Labels: minor, moderate

#7364 Improve parser for tuple select
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
Labels: minor, simple

#7367 Improve ManagedStreams
  src/options/managed_streams.cpp
  src/options/managed_streams.h
  test/regress/CMakeLists.txt
  test/regress/regress0/options/stream-printing.smt2
Labels: normal, moderate

#7352 Have docs-ci properly upload tags
  .github/workflows/docs_upload.yml
Labels: normal, moderate

#7382 Add more regressions for fixed issues
  test/regress/CMakeLists.txt
  test/regress/regress0/push-pop/issue6535-inc-solve.smt2
  test/regress/regress0/quantifiers/issue6475-rr-const.smt2
  test/regress/regress1/nl/issue5660-mb-success.smt2
  test/regress/regress1/quantifiers/issue6607-witness-te.smt2
  test/regress/regress1/quantifiers/issue6638-sygus-inst.smt2
  test/regress/regress1/quantifiers/issue6642-em-types.smt2
  test/regress/regress1/quantifiers/issue6775-vts-int.smt2
Labels: minor, simple

#7395 Add regression for fixed issue
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue6653-3-seq.smt2
Labels: minor, simple

#7412 Fix expected conclusion for EQ_RESOLVE when expanding MACRO_SR_PRED_TRANSFORM
  src/smt/proof_post_processor.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/proofs/qgu-fuzz-1-strings-pp.smt2
Labels: major, simple

#7416 Add basic regular expression type enumerator
  src/CMakeLists.txt
  src/theory/strings/kinds
  src/theory/strings/regexp_enumerator.cpp
  src/theory/strings/regexp_enumerator.h
Labels: normal, moderate

#7411 Make proofs of rewrites robust to use in internal subsolvers
  src/theory/rewriter.cpp
  src/theory/rewriter.h
Labels: normal, moderate

#7394 Alethe: Documentation on Translation
  src/proof/alethe/alethe_post_processor.cpp
Labels: minor, simple

#7355 Eliminate last static calls to rewriter from smt layer
  src/proof/proof_node_manager.cpp
  src/proof/proof_node_manager.h
  src/smt/check_models.cpp
  src/smt/check_models.h
  src/smt/model_blocker.cpp
  src/smt/model_blocker.h
  src/smt/preprocessor.cpp
  src/smt/proof_manager.cpp
  src/smt/proof_post_processor.cpp
  src/smt/solver_engine.cpp
  src/smt/sygus_solver.cpp
  src/smt/witness_form.cpp
  src/smt/witness_form.h
Labels: minor, simple

#7408 Check for higher-order variables in TheoryUF::ppRewrite
  src/theory/uf/ho_extension.cpp
  src/theory/uf/theory_uf.cpp
  test/unit/api/solver_black.cpp
Labels: normal, simple

#7435 Fix docs upload (again)
  .github/workflows/docs_upload.yml
Labels: major, moderate

#7387 Enable and fix dump test
  test/regress/CMakeLists.txt
  test/regress/regress0/datatypes/datatype-dump.cvc.smt2
Labels: minor, simple

#7446 Fix incorrect proof from ITE in circuit propagator
  src/theory/booleans/proof_circuit_propagator.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/preprocess/proj-issue305-circuit-prop-ite.smt2
Labels: normal, moderate

#7448 [proofs] Fix open proof in SAT solver due to cycles
  src/prop/sat_proof_manager.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/proofs/qgu-fuzz-1-bool-sat.smt2
Labels: normal, moderate

#7438 docs: Use light gray for background on the right.
  docs/_static/custom.css
Labels: normal, simple

#7426 Make expression mining use configurable options and logic
  src/theory/quantifiers/expr_miner.cpp
  src/theory/quantifiers/expr_miner.h
Labels: minor, simple

#7494 Minor cleanup of proof messages
  src/proof/proof_ensure_closed.h
  src/proof/proof_node_algorithm.cpp
  src/proof/proof_node_to_sexpr.cpp
  src/proof/proof_node_updater.cpp
  src/theory/arrays/theory_arrays.cpp
  src/theory/arrays/theory_arrays.h
Labels: minor, simple

#7419 Remove options::X__numValues
  src/options/README.md
  src/options/base_options.toml
  src/options/mkoptions.py
  src/options/options_handler.cpp
Labels: minor, moderate

#7530 Fix proof of nl lemma for a corner case
  src/theory/arith/nl/ext/monomial_bounds_check.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/proofs/proj-issue326-nl-bounds-check.smt2
Labels: normal, moderate

#7538 Remove assertSkeleton for bag elements during model building
  src/theory/bags/theory_bags.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/bags/fuzzy3.smt2
Labels: normal, simple

#7539 Fix soundess issue for bags with negative multiplicity
  src/theory/bags/bags_rewriter.cpp
  src/theory/bags/bags_rewriter.h
  src/theory/bags/inference_generator.cpp
  src/theory/bags/inference_generator.h
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  test/regress/CMakeLists.txt
  test/regress/regress1/bags/fuzzy4.smt2
  test/regress/regress1/bags/fuzzy5.smt2
  test/unit/theory/theory_bags_rewriter_white.cpp
Labels: major, moderate
