Repository cvc5/cvc5, pull requests merged in 2021-01, with the labels that each got.

#5661 Remove a few miscellaneous references to the expr layer
  src/expr/symbol_table.cpp
  src/expr/symbol_table.h
  src/parser/antlr_input.h
  src/printer/cvc/cvc_printer.cpp
  src/printer/tptp/tptp_printer.cpp
  src/proof/sat_proof.h
  src/prop/cnf_stream.cpp
  src/prop/prop_engine.cpp
  src/prop/sat_proof_manager.h
  src/smt/model.h
Labels: minor, simple

#5717 Add new interfaces to term formula removal and theory preprocess
  src/prop/theory_proxy.cpp
  src/smt/term_formula_removal.cpp
  src/smt/term_formula_removal.h
  src/theory/theory_preprocessor.cpp
  src/theory/theory_preprocessor.h
Labels: normal, simple

#5747 strings arith checks preprocessing pass: step 1
  src/CMakeLists.txt
  src/preprocessing/passes/foreign_theory_rewrite.cpp
  src/preprocessing/passes/foreign_theory_rewrite.h
  src/preprocessing/preprocessing_pass_registry.cpp
Labels: performance

#5752 Fix warning in TPTP parser
  src/parser/tptp/Tptp.g
Labels: minor, simple

#5753 Remove dependency on expression layer in TPTP parser
  src/parser/tptp/Tptp.g
Labels: moderate, normal

#5733 Make sure polynomials are properly factorized in nl-cad
  src/theory/arith/nl/cad/cdcac.cpp
  src/theory/arith/nl/cad/cdcac.h
  src/theory/arith/nl/cad/cdcac_utils.cpp
  src/theory/arith/nl/cad/cdcac_utils.h
  src/theory/arith/nl/cad/projections.cpp
  src/theory/arith/nl/cad/projections.h
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/issue5726-downpolys.smt2
  test/regress/regress0/nl/issue5726-sqfactor.smt2
Labels: moderate, normal

#5489 (proof-new) Some new proofs for nonlinear multiplication
  src/expr/proof_rule.cpp
  src/expr/proof_rule.h
  src/theory/arith/nl/ext/monomial_bounds_check.cpp
  src/theory/arith/nl/ext/monomial_check.cpp
  src/theory/arith/nl/ext/proof_checker.cpp
Labels: moderate, normal

#5731 Add bags inference generator
  src/CMakeLists.txt
  src/api/cvc4cpp.cpp
  src/expr/type_node.cpp
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/bags/bag_solver.cpp
  src/theory/bags/bag_solver.h
  src/theory/bags/bags_rewriter.cpp
  src/theory/bags/bags_rewriter.h
  src/theory/bags/infer_info.cpp
  src/theory/bags/infer_info.h
  src/theory/bags/inference_generator.cpp
  src/theory/bags/inference_generator.h
  src/theory/bags/inference_manager.cpp
  src/theory/bags/inference_manager.h
  src/theory/bags/normal_form.cpp
  src/theory/bags/normal_form.h
  src/theory/bags/solver_state.cpp
  src/theory/bags/solver_state.h
  src/theory/bags/theory_bags.cpp
  src/theory/bags/theory_bags.h
  src/theory/strings/base_solver.h
  test/regress/CMakeLists.txt
  test/regress/regress1/bags/disequality.smt2
  test/regress/regress1/bags/subbag1.smt2
  test/regress/regress1/bags/subbag2.smt2
  test/regress/regress1/bags/union_disjoint.smt2
  test/regress/regress1/bags/union_max1.smt2
  test/regress/regress1/bags/union_max2.smt2
Labels: moderate, normal

#5751 [proof-new] Implementing getProof in the API and SMT engine
  src/api/cvc4cpp.cpp
  src/smt/command.cpp
  src/smt/command.h
  src/smt/proof_manager.cpp
  src/smt/proof_manager.h
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
Labels: normal, simple

#5754 Rename strings::InferInfo::getAntecedent to InferInfo::getPremises
  src/theory/strings/core_solver.cpp
  src/theory/strings/infer_info.cpp
  src/theory/strings/infer_info.h
  src/theory/strings/infer_proof_cons.cpp
  src/theory/strings/inference_manager.cpp
  src/theory/strings/solver_state.cpp
  src/theory/strings/theory_strings.cpp
Labels: minor, simple

#5757 Fix issue 5513
  src/theory/bags/theory_bags.cpp
  src/theory/bags/theory_bags.h
Labels: minor, simple

#5750 Strings arith checks preprocessing pass: step 2
  src/preprocessing/passes/foreign_theory_rewrite.cpp
  src/preprocessing/passes/foreign_theory_rewrite.h
  test/unit/preprocessing/CMakeLists.txt
  test/unit/preprocessing/pass_foreign_theory_rewrite_white.h
Labels: performance

#5760 Remove extended rewrite for arithmetic
  src/theory/quantifiers/extended_rewrite.cpp
  src/theory/quantifiers/extended_rewrite.h
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/issue5737-div00.smt2
  test/regress/regress0/nl/issue5740-2-mod00.smt2
  test/regress/regress0/nl/issue5740-mod00.smt2
Labels: normal, simple

#5756 Further simplifications in preparation for removing Expr layer
  src/api/cvc4cpp.cpp
  src/expr/expr_manager_template.cpp
  src/expr/expr_manager_template.h
  src/expr/expr_template.cpp
  src/expr/node_manager.cpp
  src/expr/node_manager.h
  src/expr/node_manager_attributes.h
  src/preprocessing/passes/miplib_trick.cpp
  src/preprocessing/passes/miplib_trick.h
  src/preprocessing/passes/synth_rew_rules.cpp
  src/printer/ast/ast_printer.cpp
  src/smt/dump_manager.cpp
  src/smt/dump_manager.h
  src/smt/listeners.cpp
  src/smt/listeners.h
  src/smt/smt_engine.cpp
  src/theory/builtin/theory_builtin_type_rules.h
  src/theory/datatypes/sygus_datatype_utils.cpp
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_grammar_norm.cpp
  test/unit/expr/type_cardinality_public.h
  test/unit/util/datatype_black.h
Labels: moderate, normal

#5758 Merge theory registrar and theory proxy
  src/CMakeLists.txt
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
  src/theory/bv/bitblast/bitblaster.h
  src/theory/theory_registrar.h
  test/unit/prop/cnf_stream_white.h
  test/unit/theory/theory_bv_white.h
Labels: moderate, normal

#5765 google test: Use ASSERT_* instead of EXPECT_*.
  test/unit/api/datatype_api_black.cpp
  test/unit/api/op_black.cpp
  test/unit/api/result_black.cpp
  test/unit/api/solver_black.cpp
  test/unit/api/sort_black.cpp
  test/unit/api/term_black.cpp
  test/unit/base/map_util_black.cpp
  test/unit/context/cdlist_black.cpp
  test/unit/context/cdo_black.cpp
  test/unit/context/context_black.cpp
  test/unit/context/context_white.cpp
  test/unit/expr/attribute_black.cpp
  test/unit/expr/attribute_white.cpp
  test/unit/expr/kind_black.cpp
  test/unit/expr/node_algorithm_black.cpp
  test/unit/theory/theory_sets_type_rules_white.h
Labels: normal, simple

#5764 google test: expr: Migrate node_black.
  test/unit/expr/CMakeLists.txt
  test/unit/expr/node_black.cpp
  test/unit/expr/node_black.h
Labels: normal, simple

#5762 Do not call ppRewrite on Boolean equalities
  src/preprocessing/passes/theory_rewrite_eq.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/arith/issue5761-ppr.smt2
Labels: normal, simple

#5774 (proof-new) Fix proofs for sine secant lemmas.
  src/theory/arith/nl/transcendental/proof_checker.cpp
  src/theory/arith/nl/transcendental/transcendental_state.cpp
Labels: normal, simple

#5775 Split eager solver from strings solver state
  src/CMakeLists.txt
  src/theory/strings/eager_solver.cpp
  src/theory/strings/eager_solver.h
  src/theory/strings/solver_state.cpp
  src/theory/strings/solver_state.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: major, moderate

#5776 Updates to theory preprocess equality
  src/preprocessing/passes/theory_rewrite_eq.cpp
  src/smt/process_assertions.cpp
  src/theory/arith/theory_arith_private.cpp
  src/theory/engine_output_channel.cpp
Labels: moderate, normal

#5777 Implement --no-strings-lazy-pp as a preprocessing pass
  src/CMakeLists.txt
  src/preprocessing/passes/rewrite.cpp
  src/preprocessing/passes/strings_eager_pp.cpp
  src/preprocessing/passes/strings_eager_pp.h
  src/preprocessing/preprocessing_pass_registry.cpp
  src/smt/process_assertions.cpp
  src/theory/strings/extf_solver.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/theory_strings_preprocess.h
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/issue5608-eager-pp.smt2
  test/regress/regress0/strings/issue5745-eager-pp.smt2
  test/regress/regress0/strings/issue5767-eager-pp.smt2
  test/regress/regress0/strings/issue5771-eager-pp.smt2
  test/regress/regress1/strings/issue5406-eager-pp.smt2
Labels: moderate, normal

#5784 Implement proofs for arith BRAB lemmas
  src/expr/proof_node.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
  src/theory/eager_proof_generator.cpp
  src/theory/eager_proof_generator.h
  src/theory/theory.cpp
  src/theory/theory.h
Labels: minor, simple

#5790 Use arbitrary ground term assignment for sorts where isInterpretedFinite is true
  src/theory/theory_model_builder.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/fmf/issue5738-dt-interp-finite.smt2
Labels: normal, simple

#5791 Do not track processed in remove term formulas loop
  src/smt/term_formula_removal.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/issue5739-rtf-processed.smt2
Labels: minor, simple

#5786 Fix corner case of wrongly applied selector as trigger
  src/theory/quantifiers/ematching/candidate_generator.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue5766-wrong-sel-trigger.smt2
Labels: minor, simple

#5788 Fix type issues with relevant domain computation
  src/theory/quantifiers/inst_strategy_enumerative.cpp
  src/theory/quantifiers/relevant_domain.cpp
  src/theory/quantifiers/term_database.cpp
Labels: normal, simple

#5706 Refactoring the single invocation solver
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.h
  src/theory/quantifiers/sygus/ce_guided_single_inv_sol.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv_sol.h
Labels: minor, moderate

#5792 arith: Proofs for Diophantine cuts
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
Labels: minor, simple

#5793 Add div, mod, abs in non-strict parsing mode
  src/parser/smt2/smt2.cpp
  test/regress/regress0/expect/scrub.08.sy
  test/regress/regress0/parser/linear_arithmetic_err1.smt2
  test/regress/regress0/parser/linear_arithmetic_err2.smt2
  test/regress/regress0/parser/linear_arithmetic_err3.smt2
Labels: major, simple

#5755 [proof-new] Expanding MACRO_RESOLUTION in post-processing
  src/smt/proof_manager.cpp
  src/smt/proof_post_processor.cpp
  src/smt/proof_post_processor.h
Labels: moderate, normal

#5798 Add interface for getting preprocessed term
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/valuation.cpp
  src/theory/valuation.h
Labels: moderate, normal

#5768 (proof-new) Instantiation list utility
  src/CMakeLists.txt
  src/printer/printer.cpp
  src/printer/printer.h
  src/theory/quantifiers/instantiation_list.cpp
  src/theory/quantifiers/instantiation_list.h
Labels: moderate, normal

#5794 Initial cleaning of inst match generator
  src/theory/quantifiers/ematching/inst_match_generator.cpp
  src/theory/quantifiers/ematching/inst_match_generator.h
Labels: normal, simple

#5795 Initial cleaning of triggers
  src/options/quantifiers_options.toml
  src/theory/quantifiers/ematching/ho_trigger.cpp
  src/theory/quantifiers/ematching/ho_trigger.h
  src/theory/quantifiers/ematching/inst_strategy_e_matching.cpp
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/ematching/trigger.h
Labels: normal, simple

#5796 Initial cleaning of e-matching instantiation strategy
  src/theory/quantifiers/ematching/inst_strategy_e_matching.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching.h
  src/theory/quantifiers/quant_relevance.cpp
  src/theory/quantifiers/quant_relevance.h
Labels: normal, simple

#5799 Rename InferInfo::d_newSkolem to InferInfo::d_skolems
  src/theory/strings/core_solver.cpp
  src/theory/strings/infer_info.h
  src/theory/strings/inference_manager.cpp
Labels: minor, simple

#5807 Split E-matching strategies to own files
  src/CMakeLists.txt
  src/theory/quantifiers/ematching/inst_strategy.h
  src/theory/quantifiers/ematching/inst_strategy_e_matching.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching.h
  src/theory/quantifiers/ematching/inst_strategy_e_matching_user.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching_user.h
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  src/theory/quantifiers/ematching/instantiation_engine.h
Labels: minor, simple

#5805 Split inst match generator into multiple files
  src/CMakeLists.txt
  src/theory/quantifiers/ematching/inst_match_generator.cpp
  src/theory/quantifiers/ematching/inst_match_generator.h
  src/theory/quantifiers/ematching/inst_match_generator_multi.cpp
  src/theory/quantifiers/ematching/inst_match_generator_multi.h
  src/theory/quantifiers/ematching/inst_match_generator_multi_linear.cpp
  src/theory/quantifiers/ematching/inst_match_generator_multi_linear.h
  src/theory/quantifiers/ematching/inst_match_generator_simple.cpp
  src/theory/quantifiers/ematching/inst_match_generator_simple.h
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/ematching/var_match_generator.cpp
  src/theory/quantifiers/ematching/var_match_generator.h
Labels: normal, simple

#5808 Ensure uses of ground terms in triggers are preprocessed and registered
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/ematching/trigger.h
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/min-ppgt-em-incomplete.smt2
  test/regress/regress1/quantifiers/min-ppgt-em-incomplete2.smt2
Labels: moderate, normal

#5783 Refactor bags::SolverState
  src/theory/bags/bag_solver.cpp
  src/theory/bags/bag_solver.h
  src/theory/bags/bags_rewriter.h
  src/theory/bags/infer_info.cpp
  src/theory/bags/infer_info.h
  src/theory/bags/inference_generator.cpp
  src/theory/bags/inference_generator.h
  src/theory/bags/inference_manager.h
  src/theory/bags/solver_state.cpp
  src/theory/bags/solver_state.h
  src/theory/bags/theory_bags.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/bags/difference_remove1.smt2
  test/regress/regress1/bags/issue5759.smt2
Labels: moderate, normal

#5812 Add proofs to TheoryArithPrivate::propagate
  src/theory/arith/theory_arith_private.cpp
Labels: minor, simple

#5810 Reestablishing support for define-sort
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  src/expr/symbol_table.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/parser/define_sort.smt2
  test/unit/api/solver_black.cpp
Labels: moderate, normal

#5813 Refactor quantifiers engine initialization
  src/theory/quantifiers/anti_skolem.cpp
  src/theory/quantifiers/anti_skolem.h
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.h
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/conjecture_generator.h
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  src/theory/quantifiers/ematching/instantiation_engine.h
  src/theory/quantifiers/equality_query.cpp
  src/theory/quantifiers/equality_query.h
  src/theory/quantifiers/first_order_model.cpp
  src/theory/quantifiers/first_order_model.h
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/fmf/bounded_integers.h
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/quantifiers/fmf/full_model_check.h
  src/theory/quantifiers/fmf/model_builder.cpp
  src/theory/quantifiers/fmf/model_builder.h
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/fmf/model_engine.h
  src/theory/quantifiers/inst_strategy_enumerative.cpp
  src/theory/quantifiers/inst_strategy_enumerative.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/instantiate.h
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/quant_conflict_find.h
  src/theory/quantifiers/quant_split.cpp
  src/theory/quantifiers/quant_split.h
  src/theory/quantifiers/quant_util.cpp
  src/theory/quantifiers/quant_util.h
  src/theory/quantifiers/quantifiers_modules.cpp
  src/theory/quantifiers/quantifiers_modules.h
  src/theory/quantifiers/skolemize.cpp
  src/theory/quantifiers/skolemize.h
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/cegis_unif.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus/synth_engine.h
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
  src/theory/quantifiers/sygus_inst.cpp
  src/theory/quantifiers/sygus_inst.h
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers/term_database.h
  src/theory/quantifiers/theory_quantifiers.cpp
  src/theory/quantifiers/theory_quantifiers.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
  src/theory/theory.cpp
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: moderate, normal

#5820 Remove deprecated quantifiers modules
  src/CMakeLists.txt
  src/options/quantifiers_options.toml
  src/theory/quantifiers/anti_skolem.cpp
  src/theory/quantifiers/anti_skolem.h
  src/theory/quantifiers/equality_infer.cpp
  src/theory/quantifiers/equality_infer.h
  src/theory/quantifiers/equality_query.cpp
  src/theory/quantifiers/quantifiers_modules.cpp
  src/theory/quantifiers/quantifiers_modules.h
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/anti-sk-simp.smt2
Labels: minor, simple

#5821 Introduce quantifiers inference manager
  src/CMakeLists.txt
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.h
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/conjecture_generator.h
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  src/theory/quantifiers/ematching/instantiation_engine.h
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/fmf/bounded_integers.h
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/fmf/model_engine.h
  src/theory/quantifiers/inst_strategy_enumerative.cpp
  src/theory/quantifiers/inst_strategy_enumerative.h
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/quant_conflict_find.h
  src/theory/quantifiers/quant_split.cpp
  src/theory/quantifiers/quant_split.h
  src/theory/quantifiers/quant_util.cpp
  src/theory/quantifiers/quant_util.h
  src/theory/quantifiers/quantifiers_inference_manager.cpp
  src/theory/quantifiers/quantifiers_inference_manager.h
  src/theory/quantifiers/quantifiers_modules.cpp
  src/theory/quantifiers/quantifiers_modules.h
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus/synth_engine.h
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
  src/theory/quantifiers/sygus_inst.cpp
  src/theory/quantifiers/sygus_inst.h
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers/term_database.h
  src/theory/quantifiers/term_util.cpp
  src/theory/quantifiers/term_util.h
  src/theory/quantifiers/theory_quantifiers.cpp
  src/theory/quantifiers/theory_quantifiers.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: normal, simple

#5822 Use standard conflict mechanism in quantifiers state
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/ematching/inst_strategy.h
  src/theory/quantifiers/ematching/inst_strategy_e_matching.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching.h
  src/theory/quantifiers/ematching/inst_strategy_e_matching_user.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching_user.h
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/quantifiers/fmf/full_model_check.h
  src/theory/quantifiers/fmf/model_builder.cpp
  src/theory/quantifiers/fmf/model_builder.h
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/inst_strategy_enumerative.cpp
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/quant_util.cpp
  src/theory/quantifiers/quant_util.h
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
  src/theory/theory_state.cpp
  src/theory/theory_state.h
Labels: normal, simple

#5823 Use term canonizer utility locally in quantifiers
  src/theory/quantifiers/alpha_equivalence.cpp
  src/theory/quantifiers/alpha_equivalence.h
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/conjecture_generator.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: minor, simple

#5818 Thread proofs through arith channels & similar
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
Labels: minor, simple

#5814 (proof-new) Improvements to quantifiers engine and instantiate interfaces
  src/options/printer_options.toml
  src/options/quantifiers_options.toml
  src/smt/quant_elim_solver.cpp
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/instantiate.h
  src/theory/quantifiers/skolemize.cpp
  src/theory/quantifiers/skolemize.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  test/regress/CMakeLists.txt
Labels: moderate, normal

#5811 Split pattern term selector from trigger
  src/CMakeLists.txt
  src/preprocessing/passes/quantifier_macros.cpp
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/ematching/inst_match_generator.cpp
  src/theory/quantifiers/ematching/inst_match_generator_simple.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching_user.cpp
  src/theory/quantifiers/ematching/pattern_term_selector.cpp
  src/theory/quantifiers/ematching/pattern_term_selector.h
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/ematching/trigger.h
  src/theory/quantifiers/ematching/trigger_term_info.cpp
  src/theory/quantifiers/ematching/trigger_term_info.h
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/term_database.cpp
Labels: moderate, normal

#5825 Add option for whether to filter candidate rewrite pairs
  src/theory/quantifiers/candidate_rewrite_database.cpp
  src/theory/quantifiers/candidate_rewrite_database.h
Labels: normal, simple

#5817 Always theory-preprocess lemmas
  src/preprocessing/passes/ite_removal.cpp
  src/preprocessing/passes/theory_preprocess.cpp
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
  src/theory/theory_preprocessor.cpp
  src/theory/theory_preprocessor.h
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/tpp-unit-fail-qbv.smt2
Labels: moderate, normal

#5824 Use standard equality engine information in quantifiers state
  src/theory/combination_engine.cpp
  src/theory/combination_engine.h
  src/theory/ee_manager.h
  src/theory/ee_manager_distributed.cpp
  src/theory/ee_manager_distributed.h
  src/theory/ee_setup_info.h
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/ematching/candidate_generator.cpp
  src/theory/quantifiers/ematching/ho_trigger.cpp
  src/theory/quantifiers/ematching/inst_match_generator.cpp
  src/theory/quantifiers/ematching/inst_match_generator_multi.cpp
  src/theory/quantifiers/ematching/inst_match_generator_simple.cpp
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/ematching/var_match_generator.cpp
  src/theory/quantifiers/equality_query.cpp
  src/theory/quantifiers/equality_query.h
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/inst_match.cpp
  src/theory/quantifiers/inst_match.h
  src/theory/quantifiers/inst_match_trie.cpp
  src/theory/quantifiers/inst_match_trie.h
  src/theory/quantifiers/inst_strategy_enumerative.cpp
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/quant_util.cpp
  src/theory/quantifiers/quant_util.h
  src/theory/quantifiers/relevant_domain.cpp
  src/theory/quantifiers/relevant_domain.h
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers/term_database.h
  src/theory/quantifiers/theory_quantifiers.cpp
  src/theory/quantifiers/theory_quantifiers.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
  src/theory/theory_engine.cpp
  src/theory/theory_state.cpp
  src/theory/theory_state.h
Labels: moderate, normal

#5819 Simplify lemma interface
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
  src/smt/term_formula_removal.cpp
  src/smt/term_formula_removal.h
  src/theory/combination_care_graph.cpp
  src/theory/combination_engine.cpp
  src/theory/combination_engine.h
  src/theory/engine_output_channel.cpp
  src/theory/engine_output_channel.h
  src/theory/fp/theory_fp.cpp
  src/theory/output_channel.cpp
  src/theory/output_channel.h
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/theory_test_utils.h
  src/theory/valuation.cpp
  src/theory/valuation.h
  test/unit/theory/theory_engine_white.h
  test/unit/theory/theory_white.h
Labels: moderate, normal

#5826 Remove regex header from cvc4cpp.cpp
  src/api/cvc4cpp.cpp
  src/api/cvc4cpp.h
  test/unit/api/term_black.cpp
  test/unit/parser/parser_black.h
Labels: normal, simple

#5828 Reorganize calls to quantifiers engine from SmtEngine layer
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  src/smt/smt_solver.cpp
  src/smt/smt_solver.h
  src/smt/sygus_solver.cpp
  src/smt/sygus_solver.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: major, moderate

#5833 (proof-new) Distinguish pre vs post rewrites in term conversion proof generator
  src/expr/term_conversion_proof_generator.cpp
  src/expr/term_conversion_proof_generator.h
  src/smt/expand_definitions.cpp
  src/smt/proof_post_processor.cpp
  src/smt/term_formula_removal.cpp
  src/smt/witness_form.cpp
  src/theory/rewriter.cpp
  src/theory/theory_preprocessor.cpp
Labels: moderate, normal

#5832 Add bag inferences for operators: intersection, duplicate_removal, and empty bags
  src/theory/bags/bag_solver.cpp
  src/theory/bags/bag_solver.h
  src/theory/bags/infer_info.cpp
  src/theory/bags/inference_generator.cpp
  src/theory/bags/inference_generator.h
  src/theory/bags/solver_state.cpp
  src/theory/bags/solver_state.h
  src/theory/bags/theory_bags.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/bags/duplicate_removal1.smt2
  test/regress/regress1/bags/duplicate_removal2.smt2
  test/regress/regress1/bags/emptybag1.smt2
  test/regress/regress1/bags/intersection_min1.smt2
  test/regress/regress1/bags/intersection_min2.smt2
Labels: moderate, normal

#5834 [proof-new] Connecting new unsat cores
  src/options/smt_options.toml
  src/smt/set_defaults.cpp
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  test/regress/regress1/fmf/PUZ001+1.smt2
Labels: normal, simple

#5838 Fix unguarded call to get representative
  src/theory/quantifiers/ematching/candidate_generator.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/qs-has-term.smt2
Labels: major, simple
