Repository cvc5/cvc5, pull requests merged in 2021-07, with the labels that each got.

#6818 Add option to limit the number of instantiation rounds
  src/options/quantifiers_options.toml
  src/theory/incomplete_id.cpp
  src/theory/incomplete_id.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/instantiate.h
  src/theory/quantifiers/quant_util.h
  src/theory/quantifiers/term_database.h
  src/theory/quantifiers/term_registry.cpp
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: moderate, normal

#6824 Add recursive function definitions to subsolver in sygus
  src/options/quantifiers_options.toml
  src/smt/optimization_solver.cpp
  src/theory/quantifiers/expr_miner.cpp
  src/theory/quantifiers/fun_def_evaluator.cpp
  src/theory/quantifiers/fun_def_evaluator.h
  src/theory/quantifiers/sygus/sygus_repair_const.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/smt_engine_subsolver.cpp
  src/theory/smt_engine_subsolver.h
  test/regress/CMakeLists.txt
  test/regress/regress2/sygus/sumn_recur_synth.sy
Labels: moderate, normal

#6825 Add reverse iterators for `Node`/`TNode`
  src/expr/node.h
  src/expr/node_value.h
  test/unit/node/node_black.cpp
Labels: moderate, normal

#6805 Refactor lexer for SMT-LIB in sphinx
  docs/ext/smtliblexer.py
Labels: moderate, normal

#6828 Fix CaDiCaL auto-download on macOS
  cmake/FindCaDiCaL.cmake
Labels: moderate, normal

#6827 Fix rewriter for negative constant seq.nth
  src/printer/smt2/smt2_printer.cpp
  src/theory/strings/sequences_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue6777-seq-nth-eval-cm.smt2
Labels: normal, simple

#6820 Fix bv assert input reset assertions
  src/theory/bv/bv_solver_bitblast.cpp
  src/theory/bv/bv_solver_bitblast.h
  test/regress/CMakeLists.txt
  test/regress/regress0/bv/reset-assertions-assert-input.smt2
Labels: major, moderate

#6826 Add output tags -o, --output.
  src/base/output.cpp
  src/options/CMakeLists.txt
  src/options/base_options.toml
  src/options/mkoptions.py
  src/options/options_handler.cpp
  src/options/options_handler.h
  src/options/outputc.cpp
  src/options/outputc.h
  src/options/quantifiers_options.toml
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  test/regress/regress0/sygus/print-debug.sy
  test/regress/regress1/quantifiers/qid-debug-inst.smt2
Labels: moderate, normal

#6832 Fix performance of string regression
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/quantifiers/fmf/model_builder.cpp
  src/theory/quantifiers_engine.cpp
  test/regress/regress1/bug590.smt2
Labels: major, moderate

#6833 Make buffered inference manager more robust to backtracking
  src/theory/inference_manager_buffered.cpp
  src/theory/inference_manager_buffered.h
  src/theory/theory.cpp
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
Labels: moderate, normal

#6837 [Strings] Fix incorrect rewrite due to stale information
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/sequences_rewriter.h
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/issue6834-str-eq-const-nhomog.smt2
Labels: major, moderate

#6755 Add doc page about transcendentals
  docs/_static/custom.css
  docs/references.bib
  docs/theories/transcendentals.rst
  docs/theory.rst
  examples/api/cpp/CMakeLists.txt
  examples/api/cpp/transcendentals.cpp
  examples/api/python/CMakeLists.txt
  examples/api/python/transcendentals.py
  examples/api/smtlib/transcendentals.smt2
Labels: moderate, normal

#6789 Porting C++ API examples to SMT-LIB examples
  docs/examples/bitvectors.rst
  docs/examples/bitvectors_and_arrays.rst
  docs/examples/combination.rst
  docs/examples/datatypes.rst
  docs/examples/extract.rst
  docs/examples/sequences.rst
  docs/examples/strings.rst
  examples/api/smtlib/bitvectors.smt2
  examples/api/smtlib/bitvectors_and_arrays.smt2
  examples/api/smtlib/combination.smt2
  examples/api/smtlib/datatypes.smt2
  examples/api/smtlib/extract.smt2
  examples/api/smtlib/quickstart.smt2
  examples/api/smtlib/sequences.smt2
  examples/api/smtlib/sets.smt2
  examples/api/smtlib/strings.smt2
Labels: moderate, normal

#6842 Add learned rewrite preprocessing pass
  src/preprocessing/passes/learned_rewrite.cpp
  src/preprocessing/passes/learned_rewrite.h
Labels: moderate, normal

#6843 Add implementation of learned rewrite pass
  src/preprocessing/passes/learned_rewrite.cpp
Labels: moderate, normal

#6840 Integrate learned rewrite preprocessing pass
  src/CMakeLists.txt
  src/options/smt_options.toml
  src/preprocessing/passes/learned_rewrite.cpp
  src/preprocessing/preprocessing_pass_registry.cpp
  src/smt/process_assertions.cpp
  src/smt/set_defaults.cpp
Labels: moderate, normal

#6812 Integrate Lazard into CAD module
  src/CMakeLists.txt
  src/options/arith_options.toml
  src/theory/arith/nl/cad/cdcac.cpp
  src/theory/arith/nl/cad/projections.cpp
  test/unit/theory/CMakeLists.txt
  test/unit/theory/theory_arith_cad_white.cpp
Labels: minor, moderate

#6841 Standard output for trigger selection
  src/options/base_options.toml
  src/theory/quantifiers/ematching/inst_strategy_e_matching.cpp
  src/theory/quantifiers/ematching/trigger.cpp
Labels: moderate, normal

#6846 Fix regressions for competition build
  test/regress/regress0/sygus/print-debug.sy
  test/regress/regress1/quantifiers/qid-debug-inst.smt2
Labels: major, simple

#6849 Rename operator pow2 to int.pow2.
  src/parser/smt2/smt2.cpp
  test/regress/regress0/nl/pow2-native-0.smt2
  test/regress/regress0/nl/pow2-native-1.smt2
  test/regress/regress0/nl/pow2-native-2.smt2
  test/regress/regress0/nl/pow2-native-3.smt2
Labels: major, simple

#6851 pow2: Update NEWS.
  NEWS
Labels: normal, simple

#6852 [unsat cores] Adding regressions from #4971
  test/regress/CMakeLists.txt
  test/regress/regress0/cores/issue4971-0.smt2
  test/regress/regress0/cores/issue4971-1.smt2
  test/regress/regress0/cores/issue4971-2.smt2
Labels: normal, simple

#6853 [proof] [dot] Print let map (of terms in proof) as part of dot proof
  src/proof/dot/dot_printer.cpp
  src/proof/dot/dot_printer.h
Labels: normal, simple

#6848 Disable ordering heuristic for justification by default
  src/options/decision_options.toml
  test/regress/regress1/rels/bv1p.cvc
Labels: normal, simple

#6847 Implement stop-only for new justification heuristic
  src/decision/decision_engine.cpp
  src/decision/decision_engine.h
  src/decision/decision_engine_old.cpp
  src/decision/decision_engine_old.h
  src/decision/justification_strategy.cpp
  src/decision/justification_strategy.h
  src/options/README.md
  src/options/decision_options.toml
  src/options/options_handler.cpp
  src/options/options_handler.h
  src/prop/prop_engine.cpp
  src/prop/theory_proxy.cpp
  src/smt/set_defaults.cpp
Labels: moderate, normal

#6855 Fix sets cardinality inference involving equivalent parents
  src/theory/sets/cardinality_extension.cpp
  src/theory/sets/cardinality_extension.h
  test/regress/CMakeLists.txt
  test/regress/regress1/sets/sets-uc-wrong.smt2
Labels: moderate, normal

#6854 Use newer config.sub to fix build on Apple M1
  cmake/FindANTLR3.cmake
Labels: moderate, normal

#6857 Make regression test `issue4971-0` more robust
  test/regress/regress0/cores/issue4971-0.smt2
Labels: normal, simple

#6858 Test also with default cores
  test/regress/regress0/cores/issue4971-1.smt2
Labels: normal, simple

#6861 Improvements to debug check model
  src/theory/model_manager.cpp
  src/theory/theory_model_builder.cpp
Labels: normal, simple

#6856 Use default visibility for `cvc5::Exception`
  src/base/exception.h
Labels: major, simple

#6862 Add trace for combination splits
  src/theory/combination_care_graph.cpp
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/shared_solver.cpp
  src/theory/shared_solver.h
Labels: minor, simple

#6860 Add arithmetic preprocess rewrite equality module
  src/CMakeLists.txt
  src/theory/arith/pp_rewrite_eq.cpp
  src/theory/arith/pp_rewrite_eq.h
Labels: normal, simple

#6864 Fix ANTLR build with CMake <3.11
  cmake/FindANTLR3.cmake
Labels: major, simple

#6850 Fix for learned rewrite pass, add regression
  src/preprocessing/passes/learned_rewrite.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/nl/issue4791-llr.smt2
Labels: normal, simple

#6865 Add branch and bound module
  src/CMakeLists.txt
  src/theory/arith/branch_and_bound.cpp
  src/theory/arith/branch_and_bound.h
Labels: normal, simple

#6867 bv: Expand bitblast proof steps in the proof post processor.
  src/smt/proof_manager.cpp
  src/smt/proof_post_processor.cpp
  src/theory/bv/bitblast/proof_bitblaster.cpp
  src/theory/bv/bitblast/proof_bitblaster.h
  src/theory/bv/bv_solver_simple.cpp
  src/theory/bv/bv_solver_simple.h
  src/theory/bv/proof_checker.cpp
Labels: moderate, normal

#6868 Add branch and bound lemma if linear arithmetic generates a non-integer assignment
  src/theory/arith/arith_state.cpp
  src/theory/arith/arith_state.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
Labels: moderate, normal

#6869 bv: Do not rewrite below BV leafs in BBProof's TConvProofGenerator.
  src/expr/term_context.cpp
  src/expr/term_context.h
  src/theory/bv/bitblast/proof_bitblaster.cpp
  src/theory/bv/bitblast/proof_bitblaster.h
Labels: major, simple

#6872 [rewriter] Add rewrite to order IFF (equality for Booleans)
  src/prop/sat_proof_manager.cpp
  src/theory/booleans/theory_bool_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/proofs/open-pf-if-unordered-iff.smt2
Labels: normal, simple

#6871 bv: Simplify BV_BITBLAST_* proof rules.
  src/proof/proof_rule.cpp
  src/proof/proof_rule.h
  src/theory/bv/bitblast/proof_bitblaster.cpp
  src/theory/bv/bitblast/proof_bitblaster.h
  src/theory/bv/proof_checker.cpp
Labels: normal, simple

#6874 bv: Add missing BV_EAGER_ATOM proof rule.
  src/theory/bv/bv_solver_simple.cpp
Labels: normal, simple

#6844 Clean up option usage in command executor
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/main/command_executor.cpp
  src/main/command_executor.h
  src/main/driver_unified.cpp
  src/main/main.h
  src/main/signal_handlers.cpp
  test/regress/regress0/options/statistics.smt2
Labels: moderate, normal

#6870 Fix models for sequences of infinite element type
  src/printer/smt2/smt2_printer.cpp
  src/theory/strings/base_solver.cpp
  src/theory/strings/theory_strings.cpp
Labels: moderate, normal

#6831 Refactor setup of proof equality engine for central EE
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
  src/theory/uf/equality_engine.cpp
  src/theory/uf/equality_engine.h
Labels: moderate, normal

#6882 Move synthesis verification check to own file
  src/CMakeLists.txt
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/synth_verify.cpp
  src/theory/quantifiers/sygus/synth_verify.h
Labels: normal, simple

#6873 Fix for context on input proof generator
  src/smt/preprocess_proof_generator.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/proofs/cyclic-ucp.smt2
Labels: normal, simple

#6883 [proof] Generalize congruence handling for HO in eq proofs
  src/theory/uf/eq_proof.cpp
Labels: moderate, normal

#6884 Add option that exercises the previously buggy behavior
  test/regress/regress0/proofs/open-pf-if-unordered-iff.smt2
Labels: minor, simple

#6887 [proof] Fix open proof issues in SAT proof
  src/prop/sat_proof_manager.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/proofs/open-pf-datatypes.smt2
  test/regress/regress0/proofs/open-pf-rederivation.smt2
Labels: moderate, normal

#6888 bv: Rename simple solver to bitblast-internal.
  src/CMakeLists.txt
  src/options/bv_options.toml
  src/theory/bv/bv_solver_bitblast_internal.cpp
  src/theory/bv/bv_solver_bitblast_internal.h
  src/theory/bv/theory_bv.cpp
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  test/regress/regress0/bv/ackermann1.smt2
  test/regress/regress0/bv/bool-model.smt2
  test/regress/regress0/bv/bool-to-bv-ite.smt2
  test/regress/regress0/bv/bug734.smt2
  test/regress/regress0/bv/issue-4076.smt2
  test/regress/regress0/bv/pr4993-bvugt-bvurem-b.smt2
  test/regress/regress0/proofs/open-pf-if-unordered-iff.smt2
  test/regress/regress0/proofs/open-pf-rederivation.smt2
  test/regress/regress1/bug520.smt2
Labels: normal, simple

#6889 bv: Rename lazy solver to layered solver.
  src/CMakeLists.txt
  src/options/bv_options.toml
  src/theory/bv/bitblast/eager_bitblaster.cpp
  src/theory/bv/bitblast/eager_bitblaster.h
  src/theory/bv/bitblast/lazy_bitblaster.cpp
  src/theory/bv/bitblast/lazy_bitblaster.h
  src/theory/bv/bv_eager_solver.cpp
  src/theory/bv/bv_eager_solver.h
  src/theory/bv/bv_quick_check.cpp
  src/theory/bv/bv_quick_check.h
  src/theory/bv/bv_solver_layered.cpp
  src/theory/bv/bv_solver_layered.h
  src/theory/bv/bv_subtheory.h
  src/theory/bv/bv_subtheory_algebraic.cpp
  src/theory/bv/bv_subtheory_algebraic.h
  src/theory/bv/bv_subtheory_bitblast.cpp
  src/theory/bv/bv_subtheory_bitblast.h
  src/theory/bv/bv_subtheory_core.cpp
  src/theory/bv/bv_subtheory_core.h
  src/theory/bv/bv_subtheory_inequality.cpp
  src/theory/bv/bv_subtheory_inequality.h
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv.h
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  test/unit/theory/theory_bv_white.cpp
Labels: normal, simple

#6891 bv: Rename BBSimple to NodeBitblaster.
  src/CMakeLists.txt
  src/theory/bv/bitblast/node_bitblaster.cpp
  src/theory/bv/bitblast/node_bitblaster.h
  src/theory/bv/bitblast/proof_bitblaster.cpp
  src/theory/bv/bitblast/proof_bitblaster.h
  src/theory/bv/bv_solver_bitblast.cpp
  src/theory/bv/bv_solver_bitblast.h
  src/theory/bv/proof_checker.h
Labels: normal, simple

#6886 bv: Disable bv-assert-input if proofs are enabled.
  src/smt/set_defaults.cpp
Labels: major, simple

#6878 Add node converter utility
  src/expr/CMakeLists.txt
  src/expr/node_converter.cpp
  src/expr/node_converter.h
Labels: moderate, normal

#6877 Move master equality engine notification to own file
  src/CMakeLists.txt
  src/theory/ee_manager_distributed.cpp
  src/theory/ee_manager_distributed.h
  src/theory/quantifiers/master_eq_notify.cpp
  src/theory/quantifiers/master_eq_notify.h
Labels: normal, simple

#6876 Arithmetic equality solver
  src/theory/arith/equality_solver.cpp
  src/theory/arith/equality_solver.h
Labels: normal, simple

#6894 Connect the equality solver to theory arith
  src/CMakeLists.txt
  src/options/arith_options.toml
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
Labels: moderate, normal

#6897 Distinguish quantifiers preprocess as its own proof rule
  src/proof/proof_rule.cpp
  src/proof/proof_rule.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/proof_checker.cpp
Labels: normal, simple

#6890 Fix context for proofs of instantiations
  src/theory/quantifiers/instantiate.cpp
Labels: normal, simple

#6892 [Unit Tests] Reenable `top_scope_context_obj`
  test/unit/context/context_black.cpp
Labels: moderate, normal

#6898 [Unit Tests] Avoid linking against external libs
  test/unit/CMakeLists.txt
Labels: moderate, normal

#6899 Do not exhaustive instantiation when FMF is disabled
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/fmf/model_engine.h
Labels: moderate, normal

#6896 Add n-ary term utilities
  src/expr/CMakeLists.txt
  src/expr/nary_term_util.cpp
  src/expr/nary_term_util.h
Labels: minor, moderate

#6912 ANTLR3: Install into `CMAKE_INSTALL_LIBDIR`
  cmake/FindANTLR3.cmake
Labels: major, simple

#6907 [AUTHORS] Add CVC4 as part of CVC series
  AUTHORS
Labels: minor, simple

#6397 Add std::vector<Term> Op:: getIndices() and operator[] for Op
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  test/unit/api/op_black.cpp
Labels: normal, simple

#6915 Preparation for carry the rewrite rule database in the proof checker
  src/proof/proof_checker.cpp
  src/proof/proof_checker.h
Labels: minor, simple

#4605 Add support for minimal unsat cores
  NEWS
  src/options/smt_options.toml
  src/smt/set_defaults.cpp
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
  test/regress/CMakeLists.txt
  test/regress/regress1/minimal_unsat_core.smt2
Labels: moderate, normal

#6900 Miscellaneous changes in preparation for central equality engine
  src/theory/sets/theory_sets_private.cpp
  src/theory/shared_solver.cpp
  src/theory/theory_engine.cpp
Labels: normal, simple

#6893 Add the central equality engine manager
  src/CMakeLists.txt
  src/theory/ee_manager_central.cpp
  src/theory/ee_manager_central.h
  src/theory/theory.cpp
  src/theory/theory.h
Labels: do not merge, moderate, normal

#6885 Simplify computation of relevant terms in datatypes
  src/theory/datatypes/theory_datatypes.cpp
Labels: moderate, normal

#6904 FP: Add option to word-blast more lazily.
  src/options/fp_options.toml
  src/theory/bv/bv_solver_bitblast.h
  src/theory/fp/fp_converter.cpp
  src/theory/fp/fp_converter.h
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp.h
  test/regress/CMakeLists.txt
  test/regress/regress0/fp/word-blast.smt2
Labels: normal, simple

#6919 Fix CoCoA build for newer compilers
  cmake/FindCoCoA.cmake
  cmake/deps-utils/CoCoA-patch-0.99712.patch
Labels: normal, simple

#6921 Configuration: Indicate dependencies being built
  CMakeLists.txt
  cmake/Helpers.cmake
Labels: normal, simple

#6920 Fix CLN build
  cmake/FindCLN.cmake
Labels: normal, simple

#6902 Refactor equality engine setup for arithmetic congruence manager
  src/theory/arith/congruence_manager.cpp
  src/theory/arith/congruence_manager.h
  src/theory/arith/theory_arith_private.cpp
Labels: normal, simple

#6901 Changes to datatypes in preparation for central equality engine
  src/theory/datatypes/inference_manager.cpp
  src/theory/datatypes/theory_datatypes.cpp
Labels: normal, simple

#6927 More updates to arithmetic in preparation for central equality engine
  src/options/arith_options.toml
  src/smt/set_defaults.cpp
  src/theory/arith/equality_solver.cpp
  src/theory/arith/inference_manager.cpp
  src/theory/arith/inference_manager.h
  src/theory/arith/theory_arith_private.cpp
  src/theory/theory_inference_manager.h
Labels: moderate, normal

#6931 Enable default equality proofs for sets
  src/proof/proof_rule.cpp
  src/proof/proof_rule.h
  src/theory/builtin/proof_checker.cpp
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/sets/inference_manager.cpp
  src/theory/sets/inference_manager.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
Labels: moderate, normal

#6671 Move public options functions to separate file
  .style.yapf
  src/main/driver_unified.cpp
  src/options/CMakeLists.txt
  src/options/base_options.toml
  src/options/mkoptions.py
  src/options/options_handler.cpp
  src/options/options_public.cpp
  src/options/options_public.h
  src/options/options_public_template.cpp
  src/options/options_template.cpp
  src/options/options_template.h
  src/smt/smt_engine.cpp
  test/unit/node/node_black.cpp
Labels: moderate, normal

#6923 Add sygus enumerator callback
  src/CMakeLists.txt
  src/theory/quantifiers/sygus/sygus_enumerator_callback.cpp
  src/theory/quantifiers/sygus/sygus_enumerator_callback.h
Labels: minor, moderate

#6932 Default equality proofs for bags and separation logic
  src/theory/bags/theory_bags.cpp
  src/theory/sep/theory_sep.cpp
Labels: normal, simple

#6926 Fix eq proof conversion for constant merged parameterized ops
  src/theory/uf/eq_proof.cpp
Labels: normal, simple

#6881 Add proof letify utility
  src/CMakeLists.txt
  src/proof/proof_letify.cpp
  src/proof/proof_letify.h
Labels: minor, moderate

#6914 Miscellaneous fixes from proof-new
  src/expr/bound_var_manager.h
  src/printer/smt2/smt2_printer.cpp
Labels: minor, simple

#6937 Minor changes from proof-new
  src/util/iand.h
  test/regress/regress1/quantifiers/symmetric_unsat_7.smt2
  test/regress/regress1/strings/stoi-400million.smt2
  test/unit/theory/theory_black.cpp
Labels: minor, simple

#6938 Add regression for fixed `str.indexof_re` issue
  test/regress/CMakeLists.txt
  test/regress/regress2/strings/issue6639-replace-re-all.smt2
Labels: normal, simple

#6880 Add print expression utility
  src/proof/print_expr.cpp
  src/proof/print_expr.h
Labels: minor, moderate

#6918 Make all dependencies in the fast enumerator optional
  src/theory/datatypes/sygus_datatype_utils.cpp
  src/theory/datatypes/sygus_datatype_utils.h
  src/theory/datatypes/sygus_extension.cpp
  src/theory/datatypes/theory_datatypes_utils.h
  src/theory/quantifiers/candidate_rewrite_database.cpp
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/rcons_type_info.cpp
  src/theory/quantifiers/sygus/sygus_enumerator.cpp
  src/theory/quantifiers/sygus/sygus_enumerator.h
  src/theory/quantifiers/sygus/sygus_explain.cpp
  src/theory/quantifiers/sygus/sygus_pbe.cpp
  src/theory/quantifiers/sygus/sygus_unif.cpp
  src/theory/quantifiers/sygus/sygus_unif_io.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
Labels: minor, moderate

#6928 Minor fix for term database + central equality engine
  src/theory/quantifiers/term_database.cpp
Labels: normal, simple

#6941 Move enum value generator to own file
  src/CMakeLists.txt
  src/theory/quantifiers/sygus/enum_stream_substitution.cpp
  src/theory/quantifiers/sygus/enum_stream_substitution.h
  src/theory/quantifiers/sygus/enum_val_generator.h
  src/theory/quantifiers/sygus/sygus_enumerator.h
  src/theory/quantifiers/sygus/sygus_enumerator_basic.h
  src/theory/quantifiers/sygus/synth_conjecture.h
Labels: minor, simple

#6879 Add basic LFSC utilities
  src/CMakeLists.txt
  src/proof/lfsc/lfsc_util.cpp
  src/proof/lfsc/lfsc_util.h
  src/proof/proof_rule.cpp
  src/proof/proof_rule.h
Labels: minor, simple

#6935 Track instantiation reasons in proofs
  src/proof/proof_rule.h
  src/smt/unsat_core_manager.cpp
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/ematching/trigger.h
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/quantifiers/fmf/model_builder.h
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/instantiate.h
  src/theory/quantifiers/proof_checker.cpp
Labels: moderate, normal

#6936 proof: Add eqrange expansion rule.
  src/proof/proof_rule.cpp
  src/proof/proof_rule.h
  src/theory/arrays/proof_checker.cpp
  src/theory/arrays/skolem_cache.cpp
  src/theory/arrays/skolem_cache.h
  src/theory/arrays/theory_arrays.cpp
  src/theory/arrays/theory_arrays_rewriter.cpp
  src/theory/arrays/theory_arrays_rewriter.h
Labels: normal, simple

#6933 bv: Refactor getEqualityStatus and use for both bitblasting solvers.
  src/theory/bv/bitblast/proof_bitblaster.cpp
  src/theory/bv/bitblast/proof_bitblaster.h
  src/theory/bv/bv_solver.h
  src/theory/bv/bv_solver_bitblast.cpp
  src/theory/bv/bv_solver_bitblast.h
  src/theory/bv/bv_solver_bitblast_internal.cpp
  src/theory/bv/bv_solver_bitblast_internal.h
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv.h
Labels: normal, simple

#6948 Make extended rewriter methods const
  src/theory/quantifiers/extended_rewrite.cpp
  src/theory/quantifiers/extended_rewrite.h
Labels: minor, simple

#6922 Print link to docs preview
  docs/CMakeLists.txt
Labels: minor, simple

#6946 Only use libedit on tty inputs
  src/main/interactive_shell.cpp
  test/unit/main/interactive_shell_black.cpp
Labels: moderate, normal

#6917 Minor changes to arrays in preparation for central equality engine
  src/theory/arrays/theory_arrays.cpp
  src/theory/arrays/theory_arrays.h
Labels: moderate, normal

#6929 Minor updates to shared terms database for central equality engine
  src/theory/shared_solver.h
  src/theory/shared_solver_distributed.cpp
  src/theory/shared_solver_distributed.h
  src/theory/shared_terms_database.cpp
  src/theory/shared_terms_database.h
  src/theory/theory_engine.cpp
Labels: normal, simple

#6943 Integrate central equality engine approach into theory engine, add option and regressions
  src/options/theory_options.toml
  src/smt/set_defaults.cpp
  src/theory/combination_engine.cpp
  src/theory/theory.cpp
  src/theory/theory.h
  src/theory/theory_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/aufbv/cee-small-shared-eq.smt2
  test/regress/regress0/datatypes/canExp-dtPendingMerge.smt2
  test/regress/regress0/sets/sets-deq-dd.smt2
  test/regress/regress1/cee-bug0909-dd-scope.smt2
  test/regress/regress1/datatypes/cee-prs-small-dd2.smt2
  test/regress/regress1/push-pop/cee-prs-small.smt2
  test/regress/regress1/quantifiers/cee-npnt-dd.smt2
  test/regress/regress1/quantifiers/cee-os-delta.smt2
  test/regress/regress1/strings/cee-norn-aes-trivially.smt2
  test/regress/regress2/quantifiers/cee-event-wrong-sat.smt2
  test/regress/regress2/quantifiers/exp-trivially-dd3.smt2
Labels: moderate, normal

#6903 [proofs] Set BV solver to better proof-producing one when proofs on
  src/smt/set_defaults.cpp
  test/regress/regress0/fp/issue-5524.smt2
  test/regress/regress1/aufbv/bug348.smtv1.smt2
  test/regress/regress1/quantifiers/nested9_true-unreach-call.i_575.smt2
  test/regress/regress2/bug394.smt2
Labels: normal, simple

#6949 quickstart: Add python example to docs.
  docs/api/cpp/quickstart.rst
  docs/examples/examples.rst
  docs/examples/quickstart.rst
Labels: normal, simple

#6814 Integrate installation instructions into documentation
  INSTALL.md
  INSTALL.rst
  docs/installation/installation.rst
Labels: moderate, normal

#6954 Simplify smt2 printer
  src/printer/smt2/smt2_printer.cpp
Labels: minor, simple

#6945 Allow changing certain options while solving
  src/api/cpp/cvc5.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/options/set-after-init.smt2
Labels: normal, simple

#6952 Perform statistics printing via the API
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/main/command_executor.cpp
  src/smt/smt_engine.cpp
  src/smt/smt_engine.h
Labels: moderate, normal
