Repository cvc5/cvc5, pull requests merged in 2021-06, with the labels that each got.

#6650 Disable timeout regressions
  test/regress/CMakeLists.txt
Labels: major, simple

#6651 Use top-level substitutions in ITE simp
  src/preprocessing/passes/ite_simp.cpp
  src/theory/arith/arith_ite_utils.cpp
  src/theory/arith/arith_ite_utils.h
Labels: major, simple

#6657 docs: Restructure index page, fix style issue.
  docs/CMakeLists.txt
  docs/_static/custom.css
  docs/api/CMakeLists.txt
  docs/api/api.rst
  docs/api/cpp/CMakeLists.txt
  docs/api/cpp/Doxyfile.in
  docs/api/cpp/cpp.rst
  docs/api/cpp/datatype.rst
  docs/api/cpp/datatypeconstructor.rst
  docs/api/cpp/datatypeconstructordecl.rst
  docs/api/cpp/datatypedecl.rst
  docs/api/cpp/datatypeselector.rst
  docs/api/cpp/exceptions.rst
  docs/api/cpp/grammar.rst
  docs/api/cpp/kind.rst
  docs/api/cpp/op.rst
  docs/api/cpp/result.rst
  docs/api/cpp/roundingmode.rst
  docs/api/cpp/solver.rst
  docs/api/cpp/sort.rst
  docs/api/cpp/statistics.rst
  docs/api/cpp/term.rst
  docs/api/python/CMakeLists.txt
  docs/api/python/datatype.rst
  docs/api/python/python.rst
  docs/index.rst
Labels: normal, simple

#6659 docs: Migrate input languages page.
  docs/index.rst
  docs/languages.rst
Labels: normal, simple

#6646 Do manual squash cleanup for docs
  .github/workflows/docs_cleanup.yml
Labels: minor, moderate

#6648 Make `Options::assign()` specializations free functions
  src/options/mkoptions.py
  src/options/options_template.cpp
  src/options/options_template.h
  src/options/printer_modes.cpp
  src/options/printer_modes.h
Labels: moderate, normal

#6668 Fix issues when poly is disabled
  src/smt/set_defaults.cpp
  src/theory/arith/nl/nonlinear_extension.cpp
Labels: normal, simple

#6669 Fix issues with double negation in circuit propagator
  src/theory/booleans/proof_circuit_propagator.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/proofs/issue277-circuit-propagator.smt2
Labels: moderate, normal

#6600 Move public wrapper functions out of options class
  src/main/command_executor.cpp
  src/main/driver_unified.cpp
  src/main/interactive_shell.cpp
  src/main/main.cpp
  src/main/time_limit.cpp
  src/options/CMakeLists.txt
  src/options/options_public.cpp
  src/options/options_public.h
  src/options/options_public_functions.cpp
  src/options/options_template.h
  src/parser/parser.cpp
  src/parser/parser_builder.cpp
  src/parser/parser_builder.h
  src/parser/smt2/smt2.cpp
  src/parser/tptp/tptp.cpp
  src/smt/env.cpp
  src/smt/output_manager.cpp
  src/theory/quantifiers/expr_miner.cpp
  src/theory/quantifiers/solution_filter.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus_sampler.cpp
  src/theory/quantifiers_engine.cpp
  test/api/smt2_compliance.cpp
Labels: moderate, normal

#6649 Remove `Options::operator[]`
  src/api/cpp/cvc5.cpp
  src/options/mkoptions.py
  src/options/options_template.cpp
  src/options/options_template.h
  src/smt/env.cpp
  src/smt/env.h
  src/smt/options_manager.cpp
  src/smt/smt_engine.cpp
  src/util/resource_manager.cpp
Labels: moderate, normal

#6663 Make `STRINGS_CTN_DECOMPOSE` an explicit conflict
  src/theory/strings/extf_solver.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/issue6643-ctn-decompose-conflict.smt2
Labels: normal, simple

#6655 Fix unsat core proofs
  src/smt/proof_manager.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/bv/core/bitvec1.smtv1.smt2
  test/regress/regress0/bv/core/bitvec3.smtv1.smt2
  test/regress/regress0/bv/core/constant_core.smt2
  test/regress/regress1/datatypes/dt-param-card4-unsat.smt2
  test/regress/regress1/hole6.cvc
  test/regress/regress1/proofs/issue6625-unsat-core-proofs.smt2
  test/regress/regress1/proofs/unsat-cores-proofs.smt2
  test/regress/regress1/sets/sets-disequal.smt2
Labels: major, simple

#6670 Fix competition mode in driver
  src/main/driver_unified.cpp
Labels: major, simple

#6665 Remove option to ignore negative memberships
  src/options/strings_options.toml
  src/theory/strings/regexp_solver.cpp
  test/regress/regress1/strings/regexp002.smt2
Labels: normal, simple

#6672 Remove references to `bv-div-zero-const` in docs
  src/api/cpp/cvc5_kind.h
Labels: normal, simple

#6677 [GitHub Actions] Make caching of dependencies depend on image version
  .github/workflows/ci.yml
Labels: major, normal

#6678 Simplify automatic set-logic in smt2 parser
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
Labels: moderate, normal

#6662 docs: Migrate datatypes theory reference.
  docs/_static/custom.css
  docs/conf.py.in
  docs/ext/smtliblexer.py
  docs/index.rst
  docs/theories/datatypes.rst
  docs/theory.rst
Labels: normal, simple

#6667 Some cleanup in `mkoptions.py`
  src/options/mkoptions.py
Labels: normal, simple

#6674 Fix handling of start index in `str.indexof_re`
  src/theory/strings/term_registry.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/indexof_re-start-index.smt2
  test/regress/regress2/strings/issue6636-replace-re-all.smt2
  test/regress/regress2/strings/issue6637-replace-re-all.smt2
Labels: major, moderate

#6684 Add missing dereference
  src/main/driver_unified.cpp
Labels: major, simple

#6660 bv: Enable bitblast solver by default.
  src/options/bv_options.toml
  src/theory/bv/bv_solver_bitblast.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/bv/bv-int-collapse1.smt2
  test/regress/regress0/bv/bv-int-collapse2.smt2
  test/regress/regress0/bv/issue5396.smt2
  test/regress/regress0/issue5736.smt2
  test/regress/regress0/issue5743.smt2
  test/regress/regress0/issue5947.smt2
  test/regress/regress1/bv/bv2nat-ground.smt2
  test/regress/regress1/bv/issue3958.smt2
  test/unit/theory/theory_bv_white.cpp
Labels: normal, simple

#6687 Miscellaneous changes from central ee branch
  src/theory/combination_care_graph.cpp
  src/theory/combination_engine.cpp
  src/theory/combination_engine.h
  src/theory/shared_solver.cpp
  src/theory/shared_solver.h
Labels: minor, simple

#6689 Remove unwanted side effects in `SPLIT_EQ_STRIP_L`
  src/theory/strings/sequences_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/issue6681-split-eq-strip-l.smt2
Labels: major, normal

#6691 Support public option modules
  src/main/driver_unified.cpp
  src/main/interactive_shell.cpp
  src/options/main_options.toml
  src/options/mkoptions.py
  src/options/module_template.h
  src/options/options_public.cpp
  src/options/options_public.h
Labels: moderate, normal

#6680 (proof-new) Add debug name to lazy proof chain
  src/proof/lazy_proof.cpp
  src/proof/lazy_proof.h
  src/proof/lazy_proof_chain.cpp
  src/proof/lazy_proof_chain.h
  src/proof/proof.cpp
  src/proof/proof.h
  src/theory/booleans/circuit_propagator.cpp
Labels: minor, simple

#6682 Remove `Options::wasSetByUser()`
  src/options/mkoptions.py
  src/options/options_handler.cpp
  src/options/options_public.cpp
  src/options/options_template.h
  src/printer/printer.cpp
  src/prop/minisat/simp/SimpSolver.cc
  src/smt/options_manager.cpp
  src/smt/set_defaults.cpp
  src/smt/smt_engine.cpp
  src/theory/quantifiers/expr_miner.cpp
  src/theory/quantifiers/sygus/sygus_repair_const.cpp
Labels: moderate, normal

#6685 (proof-new) Fix missing connection in trust substitution proofs
  src/proof/proof_rule.cpp
  src/proof/proof_rule.h
  src/theory/builtin/proof_checker.cpp
  src/theory/theory.h
  src/theory/trust_substitutions.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/bv/core/bitvec1.smtv1.smt2
  test/regress/regress0/bv/core/bitvec3.smtv1.smt2
  test/regress/regress0/bv/core/constant_core.smt2
  test/regress/regress0/cores/issue3455.smt2
  test/regress/regress0/proofs/trust-subs-eq-open.smt2
Labels: moderate, normal

#6696 Fix str.update reduction
  src/theory/strings/theory_strings_preprocess.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue6653-2-update-c-len.smt2
Labels: major, simple

#6695 Make TheoryUF compatible with central equality engine
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf.h
Labels: moderate, normal

#6693 Remove `binary_name` option
  src/main/driver_unified.cpp
  src/main/main.h
  src/main/signal_handlers.cpp
  src/options/base_options.toml
  src/options/options_public.cpp
  src/options/options_public.h
  src/options/options_template.cpp
  src/options/options_template.h
  test/unit/node/node_black.cpp
Labels: moderate, normal

#6705 Make env hold a pointer to the original options
  src/smt/env.cpp
  src/smt/env.h
Labels: normal, simple

#6709 Add learned literal manager utility
  src/CMakeLists.txt
  src/preprocessing/learned_literal_manager.cpp
  src/preprocessing/learned_literal_manager.h
Labels: moderate, normal

#6710 Fix for 2 dimensional dependent bounded quantifiers
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/rep_set.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue6635-rre.smt2
  test/regress/regress1/strings/issue6653-4-rre.smt2
  test/regress/regress1/strings/issue6653-rre-small.smt2
  test/regress/regress1/strings/issue6653-rre.smt2
Labels: major, simple

#6712 docs: Fix `Kind` description
  docs/api/cpp/kind.rst
  src/api/cpp/cvc5_kind.h
Labels: minor, simple

#6702 docs: Migrate separation logic theory reference.
  docs/ext/smtliblexer.py
  docs/theories/separation-logic.rst
  docs/theory.rst
Labels: normal, simple

#6714 Require statistics for regression
  test/regress/regress0/options/statistics.smt2
Labels: major, simple

#6707 Removing spurious HO checks
  src/expr/node_manager.cpp
  src/expr/node_manager.h
Labels: normal, simple

#6704 Update options for SMT-COMP
  contrib/competitions/smt-comp/run-script-smtcomp-current
  contrib/competitions/smt-comp/run-script-smtcomp-current-incremental
  contrib/competitions/smt-comp/run-script-smtcomp-current-model-validation
  contrib/competitions/smt-comp/run-script-smtcomp-current-unsat-cores
Labels: major, simple

#6715 Push complex check inside GetInstantiationsCommand
  src/main/command_executor.cpp
  src/smt/command.cpp
  src/smt/command.h
Labels: moderate, normal

#6679 Fixes related to printing tuples, define-fun commands in smt2
  src/printer/smt2/smt2_printer.cpp
  src/smt/command.cpp
Labels: minor, simple

#6718 Integrate learned literal manager into preprocessing pass context
  src/preprocessing/learned_literal_manager.cpp
  src/preprocessing/learned_literal_manager.h
  src/preprocessing/passes/non_clausal_simp.cpp
  src/preprocessing/preprocessing_pass_context.cpp
  src/preprocessing/preprocessing_pass_context.h
Labels: normal, simple

#6713 Make squashing more robust
  .github/workflows/docs_cleanup.yml
Labels: normal, simple

#6723 Reorder ITE rewrites
  src/theory/booleans/theory_bool_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/bool/issue6717-ite-rewrite.smt2
Labels: normal, simple

#6666 Update CVC4 URLs/macros
  src/api/cpp/cvc5.h
  src/api/cpp/cvc5_kind.h
  src/api/java/cvc5/Result.java
  src/base/configuration.cpp
  src/decision/decision_engine_old.h
  src/expr/dtype.cpp
  src/expr/node.h
Labels: normal, simple

#6722 Make `--solve-int-as-bv=X` robust to rewriting
  src/preprocessing/passes/int_to_bv.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/int-to-bv/basic.smt2
  test/regress/regress0/int-to-bv/neg-consts.smt2
  test/regress/regress0/int-to-bv/not-enough-bits.smt2
  test/regress/regress0/int-to-bv/overflow.smt2
Labels: major, moderate

#6698 docs: Migrate sets and relations theory reference.
  docs/examples/examples.rst
  docs/examples/relations.rst
  docs/examples/sets.rst
  docs/ext/examples.py
  docs/ext/smtliblexer.py
  docs/theories/datatypes.rst
  docs/theories/sets-and-relations.rst
  docs/theory.rst
  examples/api/cpp/sets.cpp
  examples/api/smtlib/relations.smt2
  examples/api/smtlib/sets.smt2
Labels: normal, simple

#6721 smtcomp: Use QF_BV config for QF_UFBV.
  contrib/competitions/smt-comp/run-script-smtcomp-current
  contrib/competitions/smt-comp/run-script-smtcomp-current-incremental
Labels: major, simple

#6725 Ensure bv2nat and int2bv are not rewritten when using solve-bv-as-int
  src/preprocessing/passes/bv_to_int.cpp
  src/smt/set_defaults.cpp
  src/theory/bv/theory_bv_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/bv/bv-int-collapse1.smt2
  test/regress/regress0/bv/bv-int-collapse2.smt2
  test/regress/regress0/bv/bv2nat-simp-range.smt2
  test/regress/regress1/bv/bv2nat-ground.smt2
  test/regress/regress1/bv2int-isabelle.smt2
  test/regress/regress2/bv_to_int_mask_array_1.smt2
Labels: moderate, normal

#6732 Add skeleton for new Lazard evaluation
  src/CMakeLists.txt
  src/theory/arith/nl/cad/lazard_evaluation.cpp
  src/theory/arith/nl/cad/lazard_evaluation.h
Labels: moderate, normal

#6737 Minor simplifications to LogicInfo
  src/theory/logic_info.cpp
Labels: minor, simple

#6739 Final update to SMT-COMP 2021 options
  contrib/competitions/smt-comp/run-script-smtcomp-current
  contrib/competitions/smt-comp/run-script-smtcomp-current-incremental
  contrib/competitions/smt-comp/run-script-smtcomp-current-model-validation
  contrib/competitions/smt-comp/run-script-smtcomp-current-unsat-cores
Labels: major, simple

#6729 docs: Add references instead of links in theory reference pages.
  docs/references.bib
  docs/theories/datatypes.rst
  docs/theories/separation-logic.rst
  docs/theories/sets-and-relations.rst
Labels: normal, simple

#6746 CVC4 -> cvc5 in cpp API examples
  examples/api/cpp/bitvectors.cpp
  examples/api/cpp/bitvectors_and_arrays.cpp
  examples/api/cpp/datatypes.cpp
  examples/api/cpp/extract.cpp
  examples/api/cpp/helloworld.cpp
  examples/api/cpp/linear_arith.cpp
  examples/api/cpp/sequences.cpp
  examples/api/cpp/sets.cpp
  examples/api/cpp/strings.cpp
Labels: minor, simple

#6747 docs: Fix reference in sep logic reference.
  docs/theories/separation-logic.rst
Labels: normal, simple

#6716 Remove public option wrappers
  src/api/cpp/cvc5.cpp
  src/main/command_executor.cpp
  src/main/driver_unified.cpp
  src/main/interactive_shell.cpp
  src/main/main.cpp
  src/main/time_limit.cpp
  src/options/CMakeLists.txt
  src/options/base_options.toml
  src/options/main_options.toml
  src/options/options_handler.cpp
  src/options/options_public.cpp
  src/options/options_public.h
  src/options/parser_options.toml
  src/options/resource_manager_options.toml
  src/options/smt_options.toml
  src/parser/parser.cpp
  src/parser/parser_builder.cpp
  src/parser/smt2/smt2.cpp
  src/preprocessing/passes/ackermann.cpp
  src/preprocessing/passes/int_to_bv.cpp
  src/preprocessing/passes/ite_simp.cpp
  src/preprocessing/passes/miplib_trick.cpp
  src/prop/minisat/core/Solver.cc
  src/smt/command.cpp
  src/smt/preprocessor.cpp
  src/smt/set_defaults.cpp
  src/smt/smt_engine.cpp
  src/smt/smt_engine_state.cpp
  src/smt/sygus_solver.cpp
  src/theory/arith/arith_ite_utils.cpp
  src/theory/arith/theory_arith_private.cpp
  src/theory/bv/bitblast/eager_bitblaster.cpp
  src/theory/bv/bv_eager_solver.cpp
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/term_registry.cpp
  src/util/resource_manager.cpp
  test/api/smt2_compliance.cpp
Labels: moderate, normal

#6731 Add configuration for CoCoALib
  CMakeLists.txt
  cmake/FindCoCoA.cmake
  configure.sh
Labels: moderate, normal

#6730 Update to a more recent libpoly version
  cmake/FindPoly.cmake
Labels: minor, simple

#6683 Properly consider aliases in option handlers
  src/options/CMakeLists.txt
  src/options/README
  src/options/README.md
  src/options/base_handlers.h
  src/options/mkoptions.py
  src/options/options_handler.cpp
  src/options/options_handler.h
  src/options/options_template.cpp
  src/options/prop_options.toml
Labels: moderate, normal

#6748 Archive SMT-COMP 2021 run scripts
  contrib/competitions/smt-comp/run-script-smtcomp2021
  contrib/competitions/smt-comp/run-script-smtcomp2021-incremental
  contrib/competitions/smt-comp/run-script-smtcomp2021-model-validation
  contrib/competitions/smt-comp/run-script-smtcomp2021-unsat-cores
Labels: minor, simple

#6759 Fix build without libpoly
  src/theory/arith/nl/cad/lazard_evaluation.cpp
  src/theory/arith/nl/cad/lazard_evaluation.h
  test/regress/regress0/nl/issue3003.smt2
Labels: normal, simple

#6764 Fix CaDiCaL build on Windows
  cmake/FindCaDiCaL.cmake
Labels: major, simple

#6762 Remove obsolete libpoly patch
  cmake/FindPoly.cmake
  cmake/deps-utils/Poly-patch-cmake.patch
Labels: major, simple

#6757 Make CnfStream::toCNF iterative
  src/prop/cnf_stream.cpp
  src/prop/cnf_stream.h
  src/prop/proof_cnf_stream.h
  test/api/CMakeLists.txt
  test/api/issue6111.cpp
Labels: moderate, normal

#6771 docs: Remove 'View page source' link in right corner.
  docs/conf.py.in
Labels: normal, simple

#6768 [CI] Build with all available cores
  .github/workflows/ci.yml
Labels: normal, simple

#6767 docs: Fix config to produce unique Sphinx section labels.
  docs/conf.py.in
  docs/examples/examples.rst
Labels: normal, simple

#6770 [proof] Fix documentation of array rule
  src/proof/proof_rule.h
Labels: minor, simple

#6761 Make CaDiCaL a required dependency.
  CMakeLists.txt
  NEWS
  configure.sh
  src/CMakeLists.txt
  src/base/configuration.cpp
  src/base/configuration.h
  src/base/configuration_private.h
  src/options/options_handler.cpp
  src/options/options_handler.h
  src/prop/cadical.cpp
  src/prop/cadical.h
  src/prop/sat_solver_factory.cpp
  test/regress/regress0/bv/eager-inc-cadical.smt2
Labels: normal, simple

#6769 Move cnfConversionTime statistic to CnfStream.
  src/prop/cnf_stream.cpp
  src/prop/cnf_stream.h
  src/prop/prop_engine.cpp
  src/smt/smt_engine_stats.cpp
  src/smt/smt_engine_stats.h
  src/smt/smt_solver.cpp
  src/theory/bv/bv_solver_bitblast.cpp
Labels: normal, simple

#6388 Add Grammar.java to the java API
  src/api/java/cvc5/Grammar.java
  src/api/java/jni/cvc5_Grammar.cpp
  test/unit/api/java/cvc5/GrammarTest.java
Labels: normal, simple

#6753 Fix model issues with --bitblast=eager.
  src/theory/bv/bitblast/simple_bitblaster.cpp
  src/theory/bv/bitblast/simple_bitblaster.h
  src/theory/bv/bv_solver.h
  src/theory/bv/bv_solver_bitblast.cpp
  src/theory/bv/bv_solver_bitblast.h
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv.h
  test/regress/CMakeLists.txt
  test/regress/regress0/issue6741.smt2
Labels: normal, simple

#6772 [Attributes] Remove parameter `context_dependent`
  src/expr/attribute.h
  src/expr/attribute_internals.h
  test/unit/node/attribute_white.cpp
Labels: normal, simple

#6781 docs: Split out and merge C++ class hierarchy.
  docs/_static/custom.css
  docs/api/cpp/class_hierarchy.rst
  docs/api/cpp/cpp.rst
Labels: normal, simple

#6780 Update to CaDiCaL 1.4.1.
  cmake/FindCaDiCaL.cmake
Labels: normal, simple

#6734 Set up fine grained equality notifications
  src/theory/arrays/theory_arrays.cpp
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/ee_setup_info.h
  src/theory/sep/theory_sep.cpp
  src/theory/sets/theory_sets.cpp
  src/theory/strings/term_registry.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/uf/theory_uf.cpp
Labels: moderate, normal

#6783 Fix cases of ITE within regular expressions
  src/theory/strings/regexp_entail.cpp
Labels: normal, simple

#6719 Fix type enumeration for non first-class sorts in FMF
  src/theory/quantifiers/fmf/full_model_check.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/fmf/issue6690-re-enum.smt2
Labels: minor, simple

#6720 Always check legal eliminations in quantified logics
  src/theory/theory.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue6699-nc-shadow.smt2
Labels: normal, simple

#6726 Minor simplification to equality engine notifications
  src/theory/uf/equality_engine.cpp
  src/theory/uf/equality_engine.h
Labels: minor, simple

#6787 Avoid full normalization of lambdas in getValue
  src/theory/theory_model.cpp
  test/regress/regress0/define-fun-model.smt2
Labels: normal, simple

#6745 Remove `--tear-down-incremental`
  src/main/driver_unified.cpp
  src/options/main_options.toml
Labels: normal, simple

#6786 FP: Remove sections guarded with undefined macro SYMFPUPROPISBOOL.
  src/theory/fp/fp_expand_defs.cpp
  src/theory/fp/theory_fp.cpp
Labels: normal, simple

#6782 docs: Add quickstart guide.
  docs/api/cpp/cpp.rst
  docs/api/cpp/quickstart.rst
  docs/ext/smtliblexer.py
  examples/api/cpp/quickstart.cpp
  examples/api/smtlib/quickstart.smt2
Labels: normal, simple

#6735 [proofs] [dot] Adding a counter for subproofs
  src/proof/dot/dot_printer.cpp
  src/proof/dot/dot_printer.h
Labels: minor, simple

#6791 [regressions] Adding regression from #5371
  test/regress/CMakeLists.txt
  test/regress/regress0/ho/issue5371.smt2
Labels: minor, simple

#6792 [hol] Disable bound fmf when HOL
  src/smt/set_defaults.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/ho/issue6536.smt2
Labels: normal, simple

#6733 Add implementation for Lazard evaluation
  src/theory/arith/nl/cad/lazard_evaluation.cpp
Labels: complex, normal

#6784 Fix linear arithmetic for duplicate lemmas in incremental
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
  test/regress/CMakeLists.txt
  test/regress/regress1/push-pop/issue6773-arith-no-check.smt2
Labels: major, simple

#6796 cmake: Add new code coverage targets.
  CMakeLists.txt
  cmake/CodeCoverage.cmake
Labels: normal, simple

#6795 api: getRealValue: Fix printing of integer values.
  docs/api/cpp/quickstart.rst
  src/api/cpp/cvc5.cpp
  test/unit/api/term_black.cpp
Labels: normal, simple

#6799 [proof] [dot] Make dot printer stateful
  src/proof/dot/dot_printer.cpp
  src/proof/dot/dot_printer.h
  src/smt/proof_manager.cpp
Labels: normal, simple

#6797 Rename internal string kinds to match API
  src/api/cpp/cvc5.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/datatypes/sygus_extension.cpp
  src/theory/evaluator.cpp
  src/theory/quantifiers/sygus/sygus_invariance.cpp
  src/theory/quantifiers/sygus/sygus_unif_io.cpp
  src/theory/quantifiers/term_util.cpp
  src/theory/strings/arith_entail.cpp
  src/theory/strings/extf_solver.cpp
  src/theory/strings/kinds
  src/theory/strings/regexp_elim.cpp
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/skolem_cache.cpp
  src/theory/strings/strings_entail.cpp
  src/theory/strings/term_registry.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/theory_strings_utils.cpp
  src/theory/subs_minimize.cpp
  test/unit/theory/evaluator_white.cpp
  test/unit/theory/sequences_rewriter_white.cpp
  test/unit/theory/theory_strings_skolem_cache_black.cpp
Labels: normal, simple

#6802 FP: Refactor, rewrite and clean up word blasting.
  src/theory/fp/fp_converter.cpp
Labels: moderate, normal

#6810 Fix statistics in AigBitblaster.
  src/theory/bv/bitblast/aig_bitblaster.cpp
  src/theory/bv/bitblast/aig_bitblaster.h
Labels: major, simple

#6794 Add new variants for the CAD projection
  src/theory/arith/nl/cad/cdcac.cpp
  src/theory/arith/nl/cad/cdcac.h
Labels: moderate, normal

#6801 Fix pre vs. post-rewrite in proofs for theory preprocessor
  src/proof/conv_proof_generator.cpp
  src/theory/theory_preprocessor.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/preprocess/issue6754-tpp.smt2
Labels: moderate, normal

#6816 Do not apply fmfBound to standard quantifiers when only stringsExp is enabled
  src/smt/set_defaults.cpp
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/quantifiers_modules.cpp
  src/theory/strings/regexp_elim.cpp
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/theory_strings_preprocess.h
  src/theory/strings/theory_strings_utils.cpp
  src/theory/strings/theory_strings_utils.h
  test/regress/CMakeLists.txt
  test/regress/regress1/fmf/bug651.smt2
  test/regress/regress1/quantifiers/issue3537.smt2
  test/regress/regress1/strings/seq-quant-infinite-branch.smt2
Labels: moderate, normal

#6817 Do not notify during equality engine initialization
  src/theory/uf/equality_engine.cpp
  src/theory/uf/equality_engine.h
Labels: major, simple

#6815 Fix pruning of old docs
  .github/workflows/docs_cleanup.yml
Labels: normal, simple

#6758 Use SAT context level for --bv-assert-input instead of decision level.
  src/prop/minisat/minisat.cpp
  src/prop/minisat/minisat.h
  src/prop/prop_engine.h
  src/theory/bv/bv_solver_bitblast.cpp
  src/theory/valuation.h
  test/regress/CMakeLists.txt
  test/regress/regress0/issue6738.smt2
Labels: normal, simple
