Repository cvc5/cvc5, pull requests merged in 2022-06, with the labels that each got.

#8827 Refactor how options are passed to the printer
  src/CMakeLists.txt
  src/expr/node.h
  src/expr/node_value.cpp
  src/expr/node_value.h
  src/expr/type_node.cpp
  src/expr/type_node.h
  src/options/base_options.toml
  src/options/bv_options.toml
  src/options/expr_options.toml
  src/options/io_utils.cpp
  src/options/io_utils_template.cpp
  src/options/io_utils_template.h
  src/options/mkoptions.py
  src/options/options_handler.cpp
  src/options/options_handler.h
  src/options/options_public_template.cpp
  src/options/printer_options.toml
  src/options/proof_options.toml
  src/printer/ast/ast_printer.cpp
  src/printer/ast/ast_printer.h
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/printer/tptp/tptp_printer.cpp
  src/printer/tptp/tptp_printer.h
  src/proof/dot/dot_printer.cpp
  src/proof/lfsc/lfsc_node_converter.cpp
  src/proof/lfsc/lfsc_print_channel.cpp
  src/proof/unsat_core.cpp
  src/smt/command.cpp
  src/smt/command.h
  src/smt/env.cpp
  src/smt/env.h
  src/smt/model.cpp
  src/smt/optimization_solver.cpp
  src/smt/process_assertions.cpp
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  src/theory/quantifiers/instantiation_list.cpp
  src/theory/quantifiers/query_generator.cpp
  src/theory/quantifiers/term_database.cpp
  src/util/result.cpp
  test/unit/node/node_black.cpp
  test/unit/printer/smt2_printer_black.cpp
  test/unit/theory/theory_arith_coverings_white.cpp
  test/unit/util/boolean_simplification_black.cpp
Labels: normal, moderate

#8840 Make interpolation robust to conjectures with no shared variables
  src/theory/quantifiers/sygus/sygus_interpol.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/issue8833-interpol-no-shared-var.smt2
Labels: normal, simple

#8844 Fix missing conclusion for sep pto neg prop
  src/theory/sep/theory_sep.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/sep/issue8841-neg-prop.smt2
Labels: major, simple

#8850 [proofs] [sat] [cores] Fix unsat cores based on the SAT proof
  src/prop/proof_cnf_stream.cpp
  src/prop/prop_engine.cpp
Labels: normal, moderate

#8779 Preparation for SEQ_NTH applied to strings
  src/printer/smt2/smt2_printer.cpp
  src/theory/evaluator.cpp
  src/theory/strings/array_core_solver.cpp
  src/theory/strings/array_solver.cpp
  src/theory/strings/base_solver.cpp
  src/theory/strings/core_solver.cpp
  src/theory/strings/extf_solver.cpp
  src/theory/strings/proof_checker.cpp
  src/theory/strings/rewrites.cpp
  src/theory/strings/rewrites.h
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/strings_rewriter.cpp
  src/theory/strings/strings_rewriter.h
  src/theory/strings/term_registry.cpp
  src/theory/strings/term_registry.h
  src/theory/strings/theory_strings_type_rules.cpp
  test/regress/cli/regress0/seq/seq-nth-type-check.smt2
Labels: normal, moderate

#8825 Eliminate static options access from pattern term selector
  src/theory/quantifiers/ematching/inst_strategy_e_matching.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching_user.cpp
  src/theory/quantifiers/ematching/pattern_term_selector.cpp
  src/theory/quantifiers/ematching/pattern_term_selector.h
  src/theory/quantifiers/quantifiers_macros.cpp
  src/theory/quantifiers/quantifiers_macros.h
  src/theory/quantifiers/theory_quantifiers.cpp
Labels: minor, simple

#8830 Disable arithmetic static learning when unsat cores are enabled
  src/api/cpp/cvc5.cpp
  src/options/arith_options.toml
  src/options/smt_options.toml
  src/prop/minisat/core/Solver.cc
  src/prop/minisat/minisat.cpp
  src/prop/minisat/simp/SimpSolver.cc
  src/smt/process_assertions.cpp
  src/smt/set_defaults.cpp
  src/smt/solver_engine.cpp
  src/theory/arith/theory_arith.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/cores/issue8822-arith-static-learn.smt2
  test/regress/cli/regress1/nl/issue4791-llr.smt2
  test/regress/cli/regress2/quantifiers/cee-event-wrong-sat.smt2
Labels: normal, moderate

#8845 Fix check for whether a term contains an uninterpreted constant
  src/theory/quantifiers/term_util.cpp
Labels: minor, moderate

#8849 Add inference rules for set.map operator
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/theory/incomplete_id.cpp
  src/theory/incomplete_id.h
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/sets/solver_state.cpp
  src/theory/sets/solver_state.h
  src/theory/sets/term_registry.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
  src/theory/sets/theory_sets_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/sets/set_map_card_incomplete.smt2
  test/regress/cli/regress1/sets/set_map_negative_members.smt2
  test/regress/cli/regress1/sets/set_map_positive_members.smt2
  test/regress/cli/regress1/sets/set_map_unsat1.smt2
Labels: normal, moderate

#8853 Fix corner case of interpolants from conjectures with no free variables
  src/theory/quantifiers/sygus/sygus_interpol.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/issue8852-interpol-no-var.smt2
Labels: minor, simple

#8855 Disable LFSC for regression with learned rewrite
  test/regress/cli/regress1/nl/issue4791-llr.smt2
Labels: major, simple

#8815 Add declareOracleFun to the Java API
  src/api/java/CMakeLists.txt
  src/api/java/io/github/cvc5/IOracle.java
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/jni/api_utilities.cpp
  src/api/java/jni/api_utilities.h
  src/api/java/jni/solver.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/java/SortTest.java
  test/unit/api/java/TermTest.java
Labels: normal, moderate

#8858 Add MBQI to SMT comp script
  contrib/competitions/smt-comp/run-script-smtcomp-current
Labels: normal, simple

#8857 Disable `lfsc` tester if `proof` tester is disabled.
  test/regress/cli/README.md
  test/regress/cli/regress0/deep-restart/dd.fuzz21.smtv1.smt2
  test/regress/cli/regress0/deep-restart/dd.wrong-sat-020322.smt2
  test/regress/cli/regress0/quantifiers/lra-triv-gn.smt2
  test/regress/cli/regress1/datatypes/dt-param-card4-unsat.smt2
  test/regress/cli/regress1/hole6.cvc.smt2
  test/regress/cli/regress1/issue3970-nl-ext-purify.smt2
  test/regress/cli/regress1/nl/approx-sqrt-unsat.smt2
  test/regress/cli/regress1/nl/issue4791-llr.smt2
  test/regress/cli/regress1/quantifiers/issue4021-ind-opts.smt2
  test/regress/cli/regress1/sets/sets-disequal.smt2
  test/regress/cli/regress1/sygus/issue3201.smt2
  test/regress/cli/regress1/sygus/issue3247.smt2
  test/regress/cli/regress1/sygus/issue3995-fmf-var-op.smt2
  test/regress/cli/regress1/sygus/issue4009-qep.smt2
  test/regress/cli/regress1/sygus/issue4083-var-shadow.smt2
  test/regress/cli/regress1/sygus/issue4425-sets-sygus-infer.smt2
  test/regress/cli/regress1/sygus/proj-issue185.smt2
  test/regress/cli/regress2/fp/issue7056.smt2
  test/regress/cli/regress2/instance_1444.smtv1.smt2
  test/regress/cli/regress2/nl/ufnia-factor-open-proof.smt2
  test/regress/cli/run_regression.py
Labels: normal, minor

#8846 [CMake] Improve FindGMP
  cmake/FindGMP.cmake
  cmake/deps-utils/gmp-test.cpp
Labels: normal, moderate

#8851 Use STRING_NTH in strings reductions and eliminate STRING_TO_CODE
  src/options/strings_options.toml
  src/theory/strings/arith_entail.cpp
  src/theory/strings/core_solver.cpp
  src/theory/strings/term_registry.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/theory_strings_preprocess.h
  test/api/cpp/proj-issue334.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arith/projissue469-int-equality.smt2
  test/regress/cli/regress0/strings/issue5771-eager-pp.smt2
  test/regress/cli/regress0/strings/issue5816-re-kind.smt2
  test/regress/cli/regress0/strings/issue8722-learned-rew.smt2
  test/regress/cli/regress0/strings/model-code-point.smt2
  test/regress/cli/regress1/decision/jh-test1.smt2
  test/regress/cli/regress1/strings/cee-norn-aes-trivially.smt2
  test/regress/cli/regress1/strings/str-code-sat.smt2
  test/regress/cli/regress1/strings/to_upper_12.smt2
  test/regress/cli/regress1/strings/to_upper_over_concat.smt2
Labels: normal, moderate

#8860 Add set.map signature to lfsc
  proofs/lfsc/signatures/theory_def.plf
  src/theory/sets/theory_sets_private.cpp
Labels: major, simple

#8862 Add str.unit to LFSC signature
  proofs/lfsc/signatures/theory_def.plf
Labels: major, simple

#8856 Add set.filter operator and its inference rules
  proofs/lfsc/signatures/theory_def.plf
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_kind.h
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/bags/bag_solver.cpp
  src/theory/bags/inference_generator.cpp
  src/theory/bags/inference_generator.h
  src/theory/bags/kinds
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/sets/kinds
  src/theory/sets/solver_state.cpp
  src/theory/sets/solver_state.h
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
  src/theory/sets/theory_sets_rewriter.cpp
  src/theory/sets/theory_sets_rewriter.h
  src/theory/sets/theory_sets_type_rules.cpp
  src/theory/sets/theory_sets_type_rules.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/bags/filter3.smt2
  test/regress/cli/regress1/sets/set_filter1.smt2
  test/regress/cli/regress1/sets/set_filter2.smt2
  test/regress/cli/regress1/sets/set_filter3.smt2
  test/regress/cli/regress1/sets/set_filter4.smt2
Labels: normal, moderate

#8865 Allow mixed int/real equalities in non-strict parsing mode
  src/parser/smt2/smt2.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/non-strict-real-vs-int.smt2
Labels: normal, simple

#8866 Move slow regression
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress3/proofs/sat-proof-reloaded-reason.smt2
Labels: normal, simple

#8870 [Java API] Do not link JNI libraries
  examples/CMakeLists.txt
  examples/api/java/CMakeLists.txt
  src/api/java/CMakeLists.txt
Labels: normal, moderate

#8874 [Win64] Use `CC_FOR_BUILD` when compiling GMP
  cmake/FindGMP.cmake
Labels: normal, moderate

#8877 bv sat solvers: Update CaDiCaL and Kissat to most recent release versions.
  cmake/FindCaDiCaL.cmake
  cmake/FindKissat.cmake
Labels: normal, simple

#8882 [Regressions] Disable ASan on slow regression
  test/regress/cli/regress1/arith/issue3480.smt2
Labels: major, simple

#8885 [CMake] Remove redundant code
  cmake/FindEditline.cmake
Labels: minor, simple

#8886 Add support for operators with same payload
  src/api/cpp/cvc5.cpp
Labels: normal, simple

#8889 Remove redundant projection operators
  src/CMakeLists.txt
  src/api/cpp/cvc5.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/bags/bag_reduction.cpp
  src/theory/bags/bags_utils.cpp
  src/theory/bags/inference_generator.cpp
  src/theory/bags/kinds
  src/theory/bags/table_project_op.cpp
  src/theory/bags/table_project_op.h
  src/theory/bags/theory_bags_type_rules.cpp
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/kinds
  src/theory/datatypes/project_op.cpp
  src/theory/datatypes/project_op.h
  src/theory/datatypes/theory_datatypes_type_rules.cpp
Labels: normal, simple

#8892 Remove unused `DeclarationSequence` command
  src/printer/ast/ast_printer.cpp
  src/printer/ast/ast_printer.h
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/smt/command.cpp
  src/smt/command.h
Labels: normal, simple

#8894 [Parser] Rename generated `.c` to `.cpp` files
  src/parser/CMakeLists.txt
Labels: normal, moderate

#8891 Add type to uninterpreted constant values
  src/printer/smt2/smt2_printer.cpp
  src/util/uninterpreted_sort_value.cpp
  test/regress/cli/regress0/models-print-2.smt2
  test/regress/cli/regress0/parser/issue6908-get-value-uc.smt2
Labels: minor, simple

#8897 Fix sort inference for equality over finite types
  src/theory/sort_inference.cpp
  src/theory/sort_inference.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/datatypes/issue8883-sort-inf.smt2
Labels: normal, simple

#8907 Fix rewrite for `(to_int real.pi)`
  src/theory/arith/arith_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arith/issue8905-pi-to-int.smt2
Labels: normal, simple

#8867 Add set.fold operator
  proofs/lfsc/signatures/theory_def.plf
  src/CMakeLists.txt
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_kind.h
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/sets/kinds
  src/theory/sets/set_reduction.cpp
  src/theory/sets/set_reduction.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_rewriter.cpp
  src/theory/sets/theory_sets_rewriter.h
  src/theory/sets/theory_sets_type_rules.cpp
  src/theory/sets/theory_sets_type_rules.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/sets/set_fold1.smt2
  test/regress/cli/regress1/sets/set_fold2.smt2
  test/regress/cli/regress1/sets/set_fold3.smt2
Labels: normal, moderate

#8908 Fix explanation for strings unit oob inference
  src/theory/strings/base_solver.cpp
  src/theory/uf/equality_engine.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/strings/issue8906-oob-exp.smt2
Labels: major, simple

#8909 Move non-stream options out of `printer_options.toml`
  src/options/main_options.toml
  src/options/printer_options.toml
  src/options/proof_options.toml
  src/options/quantifiers_options.toml
  src/options/smt_options.toml
  src/printer/ast/ast_printer.cpp
  src/printer/smt2/smt2_printer.cpp
  src/proof/dot/dot_printer.cpp
  src/proof/dot/dot_printer.h
  src/smt/command.cpp
  src/smt/command.h
  src/smt/proof_manager.cpp
  src/smt/solver_engine.cpp
  src/theory/quantifiers/instantiate.cpp
Labels: normal, moderate

#8904 Remove `CommandSequence` command
  src/main/command_executor.cpp
  src/main/driver_unified.cpp
  src/main/interactive_shell.cpp
  src/main/interactive_shell.h
  src/parser/smt2/Smt2.g
  src/parser/tptp/Tptp.g
  src/printer/ast/ast_printer.cpp
  src/printer/ast/ast_printer.h
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/smt/command.cpp
  src/smt/command.h
  test/unit/main/interactive_shell_black.cpp
Labels: normal, moderate

#8819 Add inference rules for table.group
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/theory/bags/bag_solver.cpp
  src/theory/bags/bag_solver.h
  src/theory/bags/bags_utils.cpp
  src/theory/bags/inference_generator.cpp
  src/theory/bags/inference_generator.h
  src/theory/bags/solver_state.cpp
  src/theory/bags/solver_state.h
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/bags/table_group2.smt2
  test/regress/cli/regress1/bags/table_group3.smt2
  test/regress/cli/regress1/bags/table_group4.smt2
  test/regress/cli/regress1/bags/table_group5.smt2
Labels: normal, moderate

#8917 Fix model construction for str.unit
  src/theory/strings/theory_strings.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/strings/issue8915-str-unit-model.smt2
Labels: major, simple

#8919 Fix reduction for seq.nth for strings
  src/preprocessing/passes/strings_eager_pp.cpp
  src/theory/strings/extf_solver.cpp
  src/theory/strings/proof_checker.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/theory_strings_preprocess.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/strings/issue8918-str-nth-crange-red.smt2
Labels: major, simple

#8878 Add set.aggr operator to sets
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_kind.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/sets/kinds
  src/theory/sets/rels_utils.cpp
  src/theory/sets/rels_utils.h
  src/theory/sets/set_reduction.cpp
  src/theory/sets/set_reduction.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets_rewriter.cpp
  src/theory/sets/theory_sets_rewriter.h
  src/theory/sets/theory_sets_type_rules.cpp
  src/theory/sets/theory_sets_type_rules.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/sets/relation_aggregate1.smt2
Labels: normal, moderate

#8921 Fix type issue in substitutions from covering solver
  src/theory/arith/nl/coverings_solver.cpp
  src/theory/arith/nl/nl_model.cpp
  src/theory/arith/theory_arith.cpp
Labels: minor, simple

#8920 Fix injectivity inferences for seq.nth applied to strings
  src/theory/strings/base_solver.cpp
  src/theory/strings/base_solver.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/strings/issue8916-str-unit-pairs.smt2
Labels: major, moderate

#8922 [SMT-COMP] Update use of `--decision` option
  contrib/competitions/smt-comp/run-script-smtcomp-current
  contrib/competitions/smt-comp/run-script-smtcomp-current-unsat-cores
Labels: major, simple

#8925 Remove spurious pto singleton inference
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/sep/theory_sep.cpp
Labels: minor, simple

#8924 Remove `Theory::postsolve()`
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  src/smt/solver_engine_state.cpp
  src/smt/solver_engine_state.h
  src/theory/mktheorytraits
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: normal, simple
