Repository cvc5/cvc5, pull requests merged in 2022-02, with the labels that each got.

#7964 Consider RANs in variable ordering
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/normal_form.h
Labels: minor, simple

#8015 [Arrays] Fix response for `store` chains
  src/theory/arrays/theory_arrays_rewriter.cpp
Labels: major, simple

#8008 Add new ordering functors for arithmetic rewriter
  src/CMakeLists.txt
  src/theory/arith/rewriter/ordering.h
Labels: normal, moderate

#8010 [BV] Fix order of rewrites for `concat`
  src/theory/bv/theory_bv_rewriter.cpp
Labels: major, moderate

#8011 [BV] Fix strategy for `RewriteExtract`
  src/theory/bv/theory_bv_rewrite_rules_core.h
  src/theory/bv/theory_bv_rewriter.cpp
Labels: major, moderate

#8021 Fix parser issue with tuple_project operator
  src/parser/smt2/smt2.cpp
Labels: normal, simple

#8017 Extend proof step buffer to optionally ensure unique conclusions
  src/proof/proof_step_buffer.cpp
  src/proof/proof_step_buffer.h
  src/proof/theory_proof_step_buffer.cpp
  src/proof/theory_proof_step_buffer.h
  src/theory/strings/infer_proof_cons.cpp
  src/theory/strings/infer_proof_cons.h
  test/regress/CMakeLists.txt
  test/regress/regress2/strings/proj-439-cyclic-str-ipc.smt2
Labels: major, moderate

#8009 Update datatypes.rst
  docs/ext/smtliblexer.py
  docs/theories/datatypes.rst
  src/parser/parse_op.h
  src/parser/smt2/smt2.cpp
  src/theory/datatypes/datatypes_rewriter.cpp
Labels: minor, simple

#7991 Add additional check to avoid cyclic substitution
  src/theory/arith/nl/equality_substitution.cpp
  src/theory/substitutions.cpp
  src/theory/substitutions.h
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/proj-issue-444-memout-eqelim.smt2
Labels: minor, moderate

#8027 Add missing null terminators for regexp
  src/expr/nary_term_util.cpp
  src/proof/lfsc/lfsc_node_converter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/instance2984-null-term.smt2
Labels: normal, simple

#8028 Make LFSC side condition for concat unify robust to equality with full string
  proofs/lfsc/signatures/strings_rules.plf
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/regexp-050-multiply-graft-fuzz-dd.smt2
Labels: normal, simple

#8029 Fix printing of re.loop as an operator in LFSC
  src/proof/lfsc/lfsc_node_converter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/instance1079-re-loop-cong.smt2
Labels: normal, simple

#8033 api: Rename mk<Value> functions for FP for consistency.
  examples/api/cpp/floating_point_arith.cpp
  examples/api/java/FloatingPointArith.java
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/api/Solver.java
  src/api/java/jni/solver.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/parser/smt2/smt2.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/cpp/term_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/java/TermTest.java
  test/unit/api/python/test_solver.py
  test/unit/api/python/test_term.py
Labels: normal, simple

#8026 Fix invalid rewrite involving iand
  src/theory/arith/arith_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/nl/issue8016-iand-rewrite.smt2
Labels: normal, simple

#8030 Use proper filename in `-o subs` documentation
  src/options/base_options.toml
Labels: minor, simple

#8035 Rename kinds MINUS -> SUB and UMINUS -> NEG.
  src/api/cpp/cvc5.cpp
  src/preprocessing/passes/int_to_bv.cpp
  src/preprocessing/passes/nl_ext_purify.cpp
  src/preprocessing/passes/unconstrained_simplifier.cpp
  src/printer/smt2/smt2_printer.cpp
  src/proof/alethe/alethe_post_processor.cpp
  src/proof/lfsc/lfsc_node_converter.cpp
  src/theory/arith/arith_poly_norm.cpp
  src/theory/arith/arith_poly_norm.h
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_rewriter.h
  src/theory/arith/kinds
  src/theory/arith/nl/ext/monomial_check.cpp
  src/theory/arith/nl/ext/proof_checker.cpp
  src/theory/arith/nl/ext/tangent_plane_check.cpp
  src/theory/arith/nl/iand_solver.cpp
  src/theory/arith/nl/iand_utils.cpp
  src/theory/arith/nl/nl_model.cpp
  src/theory/arith/nl/transcendental/exponential_solver.cpp
  src/theory/arith/nl/transcendental/proof_checker.cpp
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/arith/nl/transcendental/taylor_generator.cpp
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  src/theory/arith/operator_elim.cpp
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith_private.cpp
  src/theory/bags/bag_reduction.cpp
  src/theory/bags/inference_generator.cpp
  src/theory/bv/int_blaster.cpp
  src/theory/datatypes/sygus_extension.cpp
  src/theory/datatypes/sygus_simple_sym.cpp
  src/theory/evaluator.cpp
  src/theory/quantifiers/cegqi/ceg_arith_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/ematching/inst_match_generator.cpp
  src/theory/quantifiers/ematching/pattern_term_selector.cpp
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/skolemize.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus_sampler.cpp
  src/theory/quantifiers/term_util.cpp
  src/theory/sets/theory_sets_rewriter.cpp
  src/theory/strings/arith_entail.cpp
  src/theory/strings/array_core_solver.cpp
  src/theory/strings/array_solver.cpp
  src/theory/strings/core_solver.cpp
  src/theory/strings/regexp_elim.cpp
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/skolem_cache.cpp
  src/theory/strings/strings_entail.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/theory_strings_utils.cpp
  test/unit/node/node_black.cpp
  test/unit/node/node_builder_black.cpp
  test/unit/theory/arith_poly_white.cpp
  test/unit/theory/sequences_rewriter_white.cpp
  test/unit/theory/theory_arith_rewriter_black.cpp
Labels: normal, simple

#8031 Fix rewrite for eliminating constant factors of PI from argument to sine
  src/theory/arith/arith_rewriter.cpp
  test/unit/api/cpp/solver_black.cpp
Labels: normal, simple

#7958 api: Add explicit guard for option produce-assertions in blockModelValues().
  src/api/cpp/cvc5.cpp
Labels: normal, simple

#8034 api: Rename kinds MINUS -> SUB and UMINUS -> NEG.
  examples/api/cpp/linear_arith.cpp
  examples/api/cpp/quickstart.cpp
  examples/api/cpp/sygus-fun.cpp
  examples/api/cpp/sygus-grammar.cpp
  examples/api/java/LinearArith.java
  examples/api/java/QuickStart.java
  examples/api/java/SygusFun.java
  examples/api/java/SygusGrammar.java
  examples/api/python/linear_arith.py
  examples/api/python/quickstart.py
  examples/api/python/sygus-fun.py
  examples/api/python/sygus-grammar.py
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_kind.h
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/parser/tptp/Tptp.g
  src/parser/tptp/tptp.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/python/test_solver.py
Labels: normal, simple

#8032 api: Remove obsolete function declaration in Cython bindings.
  src/api/python/cvc5.pxd
Labels: normal, simple

#7990 Send all `nth` terms to the core array solver
  src/theory/strings/array_solver.cpp
Labels: normal, moderate

#8012 Add node utils for the arithmetic rewriter
  src/CMakeLists.txt
  src/theory/arith/rewriter/node_utils.cpp
  src/theory/arith/rewriter/node_utils.h
Labels: normal, moderate

#8039 Add miscellaneous missing theory definitions for LFSC
  proofs/lfsc/signatures/theory_def.plf
Labels: minor, simple

#8020 Add table.product operator
  src/CMakeLists.txt
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_kind.h
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/bags/bag_solver.cpp
  src/theory/bags/bag_solver.h
  src/theory/bags/bags_rewriter.cpp
  src/theory/bags/bags_rewriter.h
  src/theory/bags/bags_utils.cpp
  src/theory/bags/bags_utils.h
  src/theory/bags/inference_generator.cpp
  src/theory/bags/inference_generator.h
  src/theory/bags/kinds
  src/theory/bags/rewrites.cpp
  src/theory/bags/rewrites.h
  src/theory/bags/theory_bags_type_rules.cpp
  src/theory/bags/theory_bags_type_rules.h
  src/theory/datatypes/tuple_utils.cpp
  src/theory/datatypes/tuple_utils.h
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/sets/rels_utils.cpp
  src/theory/sets/rels_utils.h
  src/theory/sets/theory_sets_rels.cpp
  src/theory/sets/theory_sets_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/bags/product1.smt2
  test/regress/regress1/bags/product2.smt2
  test/regress/regress1/bags/product3.smt2
Labels: normal, moderate

#8040 Eliminate more static uses of rewrite
  src/expr/subs.cpp
  src/expr/subs.h
  src/theory/quantifiers/cegqi/nested_qe.cpp
  src/theory/quantifiers/ematching/im_generator.cpp
  src/theory/quantifiers/ematching/im_generator.h
  src/theory/quantifiers/ematching/inst_match_generator.cpp
  src/theory/quantifiers/ematching/inst_match_generator.h
  src/theory/quantifiers/ematching/inst_match_generator_multi.cpp
  src/theory/quantifiers/ematching/inst_match_generator_multi.h
  src/theory/quantifiers/ematching/inst_match_generator_multi_linear.cpp
  src/theory/quantifiers/ematching/inst_match_generator_multi_linear.h
  src/theory/quantifiers/ematching/inst_match_generator_simple.cpp
  src/theory/quantifiers/ematching/inst_match_generator_simple.h
  src/theory/quantifiers/ematching/pattern_term_selector.cpp
  src/theory/quantifiers/ematching/relational_match_generator.cpp
  src/theory/quantifiers/ematching/relational_match_generator.h
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/ematching/var_match_generator.cpp
  src/theory/quantifiers/ematching/var_match_generator.h
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
Labels: minor, simple

#8042 Replace a some more static options
  src/theory/quantifiers/ematching/inst_match_generator.cpp
  src/theory/quantifiers/ematching/inst_match_generator_multi_linear.cpp
  src/theory/quantifiers/ematching/inst_match_generator_simple.cpp
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/quantifiers_modules.cpp
Labels: minor, moderate

#8038 Test proof granularity theory-rewrite by default
  test/regress/run_regression.py
Labels: normal, simple

#8044 Eliminate even more static uses of rewrite
  src/theory/quantifiers/sygus/cegis_core_connective.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_verify.cpp
  src/theory/smt_engine_subsolver.cpp
  src/theory/uf/theory_uf_rewriter.cpp
Labels: minor, simple

#8045 Improve theory combination over real algebraic models
  src/theory/arith/arith_evaluator.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/proj-issue-451-ran-combination-1.smt2
  test/regress/regress0/nl/proj-issue-451-ran-combination-2.smt2
Labels: minor, moderate

#8047 Simplify handling of disequalities in strings
  src/theory/strings/core_solver.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  test/regress/CMakeLists.txt
  test/regress/regress0/seq/wrong-model-020322.smt2
  test/regress/regress0/seq/wrong-sat-020322.smt2
Labels: major, moderate

#8043 Use Add instead of Plus in pythonic API docs
  docs/api/python/pythonic/arith.rst
Labels: normal, simple

#8057 Standardizing notifications for setting options in set_defaults
  src/smt/set_defaults.cpp
  src/smt/set_defaults.h
Labels: minor, simple

#8007 [Rewriter] Always rewrite again when kind changes
  src/theory/rewriter.cpp
  src/theory/theory_rewriter.h
  test/regress/CMakeLists.txt
  test/regress/regress0/bv/proj-issue438-prerewrite-fixed-point.smt2
  test/regress/regress1/bv/proj-issue438-prerewrite-fixed-point-original.smt2
Labels: major, moderate

#8054 Fix another rewrite involving iand
  src/theory/arith/arith_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/nl/issue8052-iand-rewrite.smt2
Labels: normal, simple

#8066 [Seq] Check types for split on indices
  src/theory/strings/array_core_solver.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/seq/mixed-types-seq-nth.smt2
Labels: major, simple

#8065 Fix indexof_re reduction
  src/theory/strings/theory_strings_preprocess.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/issue6654-indexof_re_red.smt2
Labels: normal, simple

#8074 [BV] Fix response of `RewriteConcat`
  src/theory/bv/theory_bv_rewriter.cpp
  test/unit/theory/theory_bv_rewriter_white.cpp
Labels: major, simple

#8075 Improve combination of NRA and transcendentals
  src/smt/set_defaults.cpp
  src/theory/arith/nl/nl_model.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/arith/issue7984-quant-trans.smt2
Labels: minor, moderate

#8076 Allow non-value model values
  src/theory/theory_model_builder.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/arith/exp-in-model.smt2
Labels: minor, moderate

#8058 Add user documentation for resource limits
  docs/binary/binary.rst
  docs/binary/resource-limits.rst
  src/api/cpp/cvc5.h
Labels: minor, moderate

#8077 Generalize LFSC concat unify for splitting constants
  proofs/lfsc/signatures/nary_programs.plf
  proofs/lfsc/signatures/strings_programs.plf
  proofs/lfsc/signatures/strings_rules.plf
  test/regress/CMakeLists.txt
  test/regress/regress1/strings/instance6561-dd-concat-unify-char.smt2
Labels: normal, moderate

#8081 Make witness form visited ref counted
  src/smt/witness_form.cpp
  src/smt/witness_form.h
Labels: normal, simple

#8041 Always produce assertions
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/api/Solver.java
  src/options/smt_options.toml
  src/smt/assertions.cpp
  src/smt/assertions.h
  src/smt/process_assertions.cpp
  src/smt/proof_manager.cpp
  src/smt/set_defaults.cpp
  src/smt/solver_engine.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
Labels: minor, simple

#8046 Print more commonly used murxla commands
  cmake/fuzzing-murxla.cmake
Labels: minor, simple

#8078 Fix LFSC node conversion for non-shared selectors
  src/proof/lfsc/lfsc_node_converter.cpp
Labels: minor, simple

#8062 Distinguish proof mode from unsat core mode
  src/options/smt_options.toml
  src/prop/minisat/core/Solver.cc
  src/prop/theory_proxy.cpp
  src/smt/env.cpp
  src/smt/set_defaults.cpp
  src/smt/solver_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/proj-issue406-diff-unsat-core.smt2
Labels: normal, moderate

#8013 Add addition utilities for the arithmetic rewriter
  src/CMakeLists.txt
  src/theory/arith/rewriter/addition.cpp
  src/theory/arith/rewriter/addition.h
Labels: normal, moderate

#8083 [Seq] Fix rewrite of `(seq.nth s n)` for large `n`
  src/theory/strings/sequences_rewriter.cpp
  test/unit/theory/sequences_rewriter_white.cpp
Labels: normal, major

#8000 Fix handling of `LogicException` during solving
  src/smt/smt_solver.cpp
  src/smt/solver_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/issue7974-incomplete-neg-member.smt2
Labels: normal, moderate

#8085 bv: Add --tlimit-per support for CaDiCaL.
  src/prop/cadical.cpp
  src/prop/cadical.h
  src/prop/sat_solver_factory.cpp
  src/prop/sat_solver_factory.h
  src/theory/bv/bv_solver_bitblast.cpp
Labels: normal, simple

#8086 bv: Add --tlimit-per support for CryptoMiniSat.
  src/prop/cryptominisat.cpp
  src/prop/cryptominisat.h
  src/prop/sat_solver_factory.cpp
  src/prop/sat_solver_factory.h
  src/theory/bv/bv_solver_bitblast.cpp
  src/util/resource_manager.cpp
  src/util/resource_manager.h
Labels: normal, simple

#8089 Use witness terms to represent values for large strings in models
  src/options/strings_options.toml
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings_utils.cpp
  src/theory/strings/theory_strings_utils.h
  src/theory/theory_model.cpp
  test/regress/regress0/strings/large-model.smt2
Labels: normal, moderate

#8093 Fix type check of `seq.nth`
  src/theory/strings/theory_strings_type_rules.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/seq/seq-nth-type-check.smt2
Labels: normal, simple

#8082 Fix for lambda-to-array constant conversion for unused arguments
  src/theory/uf/function_const.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/ho/issue4434-const-preserve.smt2
Labels: normal, moderate

#8092 Ensure proofs are fully disabled when incompatible
  src/smt/set_defaults.cpp
  src/theory/datatypes/datatypes_rewriter.cpp
Labels: normal, moderate

#8098 Support `try` and `all` reconstruction modes.
  src/options/quantifiers_options.toml
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/sygus_reconstruct.cpp
  src/theory/quantifiers/sygus/sygus_reconstruct.h
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/max-all.sy
  test/regress/regress1/sygus/max-limit.sy
  test/regress/regress1/sygus/max-try1.sy
  test/regress/regress1/sygus/max-try2.sy
  test/regress/regress1/sygus/simple-rewrite-not-in-db.sy
Labels: normal, moderate

#8105 Only consider relevant terms in the array-inspired sequence solver
  src/theory/strings/array_solver.cpp
  src/theory/strings/array_solver.h
  src/theory/strings/term_registry.cpp
  src/theory/strings/term_registry.h
  src/theory/strings/theory_strings.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/seq/shared-term-registration.smt2
Labels: major, moderate

#8104 Make cache (optionally) persistent in lazy CD proof
  src/proof/lazy_proof.cpp
  src/proof/lazy_proof.h
Labels: major, simple

#8109 Consolidate multiple substitutions to single AND child in trust substitution map
  src/theory/trust_substitutions.cpp
Labels: major, simple

#8100 Introduce all_simplify and replace old trust rules
  src/proof/alethe/alethe_post_processor.cpp
  src/proof/alethe/alethe_proof_rule.cpp
  src/proof/alethe/alethe_proof_rule.h
Labels: minor, simple

#8110 Remove some irrelevant node kinds from the model
  src/theory/sep/theory_sep.cpp
  src/theory/sets/theory_sets.cpp
Labels: normal, simple

#8108 Missing ids for arith conflicts
  src/theory/arith/constraint.cpp
  src/theory/arith/theory_arith_private.cpp
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  test/regress/CMakeLists.txt
  test/regress/regress0/arith/issue8097-iid.smt2
Labels: minor, simple

#8116 Introduce skolem function to make transcendental function purification unique
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
Labels: minor, simple

#8121 Fix `STRINGS_ARRAY_NTH_UPDATE` inference
  src/theory/strings/array_core_solver.cpp
Labels: major, moderate

#8123 Improve `STRINGS_ARRAY_UPDATE_BOUND` inference
  src/theory/strings/array_core_solver.cpp
Labels: major, simple

#8056 Add well formed term check to solver engine
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  test/unit/api/cpp/solver_black.cpp
Labels: normal, simple

#8059 Throw option exceptions when combining input conversion preprocessing with sygus
  src/smt/set_defaults.cpp
  src/smt/set_defaults.h
  test/unit/api/cpp/solver_black.cpp
Labels: minor, simple

#8120 Fixes and additions for LFSC signatures
  proofs/lfsc/signatures/strings_rules.plf
  proofs/lfsc/signatures/theory_def.plf
Labels: major, simple

#8107 Enable DAG and tree printing with dot files
  src/options/proof_options.toml
  src/proof/dot/dot_printer.cpp
  src/proof/dot/dot_printer.h
  src/proof/proof_node.cpp
  src/proof/proof_node.h
Labels: minor, moderate

#8113 Relax what is generated in the model from NL
  src/theory/arith/nl/cad_solver.cpp
  src/theory/arith/nl/nl_model.cpp
  src/theory/arith/nl/nl_model.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
  src/theory/arith/nl/transcendental/transcendental_solver.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  test/regress/regress0/arith/exp-in-model.smt2
  test/regress/regress0/arith/issue7984-quant-trans.smt2
Labels: normal, moderate

#8115 Change inference scheme in transcendentals to rewrite rule
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/nl/transcendental/sine_solver.cpp
Labels: minor, simple

#8129 Remove refineConflicts option
  src/options/prop_options.toml
  src/prop/minisat/core/Solver.cc
Labels: minor, simple

#8114 Support some cases of isConst for regular expressions
  src/theory/strings/kinds
  src/theory/strings/theory_strings_type_rules.cpp
  src/theory/strings/theory_strings_type_rules.h
Labels: minor, simple

#8125 Fix issue in datatypes care graph computation involving subtyping
  src/printer/ast/ast_printer.cpp
  src/theory/datatypes/theory_datatypes.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/datatypes/issue8124-real-int-cg.smt2
Labels: major, simple

#7965 Refactor multiplication in arithmetic rewriter
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/rewriter/addition.h
  src/theory/arith/rewriter/ordering.h
Labels: normal, moderate

#8084 Fix pruning of covering intervals in proofs
  src/proof/lazy_tree_proof_generator.cpp
  src/proof/lazy_tree_proof_generator.h
  src/theory/arith/nl/cad/cdcac.cpp
  src/theory/arith/nl/cad/cdcac_utils.cpp
  src/theory/arith/nl/cad/proof_generator.cpp
  src/theory/arith/nl/cad/proof_generator.h
  test/unit/theory/theory_arith_cad_white.cpp
Labels: normal, moderate

#8061 [Rewriter] Do not attempt to rewrite constants
  src/theory/rewriter.cpp
Labels: normal, moderate

#8080 Properly sanatize user names in LFSC
  src/proof/lfsc/lfsc_node_converter.cpp
  src/proof/lfsc/lfsc_node_converter.h
  test/unit/CMakeLists.txt
  test/unit/proof/CMakeLists.txt
  test/unit/proof/lfsc_node_converter_black.cpp
Labels: normal, moderate

#8137 Fix icp candidate parsing
  src/options/arith_options.toml
  src/theory/arith/nl/icp/icp_solver.cpp
  src/theory/arith/nl/icp/intersection.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/issue8135-icp-candidates.smt2
Labels: minor, moderate

#8138 Fix creation of RAN from non-dyadic rational
  src/util/real_algebraic_number_poly_imp.cpp
Labels: minor, simple

#8064 Option exception when incompatible with proofs
  src/smt/set_defaults.cpp
  test/regress/regress0/quantifiers/lra-triv-gn.smt2
  test/regress/regress1/issue3970-nl-ext-purify.smt2
  test/regress/regress1/quantifiers/issue4021-ind-opts.smt2
  test/regress/regress1/sygus/issue3201.smt2
  test/regress/regress1/sygus/issue3247.smt2
  test/regress/regress1/sygus/issue3995-fmf-var-op.smt2
  test/regress/regress1/sygus/issue4009-qep.smt2
  test/regress/regress1/sygus/issue4025-no-rlv-cond.smt2
  test/regress/regress1/sygus/issue4083-var-shadow.smt2
  test/regress/regress1/sygus/proj-issue185.smt2
  test/unit/api/cpp/solver_black.cpp
Labels: normal, simple

#8139 Remove long obsolete unsafe interrupt exception
  src/main/driver_unified.cpp
  src/parser/parser.h
  src/prop/minisat/core/Solver.cc
  src/prop/prop_engine.h
  src/smt/assertions.h
  src/smt/command.cpp
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  src/theory/theory_engine.h
  src/util/CMakeLists.txt
  src/util/resource_manager.h
  src/util/unsafe_interrupt_exception.h
  test/unit/test_smt.h
Labels: minor, moderate

#8090 Eliminate match from LFSC proofs
  src/proof/lfsc/lfsc_node_converter.cpp
  src/proof/lfsc/lfsc_node_converter.h
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/datatypes_rewriter.h
Labels: minor, moderate

#8140 Do not insist that entries for UF are constant in FMF
  src/theory/quantifiers/fmf/first_order_model_fmc.cpp
  src/theory/quantifiers/fmf/full_model_check.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/fmf/issue8096-non-const-rep.smt2
Labels: minor, simple

#8095 Further relax what is considered a value in the model
  src/options/strings_options.toml
  src/smt/solver_engine.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_model.cpp
  src/theory/theory_model.h
  src/theory/theory_model_builder.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/arith/exp-in-model.smt2
  test/regress/regress0/arith/issue7984-quant-trans.smt2
  test/regress/regress1/nl/transcedental_model_simple.smt2
  test/regress/regress1/strings/issue8094-witness-model.smt2
  test/regress/regress1/strings/witness-model.smt2
Labels: normal, complex

#8136 Allow elimination of unevaluated terms by default
  src/options/smt_options.toml
  src/theory/theory.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/nl/issue8118-elim-sin.smt2
  test/regress/regress1/sets/arjun-set-univ.cvc.smt2
  test/regress/regress1/sets/univ-set-uf-elim.smt2
Labels: normal, moderate, do not merge

#8142 Add two regressions related to RAN models
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/issue6547-ran-model.smt2
  test/regress/regress0/nl/issue6619-ran-model.smt2
Labels: minor, simple

#8145 Add regression for some fixed array issues
  test/regress/CMakeLists.txt
  test/regress/regress0/arrays/issue4240.smt2
  test/regress/regress0/arrays/issue4414-2.smt2
  test/regress/regress0/arrays/issue4414.smt2
  test/regress/regress0/arrays/issue4546-2.smt2
  test/regress/regress0/arrays/issue4546.smt2
  test/regress/regress0/arrays/issue4780-3.smt2
  test/regress/regress0/arrays/issue4780.smt2
Labels: minor, simple

#8144 Make uninterpreted sort owner non-static
  src/preprocessing/util/ite_utilities.cpp
  src/prop/cnf_stream.cpp
  src/prop/cnf_stream.h
  src/prop/proof_cnf_stream.cpp
  src/prop/proof_cnf_stream.h
  src/prop/prop_engine.cpp
  src/smt/env.cpp
  src/smt/env.h
  src/smt/expand_definitions.cpp
  src/smt/proof_post_processor.cpp
  src/smt/set_defaults.cpp
  src/theory/arith/branch_and_bound.cpp
  src/theory/arith/theory_arith.cpp
  src/theory/bv/bv_solver_bitblast.cpp
  src/theory/bv/theory_bv_utils.cpp
  src/theory/evaluator.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/term_registration_visitor.cpp
  src/theory/theory.cpp
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  test/regress/CMakeLists.txt
  test/regress/regress0/arrays/issue5720.smt2
  test/regress/regress0/arrays/issue5836-2.smt2
  test/regress/regress0/arrays/issue5836.smt2
  test/regress/regress0/arrays/issue6276-2.smt2
  test/regress/regress0/arrays/issue6276.smt2
  test/regress/regress0/bug421.smt2
  test/regress/regress0/bug421b.smt2
  test/unit/prop/cnf_stream_white.cpp
Labels: major, moderate

#8146 Get rid of some static objects in arithmetic theory
  src/theory/arith/approx_simplex.cpp
  src/theory/arith/approx_simplex.h
  src/theory/arith/attempt_solution_simplex.cpp
  src/theory/arith/constraint.h
  src/theory/arith/constraint_forward.h
  src/theory/arith/dio_solver.h
  src/theory/arith/dual_simplex.cpp
  src/theory/arith/error_set.cpp
  src/theory/arith/fc_simplex.cpp
  src/theory/arith/fc_simplex.h
  src/theory/arith/linear_equality.cpp
  src/theory/arith/nl/cad/lazard_evaluation.cpp
  src/theory/arith/soi_simplex.cpp
  src/theory/arith/soi_simplex.h
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
Labels: minor, moderate

#8130 Check for free variables in several SolverEngine calls
  examples/api/cpp/helloworld.cpp
  examples/api/java/HelloWorld.java
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/main/driver_unified.cpp
  src/options/expr_options.toml
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  test/unit/api/cpp/result_black.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/ResultTest.java
  test/unit/api/python/test_result.py
Labels: major, moderate

#8117 Make sine solver sound with respect to region boundaries
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/nl/issue7948-3-unsound-sin-region.smt2
Labels: major, moderate

#8154 Improve error message for missing options include
  src/options/mkoptions.py
Labels: minor, simple

#8150 Make model builder robust to multiple value-like terms in the same equivalence class
  src/theory/theory_model_builder.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/seq/issue8148-2-const-mv.smt2
  test/regress/regress1/seq/issue8148-const-mv.smt2
Labels: normal, moderate

#8153 Ensure variables are constrained in model when equal to transcendental function apps
  src/smt/check_models.cpp
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
  src/theory/arith/nl/transcendental/transcendental_solver.h
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/nta/issue8147-unc-model.smt2
Labels: normal, simple

#8134 [Python API] Add support for blocking models
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  test/unit/api/python/test_solver.py
Labels: normal, moderate

#8156 Consolidate extended rewrite preprocessing modes
  src/options/smt_options.toml
  src/preprocessing/passes/extended_rewriter_pass.cpp
  src/smt/process_assertions.cpp
  test/regress/regress0/fp/ext-rew-test.smt2
  test/regress/regress0/nl/issue5737-div00.smt2
  test/regress/regress0/sets/sets-extr.smt2
  test/regress/regress0/strings/issue6520.smt2
  test/regress/regress1/bv/issue3654.smt2
  test/regress/regress1/issue4273-ext-rew-cache.smt2
  test/regress/regress1/nl/ext-rew-aggr-test.smt2
  test/regress/regress1/nl/issue3656.smt2
  test/regress/regress1/nl/issue3803-nl-check-model.smt2
Labels: minor, simple

#8155 Add regression for fixed transcendental regression
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/nta/issue7938-tf-model.smt2
Labels: minor, simple

#8157 Make quantifiers terminate if it detects a (duplicate) quantifier-free conflict
  src/theory/quantifiers_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/quantifiers/issue8157-duplicate-conflicts.smt2
Labels: minor, simple

#8168 Remove spurious assertion involving constants for arguments to UF from FMF
  src/theory/quantifiers/fmf/full_model_check.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/fmf/issue8163-nconst-arg.smt2
Labels: minor, simple

#8166 Remove approximations infrastructure from model
  src/options/smt_options.toml
  src/theory/arith/nl/nl_model.cpp
  src/theory/arith/nl/nl_model.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/theory_arith.cpp
  src/theory/theory_model.cpp
  src/theory/theory_model.h
  src/theory/theory_model_builder.cpp
  test/regress/regress1/nl/issue3300-approx-sqrt-witness.smt2
Labels: minor, moderate

#8164 Fix dropped bounds on PI
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/nl/issue8162-drop-pi-bound.smt2
Labels: normal, moderate

#8165 Fix non-termination in quantifiers rewriter
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
  test/regress/CMakeLists.txt
  test/regress/regress0/quantifiers/issue8159-3-qext-nterm.smt2
Labels: normal, simple

#8169 Slightly refactor arithmetic rewriting for extended operators
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_rewriter.h
Labels: normal, moderate

#8170 Refactor rewriting of arithmetic negation and subtraction
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_rewriter.h
Labels: normal, moderate

#8014 Add utilities to rewrite atoms for the arithmetic rewriter
  src/CMakeLists.txt
  src/theory/arith/rewriter/addition.cpp
  src/theory/arith/rewriter/rewrite_atom.cpp
  src/theory/arith/rewriter/rewrite_atom.h
Labels: normal, moderate

#8172 Syntax fixes for LFSC signature
  proofs/lfsc/signatures/arith_rules.plf
  proofs/lfsc/signatures/cnf_rules.plf
  proofs/lfsc/signatures/quantifiers_rules.plf
Labels: normal, simple

#8176 Consider PI to be a model value
  src/theory/theory_model.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/nta/proj-issue460-pi-value.smt2
Labels: normal, simple

#8180 Refactor rewriting of arithmetic addition
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_rewriter.h
  src/theory/arith/rewriter/addition.cpp
  src/theory/arith/rewriter/node_utils.cpp
Labels: normal, moderate

#8177 Refactor rewriting of arithmetic leafs
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_rewriter.h
Labels: normal, moderate

#8132 Add scripts to build python wheels
  contrib/packaging_python/Readme.md
  contrib/packaging_python/manylinux2014/Dockerfile
  contrib/packaging_python/mk_build_dir.py
  contrib/packaging_python/mk_clean_wheel.sh
  contrib/packaging_python/mk_wheel.py
  src/api/python/wheels/build_wheel.py
Labels: major, moderate

#8178 Remove broken/unused `--mmap` option
  src/main/driver_unified.cpp
  src/options/parser_options.toml
  src/parser/CMakeLists.txt
  src/parser/antlr_input.cpp
  src/parser/antlr_input.h
  src/parser/input.cpp
  src/parser/input.h
  src/parser/memory_mapped_input_buffer.cpp
  src/parser/memory_mapped_input_buffer.h
  test/unit/parser/parser_builder_black.cpp
Labels: normal, simple

#8171 Add two reduction schemas for sin terms
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/arith/nl/transcendental/sine_solver.h
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  src/theory/arith/nl/transcendental/transcendental_state.h
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/nta/sin-sym-schema.smt2
  test/regress/regress1/nl/issue7948-3-unsound-sin-region.smt2
Labels: normal, moderate

#8184 Track names for witness terms in model
  src/parser/smt2/Smt2.g
  src/printer/smt2/smt2_printer.cpp
  src/theory/builtin/kinds
  src/theory/builtin/theory_builtin_type_rules.h
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers/quantifiers_attributes.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  src/theory/strings/theory_strings_utils.cpp
  src/theory/strings/theory_strings_utils.h
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/distinct-witness-id.smt2
Labels: normal, simple

#8188 Preserve model values for exact sine points
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/arith/nl/transcendental/sine_solver.h
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/nta/issue8182-2-exact-mv-keep.smt2
  test/regress/regress0/nl/nta/issue8182-exact-mv-keep.smt2
Labels: normal, simple

#8189 Fix special casing for PI in model value
  src/theory/arith/nl/ext_theory_callback.cpp
  src/theory/theory_model.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/nta/issue8183-tc-pi.smt2
Labels: normal, simple

#8175 Refactor rewriting of arithmetic atoms
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_rewriter.h
Labels: normal, moderate

#8179 [Seq/Model] Do not enumerate elements of constants
  src/theory/strings/core_solver.cpp
  src/theory/strings/theory_strings.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/seq/issue8133-block-const-elems.smt2
Labels: normal, moderate
