Repository cvc5/cvc5, pull requests merged in 2022-11, with the labels that each got.

#9225 Add option for separate check statements of LFSC subproofs
  src/options/proof_options.toml
  src/proof/lfsc/lfsc_printer.cpp
  src/proof/lfsc/lfsc_printer.h
  src/smt/proof_manager.cpp
Labels: minor, moderate

#9252 Fix datatypes model related to irrelevant constructor terms
  src/theory/datatypes/theory_datatypes.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/datatypes/issue9042-rel-irrel-cons-model.smt2
Labels: normal, moderate

#9228 Add option to print the children of trusted steps in LFSC
  src/options/proof_options.toml
  src/proof/lfsc/lfsc_print_channel.cpp
  src/proof/lfsc/lfsc_print_channel.h
  src/proof/lfsc/lfsc_printer.cpp
  src/proof/lfsc/lfsc_printer.h
  src/smt/proof_manager.cpp
Labels: minor, moderate

#9254 bv: Add native support for signed division overflow detection.
  NEWS.md
  proofs/lfsc/signatures/theory_def.plf
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_kind.h
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/bv/kinds
  src/theory/bv/theory_bv_rewrite_rules.h
  src/theory/bv/theory_bv_rewrite_rules_operator_elimination.h
  src/theory/bv/theory_bv_rewriter.cpp
  src/theory/bv/theory_bv_rewriter.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/bv/overflow/sdivo1.smt2
  test/regress/cli/regress0/bv/overflow/sdivo2.smt2
  test/unit/theory/theory_bv_black.cpp
Labels: normal, simple

#9251 Towards decoupling Assertions from AssertionPipeline
  src/preprocessing/assertion_pipeline.cpp
  src/smt/assertions.cpp
  src/smt/assertions.h
  src/smt/preprocessor.cpp
  src/smt/preprocessor.h
  src/smt/process_assertions.cpp
  src/smt/process_assertions.h
  src/smt/smt_driver.cpp
  src/smt/smt_driver_deep_restarts.cpp
  src/smt/smt_solver.cpp
  src/smt/smt_solver.h
  src/smt/solver_engine.cpp
  src/theory/substitutions.cpp
  src/theory/substitutions.h
Labels: normal, moderate

#9238 Add theory interface for marking unsoundness
  src/prop/prop_engine.cpp
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
  src/theory/arith/linear/theory_arith_private.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/theory_arith.cpp
  src/theory/engine_output_channel.cpp
  src/theory/engine_output_channel.h
  src/theory/incomplete_id.h
  src/theory/output_channel.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers_engine.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/strings/base_solver.cpp
  src/theory/strings/core_solver.cpp
  src/theory/strings/inference_manager.h
  src/theory/strings/regexp_solver.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
  src/theory/uf/cardinality_extension.cpp
  src/theory/uf/ho_extension.cpp
  src/theory/uf/theory_uf.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/sygus/sum-sq-unknown.sy
  test/unit/test_smt.h
Labels: major, moderate

#9256 Move ownership of preprocess proof generator to preprocessor
  src/smt/assertions.cpp
  src/smt/assertions.h
  src/smt/preprocessor.cpp
  src/smt/preprocessor.h
  src/smt/proof_manager.cpp
  src/smt/proof_manager.h
  src/smt/proof_post_processor.cpp
  src/smt/proof_post_processor.h
  src/smt/smt_solver.cpp
  src/smt/solver_engine.cpp
Labels: normal, moderate

#9253 More regular expression inclusions
  src/theory/strings/regexp_entail.cpp
  src/theory/strings/regexp_entail.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/strings/simple-include-mem.smt2
  test/regress/cli/regress0/strings/simple-include-subrange.smt2
Labels: normal, moderate

#9248 Reclassify some ITE rewrites in the extended rewriter
  src/theory/quantifiers/extended_rewrite.cpp
Labels: major, simple

#9262 Do not report infeasible for smart enumeration + any-constant constructors
  src/smt/sygus_solver.cpp
  src/theory/incomplete_id.cpp
  src/theory/incomplete_id.h
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/sygus/proj-issue222-any-const.sy
Labels: major, moderate

#9250 Add Bitvector rules to Alethe Backend
  src/proof/alethe/alethe_post_processor.cpp
  src/proof/alethe/alethe_proof_rule.cpp
  src/proof/alethe/alethe_proof_rule.h
Labels: minor, simple

#9266 Patch LibPoly for newer versions of Clang
  cmake/FindPoly.cmake
Labels: normal, simple

#9272 Do not add duplicates to unsat core
  src/prop/prop_engine.cpp
  src/smt/unsat_core_manager.cpp
  test/regress/cli/regress0/nl/pow2-pow-isabelle.smt2
Labels: normal, simple

#9260 [proofs] [alethe] Alethe let binding
  src/CMakeLists.txt
  src/proof/alethe/alethe_let_binding.cpp
  src/proof/alethe/alethe_let_binding.h
  src/proof/alethe/alethe_node_converter.h
  src/proof/alethe/alethe_post_processor.h
  src/proof/alethe/alethe_printer.cpp
  src/proof/alethe/alethe_printer.h
  src/proof/alethe/alethe_proof_rule.h
Labels: normal, moderate

#8689 [Docs] Add version links to pre-release docs
  .github/workflows/docs_upload.yml
Labels: normal, moderate

#9275 Track forced logic in the symbol manager
  src/main/interactive_shell.cpp
  src/parser/api/cpp/symbol_manager.cpp
  src/parser/api/cpp/symbol_manager.h
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/parser_builder.cpp
  src/parser/tptp/tptp.cpp
  src/parser/tptp/tptp.h
Labels: normal, simple

#9274 Move notifications about context to SMT driver
  src/smt/context_manager.cpp
  src/smt/context_manager.h
  src/smt/smt_driver.cpp
  src/smt/smt_driver.h
  src/smt/smt_solver.cpp
  src/smt/smt_solver.h
  src/smt/solver_engine.cpp
Labels: normal, moderate

#9267 Add more ways of inferring infeasible for sygus conjectures
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.h
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/sygus/finite-feasible-2.sy
  test/regress/cli/regress1/sygus/finite-infeasible-2.sy
  test/regress/cli/regress1/sygus/finite-infeasible.sy
  test/regress/cli/regress1/sygus/issue3649.sy
  test/regress/cli/regress1/sygus/issue7925-dt-share-config.sy
  test/regress/cli/regress1/sygus/si-infeasible.sy
Labels: minor, moderate

#9276 Introduce new parser API
  src/main/driver_unified.cpp
  src/main/interactive_shell.cpp
  src/main/interactive_shell.h
  src/main/portfolio_driver.cpp
  src/main/portfolio_driver.h
  src/parser/CMakeLists.txt
  src/parser/antlr_input.h
  src/parser/input.cpp
  src/parser/input.h
  src/parser/input_parser.cpp
  src/parser/input_parser.h
  src/parser/parser.h
  src/parser/parser_builder.cpp
  src/parser/parser_builder.h
  src/parser/smt2/smt2.h
  src/parser/smt2/smt2_input.h
  src/parser/smt2/sygus_input.h
  src/parser/tptp/tptp.h
  src/parser/tptp/tptp_input.h
Labels: normal, moderate

#9283 Reconstruct HO_CONG in LFSC proofs
  src/proof/lfsc/lfsc_post_processor.cpp
  src/proof/lfsc/lfsc_post_processor.h
Labels: normal, moderate

#2149 Change datastructure of CDList to std::vector
  CMakeLists.txt
  src/context/CMakeLists.txt
  src/context/cdlist.h
  src/context/cdlist_forward.h
  src/context/cdqueue.h
  src/context/default_clean_up.h
  src/prop/cnf_stream.cpp
  src/prop/minisat/core/Solver.h
  src/theory/arith/linear/constraint.h
  src/theory/arith/linear/partial_model.cpp
  src/theory/arith/linear/partial_model.h
  src/theory/assertion.h
  test/unit/context/cdlist_black.cpp
Labels: normal, moderate

#9285 Do not propagate when strings has a pending conflict
  src/theory/strings/theory_strings.cpp
Labels: major, simple

#9291 Remove tracking of parse-only in parser
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/parser_builder.cpp
  src/parser/parser_builder.h
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/parser/tptp/tptp.cpp
  src/parser/tptp/tptp.h
Labels: normal, simple

#9297 Support node conversions that do not preserve type
  src/expr/node_converter.cpp
  src/expr/node_converter.h
Labels: normal, moderate

#9286 Fix check-unsat-cores and minimal-unsat-cores
  src/smt/assertions.cpp
  src/smt/assertions.h
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  src/theory/quantifiers/theory_quantifiers.cpp
  src/theory/smt_engine_subsolver.cpp
  src/theory/smt_engine_subsolver.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/cores/dd.uc-min-wrong.smt2
  test/regress/cli/regress1/nl/nl-help-unsat-quant.smt2
  test/regress/cli/regress1/nl/quant-nl.smt2
Labels: major, moderate

#9301 Avoid lexing several theory-specific operators
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  test/regress/cli/regress0/declare-fun-is-match.smt2
Labels: normal, moderate

#9294 [proofs] [alethe] Update node converter
  src/expr/node_converter.cpp
  src/expr/node_converter.h
  src/proof/alethe/alethe_node_converter.cpp
  src/proof/alethe/alethe_node_converter.h
  src/proof/alethe/alethe_post_processor.cpp
Labels: normal, moderate

#9288 Fix Bug in Translation of INT-TIGHT-UB rule to Alethe
  src/proof/alethe/alethe_post_processor.cpp
Labels: minor, simple
