Repository cvc5/cvc5, pull requests merged in 2022-05, with the labels that each got.

#8696 Fix tuple printing in LFSC
  src/proof/lfsc/lfsc_node_converter.cpp
  src/proof/lfsc/lfsc_node_converter.h
Labels: normal, moderate

#8687 Further refactoring in preparation for CONST_INTEGER
  src/expr/node_manager_template.cpp
  src/expr/node_manager_template.h
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/linear/infer_bounds.cpp
  src/theory/arith/linear/normal_form.cpp
  src/theory/arith/linear/normal_form.h
  src/theory/arith/rewriter/node_utils.h
  src/theory/arith/theory_arith_type_rules.cpp
  src/theory/quantifiers/instantiate.cpp
Labels: normal, moderate

#8690 docs: Do not use explicit line numbers in literalinclude.
  docs/api/cpp/quickstart.rst
  docs/api/java/quickstart.rst
  docs/api/python/base/quickstart.rst
  docs/api/python/pythonic/quickstart.rst
  docs/binary/quickstart.rst
  examples/api/cpp/quickstart.cpp
  examples/api/java/QuickStart.java
  examples/api/python/pythonic/quickstart.py
  examples/api/python/quickstart.py
  examples/api/smtlib/quickstart.smt2
Labels: normal, simple

#8688 Add missing tests for some corners of the API
  src/api/cpp/cvc5.cpp
  src/api/python/cvc5.pxi
  test/unit/api/cpp/datatype_api_black.cpp
  test/unit/api/cpp/grammar_black.cpp
  test/unit/api/cpp/op_black.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/cpp/solver_white.cpp
  test/unit/api/cpp/synth_result_black.cpp
  test/unit/api/cpp/term_black.cpp
  test/unit/api/java/OpTest.java
  test/unit/api/java/UncoveredTest.cpp
  test/unit/api/python/test_op.py
  test/unit/api/python/test_solver.py
  test/unit/api/python/test_term.py
  test/unit/api/python/test_uncovered.cpp
Labels: normal, moderate

#8694 Make arith msum utility agnostic to Int
  src/theory/arith/arith_msum.cpp
  src/theory/arith/arith_msum.h
  src/theory/arith/arith_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/nl/issue8691-3-msum-subtypes.smt2
  test/regress/cli/regress0/nl/issue8691-msum-subtypes.smt2
Labels: minor, simple

#8695 More robust treatment of flattening in arith rewriter
  src/theory/arith/arith_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/nl/issue8692-idem-flatten.smt2
  test/regress/cli/regress2/nl/issue8693-flatten-to-real.smt2
Labels: normal, moderate

#8684 Migrate basic EqualityEngine management from CongruenceManager to EqSolver
  src/options/arith_options.toml
  src/smt/set_defaults.cpp
  src/theory/arith/equality_solver.cpp
  src/theory/arith/equality_solver.h
  src/theory/arith/linear/congruence_manager.cpp
  src/theory/arith/linear/congruence_manager.h
  src/theory/arith/linear/theory_arith_private.cpp
  src/theory/arith/linear/theory_arith_private.h
  src/theory/arith/theory_arith.cpp
Labels: normal, moderate

#8700 Final preparation for CONST_INTEGER
  src/api/cpp/cvc5.cpp
  src/expr/node_manager_template.cpp
  src/theory/arith/arith_poly_norm.cpp
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_rewriter.h
  src/theory/arith/arith_utilities.h
  src/theory/arith/linear/normal_form.cpp
  src/theory/arith/linear/theory_arith_private.cpp
  src/theory/arith/rewriter/node_utils.cpp
  src/theory/arith/rewriter/node_utils.h
  test/unit/node/node_algorithm_black.cpp
  test/unit/node/node_black.cpp
  test/unit/node/node_manager_black.cpp
  test/unit/node/node_manager_white.cpp
  test/unit/node/node_white.cpp
  test/unit/node/type_node_white.cpp
  test/unit/preprocessing/pass_foreign_theory_rewrite_white.cpp
  test/unit/theory/arith_poly_white.cpp
  test/unit/theory/evaluator_white.cpp
  test/unit/theory/sequences_rewriter_white.cpp
  test/unit/theory/theory_arith_coverings_white.cpp
  test/unit/theory/theory_arith_pow2_white.cpp
  test/unit/theory/theory_arith_rewriter_black.cpp
  test/unit/theory/theory_arith_white.cpp
  test/unit/theory/theory_bags_normal_form_white.cpp
  test/unit/theory/theory_bags_rewriter_white.cpp
  test/unit/theory/theory_bags_type_rules_white.cpp
  test/unit/theory/theory_black.cpp
  test/unit/theory/theory_bv_int_blaster_white.cpp
  test/unit/theory/theory_engine_white.cpp
  test/unit/theory/theory_int_opt_white.cpp
  test/unit/theory/theory_sets_rewriter_white.cpp
  test/unit/theory/theory_strings_skolem_cache_black.cpp
  test/unit/theory/type_enumerator_white.cpp
  test/unit/util/array_store_all_white.cpp
  test/unit/util/datatype_black.cpp
Labels: normal, moderate

#8702 Simplify representation of datatypes at the TypeNode level
  src/expr/CMakeLists.txt
  src/expr/datatype_index.cpp
  src/expr/datatype_index.h
  src/expr/dtype.cpp
  src/expr/dtype.h
  src/expr/node_manager_attributes.h
  src/expr/node_manager_template.cpp
  src/expr/node_manager_template.h
  src/expr/type_node.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/datatypes/kinds
Labels: minor, moderate

#8701 Change option name for mbqi in fmf
  src/options/quantifiers_options.toml
  src/smt/set_defaults.cpp
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/quantifiers/fmf/model_builder.cpp
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/term_registry.cpp
  src/theory/quantifiers_engine.cpp
Labels: minor, simple

#8710 docs: Some fixes in options docs.
  docs/options.rst
Labels: normal, simple

#8699 Use (non-recursive) unpurified form instead of original form for defining Skolems
  proofs/lfsc/signatures/quantifiers_rules.plf
  proofs/lfsc/signatures/strings_programs.plf
  proofs/lfsc/signatures/strings_rules.plf
  proofs/lfsc/signatures/util_defs.plf
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/proof/lfsc/lfsc_node_converter.cpp
  src/proof/lfsc/lfsc_printer.cpp
  src/proof/proof_rule.h
  src/smt/witness_form.cpp
  src/theory/quantifiers/proof_checker.cpp
Labels: major, moderate

#8713 Update LFSC version
  contrib/get-lfsc-checker
Labels: minor, simple

#8706 Fix LFSC node converter for 0-ary tuples
  src/proof/lfsc/lfsc_node_converter.cpp
Labels: major, simple

#8707 Add support for oracle constant nodes
  src/expr/CMakeLists.txt
  src/expr/node_manager_attributes.h
  src/expr/node_manager_template.cpp
  src/expr/node_manager_template.h
  src/expr/oracle.h
  src/theory/quantifiers/kinds
Labels: normal, moderate

#8716 Remove obsolete private methods from API
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
Labels: normal, moderate

#8715 Remove unecessary calls to equality engine from congruence manager
  src/theory/arith/linear/congruence_manager.cpp
  src/theory/arith/linear/congruence_manager.h
  src/theory/arith/linear/constraint.cpp
  src/theory/arith/linear/constraint.h
Labels: minor, simple

#8717 Refactor oracles using new std::function backend
  src/expr/oracle_caller.cpp
  src/expr/oracle_caller.h
  src/theory/quantifiers/oracle_checker.cpp
  src/theory/quantifiers/oracle_checker.h
  src/theory/quantifiers/oracle_engine.cpp
  src/theory/quantifiers/oracle_engine.h
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers/quantifiers_attributes.h
  src/theory/quantifiers/sygus/synth_verify.cpp
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: normal, moderate

#8721 Make printStatisticsSafe public
  src/api/cpp/cvc5.h
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/cpp/solver_white.cpp
  test/unit/api/java/UncoveredTest.cpp
  test/unit/api/python/test_uncovered.cpp
Labels: normal, moderate

#8719 Make equality solver the entry point for all equality engine explanations in arithmetic
  src/theory/arith/equality_solver.cpp
  src/theory/arith/linear/congruence_manager.cpp
  src/theory/arith/linear/congruence_manager.h
  src/theory/arith/linear/constraint.cpp
  src/theory/arith/linear/constraint.h
  src/theory/arith/linear/theory_arith_private.cpp
  src/theory/arith/theory_arith.cpp
Labels: normal, moderate

#8718 Improve finding Python library/includes
  src/api/python/CMakeLists.txt
Labels: normal, moderate

#8711 Use purification for set comprehension reduction
  src/theory/sets/theory_sets_private.cpp
Labels: minor, simple

#8681 Add operators table.aggr and table.join
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_kind.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/bags/bag_reduction.cpp
  src/theory/bags/bag_reduction.h
  src/theory/bags/bag_solver.cpp
  src/theory/bags/bag_solver.h
  src/theory/bags/bags_rewriter.cpp
  src/theory/bags/bags_rewriter.h
  src/theory/bags/bags_utils.cpp
  src/theory/bags/bags_utils.h
  src/theory/bags/card_solver.cpp
  src/theory/bags/card_solver.h
  src/theory/bags/inference_generator.cpp
  src/theory/bags/inference_generator.h
  src/theory/bags/kinds
  src/theory/bags/rewrites.cpp
  src/theory/bags/rewrites.h
  src/theory/bags/table_project_op.cpp
  src/theory/bags/table_project_op.h
  src/theory/bags/theory_bags.cpp
  src/theory/bags/theory_bags.h
  src/theory/bags/theory_bags_type_rules.cpp
  src/theory/bags/theory_bags_type_rules.h
  src/theory/datatypes/tuple_utils.cpp
  src/theory/datatypes/tuple_utils.h
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/bags/table_aggregate1.smt2
  test/regress/cli/regress1/bags/table_join1.smt2
  test/regress/cli/regress1/bags/table_join2.smt2
  test/regress/cli/regress1/bags/table_join3.smt2
  test/unit/theory/theory_bags_normal_form_white.cpp
Labels: normal

#8727 Fix more issues with subtypes in regressions
  test/regress/cli/regress0/nl/issue8691-3-msum-subtypes.smt2
  test/regress/cli/regress0/nl/issue8692-idem-flatten.smt2
  test/regress/cli/regress1/fmf/issue3626.smt2
  test/regress/cli/regress1/fmf/sort-inf-int-real.smt2
  test/regress/cli/regress1/nl/issue7948-3-unsound-sin-region.smt2
  test/regress/cli/regress1/nl/issue8162-drop-pi-bound.smt2
Labels: minor, simple

#8725 Fix cache in learned rewrite preprocessing pass
  src/preprocessing/passes/learned_rewrite.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/strings/issue8722-learned-rew.smt2
Labels: minor, simple

#8728 Preparation for making equality strictly typed
  src/smt/proof_post_processor.cpp
  src/theory/arith/arith_msum.cpp
  src/theory/arith/arith_utilities.cpp
  src/theory/arith/arith_utilities.h
  src/theory/arith/bound_inference.cpp
  src/theory/arith/linear/normal_form.cpp
  src/theory/arith/linear/normal_form.h
  src/theory/arith/nl/ext/ext_state.cpp
  src/theory/arith/nl/ext/factoring_check.cpp
  src/theory/arith/nl/ext/monomial_check.cpp
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/nl/pow2_solver.cpp
  src/theory/arith/nl/transcendental/exponential_solver.cpp
  src/theory/arith/nl/transcendental/proof_checker.cpp
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  src/theory/arith/operator_elim.cpp
  src/theory/arith/proof_checker.cpp
  src/theory/quantifiers/cegqi/ceg_arith_instantiator.cpp
Labels: normal, moderate

#8720 Add test coverage for almost everything from the Python API
  src/api/cpp/cvc5.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  test/unit/api/python/test_datatype_api.py
  test/unit/api/python/test_grammar.py
  test/unit/api/python/test_uncovered.cpp
Labels: normal, moderate

#8726 Fix LFSC side condition for matching premise of concat_unify
  proofs/lfsc/signatures/strings_rules.plf
Labels: normal, simple

#8734 Separate ill-typed portion of arith models
  src/theory/arith/linear/theory_arith_private.cpp
  src/theory/arith/linear/theory_arith_private.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
Labels: normal, moderate, do not merge

#8724 Eliminate arithmetic subtyping for (dis)equalities from TPTP parser
  src/parser/tptp/tptp.cpp
Labels: normal, simple

#8730 Fallback for sequential substitution proof reconstruction
  src/smt/proof_post_processor.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress2/strings/dd.trust-subs.smt2
Labels: normal, moderate

#8708 Fix proofs for ppAssert for theory Bool
  src/theory/booleans/theory_bool.cpp
  src/theory/theory.cpp
  src/theory/theory_engine.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/cores/issue8705-bool-ppassert.smt2
Labels: normal, moderate

#8733 More preparation for strict type rules
  src/preprocessing/passes/unconstrained_simplifier.cpp
  src/theory/arith/arith_msum.cpp
  src/theory/arith/arith_utilities.cpp
  src/theory/arith/arith_utilities.h
  src/theory/arith/linear/theory_arith_private.cpp
  src/theory/arith/nl/ext/monomial_bounds_check.cpp
  src/theory/arith/nl/ext/monomial_check.cpp
  src/theory/arith/nl/nl_model.cpp
  src/theory/arith/nl/transcendental/exponential_solver.cpp
  src/theory/arith/nl/transcendental/proof_checker.cpp
  src/theory/arith/operator_elim.cpp
  src/theory/quantifiers/cegqi/ceg_arith_instantiator.cpp
  src/theory/quantifiers/sygus_sampler.cpp
  src/theory/substitutions.cpp
  test/api/cpp/reset_assertions.cpp
  test/api/python/reset_assertions.py
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/datatypes/dd.pair-real-bool-const-conf.smt2
  test/regress/cli/regress1/abduction/abd-real-const.smt2
  test/regress/cli/regress1/ho/issue4758.smt2
Labels: normal, moderate

#8732 Do not rely on subtyping in real-to-int preprocessing pass
  src/preprocessing/passes/real_to_int.cpp
Labels: normal, simple

#8741 Add unit tests for getInstantiations
  src/api/cpp/cvc5.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
Labels: minor, simple

#8737 Do not rely on subtyping for APPLY_UF in TPTP parser
  src/parser/tptp/tptp.cpp
  src/parser/tptp/tptp.h
Labels: normal, moderate

#8743 Compress debug symbols to make libcvc5 smaller
  CMakeLists.txt
Labels: normal, simple

#8723 Add test coverage for almost everything from the Java API
  src/api/java/io/github/cvc5/DatatypeDecl.java
  src/api/java/jni/solver.cpp
  test/unit/api/java/CMakeLists.txt
  test/unit/api/java/DatatypeTest.java
  test/unit/api/java/GrammarTest.java
  test/unit/api/java/OpTest.java
  test/unit/api/java/SolverTest.java
  test/unit/api/java/SortTest.java
  test/unit/api/java/UncoveredTest.cpp
Labels: normal, moderate, do not merge

#8746 Fix some issues with the Python API tests
  src/api/python/cvc5.pxi
  test/unit/api/python/test_solver.py
  test/unit/api/python/test_sort.py
Labels: normal, moderate

#8748 Ensure substitutions in nonlinear solver are properly typed
  src/theory/arith/nl/equality_substitution.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/nl/issue8744-int.smt2
  test/regress/cli/regress0/nl/issue8744-real-cov.smt2
  test/regress/cli/regress0/nl/issue8744-real.smt2
Labels: normal, moderate

#8751 Relax an assertion in the evaluator
  src/theory/evaluator.cpp
Labels: minor, simple

#8752 Remove --build from GMP configure line
  cmake/FindGMP.cmake
Labels: major, moderate

#8754 Make regular options access const
  src/api/cpp/cvc5.cpp
  src/options/README.md
  src/options/mkoptions.py
  src/options/options_handler.cpp
  src/options/options_template.cpp
  src/smt/set_defaults.cpp
  src/smt/solver_engine.cpp
  src/smt/sygus_solver.cpp
  src/theory/quantifiers/query_generator_unsat.cpp
  src/theory/quantifiers/sygus/synth_verify.cpp
  test/unit/node/node_black.cpp
  test/unit/theory/theory_arith_coverings_white.cpp
Labels: normal, moderate

#8747 [docs] Marking internal comment in proofs docs
  src/proof/proof_rule.h
Labels: minor, simple

#8740 Preserve types in rewriter and make core type rules strict
  NEWS.md
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/cpp/cvc5_kind.h
  src/expr/mkmetakind
  src/expr/node_manager_template.cpp
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/prop/prop_engine.cpp
  src/theory/arith/arith_msum.cpp
  src/theory/arith/linear/congruence_manager.cpp
  src/theory/arith/linear/constraint.cpp
  src/theory/arith/linear/normal_form.cpp
  src/theory/arith/nl/nl_model.cpp
  src/theory/arith/rewriter/rewrite_atom.cpp
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith_type_rules.cpp
  src/theory/booleans/theory_bool_type_rules.cpp
  src/theory/builtin/theory_builtin_type_rules.cpp
  src/theory/datatypes/sygus_datatype_utils.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/quantifiers/fmf/full_model_check.h
  src/theory/quantifiers/sygus/type_info.cpp
  src/theory/rewriter.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_model.cpp
  src/theory/uf/theory_uf_type_rules.cpp
  test/regress/cli/regress0/nl/issue8744-int.smt2
  test/regress/cli/regress0/nl/issue8744-real-cov.smt2
  test/regress/cli/regress0/nl/issue8744-real.smt2
  test/regress/cli/regress0/nl/nta/issue8147-unc-model.smt2
  test/regress/cli/regress1/fmf/issue3626.smt2
  test/regress/cli/regress1/fmf/sort-inf-int-real.smt2
  test/regress/cli/regress1/nl/bad-050217.smt2
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
  test/unit/theory/theory_arith_white.cpp
Labels: normal, complex

#8756 Eliminate use of subtypes from remainder of type rules
  src/expr/type_matcher.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/arith/theory_arith_type_rules.cpp
  src/theory/arrays/theory_arrays_type_rules.cpp
  src/theory/bags/theory_bags_type_rules.cpp
  src/theory/datatypes/theory_datatypes_type_rules.cpp
  src/theory/sets/theory_sets_type_rules.cpp
  src/theory/strings/theory_strings_type_rules.cpp
  src/theory/uf/theory_uf_type_rules.cpp
Labels: normal, simple

#8762 Fix type of null terminator for ADD/MULT for LFSC
  src/expr/nary_term_util.cpp
  src/expr/node_converter.cpp
Labels: major, simple

#8753 Minor refactoring for sep theory
  src/theory/sep/theory_sep.cpp
  src/theory/sep/theory_sep.h
Labels: normal, moderate

#8763 Fix debug failures in LFSC proofs due to curried arithmetic operators
  src/proof/lfsc/lfsc_node_converter.cpp
  src/proof/lfsc/lfsc_post_processor.cpp
  src/proof/lfsc/lfsc_printer.cpp
Labels: major, moderate

#8766 Add utilities in preparation for supporting str.nth
  src/theory/evaluator.cpp
  src/theory/strings/kinds
  src/theory/strings/theory_strings_utils.cpp
  src/theory/strings/theory_strings_utils.h
  src/theory/strings/word.cpp
  src/theory/strings/word.h
Labels: normal, moderate

#8771 Fixes and improvement for IAND solver
  src/options/smt_options.toml
  src/theory/arith/nl/iand_solver.cpp
  src/theory/arith/nl/nl_model.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/nl/dd.iand-wrong-0513-pp.smt2
  test/regress/cli/regress1/bv/dd.iand-wrong-0513.smt2
Labels: normal, moderate

#8765 Make arith substitute its own utility
  src/CMakeLists.txt
  src/expr/subs.cpp
  src/expr/subs.h
  src/theory/arith/arith_subs.cpp
  src/theory/arith/arith_subs.h
  src/theory/arith/arith_utilities.cpp
  src/theory/arith/arith_utilities.h
  src/theory/arith/nl/nl_model.cpp
  src/theory/arith/nl/nl_model.h
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
Labels: normal, moderate

#8761 Eliminate ops for parameterized type constructors
  src/CMakeLists.txt
  src/api/cpp/cvc5.cpp
  src/expr/node_manager_template.cpp
  src/expr/node_manager_template.h
  src/proof/lfsc/lfsc_node_converter.cpp
  src/theory/bags/bag_make_op.cpp
  src/theory/bags/bag_make_op.h
  src/theory/bags/bag_reduction.cpp
  src/theory/bags/bags_rewriter.cpp
  src/theory/bags/bags_rewriter.h
  src/theory/bags/bags_utils.cpp
  src/theory/bags/kinds
  src/theory/bags/theory_bags.cpp
  src/theory/bags/theory_bags_type_enumerator.cpp
  src/theory/bags/theory_bags_type_rules.cpp
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/sets/cardinality_extension.cpp
  src/theory/sets/kinds
  src/theory/sets/normal_form.h
  src/theory/sets/singleton_op.cpp
  src/theory/sets/singleton_op.h
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_rels.cpp
  src/theory/sets/theory_sets_rels.h
  src/theory/sets/theory_sets_rewriter.cpp
  src/theory/sets/theory_sets_type_enumerator.cpp
  src/theory/sets/theory_sets_type_rules.cpp
  src/theory/sets/theory_sets_type_rules.h
  src/theory/strings/array_core_solver.cpp
  src/theory/strings/kinds
  src/theory/strings/seq_unit_op.cpp
  src/theory/strings/seq_unit_op.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/theory_strings_type_rules.cpp
  src/theory/strings/theory_strings_utils.cpp
  test/unit/theory/sequences_rewriter_white.cpp
  test/unit/theory/theory_bags_normal_form_white.cpp
  test/unit/theory/theory_bags_rewriter_white.cpp
  test/unit/theory/theory_bags_type_rules_white.cpp
  test/unit/theory/theory_sets_rewriter_white.cpp
  test/unit/theory/theory_sets_type_rules_white.cpp
Labels: normal, moderate

#8759 Eliminate the use of CAST_TO_REAL
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/expr/subtype_elim_node_converter.cpp
  src/expr/subtype_elim_node_converter.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/proof/alethe/alethe_nosubtype_node_converter.cpp
  src/proof/lfsc/lfsc_node_converter.cpp
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/kinds
  src/theory/arith/theory_arith_type_rules.cpp
  src/theory/evaluator.cpp
Labels: normal, simple

#8780 Rename equality engine trace to print E-graph
  src/theory/uf/equality_engine.cpp
Labels: normal, simple

#8781 [proofs] Generalize handling of constants merged in equality engine
  src/theory/uf/eq_proof.cpp
  src/theory/uf/equality_engine.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/proofs/eq-engine-corner-case-constants-disequal.smt2
Labels: normal, moderate

#8772 Last remaining fixes for eliminating subtyping
  NEWS.md
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/expr/array_store_all.cpp
  src/theory/arith/linear/theory_arith_private.cpp
  src/theory/arith/nl/ext/monomial_check.cpp
  src/theory/sets/term_registry.cpp
  src/theory/sets/term_registry.h
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
  test/unit/theory/theory_arith_white.cpp
  test/unit/util/array_store_all_white.cpp
Labels: major, moderate

#8768 Generalize pto constraint tracking for multiple heaps in sep theory
  src/theory/sep/theory_sep.cpp
  src/theory/sep/theory_sep.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/sep/issue8659-wand-diff-heaps.smt2
Labels: normal, moderate

#8739 Fix LFSC proof construction for concat clash of sequences
  src/proof/lfsc/lfsc_post_processor.cpp
  src/proof/proof_rule.h
  src/theory/strings/infer_proof_cons.cpp
  src/theory/strings/proof_checker.cpp
  test/regress/cli/regress0/seq/seq-types.smt2
Labels: minor, moderate

#8791 Minor cleanup of datatypes theory
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
Labels: minor, simple

#8742 Refactor declare oracle command
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/smt/command.cpp
  src/smt/command.h
Labels: minor, simple

#8749 Make skolem definition manager robust to definitions for already asserted skolems
  src/prop/prop_engine.cpp
  src/prop/skolem_def_manager.cpp
  src/prop/skolem_def_manager.h
  src/prop/theory_proxy.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/quantifiers/proj-issue512-has-skolem.smt2
  test/regress/cli/regress1/strings/issue8347-has-skolem.smt2
Labels: normal, moderate, do not merge

#8790 Basic cleanup of sep theory
  src/theory/sep/theory_sep.cpp
  src/theory/sep/theory_sep.h
Labels: minor, moderate

#8803 Add options and regressions to increase coverage
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/model-core-non-implied.smt2
  test/regress/cli/regress0/model-core.smt2
  test/regress/cli/regress1/push-pop/arith_lra_01.smt2
  test/regress/cli/regress1/push-pop/fuzz_5_1.smt2
  test/regress/cli/regress1/sygus/grammar_norm.sy
  test/regress/cli/regress2/arith/sc-7.base.cvc.smtv1.smt2
  test/regress/cli/regress2/sygus/qgu-bools.sy
Labels: normal, simple

#8800 Minor deleting of unused code
  src/smt/command.cpp
  src/smt/command.h
  src/theory/arith/linear/normal_form.cpp
  src/theory/arith/linear/normal_form.h
  src/theory/quantifiers/ematching/inst_match_generator_multi.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching_user.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching_user.h
  src/theory/quantifiers/inst_match_trie.cpp
  src/theory/quantifiers/inst_match_trie.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/instantiate.h
  src/theory/quantifiers/quantifiers_state.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/uf/theory_uf_model.cpp
  src/theory/uf/theory_uf_model.h
Labels: minor, simple

#8745 New way to identify THEORY_LEMMA clusters when printing in the .dot format
  src/proof/dot/dot_printer.cpp
  src/proof/dot/dot_printer.h
Labels: normal, simple

#8698 Trying to break cycles when printing a .dot DAG
  src/proof/dot/dot_printer.cpp
  src/proof/dot/dot_printer.h
Labels: normal, simple

#8806 More removing of unused code
  src/CMakeLists.txt
  src/theory/arith/linear/theory_arith_private.cpp
  src/theory/arrays/union_find.cpp
  src/theory/arrays/union_find.h
  src/theory/engine_output_channel.cpp
  src/theory/engine_output_channel.h
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/output_channel.h
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  src/theory/quantifiers/ematching/instantiation_engine.h
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/fmf/model_engine.h
  src/theory/quantifiers/inst_match_trie.cpp
  src/theory/quantifiers/inst_match_trie.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/instantiate.h
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus/synth_engine.h
Labels: minor, simple

#8758 Add cross-compilation for arm64 on MacOS
  .github/workflows/ci.yml
  NEWS.md
  cmake/FindANTLR3.cmake
  cmake/FindCaDiCaL.cmake
  cmake/FindGMP.cmake
  cmake/Toolchain-aarch64.cmake
  cmake/deps-utils/gmp-test.cpp
Labels: normal, moderate

#8796 Add option to send all instantiations in a bounded range
  src/options/quantifiers_options.toml
  src/theory/quantifiers/fmf/full_model_check.cpp
Labels: minor, simple

#8797 Reenable assertion in skolem definition manager
  src/prop/skolem_def_manager.cpp
Labels: minor, simple

#8799 Move smt_util to preprocessing/util
  src/CMakeLists.txt
  src/preprocessing/passes/miplib_trick.cpp
  src/preprocessing/util/boolean_simplification.cpp
  src/preprocessing/util/boolean_simplification.h
  src/printer/smt2/smt2_printer.cpp
  src/theory/arith/linear/theory_arith_private.cpp
  src/theory/booleans/theory_bool.cpp
  test/unit/util/boolean_simplification_black.cpp
Labels: minor, simple

#8801 Simplification of smt2 printer for type ascriptions
  src/printer/smt2/smt2_printer.cpp
Labels: minor, simple

#8788 bv: Add resource limits support for CaDiCaL.
  src/prop/cadical.cpp
  src/prop/cadical.h
  src/prop/sat_solver_factory.cpp
  src/util/resource_manager.cpp
  src/util/resource_manager.h
Labels: normal, simple

#8811 Make model core robust to when we cannot show the model satisfies input
  src/smt/model_core_builder.cpp
  src/theory/subs_minimize.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/issue8807-model-core-partial.smt2
Labels: minor, simple

#8812 Remove spurious assertion in isLegalElimination
  src/theory/theory.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arith/issue8805-mixed-var-elim.smt2
Labels: minor, simple

#8731 Add table.group operator
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_kind.h
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/bags/bag_reduction.cpp
  src/theory/bags/bag_reduction.h
  src/theory/bags/bags_utils.cpp
  src/theory/bags/bags_utils.h
  src/theory/bags/kinds
  src/theory/bags/solver_state.cpp
  src/theory/bags/table_project_op.cpp
  src/theory/bags/table_project_op.h
  src/theory/bags/theory_bags.cpp
  src/theory/bags/theory_bags_type_rules.cpp
  src/theory/bags/theory_bags_type_rules.h
  src/theory/datatypes/tuple_utils.cpp
  src/theory/datatypes/tuple_utils.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/bags/table_group1.smt2
Labels: normal, moderate

#8816 bv: Disable rule ExtractArith.
  src/options/bv_options.toml
  src/theory/bv/theory_bv_rewriter.cpp
Labels: normal, simple

#8782 Fix subtype issues in proofs for nonlinear solver
  src/theory/arith/nl/coverings/proof_generator.cpp
  src/theory/arith/nl/ext/monomial_bounds_check.cpp
Labels: minor, simple

#8793 Introduce function array constant
  src/expr/CMakeLists.txt
  src/expr/function_array_const.cpp
  src/expr/function_array_const.h
  src/theory/uf/kinds
  src/theory/uf/theory_uf_type_rules.cpp
  src/theory/uf/theory_uf_type_rules.h
Labels: normal, moderate

#8802 Eliminate more static options accesses
  src/options/quantifiers_options.toml
  src/theory/difficulty_manager.cpp
  src/theory/difficulty_manager.h
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/relevance_manager.cpp
  test/regress/cli/regress2/sygus/issue4022-conjecture-gen.smt2
Labels: minor, simple

#8804 Eliminate static access to dtSharedSelectors
  src/expr/dtype_cons.cpp
  src/expr/dtype_cons.h
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/datatypes_rewriter.h
  src/theory/datatypes/proof_checker.cpp
  src/theory/datatypes/proof_checker.h
  src/theory/datatypes/sygus_extension.cpp
  src/theory/datatypes/sygus_extension.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes_utils.cpp
  src/theory/datatypes/theory_datatypes_utils.h
  src/theory/datatypes/tuple_utils.cpp
  src/theory/quantifiers/cegqi/ceg_dt_instantiator.cpp
  src/theory/quantifiers/ematching/candidate_generator.cpp
  src/theory/quantifiers/ematching/candidate_generator.h
  src/theory/quantifiers/ematching/inst_match_generator.cpp
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/skolemize.cpp
  src/theory/quantifiers/sygus/sygus_eval_unfold.cpp
  src/theory/quantifiers/sygus/sygus_explain.cpp
  src/theory/quantifiers/sygus/sygus_explain.h
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus_inst.cpp
Labels: normal, moderate

#8729 Add model-based quantifier instantiation
  src/CMakeLists.txt
  src/options/quantifiers_options.toml
  src/preprocessing/passes/sort_infer.cpp
  src/smt/set_defaults.cpp
  src/smt/solver_engine.cpp
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/quantifiers/inst_strategy_enumerative.h
  src/theory/quantifiers/inst_strategy_mbqi.cpp
  src/theory/quantifiers/inst_strategy_mbqi.h
  src/theory/quantifiers/quantifiers_modules.cpp
  src/theory/quantifiers/quantifiers_modules.h
  src/theory/quantifiers/skolemize.h
  src/theory/smt_engine_subsolver.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/ho/issue6536.smt2
  test/regress/cli/regress0/push-pop/inc-double-u.smt2
  test/regress/cli/regress0/quantifiers/mbqi-simple.smt2
  test/regress/cli/regress1/bug567.smt2
  test/regress/cli/regress1/fmf/issue3587.smt2
  test/regress/cli/regress1/quantifiers/dt-tc-opt-small.smt2
  test/regress/cli/regress1/quantifiers/issue3724-quant.smt2
Labels: normal, moderate

#8817 [proofs] [alethe] Remove static call to options from post-processor
  src/proof/alethe/alethe_post_processor.cpp
  src/proof/alethe/alethe_post_processor.h
  src/smt/proof_manager.cpp
Labels: minor, simple

#8795 Eliminate some static options access
  src/options/strings_options.toml
  src/prop/sat_proof_manager.cpp
  src/smt/abstract_values.cpp
  src/smt/abstract_values.h
  src/smt/command.cpp
  src/smt/command.h
  src/smt/preprocess_proof_generator.cpp
  src/smt/proof_final_callback.cpp
  src/smt/proof_final_callback.h
  src/smt/proof_post_processor.cpp
  src/smt/solver_engine.cpp
  src/theory/datatypes/inference.cpp
  src/theory/datatypes/inference_manager.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.h
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/sygus_repair_const.cpp
  src/theory/strings/normal_form.cpp
Labels: minor, simple

#8824 Make sure phase-shift lemma is properly typed
  src/theory/arith/nl/transcendental/sine_solver.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/nl/nta/issue8773-phase-shift.smt2
Labels: minor, moderate

#8828 Make Rewriter::rewrite non-static
  src/preprocessing/preprocessing_pass.cpp
  src/smt/listeners.cpp
  src/smt/solver_engine_scope.cpp
  src/smt/solver_engine_scope.h
  src/theory/evaluator.cpp
  src/theory/rewriter.cpp
  src/theory/rewriter.h
  test/unit/preprocessing/pass_bv_gauss_white.cpp
  test/unit/theory/regexp_operation_black.cpp
  test/unit/theory/strings_rewriter_white.cpp
  test/unit/theory/theory_arith_white.cpp
  test/unit/theory/theory_bags_rewriter_white.cpp
  test/unit/theory/theory_black.cpp
  test/unit/theory/theory_bv_int_blaster_white.cpp
  test/unit/theory/theory_bv_rewriter_white.cpp
  test/unit/theory/theory_engine_white.cpp
  test/unit/theory/theory_sets_rewriter_white.cpp
  test/unit/theory/theory_sets_type_enumerator_white.cpp
Labels: minor, simple

#8829 Eliminate static options access in BV inverter
  src/theory/quantifiers/bv_inverter.cpp
  src/theory/quantifiers/bv_inverter.h
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.h
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
Labels: minor, simple

#8826 Fix mixed arithmetic issue in relevant domain
  src/theory/quantifiers/relevant_domain.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/quantifiers/issue8821-enum-interleave-types.smt2
Labels: normal, simple

#8831 Eliminate static options access in skolemize
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/quantifiers_preprocess.cpp
  src/theory/quantifiers/skolemize.cpp
  src/theory/quantifiers/skolemize.h
Labels: minor, simple

#8823 Eliminate static options access for central ee
  src/theory/combination_engine.cpp
  src/theory/ee_manager_central.cpp
  src/theory/ee_manager_central.h
  src/theory/term_registration_visitor.cpp
  src/theory/theory.cpp
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: minor, moderate

#8832 Eliminate more static options accesses
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/quant_conflict_find.h
Labels: minor, simple

#8838 Fix FindCaDiCaL script
  cmake/FindCaDiCaL.cmake
Labels: normal, moderate

#8837 Fix issues with to_real around coverings solver
  src/theory/arith/nl/coverings_solver.cpp
  src/theory/arith/nl/equality_substitution.cpp
  src/theory/arith/nl/poly_conversion.cpp
  src/theory/arith/nl/poly_conversion.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/nl/issue8835-int-second.smt2
Labels: major, moderate

#8839 Make subs minimize utility robust to non-constant evaluation
  src/theory/subs_minimize.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/issue8834-model-core-nconst.smt2
Labels: minor, simple
