Repository cvc5/cvc5, pull requests merged in 2022-12, with the labels that each got.

#9302 fp: Send rewritten lemma.
  src/theory/fp/theory_fp.cpp
Labels: normal, simple

#9306 Do not send trivial splits when handling string disequalities
  src/theory/strings/core_solver.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/strings/issue9287-trivial-deq-disl.smt2
Labels: normal, simple

#9304 Consolidate delayed resolution of indexed operators in the parser
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
Labels: normal, moderate

#9305 Do not lex custom constant array syntax
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
Labels: normal, simple

#9310 Move input stream exception to parser exception file
  src/parser/input.cpp
  src/parser/input.h
  src/parser/parser_exception.h
Labels: minor, simple

#9290 Move ANTLR specific file inclusion to base parser
  src/parser/CMakeLists.txt
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/parser_utils.cpp
  src/parser/parser_utils.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/parser/tptp/Tptp.g
  src/parser/tptp/tptp.cpp
  src/parser/tptp/tptp.h
Labels: normal, simple

#9268 Decouple Assertions and AssertionsPipeline
  src/smt/assertions.cpp
  src/smt/assertions.h
  src/smt/preprocessor.cpp
  src/smt/smt_driver.cpp
  src/smt/smt_driver.h
  src/smt/smt_driver_deep_restarts.cpp
  src/smt/smt_driver_deep_restarts.h
  src/smt/smt_solver.cpp
  src/smt/smt_solver.h
  src/smt/solver_engine.cpp
Labels: normal, moderate

#9311 Move parsing of SMT-specific sorts to cpp
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
Labels: normal, simple

#9313 Do not reset context when checking again with SmtDriver
  src/smt/context_manager.cpp
  src/smt/smt_driver.cpp
  src/smt/smt_driver_deep_restarts.cpp
  src/smt/solver_engine.cpp
  src/theory/uf/equality_engine.cpp
Labels: normal, moderate

#9322 SetDefaults: Use const references for parameters of member functions.
  src/smt/set_defaults.cpp
  src/smt/set_defaults.h
Labels: normal, simple

#9327 fp: Guard tracing in wordBlastAndEquateTerm().
  src/theory/fp/theory_fp.cpp
Labels: minor, simple

#9333 fp: Use TheoryEqNotifyClass instead of custom derivation of EqualityEngineNotify.
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp.h
Labels: normal, simple

#9336 fp: Use fixed with integers for FP format sizes.
  src/theory/fp/theory_fp.cpp
Labels: minor, simple

#9325 Add statistics for theory engine
  src/CMakeLists.txt
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/theory_engine_statistics.cpp
  src/theory/theory_engine_statistics.h
Labels: normal, simple

#9330 mkkind: Only unset patsub_replacement if bash version supports it
  src/expr/mkkind
Labels: simple

#9331 bv: Use Theory::ppAssert default implementation in ppAssert.
  src/theory/bv/theory_bv.cpp
Labels: normal, simple

#9332 bv: Remove redundant expandDefinition call in ppRewrite().
  src/theory/bv/theory_bv.cpp
Labels: normal, simple

#9335 Branch on option string names using hash map and switch-case
  src/options/mkoptions.py
  src/options/options_public_template.cpp
  test/unit/options/options_black.cpp
Labels: simple

#9334 Small cleanup in datatypes theory
  src/theory/datatypes/theory_datatypes.cpp
Labels: minor, simple

#9338 Guard remaining shopt patsub_replacement calls.
  src/expr/mkexpr
  src/expr/mkmetakind
Labels: major, simple

#9312 Decouple parser state from ANTLR specific parsing
  src/parser/CMakeLists.txt
  src/parser/antlr_input_imports.cpp
  src/parser/input_parser.h
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/parser_antlr.cpp
  src/parser/parser_antlr.h
  src/parser/parser_builder.cpp
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/parser/smt2/smt2_antlr.cpp
  src/parser/smt2/smt2_antlr.h
  src/parser/tptp/Tptp.g
  src/parser/tptp/tptp.cpp
  src/parser/tptp/tptp.h
  src/parser/tptp/tptp_antlr.cpp
  src/parser/tptp/tptp_antlr.h
  src/smt/smt_driver.cpp
  test/api/cpp/ouroborous.cpp
  test/api/cpp/smt2_compliance.cpp
  test/regress/cli/regress0/sygus/setFeature.sy
  test/unit/parser/parser_black.cpp
  test/unit/parser/parser_builder_black.cpp
Labels: normal, moderate

#9341 Fixes for TPTP parsing
  src/parser/tptp/Tptp.g
  src/parser/tptp/tptp.cpp
Labels: normal, simple

#9342 Refactor input parser for incremental string inputs
  src/main/interactive_shell.cpp
  src/parser/input_parser.cpp
  src/parser/input_parser.h
Labels: normal, simple

#9339 Delay possible inference processing in strings
  src/theory/strings/core_solver.cpp
  src/theory/strings/core_solver.h
Labels: normal, moderate

#9344 Clean parser state and smt2 parser state
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
Labels: normal, moderate

#9343 Make regressions robust to minor changes in parse error output
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/theory/theory_engine.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/bv/issue-4075.smt2
  test/regress/cli/regress0/bv/issue-4130.smt2
  test/regress/cli/regress0/parser/issue5163.smt2
  test/regress/cli/regress0/parser/non_well_founded_dt.smt2
  test/regress/cli/regress0/parser/parser-line-error.smt2
  test/regress/cli/regress0/quantifiers/issue4437-unc-quant.smt2
  test/regress/cli/regress0/sygus/no-logic.sy
  test/regress/cli/regress0/sygus/pLTL-sygus-syntax-err.sy
  test/regress/cli/regress0/sygus/setFeature.sy
  test/regress/cli/regress1/arrayinuf_error.smt2
Labels: normal, simple

#9340 Fix name for Theory engine stat
  src/theory/theory_engine_statistics.cpp
Labels: normal, simple

#9348 Add string rewrite for rev unit
  src/theory/strings/rewrites.cpp
  src/theory/strings/rewrites.h
  src/theory/strings/sequences_rewriter.cpp
Labels: minor, simple

#9351 fp: Simplify collectModelInfo.
  src/theory/fp/theory_fp.cpp
Labels: normal, simple

#9354 TheoryProxy: Remove unused member.
  src/prop/theory_proxy.h
Labels: normal, simple

#9353 Fix scope issues in interactive shell
  src/main/interactive_shell.cpp
  src/main/interactive_shell.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/issue9350-ishell-scope-reset.smt2
Labels: normal, simple

#9346 Make string cardinality check functionality more modular
  src/theory/strings/base_solver.cpp
  src/theory/strings/base_solver.h
Labels: minor, moderate

#9347 Separate shouldDoReduction from doReduction for strings ext solver
  src/theory/strings/extf_solver.cpp
  src/theory/strings/extf_solver.h
Labels: minor, moderate

#9349 Make virtual base class for model construction for strings
  src/CMakeLists.txt
  src/theory/strings/base_solver.cpp
  src/theory/strings/model_cons.h
  src/theory/strings/model_cons_default.cpp
  src/theory/strings/model_cons_default.h
  src/theory/strings/solver_state.cpp
  src/theory/strings/solver_state.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: minor, moderate

#9352 Always flush the command output
  src/parser/api/cpp/command.cpp
Labels: normal, simple

#9356 Minor improvements for handling str.code
  src/theory/strings/theory_strings.cpp
Labels: normal, moderate

#9361 Move string code point solver to own file
  src/CMakeLists.txt
  src/theory/strings/code_point_solver.cpp
  src/theory/strings/code_point_solver.h
  src/theory/strings/core_solver.cpp
  src/theory/strings/core_solver.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: minor, simple

#9359 Add flex input class
  src/parser/CMakeLists.txt
  src/parser/flex_input.cpp
  src/parser/flex_input.h
Labels: normal, simple

#9362 ff: fix warnings
  src/theory/ff/kinds
  src/theory/ff/theory_ff.cpp
Labels: minor, simple

#9360 Add new utility methods to smt2 parser state
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
Labels: normal, moderate

#9371 Add eager evaluation option for bv
  src/options/bv_options.toml
  src/options/strings_options.toml
  src/theory/bv/theory_bv.cpp
Labels: major, simple

#9365 Cache lemmas in TheoryStrings
  src/theory/strings/core_solver.cpp
  src/theory/strings/inference_manager.cpp
  src/theory/strings/solver_state.cpp
  src/theory/strings/solver_state.h
Labels: normal, moderate

#9368 Rename ExtTheory::markReduced to ExtTheory::markInactive
  src/theory/ext_theory.cpp
  src/theory/ext_theory.h
  src/theory/strings/array_core_solver.cpp
  src/theory/strings/extf_solver.cpp
  src/theory/strings/inference_manager.cpp
  src/theory/strings/inference_manager.h
  src/theory/strings/regexp_solver.cpp
Labels: minor, simple
