Repository cvc5/cvc5, pull requests merged in 2022-03, with the labels that each got.

#8187 Rename cad to coverings
  src/CMakeLists.txt
  src/options/arith_options.toml
  src/proof/lazy_tree_proof_generator.h
  src/proof/proof_rule.cpp
  src/proof/proof_rule.h
  src/smt/set_defaults.cpp
  src/theory/arith/nl/coverings/cdcac.cpp
  src/theory/arith/nl/coverings/cdcac.h
  src/theory/arith/nl/coverings/cdcac_utils.cpp
  src/theory/arith/nl/coverings/cdcac_utils.h
  src/theory/arith/nl/coverings/constraints.cpp
  src/theory/arith/nl/coverings/constraints.h
  src/theory/arith/nl/coverings/lazard_evaluation.cpp
  src/theory/arith/nl/coverings/lazard_evaluation.h
  src/theory/arith/nl/coverings/projections.cpp
  src/theory/arith/nl/coverings/projections.h
  src/theory/arith/nl/coverings/proof_checker.cpp
  src/theory/arith/nl/coverings/proof_checker.h
  src/theory/arith/nl/coverings/proof_generator.cpp
  src/theory/arith/nl/coverings/proof_generator.h
  src/theory/arith/nl/coverings/variable_ordering.cpp
  src/theory/arith/nl/coverings/variable_ordering.h
  src/theory/arith/nl/coverings_solver.cpp
  src/theory/arith/nl/coverings_solver.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/nl/poly_conversion.cpp
  src/theory/arith/nl/poly_conversion.h
  src/theory/arith/nl/strategy.cpp
  src/theory/arith/nl/strategy.h
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  test/regress/regress0/nl/issue5726-downpolys.smt2
  test/regress/regress0/nl/issue5726-sqfactor.smt2
  test/unit/api/cpp/theory_arith_nl_black.cpp
  test/unit/theory/CMakeLists.txt
  test/unit/theory/theory_arith_coverings_white.cpp
Labels: minor, moderate, work in progress

#8197 Remove unused data members from `TheoryArrays`
  src/theory/arrays/theory_arrays.cpp
  src/theory/arrays/theory_arrays.h
Labels: minor, simple

#8152 Fix lambda lifting + proofs
  src/theory/uf/lambda_lift.cpp
Labels: minor, simple

#8196 [BV] Fix rewriter policy for `bvneg`
  src/theory/bv/theory_bv_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/bv/issue8159-1-rewrite-bvneg.smt2
Labels: normal, simple

#8191 Disable regression
  test/regress/CMakeLists.txt
Labels: major, simple

#8185 Do not use sygus evaluation functions in sygus-inst
  src/theory/quantifiers/sygus_inst.cpp
Labels: normal, simple

#8198 Fix issue involving dropped purification lemmas for transcendental functions
  src/theory/arith/nl/transcendental/exponential_solver.cpp
  src/theory/arith/nl/transcendental/exponential_solver.h
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/arith/nl/transcendental/sine_solver.h
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  src/theory/arith/nl/transcendental/transcendental_state.h
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/nta/issue4693-4-inc-purify-sat.smt2
  test/regress/regress0/nl/nta/issue4693-5-inc-purify.smt2
  test/regress/regress0/nl/nta/issue4693-inc-purify.smt2
Labels: normal, moderate

#8192 Add standard theories to documentation
  docs/theories/theories.rst
Labels: minor, moderate

#8200 Prune spurious roots in lazard evaluation of coverings solver
  src/base/configuration.cpp
  src/base/configuration.h
  src/base/configuration_private.h
  src/options/options_handler.cpp
  src/theory/arith/nl/coverings/lazard_evaluation.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/lazard-spurious-root.smt2
Labels: normal, moderate

#8141 Add utility to access how to print floating point
  src/util/floatingpoint.cpp
  src/util/floatingpoint.h
Labels: minor, simple

#8195 Refactor rewriting of arithmetic division
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_rewriter.h
Labels: minor, moderate

#8199 Move libpoly <-> CoCoA conversion to new utility
  src/CMakeLists.txt
  src/theory/arith/nl/coverings/cocoa_converter.cpp
  src/theory/arith/nl/coverings/cocoa_converter.h
  src/theory/arith/nl/coverings/lazard_evaluation.cpp
Labels: minor, moderate

#8203 Improve error message when not using strings-exp
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/theory/strings/term_registry.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/seq/issue6005-no-strings-exp.smt2
Labels: minor, simple

#8204 Fix incorrect assertion in prop engine proofs
  src/prop/prop_engine.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/proofs/proj-issue462-sat-proof-option.smt2
Labels: minor, simple

#8173 Eliminate CDHashMap::insertAtContextLevelZero
  src/context/cdhashmap.h
  src/context/cdhashset.h
  src/context/cdinsert_hashmap.h
  src/expr/symbol_manager.cpp
  src/expr/symbol_table.cpp
  src/expr/symbol_table.h
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/tptp/tptp.cpp
  src/parser/tptp/tptp.h
  test/unit/context/cdhashmap_black.cpp
Labels: minor, moderate

#8201 Always purify universe from set minus
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/sets/cardinality_extension.cpp
  src/theory/sets/cardinality_extension.h
  src/theory/sets/term_registry.cpp
  src/theory/sets/theory_sets_private.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/sets/issue5400-2-card-minus-univ.smt2
  test/regress/regress0/sets/issue5400-card-minus-univ.smt2
  test/regress/regress0/sets/issue5402-1-card.smt2
Labels: normal, moderate

#8206 Fix models involving cardinality of sets of finite type
  src/theory/sets/cardinality_extension.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/sets/issue5402-2-card-finite.smt2
Labels: normal, simple

#8211 Fix issue with dropping non-reduced sine terms
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/nta/issue8208-red-nred.smt2
Labels: normal, simple

#8214 Fix rewriting of mixed-integer atoms
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/rewriter/addition.cpp
  src/theory/arith/rewriter/addition.h
  src/theory/arith/rewriter/node_utils.cpp
  src/theory/arith/rewriter/node_utils.h
  src/theory/arith/rewriter/rewrite_atom.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/arith/issue8159-rewrite-intreal.smt2
Labels: major, moderate

#8131 Integrate pythonic api
  cmake/FindCVC5PythonicAPI.cmake
  docs/api/python/CMakeLists.txt
  docs/api/python/pythonic/arith.rst
  docs/api/python/pythonic/array.rst
  docs/api/python/pythonic/bitvec.rst
  docs/api/python/pythonic/boolean.rst
  docs/api/python/pythonic/dt.rst
  docs/api/python/pythonic/fp.rst
  docs/api/python/pythonic/internals.rst
  docs/api/python/pythonic/quant.rst
  docs/api/python/pythonic/set.rst
  docs/api/python/pythonic/solver.rst
  docs/conf.py.in
  src/api/python/CMakeLists.txt
Labels: major, moderate

#8207 Improve error for higher-order logic
  src/theory/uf/theory_uf.cpp
Labels: minor, simple

#8213 Add regression for fixed issue
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/issue5815-ndet-string-ent.smt2
Labels: minor, simple

#8212 Throw logic exception if a transcendental function is encountered when nl-ext is not full
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/nta/proj-issue376.smt2
Labels: minor, simple

#7754 Alethe: Removed Steps that are Double-Printed
  src/proof/alethe/alethe_printer.cpp
  src/proof/alethe/alethe_printer.h
Labels: normal, moderate

#8220 Generalize LFSC string signature to sequences
  proofs/lfsc/signatures/strings_programs.plf
  proofs/lfsc/signatures/strings_rules.plf
  src/proof/lfsc/lfsc_printer.cpp
Labels: normal, moderate

#8087 Build python wheels in our CI
  .github/actions/install-dependencies/action.yml
  .github/actions/package-python-wheel-macos/action.yml
  .github/actions/package-python-wheel/action.yml
  .github/workflows/package_pypi.yml
  contrib/packaging_python/Readme.md
  docs/conf.py.in
Labels: normal, moderate

#8099 Add support for get learned literals in the API
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/api/Solver.java
  src/api/java/jni/solver.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/options/smt_options.toml
  src/parser/smt2/Smt2.g
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
  src/prop/zero_level_learner.cpp
  src/prop/zero_level_learner.h
  src/smt/command.cpp
  src/smt/command.h
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  test/regress/CMakeLists.txt
  test/regress/regress1/get-learned-literals.smt2
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
Labels: normal, moderate

#8228 Add regressions for fixed projects issues
  test/regress/CMakeLists.txt
  test/regress/regress0/sets/proj-issue177.smt2
  test/regress/regress1/arith/proj-issue158.smt2
  test/regress/regress1/ho/proj-issue139-2.smt2
  test/regress/regress1/nl/proj-issue231.smt2
  test/regress/regress1/nl/proj-issue232.smt2
  test/regress/regress1/nl/proj-issue251.smt2
  test/regress/regress1/nl/proj-issue253.smt2
  test/regress/regress1/nl/proj-issue280.smt2
  test/regress/regress1/nl/proj-issue282.smt2
  test/regress/regress1/nl/proj-issue286.smt2
  test/regress/regress1/nl/proj-issue290.smt2
  test/regress/regress1/push-pop/proj-issue161.smt2
  test/regress/regress1/quantifiers/proj-issue151-2.smt2
  test/regress/regress1/quantifiers/proj-issue155.smt2
  test/regress/regress1/quantifiers/proj-issue285.smt2
  test/regress/regress1/quantifiers/proj-issue295.smt2
  test/regress/regress1/strings/proj-issue281.smt2
  test/regress/regress1/sygus/issue4425-sets-sygus-infer.smt2
  test/regress/regress1/sygus/proj-issue135.smt2
  test/regress/regress1/sygus/proj-issue165.smt2
  test/regress/regress1/sygus/proj-issue264.smt2
  test/regress/regress2/sygus/proj-issue119.sy
Labels: minor, simple

#8223 Only build wheels nightly and for releases
  .github/workflows/package_pypi.yml
Labels: major, simple

#8225 Logic exception when using solution filtering for non-Boolean grammars
  src/theory/quantifiers/solution_filter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/sygus/proj-issue464-rr-option.smt2
Labels: minor, simple

#8221 Fix rewrite rule synthesis for 0-ary operators
  src/options/quantifiers_options.toml
  src/preprocessing/passes/synth_rew_rules.cpp
  src/smt/set_defaults.cpp
  src/theory/quantifiers/sygus/type_info.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/rr-verify/bv-term-32.sy
  test/regress/regress1/sygus/issue8216-rr-input-re.smt2
  test/unit/api/cpp/solver_black.cpp
Labels: minor, simple

#8234 Guard recursion into terms during substitution in arithmetic utility
  src/theory/arith/nl/equality_substitution.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/issue8161-var-elim.smt2
Labels: normal, moderate

#8231 Remove spurious assertion in linear solver
  src/theory/arith/rewriter/rewrite_atom.cpp
  src/theory/arith/theory_arith_private.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/arith/projissue469-int-equality.smt2
Labels: normal, moderate

#8235 Add unit test for fixed issue
  test/unit/api/cpp/theory_arith_nl_black.cpp
Labels: normal, moderate

#8233 Enable NL tangent planes by default
  src/options/arith_options.toml
  test/regress/CMakeLists.txt
  test/regress/regress0/proofs/proj-issue326-nl-bounds-check.smt2
  test/regress/regress1/nl/proj-issue215.smt2
  test/regress/regress1/nl/proj-issue279.smt2
  test/regress/regress1/nl/proj-issue291.smt2
  test/regress/regress1/nl/proj-issue292.smt2
  test/regress/regress1/nl/proj-issue294.smt2
  test/regress/regress1/nl/proj-issue297.smt2
  test/regress/regress1/nl/proj-issue302.smt2
Labels: normal, simple

#8237 Add regressions for fixed issue
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/issue4334-sat-proof-min.smt2
  test/regress/regress1/nl/issue4334-sat-proof.smt2
Labels: normal, simple

#8238 [Docs] Add missing requirement
  docs/CMakeLists.txt
Labels: minor, simple

#8229 Unit tests for fixed projects issues
  test/unit/api/cpp/CMakeLists.txt
  test/unit/api/cpp/theory_arith_nl_black.cpp
  test/unit/api/cpp/theory_uf_ho_black.cpp
Labels: minor, simple

#8217 Disallow models with `--arrays-weak-equiv`
  src/smt/set_defaults.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/arrays/issue8103-1-weak-equiv-models.smt2
Labels: normal, simple

#8230 Try harder to show that a RAN is rational
  src/expr/node_manager_template.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/issue8226-ran-refinement.smt2
Labels: normal, moderate

#8245 Proper error message for non-first-class sets
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
Labels: minor, simple

#8019 Fix docs warnings
  docs/api/cpp/Doxyfile.in
  docs/api/java/CMakeLists.txt
  src/api/cpp/cvc5.h
  src/api/cpp/cvc5_kind.h
  src/api/python/cvc5.pxi
  src/api/python/genkinds.py.in
Labels: minor, moderate

#8239 Update documentation of `Solver::getUnsatCore()`
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/api/Solver.java
  src/api/python/cvc5.pxi
  test/unit/api/cpp/solver_black.cpp
Labels: normal, simple

#8256 Don't run the pypi packaging job on forks
  .github/workflows/package_pypi.yml
Labels: normal, moderate

#8258 Rerun failed tests in CI
  .github/actions/run-tests/action.yml
Labels: normal, moderate

#8254 Script to list not covered API functions
  cmake/CodeCoverage.cmake
  contrib/uncovered-api-functions.py
Labels: normal, moderate

#8253 Add unit for fixed project issue
  test/api/cpp/CMakeLists.txt
  test/api/cpp/proj-issue377.cpp
Labels: minor, simple

#8244 Eliminate shadowing in the quantifiers rewriter
  src/preprocessing/passes/non_clausal_simp.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
  test/regress/CMakeLists.txt
  test/regress/regress0/quantifiers/issue8227-subs-shadow.smt2
Labels: major, moderate

#8205 Fixes and additions to LFSC signature
  proofs/lfsc/signatures/theory_def.plf
  src/proof/lfsc/lfsc_node_converter.cpp
  src/proof/lfsc/lfsc_node_converter.h
Labels: normal, moderate

#8261 Make one CI job not use libpoly
  .github/workflows/ci.yml
  test/regress/regress0/nl/issue8226-ran-refinement.smt2
Labels: normal, moderate

#8255 Guard another case of non-termination in quantifiers rewriting
  src/theory/quantifiers/quantifiers_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/quantifiers/proj-issue152-2-non-std-nterm-ext-rew.smt2
Labels: normal, simple

#8259 [API/Python] Add support for `Solver::getProof()`
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  test/unit/api/python/test_solver.py
Labels: normal, moderate

#8174 Do not expand APPLY_SELECTOR
  src/expr/dtype_cons.cpp
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/datatypes_rewriter.h
  src/theory/datatypes/infer_proof_cons.cpp
  src/theory/datatypes/proof_checker.cpp
  src/theory/datatypes/sygus_extension.cpp
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes_utils.cpp
  src/theory/datatypes/tuple_utils.cpp
  src/theory/quantifiers/cegqi/ceg_dt_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/ematching/candidate_generator.cpp
  src/theory/quantifiers/ematching/inst_match_generator.cpp
  src/theory/quantifiers/ematching/trigger_term_info.cpp
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/skolemize.cpp
  src/theory/quantifiers/sygus/sygus_eval_unfold.cpp
  src/theory/quantifiers/sygus/sygus_explain.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/term_database.cpp
  src/theory/theory_model.cpp
  src/theory/theory_model_builder.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/datatypes/data-nested-codata.smt2
  test/regress/regress0/datatypes/parametric-alt-list.cvc.smt2
  test/regress/regress0/quantifiers/pure_dt_cbqi.smt2
  test/regress/regress1/cee-bug0909-dd-scope.smt2
  test/regress/regress1/datatypes/non-simple-rec-param.smt2
  test/regress/regress1/fmf/cons-sets-bounds.smt2
  test/regress/regress1/fmf/jasmin-cdt-crash.smt2
  test/regress/regress1/fmf/loopy_coda.smt2
  test/regress/regress1/fmf/lst-no-self-rev-exp.smt2
  test/regress/regress1/fmf/nun-0208-to.smt2
  test/regress/regress1/strings/issue1105.smt2
  test/regress/regress2/quantifiers/net-policy-no-time.smt2
  test/unit/api/cpp/solver_black.cpp
Labels: normal, moderate

#8252 Produce intermediate json output for coverage
  cmake/CodeCoverage.cmake
Labels: normal, moderate

#8266 Eliminate the APPLY_SELECTOR_TOTAL kind
  src/api/cpp/cvc5.cpp
  src/printer/smt2/smt2_printer.cpp
  src/proof/lfsc/lfsc_node_converter.cpp
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/kinds
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes_type_rules.cpp
Labels: minor, simple

#8265 Add regression for fixed issue 6700
  test/regress/CMakeLists.txt
  test/regress/regress0/arrays/issue6700-inc-check-model.smt2
Labels: minor, simple

#8264 Add REGEXP_ALL kind to API
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_kind.h
  src/printer/smt2/smt2_printer.cpp
  src/theory/strings/kinds
  src/theory/strings/rewrites.cpp
  src/theory/strings/rewrites.h
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/sequences_rewriter.h
  src/theory/strings/theory_strings_utils.cpp
Labels: normal, simple

#8250 Use expression mining independent of whether sygus stream is enabled
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
Labels: normal, moderate

#8251 Change interface for printing instantiations in the API
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/api/Solver.java
  src/api/java/jni/solver.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/smt/command.cpp
Labels: normal, simple

#8236 Clear obsolete pending lemmas in arithmetic
  src/theory/arith/theory_arith.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/proj-issue-465-asan-proofs.smt2
  test/regress/regress0/use_approx/specsharp-WindowsCard.15.RTE.Terminate_System.Int32_approx.smt2
  test/regress/regress1/nl/arrowsmith-050317.smt2
  test/unit/api/cpp/theory_arith_nl_black.cpp
Labels: normal, moderate

#8262 Rename expert statistics to internal, add documentation
  docs/api/cpp/statistics.rst
  docs/binary/binary.rst
  docs/binary/statistics.rst
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/api/Stat.java
  src/api/java/io/github/cvc5/api/Statistics.java
  src/api/java/jni/stat.cpp
  src/decision/justify_stats.cpp
  src/main/command_executor.cpp
  src/options/base_options.toml
  src/options/options_handler.cpp
  src/prop/cadical.cpp
  src/util/statistics_public.h
  src/util/statistics_registry.cpp
  src/util/statistics_registry.h
  src/util/statistics_value.h
  test/regress/regress0/options/statistics.smt2
Labels: normal, moderate

#8268 Fix regression errors for arm64 nightlies.
  test/regress/regress0/bug548a.smt2
  test/regress/run_regression.py
Labels: normal, simple

#8273 Disable timing out regressions
  test/regress/CMakeLists.txt
  test/regress/regress1/sygus/max-limit.sy
  test/regress/regress1/sygus/max-try2.sy
Labels: major, simple

#8270 Add output -o pre-asserts
  src/options/base_options.toml
  src/smt/process_assertions.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/printer/pre-asserts-output.smt2
Labels: minor, simple

#8278 Fix cvc5-projects issue 475
  src/theory/bags/inference_generator.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/bags/murxla4.smt2
Labels: normal, simple

#8280 Remove unecessary datatype options
  src/options/datatypes_options.toml
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
  test/regress/regress0/quantifiers/cbqi-lia-dt-simp.smt2
  test/regress/regress1/fmf/lst-no-self-rev-exp.smt2
Labels: minor, simple

#8279 Fix theoryOf call in get equality status
  src/theory/shared_solver_distributed.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/proj-issue476-theoryOf-no-uf.smt2
Labels: normal, simple

#8282 Fix issue with subtyping from set membership in models
  src/theory/sets/theory_sets_private.cpp
Labels: normal, simple

#8287 Refactor kinds parser
  src/api/java/CMakeLists.txt
  src/api/java/genkinds.py.in
  src/api/parsekinds.py
  src/api/python/genkinds.py.in
Labels: normal, moderate

#8272 [CI] Make building static/shared configurable
  .github/actions/configure-and-build/action.yml
  .github/workflows/ci.yml
Labels: normal, simple

#8289 Fix reduction for arc trig functions
  src/theory/arith/operator_elim.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/nta/proj-issue483-arccos-oob.smt2
  test/regress/regress1/nl/sugar-ident.smt2
Labels: normal, simple

#8284 Consider APPLY_CONSTRUCTOR applied to values to be a value
  src/theory/theory_model.cpp
  src/theory/theory_model_builder.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/datatypes/proj-issue474-app-cons-value.smt2
Labels: normal, simple

#8281 Remove unecessary CEGQI options
  src/options/quantifiers_options.toml
  src/smt/set_defaults.cpp
  src/theory/quantifiers/cegqi/ceg_arith_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
Labels: minor, simple

#8193 Add first step for proofs documentation
  docs/api/cpp/CMakeLists.txt
  docs/index.rst
  docs/proofs/output_alethe.rst
  docs/proofs/output_lean.rst
  docs/proofs/output_lsfc.rst
  docs/proofs/proof_rules.rst
  docs/proofs/proofs.rst
Labels: normal, moderate

#8277 Guard parametric datatypes instantiated by non-first-class sorts
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_checks.h
Labels: minor, simple

#8246 Fix maximum value for pedantic proof level
  src/options/proof_options.toml
  src/smt/proof_manager.cpp
Labels: minor, simple

#8263 Update abduction and interpolation API to not use pass/return by reference
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/api/Solver.java
  src/api/java/jni/solver.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/smt/command.cpp
  src/smt/command.h
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
Labels: normal, moderate

#8275 Remove old decision justification heurstic
  src/CMakeLists.txt
  src/decision/decision_attributes.h
  src/decision/decision_engine.cpp
  src/decision/decision_engine_old.cpp
  src/decision/decision_engine_old.h
  src/decision/decision_strategy.h
  src/decision/justification_heuristic.cpp
  src/decision/justification_heuristic.h
  src/options/decision_options.toml
  src/options/decision_weight.h
  src/prop/prop_engine.cpp
  test/regress/regress1/ho/bug_freevar_PHI004^4-delta.smt2
Labels: minor, simple

#8283 api: Make checks header private.
  src/api/cpp/cvc5_checks.h
Labels: normal, simple

#8267 [API/Python] Add support for `Solver::getModel()`
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  test/unit/api/python/test_solver.py
Labels: normal, moderate

#8292 Always ensure literal when requiring phase via inference manager
  src/theory/quantifiers_engine.cpp
  src/theory/theory_inference_manager.cpp
  test/api/cpp/CMakeLists.txt
  test/api/cpp/proj-issue484.cpp
Labels: normal, simple

#8248 Document type rules
  src/theory/datatypes/theory_datatypes_type_rules.h
  src/theory/quantifiers/theory_quantifiers_type_rules.h
  src/theory/sep/theory_sep_type_rules.h
  src/theory/uf/theory_uf_type_rules.cpp
  src/theory/uf/theory_uf_type_rules.h
Labels: minor, simple

#8224 Improvements for sygus query generation
  src/CMakeLists.txt
  src/options/quantifiers_options.toml
  src/theory/quantifiers/expr_miner.cpp
  src/theory/quantifiers/expr_miner_manager.cpp
  src/theory/quantifiers/expr_miner_manager.h
  src/theory/quantifiers/query_generator.cpp
  src/theory/quantifiers/query_generator.h
  src/theory/quantifiers/query_generator_sample_sat.cpp
  src/theory/quantifiers/query_generator_sample_sat.h
  src/theory/quantifiers/query_generator_unsat.cpp
  src/theory/quantifiers/query_generator_unsat.h
Labels: minor, moderate

#8286 Add algorithm for finding pairs of paths in a node trie
  src/expr/CMakeLists.txt
  src/expr/node_trie.cpp
  src/expr/node_trie.h
  src/expr/node_trie_algorithm.cpp
  src/expr/node_trie_algorithm.h
Labels: normal, moderate

#8290 Introduce new splitting inference in sets + cardinality
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/sets/cardinality_extension.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/sets/proj-issue486-sets-split-eq.smt2
Labels: normal, moderate

#8293 Minor sync from proof-new
  proofs/lfsc/signatures/boolean_rules.plf
Labels: normal, simple

#8291 Run preprocess rewrite on equalities until fixed point
  src/preprocessing/passes/theory_rewrite_eq.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/quad-138-4-2-unsat.smt2
Labels: normal, simple

#8299 Add rewrite for allchar beneath union + star
  src/theory/strings/rewrites.cpp
  src/theory/strings/rewrites.h
  src/theory/strings/sequences_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/strings/issue8295-star-union-char.smt2
Labels: normal, simple

#8301 Fixes for skolem definition management
  src/decision/justification_strategy.cpp
  src/prop/prop_engine.cpp
  src/prop/skolem_def_manager.cpp
  src/prop/skolem_def_manager.h
  test/regress/CMakeLists.txt
  test/regress/regress0/decision/issue8296-sk-def-before-assert.smt2
Labels: major, moderate

#8285 Rename TO_FP operator kinds.
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/cpp/cvc5_kind.h
  src/api/java/io/github/cvc5/api/Solver.java
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/proof/lfsc/lfsc_node_converter.cpp
  src/theory/fp/fp_word_blaster.cpp
  src/theory/fp/kinds
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp_rewriter.cpp
  src/theory/fp/theory_fp_type_rules.cpp
  test/unit/api/cpp/op_black.cpp
  test/unit/api/java/OpTest.java
  test/unit/api/python/test_op.py
Labels: normal, simple

#8304 Simplify reductions for set and bag choose
  src/theory/bags/theory_bags.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/skolem_lemma.cpp
  src/theory/skolem_lemma.h
  test/regress/CMakeLists.txt
  test/regress/regress0/sets/proj-issue493-choose-det.smt2
Labels: minor, simple

#8305 Fix to consider leafs of theory sets to be variables
  src/theory/sets/solver_state.cpp
  test/regress/CMakeLists.txt
  test/regress/regress1/sets/proj-issue494-finite-leafof.smt2
Labels: normal, simple

#8307 Simplify `context::Scope`
  src/context/context.cpp
  src/context/context.h
Labels: minor, simple

#8310 Enable nl-cov-var-elim by default, but disable with proofs
  src/options/arith_options.toml
  src/smt/set_defaults.cpp
Labels: normal, moderate

#8247 Properly guard sort instantiate
  src/api/cpp/cvc5.cpp
  test/unit/api/cpp/CMakeLists.txt
  test/unit/api/cpp/parametric_datatype_black.cpp
Labels: minor, simple

#7995 Add skolem lemmas for bags card terms
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/theory/bags/bag_solver.cpp
  src/theory/bags/bags_rewriter.cpp
  src/theory/bags/bags_rewriter.h
  src/theory/bags/card_solver.cpp
  src/theory/bags/card_solver.h
  src/theory/bags/infer_info.cpp
  src/theory/bags/infer_info.h
  src/theory/bags/inference_generator.cpp
  src/theory/bags/inference_generator.h
  src/theory/bags/solver_state.cpp
  src/theory/bags/solver_state.h
  src/theory/bags/theory_bags.cpp
  src/theory/bags/theory_bags.h
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/theory_state.cpp
  src/theory/theory_state.h
  test/regress/CMakeLists.txt
  test/regress/regress1/bags/murxla5.smt2
  test/unit/theory/theory_bags_rewriter_white.cpp
Labels: normal, simple

#8300 Fix issues involving multiple sources of model substitutions in NL
  src/theory/arith/nl/coverings_solver.cpp
  src/theory/arith/nl/nl_model.cpp
  src/theory/arith/nl/nl_model.h
  src/theory/arith/nl/transcendental/sine_solver.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/nl/nta/issue8294-2-double-solve.smt2
Labels: normal, moderate

#8257 Add unit test involving seq concat term
  test/unit/api/cpp/solver_black.cpp
Labels: minor, simple

#8297 [BV] Fix strategy for rewriting `bvnot`
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
  src/theory/bv/theory_bv_rewriter.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/bv/issue8240-rewrite-bvnot.smt2
Labels: normal, moderate

#8312 api: Remove Sort::isFirstClass().
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/cpp/cvc5_checks.h
  src/api/java/io/github/cvc5/api/Sort.java
  src/api/java/jni/sort.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  test/unit/api/cpp/sort_black.cpp
  test/unit/api/java/SortTest.java
  test/unit/api/python/test_sort.py
Labels: normal, simple

#8308 Make learned literal computation more robust
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
  src/prop/zero_level_learner.cpp
  src/prop/zero_level_learner.h
  src/smt/smt_solver.cpp
  test/regress/regress0/printer/learned-lit-output.smt2
Labels: normal, moderate

#8318 Ignore `CMAKE_SYSROOT` when cross-compiling
  cmake/Toolchain-aarch64.cmake
  cmake/Toolchain-mingw64.cmake
Labels: normal, simple

#8302 Ensure trusted steps are given for skolem lemmas when proofs are enabled
  src/preprocessing/passes/theory_rewrite_eq.cpp
  src/proof/proof_rule.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/theory_preprocessor.cpp
  test/regress/CMakeLists.txt
  test/regress/regress0/proofs/proj-issue492-skolem-lemma-pf.smt2
Labels: normal, moderate

#8306 Fix shared library Windows builds with LibPoly
  cmake/FindPoly.cmake
Labels: normal, moderate

#8315 api: Make mkDatatypeDecl argument const&.
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/python/cvc5.pxd
Labels: normal, simple

#8320 api: Print the correct string for external kinds.
  src/api/cpp/cvc5.cpp
Labels: major, simple

#8317 Add regression for cvc5-projects issue 490
  test/regress/CMakeLists.txt
  test/regress/regress1/bags/murxla6.smt2
Labels: normal, simple

#8322 unit: Add test for api::Kind.
  test/unit/api/cpp/CMakeLists.txt
  test/unit/api/cpp/api_kind_black.cpp
Labels: normal, simple

#8311 Use native cancellation mechanism
  .github/workflows/cancel.yml
  .github/workflows/ci.yml
Labels: normal, moderate

#8321 [CI] Build and release Win64 binaries
  .github/actions/add-to-release/action.yml
  .github/actions/install-dependencies/action.yml
  .github/workflows/ci.yml
  CMakeLists.txt
  src/base/output.h
Labels: normal, moderate

#8325 Remove unused files in `regress0`
  test/regress/cli/regress0/bv/temp.lrat
  test/regress/cli/regress0/uf/mkpidgeon
Labels: minor, simple

#7578 Add unit test and assertion to test and catch cvc5-projects/issues/#337.
  src/api/cpp/cvc5.cpp
  test/unit/api/cpp/solver_black.cpp
Labels: normal, simple

#8327 [CI] Strip stored binaries
  .github/actions/configure-and-build/action.yml
  .github/workflows/ci.yml
Labels: normal, simple

#8323 Don't use apts gtest in CI
  .github/actions/install-dependencies/action.yml
Labels: minor, moderate

#8330 api: Fix documentation for UNINTERPRETED_SORT_VALUE kind.
  src/api/cpp/cvc5_kind.h
Labels: normal, simple

#8329 api: Fix documentation for *TO_FP* kinds.
  src/api/cpp/cvc5_kind.h
Labels: normal, simple

#8298 Update care graph computations to use standard node trie algorithm
  src/CMakeLists.txt
  src/theory/care_pair_argument_callback.cpp
  src/theory/care_pair_argument_callback.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  src/theory/theory.cpp
  src/theory/theory.h
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf.h
Labels: normal, moderate

#8328 ctest: Fix labels for python unit tests.
  test/unit/api/python/CMakeLists.txt
Labels: normal, simple

#8333 [Parser] Simplify `Smt2::addIndexedOperator()`
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
Labels: normal, simple

#8343 Add `getStatistics()` to python API
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  test/unit/api/python/test_solver.py
Labels: normal, moderate

#8353 Fix LFSC conversion for seq unit
  src/proof/lfsc/lfsc_node_converter.cpp
Labels: normal, simple

#8288 Refactor documentation
  docs/binary/binary.rst
  docs/binary/languages.rst
  docs/binary/options.rst
  docs/conf.py.in
  docs/ext/run_command.py
  docs/index.rst
  docs/options.rst
  docs/output-tags.rst
  docs/resource-limits.rst
  docs/statistics.rst
  src/options/base_options.toml
  src/options/main_options.toml
  src/options/mkoptions.py
  src/options/parser_options.toml
  src/options/quantifiers_options.toml
  src/options/smt_options.toml
Labels: normal, moderate

#8354 Fix return value for candidate rewrite database
  src/theory/quantifiers/candidate_rewrite_database.cpp
  src/theory/quantifiers/candidate_rewrite_database.h
Labels: normal, simple

#8355 Remove `Op::getIndices()`
  examples/api/python/extract.py
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/api/Op.java
  src/api/java/jni/op.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  test/unit/api/cpp/op_black.cpp
  test/unit/api/cpp/op_white.cpp
  test/unit/api/java/OpTest.java
Labels: normal, simple

#8356 [API] Support `Op::operator[]` in Java and Python
  src/api/java/io/github/cvc5/api/Op.java
  src/api/java/jni/op.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  test/unit/api/cpp/op_black.cpp
  test/unit/api/java/OpTest.java
  test/unit/api/python/test_op.py
Labels: normal, moderate

#8357 api: Unify mkTerm variants.
  examples/api/cpp/bitvectors.cpp
  examples/api/cpp/bitvectors_and_arrays.cpp
  examples/api/cpp/combination.cpp
  examples/api/cpp/datatypes.cpp
  examples/api/cpp/extract.cpp
  examples/api/cpp/floating_point_arith.cpp
  examples/api/cpp/linear_arith.cpp
  examples/api/cpp/quickstart.cpp
  examples/api/cpp/relations.cpp
  examples/api/cpp/sequences.cpp
  examples/api/cpp/sets.cpp
  examples/api/cpp/strings.cpp
  examples/api/cpp/sygus-fun.cpp
  examples/api/cpp/sygus-grammar.cpp
  examples/api/cpp/sygus-inv.cpp
  examples/api/cpp/transcendentals.cpp
  examples/simple_vc_cxx.cpp
  examples/simple_vc_quant_cxx.cpp
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/jni/solver.cpp
  src/parser/parser.cpp
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/tptp/Tptp.g
  src/parser/tptp/tptp.cpp
  src/smt/command.cpp
  test/api/cpp/issue4889.cpp
  test/api/cpp/issue5074.cpp
  test/api/cpp/issue6111.cpp
  test/api/cpp/proj-issue306.cpp
  test/api/cpp/proj-issue334.cpp
  test/api/cpp/reset_assertions.cpp
  test/api/cpp/sep_log_api.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/cpp/solver_white.cpp
  test/unit/api/cpp/term_black.cpp
  test/unit/api/cpp/term_white.cpp
  test/unit/api/cpp/theory_uf_ho_black.cpp
  test/unit/theory/theory_sets_type_rules_white.cpp
Labels: major, simple

#8313 Refactor result class
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/api/Result.java
  src/api/java/jni/result.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/main/command_executor.cpp
  src/omt/bitvector_optimizer.cpp
  src/omt/integer_optimizer.cpp
  src/prop/prop_engine.cpp
  src/smt/abduction_solver.cpp
  src/smt/assertions.cpp
  src/smt/command.cpp
  src/smt/interpolation_solver.cpp
  src/smt/optimization_solver.cpp
  src/smt/optimization_solver.h
  src/smt/quant_elim_solver.cpp
  src/smt/smt_mode.cpp
  src/smt/smt_solver.cpp
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  src/smt/solver_engine_state.cpp
  src/smt/sygus_solver.cpp
  src/theory/arith/attempt_solution_simplex.cpp
  src/theory/arith/attempt_solution_simplex.h
  src/theory/arith/dual_simplex.cpp
  src/theory/arith/dual_simplex.h
  src/theory/arith/fc_simplex.cpp
  src/theory/arith/fc_simplex.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/simplex.h
  src/theory/arith/soi_simplex.cpp
  src/theory/arith/soi_simplex.h
  src/theory/arith/theory_arith_private.cpp
  src/theory/arith/theory_arith_private.h
  src/theory/quantifiers/candidate_rewrite_database.cpp
  src/theory/quantifiers/query_generator.cpp
  src/theory/quantifiers/query_generator_sample_sat.cpp
  src/theory/quantifiers/query_generator_unsat.cpp
  src/theory/quantifiers/solution_filter.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/cegis_core_connective.cpp
  src/theory/quantifiers/sygus/sygus_interpol.cpp
  src/theory/quantifiers/sygus/sygus_repair_const.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_verify.cpp
  src/theory/smt_engine_subsolver.cpp
  src/util/result.cpp
  src/util/result.h
  test/unit/api/cpp/result_black.cpp
  test/unit/api/java/ResultTest.java
  test/unit/api/python/test_result.py
  test/unit/theory/theory_bv_opt_white.cpp
  test/unit/theory/theory_bv_white.cpp
  test/unit/theory/theory_int_opt_white.cpp
  test/unit/theory/theory_opt_multigoal_white.cpp
  test/unit/theory/theory_quantifiers_bv_inverter_white.cpp
Labels: major, moderate

#8334 [FP] Remove `FLOATINGPOINT_TO_FP_GENERIC` kind
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/cpp/cvc5_kind.h
  src/api/java/io/github/cvc5/api/Solver.java
  src/parser/parse_op.cpp
  src/parser/parse_op.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/printer/smt2/smt2_printer.cpp
  src/proof/lfsc/lfsc_node_converter.cpp
  src/theory/fp/kinds
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp_rewriter.cpp
  src/theory/fp/theory_fp_type_rules.cpp
  src/theory/fp/theory_fp_type_rules.h
  src/util/floatingpoint.h
  test/unit/api/cpp/op_black.cpp
  test/unit/api/java/OpTest.java
  test/unit/api/python/test_op.py
Labels: normal, moderate

#8359 Add a timeout option for verification of synthesized terms.
  src/options/quantifiers_options.toml
  src/theory/quantifiers/sygus/synth_verify.cpp
Labels: normal, simple

#8364 update sets-and-relations.rst
  docs/theories/sets-and-relations.rst
Labels: minor, simple

#7779 [proofs] Alethe: fixing formatting and adding missing comment
  src/proof/alethe/alethe_post_processor.cpp
Labels: minor, simple

#8360 Make uncovered-api-functions.py exit with 1 if something is not covered
  contrib/uncovered-api-functions.py
Labels: minor, simple

#8366 Updates for the theory reference for separation logic
  docs/references.bib
  docs/theories/separation-logic.rst
Labels: minor, moderate

#8303 Refactor proof rule documentation
  docs/api/cpp/CMakeLists.txt
  docs/conf.py.in
  src/proof/proof_rule.h
Labels: normal, moderate

#8362 Change null terminator for regular expression intersection
  proofs/lfsc/signatures/strings_rules.plf
  src/expr/nary_term_util.cpp
Labels: normal, simple

#8340 Fix non-termination issue in sygus enumerator
  src/theory/quantifiers/sygus/enum_value_manager.cpp
  src/theory/quantifiers/sygus/sygus_enumerator.cpp
  src/theory/quantifiers/sygus/sygus_enumerator.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/sygus/discPresent.sy
Labels: normal, moderate

#8331 Fix cvc5-projects issue 497
  src/theory/bags/card_solver.cpp
  src/theory/bags/card_solver.h
  src/theory/bags/infer_info.cpp
  src/theory/bags/infer_info.h
  src/theory/bags/inference_generator.cpp
  src/theory/bags/inference_generator.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/bags/proj-issue497.smt2
Labels: normal, simple

#8365 Initial documentation on LFSC
  docs/proofs/output_alethe.rst
  docs/proofs/output_lfsc.rst
  docs/proofs/output_lsfc.rst
  docs/proofs/proofs.rst
  docs/references.bib
Labels: normal, moderate

#8372 update SET_COMPREHENSION kind documentation
  src/api/cpp/cvc5_kind.h
Labels: minor

#8367 Update PRs without waiting on successful build
  .github/workflows/ci.yml
Labels: minor, moderate

#8337 Store latest builds in a special release
  .github/actions/add-to-release/action.yml
  .github/actions/store-binary/action.yml
  .github/workflows/ci.yml
Labels: normal, moderate

#8368 Run gen-versioninfo unconditionally
  cmake/version.cmake
Labels: normal, moderate

#8352 Add internal synth result class
  src/util/CMakeLists.txt
  src/util/result.h
  src/util/synth_result.cpp
  src/util/synth_result.h
Labels: major, simple

#8379 Only update latest tag if commit changed.
  .github/actions/store-binary/action.yml
Labels: normal, simple

#8363 Make IDOF_MAX rewrite only apply when all children are constant
  src/theory/strings/sequences_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/strings/issue8346-idof-max.smt2
Labels: normal, simple

#8375 Document proof rules for transcendentals
  src/proof/proof_rule.h
Labels: minor, moderate

#8342 Add `getOptionInfo()` and `getOptionNames()` to python API
  src/api/cpp/cvc5.h
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  test/unit/api/python/CMakeLists.txt
  test/unit/api/python/test_solver.py
Labels: normal, moderate

#8370 Add SynthResult to the API
  docs/api/cpp/cpp.rst
  docs/api/cpp/synthresult.rst
  docs/api/java/java.rst
  docs/api/python/base/python.rst
  docs/api/python/base/synthresult.rst
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/CMakeLists.txt
  src/api/java/io/github/cvc5/api/Solver.java
  src/api/java/io/github/cvc5/api/SynthResult.java
  src/api/java/jni/solver.cpp
  src/api/java/jni/synth_result.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  test/unit/api/cpp/CMakeLists.txt
  test/unit/api/cpp/synth_result_black.cpp
  test/unit/api/java/CMakeLists.txt
  test/unit/api/java/SynthResultTest.java
  test/unit/api/python/CMakeLists.txt
  test/unit/api/python/test_synth_result.py
Labels: major, moderate

#8341 Add API unit tests for statistics
  docs/statistics.rst
  examples/api/java/Statistics.java
  src/api/java/io/github/cvc5/api/Statistics.java
  src/api/java/jni/statistics.cpp
  src/options/mkoptions.py
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
Labels: normal, moderate

#8371 [unsat-cores] [sat-proof] Fix open proofs due to theory lemmas
  src/prop/proof_cnf_stream.cpp
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/proj-issue468-mkScope.smt2
Labels: normal, moderate
