Repository cvc5/cvc5, pull requests merged in 2022-04, with the labels that each got.

#8506 Fix pypi packaging trigger
  .github/workflows/package_pypi.yml
Labels: major, simple

#8495 api: Use std::optional for symbols in mk* functions.
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/jni/solver.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/parser/parser.cpp
  test/unit/api/cpp/datatype_api_black.cpp
  test/unit/api/cpp/parametric_datatype_black.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/cpp/sort_black.cpp
  test/unit/api/java/DatatypeTest.java
  test/unit/api/java/ResultTest.java
  test/unit/api/java/SolverTest.java
  test/unit/api/java/SortTest.java
  test/unit/api/python/test_datatype_api.py
  test/unit/api/python/test_solver.py
  test/unit/api/python/test_sort.py
Labels: major, simple

#8499 api: Swap arguments of declareSygusVar.
  examples/api/cpp/sygus-fun.cpp
  examples/api/cpp/sygus-grammar.cpp
  examples/api/java/SygusFun.java
  examples/api/java/SygusGrammar.java
  examples/api/python/sygus-fun.py
  examples/api/python/sygus-grammar.py
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/jni/solver.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/parser/smt2/Smt2.g
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
Labels: major, simple

#8500 Fix sygus-inst when combined with bounded string quantifiers
  src/theory/quantifiers/sygus_inst.cpp
  src/theory/quantifiers/sygus_inst.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/quantifiers/issue8497-syqi-str-fmf.smt2
Labels: normal, simple

#8503 [API] Remove redundant version of `mkFunctionSort`
  examples/api/cpp/combination.cpp
  examples/simple_vc_quant_cxx.cpp
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/jni/solver.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/parser/tptp/tptp.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/cpp/sort_black.cpp
  test/unit/api/cpp/term_black.cpp
  test/unit/api/cpp/term_white.cpp
  test/unit/parser/parser_black.cpp
Labels: normal, moderate

#8480 Python api: Various fixes in docs.
  docs/api/python/base/python.rst
  docs/api/python/base/statistics.rst
  src/api/python/cvc5.pxi
Labels: normal, moderate

#8509 docs: Add documentation for modes.
  docs/api/cpp/cpp.rst
  docs/api/cpp/modes.rst
  src/api/cpp/cvc5.h
  src/api/cpp/cvc5_types.h
Labels: major, simple

#8502 Fix javadoc custom tag warning
  docs/api/java/CMakeLists.txt
  src/api/java/io/github/cvc5/Datatype.java
  src/api/java/io/github/cvc5/DatatypeConstructor.java
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/io/github/cvc5/Sort.java
  src/api/java/io/github/cvc5/Term.java
Labels: minor, simple

#8521 [API] Add mode argument for `Solver::blockModel()`
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/CMakeLists.txt
  src/api/java/genenums.py.in
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/jni/solver.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/options/smt_options.toml
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/smt/command.cpp
  src/smt/command.h
  src/smt/model_blocker.cpp
  src/smt/model_blocker.h
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  test/regress/cli/regress1/model-blocker-simple.smt2
  test/regress/cli/regress1/model-blocker-values.smt2
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
Labels: normal, moderate

#8505 Remove decorator from python API
  examples/api/python/bitvectors.py
  examples/api/python/bitvectors_and_arrays.py
  examples/api/python/combination.py
  examples/api/python/datatypes.py
  examples/api/python/relations.py
  examples/api/python/sygus-grammar.py
  src/api/python/cvc5.pxi
  test/api/python/issue5074.py
  test/api/python/issue6111.py
  test/api/python/proj-issue306.py
  test/unit/api/python/test_datatype_api.py
  test/unit/api/python/test_solver.py
  test/unit/api/python/test_sort.py
  test/unit/api/python/test_term.py
Labels: normal, moderate

#8501 [proofs] [doc] Minor changes to general proofs page, some changes to Alethe page, added DOT page
  docs/proofs/output_alethe.rst
  docs/proofs/output_dot.rst
  docs/proofs/proofs.rst
  docs/references.bib
Labels: normal, simple

#8519 Internal simplifications to constructing datatypes
  src/api/cpp/cvc5.cpp
  src/expr/dtype.cpp
  src/expr/dtype.h
  src/expr/dtype_cons.cpp
  src/expr/dtype_cons.h
  src/expr/dtype_selector.cpp
  src/expr/node_manager_attributes.h
  src/expr/node_manager_template.cpp
  src/expr/node_manager_template.h
  src/expr/type_node.cpp
  src/expr/type_node.h
  src/parser/parser.cpp
  src/parser/parser.h
  src/preprocessing/passes/synth_rew_rules.cpp
  src/theory/datatypes/sygus_datatype_utils.cpp
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_grammar_norm.cpp
  test/unit/node/type_cardinality_black.cpp
  test/unit/util/datatype_black.cpp
Labels: major, moderate

#8525 [proofs] [alethe] Fix Alethe post-processor
  src/proof/alethe/alethe_post_processor.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/nomerge-alethe-pf.smt2
Labels: normal, simple

#8507 Python API: Do not rename enumerators.
  docs/api/python/base/quickstart.rst
  examples/api/python/bags.py
  examples/api/python/bitvectors.py
  examples/api/python/bitvectors_and_arrays.py
  examples/api/python/combination.py
  examples/api/python/datatypes.py
  examples/api/python/extract.py
  examples/api/python/floating_point.py
  examples/api/python/linear_arith.py
  examples/api/python/quickstart.py
  examples/api/python/relations.py
  examples/api/python/sequences.py
  examples/api/python/sets.py
  examples/api/python/strings.py
  examples/api/python/sygus-fun.py
  examples/api/python/sygus-grammar.py
  examples/api/python/sygus-inv.py
  examples/api/python/transcendentals.py
  examples/api/python/utils.py
  src/api/python/genenums.py.in
  test/api/python/issue4889.py
  test/api/python/issue5074.py
  test/api/python/issue6111.py
  test/api/python/proj-issue306.py
  test/api/python/reset_assertions.py
  test/api/python/sep_log_api.py
  test/unit/api/python/test_op.py
  test/unit/api/python/test_solver.py
  test/unit/api/python/test_term.py
  test/unit/api/python/test_to_python_obj.py
Labels: normal, simple

#8513 Document special member functions in python API
  docs/api/python/base/datatype.rst
  docs/api/python/base/datatypeconstructor.rst
  docs/api/python/base/op.rst
  docs/api/python/base/term.rst
  src/api/python/cvc5.pxi
Labels: normal, moderate

#8530 Change CI concurrency policy to not queue on main
  .github/workflows/ci.yml
Labels: normal, moderate

#8498 [proofs] [doc] Document string rules
  src/proof/proof_rule.h
Labels: normal, moderate

#8524 make-release: Clarify instructions for pushing commits and tag.
  contrib/make-release.py
Labels: normal, simple

#8526 Only run pypi packaging when release is published
  .github/workflows/package_pypi.yml
Labels: major, simple

#8529 api: Remove Datatype::getConstructorTerm().
  examples/api/cpp/datatypes.cpp
  examples/api/java/Datatypes.java
  examples/api/python/datatypes.py
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/cpp/cvc5_kind.h
  src/api/java/io/github/cvc5/Datatype.java
  src/api/java/jni/datatype.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/cpp/solver_white.cpp
  test/unit/api/cpp/term_black.cpp
  test/unit/api/cpp/term_white.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/java/TermTest.java
  test/unit/api/python/test_solver.py
  test/unit/api/python/test_term.py
Labels: normal, simple

#8510 api kinds: Refactor docs for kinds to properly render in Python.
  src/api/cpp/cvc5.h
  src/api/cpp/cvc5_kind.h
  src/api/python/genenums.py.in
Labels: normal, moderate

#8523 Prevent using the coverings solver with extended operators
  src/options/arith_options.toml
  src/smt/set_defaults.cpp
  src/theory/arith/nl/nonlinear_extension.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/nl/issue8515-cov-iand.smt2
  test/regress/cli/regress0/nl/issue8516-cov-sin.smt2
Labels: major, moderate

#8508 docs: Document UnknownExplanation.
  docs/api/cpp/cpp.rst
  docs/api/cpp/roundingmode.rst
  docs/api/cpp/unknownexplanation.rst
  docs/resource-limits.rst
  src/api/cpp/cvc5_types.h
Labels: major, simple

#8511 Simplifications to the datatypes API
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/DatatypeConstructorDecl.java
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/jni/datatype_constructor_decl.cpp
  src/api/java/jni/solver.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/parser/parser.cpp
  test/unit/api/cpp/datatype_api_black.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/DatatypeTest.java
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_datatype_api.py
  test/unit/api/python/test_solver.py
Labels: major, moderate

#8514 Simplify the python base API in a few places
  src/api/python/cvc5.pxi
  test/unit/api/python/test_solver.py
Labels: normal, moderate

#8493 Add more explanations in the API
  src/api/cpp/cvc5.h
Labels: normal, simple

#8533 Add a few miscellaneous pieces of documentation
  docs/api/python/pythonic/pythonic.rst
  docs/theories/datatypes.rst
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/Datatype.java
  src/api/java/io/github/cvc5/DatatypeConstructor.java
  src/api/java/io/github/cvc5/DatatypeConstructorDecl.java
  src/api/java/io/github/cvc5/DatatypeDecl.java
  src/api/java/io/github/cvc5/DatatypeSelector.java
  src/api/java/io/github/cvc5/Grammar.java
  src/api/java/io/github/cvc5/Op.java
  src/api/java/io/github/cvc5/Result.java
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/io/github/cvc5/Sort.java
  src/api/java/io/github/cvc5/SynthResult.java
  src/api/java/io/github/cvc5/Term.java
  src/api/python/cvc5.pxi
Labels: normal, simple

#8528 Require that used model values are constant in CEGQI
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/quantifiers/issue8520-cegqi-nl-cov.smt2
Labels: normal, simple

#8535 api: Remove DatatypeConstructor::getSelectorTerm().
  examples/api/cpp/datatypes.cpp
  examples/api/java/Datatypes.java
  examples/api/python/datatypes.py
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/cpp/cvc5_kind.h
  src/api/java/io/github/cvc5/DatatypeConstructor.java
  src/api/java/jni/datatype_constructor.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/cpp/solver_white.cpp
  test/unit/api/cpp/term_black.cpp
  test/unit/api/cpp/term_white.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
  test/unit/api/python/test_term.py
Labels: normal, simple

#8538 docs: Add Python installation instructions for pip.
  docs/api/python/python.rst
Labels: minor, simple

#8534 Ignore irrelevant exponential terms
  src/theory/arith/nl/transcendental/exponential_solver.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/quantifiers/issue8517-exp-exp.smt2
Labels: minor, simple

#8542 Always cancel already running CI runs on forks
  .github/workflows/ci.yml
Labels: minor, moderate

#8532 Follow renaming within pythonic API
  cmake/FindCVC5PythonicAPI.cmake
  docs/api/api.rst
  docs/api/cpp/quickstart.rst
  docs/api/java/quickstart.rst
  docs/api/python/base/quickstart.rst
  docs/binary/quickstart.rst
  docs/conf.py.in
  docs/examples/bitvectors.rst
  docs/examples/bitvectors_and_arrays.rst
  docs/examples/combination.rst
  docs/examples/datatypes.rst
  docs/examples/extract.rst
  docs/examples/floatingpoint.rst
  docs/examples/helloworld.rst
  docs/examples/lineararith.rst
  docs/examples/quickstart.rst
  docs/examples/sets.rst
  src/api/python/CMakeLists.txt
Labels: normal, simple

#8537 api: Rename get(Selector|Constructor)Term() to getTerm().
  docs/theories/datatypes.rst
  examples/api/cpp/datatypes.cpp
  examples/api/java/Datatypes.java
  examples/api/java/Statistics.java
  examples/api/python/datatypes.py
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/cpp/cvc5_kind.h
  src/api/java/io/github/cvc5/DatatypeConstructor.java
  src/api/java/io/github/cvc5/DatatypeSelector.java
  src/api/java/jni/datatype_constructor.cpp
  src/api/java/jni/datatype_selector.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/parser/parser.cpp
  src/parser/smt2/smt2.cpp
  test/unit/api/cpp/datatype_api_black.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/cpp/solver_white.cpp
  test/unit/api/cpp/sort_black.cpp
  test/unit/api/cpp/term_black.cpp
  test/unit/api/cpp/term_white.cpp
  test/unit/api/java/DatatypeTest.java
  test/unit/api/java/SolverTest.java
  test/unit/api/java/SortTest.java
  test/unit/api/java/TermTest.java
  test/unit/api/python/test_datatype_api.py
  test/unit/api/python/test_solver.py
  test/unit/api/python/test_sort.py
  test/unit/api/python/test_term.py
Labels: normal, simple

#8543 Remove variant of mkDatatypeDecl with one sort parameter
  examples/api/cpp/datatypes.cpp
  examples/api/java/Datatypes.java
  examples/api/python/datatypes.py
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/DatatypeDecl.java
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/jni/solver.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  test/unit/api/cpp/parametric_datatype_black.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/cpp/sort_black.cpp
  test/unit/api/cpp/term_black.cpp
  test/unit/api/cpp/term_white.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/java/SortTest.java
  test/unit/api/java/TermTest.java
  test/unit/api/python/test_solver.py
  test/unit/api/python/test_sort.py
  test/unit/api/python/test_term.py
Labels: normal, simple

#8544 Rename mkSygusGrammar to mkGrammar
  examples/api/cpp/sygus-fun.cpp
  examples/api/cpp/sygus-grammar.cpp
  examples/api/java/SygusFun.java
  examples/api/java/SygusGrammar.java
  examples/api/python/sygus-fun.py
  examples/api/python/sygus-grammar.py
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/jni/solver.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/parser/smt2/smt2.cpp
  test/unit/api/cpp/grammar_black.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/GrammarTest.java
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_grammar.py
  test/unit/api/python/test_solver.py
Labels: normal, simple

#8545 Speed up CI by using more cores
  .github/actions/install-dependencies/action.yml
Labels: minor, moderate

#8547 Fix for get-value with empty uninterpreted sort domain
  src/parser/parser.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/theory_model.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/cvc5-printing.cpp-sample.smt2
  test/regress/cli/regress0/models-print-2.smt2
  test/regress/cli/regress0/printer/empty_sort.smt2
Labels: major, simple

#8550 Use raw symbols in proofs
  src/expr/node_manager_template.cpp
  src/expr/node_manager_template.h
  src/printer/smt2/smt2_printer.cpp
  src/proof/lfsc/lfsc_node_converter.cpp
  src/proof/lfsc/lfsc_node_converter.h
  src/proof/lfsc/lfsc_printer.cpp
  src/proof/proof_node_to_sexpr.cpp
  src/theory/builtin/kinds
Labels: normal, simple

#8549 Rename getInstantiatedConstructorTerm to getInstantiatedTerm
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/DatatypeConstructor.java
  src/api/java/io/github/cvc5/DatatypeSelector.java
  src/api/java/jni/datatype_constructor.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/parser/parser.cpp
  src/parser/smt2/Smt2.g
  test/unit/api/cpp/datatype_api_black.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/DatatypeTest.java
  test/unit/api/python/test_datatype_api.py
Labels: normal, simple

#8551 Various improvements and fixes in the documentation
  INSTALL.rst
  docs/binary/binary.rst
  docs/proofs/output_alethe.rst
  docs/proofs/output_dot.rst
  docs/proofs/output_lean.rst
  docs/proofs/output_lfsc.rst
  docs/proofs/proofs.rst
  docs/references.bib
  docs/theories/datatypes.rst
  docs/theories/theories.rst
  src/api/cpp/cvc5.h
  src/api/cpp/cvc5_kind.h
  src/api/python/cvc5.pxi
Labels: major, moderate

#8554 api: Various fixes in Python documentation.
  docs/ext/smtliblexer.py
  src/api/python/cvc5.pxi
Labels: normal, simple

#8555 Maintain symlink to docs for latest release
  .github/workflows/docs_upload.yml
Labels: major, simple

#8556 python api: More fixes.
  src/api/python/cvc5.pxi
Labels: normal, simple

#8557 Fix links when converting kinds documentation to python
  src/api/python/genenums.py.in
Labels: normal, moderate

#8558 api: First batch of fixes in the api docs.
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/Sort.java
  src/api/python/cvc5.pxi
Labels: normal, moderate

#8559 api: More fixes in docs.
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/Sort.java
  src/api/python/cvc5.pxi
Labels: normal, simple

#8560 Docs: remove api from package name in java.rst
  docs/api/java/java.rst
Labels: major, simple

#8561 api: Fixes in docs for DatatypeConstructor.
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/DatatypeConstructor.java
  src/api/python/cvc5.pxi
Labels: normal, simple

#8562 api: Fixes in java api docs.
  src/api/java/io/github/cvc5/Datatype.java
  src/api/java/io/github/cvc5/DatatypeConstructorDecl.java
  src/api/java/io/github/cvc5/DatatypeDecl.java
  src/api/java/io/github/cvc5/DatatypeSelector.java
  src/api/java/io/github/cvc5/Solver.java
Labels: normal, simple

#8563 api: Fixes for Grammar docs in java API.
  src/api/java/io/github/cvc5/Grammar.java
Labels: normal, simple

#8565 api: Fixes in docs for Op.
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/Op.java
Labels: normal, simple

#8569 api: Fix OptionInfo docs for java API.
  src/api/java/io/github/cvc5/OptionInfo.java
Labels: normal, simple

#8567 docs: Fix mkTerm calls in theory documentation.
  docs/theories/bags.rst
  docs/theories/separation-logic.rst
  docs/theories/sequences.rst
  docs/theories/sets-and-relations.rst
Labels: major

#8570 api: More fixes in C++ API docs.
  docs/api/cpp/term.rst
  src/api/cpp/cvc5.h
  src/api/cpp/cvc5_types.h
Labels: normal, simple

#8568 Be permissive for subtyping in function definitions
  src/api/cpp/cvc5.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/real-numerals.smt2
Labels: major, simple

#8571 api: More fixes in the java API.
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/Op.java
  src/api/java/io/github/cvc5/OptionInfo.java
  src/api/java/io/github/cvc5/Result.java
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/io/github/cvc5/Sort.java
  src/api/java/io/github/cvc5/Stat.java
  src/api/java/io/github/cvc5/Statistics.java
  src/api/java/io/github/cvc5/SynthResult.java
  src/api/java/io/github/cvc5/Term.java
Labels: normal, simple

#8564 Make rewriter more robust against RAN becoming rational
  src/theory/arith/rewriter/node_utils.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arith/arith-rewrite-with-ran.smt2
Labels: major, moderate

#8460 Update NEWS for cvc5 1.0.
  NEWS
  NEWS.md
Labels: major

#8576 api: Fix doc generation for kinds in java API.
  src/api/cpp/cvc5_kind.h
  src/api/java/genenums.py.in
  src/api/java/io/github/cvc5/Solver.java
  src/api/python/cvc5.pxi
  src/options/mkoptions.py
  src/proof/proof_rule.h
Labels: normal, simple, do not merge

#8579 Fixes for LFSC printing and signatures
  proofs/lfsc/signatures/theory_def.plf
  src/proof/lfsc/lfsc_node_converter.cpp
  src/proof/lfsc/lfsc_printer.cpp
Labels: normal, simple

#8578 Fix proof checker for SUBS
  src/theory/builtin/proof_checker.cpp
Labels: normal, simple

#8577 Minor fix for printing nullary operators in smt2
  src/printer/smt2/smt2_printer.cpp
  src/smt/listeners.h
Labels: minor, simple

#8583 Add method to get leaves of a NodeTrie
  src/expr/node_trie.cpp
  src/expr/node_trie.h
Labels: minor, simple

#8586 Generalization for sygus verify utility
  src/theory/quantifiers/sygus/synth_verify.cpp
  src/theory/quantifiers/sygus/synth_verify.h
  src/theory/smt_engine_subsolver.cpp
Labels: normal, moderate

#8591 Properly parse numerals as real when integers are disabled
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
Labels: minor, simple

#8590 Eliminate more uses of CONST_RATIONAL
  src/theory/arith/arith_ite_utils.cpp
  src/theory/arith/arith_utilities.cpp
  src/theory/arith/arith_utilities.h
  src/theory/arith/nl/ext_theory_callback.cpp
  src/theory/arith/nl/ext_theory_callback.h
  src/theory/arith/nl/nl_model.cpp
  src/theory/arith/type_enumerator.h
  src/theory/bags/bags_utils.cpp
  src/theory/bags/theory_bags.cpp
  src/theory/strings/theory_strings.cpp
Labels: minor, simple

#8587 Do not parse inlined unresolved sorts in smt2 parser
  src/parser/smt2/Smt2.g
Labels: minor, simple

#8588 Minor refactoring of smt2 printer
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
Labels: minor, simple

#8592 Simplify parser
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
Labels: normal, simple

#8582 Add learned literal type and prop learned database
  src/CMakeLists.txt
  src/api/cpp/cvc5_types.cpp
  src/api/cpp/cvc5_types.h
  src/prop/learned_db.cpp
  src/prop/learned_db.h
Labels: normal, moderate

#8589 Add oracle engine to quantifiers engine
  src/CMakeLists.txt
  src/options/quantifiers_options.toml
  src/theory/quantifiers/oracle_engine.cpp
  src/theory/quantifiers/oracle_engine.h
  src/theory/quantifiers/quantifiers_modules.cpp
  src/theory/quantifiers/quantifiers_modules.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: normal, moderate

#8595 More cleaning uses of arithmetic subtyping
  src/theory/arith/arith_utilities.cpp
  src/theory/arith/arith_utilities.h
  src/theory/arith/bound_inference.cpp
  src/theory/arith/congruence_manager.cpp
  src/theory/arith/constraint.cpp
  src/theory/arith/nl/ext/monomial_check.cpp
  src/theory/arith/theory_arith_private.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/rewriter.cpp
Labels: minor, moderate

#8574 Print nodes clusters at dot format
  src/options/printer_options.toml
  src/proof/dot/dot_printer.cpp
  src/proof/dot/dot_printer.h
Labels: normal, moderate

#8601 Fix more misuses of arithmetic subtypes
  src/theory/arith/arith_utilities.cpp
  src/theory/arith/arith_utilities.h
  src/theory/arith/nl/ext/proof_checker.cpp
  src/theory/arith/nl/ext/split_zero_check.cpp
  src/theory/arith/nl/ext/tangent_plane_check.cpp
  src/theory/arith/nl/nl_model.cpp
  src/theory/quantifiers/cegqi/ceg_arith_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
Labels: minor, simple

#8599 Add oracle caller utility
  src/expr/CMakeLists.txt
  src/expr/oracle_caller.cpp
  src/expr/oracle_caller.h
Labels: normal, moderate

#8603 Add oracle checker utility
  src/CMakeLists.txt
  src/theory/quantifiers/oracle_checker.cpp
  src/theory/quantifiers/oracle_checker.h
Labels: normal, moderate

#8607 Fix type issue for LFSC null terminator
  src/proof/lfsc/lfsc_post_processor.cpp
Labels: normal, simple

#8608 Fix spurious assertion failure caused by subtyping in LFSC proof postprocessor
  src/expr/type_node.cpp
  src/proof/lfsc/lfsc_node_converter.cpp
  src/proof/lfsc/lfsc_post_processor.cpp
Labels: normal, simple

#8612 Fix type issue for FP constants in LFSC node converter
  src/proof/lfsc/lfsc_node_converter.cpp
Labels: minor, simple

#8614 Update LFSC version
  contrib/get-lfsc-checker
Labels: normal, simple

#8611 Fix spurious assertion involving subtypes
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/quantifiers/issue8609-subtype-assert.smt2
Labels: minor, simple

#8604 Integrate oracle checker into quantifiers term registry
  src/smt/set_defaults.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/term_database_sygus.h
  src/theory/quantifiers/term_registry.cpp
  src/theory/quantifiers/term_registry.h
Labels: normal, moderate

#8143 Revised partitioning
  src/CMakeLists.txt
  src/options/parallel_options.toml
  src/prop/minisat/core/Solver.h
  src/prop/minisat/minisat.cpp
  src/prop/minisat/minisat.h
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/sat_solver.h
  src/smt/set_defaults.cpp
  src/theory/partition_generator.cpp
  src/theory/partition_generator.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: normal, moderate

#8598 Improvements to phase shifting + purification lemmas
  src/theory/arith/nl/transcendental/exponential_solver.cpp
  src/theory/arith/nl/transcendental/proof_checker.cpp
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/arith/nl/transcendental/sine_solver.h
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  src/theory/arith/nl/transcendental/transcendental_state.h
  src/theory/inference_id.cpp
  src/theory/inference_id.h
Labels: minor, moderate

#8613 Remove static calls to rewrite involving array constants
  src/theory/arrays/theory_arrays_rewriter.cpp
  src/theory/arrays/theory_arrays_rewriter.h
  src/theory/arrays/type_enumerator.cpp
  src/theory/uf/function_const.cpp
Labels: normal, moderate

#8617 Implement internal support for synthesis modulo oracles
  src/theory/quantifiers/sygus/synth_verify.cpp
  src/theory/quantifiers/sygus/synth_verify.h
Labels: normal, moderate

#8616 Make LFSC printer robust to internal types
  src/proof/lfsc/lfsc_node_converter.cpp
  src/proof/lfsc/lfsc_node_converter.h
  src/proof/lfsc/lfsc_printer.cpp
Labels: normal, moderate

#8618 Implement internal support for (definitional) satisfiability modulo oracles
  src/expr/oracle_caller.cpp
  src/expr/oracle_caller.h
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/quantifiers/oracle_engine.cpp
  src/theory/quantifiers/oracle_engine.h
Labels: normal, moderate

#8619 Fix internal type issue for congruence over quantifiers in LFSC post-processor
  src/proof/lfsc/lfsc_node_converter.cpp
  src/proof/lfsc/lfsc_post_processor.cpp
Labels: minor, simple

#8623 Remove support for unused `declare-*` commands
  NEWS.md
  src/parser/smt2/Smt2.g
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/declare-funs.smt2
Labels: normal, simple

#8580 Simplify management of separation logic heap
  src/preprocessing/passes/sep_skolem_emp.cpp
  src/smt/env.cpp
  src/smt/env.h
  src/smt/set_defaults.cpp
  src/smt/solver_engine.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/sep/theory_sep.h
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: normal, moderate

#8626 Make more utilities distinguish Int and Real
  src/preprocessing/passes/real_to_int.cpp
  src/theory/arith/arith_static_learner.cpp
  src/theory/evaluator.cpp
  src/theory/evaluator.h
Labels: normal, moderate

#8624 Distinguish name variants for types in LFSC node converter
  src/proof/lfsc/lfsc_node_converter.cpp
  src/proof/lfsc/lfsc_node_converter.h
Labels: normal, moderate

#8629 Add some missing FP symbols to LFSC
  proofs/lfsc/signatures/theory_def.plf
  src/proof/lfsc/lfsc_node_converter.cpp
Labels: minor, simple

#8630 Remove instances of `check-proofs` in regressions.
  test/regress/cli/regress0/arith/issue5219-conflict-rewrite.smt2
  test/regress/cli/regress0/preprocess/proj-issue304-circuit-prop-xor.smt2
  test/regress/cli/regress0/preprocess/proj-issue305-circuit-prop-ite-a.smt2
  test/regress/cli/regress0/preprocess/proj-issue305-circuit-prop-ite-b.smt2
  test/regress/cli/regress0/preprocess/proj-issue305-circuit-prop-ite-c.smt2
  test/regress/cli/regress0/preprocess/proj-issue305-circuit-prop-ite-d.smt2
  test/regress/cli/regress0/preprocess/proj-issue309-circuit-prop-ite.smt2
  test/regress/cli/regress0/preprocess/proj-issue332-circuit-prop-xor.smt2
  test/regress/cli/regress0/proofs/proj-issue326-nl-bounds-check.smt2
  test/regress/cli/regress0/proofs/proj-issue430-coverings-double-negation.smt2
  test/regress/cli/regress0/proofs/project-issue330-eqproof.smt2
  test/regress/cli/regress0/proofs/qgu-fuzz-5-bool-open-sat.smt2
  test/regress/cli/regress1/datatypes/dt-param-card4-unsat.smt2
  test/regress/cli/regress1/hole6.cvc.smt2
  test/regress/cli/regress1/nl/approx-sqrt-unsat.smt2
  test/regress/cli/regress1/nl/factor_agg_s.smt2
  test/regress/cli/regress1/sets/sets-disequal.smt2
  test/regress/cli/regress1/strings/proj-issue331.smt2
  test/regress/cli/regress2/instance_1444.smtv1.smt2
  test/regress/cli/run_regression.py
Labels: normal, simple

#8625 Generalize concat conflict for sequences in LFSC
  proofs/lfsc/signatures/strings_programs.plf
  proofs/lfsc/signatures/strings_rules.plf
  src/proof/lfsc/lfsc_post_processor.cpp
  src/proof/lfsc/lfsc_printer.cpp
  src/proof/lfsc/lfsc_util.cpp
  src/proof/lfsc/lfsc_util.h
Labels: normal, moderate

#8632 Add table.project evaluator
  src/CMakeLists.txt
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_kind.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/bags/bags_utils.cpp
  src/theory/bags/bags_utils.h
  src/theory/bags/kinds
  src/theory/bags/table_project_op.cpp
  src/theory/bags/table_project_op.h
  src/theory/bags/theory_bags.cpp
  src/theory/bags/theory_bags_type_rules.cpp
  src/theory/bags/theory_bags_type_rules.h
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/theory_datatypes_type_rules.cpp
  src/theory/datatypes/theory_datatypes_type_rules.h
  src/theory/datatypes/tuple_project_op.cpp
  src/theory/datatypes/tuple_project_op.h
  src/theory/datatypes/tuple_utils.cpp
  src/theory/datatypes/tuple_utils.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/bags/table_project1.smt2
Labels: normal, simple

#8634 Simplify implementation of subtype methods in TypeNode
  src/expr/type_node.cpp
  src/expr/type_node.h
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
Labels: normal, simple

#8635 Avoid trivial equalities in explanation of SETS_CARD_CYCLE
  src/theory/sets/cardinality_extension.cpp
Labels: minor, simple

#8597 Updates to zero level learner
  src/preprocessing/preprocessing_pass_context.cpp
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
  src/prop/zero_level_learner.cpp
  src/prop/zero_level_learner.h
  src/smt/solver_engine.cpp
Labels: normal, moderate

#8639 Remove redundant assertion in int-blaster
  src/theory/bv/int_blaster.cpp
  test/unit/api/cpp/solver_black.cpp
Labels: bug

#8636 Minor simplifications for datatype selector triggers
  src/theory/quantifiers/ematching/candidate_generator.cpp
  src/theory/quantifiers/ematching/candidate_generator.h
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  src/theory/quantifiers/instantiate.cpp
Labels: minor, simple

#8621 Add declare-oracle-fun command utility
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/smt/command.cpp
  src/smt/command.h
Labels: normal, simple

#8641 Improve handling of `(push)` and `(pop)`
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/printer/ast/ast_printer.cpp
  src/printer/ast/ast_printer.h
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/smt/command.cpp
  src/smt/command.h
Labels: normal, simple

#8048 Remove unused `SEQ_NTH_TOTAL` kind
  src/parser/parser.h
  src/theory/strings/kinds
  src/theory/strings/rewrites.cpp
  src/theory/strings/rewrites.h
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/sequences_rewriter.h
  src/theory/theory_model.cpp
  src/theory/theory_model_builder.cpp
  test/regress/cli/regress0/seq/seq-expand-defs.smt2
Labels: normal, simple

#8642 Add utilities in preparation for deep restarts
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
  src/prop/zero_level_learner.cpp
  src/prop/zero_level_learner.h
Labels: normal, simple

#8637 Add bag.partition evaluation
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_kind.h
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/bags/bags_rewriter.cpp
  src/theory/bags/bags_rewriter.h
  src/theory/bags/bags_utils.cpp
  src/theory/bags/bags_utils.h
  src/theory/bags/kinds
  src/theory/bags/rewrites.cpp
  src/theory/bags/rewrites.h
  src/theory/bags/theory_bags.cpp
  src/theory/bags/theory_bags_type_rules.cpp
  src/theory/bags/theory_bags_type_rules.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/bags/bag_partition1.smt2
Labels: normal, moderate, do not merge

#8643 [Seq] Remove `SkolemCache::mkSkolemSeqNth()`
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/theory/strings/array_core_solver.cpp
  src/theory/strings/array_solver.cpp
  src/theory/strings/skolem_cache.cpp
  src/theory/strings/skolem_cache.h
  src/theory/strings/theory_strings_preprocess.cpp
Labels: normal, moderate

#8606 Add tester for LFSC printer.
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/bv/div_mod.cvc.smt2
  test/regress/cli/regress0/bv/fuzz15.delta01.smtv1.smt2
  test/regress/cli/regress0/bv/fuzz38.delta01.smtv1.smt2
  test/regress/cli/regress0/fp/issue-5524.smt2
  test/regress/cli/regress0/fp/rti_3_5_bug.smt2
  test/regress/cli/regress0/fp/word-blast.smt2
  test/regress/cli/regress0/quantifiers/lra-triv-gn.smt2
  test/regress/cli/regress0/seq/seq-types.smt2
  test/regress/cli/regress1/aufbv/bug348.smtv1.smt2
  test/regress/cli/regress1/auflia/bug330.smt2
  test/regress/cli/regress1/bv/divtest.smt2
  test/regress/cli/regress1/bv/fuzz38.smtv1.smt2
  test/regress/cli/regress1/bv/incorrect1.smtv1.smt2
  test/regress/cli/regress1/bv/proj-issue438-prerewrite-fixed-point-original.smt2
  test/regress/cli/regress1/bvdiv2.smt2
  test/regress/cli/regress1/fp/rti_3_5_bug_report.smt2
  test/regress/cli/regress1/issue3970-nl-ext-purify.smt2
  test/regress/cli/regress1/quantifiers/NUM878.smt2
  test/regress/cli/regress1/quantifiers/inst-max-level-segf.smt2
  test/regress/cli/regress1/quantifiers/issue4021-ind-opts.smt2
  test/regress/cli/regress1/quantifiers/qbv-test-invert-bvcomp.smt2
  test/regress/cli/regress1/quantifiers/seqa-unsat-unknown-110921.smt2
  test/regress/cli/regress1/quantifiers/tpp-unit-fail-qbv.smt2
  test/regress/cli/regress1/sets/comp-intersect.smt2
  test/regress/cli/regress1/sets/comp-odd.smt2
  test/regress/cli/regress1/sets/comp-pos-member.smt2
  test/regress/cli/regress1/sets/comp-positive.smt2
  test/regress/cli/regress1/sygus/issue3201.smt2
  test/regress/cli/regress1/sygus/issue3247.smt2
  test/regress/cli/regress1/sygus/issue3995-fmf-var-op.smt2
  test/regress/cli/regress1/sygus/issue4009-qep.smt2
  test/regress/cli/regress1/sygus/issue4083-var-shadow.smt2
  test/regress/cli/regress1/sygus/issue4425-sets-sygus-infer.smt2
  test/regress/cli/regress1/sygus/proj-issue185.smt2
  test/regress/cli/regress2/bug349.smtv1.smt2
  test/regress/cli/regress2/fp/issue7056.smt2
  test/regress/cli/regress2/instance_1444.smtv1.smt2
  test/regress/cli/regress2/nl/ufnia-factor-open-proof.smt2
  test/regress/cli/regress2/ooo.tag10.smt2
  test/regress/cli/run_regression.py
Labels: normal, moderate

#8644 Add `deep-restart` option
  src/options/base_options.toml
  src/options/smt_options.toml
  src/prop/theory_proxy.cpp
  src/prop/zero_level_learner.cpp
  src/prop/zero_level_learner.h
  src/smt/set_defaults.cpp
  src/smt/smt_solver.cpp
  src/smt/smt_solver.h
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/deep-restart/dd.266.smt2
  test/regress/cli/regress0/deep-restart/dd.fuzz21.smtv1.smt2
  test/regress/cli/regress0/deep-restart/dd.issue4735.smt2
  test/regress/cli/regress0/deep-restart/dd.wrong-sat-020322.smt2
  test/regress/cli/regress0/printer/deep-restart-output.smt2
Labels: normal, moderate, do not merge

#8650 Minor cleanup of NodeManager
  src/api/cpp/cvc5.cpp
  src/expr/node_builder.cpp
  src/expr/node_manager_template.cpp
  src/expr/node_manager_template.h
  src/preprocessing/passes/ite_simp.cpp
  src/preprocessing/passes/ite_simp.h
  src/preprocessing/passes/synth_rew_rules.cpp
  src/theory/datatypes/sygus_datatype_utils.cpp
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_grammar_norm.cpp
  src/theory/rewriter.cpp
  src/theory/rewriter.h
  src/theory/rewriter_tables_template.h
Labels: minor, simple

#8653 Add custom targets for specific testers.
  test/regress/cli/CMakeLists.txt
Labels: normal, moderate

#8633 Make BVInstantiatorUtil an EnvObj
  src/smt/solver_engine.h
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.h
  src/theory/quantifiers/cegqi/ceg_bv_instantiator_utils.cpp
  src/theory/quantifiers/cegqi/ceg_bv_instantiator_utils.h
  test/unit/theory/theory_quantifiers_bv_instantiator_white.cpp
Labels: normal, simple

#8658 Option exception for quantified bit-vectors + eager bitblasting + incremental
  src/smt/set_defaults.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/bv/issue8654-bitblast-quant-exc.smt2
Labels: major, simple

#8656 Move VTS term cache to term registry
  src/theory/quantifiers/cegqi/ceg_arith_instantiator.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.h
  src/theory/quantifiers/cegqi/vts_term_cache.cpp
  src/theory/quantifiers/cegqi/vts_term_cache.h
  src/theory/quantifiers/term_registry.cpp
  src/theory/quantifiers/term_registry.h
Labels: normal, simple

#8652 [Regressions] Use Wine for Windows builds
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/models-print-2.smt2
  test/regress/cli/regress0/options/help.smt2
  test/regress/cli/run_regression.py
Labels: normal, moderate

#8620 Simplify internal representation of instantiated sorts
  src/expr/dtype_cons.cpp
  src/expr/node_manager_template.cpp
  src/expr/type_node.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/builtin/kinds
  src/theory/builtin/type_enumerator.cpp
  src/theory/datatypes/theory_datatypes_type_rules.cpp
Labels: normal, moderate, do not merge

#8645 Fix GMP cross-compilation when Wine installed
  cmake/FindGMP.cmake
Labels: normal, moderate

#8660 Simplify internal represenation of uninterpreted sorts
  src/expr/node_converter.cpp
  src/expr/node_manager_template.cpp
  src/expr/node_manager_template.h
  src/theory/builtin/kinds
Labels: normal, simple

#8662 Add some missing resultants in the coverings solver
  src/theory/arith/nl/coverings/cdcac.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/nl/issue8638-cov-resultants.smt2
Labels: normal, moderate

#8657 Refactor mkRep option for instantiation
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/instantiate.h
Labels: normal, simple

#8647 Move rep set iterator to its own file
  src/CMakeLists.txt
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/fmf/bounded_integers.h
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/quantifiers/quant_bound_inference.cpp
  src/theory/quantifiers/quant_bound_inference.h
  src/theory/quantifiers/quant_rep_bound_ext.cpp
  src/theory/quantifiers/quant_rep_bound_ext.h
  src/theory/rep_set.cpp
  src/theory/rep_set.h
  src/theory/rep_set_iterator.cpp
  src/theory/rep_set_iterator.h
Labels: minor, simple

#8649 Make IndexTrie take nodes
  src/theory/quantifiers/index_trie.cpp
  src/theory/quantifiers/index_trie.h
  src/theory/quantifiers/inst_strategy_enumerative.cpp
  src/theory/quantifiers/inst_strategy_pool.cpp
  src/theory/quantifiers/term_tuple_enumerator.cpp
  src/theory/quantifiers/term_tuple_enumerator.h
Labels: normal, moderate

#8661 Minor improvements to quantifiers utilities
  src/expr/term_canonize.cpp
  src/expr/term_canonize.h
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers/term_database.h
Labels: normal, simple

#8663 Minor improvements for entailment test
  src/theory/quantifiers/entailment_check.cpp
Labels: minor, simple

#8666 Refactoring of term registration in datatypes
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
Labels: normal, moderate

#8668 Add option to apply constant propagation for all learned literals
  src/options/smt_options.toml
  src/preprocessing/passes/non_clausal_simp.cpp
  src/smt/set_defaults.cpp
  src/smt/set_defaults.h
Labels: normal, simple

#8672 Add resource limiting to coverings solver
  src/theory/arith/nl/coverings/cdcac.cpp
  src/util/resource_manager.cpp
  src/util/resource_manager.h
Labels: normal, simple

#8671 Make labelled separation logic asserts preserve labels
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/sep/theory_sep.cpp
  src/theory/sep/theory_sep.h
  src/theory/sep/theory_sep_rewriter.cpp
Labels: normal, moderate

#8664 Move datatype split inference scheme to its own method
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
Labels: minor, simple

#8669 Add some missing API tests
  test/unit/api/cpp/op_black.cpp
  test/unit/api/cpp/result_black.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/cpp/sort_black.cpp
  test/unit/api/cpp/synth_result_black.cpp
  test/unit/api/java/OpTest.java
  test/unit/api/java/ResultTest.java
  test/unit/api/java/SynthResultTest.java
  test/unit/api/python/test_op.py
  test/unit/api/python/test_result.py
  test/unit/api/python/test_synth_result.py
Labels: minor, moderate

#8677 Add unit test for code not exposed by python API
  src/api/cpp/cvc5.cpp
  test/unit/api/python/CMakeLists.txt
  test/unit/api/python/test_uncovered.cpp
Labels: minor, moderate

#8678 Add unit test for code not exposed by java API
  src/api/cpp/cvc5.cpp
  test/unit/api/java/CMakeLists.txt
  test/unit/api/java/SolverTest.java
  test/unit/api/java/UncoveredTest.cpp
Labels: minor, moderate

#8676 Add an option to enable all testers.
  test/regress/cli/CMakeLists.txt
  test/regress/cli/run_regression.py
Labels: normal, simple

#8682 Make extended rewriter use standard Subs utility
  src/theory/quantifiers/extended_rewrite.cpp
  src/theory/quantifiers/extended_rewrite.h
Labels: minor, simple

#8683 Ensure mkConstInt is used on integral rationals only
  src/expr/node_manager_template.cpp
  src/proof/proof_rule.cpp
  src/theory/arith/arith_msum.cpp
  src/theory/arith/linear/constraint.cpp
  src/theory/arith/linear/theory_arith_private.cpp
Labels: normal, simple

#8679 Document non-standard string operators
  docs/theories/strings.rst
  docs/theories/theories.rst
Labels: major, moderate

#8680 Towards proper usage of TO_REAL
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_rewriter.h
  src/theory/arith/linear/theory_arith_private.cpp
  src/theory/arith/rewriter/rewrite_atom.cpp
  src/theory/arith/rewriter/rewrite_atom.h
  src/theory/arith/rewrites.cpp
  src/theory/arith/rewrites.h
  src/theory/arith/theory_arith.cpp
  src/theory/evaluator.cpp
  src/theory/quantifiers/cegqi/ceg_arith_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/fmf/full_model_check.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arith/bug549.cvc.smt2
  test/regress/cli/regress0/bug339.smt2
  test/regress/cli/regress0/nl/dd.fuzz01.smtv1-to-real-idem.smt2
  test/regress/cli/regress0/quantifiers/mix-match.smt2
Labels: normal, moderate

#8686 Replace mkConst(CONST_RATIONAL) by mkConstReal()
  src/theory/arith/nl/coverings/cdcac.cpp
  src/theory/arith/nl/coverings/proof_generator.cpp
  src/theory/arith/nl/ext/ext_state.cpp
  src/theory/arith/nl/ext/factoring_check.cpp
  src/theory/arith/nl/ext/monomial.cpp
  src/theory/arith/nl/ext/monomial_bounds_check.cpp
  src/theory/arith/nl/ext/proof_checker.cpp
  src/theory/arith/nl/ext/tangent_plane_check.cpp
  src/theory/arith/nl/nl_model.cpp
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/poly_conversion.cpp
Labels: normal, moderate

#8685 Add simple type rule for real-or-int arguments
  src/expr/type_checker_util.h
  src/theory/arith/kinds
Labels: normal, moderate
