Repository cvc5/cvc5, pull requests merged in 2022-09, with the labels that each got.

#9098 Do not compute intersections of regular expressions with complement
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/regexp_solver.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/strings/issue9040-re-inter-comp.smt2
Labels: minor, simple

#9097 Support lazy approach for arithmetic-bitvector conversion in UF
  src/CMakeLists.txt
  src/options/uf_options.toml
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/quantifiers/term_database.cpp
  src/theory/uf/conversions_solver.cpp
  src/theory/uf/conversions_solver.h
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/issue8958-bv2nat-lazy.smt2
Labels: normal, moderate

#9104 bv: Only force BITBLAST_INTERNAL if full proofs are required.
  src/smt/set_defaults.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/bv/issue9101-unsat-cores.smt2
Labels: normal, simple

#9100 [Strings] Fix typo in `RegExpConstType`
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/regexp_operation.h
  src/theory/strings/regexp_solver.cpp
Labels: minor, simple

#9034 Remove expandDefinitions infrastructure in the preprocessor
  src/smt/expand_definitions.cpp
  src/smt/expand_definitions.h
  src/smt/optimization_solver.cpp
  src/smt/preprocessor.cpp
  src/smt/preprocessor.h
  src/smt/process_assertions.cpp
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  src/smt/sygus_solver.cpp
  src/theory/substitutions.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/get-value-div-0.smt2
Labels: minor, moderate

#9059 ff: kinds file and deps (enumerator, type-checker, rewriter)
  src/CMakeLists.txt
  src/expr/node_manager_template.cpp
  src/expr/node_manager_template.h
  src/expr/type_node.cpp
  src/expr/type_node.h
  src/theory/ff/kinds
  src/theory/ff/theory_ff.cpp
  src/theory/ff/theory_ff.h
  src/theory/ff/theory_ff_rewriter.cpp
  src/theory/ff/theory_ff_rewriter.h
  src/theory/ff/theory_ff_type_rules.cpp
  src/theory/ff/theory_ff_type_rules.h
  src/theory/ff/type_enumerator.h
  src/theory/logic_info.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_id.cpp
  src/theory/theory_id.h
  src/util/CMakeLists.txt
  src/util/ff_val.cpp
  src/util/ff_val.h
  test/unit/theory/logic_info_white.cpp
  test/unit/theory/theory_arith_coverings_white.cpp
Labels: normal, moderate

#9108 Fix push/pop with quantifier elimination solver
  src/smt/solver_engine.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/quantifiers/issue8923-qe-push-pop.smt2
Labels: normal, moderate

#9019 Move rewrite rule for set minus to ppRewrite
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/sets/issue8995-minus-rr.smt2
Labels: minor, simple

#9109 Reflect function definitions in LFSC.
  src/proof/lfsc/lfsc_post_processor.cpp
  src/proof/lfsc/lfsc_post_processor.h
  src/proof/lfsc/lfsc_printer.cpp
  src/proof/lfsc/lfsc_printer.h
  src/proof/lfsc/lfsc_util.cpp
  src/proof/lfsc/lfsc_util.h
  src/smt/proof_manager.cpp
  src/smt/proof_manager.h
  src/smt/solver_engine.cpp
Labels: normal, moderate

#9117 Removing semi-colons from python example
  examples/api/python/quickstart.py
Labels: minor, simple

#9107 Use SMT driver for checkSat
  src/CMakeLists.txt
  src/smt/quant_elim_solver.cpp
  src/smt/smt_driver_deep_restarts.cpp
  src/smt/smt_driver_deep_restarts.h
  src/smt/smt_solver.cpp
  src/smt/smt_solver.h
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  src/smt/sygus_solver.cpp
Labels: normal, moderate

#9106 [CMake] Use `SYSTEM` includes for dependencies
  .github/workflows/ci.yml
  cmake/FindANTLR3.cmake
  cmake/FindCLN.cmake
  cmake/FindCaDiCaL.cmake
  cmake/FindCoCoA.cmake
  cmake/FindCryptoMiniSat.cmake
  cmake/FindDummy.cmake.template
  cmake/FindGMP.cmake
  cmake/FindGTest.cmake
  cmake/FindKissat.cmake
  cmake/FindPoly.cmake
  cmake/FindSymFPU.cmake
  cmake/deps-helper.cmake
  src/CMakeLists.txt
Labels: minor, simple

#9122 Add regression for fixed issue
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/issue8767-exception.smt2
Labels: normal, simple

#9119 Fix LFSC printing bug.
  src/proof/lfsc/lfsc_printer.cpp
  src/smt/proof_manager.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/unused-def1.smt2
  test/regress/cli/regress0/proofs/unused-def2.smt2
Labels: normal, moderate

#9124 Fixes for API coverage
  src/api/cpp/cvc5_types.cpp
  src/api/cpp/cvc5_types.h
  test/unit/api/cpp/CMakeLists.txt
  test/unit/api/cpp/types_black.cpp
  test/unit/api/java/UncoveredTest.cpp
  test/unit/api/python/test_uncovered.cpp
Labels: normal, simple

#9103 Minor refactoring arithmetic congruence manager
  src/theory/arith/linear/congruence_manager.cpp
  src/theory/arith/linear/congruence_manager.h
Labels: minor, simple

#9105 Expand definitions in check-model
  src/smt/check_models.cpp
  src/smt/expand_definitions.cpp
  test/regress/cli/regress0/arith/div.02.smt2
  test/regress/cli/regress0/arith/issue8097-iid.smt2
  test/regress/cli/regress0/arrays/issue5836-2.smt2
  test/regress/cli/regress0/cores/issue5238.smt2
  test/regress/cli/regress0/fp/issue7002.smt2
  test/regress/cli/regress0/get-value-div-0.smt2
  test/regress/cli/regress0/nl/dd.fuzz01.smtv1-to-real-idem.smt2
  test/regress/cli/regress0/nl/issue3411.smt2
  test/regress/cli/regress0/nl/issue4463-ack-model.smt2
  test/regress/cli/regress0/nl/issue5737-div00.smt2
  test/regress/cli/regress0/nl/issue8712-div-toreal-rew.smt2
  test/regress/cli/regress0/proofs/proj-issue326-nl-bounds-check.smt2
  test/regress/cli/regress0/seq/proj-issue384-2-subtypes.smt2
  test/regress/cli/regress0/strings/issue5767-eager-pp.smt2
  test/regress/cli/regress1/arith/arith-brab-test.smt2
  test/regress/cli/regress1/arith/div.06.smt2
  test/regress/cli/regress1/arith/issue6774-sanity-int-model.smt2
  test/regress/cli/regress1/arith/issue7252-arith-sanity.smt2
  test/regress/cli/regress1/arith/mod.03.smt2
  test/regress/cli/regress1/cores/issue6988-arith-sanity.smt2
  test/regress/cli/regress1/issue7937-difficulty-irr.smt2
  test/regress/cli/regress1/nl/div-mod-partial.smt2
  test/regress/cli/regress1/nl/issue8960-lr-to-real-model.smt2
  test/regress/cli/regress1/nl/proj-issue290.smt2
  test/regress/cli/regress1/quantifiers/issue8497-syqi-str-fmf.smt2
  test/regress/cli/regress1/sets/issue4391-card-lasso.smt2
  test/regress/cli/regress1/strings/issue6203-1-substr-ctn-strip.smt2
  test/regress/cli/regress1/strings/issue6653-3-seq.smt2
  test/regress/cli/regress1/strings/issue6777-seq-nth-eval-cm.smt2
  test/regress/cli/regress1/strings/issue8916-str-unit-pairs.smt2
  test/regress/cli/regress1/strings/issue8932-cmi-unit.smt2
  test/regress/cli/regress1/sygus/issue3634.smt2
Labels: minor, simple

#9125 [CI] Test macOS 12
  .github/workflows/ci.yml
Labels: minor, simple

#9127 Fix get-value output to not letify across key-value pairs
  src/api/cpp/cvc5.cpp
  src/smt/command.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/printer/get-value-no-letify.smt2
Labels: major, simple

#9004 Allow `(get-model)` after answering `unknown`
  NEWS.md
  src/smt/smt_solver.cpp
  src/smt/smt_solver.h
  src/smt/solver_engine.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/util/resource_manager.cpp
  src/util/resource_manager.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/solver/issue8854-get-model-after-unknown.smt2
Labels: major, moderate

#8122 [Seq/Array] Ignore congruent and inactive terms
  src/theory/strings/array_solver.cpp
  src/theory/strings/array_solver.h
  src/theory/strings/base_solver.cpp
  src/theory/strings/base_solver.h
  src/theory/strings/extf_solver.cpp
  src/theory/strings/extf_solver.h
  src/theory/strings/theory_strings.cpp
Labels: normal, moderate

#9133 Remove mention of `ENTAILED`/`NOT_ENTAILED`
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/Solver.java
  src/api/python/cvc5.pxi
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
Labels: minor, simple

#9134 [Arith] Fix elimination of inverse functions with integer arguments
  src/smt/smt_driver.cpp
  src/theory/arith/operator_elim.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arith/issue9131-inverse-of-int.smt2
Labels: normal, moderate

#9136 Further simplification of printing for get-value
  src/smt/command.cpp
  src/smt/command.h
Labels: simple, moderate

#9132 [Regressions] Improve output of regression script
  test/regress/cli/run_regression.py
Labels: normal, moderate

#9128 Fix care graph for bv2nat of different widths
  src/theory/uf/theory_uf.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/issue9112-bv2nat-cg.smt2
Labels: normal, simple

#9123 Transfer ownership of assertions to SMT solver
  src/smt/smt_driver.cpp
  src/smt/smt_driver_deep_restarts.cpp
  src/smt/smt_solver.cpp
  src/smt/smt_solver.h
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  src/smt/sygus_solver.cpp
  src/smt/sygus_solver.h
Labels: minor, moderate

#9129 Fix `NEWS.md`
  NEWS.md
Labels: minor, simple

#9130 [Strings] Refactor base solver, improve debugging
  src/theory/strings/base_solver.cpp
  src/theory/strings/theory_strings.cpp
Labels: normal, moderate

#8893 Move `Command` infrastructure to parser
  src/CMakeLists.txt
  src/api/cpp/cvc5.h
  src/expr/node_manager_template.cpp
  src/expr/node_manager_template.h
  src/expr/node_value.h
  src/expr/type_node.cpp
  src/expr/type_node.h
  src/main/command_executor.cpp
  src/main/command_executor.h
  src/main/driver_unified.cpp
  src/main/interactive_shell.cpp
  src/main/interactive_shell.h
  src/main/portfolio_driver.cpp
  src/main/portfolio_driver.h
  src/options/io_utils_template.h
  src/options/mkoptions.py
  src/options/options_handler.cpp
  src/parser/CMakeLists.txt
  src/parser/api/cpp/command.cpp
  src/parser/api/cpp/command.h
  src/parser/api/cpp/symbol_manager.cpp
  src/parser/input.h
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.h
  src/parser/smt2/smt2_input.h
  src/parser/smt2/sygus_input.h
  src/parser/tptp/Tptp.g
  src/parser/tptp/tptp.cpp
  src/parser/tptp/tptp.h
  src/printer/ast/ast_printer.cpp
  src/printer/ast/ast_printer.h
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/printer/tptp/tptp_printer.cpp
  src/printer/tptp/tptp_printer.h
  src/proof/unsat_core.h
  src/theory/quantifiers/sygus/sygus_reconstruct.cpp
  src/util/ff_val.h
  src/util/smt2_quote_string.h
  test/api/cpp/ouroborous.cpp
  test/api/cpp/smt2_compliance.cpp
  test/unit/main/interactive_shell_black.cpp
  test/unit/parser/parser_black.cpp
  test/unit/parser/parser_builder_black.cpp
Labels: normal, moderate

#9135 Check whether theories are enabled during ppRewrite
  src/theory/theory_engine.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/issue9121-theoryof-no-enabled.smt2
Labels: normal, simple

#9139 Fix computation of cardinality class
  src/util/cardinality.h
  src/util/cardinality_class.cpp
  src/util/cardinality_class.h
  test/unit/api/cpp/solver_black.cpp
Labels: normal, moderate

#9102 Filter relevant skolemizations with --dump-instantiations
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  src/smt/unsat_core_manager.cpp
  src/smt/unsat_core_manager.h
  test/regress/cli/regress1/quantifiers/dump-inst-i.smt2
  test/regress/cli/regress1/quantifiers/dump-inst.smt2
Labels: minor, moderate

#9091 Add entailment term evaluator
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/theory/quantifiers/ieval/state.cpp
  src/theory/quantifiers/ieval/state.h
  src/theory/quantifiers/ieval/term_evaluator.cpp
  src/theory/quantifiers/ieval/term_evaluator.h
Labels: normal, moderate

#9137 Do not traverse beneath non-standard closures when selecting patterns
  src/theory/quantifiers/ematching/pattern_term_selector.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/quantifiers/proj-issue532-set-comp-fv-trigger.smt2
Labels: minor, simple

#9143 Move proof rule checker to own file
  src/CMakeLists.txt
  src/proof/proof_checker.cpp
  src/proof/proof_checker.h
  src/proof/proof_rule_checker.cpp
  src/proof/proof_rule_checker.h
  src/prop/cnf_stream.h
  src/prop/theory_proxy.cpp
  src/theory/bv/bv_solver_bitblast_internal.h
Labels: minor, simple

#9092 Add instantiation evaluator
  src/CMakeLists.txt
  src/theory/quantifiers/ieval/inst_evaluator.cpp
  src/theory/quantifiers/ieval/inst_evaluator.h
  src/theory/quantifiers/ieval/quant_info.h
  src/theory/quantifiers/ieval/state.cpp
  src/theory/quantifiers/ieval/state.h
Labels: normal, moderate

#9152 Apply oracle function in uncovered python unit test
  test/unit/api/python/test_uncovered.cpp
Labels: normal, simple

#9141 [proof] [sat] Avoid duplicating assumption in chain links for SAT proof
  src/proof/buffered_proof_generator.cpp
  src/proof/buffered_proof_generator.h
  src/proof/lazy_proof.cpp
  src/proof/lazy_proof_chain.cpp
  src/prop/proof_cnf_stream.cpp
  src/prop/sat_proof_manager.cpp
Labels: normal, moderate

#9145 Stabilize numbering of bound and free vars in LFSC proofs.
  src/proof/lfsc/lfsc_node_converter.cpp
  src/proof/lfsc/lfsc_node_converter.h
  src/proof/lfsc/lfsc_post_processor.cpp
  src/proof/lfsc/lfsc_printer.cpp
Labels: normal, moderate

#9153 [proof] Add regression
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/proj-issue529-open-pf.smt2
Labels: minor, simple

#9150 Add instantiation evaluator manager
  src/CMakeLists.txt
  src/theory/quantifiers/ieval/inst_evaluator_manager.cpp
  src/theory/quantifiers/ieval/inst_evaluator_manager.h
  src/theory/quantifiers/term_registry.cpp
  src/theory/quantifiers/term_registry.h
Labels: normal, moderate

#9151 Implementation of instantiation evaluation state
  src/theory/quantifiers/ieval/state.cpp
  src/theory/quantifiers/ieval/state.h
Labels: normal, moderate

#9148 Fix getEqualityStatus for non-linear arithmetic terms
  src/theory/arith/theory_arith.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/nl/issue9113-1-iand-cg.smt2
  test/regress/cli/regress1/nl/issue9113-iand-cg.smt2
Labels: normal, simple

#9154 NM: Initialize NodeManager on construction.
  src/api/cpp/cvc5.cpp
  src/expr/node_manager_template.cpp
  src/expr/node_manager_template.h
  src/expr/node_value.cpp
  src/expr/node_value.h
  test/unit/test_node.h
  test/unit/test_smt.h
Labels: normal, simple

#9159 Fix print benchmark utility for dependencies in the body of ordinary define-fun
  src/smt/print_benchmark.cpp
Labels: normal, simple

#9155 [parser] Fix handling of the :named attribute
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/use-name-in-same-command-minimal.smt2
  test/regress/cli/regress0/parser/use-name-in-same-command.smt2
Labels: normal, simple

#9157 Unexpected EOF exception for unterminated tokens
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/Smt2.g
Labels: normal, moderate

#9161 api: Associate nullary constructors with currentNM().
  src/api/cpp/cvc5.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/parser/smt2/smt2.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/python/test_solver.py
Labels: normal, simple

#9142 Better error checking for indices of `to_fp`
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_checks.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/issue9140-check-to-fp-args.smt2
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
Labels: normal, simple

#9138 Minor simplification to solver engine interface
  src/printer/tptp/tptp_printer.cpp
  src/smt/abduction_solver.cpp
  src/smt/assertions.cpp
  src/smt/expand_definitions.cpp
  src/smt/interpolation_solver.cpp
  src/smt/optimization_solver.cpp
  src/smt/optimization_solver.h
  src/smt/preprocessor.cpp
  src/smt/proof_post_processor.cpp
  src/smt/smt_solver.cpp
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  src/smt/solver_engine_state.cpp
  src/theory/bv/theory_bv_rewrite_rules.h
  src/theory/quantifiers/ematching/candidate_generator.cpp
  src/theory/rewriter.cpp
  src/theory/smt_engine_subsolver.cpp
  src/theory/theory_model.cpp
  test/unit/preprocessing/pass_bv_gauss_white.cpp
  test/unit/prop/cnf_stream_white.cpp
  test/unit/theory/evaluator_white.cpp
  test/unit/theory/regexp_operation_black.cpp
  test/unit/theory/sequences_rewriter_white.cpp
  test/unit/theory/strings_rewriter_white.cpp
  test/unit/theory/theory_arith_coverings_white.cpp
  test/unit/theory/theory_arith_rewriter_black.cpp
  test/unit/theory/theory_arith_white.cpp
  test/unit/theory/theory_bags_rewriter_white.cpp
  test/unit/theory/theory_black.cpp
  test/unit/theory/theory_bv_rewriter_white.cpp
  test/unit/theory/theory_engine_white.cpp
  test/unit/theory/theory_sets_rewriter_white.cpp
  test/unit/theory/theory_sets_type_enumerator_white.cpp
  test/unit/theory/theory_white.cpp
Labels: minor, simple

#9166 Fix bug causing Amazon Linux 2 nightly failures.
  src/proof/lfsc/lfsc_printer.cpp
Labels: normal, simple

#9168 test: Use correct Python interpreter for run_regression.py.
  test/regress/cli/CMakeLists.txt
Labels: major, simple

#9160 Use the interactive shell when piping from stdin
  src/main/driver_unified.cpp
  src/main/interactive_shell.cpp
  src/main/interactive_shell.h
  src/options/main_options.toml
Labels: major, simple

#9170 bv: rewriter: Remove unwanted whitespaces.
  src/theory/bv/theory_bv_rewriter.cpp
Labels: minor, simple

#9149 Improve management of relevant terms in TheoryStrings
  src/theory/arith/theory_arith.cpp
  src/theory/model_manager_distributed.cpp
  src/theory/strings/base_solver.cpp
  src/theory/strings/base_solver.h
  src/theory/strings/extf_solver.cpp
  src/theory/strings/extf_solver.h
  src/theory/strings/term_registry.cpp
  src/theory/strings/term_registry.h
  src/theory/strings/theory_strings.cpp
  src/theory/theory.cpp
  src/theory/theory.h
Labels: normal, moderate

#9169 bv: Add native support for unsigned multiplication overflow detection.
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_kind.h
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/bv/kinds
  src/theory/bv/theory_bv_rewrite_rules.h
  src/theory/bv/theory_bv_rewrite_rules_operator_elimination.h
  src/theory/bv/theory_bv_rewriter.cpp
  src/theory/bv/theory_bv_rewriter.h
  src/theory/bv/theory_bv_utils.cpp
  src/theory/bv/theory_bv_utils.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/bv/overflow/umulo1.smt2
  test/regress/cli/regress0/bv/overflow/umulo2.smt2
  test/unit/theory/theory_bv_white.cpp
Labels: normal, moderate

#9173 ff: statistics
  src/CMakeLists.txt
  src/theory/ff/stats.cpp
  src/theory/ff/stats.h
Labels: normal, simple

#9175 Fixes for theory combination + non-linear arithmetic
  src/theory/arith/arith_evaluator.cpp
  src/theory/arith/arith_evaluator.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/nl/issue9164-2.smt2
  test/regress/cli/regress1/nl/issue9164.smt2
Labels: normal, moderate

#9174 bv: Add native support for signed multiplication overflow detection.
  proofs/lfsc/signatures/theory_def.plf
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_kind.h
  src/parser/smt2/smt2.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/bv/kinds
  src/theory/bv/theory_bv_rewrite_rules.h
  src/theory/bv/theory_bv_rewrite_rules_operator_elimination.h
  src/theory/bv/theory_bv_rewriter.cpp
  src/theory/bv/theory_bv_rewriter.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/bv/overflow/smulo1.smt2
  test/regress/cli/regress0/bv/overflow/smulo2.smt2
  test/unit/theory/theory_bv_white.cpp
Labels: normal, moderate

#9180 lfsc: Add bvumulo to signature.
  proofs/lfsc/signatures/theory_def.plf
Labels: major, simple
