Repository cvc5/cvc5, pull requests merged in 2022-08, with the labels that each got.

#9002 [proof] [cnf] Decouple Proof Cnf Stream from Sat Proof Manager
  src/prop/proof_cnf_stream.cpp
  src/prop/proof_cnf_stream.h
Labels: normal, simple

#9005 [Cython] Set language level explicitly
  src/api/python/CMakeLists.txt
  src/api/python/cvc5_python_base.pyx
Labels: minor, simple

#9008 Fix model block values mode when no terms are specified
  src/smt/model_blocker.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/model-blocker-no-spec-values.smt2
Labels: normal, simple

#9018 Catch logic exception for higher-order relation operators
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets_rewriter.cpp
  src/theory/uf/theory_uf.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/sets/issue8987-ho-exception.smt2
  test/regress/cli/regress1/sets/issue8987-ho.smt2
Labels: normal, simple

#9017 Make cegis-sample robust for unevaluatable conjectures
  src/theory/quantifiers/sygus/cegis.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/abduction/issue9001-sample-fail.smt2
Labels: minor, simple

#9014 Fix spurious registration lemma for string disequality split
  src/theory/strings/core_solver.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/strings/issue9003-deq-split.smt2
Labels: major, simple

#9013 Optimize arithmetic getEqualityStatus
  src/theory/arith/arith_evaluator.cpp
  src/theory/arith/arith_evaluator.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
Labels: normal, moderate

#8990 Add learned literal types to the API
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/cpp/cvc5_types.cpp
  src/api/cpp/cvc5_types.h
  src/api/java/CMakeLists.txt
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/jni/solver.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/prop/learned_db.cpp
  src/prop/learned_db.h
  src/prop/theory_proxy.cpp
  src/prop/zero_level_learner.cpp
  src/smt/command.cpp
  src/smt/command.h
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  src/theory/partition_generator.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/printer/learned-lit-output.smt2
  test/regress/cli/regress1/get-learned-literals-types.smt2
  test/unit/api/java/SolverTest.java
  test/unit/api/java/UncoveredTest.cpp
  test/unit/api/python/test_solver.py
  test/unit/api/python/test_uncovered.cpp
Labels: normal, moderate

#9020 api: Refactor sort and term (like) objects to not depend on Solver.
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/cpp/cvc5_checks.h
  src/smt/sygus_solver.cpp
  test/unit/api/cpp/op_white.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/cpp/solver_white.cpp
  test/unit/api/cpp/term_white.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
Labels: moderate

#9007 Minor refactoring in preparation for proof components
  src/smt/proof_manager.cpp
  src/smt/proof_manager.h
  src/smt/smt_solver.cpp
  src/smt/smt_solver.h
  src/smt/solver_engine.cpp
Labels: normal, simple

#9009 Use synth verify utility to check side conditions for abduction
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/synth_verify.cpp
  src/theory/quantifiers/sygus/synth_verify.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/abduction/dd.abduct-check-sc.smt2
Labels: normal, moderate

#9016 Minor sync to proof-new
  src/expr/nary_match_trie.cpp
  src/printer/let_binding.h
  src/proof/alethe/alethe_node_converter.h
  src/smt/proof_final_callback.cpp
  src/theory/arith/arith_poly_norm.cpp
Labels: minor, simple

#9021 Disable checking on subsolvers when doing sygus rewrite rule synthesis
  src/smt/process_assertions.cpp
  src/smt/set_defaults.cpp
  src/theory/quantifiers/candidate_rewrite_database.cpp
  src/theory/quantifiers/candidate_rewrite_database.h
  src/theory/quantifiers/expr_miner.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/strings/issue8956-1.smt2
  test/regress/cli/regress1/sygus/issue8956-2.smt2
  test/regress/cli/regress1/sygus/issue8976-interp-check.smt2
Labels: minor, simple

#9029 Implementation, parsing, printing for proof components
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  src/printer/ast/ast_printer.cpp
  src/printer/ast/ast_printer.h
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/smt/command.cpp
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
Labels: normal, moderate

#9025 Fix double binding of symbols for named
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/symbol_table.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/dd.define-named.smt2
Labels: normal, simple, do not merge

#9015 Add --check-proof-steps debug option
  src/options/proof_options.toml
  src/smt/proof_final_callback.cpp
  src/smt/proof_post_processor.cpp
  src/smt/set_defaults.cpp
  src/theory/builtin/proof_checker.cpp
Labels: normal, moderate

#9030 Add Proof components to the API
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/jni/solver.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/smt/command.cpp
  src/smt/command.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/proof-components.smt2
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
Labels: normal, moderate

#8969 Implement TheoryBags::computeCareGraph
  src/expr/node_trie.cpp
  src/expr/node_trie.h
  src/theory/bags/theory_bags.cpp
  src/theory/bags/theory_bags.h
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets_private.cpp
Labels: normal, moderate

#9031 Do not print surrounding parentheses around external proof formats
  src/smt/solver_engine.cpp
Labels: major, simple

#9032 Disable checking for solution filter subsolvers
  src/theory/quantifiers/expr_miner.cpp
  src/theory/quantifiers/expr_miner.h
  src/theory/quantifiers/query_generator.cpp
  src/theory/quantifiers/query_generator_sample_sat.cpp
  src/theory/quantifiers/solution_filter.cpp
  src/theory/quantifiers/solution_filter.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/abduction/multiple-get-abduct-uc.smt2
Labels: normal, simple

#9033 Simplify interplay of SMT Solver and preprocessor
  src/smt/assertions.cpp
  src/smt/assertions.h
  src/smt/preprocessor.cpp
  src/smt/process_assertions.cpp
  src/smt/smt_solver.cpp
  src/smt/smt_solver.h
  src/smt/solver_engine.cpp
Labels: normal, moderate

#9036 Disable lfsc on proof output regression
  test/regress/cli/regress0/proofs/proof-components.smt2
Labels: major, simple

#9039 Update sygus_interpol.h class documentation
  src/theory/quantifiers/sygus/sygus_interpol.h
Labels: minor

#9046 [FP] Address `// Removed` comments
  src/theory/fp/theory_fp.cpp
Labels: minor, simple

#9048 bv: Refactor BitVector interface.
  src/util/bitvector.cpp
  src/util/bitvector.h
  src/util/floatingpoint_literal_symfpu_traits.cpp
  test/unit/util/bitvector_black.cpp
Labels: normal, simple, do not merge

#9045 [CMake] Minor updates related to build configs
  CMakeLists.txt
  configure.sh
Labels: minor, simple

#9049 bv: Use PairHashFunction to combine hash values.
  src/util/bitvector.cpp
Labels: normal, simple

#9026 Finite field (really prime field) utility class
  src/util/CMakeLists.txt
  src/util/finite_field.cpp
  src/util/finite_field.h
  src/util/integer_cln_imp.cpp
  src/util/integer_cln_imp.h
  src/util/integer_gmp_imp.cpp
  src/util/integer_gmp_imp.h
Labels: normal, moderate

#9061 Use assertions instead of CheckArgument in node_manager_template.
  src/expr/node_manager_template.cpp
  src/expr/node_manager_template.h
Labels: normal, simple

#9058 [CMake] Use `DOWNLOAD_EXTRACT_TIMESTAMP`
  CMakeLists.txt
Labels: minor, simple

#9055 [FP] Do not attempt to word blast within closures
  src/theory/fp/fp_word_blaster.cpp
  src/theory/fp/theory_fp.cpp
  src/theory/theory_engine.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/fp/fp-set-comprehension-basic.smt2
  test/regress/cli/regress0/fp/proj-issue477-fp-set-comprehension.smt2
  test/regress/cli/regress0/fp/proj-issue509-fp-set-comprehension.smt2
Labels: normal, moderate

#9037 Decouple context management from SolverEngineState
  src/CMakeLists.txt
  src/smt/context_manager.cpp
  src/smt/context_manager.h
  src/smt/quant_elim_solver.cpp
  src/smt/quant_elim_solver.h
  src/smt/smt_solver.cpp
  src/smt/smt_solver.h
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  src/smt/solver_engine_state.cpp
  src/smt/solver_engine_state.h
  src/smt/sygus_solver.cpp
Labels: normal, moderate

#9072 Disable LFSC tester on regression that uses sets
  test/regress/cli/regress0/fp/proj-issue509-fp-set-comprehension.smt2
Labels: major, simple

#9073 proof: Fix typo: (P|p)roccess -> (P|p)rocess.
  src/parser/tptp/Tptp.g
  src/proof/lfsc/lfsc_post_processor.cpp
  src/prop/proof_cnf_stream.cpp
  src/prop/proof_cnf_stream.h
  src/prop/proof_post_processor.cpp
  src/prop/proof_post_processor.h
  src/prop/prop_proof_manager.cpp
  src/prop/prop_proof_manager.h
  src/prop/sat_proof_manager.h
  src/smt/proof_manager.cpp
  src/smt/proof_manager.h
  src/smt/proof_post_processor.cpp
  src/smt/proof_post_processor.h
  src/theory/arith/linear/attempt_solution_simplex.h
  src/theory/arith/linear/dio_solver.h
  src/theory/arith/linear/dual_simplex.h
  src/theory/arith/linear/fc_simplex.h
  src/theory/arith/linear/simplex.h
  src/theory/arith/linear/soi_simplex.h
  src/theory/uf/eq_proof.cpp
Labels: normal, simple

#9066 Use assertions instead of (Pretty)CheckArgument in util.
  src/util/cardinality.cpp
  src/util/divisible.cpp
  src/util/result.cpp
  src/util/uninterpreted_sort_value.cpp
  test/unit/util/cardinality_black.cpp
Labels: normal, simple

#9065 Use assertions instead of (Pretty)CheckArgument in expr and smt.
  src/api/cpp/cvc5.cpp
  src/expr/array_store_all.cpp
  src/expr/codatatype_bound_variable.cpp
  src/expr/mkexpr
  src/smt/command.cpp
  test/unit/api/cpp/term_black.cpp
  test/unit/api/java/TermTest.java
  test/unit/api/python/test_term.py
  test/unit/util/array_store_all_white.cpp
Labels: normal, simple

#9028 Fix for API guarding of double use of DatatypeDecl
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_checks.h
  src/expr/node_manager_template.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
Labels: normal, moderate

#9068 Fix case for block model literals mode
  src/smt/model_blocker.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/issue9057-block-m-lit.smt2
Labels: normal, simple

#9064 Use assertions instead of (Pretty)CheckArgument in symbol_(table|manager).
  src/parser/api/cpp/symbol_manager.cpp
  src/parser/symbol_table.cpp
Labels: normal, simple

#9074 api: Move well-foundedness guard of DT from parser to API.
  src/api/cpp/cvc5.cpp
  src/parser/parser.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/non_well_founded_dt.smt2
  test/regress/cli/regress0/parser/non_well_founded_dts.smt2
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
Labels: normal, simple

#9062 Use assertions instead of (Pretty)CheckArgument in integer_*_imp.
  src/util/integer_cln_imp.cpp
  src/util/integer_gmp_imp.cpp
  test/unit/util/integer_black.cpp
Labels: normal, simple

#9075 Fix typo in node_manager_template.cpp.
  src/expr/node_manager_template.cpp
Labels: normal, simple

#9083 unit: Fix integer_black unit tests.
  test/unit/util/integer_black.cpp
Labels: major, simple

#9081 [proofs] Fix eqproof conversion
  src/theory/uf/eq_proof.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/proj-issue528-ufpfchecker.smt2
Labels: normal, simple

#9077 Enable `dump` tester by default
  test/regress/cli/run_regression.py
Labels: minor, simple

#9080 Simplify initialization of check model utility
  src/smt/solver_engine.cpp
Labels: minor, simple

#9012 Add instantiation match to fmf utility
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/quantifiers/fmf/model_builder.cpp
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/quant_rep_bound_ext.cpp
  src/theory/quantifiers/quant_rep_bound_ext.h
Labels: minor, simple

#9022 Simplify code for generating E-matching triggers from pattern terms
  src/theory/quantifiers/ematching/inst_strategy_e_matching.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching.h
Labels: normal, moderate

#9084 bv: Change sort of reduction operators to (_ BitVec 1).
  NEWS.md
  src/theory/bv/kinds
  src/theory/bv/theory_bv_rewrite_rules_operator_elimination.h
  src/theory/bv/theory_bv_rewriter.cpp
  src/theory/bv/theory_bv_type_rules.cpp
  src/theory/bv/theory_bv_type_rules.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/bv/redand.smt2
  test/regress/cli/regress0/bv/redor.smt2
Labels: normal, simple

#9087 Set re-inter mode to none by default
  src/options/strings_options.toml
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/strings/norn-re-inter-none.smt2
  test/regress/cli/regress1/strings/re-inter-stack-ovf.smt2
Labels: normal, simple

#9069 [Strings] Fix skeletons generated for sequences
  src/theory/strings/theory_strings.cpp
Labels: major, simple

#9088 test: Require no-competition from expectedly failing DT parser tests.
  test/regress/cli/regress0/parser/non_well_founded_dt.smt2
  test/regress/cli/regress0/parser/non_well_founded_dts.smt2
Labels: major, simple

#9011 Add basic utilities for instantiation evaluation
  src/CMakeLists.txt
  src/theory/quantifiers/ieval/free_var_info.cpp
  src/theory/quantifiers/ieval/free_var_info.h
  src/theory/quantifiers/ieval/pattern_term_info.cpp
  src/theory/quantifiers/ieval/pattern_term_info.h
  src/theory/quantifiers/ieval/quant_info.cpp
  src/theory/quantifiers/ieval/quant_info.h
  src/theory/quantifiers/ieval/state.cpp
  src/theory/quantifiers/ieval/state.h
  src/theory/quantifiers/ieval/term_evaluator.cpp
  src/theory/quantifiers/ieval/term_evaluator.h
Labels: normal, moderate

#9090 Remove infrastructure for `Debug()`
  src/base/CMakeLists.txt
  src/base/collect_tags.py
  src/base/configuration.cpp
  src/base/configuration.h
  src/main/driver_unified.cpp
  src/options/base_options.toml
  src/options/main_options.toml
  src/options/options_handler.cpp
  src/options/options_handler.h
Labels: normal, simple

#9089 Add debug option to print the grammar source of sygus terms
  src/CMakeLists.txt
  src/options/base_options.toml
  src/theory/quantifiers/sygus/print_sygus_to_builtin.cpp
  src/theory/quantifiers/sygus/print_sygus_to_builtin.h
  src/theory/quantifiers/sygus/sygus_grammar_norm.cpp
  src/theory/quantifiers/sygus/sygus_grammar_norm.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/sygus/print-sygus-gterm.sy
Labels: normal, moderate

#9093 api: Add getVersion().
  NEWS.md
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/jni/solver.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
Labels: normal, simple

#9094 Add debug output -o lemmas
  src/options/base_options.toml
  src/prop/prop_engine.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/printer/deep-restart-output.smt2
  test/regress/cli/regress0/printer/print_sat_lemmas.smt2
Labels: normal, simple

#9096 Move arithmetic-bitvector conversions to the UF theory
  NEWS.md
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_rewriter.h
  src/theory/arith/kinds
  src/theory/arith/linear/normal_form.h
  src/theory/arith/operator_elim.cpp
  src/theory/arith/theory_arith_type_rules.cpp
  src/theory/arith/theory_arith_type_rules.h
  src/theory/uf/kinds
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf.h
  src/theory/uf/theory_uf_rewriter.cpp
  src/theory/uf/theory_uf_rewriter.h
  src/theory/uf/theory_uf_type_rules.cpp
  src/theory/uf/theory_uf_type_rules.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/bv/bv2nat-ground-c.smt2
  test/regress/cli/regress0/bv/issue3621.smt2
  test/regress/cli/regress0/bv/issue5396.smt2
  test/regress/cli/regress0/parser/bv_nat.smt2
  test/regress/cli/regress1/bv/issue3776.smt2
Labels: normal, moderate

#9095 Fix unsoudness with bag disequality inference rule
  src/theory/bags/inference_generator.cpp
  src/theory/bags/inference_generator.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/bags/fold3.smt2
Labels: normal, simple
