Repository cvc5/cvc5, pull requests merged in 2023-11, with the labels that each got.

#10134 Add is_singleton rewrite
  src/theory/sets/theory_sets_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/sets/proj-issue668.smt2
Labels: minor, simple

#10135 Fix initial sign lemma for sine
  src/smt/proof_manager.cpp
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/arith/operator_elim.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arith/issue9131-inverse-of-int.smt2
  test/regress/cli/regress1/nl/proj-issue667-init-bound.smt2
Labels: normal, simple

#10076 Add support for `get-timeout-core-assuming`
  NEWS.md
  include/cvc5/cvc5.h
  src/api/cpp/cvc5.cpp
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/jni/solver.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/parser/commands.cpp
  src/parser/commands.h
  src/parser/smt2/smt2_cmd_parser.cpp
  src/parser/tokens.cpp
  src/parser/tokens.h
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  src/smt/timeout_core_manager.cpp
  src/smt/timeout_core_manager.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/timeout_core_soft.smt2
  test/regress/cli/regress1/timeout_core_soft_simple.smt2
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
Labels: normal, moderate

#10142 Another fix for arithmetic equality status
  src/theory/arith/arith_subs.cpp
  src/theory/arith/theory_arith.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/nl/issue10139-iand.smt2
Labels: normal, simple

#10137 Fix behaviour and API tests for proofs
  src/api/cpp/cvc5.cpp
  test/unit/api/cpp/proof_black.cpp
  test/unit/api/cpp/types_black.cpp
  test/unit/api/java/UncoveredTest.cpp
  test/unit/api/python/test_uncovered.cpp
Labels: simple

#10141 Add conflict, unsoundness and negation tracking to assertion pipeline
  src/preprocessing/assertion_pipeline.cpp
  src/preprocessing/assertion_pipeline.h
  src/preprocessing/passes/apply_substs.cpp
  src/preprocessing/passes/bool_to_bv.cpp
  src/preprocessing/passes/bv_gauss.cpp
  src/preprocessing/passes/bv_to_bool.cpp
  src/preprocessing/passes/extended_rewriter_pass.cpp
  src/preprocessing/passes/foreign_theory_rewrite.cpp
  src/preprocessing/passes/global_negate.cpp
  src/preprocessing/passes/int_to_bv.cpp
  src/preprocessing/passes/ite_simp.cpp
  src/preprocessing/passes/learned_rewrite.cpp
  src/preprocessing/passes/miplib_trick.cpp
  src/preprocessing/passes/non_clausal_simp.cpp
  src/preprocessing/passes/real_to_int.cpp
  src/preprocessing/passes/rewrite.cpp
  src/preprocessing/passes/strings_eager_pp.cpp
  src/smt/process_assertions.cpp
  src/smt/smt_driver.cpp
  src/smt/smt_solver.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/preprocess/real-as-int-unk.smt2
  test/unit/api/cpp/result_black.cpp
  test/unit/api/java/ResultTest.java
  test/unit/api/python/test_result.py
Labels: minor, moderate

#10143 [proof-new] Fix slt-eliminate to use bvshl
  src/theory/bv/rewrites
Labels: bug, minor, simple

#10146 Remove toCmd
  include/cvc5/cvc5_parser.h
  src/api/cpp/cvc5_parser.cpp
  src/main/command_executor.cpp
  src/main/interactive_shell.cpp
  src/main/portfolio_driver.cpp
Labels: normal, simple

#10150 Fix missing case of terminating due to conflict in preprocessing
  src/preprocessing/assertion_pipeline.cpp
  src/preprocessing/passes/static_rewrite.cpp
  src/preprocessing/passes/theory_preprocess.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/preprocess/issue10148.smt2
  test/regress/cli/regress0/preprocess/proj-issue678.smt2
  test/regress/cli/regress0/preprocess/proj-issue679.smt2
  test/regress/cli/regress0/preprocess/proj-issue681.smt2
  test/regress/cli/regress0/preprocess/proj-issue683.smt2
  test/regress/cli/regress0/preprocess/proj-issue684.smt2
Labels: major, simple

#10149 Use rewrite again full for pow with const
  src/theory/arith/arith_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/nl/issue10145-ir-pow.smt2
Labels: minor, simple

#10152 Fix global negate for true input
  src/preprocessing/passes/global_negate.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/preprocess/proj-issue685-gn.smt2
Labels: minor, simple

#10151 Remove old omt infrastructure
  src/CMakeLists.txt
  src/omt/bitvector_optimizer.cpp
  src/omt/bitvector_optimizer.h
  src/omt/integer_optimizer.cpp
  src/omt/integer_optimizer.h
  src/omt/omt_optimizer.cpp
  src/omt/omt_optimizer.h
  src/smt/optimization_solver.cpp
  src/smt/optimization_solver.h
  test/unit/theory/CMakeLists.txt
  test/unit/theory/theory_bv_opt_white.cpp
  test/unit/theory/theory_int_opt_white.cpp
  test/unit/theory/theory_opt_multigoal_white.cpp
Labels: minor, simple

#10155 Refactor pattern selection utility
  src/theory/quantifiers/ematching/inst_strategy_e_matching_user.cpp
  src/theory/quantifiers/ematching/pattern_term_selector.cpp
  src/theory/quantifiers/ematching/pattern_term_selector.h
Labels: normal, simple

#10123 Improve subproof merging in proof node updater
  src/proof/proof_node_updater.cpp
Labels: normal, simple

#10129 Improve FF utility class
  src/printer/smt2/smt2_printer.cpp
  src/util/finite_field_value.cpp
  src/util/finite_field_value.h
Labels: normal, moderate

#10133 Refactor trusted and macro proof rules
  include/cvc5/cvc5_proof_rule.h
  src/CMakeLists.txt
  src/api/cpp/cvc5_proof_rule.cpp
  src/preprocessing/assertion_pipeline.cpp
  src/preprocessing/passes/non_clausal_simp.cpp
  src/proof/alethe/alethe_post_processor.cpp
  src/proof/conv_proof_generator.cpp
  src/proof/conv_proof_generator.h
  src/proof/dot/dot_printer.cpp
  src/proof/dot/dot_printer.h
  src/proof/lazy_proof.cpp
  src/proof/lazy_proof.h
  src/proof/proof.cpp
  src/proof/proof.h
  src/proof/proof_node_manager.cpp
  src/proof/proof_node_manager.h
  src/proof/proof_node_to_sexpr.cpp
  src/proof/proof_node_to_sexpr.h
  src/proof/proof_step_buffer.cpp
  src/proof/proof_step_buffer.h
  src/proof/trust_id.cpp
  src/proof/trust_id.h
  src/prop/proof_cnf_stream.cpp
  src/prop/prop_engine.cpp
  src/smt/preprocess_proof_generator.cpp
  src/smt/preprocess_proof_generator.h
  src/smt/proof_final_callback.cpp
  src/smt/proof_final_callback.h
  src/smt/proof_manager.cpp
  src/smt/proof_post_processor.cpp
  src/smt/term_formula_removal.cpp
  src/smt/witness_form.cpp
  src/theory/arith/linear/constraint.cpp
  src/theory/arith/operator_elim.cpp
  src/theory/arith/pp_rewrite_eq.cpp
  src/theory/arrays/inference_manager.cpp
  src/theory/arrays/theory_arrays.cpp
  src/theory/builtin/proof_checker.cpp
  src/theory/bv/bitblast/bitblast_proof_generator.cpp
  src/theory/bv/proof_checker.cpp
  src/theory/datatypes/infer_proof_cons.cpp
  src/theory/datatypes/infer_proof_cons.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/proof_checker.cpp
  src/theory/rewriter.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/sep/theory_sep.h
  src/theory/sets/inference_manager.cpp
  src/theory/sets/inference_manager.h
  src/theory/strings/infer_proof_cons.cpp
  src/theory/strings/infer_proof_cons.h
  src/theory/strings/proof_checker.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_inference_manager.cpp
  src/theory/theory_preprocessor.cpp
  src/theory/theory_preprocessor.h
  src/theory/trust_substitutions.cpp
  src/theory/trust_substitutions.h
  src/theory/uf/eq_proof.cpp
Labels: normal, moderate

#10165 Do not apply preprocessing pass for TheorySep unless enabled
  src/theory/sep/theory_sep.cpp
Labels: normal, simple

#10157 Add kind for ff.bitsum
  include/cvc5/cvc5_kind.h
  src/parser/smt2/smt2_state.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/ff/kinds
Labels: normal, simple

#10170 Fix for ALF documentation
  docs/proofs/output_alf.rst
Labels: normal, simple

#10158 FieldObj class & CoCoA utilities
  src/CMakeLists.txt
  src/theory/ff/cocoa_util.cpp
  src/theory/ff/cocoa_util.h
  src/theory/ff/sub_theory.cpp
  src/theory/ff/sub_theory.h
  src/theory/ff/util.cpp
  src/theory/ff/util.h
Labels: normal, simple

#10167 Fixes for theory combination + HO
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/theory_model_builder.cpp
  src/theory/uf/ho_extension.cpp
  src/theory/uf/theory_uf.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/ho/SYO372.smt2
  test/regress/cli/regress0/ho/dd.syo009.smt2
  test/regress/cli/regress0/ho/dd.syo372-finite-ho-ext.smt2
Labels: normal, moderate

#10180 Add fixed project issues
  test/api/cpp/CMakeLists.txt
  test/api/cpp/proj-issue646.cpp
  test/api/cpp/proj-issue652.cpp
  test/api/cpp/proj-issue666.cpp
Labels: minor, simple
