Repository cvc5/cvc5, pull requests merged in 2023-02, with the labels that each got.

#9471 Expose sygus assumptions and constraints to the api
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/jni/solver.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  src/smt/sygus_solver.cpp
  src/smt/sygus_solver.h
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
Labels: normal, simple

#9467 Remove unused array kinds
  src/printer/smt2/smt2_printer.cpp
  src/theory/arrays/kinds
  src/theory/arrays/theory_arrays_type_rules.cpp
  src/theory/arrays/theory_arrays_type_rules.h
Labels: minor, simple

#9390 Eliminate capture avoiding substitution
  src/expr/CMakeLists.txt
  src/expr/annotation_elim_node_converter.h
  src/expr/elim_shadow_converter.cpp
  src/expr/elim_shadow_converter.h
  src/expr/node_algorithm.cpp
  src/expr/node_algorithm.h
  src/theory/builtin/theory_builtin_rewriter.cpp
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/sets/theory_sets_rewriter.cpp
  src/theory/sets/theory_sets_rewriter.h
  src/theory/strings/arith_entail.cpp
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf_rewriter.cpp
  src/theory/uf/theory_uf_rewriter.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/ho/dd.shadowing-defs.smt2
Labels: minor, moderate

#9481 Fix rewrite for pow to pow2
  src/theory/arith/arith_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/nl/issue9480-pow-pow2.smt2
Labels: normal, simple

#9464 Do not eliminate partial arithmetic operators in sygus
  src/theory/datatypes/sygus_datatype_utils.cpp
Labels: minor, simple

#9452 Add basic definition of rewrite proof rules
  src/rewriter/CMakeLists.txt
  src/rewriter/rewrite_proof_rule.cpp
  src/rewriter/rewrite_proof_rule.h
Labels: minor, moderate

#9490 Add evaluators for bv to arith conversions
  src/theory/evaluator.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/sygus/bv2nat.sy
  test/regress/cli/regress1/sygus/int2bv.sy
Labels: normal, simple

#9488 Minor cleaning of symbol table
  src/parser/symbol_table.cpp
Labels: minor, simple

#9475 Add policy to CNF stream to be notified when Boolean variables are asserted
  src/prop/cnf_stream.cpp
  src/prop/cnf_stream.h
  src/prop/theory_preregistrar.cpp
  src/prop/theory_preregistrar.h
  src/prop/theory_proxy.cpp
Labels: normal, moderate

#9489 Do not use RANs in MBQI
  src/theory/quantifiers/inst_strategy_mbqi.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/quantifiers/issue9477-mbqi-ran.smt2
Labels: normal, simple

#9487 Catch failures when binding terms
  src/parser/api/cpp/command.cpp
  src/parser/api/cpp/command.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/double-bind.smt2
Labels: normal, simple

#9454 Implement term parsing in Flex smt2 parser
  src/parser/smt2/smt2_term_parser.cpp
  src/parser/smt2/smt2_term_parser.h
Labels: normal, complex

#9458 [proof] [alethe] Fix resolution post update when not printing pivots
  src/proof/alethe/alethe_post_processor.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/alethe-res-need-or-step.smt2
Labels: normal, simple

#9432 Avoid spurious equality engine trigger predicates
  src/theory/arrays/theory_arrays.cpp
  src/theory/bags/theory_bags.cpp
  src/theory/bv/theory_bv.cpp
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/ff/theory_ff.cpp
  src/theory/fp/theory_fp.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/shared_terms_database.cpp
  src/theory/shared_terms_database.h
  src/theory/strings/term_registry.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/theory_state.cpp
  src/theory/theory_state.h
  src/theory/uf/theory_uf.cpp
  src/theory/valuation.cpp
  src/theory/valuation.h
Labels: normal, moderate

#9496 Make flex parser available via option
  src/options/parser_options.toml
  src/parser/flex_parser.cpp
  src/parser/flex_parser.h
  src/parser/input_parser.cpp
  src/parser/input_parser.h
  src/parser/smt2/smt2_input.cpp
Labels: normal, simple

#9317 Add theory engine modules infrastructure
  src/CMakeLists.txt
  src/theory/engine_output_channel.cpp
  src/theory/engine_output_channel.h
  src/theory/partition_generator.cpp
  src/theory/partition_generator.h
  src/theory/relevance_manager.cpp
  src/theory/relevance_manager.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/theory_engine_module.cpp
  src/theory/theory_engine_module.h
  src/theory/theory_id.cpp
  src/theory/theory_id.h
Labels: normal, moderate

#9501 fp: Get rid of unnecessary configuration query.
  src/theory/fp/theory_fp.cpp
Labels: normal, simple

#9502 context: Use uint32_t for context level.
  src/context/context.cpp
  src/context/context.h
  src/prop/cadical.cpp
  src/prop/cadical.h
  src/prop/cryptominisat.cpp
  src/prop/cryptominisat.h
  src/prop/kissat.cpp
  src/prop/kissat.h
  src/prop/minisat/core/Solver.cc
  src/prop/minisat/minisat.cpp
  src/prop/minisat/minisat.h
  src/prop/proof_cnf_stream.cpp
  src/prop/proof_cnf_stream.h
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/sat_proof_manager.cpp
  src/prop/sat_solver.h
  src/smt/context_manager.cpp
  src/smt/context_manager.h
  src/theory/arith/linear/theory_arith_private.cpp
Labels: simple

#9498 Improvements to user-facing parser API
  src/main/driver_unified.cpp
  src/main/interactive_shell.cpp
  src/main/portfolio_driver.h
  src/parser/CMakeLists.txt
  src/parser/api/cpp/command.h
  src/parser/api/cpp/input_parser.cpp
  src/parser/api/cpp/input_parser.h
  src/parser/api/cpp/symbol_manager.h
Labels: normal, simple

#9508 CnfStream: Reorder class to comply to code guidelines.
  src/prop/cnf_stream.h
Labels: normal, simple

#9512 theory engine: Add resource limit check point.
  src/prop/cadical.cpp
  src/theory/theory_engine.cpp
Labels: major, simple

#9507 Purify terms in branch and bound lemmas when necessary
  src/theory/arith/branch_and_bound.cpp
  src/theory/arith/branch_and_bound.h
  src/theory/arith/linear/theory_arith_private.cpp
  src/theory/arith/linear/theory_arith_private.h
  src/theory/arith/theory_arith.cpp
Labels: major, moderate

#9513 theory engine: Add more resource limit checks.
  src/theory/theory_engine.cpp
Labels: major, simple

#9497 Add new type checking algorithm
  src/expr/node_manager_template.cpp
  src/expr/type_checker.h
  src/expr/type_checker_template.cpp
Labels: normal, moderate

#9521 Rename CDCLTSatSolverInterface to CDCLTSatSolver.
  src/decision/decision_engine.cpp
  src/decision/decision_engine.h
  src/decision/justification_strategy.cpp
  src/decision/justification_strategy.h
  src/decision/justify_cache.cpp
  src/decision/justify_cache.h
  src/prop/minisat/minisat.h
  src/prop/prop_engine.h
  src/prop/prop_proof_manager.cpp
  src/prop/prop_proof_manager.h
  src/prop/sat_solver.h
  src/prop/theory_preregistrar.cpp
  src/prop/theory_preregistrar.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
Labels: normal, simple

#9522 SatSolverFactory: Return CDCLTSatSolver* instead of MinisatSatSolver*.
  src/prop/sat_solver_factory.cpp
  src/prop/sat_solver_factory.h
Labels: normal, simple

#9514 minisat: Move preregistration handling of new sat variables to theory level.
  src/prop/cadical.cpp
  src/prop/cadical.h
  src/prop/cnf_stream.cpp
  src/prop/cryptominisat.cpp
  src/prop/cryptominisat.h
  src/prop/kissat.cpp
  src/prop/kissat.h
  src/prop/minisat/core/Solver.cc
  src/prop/minisat/core/Solver.h
  src/prop/minisat/minisat.cpp
  src/prop/minisat/minisat.h
  src/prop/minisat/simp/SimpSolver.cc
  src/prop/minisat/simp/SimpSolver.h
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/sat_solver.h
  src/prop/theory_preregistrar.cpp
  src/prop/theory_preregistrar.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
  test/unit/prop/cnf_stream_white.cpp
Labels: normal, moderate

#9524 CDCLTSatSolver: Get rid of unused properExplanation().
  src/prop/minisat/minisat.cpp
  src/prop/minisat/minisat.h
  src/prop/prop_engine.cpp
  src/prop/sat_solver.h
Labels: normal, simple

#9523 prop: Manage decision levels of theory literals in theory proxy.
  src/prop/minisat/minisat.cpp
  src/prop/minisat/minisat.h
  src/prop/prop_engine.cpp
  src/prop/sat_solver.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
Labels: normal, simple

#9525 theory preregistrar: Fix ASAN error in notifyBacktrack().
  src/prop/theory_preregistrar.cpp
Labels: major, simple

#9520 Fixes for proof-annotate
  src/proof/eager_proof_generator.cpp
  src/proof/eager_proof_generator.h
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
Labels: minor, simple

#9509 Notify theory engine modules of conflicts
  src/options/smt_options.toml
  src/theory/theory_engine.cpp
Labels: normal, simple

#9529 More rewrites for conversion functions
  src/theory/uf/theory_uf_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/bv/issue9517-conv-arith-deq.smt2
Labels: normal, moderate

#9526 sat solver factory: Fix compiler warning.
  src/prop/sat_solver_factory.cpp
Labels: normal, simple

#9495 Fix printing for APPLY_UF with non-variable operators
  src/printer/smt2/smt2_printer.cpp
Labels: normal, simple

#9491 Add rewrite database term processor
  src/rewriter/CMakeLists.txt
  src/rewriter/rewrite_db_term_process.cpp
  src/rewriter/rewrite_db_term_process.h
Labels: normal, simple

#9533 Fix printing of higher-order APPLY_UF in LFSC terms
  src/proof/lfsc/lfsc_node_converter.cpp
  src/proof/lfsc/lfsc_node_converter.h
Labels: major, moderate
