Repository cvc5/cvc5, pull requests merged in 2023-01, with the labels that each got.

#9374 Refactor extended function solver
  src/theory/strings/extf_solver.cpp
  src/theory/strings/extf_solver.h
  src/theory/strings/strategy.cpp
  src/theory/strings/strategy.h
  src/theory/strings/theory_strings.cpp
Labels: normal, moderate

#9355 Bind declarations and definitions only when commands are invoked
  src/main/command_executor.cpp
  src/main/driver_unified.cpp
  src/main/interactive_shell.cpp
  src/main/interactive_shell.h
  src/parser/api/cpp/command.cpp
  src/parser/api/cpp/symbol_manager.cpp
  src/parser/api/cpp/symbol_manager.h
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/Smt2.g
  test/api/cpp/ouroborous.cpp
  test/unit/main/interactive_shell_black.cpp
  test/unit/parser/parser_black.cpp
Labels: normal, moderate

#9357 Rename Theory::getModelValue to Theory::getCandidateModelValue
  src/theory/arith/linear/theory_arith_private.cpp
  src/theory/arith/linear/theory_arith_private.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/arrays/theory_arrays.cpp
  src/theory/bags/theory_bags.cpp
  src/theory/bags/theory_bags.h
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp.h
  src/theory/sets/cardinality_extension.cpp
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
  src/theory/strings/model_cons_default.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/valuation.cpp
  src/theory/valuation.h
Labels: minor, simple

#9372 Separate propagation and lemma phases in core strings solver
  src/theory/incomplete_id.cpp
  src/theory/incomplete_id.h
  src/theory/strings/core_solver.cpp
  src/theory/strings/core_solver.h
  src/theory/strings/infer_info.h
  src/theory/strings/inference_manager.cpp
  src/theory/strings/strategy.cpp
  src/theory/strings/strategy.h
  src/theory/strings/theory_strings.cpp
Labels: normal, moderate

#9376 Add rewrite based on regular expression inclusion
  src/theory/strings/rewrites.cpp
  src/theory/strings/rewrites.h
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/sequences_rewriter.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/strings/re-mem-include-rewrite.smt2
Labels: normal, moderate

#9378 Fix regression for nightlies
  test/regress/cli/regress0/parser/issue5163.smt2
Labels: major, simple

#9358 doc: ff examples
  docs/examples/examples.rst
  docs/examples/finite_field.rst
  examples/api/smtlib/finite_field.smt2
Labels: minor, simple

#9386 Add base flex lexer and token definitions
  src/parser/CMakeLists.txt
  src/parser/flex_lexer.cpp
  src/parser/flex_lexer.h
  src/parser/tokens.cpp
  src/parser/tokens.h
Labels: normal, moderate

#9389 Add minimization for string prefix conflicts
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/strings/eager_solver.cpp
  src/theory/strings/inference_manager.cpp
  src/theory/strings/inference_manager.h
  src/theory/strings/solver_state.cpp
  src/theory/strings/solver_state.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/strings/prefix-min-conflict.smt2
Labels: normal, moderate

#9383 Add new utility methods to regular expression solver
  src/theory/strings/regexp_solver.cpp
  src/theory/strings/regexp_solver.h
Labels: normal, moderate

#9398 Disable eager evaluation in BV by default
  src/options/bv_options.toml
Labels: normal, simple

#9392 Add base class for Flex parser
  src/parser/CMakeLists.txt
  src/parser/flex_parser.cpp
  src/parser/flex_parser.h
Labels: normal, moderate

#9399 Add missing print for inference id
  src/theory/inference_id.cpp
Labels: minor, simple

#9400 ci: Use GitHub mirror for GMP package.
  cmake/FindGMP.cmake
Labels: major, simple

#9397 Remove subtyping from results of simplify
  src/smt/solver_engine.cpp
Labels: minor, simple

#9396 Introduce more regular expression utility methods
  src/theory/ext_theory.cpp
  src/theory/ext_theory.h
  src/theory/strings/regexp_solver.cpp
  src/theory/strings/regexp_solver.h
Labels: normal, moderate

#9298 Add proof rule BETA_REDUCE
  src/proof/proof_rule.cpp
  src/proof/proof_rule.h
  src/theory/uf/proof_checker.cpp
Labels: normal, simple

#9373 Refactor the regular expression solver
  src/theory/strings/regexp_solver.cpp
  src/theory/strings/regexp_solver.h
  src/theory/strings/strategy.cpp
  src/theory/strings/theory_strings.cpp
Labels: normal, moderate

#9280 [proofs] [cnf] Add utility for retrieving clauses from input/lemmas
  src/prop/proof_cnf_stream.cpp
  src/prop/proof_cnf_stream.h
Labels: normal, simple

#9308 Do not print nested annotations in quantifier bodies
  src/printer/smt2/smt2_printer.cpp
  test/regress/cli/regress0/quantifiers/double-pattern.smt2
  test/regress/cli/regress1/quantifiers/pool-example.smt2
Labels: normal, simple

#9309 Fix pattern printing for match terms
  src/printer/smt2/smt2_printer.cpp
Labels: normal, simple

#9401 Lazily resolve symbol table lookups for testers and updaters
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2.h
  test/regress/cli/regress0/issue1063-overloading-dt-cons.smt2
Labels: normal, moderate

#9320 Rename method in synth engine
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus/synth_engine.h
  src/theory/quantifiers_engine.cpp
Labels: minor, simple

#9387 Minor fixes for quantifiers rewriter
  src/theory/quantifiers/quantifiers_rewriter.cpp
Labels: minor, simple

#9295 [proofs] [alethe] Use let binder in Alethe printer
  src/proof/alethe/alethe_printer.cpp
  src/proof/alethe/alethe_printer.h
  src/smt/proof_manager.cpp
Labels: normal, moderate

#9299 [proofs] [alethe] Updates to resolution processing
  src/proof/alethe/alethe_post_processor.cpp
  src/proof/alethe/alethe_post_processor.h
  src/proof/alethe/alethe_proof_rule.cpp
  src/proof/alethe/alethe_proof_rule.h
Labels: normal, moderate

#9406 Ensure facts from sequences array solver are rewritten
  src/theory/strings/array_solver.cpp
  src/theory/strings/inference_manager.cpp
Labels: minor, simple

#9405 [proofs] [alethe] Guard loop used only for tracing.
  src/proof/alethe/alethe_printer.cpp
Labels: minor, simple

#9402 Add eager reduction for fixed length RE memberships
  src/theory/strings/term_registry.cpp
Labels: normal, simple

#9410 Introduce Flex SMT2 term parser its basic methods
  src/parser/CMakeLists.txt
  src/parser/smt2/smt2_lexer.h
  src/parser/smt2/smt2_term_parser.cpp
  src/parser/smt2/smt2_term_parser.h
Labels: normal, moderate

#9411 Add LFSC proofs for INSTANTIATE and BETA_REDUCE
  contrib/get-lfsc-checker
  proofs/lfsc/signatures/arith_programs.plf
  proofs/lfsc/signatures/arith_rules.plf
  proofs/lfsc/signatures/boolean_programs.plf
  proofs/lfsc/signatures/nary_programs.plf
  proofs/lfsc/signatures/quantifiers_rules.plf
  proofs/lfsc/signatures/strings_programs.plf
  proofs/lfsc/signatures/strings_rules.plf
  proofs/lfsc/signatures/util_defs.plf
  src/proof/lfsc/lfsc_post_processor.cpp
  src/proof/lfsc/lfsc_printer.cpp
  src/proof/lfsc/lfsc_util.cpp
  src/proof/lfsc/lfsc_util.h
Labels: minor, moderate

#9263 Add infrastructure and API for abstract sorts
  src/CMakeLists.txt
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5.h
  src/api/cpp/cvc5_sort_kind.h
  src/api/java/CMakeLists.txt
  src/api/java/genenums.py.in
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/io/github/cvc5/Sort.java
  src/api/java/jni/solver.cpp
  src/api/java/jni/sort.cpp
  src/api/python/CMakeLists.txt
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/api/python/cvc5_python_base.pyx
  src/expr/node_manager_template.cpp
  src/expr/node_manager_template.h
  src/expr/type_node.cpp
  src/expr/type_node.h
  src/printer/smt2/smt2_printer.cpp
  src/theory/builtin/abstract_type.cpp
  src/theory/builtin/abstract_type.h
  src/theory/builtin/kinds
  test/unit/api/cpp/CMakeLists.txt
  test/unit/api/cpp/api_sort_kind_black.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/cpp/sort_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/java/SortTest.java
  test/unit/api/python/test_solver.py
  test/unit/api/python/test_sort.py
Labels: normal, moderate

#9419 Add Flex parser for SMT2 sorts
  src/parser/smt2/smt2_term_parser.cpp
  src/parser/smt2/smt2_term_parser.h
Labels: normal, moderate

#9418 Add Flex parser for SMT2 symbolic expressions
  src/parser/smt2/smt2_term_parser.cpp
  src/parser/smt2/smt2_term_parser.h
Labels: normal, moderate

#9414 [proofs] Adds option to optimize elaboration of macro resolution steps
  src/CMakeLists.txt
  src/options/proof_options.toml
  src/proof/alethe/alethe_post_processor.cpp
  src/proof/proof_node_algorithm.cpp
  src/proof/proof_node_algorithm.h
  src/proof/resolution_proofs_util.cpp
  src/proof/resolution_proofs_util.h
  src/smt/proof_post_processor.cpp
  src/smt/proof_post_processor.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/issue9393-optResReconstruction-alethebug.smt2
  test/regress/cli/regress0/proofs/other-optResRecons-corner-case.smt2
Labels: normal, moderate

#9424 Add smt2 Flex parser for datatype declarations
  src/parser/smt2/smt2_term_parser.cpp
  src/parser/smt2/smt2_term_parser.h
Labels: normal, moderate

#9409 Introduce class of rewrites eliminating bv2nat and int2bv in inequalities
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_rewriter.h
  src/theory/arith/rewrites.cpp
  src/theory/arith/rewrites.h
  src/theory/bv/theory_bv_rewrite_rules.h
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
  src/theory/bv/theory_bv_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arith-bv-conv-ineq-rewrites.smt2
  test/regress/cli/regress0/bv/bvule-elim-conv.smt2
  test/regress/cli/regress0/bv/issue9415-bv2nat.smt2
  test/regress/cli/regress0/bv/le-elim-conv.smt2
  test/regress/cli/regress0/dd.bad-conv-rewrite.smt2
Labels: normal, moderate

#9423 Add smt2 Flex lexer and Flex dependency
  src/parser/CMakeLists.txt
  src/parser/flex_lexer.cpp
  src/parser/flex_lexer.h
  src/parser/smt2/smt2_lexer.flex
  src/parser/smt2/smt2_lexer.h
Labels: normal, moderate

#9426 Parse SyGuS grammar in Flex parser
  src/parser/smt2/smt2_term_parser.cpp
  src/parser/smt2/smt2_term_parser.h
Labels: normal, moderate

#9433 Factor out some methods from decision engine
  src/CMakeLists.txt
  src/decision/justification_strategy.cpp
  src/decision/justification_strategy.h
  src/decision/justify_cache.cpp
  src/decision/justify_cache.h
  src/expr/node_algorithm.cpp
  src/expr/node_algorithm.h
Labels: normal, moderate

#9412 bv: Add missing rewrites for bvult.
  src/theory/bv/theory_bv_rewrite_rules.h
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
  src/theory/bv/theory_bv_rewriter.cpp
Labels: normal, simple

#9430 Add tests for uncovered API methods for abstract sorts
  test/unit/api/cpp/api_sort_kind_black.cpp
  test/unit/api/java/SortTest.java
  test/unit/api/java/UncoveredTest.cpp
  test/unit/api/python/test_uncovered.cpp
Labels: major, simple

#9416 Add DSL rewrite rule subdirectory
  .github/actions/install-dependencies/action.yml
  src/CMakeLists.txt
  src/rewriter/CMakeLists.txt
  src/rewriter/mkrewrites.py
  src/rewriter/rewrite_db.cpp
  src/rewriter/rewrite_db.h
  src/rewriter/rewrites_template.cpp
  src/rewriter/rewrites_template.h
  src/rewriter/util.py
  src/theory/booleans/rewrites
Labels: normal, moderate

#9431 Fix LFSC side condition for beta reduction
  contrib/get-lfsc-checker
  proofs/lfsc/signatures/quantifiers_rules.plf
Labels: normal, simple

#9429 Add ieval failure with learning option to regressions
  src/theory/quantifiers/ieval/term_evaluator.cpp
  test/regress/cli/regress1/fmf/agree466.smt2
  test/regress/cli/regress1/quantifiers/set8.smt2
  test/regress/cli/regress2/quantifiers/javafe.tc.CheckCompilationUnit.001.smt2
Labels: minor, simple

#9439 Refactor strings preregistration
  src/theory/strings/strings_fmf.cpp
  src/theory/strings/term_registry.cpp
  src/theory/strings/term_registry.h
  src/theory/strings/theory_strings.cpp
Labels: normal, moderate

#9440 Simplify quantifier elimination preprocessing in Sygus solver
  src/expr/node_visitor.h
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/quantifiers/sygus/sygus_process_conj.cpp
  src/theory/quantifiers/sygus/sygus_qe_preproc.cpp
  src/theory/quantifiers/sygus/sygus_qe_preproc.h
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus/synth_engine.h
Labels: normal, simple

#9444 Move sets ppRewrite to extended rewrite
  src/theory/quantifiers/extended_rewrite.cpp
  src/theory/quantifiers/extended_rewrite.h
  src/theory/sets/theory_sets.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/sets/issue9114-sets-card-extr.smt2
Labels: minor, simple

#9441 [dsl] Adding code for the DSL compiler
  src/rewriter/mkrewrites.py
  src/rewriter/node.py
  src/rewriter/parser.py
  src/rewriter/rewrites_template.cpp
  src/rewriter/rule.py
Labels: normal, moderate

#9446 Add theory preregistrar
  src/CMakeLists.txt
  src/options/prop_options.toml
  src/prop/cnf_stream.cpp
  src/prop/cnf_stream.h
  src/prop/registrar.h
  src/prop/theory_preregistrar.cpp
  src/prop/theory_preregistrar.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
  src/theory/bv/bv_solver_bitblast.cpp
Labels: normal, moderate

#9443 Fix theory need check tracking
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
Labels: normal, moderate

#9445 Minor simplification to Minisat theory check
  src/prop/minisat/core/Solver.cc
  src/prop/minisat/core/Solver.h
Labels: minor, simple

#9455 cmake: Use absolute path to *.flex file.
  src/parser/CMakeLists.txt
Labels: major, simple

#9457 Fix ref count issue in evaluation invariance test for multiple functions-to-synthesize
  src/theory/quantifiers/sygus/sygus_invariance.cpp
Labels: normal, simple

#9450 Minor improvement to expansion of REWRITE
  src/smt/proof_post_processor.cpp
Labels: minor, simple

#9434 Include free variables in error messages
  src/api/cpp/cvc5.cpp
  src/smt/solver_engine.cpp
Labels: normal, simple

#9296 [proofs] [alethe] Extend post-processor with Skolem rules
  src/proof/alethe/alethe_post_processor.cpp
  src/proof/alethe/alethe_proof_rule.cpp
  src/proof/alethe/alethe_proof_rule.h
Labels: normal, moderate

#9300 [proofs] [alethe] Improve handling of last proof step
  src/proof/alethe/alethe_post_processor.cpp
  src/proof/alethe/alethe_post_processor.h
Labels: normal, moderate

#9453 Add the smt2 Flex parser
  src/parser/CMakeLists.txt
  src/parser/smt2/smt2_parser.cpp
  src/parser/smt2/smt2_parser.h
Labels: normal, simple

#9462 cmake: Fix flex detection for Apple Silicon homebrew.
  src/parser/CMakeLists.txt
Labels: major, simple

#9461 Add option for eager reduction of positive membership into re concat
  src/options/strings_options.toml
  src/theory/strings/regexp_solver.cpp
  src/theory/strings/regexp_solver.h
  src/theory/strings/strategy.cpp
  src/theory/strings/strategy.h
  src/theory/strings/theory_strings.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/strings/slent-re-pos-eager.smt2
Labels: normal, simple

#9384 Use NFA for regular expression evaluation
  src/CMakeLists.txt
  src/theory/strings/regexp_entail.cpp
  src/theory/strings/regexp_entail.h
  src/theory/strings/regexp_eval.cpp
  src/theory/strings/regexp_eval.h
  src/theory/strings/sequences_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/strings/re-mem-eval-large.smt2
Labels: normal, moderate

#9463 Minor extension to learned-rewrite
  src/preprocessing/passes/learned_rewrite.cpp
  src/preprocessing/passes/learned_rewrite.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/nl/issue9420-ll.smt2
Labels: normal, simple

#9468 cmake: Use older version range format for find_package.
  CMakeLists.txt
  src/api/python/CMakeLists.txt
Labels: major, simple

#9470 cmake: Force Python version for FindPythonInterp and FindPythonLibs.
  CMakeLists.txt
  src/api/python/CMakeLists.txt
  src/rewriter/CMakeLists.txt
Labels: major, simple

#9469 Do not use null sort as dummy for empty set and bag
  src/api/cpp/cvc5.cpp
  src/parser/smt2/smt2.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
Labels: minor, simple

#9466 Pass optional output stream to computeType methods
  src/expr/mkexpr
  src/expr/node_manager_template.cpp
  src/expr/node_manager_template.h
  src/expr/type_checker.h
  src/expr/type_checker_template.cpp
  src/expr/type_checker_util.h
  src/theory/arith/theory_arith_type_rules.cpp
  src/theory/arith/theory_arith_type_rules.h
  src/theory/arrays/theory_arrays_type_rules.cpp
  src/theory/arrays/theory_arrays_type_rules.h
  src/theory/bags/theory_bags_type_rules.cpp
  src/theory/bags/theory_bags_type_rules.h
  src/theory/booleans/theory_bool_type_rules.cpp
  src/theory/booleans/theory_bool_type_rules.h
  src/theory/builtin/theory_builtin_type_rules.cpp
  src/theory/builtin/theory_builtin_type_rules.h
  src/theory/bv/theory_bv_type_rules.cpp
  src/theory/bv/theory_bv_type_rules.h
  src/theory/datatypes/theory_datatypes_type_rules.cpp
  src/theory/datatypes/theory_datatypes_type_rules.h
  src/theory/ff/theory_ff_type_rules.cpp
  src/theory/ff/theory_ff_type_rules.h
  src/theory/fp/theory_fp_type_rules.cpp
  src/theory/fp/theory_fp_type_rules.h
  src/theory/quantifiers/theory_quantifiers_type_rules.cpp
  src/theory/quantifiers/theory_quantifiers_type_rules.h
  src/theory/sep/theory_sep_type_rules.cpp
  src/theory/sep/theory_sep_type_rules.h
  src/theory/sets/theory_sets_type_rules.cpp
  src/theory/sets/theory_sets_type_rules.h
  src/theory/strings/theory_strings_type_rules.cpp
  src/theory/strings/theory_strings_type_rules.h
  src/theory/uf/theory_uf_type_rules.cpp
  src/theory/uf/theory_uf_type_rules.h
Labels: normal, moderate

#9451 Construct the rewrite rule database in ProofManager
  src/smt/proof_manager.cpp
  src/smt/proof_manager.h
Labels: minor, simple

#9449 Add basic rewrite rule reconstruction
  src/options/proof_options.toml
  src/rewriter/CMakeLists.txt
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/rewriter/rewrite_db_proof_cons.cpp
  src/rewriter/rewrite_db_proof_cons.h
  src/smt/proof_post_processor.cpp
  src/smt/proof_post_processor.h
Labels: normal, moderate
