Repository cvc5/cvc5, pull requests merged in 2023-06, with the labels that each got.

#9787 Revert corner case in branch and bound
  src/theory/arith/branch_and_bound.cpp
  src/theory/arith/branch_and_bound.h
Labels: minor, simple

#9756 Add -o sygus-enumerator
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/options/base_options.toml
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/sygus/print-enumerator.sy
Labels: minor, simple, do not merge

#9795 Add new utility methods for sygus
  src/smt/sygus_solver.cpp
  src/smt/sygus_solver.h
  src/theory/datatypes/sygus_datatype_utils.cpp
  src/theory/datatypes/sygus_datatype_utils.h
Labels: minor, simple

#9796 Refactor expression miner interface
  src/options/quantifiers_options.toml
  src/preprocessing/passes/synth_rew_rules.cpp
  src/preprocessing/passes/synth_rew_rules.h
  src/smt/process_assertions.cpp
  src/smt/set_defaults.cpp
  src/theory/datatypes/sygus_extension.cpp
  src/theory/quantifiers/candidate_rewrite_database.cpp
  src/theory/quantifiers/candidate_rewrite_database.h
  src/theory/quantifiers/expr_miner.cpp
  src/theory/quantifiers/expr_miner.h
  src/theory/quantifiers/expr_miner_manager.cpp
  src/theory/quantifiers/expr_miner_manager.h
  src/theory/quantifiers/query_generator.cpp
  src/theory/quantifiers/query_generator.h
  src/theory/quantifiers/query_generator_sample_sat.cpp
  src/theory/quantifiers/query_generator_sample_sat.h
  src/theory/quantifiers/query_generator_unsat.cpp
  src/theory/quantifiers/query_generator_unsat.h
  src/theory/quantifiers/solution_filter.cpp
  src/theory/quantifiers/solution_filter.h
  src/theory/quantifiers/sygus/enum_value_manager.cpp
  src/theory/quantifiers/sygus/rcons_type_info.cpp
  src/theory/quantifiers/sygus/sygus_enumerator_callback.cpp
  src/theory/quantifiers/sygus/sygus_enumerator_callback.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  test/api/cpp/proj-issue445.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/sygus/proj-issue464-rr-option.smt2
  test/regress/cli/regress1/rr-verify/bool-crci.sy
  test/regress/cli/regress1/rr-verify/bv-term-32.sy
  test/regress/cli/regress1/rr-verify/bv-term.sy
  test/regress/cli/regress1/rr-verify/fp-arith.sy
  test/regress/cli/regress1/rr-verify/fp-bool.sy
  test/regress/cli/regress1/rr-verify/string-term.sy
  test/regress/cli/regress1/sygus/issue8216-rr-input-re.smt2
  test/regress/cli/regress1/sygus/issue8956-2.smt2
  test/regress/cli/regress1/sygus/proj-issue541.smt2
  test/regress/cli/regress1/sygus/proj-issue548-srr.smt2
  test/regress/cli/regress1/sygus/proj-issue549-srr.smt2
  test/regress/cli/regress1/sygus/proj-issue553-srr.smt2
  test/regress/cli/regress1/sygus/proj-issue627-srr.smt2
  test/regress/cli/regress2/sygus/qgu-bools.sy
  test/unit/api/cpp/solver_black.cpp
Labels: normal, moderate

#9781 Minor improvements to Sygus `rcons` procedure.
  examples/api/cpp/CMakeLists.txt
  examples/api/cpp/sygus-grammar.cpp
  examples/api/java/CMakeLists.txt
  examples/api/java/SygusGrammar.java
  examples/api/python/CMakeLists.txt
  examples/api/python/sygus-grammar.py
  examples/api/smtlib/sygus-grammar.sy
  include/cvc5/cvc5.h
  src/api/cpp/cvc5.cpp
  src/expr/CMakeLists.txt
  src/expr/sygus_datatype.cpp
  src/expr/sygus_grammar.cpp
  src/expr/sygus_grammar.h
  src/options/quantifiers_options.toml
  src/preprocessing/passes/synth_rew_rules.cpp
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/quantifiers/sygus/rcons_type_info.cpp
  src/theory/quantifiers/sygus/rcons_type_info.h
  src/theory/quantifiers/sygus/sygus_abduct.cpp
  src/theory/quantifiers/sygus/sygus_reconstruct.cpp
  src/theory/quantifiers/sygus/sygus_reconstruct.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/sygus/const-var-test.sy
  test/regress/cli/regress1/sygus/complex-no-rewrite.sy
  test/regress/cli/regress1/sygus/complex-rewrite-in-db.sy
  test/regress/cli/regress1/sygus/eq-sub-obs.sy
  test/regress/cli/regress1/sygus/hd-19-d1-prog-dup-op.sy
  test/regress/cli/regress1/sygus/no-var-in-sol.sy
  test/regress/cli/regress2/sygus/no-bad-filter.sy
  test/regress/cli/regress2/sygus/tp19.eqn_sygus_iter_98_0.sy
Labels: normal, moderate

#9803 Use standard theory state in arithmetic
  src/CMakeLists.txt
  src/theory/arith/arith_preprocess.cpp
  src/theory/arith/arith_preprocess.h
  src/theory/arith/arith_state.cpp
  src/theory/arith/arith_state.h
  src/theory/arith/branch_and_bound.cpp
  src/theory/arith/branch_and_bound.h
  src/theory/arith/equality_solver.cpp
  src/theory/arith/equality_solver.h
  src/theory/arith/inference_manager.cpp
  src/theory/arith/inference_manager.h
  src/theory/arith/linear/theory_arith_private.cpp
  src/theory/arith/nl/iand_solver.cpp
  src/theory/arith/nl/iand_solver.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/nl/pow2_solver.cpp
  src/theory/arith/nl/pow2_solver.h
  src/theory/arith/nl/transcendental/transcendental_solver.cpp
  src/theory/arith/nl/transcendental/transcendental_solver.h
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
Labels: minor, simple

#9806 Split embedding converter and sygus grammar constructor
  src/CMakeLists.txt
  src/theory/quantifiers/sygus/embedding_converter.cpp
  src/theory/quantifiers/sygus/embedding_converter.h
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.h
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
  src/theory/quantifiers/sygus/template_infer.cpp
Labels: minor, simple

#9794 Fix term ordering in TermCanonize
  src/expr/term_canonize.cpp
Labels: normal, simple

#9783 Add Node::getTypeOrNull
  src/expr/node.h
  src/expr/node_manager_template.cpp
Labels: minor, simple

#9754 Change name of method in strings proof converter
  src/smt/proof_post_processor.cpp
  src/theory/strings/infer_proof_cons.cpp
  src/theory/strings/infer_proof_cons.h
Labels: normal, simple

#9792 Add has abstract subterm method
  src/expr/node_algorithm.cpp
  src/expr/node_algorithm.h
Labels: normal, simple

#9793 Finer grained identifiers for sygus exclusion lemmas
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/quantifiers/sygus/enum_value_manager.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/synth_conjecture.h
Labels: minor, simple

#9765 Always print the learned literal type
  src/prop/zero_level_learner.cpp
Labels: normal, simple

#9807 Use sygus utils for setting up mapping from functions-to-synthesize to grammars
  src/smt/abduction_solver.cpp
  src/smt/sygus_solver.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/embedding_converter.cpp
  src/theory/quantifiers/sygus/sygus_abduct.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.h
  src/theory/quantifiers/sygus/sygus_interpol.cpp
  src/theory/quantifiers/sygus/sygus_utils.cpp
  src/theory/quantifiers/sygus/sygus_utils.h
  src/theory/quantifiers/sygus/template_infer.cpp
Labels: minor, simple

#9811 Rename pass to static rewrite
  src/CMakeLists.txt
  src/preprocessing/passes/static_rewrite.cpp
  src/preprocessing/passes/static_rewrite.h
  src/preprocessing/preprocessing_pass_registry.cpp
  src/smt/process_assertions.cpp
Labels: minor, simple

#9766 Simplify API for constructing tuple values
  NEWS.md
  examples/api/cpp/relations.cpp
  examples/api/java/Relations.java
  examples/api/python/relations.py
  include/cvc5/cvc5.h
  src/api/cpp/cvc5.cpp
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/jni/solver.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/parser/smt2/smt2.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/cpp/term_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/java/TermTest.java
  test/unit/api/python/test_solver.py
  test/unit/api/python/test_term.py
Labels: normal, moderate

#9775 Further refactor setLogic in the parser
  src/main/interactive_shell.cpp
  src/parser/api/cpp/command.cpp
  src/parser/api/cpp/input_parser.cpp
  src/parser/api/cpp/symbol_manager.cpp
  src/parser/api/cpp/symbol_manager.h
  src/parser/parser.cpp
  src/parser/parser_builder.cpp
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2_cmd_parser.cpp
  src/parser/smt2/smt2_parser.cpp
  src/parser/tptp/tptp.cpp
Labels: minor, simple

#9804 Add rewrite verifier expression miner
  src/CMakeLists.txt
  src/theory/quantifiers/query_generator_sample_sat.cpp
  src/theory/quantifiers/rewrite_verifier.cpp
  src/theory/quantifiers/rewrite_verifier.h
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus_sampler.cpp
  src/theory/quantifiers/sygus_sampler.h
Labels: normal, simple

#9810 Add filtering for query generation
  src/options/quantifiers_options.toml
  src/theory/quantifiers/query_generator.cpp
  src/theory/quantifiers/query_generator.h
  src/theory/quantifiers/query_generator_sample_sat.cpp
  src/theory/quantifiers/query_generator_unsat.cpp
  src/theory/quantifiers/query_generator_unsat.h
Labels: minor, simple

#9816 Minor simplifications for sygus
  src/theory/datatypes/sygus_extension.h
  src/theory/quantifiers/sygus/sygus_stats.cpp
  src/theory/quantifiers/sygus/sygus_stats.h
Labels: minor, simple

#9813 Refactor interface for any constant constructors
  src/expr/dtype_cons.cpp
  src/expr/dtype_cons.h
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/expr/sygus_datatype.cpp
  src/expr/sygus_datatype.h
  src/printer/smt2/smt2_printer.cpp
  src/theory/datatypes/sygus_datatype_utils.cpp
  src/theory/datatypes/sygus_datatype_utils.h
  src/theory/datatypes/sygus_extension.cpp
  src/theory/quantifiers/sygus/sygus_eval_unfold.cpp
  src/theory/quantifiers/sygus/sygus_grammar_red.cpp
  src/theory/quantifiers/sygus/sygus_repair_const.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/type_info.cpp
  test/regress/cli/regress0/sygus/print-grammar.sy
Labels: normal, simple

#9759 Enable the new smt2 lexer by default
  src/parser/CMakeLists.txt
  src/parser/flex_lexer.cpp
  src/parser/flex_lexer.h
  src/parser/smt2/smt2_cmd_parser.cpp
  src/parser/smt2/smt2_cmd_parser.h
  src/parser/smt2/smt2_lexer.flex
  src/parser/smt2/smt2_lexer.h
  src/parser/smt2/smt2_lexer_new.cpp
  src/parser/smt2/smt2_lexer_new.h
  src/parser/smt2/smt2_parser.cpp
  src/parser/smt2/smt2_parser.h
  src/parser/smt2/smt2_term_parser.cpp
  src/parser/smt2/smt2_term_parser.h
Labels: normal, moderate

#9834 fp: Minor cleanup in theory FP.
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp.h
Labels: normal, simple

#9776 Change option name for print unsat cores full
  NEWS.md
  src/options/smt_options.toml
  src/parser/api/cpp/command.cpp
  test/regress/cli/regress0/dump-unsat-core-full.smt2
Labels: minor, simple

#9817 Updates and extensions to sygus grammar utility
  src/expr/sygus_grammar.cpp
  src/expr/sygus_grammar.h
Labels: minor, moderate

#9814 Add synth finder utility
  include/cvc5/cvc5_types.h
  src/CMakeLists.txt
  src/api/cpp/cvc5_types.cpp
  src/theory/quantifiers/sygus/synth_finder.cpp
  src/theory/quantifiers/sygus/synth_finder.h
  test/unit/api/java/UncoveredTest.cpp
  test/unit/api/python/test_uncovered.cpp
Labels: normal, moderate

#9789 Fix gcc compile issue
  include/cvc5/cvc5_kind.h
Labels: normal, simple

#9805 Disabling 'make test' workaround.
  test/api/cpp/CMakeLists.txt
  test/regress/cli/CMakeLists.txt
  test/unit/CMakeLists.txt
Labels: major

#9798 Add verbose trace message to timeout core manager
  src/smt/timeout_core_manager.cpp
Labels: normal, simple

#9679 [proofs] [sat] Cover missed case when tracking optimized clauses' proofs
  src/prop/sat_proof_manager.cpp
  src/prop/sat_proof_manager.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/issue9669-clause-level-opt-incremental.smt2
Labels: normal, simple

#9827 Change timeout cores to apply to preprocessed assertions
  src/api/cpp/cvc5.cpp
  src/smt/smt_driver_deep_restarts.cpp
  src/smt/smt_solver.cpp
  src/smt/smt_solver.h
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  src/smt/timeout_core_manager.cpp
  src/smt/timeout_core_manager.h
  test/regress/cli/regress0/timeout_core_simple.smt2
  test/regress/cli/regress1/print_timeout_core.smt2
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
Labels: normal, moderate

#9729 Improvements for GenericOp
  src/printer/smt2/smt2_printer.cpp
  src/theory/builtin/generic_op.cpp
  src/theory/builtin/generic_op.h
  src/theory/builtin/theory_builtin_rewriter.cpp
Labels: minor, simple

#9808 Fix registration of arithmetic proof checkers
  src/theory/arith/linear/theory_arith_private.cpp
  src/theory/arith/linear/theory_arith_private.h
  src/theory/arith/nl/coverings_solver.cpp
  src/theory/arith/nl/coverings_solver.h
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/arith/nl/nonlinear_extension.h
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  src/theory/arith/nl/transcendental/transcendental_state.h
  src/theory/arith/proof_checker.cpp
  src/theory/arith/proof_checker.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
Labels: minor, simple

#9820 Update type checker utility for gradual types
  src/expr/type_checker_util.h
Labels: minor, simple

#9797 Unify purification skolems and skolem functions
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/preprocessing/passes/real_to_int.cpp
  src/printer/smt2/smt2_printer.cpp
  src/smt/term_formula_removal.cpp
  src/theory/arith/nl/ext/factoring_check.cpp
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  src/theory/arith/operator_elim.cpp
  src/theory/bags/inference_generator.cpp
  src/theory/bags/inference_generator.h
  src/theory/bags/theory_bags.cpp
  src/theory/bv/int_blaster.cpp
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/fp/theory_fp.cpp
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/ho_term_database.cpp
  src/theory/quantifiers/inst_strategy_mbqi.cpp
  src/theory/quantifiers/sygus_inst.cpp
  src/theory/sets/skolem_cache.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
  src/theory/strings/infer_proof_cons.cpp
  src/theory/strings/skolem_cache.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/uf/lambda_lift.cpp
  test/regress/cli/regress0/bug421.smt2
Labels: normal, moderate

#9841 Avoid calling getCardinality on infinite types in arrays
  src/theory/arrays/theory_arrays_rewriter.cpp
  src/theory/arrays/theory_arrays_type_rules.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/datatypes/nested-rec-array-aa.smt2
Labels: minor, simple

#9842 Fix coverage
  test/unit/api/cpp/types_black.cpp
Labels: normal, simple

#9777 Add output for portfolio
  src/main/portfolio_driver.cpp
  src/main/portfolio_driver.h
  src/options/base_options.toml
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/printer/portfolio-out.smt2
Labels: minor, simple

#9788 Add parsing support for unimplemented declare-oracle-fun
  src/parser/smt2/smt2_cmd_parser.cpp
  src/parser/tokens.cpp
  src/parser/tokens.h
Labels: minor, simple

#9836 Clean up includes and use of internal namespace
  src/parser/api/cpp/command.cpp
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/printer/tptp/tptp_printer.cpp
  src/proof/unsat_core.cpp
  src/proof/unsat_core.h
  src/smt/solver_engine.cpp
Labels: normal, simple

#9818 Add new sygus grammar construction utility
  src/CMakeLists.txt
  src/theory/quantifiers/sygus/sygus_grammar_cons_new.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons_new.h
Labels: minor, moderate

#9837 Remove spurious mkTypeConst method from node manager
  src/expr/mkmetakind
  src/expr/node_manager_template.cpp
Labels: minor, simple

#9838 Check if IPO is actually available and turn it off if it's not
  CMakeLists.txt
Labels: minor

#9848 fp: Refactor and extend model value handling.
  src/theory/fp/fp_word_blaster.cpp
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp.h
Labels: normal, moderate

#9851 Do not use ITE or OR in grammars generated for abduction
  src/options/quantifiers_options.toml
  src/smt/abduction_solver.cpp
  src/theory/quantifiers/sygus/embedding_converter.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons_new.cpp
Labels: normal, simple

#9826 Update arrays to gradual type system
  src/theory/arrays/theory_arrays_type_rules.cpp
  src/theory/arrays/theory_arrays_type_rules.h
Labels: minor, moderate

#9857 Simplify use of DT_SIZE in sygus
  src/theory/datatypes/theory_datatypes.cpp
  test/regress/cli/regress0/quantifiers/issue8159-3-qext-nterm.smt2
  test/regress/cli/regress1/quantifiers/issue5766-wrong-sel-trigger.smt2
  test/regress/cli/regress1/sygus/commutative-stream.sy
Labels: normal, simple

#9726 Add preComputeType to the type checker
  src/expr/mkexpr
  src/expr/type_checker_template.cpp
  src/theory/arith/kinds
  src/theory/arith/theory_arith_type_rules.cpp
  src/theory/arith/theory_arith_type_rules.h
  src/theory/bags/theory_bags_type_rules.cpp
  src/theory/bags/theory_bags_type_rules.h
  src/theory/booleans/theory_bool_type_rules.cpp
  src/theory/builtin/theory_builtin_type_rules.cpp
  src/theory/builtin/theory_builtin_type_rules.h
  src/theory/bv/theory_bv_type_rules.cpp
  src/theory/bv/theory_bv_type_rules.h
  src/theory/datatypes/theory_datatypes_type_rules.cpp
  src/theory/datatypes/theory_datatypes_type_rules.h
  src/theory/ff/theory_ff_type_rules.cpp
  src/theory/ff/theory_ff_type_rules.h
  src/theory/fp/kinds
  src/theory/fp/theory_fp_type_rules.cpp
  src/theory/fp/theory_fp_type_rules.h
  src/theory/quantifiers/theory_quantifiers_type_rules.cpp
  src/theory/quantifiers/theory_quantifiers_type_rules.h
  src/theory/sep/theory_sep_type_rules.cpp
  src/theory/sep/theory_sep_type_rules.h
  src/theory/sets/theory_sets_type_rules.cpp
  src/theory/sets/theory_sets_type_rules.h
  src/theory/strings/theory_strings_type_rules.cpp
  src/theory/strings/theory_strings_type_rules.h
  src/theory/uf/kinds
  src/theory/uf/theory_uf_type_rules.cpp
  src/theory/uf/theory_uf_type_rules.h
Labels: normal, moderate
