Repository cvc5/cvc5, pull requests merged in 2023-03, with the labels that each got.

#9535 [proofs] [alethe] Fix some resolution pivots added during conversion
  src/proof/alethe/alethe_post_processor.cpp
Labels: normal, simple

#9534 Add basic support for finite field proofs in LFSC
  proofs/lfsc/signatures/theory_def.plf
  src/expr/nary_term_util.cpp
  src/proof/lfsc/lfsc_node_converter.cpp
Labels: minor, moderate

#9504 Fix special cases for channel options
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2_cmd_parser.cpp
  src/printer/smt2/smt2_printer.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/options/stream-printing.smt2
  test/regress/cli/regress0/parser/stdout-diag.smt2
Labels: moderate

#9499 Enable flex smt2 parser by default
  src/main/driver_unified.cpp
  src/options/parser_options.toml
  src/parser/api/cpp/command.cpp
  src/parser/flex_parser.cpp
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2_lexer.flex
  src/parser/smt2/smt2_term_parser.cpp
  test/binary/interactive_shell.py
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/non-std-char.smt2
Labels: normal, simple

#9530 [proofs] [alethe] Proper support for Skolems
  src/proof/alethe/alethe_node_converter.cpp
  src/proof/alethe/alethe_node_converter.h
  src/proof/alethe/alethe_post_processor.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/issue9515-alethe-skolems-crash.smt2
  test/regress/cli/regress0/proofs/issue9516-alethe-skolems-undef-in-proof.smt2
Labels: normal, moderate

#9546 Fix regular expression inclusion for ranges
  src/theory/strings/regexp_entail.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/strings/issue9543-re-inc.smt2
  test/regress/cli/regress1/strings/re-inc-range.smt2
Labels: major, simple

#9541 Fix resource manager disabling on last call and add resource checks for sygus solver
  src/theory/model_manager.cpp
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/theory_engine.cpp
  src/util/resource_manager.cpp
  src/util/resource_manager.h
Labels: normal, moderate

#9552 ci: Switch to ubuntu-latest.
  .github/workflows/ci.yml
Labels: major

#9550 Enable stdin-input-per-line by default
  src/options/main_options.toml
Labels: major, simple

#9493 Add tuple semantics for pool-based instantiation
  src/api/cpp/cvc5_kind.h
  src/options/quantifiers_options.toml
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/quantifiers/inst_strategy_pool.cpp
  src/theory/quantifiers/inst_strategy_pool.h
  src/theory/quantifiers/theory_quantifiers_type_rules.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/quantifiers/pool-tuple.smt2
Labels: minor, moderate

#9548 Improve Flex lexing for comments
  src/parser/smt2/smt2_lexer.flex
Labels: major, simple

#9511 Proper memory management of parsed commands
  src/main/interactive_shell.cpp
  src/main/portfolio_driver.cpp
  src/parser/api/cpp/input_parser.cpp
  src/parser/api/cpp/input_parser.h
  src/parser/flex_parser.cpp
  src/parser/flex_parser.h
  src/parser/input.h
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/parser_antlr.cpp
  src/parser/parser_antlr.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2_input.cpp
  src/parser/smt2/smt2_input.h
  src/parser/smt2/smt2_parser.cpp
  src/parser/smt2/smt2_parser.h
  src/parser/smt2/sygus_input.cpp
  src/parser/smt2/sygus_input.h
  src/parser/tptp/Tptp.g
  src/parser/tptp/tptp.cpp
  src/parser/tptp/tptp.h
  src/parser/tptp/tptp_input.cpp
  src/parser/tptp/tptp_input.h
  test/api/cpp/ouroborous.cpp
  test/api/cpp/smt2_compliance.cpp
  test/unit/parser/parser_black.cpp
  test/unit/parser/parser_builder_black.cpp
Labels: normal, moderate

#9551 Fix ref count for literals used in difficulty manager
  src/theory/difficulty_manager.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/issue9544-difficulty-refcount.smt2
Labels: normal, simple

#9528 prop: Simplify handling of introduction and decision levels.
  src/prop/minisat/minisat.cpp
  src/prop/minisat/minisat.h
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/sat_solver.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
  src/theory/bv/bv_solver_bitblast.cpp
  src/theory/valuation.cpp
  src/theory/valuation.h
Labels: normal, moderate

#9558 bv: rewrites: Clarify documentation for MultSltMult (via formatting).
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
Labels: normal, simple

#9538 Fix bug in relevance manager for incomplete assignments
  src/theory/relevance_manager.cpp
Labels: normal, simple

#9510 Minor improvements to difficulty manager
  src/theory/difficulty_manager.cpp
  src/theory/difficulty_manager.h
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
Labels: minor, simple

#9539 Introduce generic operator and APPLY_INDEXED_SYMBOL kind
  src/CMakeLists.txt
  src/proof/lfsc/lfsc_node_converter.cpp
  src/theory/builtin/generic_op.cpp
  src/theory/builtin/generic_op.h
  src/theory/builtin/kinds
  src/theory/builtin/theory_builtin_rewriter.cpp
  src/theory/builtin/theory_builtin_rewriter.h
  src/theory/builtin/theory_builtin_type_rules.cpp
  src/theory/builtin/theory_builtin_type_rules.h
Labels: minor, moderate

#9561 Revert change to type checker
  src/expr/node_manager_template.cpp
  src/expr/type_checker_template.cpp
Labels: major, simple

#9576 Add missing calls to rewrite from learned rewrite pass
  src/preprocessing/passes/learned_rewrite.cpp
  src/preprocessing/passes/non_clausal_simp.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/issue9573-lr-rewrite.smt2
Labels: minor, simple

#9547 Eliminate quantifiers pre rewrite, combine quantifiers at post rewrite.
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/substitutions.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/quantifiers/issue9545-mini-agg.smt2
Labels: normal, moderate

#9583 Make block models robust to non-constant evaluations
  src/smt/model_blocker.cpp
  test/api/cpp/CMakeLists.txt
  test/api/cpp/proj-issue573.cpp
  test/api/cpp/proj-issue574.cpp
  test/api/cpp/proj-issue575.cpp
Labels: normal, simple

#9540 Add implementation of DSL rewrite database
  src/rewriter/rewrite_db.cpp
  src/rewriter/rewrite_db.h
  src/rewriter/rewrite_proof_rule.cpp
  src/rewriter/rewrite_proof_rule.h
Labels: minor, moderate

#9586 Fixes for instantiation evaluation
  src/theory/quantifiers/ieval/pattern_term_info.cpp
  src/theory/quantifiers/ieval/state.cpp
  src/theory/quantifiers/ieval/term_evaluator.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/quantifiers/dd.ho-matching-enum.smt2
  test/regress/cli/regress1/quantifiers/dd.bug812-ieval.smt2
  test/regress/cli/regress1/quantifiers/proj-issue564.smt2
  test/regress/cli/regress1/quantifiers/proj-issue597.smt2
  test/regress/cli/regress1/quantifiers/proj-issue599.smt2
  test/regress/cli/regress1/quantifiers/proj-issue602.smt2
Labels: normal, moderate

#9599 Fix type issue for bv2nat rewrite
  src/theory/uf/theory_uf_rewriter.cpp
  test/api/cpp/CMakeLists.txt
  test/api/cpp/proj-issue538.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/int2bv2nat-rew-type.smt2
Labels: normal, simple

#9582 Filter lemmas from difficulty manager
  src/smt/proof_manager.cpp
  src/smt/solver_engine.cpp
  src/theory/difficulty_manager.cpp
  src/theory/difficulty_manager.h
  src/theory/relevance_manager.cpp
  src/theory/relevance_manager.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/proj-issue589.smt2
  test/regress/cli/regress0/proofs/t1-difficulty-filter.smt2
  test/regress/cli/regress1/difficulty-polarity.smt2
  test/regress/cli/regress1/proj-issue542.smt2
Labels: normal, simple

#9595 Fix nl callback for non-arithmetic equalities
  src/theory/arith/nl/ext_theory_callback.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/nl/proj-issue552-narith-cee.smt2
Labels: normal, simple

#9596 Fix another case of model blocking for non-constant evaluation
  src/smt/model_blocker.cpp
  test/api/cpp/CMakeLists.txt
  test/api/cpp/proj-issue612.cpp
Labels: minor, simple

#9604 Define minimal granularity for bitwise `and`
  src/options/smt_options.toml
  test/api/cpp/CMakeLists.txt
  test/api/cpp/proj-issue611.cpp
Labels: bug

#9606 Disable lfsc on new regression with set comprehension
  test/regress/cli/regress1/quantifiers/proj-issue564.smt2
Labels: major, simple

#9608 Do not traverse beneath non-string operators during lazy term registration
  src/theory/strings/term_registry.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/seq/proj-issue604-reg-closure.smt2
Labels: minor, simple

#9618 Fix learned rewrite pass for rewritten nodes
  src/preprocessing/passes/learned_rewrite.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/nl/issue9611-lrew.smt2
Labels: normal, simple

#9615 Fix cases of abduction and interpolation where conjecture is not available
  src/smt/set_defaults.cpp
  src/smt/solver_engine.cpp
  test/api/cpp/CMakeLists.txt
  test/api/cpp/proj-issue567.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/sygus/abduct-pponly.smt2
  test/regress/cli/regress0/sygus/interpolant-gn.smt2
Labels: normal, simple

#9590 Make decomposeLiteral more robust to failure
  src/theory/arith/linear/theory_arith_private.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/strings/proj-issue585-cbqi-t-cons.smt2
Labels: minor, simple

#9613 Make CEGQI single invocation more robust for quantified subqueries
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  test/api/cpp/CMakeLists.txt
  test/api/cpp/proj-issue581.cpp
Labels: minor, simple

#9612 Disable lfsc on new regression
  test/regress/cli/regress0/proofs/t1-difficulty-filter.smt2
Labels: major, simple

#9609 Check for infeasible side conditions for abduction
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/quantifiers/sygus/cegis_core_connective.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  test/api/cpp/CMakeLists.txt
  test/api/cpp/proj-issue587.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/abduction/abduct-apply-uf.smt2
  test/regress/cli/regress1/abduction/abduct-false-sc.smt2
Labels: normal, moderate

#9591 Fix a case for failing proofs in datatypes clashing testers
  src/theory/datatypes/infer_proof_cons.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/datatypes/proj-issue578-clash-pf.smt2
Labels: minor, simple

#9593 Add proof rules and checker for DSL_REWRITE and ENCODE_PRED_TRANSFORM
  src/proof/proof_rule.cpp
  src/proof/proof_rule.h
  src/theory/builtin/proof_checker.cpp
  src/theory/builtin/proof_checker.h
Labels: normal, moderate

#9594 Fix spurious eager check of theory lemma
  src/prop/prop_engine.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/proj-issue554.smt2
Labels: minor, simple

#9597 Fix case of non-constant array in function constant conversion
  src/theory/arrays/theory_arrays_rewriter.cpp
  src/theory/uf/function_const.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arrays/proj-issue545-array-nconst.smt2
  test/regress/cli/regress0/arrays/proj-issue563.smt2
Labels: normal, simple

#9630 Do not use single invocation solver when side condition for abduction is present
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  test/api/cpp/CMakeLists.txt
  test/api/cpp/proj-issue618.cpp
Labels: minor, simple

#9601 Relax assertions in nlt proof checker
  src/theory/arith/nl/transcendental/proof_checker.cpp
  src/theory/arith/nl/transcendental/sine_solver.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/nl/proj-issue530.smt2
Labels: minor, simple

#9607 Add scripts for TPTP solving using smt2 conversion
  contrib/competitions/casc/run-script-current-fnt
  contrib/competitions/casc/run-script-current-fof
  contrib/competitions/casc/run-script-current-tfa
  contrib/competitions/casc/run-script-current-thf
Labels: normal, simple

#9624 Disable LFSC on new regression
  test/regress/cli/regress0/seq/proj-issue604-reg-closure.smt2
Labels: major, simple

#9616 Fix returned result for sygus single invocation solver when unknown
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  test/api/cpp/CMakeLists.txt
  test/api/cpp/proj-issue570.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/interpolant-unk-570.smt2
Labels: minor, simple

#9633 More fixes for learned-rewrite
  src/preprocessing/passes/learned_rewrite.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/nl/issue9611-lrew.smt2
  test/regress/cli/regress1/nl/issue9621-lrew.smt2
Labels: normal, simple

#9619 Move bv2nat inequality elimination to ppRewrite
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_rewriter.h
  src/theory/arith/theory_arith.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/proj-issue539-rew-bv2nat.smt2
  test/regress/cli/regress1/proj-issue557-rew-bv2nat.smt2
Labels: normal, moderate

#9575 Fix parsing for datatypes in interactive mode
  src/main/command_executor.cpp
  src/parser/api/cpp/command.cpp
  src/parser/api/cpp/symbol_manager.cpp
  src/parser/api/cpp/symbol_manager.h
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2_cmd_parser.cpp
  src/parser/smt2/smt2_term_parser.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/issue9568-dt-multi-line.smt2
Labels: major, moderate

#9626 Fix printing of projection operators and divisible operator
  src/printer/smt2/smt2_printer.cpp
  src/theory/datatypes/project_op.cpp
Labels: normal, simple

#9617 Ensure types are preserved when rewriting mixed POW terms
  src/theory/arith/arith_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/quantifiers/issue9602-rewrite-pow-type.smt2
Labels: minor, simple

#9636 Fix assertion for internal representative selection in quantifiers
  src/theory/quantifiers/equality_query.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/quantifiers/proj-issue546-ee-rep.smt2
Labels: minor, simple

#9625 Fixes for sygus-rr-synth-input
  src/preprocessing/passes/synth_rew_rules.cpp
  src/smt/set_defaults.cpp
  src/theory/datatypes/sygus_extension.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/sygus/proj-issue541.smt2
  test/regress/cli/regress1/sygus/proj-issue548-srr.smt2
  test/regress/cli/regress1/sygus/proj-issue549-srr.smt2
  test/regress/cli/regress1/sygus/proj-issue553-srr.smt2
Labels: minor, simple

#9635 Proper parse error for incorrectly indexed symbols
  src/parser/smt2/smt2_term_parser.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/issue9623-indexed-err.smt2
Labels: minor, simple

#9641 Fix virtual term substitution for non arithmetic equalities
  src/theory/quantifiers/cegqi/vts_term_cache.cpp
  src/theory/quantifiers/instantiate.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/quantifiers/issue9640-vts-iff.smt2
Labels: normal, simple
