Repository cvc5/cvc5, pull requests merged in 2023-04, with the labels that each got.

#9610 Fixes related to congruent optimization for sets
  src/theory/sets/solver_state.cpp
  src/theory/sets/theory_sets_private.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/sets/proj-issue583.smt2
  test/regress/cli/regress1/sets/proj-issue610.smt2
Labels: normal, moderate

#9574 Fix models for separation logic
  src/theory/sep/theory_sep.cpp
  src/theory/sep/theory_sep.h
Labels: normal, moderate

#9637 [proofs] [alethe] Fixes issue where clausal reasoning would clash with introduced literals
  src/proof/alethe/alethe_post_processor.cpp
  src/proof/alethe/alethe_post_processor.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/issue9531-alethe-resolution.smt2
Labels: normal, moderate

#9646 Disable lfsc on timeout regression
  test/regress/cli/regress1/quantifiers/bug802.smt2
Labels: major, simple

#9648 bv: rewriter: Rename rewrite XorOne to XorOnes and fix documentation.
  src/theory/bv/theory_bv_rewrite_rules.h
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
  src/theory/bv/theory_bv_rewriter.cpp
Labels: normal, simple

#9647 Rewrite double application of to_real
  src/theory/arith/arith_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arith/issue9643.smt2
Labels: minor, simple

#9628 Miscellaneous infrastructure for DSL rewrite rules
  src/proof/proof_node_to_sexpr.cpp
  src/proof/proof_node_to_sexpr.h
  src/smt/proof_final_callback.cpp
  src/smt/proof_final_callback.h
Labels: minor, simple

#9654 Move clone of ProofNodes from the ProofNodeManager to ProofNode
  src/proof/proof_node.cpp
  src/proof/proof_node.h
  src/proof/proof_node_manager.cpp
  src/proof/proof_node_manager.h
  src/prop/proof_cnf_stream.cpp
  src/prop/sat_proof_manager.cpp
  src/smt/proof_manager.cpp
  src/theory/uf/proof_equality_engine.cpp
Labels: normal, simple

#9649 symfpu: Use patched branch instead of applying patch.
  cmake/FindSymFPU.cmake
  cmake/deps-utils/SymFPU-patch-20201114.patch
Labels: normal, simple

#9537 Introduce timeout core manager class
  src/CMakeLists.txt
  src/options/smt_options.toml
  src/smt/timeout_core_manager.cpp
  src/smt/timeout_core_manager.h
Labels: major, moderate

#9666 Fixes for invalid inputs
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2_term_parser.cpp
  src/theory/strings/regexp_entail.cpp
  src/theory/strings/regexp_eval.cpp
  src/theory/strings/theory_strings_utils.cpp
  src/theory/strings/theory_strings_utils.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/issue9663-2.smt2
  test/regress/cli/regress0/parser/issue9663.smt2
  test/regress/cli/regress0/parser/issue9665.smt2
Labels: minor, simple

#9652 Catch more error cases in the parser
  src/parser/smt2/smt2.cpp
  src/parser/smt2/smt2_term_parser.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/issue9645.smt2
  test/regress/cli/regress0/parser/issue9651.smt2
Labels: minor, simple

#9670 Add `get-timeout-core` to the API
  NEWS.md
  include/cvc5/cvc5.h
  src/api/cpp/cvc5.cpp
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/jni/solver.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/options/base_options.toml
  src/parser/api/cpp/command.cpp
  src/parser/api/cpp/command.h
  src/parser/smt2/Smt2.g
  src/parser/smt2/smt2_cmd_parser.cpp
  src/parser/smt2/smt2_lexer.flex
  src/parser/tokens.cpp
  src/parser/tokens.h
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/smt/smt_solver.h
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  src/smt/timeout_core_manager.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/timeout_core_simple.smt2
  test/regress/cli/regress1/print_timeout_core.smt2
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
Labels: normal, moderate

#9659 Rare: Add missing and previously buggy rules to bv/rewrites
  src/theory/bv/rewrites
Labels: minor, simple, project

#9684 parser: Add error check for number of argmuments of fp value.
  src/parser/smt2/smt2.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/issue9676.smt2
Labels: normal, simple

#9680 Distinguish ppStaticRewrite from normal ppRewrite
  src/preprocessing/passes/theory_rewrite_eq.cpp
  src/preprocessing/passes/theory_rewrite_eq.h
  src/preprocessing/preprocessing_pass_registry.cpp
  src/smt/process_assertions.cpp
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/booleans/theory_bool.cpp
  src/theory/booleans/theory_bool.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/datatypes/theory_datatypes.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/sets/comp-qf-error.smt2
  test/regress/cli/regress1/issue9660-bv2nat-static.smt2
  test/regress/cli/regress1/proj-issue623-bv2nat-static.smt2
  test/regress/cli/regress1/quantifiers/proj-issue295.smt2
Labels: normal, moderate

#9686 api: mkFloatingPoint: Add missing guards for size of exp/sig.
  src/api/cpp/cvc5.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/issue9675.smt2
Labels: normal, simple

#9685 Disable dagification when printing operator names in LFSC
  src/proof/lfsc/lfsc_node_converter.cpp
Labels: major, simple

#9681 Ensure model is built when notifying modules of candidate models
  src/theory/difficulty_manager.cpp
  src/theory/difficulty_manager.h
  src/theory/relevance_manager.cpp
  src/theory/relevance_manager.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine_module.cpp
  src/theory/theory_engine_module.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/proj-issue634-diff-mc.smt2
Labels: minor, simple

#9653 Make sygus fairness direct policy more robust
  src/theory/datatypes/sygus_extension.cpp
  src/theory/datatypes/sygus_extension.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/sygus/proj-issue627-srr.smt2
Labels: minor, simple

#9687 Rare: Correct a minor error in urem pow2
  src/theory/bv/rewrites
Labels: bug, minor, simple

#9688 [proofs] [alethe] Use defs+assumptions scope mode for Alethe
  src/proof/alethe/alethe_post_processor.cpp
  src/smt/solver_engine.cpp
Labels: normal, moderate

#9689 Fix typos in BV rewrite rules
  src/theory/bv/rewrites
Labels: bug, minor, simple

#9691 Fix bug in bv-rotate-{left,right}-eliminate
  src/theory/bv/rewrites
Labels: bug, minor, simple

#9699 Add more BV rewrite rules to fill holes
  src/theory/bv/rewrites
Labels: minor, simple, engineer

#9700 Fix license link for SymFPU.
  COPYING
Labels: major, simple

#9673 Update news for new parser
  NEWS.md
Labels: minor, simple

#9683 Do not force binary in smt2 printer
  src/printer/smt2/smt2_printer.cpp
Labels: minor, simple
