Repository cvc5/cvc5, pull requests merged in 2024-08, with the labels that each got.

#11064 Fixing documentation for proof rules
  include/cvc5/cvc5_proof_rule.h
Labels: normal, moderate

#11070 Fix for parsing incremental input
  include/cvc5/cvc5_parser.h
  src/api/cpp/cvc5_parser.cpp
  test/api/c/CMakeLists.txt
  test/api/c/issue11069.c
  test/api/cpp/CMakeLists.txt
  test/api/cpp/issue11069.cpp
Labels: normal, simple

#11116 test: c api: Fix memory leaks in capi_issue11069
  test/api/c/issue11069.c
Labels: normal, simple

#11057 docs: python: Add missing docs text for pages.
  docs/api/cpp/classes/op.rst
  docs/api/cpp/classes/sort.rst
  docs/api/cpp/classes/term.rst
  docs/api/python/base/datatype.rst
  docs/api/python/base/datatypeconstructor.rst
  docs/api/python/base/datatypeconstructordecl.rst
  docs/api/python/base/datatypedecl.rst
  docs/api/python/base/datatypeselector.rst
  docs/api/python/base/grammar.rst
  docs/api/python/base/kind.rst
  docs/api/python/base/op.rst
  docs/api/python/base/proofrule.rst
  docs/api/python/base/result.rst
  docs/api/python/base/roundingmode.rst
  docs/api/python/base/solver.rst
  docs/api/python/base/sort.rst
  docs/api/python/base/statistics.rst
  docs/api/python/base/synthresult.rst
  docs/api/python/base/term.rst
  docs/api/python/base/unknownexplanation.rst
Labels: normal, simple

#11058 docs: python base: Add missing docs pages.
  docs/api/python/base/command.rst
  docs/api/python/base/inputparser.rst
  docs/api/python/base/modes.rst
  docs/api/python/base/plugin.rst
  docs/api/python/base/proof.rst
  docs/api/python/base/python.rst
  docs/api/python/base/symbolmanager.rst
Labels: normal, simple

#11105 c api: Add API test sep_log_api.
  test/api/c/CMakeLists.txt
  test/api/c/sep_log_api.c
  test/api/cpp/sep_log_api.cpp
Labels: normal, simple

#11087 Add missing NEWS for 1.2.0
  NEWS.md
Labels: normal, moderate

#11136 Initialize d_isRational if CVC5_POLY_IMP is true
  src/util/real_algebraic_number_poly_imp.cpp
  src/util/real_algebraic_number_poly_imp.h
Labels: normal, simple

#11134 doc: Update notes on library path
  INSTALL.rst
Labels: normal, simple

#11129 [alethe] Update processing of ProofRule::FORALL_INST
  src/proof/alethe/alethe_post_processor.cpp
Labels: normal, simple

#11127 [alethe] Support for ProofRule::ALPHA_EQUIV
  src/proof/alethe/alethe_post_processor.cpp
Labels: normal, simple

#11138 [docs] Fixing issues in proof rules
  include/cvc5/cvc5_proof_rule.h
Labels: normal, simple

#11112 Enable term-db-mode=relevant by default
  src/options/quantifiers_options.toml
  test/regress/cli/regress0/quantifiers/dd.ricart-ieval.smt2
  test/regress/cli/regress1/quantifiers/quaternion_ds1_symm_0428.fof.smt2
Labels: normal, simple

#11137 Reference release version of ethos
  NEWS.md
  contrib/get-ethos-checker
Labels: normal, simple

#11141 Fix timeout on regression
  test/regress/cli/regress2/bug674.smt2
Labels: major, simple

#11125 [alethe] Post-processing ProofRule::TRUST
  src/proof/alethe/alethe_post_processor.cpp
Labels: normal, simple

#11123 [alethe] Add arguments to rules and/not_or/and_pos/or_neg
  src/proof/alethe/alethe_post_processor.cpp
Labels: normal, simple

#11122 [alethe] Tracking post-processing failures
  src/proof/alethe/alethe_post_processor.cpp
  src/proof/alethe/alethe_post_processor.h
  src/proof/proof_checker.cpp
  src/proof/proof_checker.h
  src/smt/proof_manager.cpp
Labels: normal, simple

#11130 [alethe] Support for rules added during elaboration of rewrites
  src/proof/alethe/alethe_post_processor.cpp
Labels: normal, simple

#11124 [alethe] Generalize resolution post-processing
  src/proof/alethe/alethe_post_processor.cpp
Labels: normal, moderate

#11140 Refine policy for lazy lambda lifting
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/theory_engine.cpp
  src/theory/theory_model_builder.cpp
  src/theory/uf/ho_extension.cpp
  src/theory/uf/lambda_lift.cpp
  src/theory/uf/lambda_lift.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/ho/model-dep-arg.smt2
  test/regress/cli/regress1/sets/filter-no-lift-red_2.smt2
Labels: normal, moderate

#11118 [alethe] Optimize printer
  src/proof/alethe/alethe_let_binding.cpp
  src/proof/alethe/alethe_printer.cpp
  src/proof/alethe/alethe_printer.h
Labels: normal, moderate

#11126 [alethe] Better support for BV
  src/proof/alethe/alethe_post_processor.cpp
Labels: normal, simple

#11120 [alethe] Updates to node converter
  src/proof/alethe/alethe_node_converter.cpp
Labels: normal, simple

#11119 [alethe] Updates to resolution post-processing
  src/proof/alethe/alethe_post_processor.cpp
  src/smt/proof_manager.cpp
Labels: normal, moderate

#11144 Do not override proof granularity if set by user
  src/smt/set_defaults.cpp
Labels: normal, simple

#11142 Update copyright headers and year in copyright message
  contrib/get-authors
  docs/CMakeLists.txt
  docs/api/CMakeLists.txt
  docs/api/java/CMakeLists.txt
  docs/api/python/CMakeLists.txt
  src/base/configuration.cpp
  src/theory/conflict_processor.cpp
  src/theory/conflict_processor.h
Labels: normal, simple

#11113 Add unsat core lemma output tag
  include/cvc5/cvc5_proof_rule.h
  src/CMakeLists.txt
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/options/base_options.toml
  src/options/proof_options.toml
  src/proof/annotation_proof_generator.cpp
  src/proof/annotation_proof_generator.h
  src/proof/proof_node_to_sexpr.cpp
  src/prop/prop_engine.cpp
  src/prop/prop_proof_manager.cpp
  src/prop/prop_proof_manager.h
  src/smt/proof_final_callback.cpp
  src/smt/proof_final_callback.h
  src/theory/builtin/proof_checker.cpp
  src/theory/inference_id_proof_annotator.cpp
  src/theory/inference_id_proof_annotator.h
  src/theory/theory_inference_manager.cpp
  src/theory/theory_inference_manager.h
Labels: minor, moderate

#11149 Fix minor projects issues
  src/smt/process_assertions.cpp
  src/theory/arith/linear/congruence_manager.cpp
  src/theory/theory_engine.cpp
  test/regress/cli/regress0/quantifiers/proj-issue738-qpre-sk.smt2
  test/regress/cli/regress0/strings/issue2958.smt2
Labels: minor, simple

#10914 Update RARE reconstruction algorithm to allow free variables defined in conditions
  src/rewriter/mkrewrites.py
  src/rewriter/rewrite_db_proof_cons.cpp
  src/rewriter/rewrite_proof_rule.cpp
  src/rewriter/rewrite_proof_rule.h
  src/theory/arith/arith_rewriter.cpp
  src/theory/evaluator.cpp
Labels: normal, moderate

#11150 Distinguish user triggers in -o trigger
  src/theory/quantifiers/ematching/ho_trigger.cpp
  src/theory/quantifiers/ematching/ho_trigger.h
  src/theory/quantifiers/ematching/inst_strategy_e_matching.cpp
  src/theory/quantifiers/ematching/inst_strategy_e_matching_user.cpp
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/ematching/trigger.h
  src/theory/quantifiers/ematching/trigger_database.cpp
  src/theory/quantifiers/ematching/trigger_database.h
Labels: minor, simple

#11152 [alethe] Refactoring handling of "final step"
  src/proof/alethe/alethe_post_processor.cpp
  src/proof/alethe/alethe_post_processor.h
Labels: normal, moderate

#11117 Exclude more kinds in getSharableFormula
  src/smt/env.cpp
Labels: normal, simple

#11148 Minor changes to sequence rewriter
  src/theory/strings/sequences_rewriter.cpp
Labels: minor, simple

#11147 Add support for more evaluations in cpc proofs
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/programs/Arith.eo
  src/proof/alf/alf_printer.cpp
Labels: minor, simple

#11143 doc: Note on cross-compiling with POSIX variant of MinGW-w64
  INSTALL.rst
Labels: normal, simple

#11163 cmake: Make sure CMake uses the same version of Java and JNI
  src/api/java/CMakeLists.txt
Labels: normal, moderate

#11161 Add option to print uninterpreted sorts as a datatype in models
  src/options/printer_options.toml
  src/printer/smt2/smt2_printer.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/printer/model-u-print.smt2
Labels: normal, simple

#11131 [alethe] Fixes to arithmetic rules
  src/proof/alethe/alethe_post_processor.cpp
Labels: normal, moderate

#11167 [alethe] Refactor translation of ASSUME/SCOPE
  src/proof/alethe/alethe_post_processor.cpp
  test/regress/cli/CMakeLists.txt
Labels: normal, simple

#11154 More aggressive proof elaboration for strings
  src/theory/strings/infer_proof_cons.cpp
Labels: normal, simple

#11121 [proof checker] Fixes for MACRO_RESOLUTION
  src/theory/booleans/proof_checker.cpp
Labels: normal, moderate

#11171 [alethe] Porting remaining changes
  src/proof/alethe/alethe_post_processor.cpp
Labels: normal, simple

#11173 ci: Use GitHub mirror for CoCoA package
  cmake/FindCoCoA.cmake
Labels: normal, simple, ci

#10529 Adds the Carcara proof checker infrastructure
  contrib/get-carcara-checker
  test/regress/cli/CMakeLists.txt
  test/regress/cli/run_regression.py
Labels: normal, simple

#11174 Fix issue with non-standard RE ranges in regular expression consume
  src/theory/strings/regexp_entail.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/strings/issue11168.smt2
Labels: normal, simple

#11177 Eliminate use of decimals and let in cpc signature
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/programs/Arith.eo
  proofs/eo/cpc/programs/Strings.eo
  proofs/eo/cpc/rules/Arith.eo
  proofs/eo/cpc/rules/Transcendentals.eo
Labels: normal, simple

#11186 Minor fix for MBQI, add regressions for fixed issues
  src/theory/quantifiers/inst_strategy_mbqi.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/sets/proj-issue728.smt2
  test/regress/cli/regress0/sets/proj-issue731.smt2
  test/regress/cli/regress1/seq/proj-issue733-mbqi-w.smt2
Labels: minor, simple
