Repository cvc5/cvc5, pull requests merged in 2024-11, with the labels that each got.

#11325 Fix print benchmark for RegLan
  src/smt/print_benchmark.cpp
Labels: normal, simple

#11317 Add another missing case to Eunoia implementation of STRING_EAGER_REDUCE
  proofs/eo/cpc/programs/Strings.eo
  src/proof/alf/alf_printer.cpp
Labels: minor, simple

#11290 More changes for safe-options
  src/options/base_options.toml
  src/options/printer_options.toml
  src/options/proof_options.toml
  src/options/quantifiers_options.toml
  src/options/sets_options.toml
  src/options/smt_options.toml
  src/smt/set_defaults.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
Labels: normal, simple

#11278 More improvements to final proof statistics
  src/prop/prop_proof_manager.cpp
  src/smt/proof_final_callback.cpp
  src/smt/proof_final_callback.h
  test/regress/cli/regress0/printer/print_trusted_proof_steps.smt2
Labels: minor, simple

#11298 Add Eunoia definition of ARITH_REDUCTION
  proofs/eo/cpc/rules/Arith.eo
  src/proof/alf/alf_printer.cpp
  src/theory/arith/operator_elim.cpp
Labels: normal, simple

#11271 Add proof support in rewrite and extended rewrite preprocessing passes
  src/CMakeLists.txt
  src/preprocessing/passes/extended_rewriter_pass.cpp
  src/preprocessing/passes/extended_rewriter_pass.h
  src/preprocessing/passes/rewrite.cpp
  src/preprocessing/passes/rewrite.h
  src/proof/method_id.cpp
  src/proof/method_id.h
  src/proof/rewrite_proof_generator.cpp
  src/proof/rewrite_proof_generator.h
  src/smt/env.cpp
Labels: normal, simple

#11328 Remove implicit conversion from char const* to bool
  src/proof/dot/dot_printer.cpp
Labels: normal, simple

#11303 Add proof support for several simple elimination theory rewrites
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/theories/Arith.eo
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_rewriter.h
  src/theory/arith/kinds
  src/theory/arith/theory_arith_type_rules.cpp
  src/theory/arith/theory_arith_type_rules.h
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/sets/theory_sets_rewriter.cpp
  src/theory/uf/theory_uf_rewriter.cpp
  test/regress/cli/regress0/arith/bug549.cvc.smt2
  test/regress/cli/regress0/nl/issue10145-ir-pow.smt2
  test/regress/cli/regress0/quantifiers/issue9602-rewrite-pow-type.smt2
  test/regress/cli/regress1/nl/issue9480-pow-pow2.smt2
Labels: minor, simple

#11284 Add a few more proofs for theory rewrites
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/programs/Utils.eo
  proofs/eo/cpc/rules/Arrays.eo
  proofs/eo/cpc/rules/Quantifiers.eo
  proofs/eo/cpc/rules/Uf.eo
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/proof/alf/alf_printer.cpp
  src/theory/arrays/theory_arrays_rewriter.cpp
  src/theory/builtin/theory_builtin_rewriter.cpp
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/datatypes_rewriter.h
  src/theory/uf/theory_uf_rewriter.cpp
  src/theory/uf/theory_uf_rewriter.h
Labels: normal, moderate

#11318 Add a few more simple missing RARE rules
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/theory/booleans/rewrites
  src/theory/uf/rewrites
Labels: minor, simple

#11316 Fixes and changes to BV overflow elimination rules
  proofs/eo/cpc/rules/Rewrites.eo
  src/rewriter/rewrite_db_term_process.cpp
  src/theory/bv/rewrites
  src/theory/bv/rewrites-elimination
Labels: normal, simple

#11335 More RARE string rewrites
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/theory/strings/rewrites
Labels: normal, moderate

#11336 Add RARE rewrites for arith bv conversions
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/theory/uf/rewrites
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/uf-conv-rewrites.smt2
Labels: normal, moderate

#11339 docs: Improve docs for getInterpolant.
  include/cvc5/c/cvc5.h
  include/cvc5/cvc5.h
  src/api/java/io/github/cvc5/Solver.java
  src/api/python/cvc5.pxi
Labels: normal, simple

#11337 Refactoring naming scheme related to experimental theories, include FP
  src/options/bags_options.toml
  src/options/datatypes_options.toml
  src/options/ff_options.toml
  src/options/fp_options.toml
  src/options/sep_options.toml
  src/options/uf_options.toml
  src/smt/set_defaults.cpp
  src/theory/bags/theory_bags.cpp
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/ff/theory_ff.cpp
  src/theory/fp/theory_fp.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/uf/theory_uf.cpp
Labels: normal, simple

#11342 Minor fix in java docs.
  src/api/java/io/github/cvc5/Solver.java
Labels: normal, simple

#11305 Add Eunoia definitions for missing quantifiers rules
  proofs/eo/cpc/rules/Quantifiers.eo
  src/proof/alf/alf_printer.cpp
  src/proof/alf/alf_printer.h
  src/theory/quantifiers/quantifiers_rewriter.cpp
  test/regress/cli/regress0/quantifiers/issue11066-fresh-binders-err.smt2
Labels: normal, moderate

#11313 Add Eunoia definition for ProofRule::ARITH_MULT_TANGENT
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Arith.eo
  proofs/eo/cpc/theories/Arith.eo
  src/proof/alf/alf_printer.cpp
  src/theory/arith/nl/ext/proof_checker.cpp
  src/theory/arith/nl/ext/tangent_plane_check.cpp
Labels: minor, simple

#11333 [CPC] Ensure minus is used in contexts where it can be typed
  contrib/get-ethos-checker
  proofs/eo/cpc/programs/Arith.eo
  proofs/eo/cpc/rules/Arith.eo
  proofs/eo/cpc/rules/Strings.eo
  proofs/eo/cpc/theories/Strings.eo
Labels: normal, simple

#11323 Add proof reconstruction for ProofRewriteRule::MACRO_QUANT_VAR_ELIM_EQ
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Quantifiers.eo
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/proof/alf/alf_printer.cpp
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
Labels: normal, moderate

#11349 Add a few more missing proofs for sets interences
  src/theory/sets/infer_proof_cons.cpp
Labels: normal, simple

#11340 Fix getInterpolant when top-level substitutions are present
  src/smt/abduction_solver.cpp
  src/smt/interpolation_solver.cpp
  src/smt/interpolation_solver.h
  src/smt/solver_engine.cpp
  src/theory/quantifiers/sygus/sygus_interpol.cpp
  src/theory/substitutions.cpp
  src/theory/substitutions.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/interpolant-subs.smt2
Labels: normal, moderate

#11330 Use ALPHA_EQUIV as a reconstruction tactic prior to RARE
  src/rewriter/rewrite_db_proof_cons.cpp
  src/rewriter/rewrite_db_proof_cons.h
Labels: normal, moderate

#11369 Add extensionality rule `ProofRule::STRINGS_EXT` for sequences and strings
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/programs/Strings.eo
  proofs/eo/cpc/rules/Strings.eo
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/proof/alf/alf_printer.cpp
  src/theory/strings/core_solver.cpp
  src/theory/strings/core_solver.h
  src/theory/strings/infer_proof_cons.cpp
  src/theory/strings/proof_checker.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/strings/strings-ext.smt2
Labels: normal, moderate

#11370 Fix proof checking for ProofRule::CONCAT_CONFLICT_DEQ
  src/proof/alf/alf_printer.cpp
  src/theory/strings/proof_checker.cpp
Labels: normal, simple

#11345 Minor updates to BV RARE rules
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/theory/bv/rewrites-elimination
  src/theory/bv/rewrites-simplification
  src/theory/bv/theory_bv_rewriter.cpp
Labels: normal, simple

#11343 ci: Only install ethos and carcara when testing proofs
  .github/actions/setup-cache/action.yml
  .github/workflows/ci.yml
  contrib/get-carcara-checker
  contrib/get-ethos-checker
  contrib/get-lfsc-checker
Labels: normal, simple

#11367 Add trust id for arithmetic DIO lemmas
  src/proof/trust_id.cpp
  src/proof/trust_id.h
  src/theory/arith/linear/theory_arith_private.cpp
Labels: normal, simple

#11346 Fill in remaining datatypes rewrites
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/rewriter/rewrite_db_term_process.cpp
  src/rewriter/rewrite_db_term_process.h
  src/theory/datatypes/datatypes_rewriter.cpp
Labels: normal, simple

#11311 Make interface for ppStaticLearn able to track proofs
  src/preprocessing/passes/static_learning.cpp
  src/theory/arith/linear/arith_static_learner.cpp
  src/theory/arith/linear/arith_static_learner.h
  src/theory/arith/linear/linear_solver.cpp
  src/theory/arith/linear/linear_solver.h
  src/theory/arith/linear/theory_arith_private.cpp
  src/theory/arith/linear/theory_arith_private.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/bv/bv_solver.h
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv.h
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf.h
Labels: normal, moderate

#11304 Add proof support for missing datatypes inferences
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/theory/datatypes/infer_proof_cons.cpp
  src/theory/datatypes/infer_proof_cons.h
  src/theory/datatypes/proof_checker.cpp
Labels: normal, moderate

#11372 Fix issue #11354
  src/parser/smt2/smt2_state.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/datatypes/nullable_checks.smt2
Labels: bug, normal, simple

#11373 Add ProofRewriteRule::DT_CYCLE
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/infer_proof_cons.cpp
Labels: normal, moderate

#11277 Make ExtTheory proof producing
  src/theory/ext_theory.cpp
  src/theory/ext_theory.h
Labels: normal, moderate

#11363 Track more fine grained trust ids in preprocessor
  src/preprocessing/assertion_pipeline.cpp
  src/preprocessing/assertion_pipeline.h
  src/preprocessing/passes/ackermann.cpp
  src/preprocessing/passes/bool_to_bv.cpp
  src/preprocessing/passes/bv_gauss.cpp
  src/preprocessing/passes/bv_intro_pow2.cpp
  src/preprocessing/passes/bv_to_bool.cpp
  src/preprocessing/passes/bv_to_int.cpp
  src/preprocessing/passes/ff_bitsum.cpp
  src/preprocessing/passes/ff_disjunctive_bit.cpp
  src/preprocessing/passes/foreign_theory_rewrite.cpp
  src/preprocessing/passes/fun_def_fmf.cpp
  src/preprocessing/passes/ho_elim.cpp
  src/preprocessing/passes/ite_simp.cpp
  src/preprocessing/passes/learned_rewrite.cpp
  src/preprocessing/passes/miplib_trick.cpp
  src/preprocessing/passes/nl_ext_purify.cpp
  src/preprocessing/passes/non_clausal_simp.cpp
  src/preprocessing/passes/quantifiers_preprocess.cpp
  src/preprocessing/passes/sort_infer.cpp
  src/preprocessing/passes/static_learning.cpp
  src/preprocessing/passes/strings_eager_pp.cpp
  src/preprocessing/passes/theory_preprocess.cpp
  src/preprocessing/passes/unconstrained_simplifier.cpp
  src/proof/trust_id.cpp
  src/proof/trust_id.h
  src/smt/preprocess_proof_generator.cpp
  src/smt/preprocess_proof_generator.h
  src/theory/trust_substitutions.h
Labels: normal, moderate

#11365 Add licensing info for gcc-libs and winpthreads
  .github/actions/add-package/action.yml
  COPYING
  licenses/GCC-exception-3.1.txt
  licenses/winpthreads-LICENSE
  src/api/python/CMakeLists.txt
Labels: normal, simple

#11293 Make quantifiers dynamic split proof producing
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/theory/quantifiers/quant_split.cpp
  src/theory/quantifiers/quant_split.h
  src/theory/quantifiers/quantifiers_rewriter.cpp
Labels: normal, moderate

#11376 Refactor RARE arithmetic rules to avoid mixed arithmetic
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/theory/arith/rewrites
Labels: normal, moderate

#11374 Add three new BV RARE rules for handling TheoryBv::ppAssert
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/rewriter/rewrite_db_proof_cons.cpp
  src/theory/bv/rewrites
Labels: normal, moderate

#11378 Make existing quant miniscope a macro, elaborate to simpler version
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Quantifiers.eo
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/proof/alf/alf_printer.cpp
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/theory/quantifiers/quantifiers_rewriter.cpp
Labels: normal, moderate

#11347 Support bitvectors in Eunoia definition of ARITH_POLY_NORM
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/programs/Arith.eo
  proofs/eo/cpc/programs/PolyNorm.eo
  src/theory/evaluator.cpp
Labels: normal, moderate

#11361 Formalize more quantifiers theory rewrites in Eunoia
  proofs/eo/cpc/rules/Quantifiers.eo
  src/proof/alf/alf_printer.cpp
Labels: normal, moderate

#11381 Handle cases of variable reordering in alpha equivalence proofs
  src/theory/quantifiers/alpha_equivalence.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/quantifiers/alpha-eq-var-reorder.smt2
Labels: normal, moderate

#11383 Make `preregister-mode` a regular option
  src/options/prop_options.toml
Labels: normal, simple

#11360 Add more cases of STRING_REDUCE in Eunoia
  proofs/eo/cpc/programs/Strings.eo
  src/proof/alf/alf_printer.cpp
  src/theory/strings/theory_strings_preprocess.cpp
Labels: normal, moderate

#11344 Do not use cegqi-bv for quantifiers from quantifier elimination
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers/quantifiers_attributes.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/quantifiers/qe-no-skolem.smt2
Labels: normal, simple

#11341 Fix lexer for symbols starting with !
  src/parser/smt2/smt2_lexer.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/bang-lex.smt2
Labels: normal, simple

#11320 Add NodeManager pointer to NodeValue
  src/expr/node.cpp
  src/expr/node.h
  src/expr/node_builder.cpp
  src/expr/node_manager_template.cpp
  src/expr/node_value.cpp
  src/expr/node_value.h
Labels: normal, moderate

#11387 Change ARITH_POLY_NORM_REL to avoid mixed arithmetic
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/programs/PolyNorm.eo
  src/theory/arith/arith_poly_norm.cpp
  src/theory/arith/proof_checker.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/arith-poly-norm-rel-mixed.smt2
Labels: normal, moderate

#11243 Add proof logger interface
  src/CMakeLists.txt
  src/smt/proof_logger.cpp
  src/smt/proof_logger.h
Labels: normal, moderate
