Repository cvc5/cvc5, pull requests merged in 2024-05, with the labels that each got.

#10707 Fixes and additions to evaluation in ALF
  proofs/alf/cvc5/Cvc5.smt3
  proofs/alf/cvc5/programs/Strings.smt3
  proofs/alf/cvc5/programs/Utils.smt3
  src/proof/alf/alf_printer.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/equal-eval-rw_340.smt2
  test/regress/cli/regress0/proofs/indexof-eval-rw_155.smt2
Labels: normal, simple

#10710 Minor optimizations to theory combination utils
  src/expr/kind_template.cpp
  src/expr/kind_template.h
  src/expr/node.h
  src/theory/term_registration_visitor.cpp
  src/theory/theory.cpp
Labels: minor, simple

#10688 Add `-o inst-strategy`
  src/options/base_options.toml
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.h
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/conjecture_generator.h
  src/theory/quantifiers/ematching/instantiation_engine.cpp
  src/theory/quantifiers/ematching/instantiation_engine.h
  src/theory/quantifiers/fmf/model_engine.cpp
  src/theory/quantifiers/inst_strategy_enumerative.cpp
  src/theory/quantifiers/inst_strategy_enumerative.h
  src/theory/quantifiers/inst_strategy_mbqi.h
  src/theory/quantifiers/inst_strategy_pool.cpp
  src/theory/quantifiers/inst_strategy_sub_conflict.cpp
  src/theory/quantifiers/inst_strategy_sub_conflict.h
  src/theory/quantifiers/oracle_engine.cpp
  src/theory/quantifiers/quant_conflict_find.cpp
  src/theory/quantifiers/quant_conflict_find.h
  src/theory/quantifiers/quant_module.cpp
  src/theory/quantifiers/quant_module.h
  src/theory/quantifiers/quantifiers_inference_manager.cpp
  src/theory/quantifiers/quantifiers_inference_manager.h
  src/theory/quantifiers/quantifiers_registry.h
  src/theory/quantifiers/quantifiers_state.h
  src/theory/quantifiers/sygus_inst.cpp
  src/theory/quantifiers/sygus_inst.h
  src/theory/quantifiers_engine.cpp
  src/theory/quantifiers_engine.h
Labels: normal, moderate

#10682 Improve automatic elimination of TRUST
  src/proof/trust_id.cpp
  src/proof/trust_id.h
  src/smt/preprocess_proof_generator.cpp
  src/smt/proof_manager.cpp
  src/smt/proof_post_processor.cpp
  src/smt/proof_post_processor.h
Labels: normal, simple

#10718 Ensure define-fun are printed in unsat core benchmark output
  src/smt/unsat_core_manager.cpp
  src/smt/unsat_core_manager.h
Labels: normal, simple

#10660 Simplify and fix computation of free assumptions
  src/proof/proof_node_algorithm.cpp
  src/prop/prop_engine.cpp
Labels: normal, simple

#10653 ff: add resource limits & fix UNSAT core bug
  src/theory/ff/cocoa_encoder.cpp
  src/theory/ff/cocoa_encoder.h
  src/theory/ff/cocoa_util.cpp
  src/theory/ff/cocoa_util.h
  src/theory/ff/multi_roots.cpp
  src/theory/ff/multi_roots.h
  src/theory/ff/split_gb.cpp
  src/theory/ff/split_gb.h
  src/theory/ff/sub_theory.cpp
  src/theory/ff/util.cpp
  src/theory/ff/util.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/ff/tlimit_per.smt2
  test/unit/theory/theory_ff_multi_roots_black.cpp
  test/unit/theory/theory_ff_split_gb_black.cpp
Labels: normal, moderate

#10721 Fix broken links to SMT-LIB
  docs/binary/binary.rst
  docs/binary/quickstart.rst
  docs/theories/strings.rst
  docs/theories/theories.rst
  src/smt/set_defaults.cpp
  src/smt/smt_mode.h
Labels: major, simple

#10712 Use explicit IMPLIES_ELIM step for explaining theory conflicts
  src/theory/theory_engine.cpp
Labels: minor, simple

#10715 Fix missing delete in prop proof manager
  src/prop/prop_proof_manager.cpp
Labels: major, simple

#10709 win64: Do not export all symbols of parser
  src/parser/CMakeLists.txt
Labels: minor, simple

#10706 Fix performance issues with dynamic quantifiers splitting
  src/theory/quantifiers/first_order_model.cpp
  src/theory/quantifiers/first_order_model.h
  src/theory/quantifiers/quant_split.cpp
  src/theory/quantifiers/quant_split.h
Labels: minor, simple

#10685 Updates to ALF signature for strings
  contrib/get-alf-checker
  proofs/alf/cvc5/programs/Strings.smt3
  proofs/alf/cvc5/programs/Utils.smt3
  proofs/alf/cvc5/rules/Strings.smt3
  src/proof/alf/alf_list_node_converter.cpp
  src/proof/alf/alf_list_node_converter.h
  src/proof/alf/alf_printer.cpp
  src/proof/alf/alf_printer.h
Labels: normal, moderate

#10722 Disable DSL proof on a regression that times out
  test/regress/cli/regress1/quantifiers/bug802.smt2
Labels: major, simple

#10725 test: Add tests for uncovered API coverage.
  test/unit/api/cpp/api_proof_rule_black.cpp
  test/unit/api/cpp/datatype_api_black.cpp
  test/unit/api/java/DatatypeTest.java
  test/unit/api/java/UncoveredTest.cpp
  test/unit/api/python/test_uncovered.cpp
Labels: major, simple

#10663 Add Plugin to the API
  include/cvc5/cvc5.h
  src/api/cpp/cvc5.cpp
  test/unit/api/cpp/solver_black.cpp
Labels: normal, moderate

#10700 Install Python dependencies automatically in venv
  .github/actions/install-dependencies/action.yml
  .github/workflows/ci.yml
  .github/workflows/cmake-version.yml
  CMakeLists.txt
  INSTALL.rst
  cmake/FindCython.cmake
  cmake/Helpers.cmake
  contrib/cibw/before_all_linux.sh
  contrib/cibw/before_all_macos.sh
  contrib/cibw/before_all_windows.sh
  docs/api/python/python.rst
  examples/api/python/CMakeLists.txt
  src/api/python/CMakeLists.txt
  test/binary/CMakeLists.txt
Labels: normal, moderate

#10729 ci: Fix add-package action
  .github/actions/add-package/action.yml
Labels: major, simple, ci

#10711 Simplify policy for Boolean term skolems
  src/prop/cnf_stream.cpp
  src/prop/registrar.h
  src/smt/env.cpp
  src/smt/env.h
  src/smt/term_formula_removal.cpp
  src/smt/term_formula_removal.h
  src/theory/theory.cpp
  src/theory/theory.h
Labels: normal, moderate

#10719 Do not miniscope quantified formulas with user patterns by default
  src/options/quantifiers_options.toml
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/quantifiers/example10714-core-no-miniscope-user.smt2
Labels: normal, simple

#10690 Support erasing substitutions
  src/theory/substitutions.cpp
  src/theory/substitutions.h
Labels: normal, moderate

#10737 Make skolem from ite-simp a purification skolem
  src/theory/arith/arith_ite_utils.cpp
Labels: normal, simple

#10735 Check for divisible by zero in the API
  src/api/cpp/cvc5.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/issue10723-divisible0.smt2
Labels: normal, simple

#10727 Flatten lemmas from oracle engine
  src/theory/quantifiers/oracle_engine.cpp
Labels: normal, simple

#10740 Use purify skolem in ackermann prepreprocessing pass
  src/preprocessing/passes/ackermann.cpp
Labels: minor, simple

#10728 Add datatypes rewrite for constant testers
  src/theory/datatypes/datatypes_rewriter.cpp
Labels: normal, simple

#10726 Ensure operators are traversed when computing hasSubtermKinds
  src/expr/node_algorithm.cpp
Labels: normal, simple

#10730 Initial setup for sets proofs
  src/theory/sets/inference_manager.cpp
  src/theory/sets/inference_manager.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_private.h
  src/theory/sets/theory_sets_rewriter.cpp
  src/theory/sets/theory_sets_rewriter.h
Labels: normal, moderate

#10661 Support `ProofRule::CONCAT_LPROP` in ALF
  include/cvc5/cvc5_proof_rule.h
  proofs/alf/cvc5/rules/Strings.smt3
  src/proof/alf/alf_printer.cpp
  src/theory/strings/core_solver.cpp
Labels: normal, moderate

#10743 Add support for set.is_empty
  docs/theories/sets-and-relations.rst
  include/cvc5/cvc5_kind.h
  proofs/alf/cvc5/theories/Sets.smt3
  proofs/lfsc/signatures/theory_def.plf
  src/api/cpp/cvc5.cpp
  src/parser/smt2/smt2_state.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/sets/kinds
  src/theory/sets/theory_sets_rewriter.cpp
  src/theory/sets/theory_sets_type_rules.cpp
  src/theory/sets/theory_sets_type_rules.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/sets/set_is_empty.smt2
Labels: normal, simple

#10697 Support `ProofRule::CONCAT_CPROP` in ALF
  include/cvc5/cvc5_proof_rule.h
  proofs/alf/cvc5/programs/Nary.smt3
  proofs/alf/cvc5/programs/Strings.smt3
  proofs/alf/cvc5/programs/Utils.smt3
  proofs/alf/cvc5/rules/Strings.smt3
  proofs/alf/cvc5/theories/Sets.smt3
  src/proof/alf/alf_printer.cpp
  src/theory/strings/core_solver.cpp
  src/theory/strings/theory_strings_utils.cpp
  src/theory/strings/theory_strings_utils.h
Labels: normal, moderate

#10744 Add proof rules for sets
  include/cvc5/cvc5_proof_rule.h
  src/CMakeLists.txt
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/theory/sets/proof_checker.cpp
  src/theory/sets/proof_checker.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
Labels: normal, moderate

#10733 cmake: Install Python modules only when --auto-download is given
  CMakeLists.txt
  INSTALL.rst
  cmake/FindCython.cmake
  cmake/Helpers.cmake
  configure.sh
Labels: normal, moderate

#10741 Fixes for Java bindings on Windows
  .github/workflows/ci.yml
  examples/CMakeLists.txt
  examples/api/java/CMakeLists.txt
  src/api/java/CMakeLists.txt
Labels: normal, simple

#10757 cmake: Do not search for Python development artifacts
  CMakeLists.txt
Labels: normal, simple

#10736 Optionally apply substitutions in simplify
  include/cvc5/cvc5.h
  src/api/cpp/cvc5.cpp
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/jni/solver.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
Labels: normal, moderate

#10755 Add callback to restrict which proofs can merge in proof node updater
  src/proof/proof_node_updater.cpp
  src/proof/proof_node_updater.h
  src/smt/proof_post_processor.cpp
  src/smt/proof_post_processor.h
Labels: normal, moderate

#10606 Add module for MBQI + fast sygus enumeration
  src/CMakeLists.txt
  src/theory/quantifiers/inst_strategy_mbqi.h
  src/theory/quantifiers/mbqi_fast_sygus.cpp
  src/theory/quantifiers/mbqi_fast_sygus.h
Labels: major, moderate

#10732 cmake: Fixes in FindCLN
  cmake/FindCLN.cmake
Labels: normal, moderate

#10720 Provide default solutions for unconstrained functions-to-synthesize
  src/expr/node_algorithm.cpp
  src/expr/node_algorithm.h
  src/preprocessing/passes/ackermann.cpp
  src/proof/alf/alf_print_channel.cpp
  src/proof/alf/alf_print_channel.h
  src/proof/alf/alf_printer.cpp
  src/smt/sygus_solver.cpp
  src/smt/sygus_solver.h
  src/theory/arith/nl/icp/icp_solver.cpp
  src/theory/datatypes/sygus_datatype_utils.cpp
  src/theory/datatypes/sygus_datatype_utils.h
  src/theory/quantifiers/sygus/rcons_obligation.cpp
  src/theory/quantifiers/sygus/sygus_reconstruct.cpp
  src/theory/quantifiers/sygus/sygus_utils.cpp
  src/theory/quantifiers/sygus/sygus_utils.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/sygus/print-enumerator.sy
  test/regress/cli/regress0/sygus/print-grammar.sy
  test/regress/cli/regress1/sygus/issue10708-unconstrained-int.sy
Labels: minor, moderate

#10754 Add support for THEORY_REWRITE in ALF
  proofs/alf/cvc5/rules/Uf.smt3
  src/proof/alf/alf_print_channel.cpp
  src/proof/alf/alf_printer.cpp
  src/proof/alf/alf_printer.h
  src/rewriter/rewrite_db_term_process.cpp
  src/theory/builtin/generic_op.h
Labels: normal, simple

#10758 RARE fix: Fixed point syntax sugar
  src/rewriter/mkrewrites.py
  src/rewriter/rw_parser.py
Labels: bug, minor, simple

#10759 Add regressions and option for MBQI + fast sygus
  src/options/quantifiers_options.toml
  src/smt/set_defaults.cpp
  src/theory/quantifiers/inst_strategy_mbqi.cpp
  src/theory/quantifiers/inst_strategy_mbqi.h
  src/theory/quantifiers/mbqi_fast_sygus.cpp
  src/theory/quantifiers/quantifiers_modules.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/ho/dd.lcl720.smt2
  test/regress/cli/regress0/ho/m-enum-bug1.smt2
  test/regress/cli/regress0/ho/m-enum-bug2.smt2
  test/regress/cli/regress0/ho/m-enum-bug3.smt2
  test/regress/cli/regress1/quantifiers/ho-grammar.smt2
  test/regress/cli/regress1/quantifiers/lcl579-2-ho-mbqi.smt2
  test/regress/cli/regress1/quantifiers/mbqi_fast_sy_check_ic.smt2
Labels: major, simple

#10763 Move expansion of MACRO_ARITH_SCALE_SUM_UB to its own utility method
  src/smt/proof_post_processor.cpp
  src/theory/arith/arith_proof_utilities.cpp
  src/theory/arith/arith_proof_utilities.h
Labels: normal, simple

#10761 Add new utilities involving ARITH_POLY_NORM
  src/theory/arith/arith_poly_norm.cpp
  src/theory/arith/arith_poly_norm.h
Labels: normal, moderate

#10698 Support `ProofRule::REGEXP_UNFOLD_NEG_CONCAT_FIXED` in ALF
  include/cvc5/cvc5_proof_rule.h
  proofs/alf/cvc5/rules/Strings.smt3
  src/proof/alf/alf_printer.cpp
  src/theory/strings/infer_proof_cons.cpp
  src/theory/strings/proof_checker.cpp
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/regexp_operation.h
Labels: normal, moderate

#10752 Add new RARE rules for sets
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/rewriter/node.py
  src/rewriter/rewrite_db_proof_cons.cpp
  src/rewriter/rewrite_db_proof_cons.h
  src/rewriter/rewrite_proof_status.cpp
  src/rewriter/rewrite_proof_status.h
  src/theory/sets/rewrites
  src/theory/sets/theory_sets_rewriter.cpp
  src/theory/sets/theory_sets_rewriter.h
  src/theory/theory_rewriter.cpp
  src/theory/theory_rewriter.h
Labels: normal, moderate

#10764 Update ProofRule::THEORY_REWRITE to take an equality
  include/cvc5/cvc5_proof_rule.h
  proofs/alf/cvc5/rules/Strings.smt3
  proofs/alf/cvc5/rules/Uf.smt3
  src/proof/eager_proof_generator.cpp
  src/proof/lfsc/lfsc_post_processor.cpp
  src/proof/proof.cpp
  src/rewriter/basic_rewrite_rcons.cpp
  src/theory/builtin/proof_checker.cpp
Labels: normal, moderate, do not merge

#10767 Handle case where conclusion is null in RARE reconstruction
  src/rewriter/rewrite_db_proof_cons.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/proj-issue723-rdb-step.smt2
Labels: major, simple

#10773 Fix DSL proof reconstruction for THEORY_REWRITE
  src/rewriter/rewrite_db_proof_cons.cpp
Labels: major, simple

#10771 Changes to quantified logics in SMT-COMP script for 2024
  contrib/competitions/smt-comp/run-script-smtcomp-current
Labels: major, simple

#10623 c api: Add term manager, sort creation + tests.
  include/cvc5/c/cvc5.h
  src/api/c/cvc5.cpp
  src/api/c/cvc5_checks.h
  test/unit/api/c/CMakeLists.txt
  test/unit/api/c/capi_term_manager_black.cpp
  test/unit/api/cpp/api_term_manager_black.cpp
Labels: normal, moderate

#10776 Fix repeat substitutions when processing learned literals
  src/prop/zero_level_learner.cpp
  src/prop/zero_level_learner.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/issue10750-zll-repeat.smt2
  test/regress/cli/regress1/proj-issue719-zll-repeat.smt2
Labels: normal, moderate

#10774 Fixes several issues related to DSL/THEORY rewrites
  src/options/proof_options.toml
  src/proof/proof_node_to_sexpr.cpp
  src/rewriter/rewrite_db.cpp
  src/rewriter/rewrite_db_proof_cons.cpp
Labels: normal, moderate

#10780 cmake: Use a CACHE variable for Python_BASE_EXECUTABLE
  CMakeLists.txt
Labels: normal, simple

#10775 Ensure new utilities for ARITH_POLY_NORM are idempotent
  src/theory/arith/arith_poly_norm.cpp
Labels: normal, simple

#10777 Fix type issue in real-to-int prepreprocessing pass
  src/preprocessing/passes/real_to_int.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/nl/issue10724-real-as-int-types.smt2
Labels: minor, simple

#10785 Update AUTHORS file.
  AUTHORS
Labels: major, simple

#10778 Eliminate dependency on cardinality utility in model
  src/theory/strings/base_solver.cpp
  src/theory/theory_model.cpp
  src/theory/theory_model.h
Labels: minor, simple

#10786 Install static libraries for CryptoMiniSat, Kissat, and CoCoA
  cmake/FindCoCoA.cmake
  cmake/FindCryptoMiniSat.cmake
  cmake/FindKissat.cmake
  src/CMakeLists.txt
Labels: normal, simple

#10783 Fix --ff-disjunctive-bit
  src/options/ff_options.toml
  src/smt/process_assertions.cpp
Labels: bug, simple

#10772 Support ProofRule::RE_UNFOLD_NEG in ALF
  include/cvc5/cvc5_proof_rule.h
  proofs/alf/cvc5/rules/Strings.smt3
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/skolem_cache.cpp
Labels: normal, moderate

#10781 Add macro theory rewrite MACRO_BOOL_NNF_NORM
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/proof/trust_id.cpp
  src/proof/trust_id.h
  src/theory/booleans/theory_bool_rewriter.cpp
  src/theory/booleans/theory_bool_rewriter.h
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
Labels: normal, moderate

#10792 Add -o rare-db
  src/options/base_options.toml
  src/proof/alf/alf_printer.h
  src/rewriter/rewrite_db.cpp
  src/rewriter/rewrite_db.h
  src/smt/proof_manager.cpp
  src/smt/solver_engine.cpp
Labels: normal, simple

#10791 Handle concatenations with variables in regexp consume utility
  src/theory/strings/regexp_entail.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/strings/re-consume-bi-dir.smt2
  test/regress/cli/regress0/strings/re-consume-inter.smt2
  test/regress/cli/regress0/strings/re-consume-sym-sigma.smt2
  test/regress/cli/regress0/strings/re-consume-sym.smt2
Labels: major, moderate

#10802 Do not prefix RARE rules with dsl. in ALF
  src/proof/alf/alf_dependent_type_converter.h
  src/proof/alf/alf_list_node_converter.h
  src/proof/alf/alf_printer.cpp
Labels: minor, simple

#10800 Add some theory rewrites for quantifiers
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
Labels: minor, moderate

#10803 Add infrastructure for elaboration of MACRO theory rewrites
  src/proof/proof_node_algorithm.cpp
  src/proof/proof_node_algorithm.h
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/rewriter/rewrite_db_proof_cons.cpp
  src/rewriter/rewrite_db_proof_cons.h
  src/smt/proof_post_processor_dsl.cpp
  src/smt/proof_post_processor_dsl.h
Labels: normal, moderate

#10810 Ensure macro expansion is called in all cases for theory rewrites
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/rewriter/rewrite_db_proof_cons.cpp
Labels: major, moderate

#10782 Add more RARE rewrites for Booleans
  include/cvc5/cvc5_proof_rule.h
  src/theory/booleans/rewrites
Labels: normal, simple

#10815 Add another missing RARE rewrite
  include/cvc5/cvc5_proof_rule.h
  src/smt/proof_post_processor_dsl.cpp
  src/theory/booleans/rewrites
Labels: major, simple, do not merge

#10818 Fix issues related to error handling in the parser
  src/api/cpp/cvc5.cpp
  src/parser/smt2/smt2_term_parser.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/issue10813-1.smt2
  test/regress/cli/regress0/parser/issue10813-2.smt2
  test/unit/api/cpp/term_black.cpp
  test/unit/api/java/TermTest.java
  test/unit/api/python/test_term.py
Labels: normal, moderate

#10819 Disable dsl-proof on two regressions
  test/regress/cli/regress1/quantifiers/qcft-smtlib3dbc51.smt2
  test/regress/cli/regress1/quantifiers/smtlibe99bbe.smt2
Labels: major, simple

#10808 Add support for more arithmetic rewrites in RARE
  include/cvc5/cvc5_proof_rule.h
  src/rewriter/mkrewrites.py
  src/rewriter/node.py
  src/rewriter/rw_parser.py
  src/theory/arith/rewrites
Labels: normal, moderate

#10252 Refresh assertions for get-abduct and get-interpolant
  src/smt/solver_engine.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/issue10788-refresh-a-interp.smt2
Labels: normal, simple

#10799 Simplify ENCODE_PRED_TRANSFORM
  include/cvc5/cvc5_proof_rule.h
  proofs/alf/cvc5/Cvc5.smt3
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/proof/alf/alf_printer.cpp
  src/proof/lfsc/lfsc_printer.cpp
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/rewriter/rewrite_db_proof_cons.cpp
  src/rewriter/rewrite_db_proof_cons.h
  src/rewriter/rewrite_db_term_process.cpp
  src/rewriter/rewrite_db_term_process.h
  src/theory/builtin/proof_checker.cpp
Labels: normal, moderate

#10821 Fix link in proof documentation
  docs/proofs/output_alf.rst
Labels: normal, simple

#10756 Minor updates to skolems
  src/expr/plugin.cpp
  src/theory/quantifiers/skolemize.cpp
  test/regress/cli/regress1/quantifiers/dump-inst-i.smt2
  test/regress/cli/regress1/quantifiers/dump-inst.smt2
  test/regress/cli/regress1/quantifiers/lia-witness-div-pp.smt2
Labels: normal, simple

#10779 Infrastructure for commutative skolems
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/theory/arrays/inference_manager.cpp
Labels: normal, moderate

#10829 test: C API: Don't catch GMP specific error message in unit test.
  test/unit/api/c/capi_term_manager_black.cpp
Labels: major, simple

#10784 Add new string theory rewrites in ALF
  proofs/alf/cvc5/programs/Strings.smt3
  proofs/alf/cvc5/rules/Strings.smt3
  proofs/alf/cvc5/theories/Strings.smt3
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/strings/str-term-small-rw_545.smt2
Labels: normal, moderate

#10696 Add new RARE rewrites for regular expression membership
  include/cvc5/cvc5_proof_rule.h
  src/CMakeLists.txt
  src/theory/strings/rewrites
  src/theory/strings/rewrites-regexp-membership
Labels: normal, moderate

#10768 Refactor strings arithmetic entailment utility
  src/preprocessing/passes/foreign_theory_rewrite.cpp
  src/preprocessing/passes/foreign_theory_rewrite.h
  src/theory/quantifiers/extended_rewrite.cpp
  src/theory/strings/arith_entail.cpp
  src/theory/strings/arith_entail.h
  src/theory/strings/sequences_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/strings/str-term-small-rw_529-arith-subs-ent.smt2
Labels: normal, moderate

#10834 Add implementation of proof rewrite rules for arithmetic string entailment
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_rewriter.h
Labels: normal, moderate

#10838 Refactor strings entailment utility in preparation for new proof rewrite rule
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/strings_entail.cpp
  src/theory/strings/strings_entail.h
Labels: normal, simple
