Repository cvc5/cvc5, pull requests merged in 2024-09, with the labels that each got.

#11181 Pin setuptools to versions below 72.2.0 for PyPy
  src/api/python/pyproject.toml
Labels: normal, simple

#11187 Handle rare case of aliased purification variables in string infer proof cons
  src/smt/proof_post_processor.cpp
  src/theory/strings/infer_proof_cons.cpp
  src/theory/strings/infer_proof_cons.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/strings/issue11164-double-purify.smt2
Labels: minor, simple

#11191 cmake: Pass path of GMP to CLN when building from source
  .github/actions/add-package/action.yml
  cmake/FindCLN.cmake
Labels: normal, simple

#11190 Fix print benchmark utility when :qid is present
  src/smt/print_benchmark.cpp
  src/smt/print_benchmark.h
  src/theory/quantifiers/quantifiers_attributes.cpp
Labels: minor, simple

#11200 Optimizations for checking whether a term is legal for E-matching
  src/theory/quantifiers/ematching/candidate_generator.cpp
  src/theory/quantifiers/ematching/candidate_generator.h
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers/term_database.h
  src/theory/quantifiers/term_util.cpp
  src/theory/quantifiers/term_util.h
Labels: minor, simple

#11194 Make macOS binaries and libraries relocatable
  .github/actions/add-package/action.yml
  cmake/FindCLN.cmake
  cmake/FindGMP.cmake
  cmake/FindPoly.cmake
  cmake/Helpers.cmake
  cmake/update_rpath_macos.cmake
  src/CMakeLists.txt
Labels: normal, moderate

#11205 Fix a few options classification
  src/options/theory_options.toml
Labels: normal, simple

#11178 [alethe] Have Alethe backend better indicate unsupported proofs
  src/proof/alethe/alethe_node_converter.cpp
  src/proof/alethe/alethe_post_processor.cpp
Labels: normal, simple

#11179 [alethe] Enable Alethe tester in regressions
  contrib/get-carcara-checker
  test/regress/cli/regress0/bug1247.smt2
  test/regress/cli/regress0/bv/issue9518.smt2
  test/regress/cli/regress0/datatypes/stream-singleton.smt2
  test/regress/cli/regress0/proofs/issue10278-pf-clone.smt2
  test/regress/cli/regress0/proofs/proj-issue723-rdb-step.smt2
  test/regress/cli/regress0/proofs/proof-components.smt2
  test/regress/cli/regress0/proofs/t1-difficulty-filter.smt2
  test/regress/cli/regress0/proofs/unused-def1.smt2
  test/regress/cli/regress0/proofs/unused-def2.smt2
  test/regress/cli/regress0/quantifiers/dd.ricart-ieval.smt2
  test/regress/cli/regress0/smtlib/issue4552.smt2
  test/regress/cli/regress0/tptp/SYN000=2.smt2
  test/regress/cli/regress1/bv/divtest.smt2
  test/regress/cli/regress1/bv/incorrect1.smtv1.smt2
  test/regress/cli/regress1/bvdiv2.smt2
  test/regress/cli/regress1/proofs/base-lfsc-treesize.smt2
  test/regress/cli/regress1/quantifiers/cee-npnt-dd.smt2
  test/regress/cli/regress1/quantifiers/dd.binary_trees.adb_1105_16_loop_invariant_init_1.smt2
  test/regress/cli/regress1/quantifiers/dd.bug812-ieval.smt2
  test/regress/cli/regress1/quantifiers/ddatv-delta2.smt2
  test/regress/cli/regress1/quantifiers/issue10346-ieval-index-conflict.smt2
  test/regress/cli/regress1/quantifiers/issue3250-syg-inf-q.smt2
  test/regress/cli/regress1/quantifiers/issue6642-em-types.smt2
  test/regress/cli/regress1/quantifiers/issue8410-vts-subtypes.smt2
  test/regress/cli/regress1/quantifiers/issue8456-2-syqi-ic.smt2
  test/regress/cli/regress1/quantifiers/qcft-smtlib3dbc51.smt2
  test/regress/cli/regress1/quantifiers/smtlibe99bbe.smt2
  test/regress/cli/regress1/sets/insert_invariant_37_2.smt2
  test/regress/cli/regress1/strings/issue6913.smt2
  test/regress/cli/run_regression.py
Labels: normal, simple

#11204 Correct incompleteness tracking in incremental mode
  src/preprocessing/passes/real_to_int.cpp
  src/smt/smt_driver.cpp
  src/smt/smt_solver.cpp
  src/theory/incomplete_id.cpp
  src/theory/incomplete_id.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/issue11198-real-as-int.smt2
  test/unit/api/c/capi_result_black.cpp
  test/unit/api/cpp/api_result_black.cpp
  test/unit/api/java/ResultTest.java
  test/unit/api/python/test_result.py
Labels: normal, simple

#11209 [proofs] [alethe] Enable Alethe tester in CI
  .github/actions/setup-cache/action.yml
  .github/workflows/ci.yml
Labels: major, simple

#11202 Do not insist that ensureType is called on instantiations
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/instantiate.h
  src/theory/quantifiers/relevant_domain.cpp
  src/theory/quantifiers/term_util.cpp
  src/theory/quantifiers/term_util.h
Labels: minor, simple

#11203 Standardize ppNotifyAssertions in quantifiers modules
  src/theory/quantifiers/quant_module.h
  src/theory/quantifiers/sygus/synth_engine.cpp
  src/theory/quantifiers/sygus/synth_engine.h
  src/theory/quantifiers/sygus_inst.h
  src/theory/quantifiers_engine.cpp
Labels: minor, simple

#11212 theory fp rewriter: Refactor to not use NodeManager::currentNM().
  src/theory/fp/theory_fp_rewriter.cpp
  src/theory/fp/theory_fp_rewriter.h
Labels: normal, simple

#11216 Fix typos in PropPfManager documentation.
  src/prop/prop_proof_manager.cpp
Labels: minor, simple

#11196 Minor optimizations to getOriginalForm
  src/expr/skolem_manager.cpp
Labels: minor, simple

#11214 theory fp: Refactor theory_fp and fp_expand_defs to not use NodeManager::currentNM().
  src/theory/fp/fp_expand_defs.cpp
  src/theory/fp/fp_expand_defs.h
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp_rewriter.cpp
Labels: normal, simple

#11217 Fix a few cases where rewrites impact user triggers
  src/theory/quantifiers/quant_split.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
Labels: normal, simple

#11195 A few minor changes to how proofs are configured
  src/smt/proof_manager.cpp
  src/smt/set_defaults.cpp
  src/smt/solver_engine.cpp
Labels: minor, simple

#11180 Minor change to explanation in strings
  src/theory/strings/inference_manager.cpp
Labels: normal, simple

#11223 theory sep: Refactor to not use NodeManager::currentNM()
  src/theory/sep/theory_sep.cpp
  src/theory/sep/theory_sep.h
Labels: normal, simple

#11218 Provide histogram of statistics for unsat core lemmas
  src/prop/prop_proof_manager.cpp
  src/prop/prop_proof_manager.h
  src/smt/set_defaults.cpp
Labels: normal, simple

#11224 extended rewrite: Refactor to not use NodeManager::currentNM()
  src/theory/quantifiers/extended_rewrite.cpp
Labels: normal, simple

#11219 regexp operation: Refactor to not use NodeManager::currentNM()
  src/theory/strings/proof_checker.cpp
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/regexp_operation.h
Labels: normal, simple

#11208 [proofs] [alethe] Reenable Alethe regressions and add regression from closed issue
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/issue9515-alethe-skolems-crash.smt2
  test/regress/cli/regress0/proofs/issue9516-alethe-skolems-undef-in-proof.smt2
  test/regress/cli/regress0/proofs/issue9927.smt2
Labels: normal, simple

#11222 arith priv/dio slv/congr mng: Refactor to not use NodeManager::currentNM()
  src/theory/arith/linear/congruence_manager.cpp
  src/theory/arith/linear/dio_solver.cpp
  src/theory/arith/linear/theory_arith_private.cpp
  src/theory/arith/linear/theory_arith_private.h
Labels: normal, simple

#11228 [alethe] Disable incompatible regressions
  test/regress/cli/regress0/use_approx/bug812_approx.smt2
  test/regress/cli/regress0/use_approx/specsharp-WindowsCard.15.RTE.Terminate_System.Int32_approx.smt2
Labels: major, simple

#11230 Add bvnego to LFSC signature
  proofs/lfsc/signatures/theory_def.plf
Labels: major, simple

#11227 strings core solver: Refactor to not use NodeManager::currentNM()
  src/theory/strings/core_solver.cpp
  src/theory/strings/core_solver.h
  src/theory/strings/proof_checker.cpp
Labels: normal, simple

#11229 More fixes for proof configuration in `pp-only` mode
  src/smt/set_defaults.cpp
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/no-proof-uc.smt2
  test/regress/cli/regress0/proofs/pp-only-proof.smt2
Labels: major, simple

#11232 doc: Pass TermManager to Solver in Java examples
  docs/api/java/quickstart.rst
  examples/SimpleVC.java
  examples/api/java/Bags.java
  examples/api/java/BitVectors.java
  examples/api/java/BitVectorsAndArrays.java
  examples/api/java/Combination.java
  examples/api/java/Datatypes.java
  examples/api/java/Exceptions.java
  examples/api/java/Extract.java
  examples/api/java/FiniteField.java
  examples/api/java/HelloWorld.java
  examples/api/java/LinearArith.java
  examples/api/java/Parser.java
  examples/api/java/ParserSymbolManager.java
  examples/api/java/QuickStart.java
  examples/api/java/Relations.java
  examples/api/java/Sequences.java
  examples/api/java/Sets.java
  examples/api/java/Statistics.java
  examples/api/java/Strings.java
  examples/api/java/SygusFun.java
  examples/api/java/SygusInv.java
  examples/api/java/Transcendentals.java
  examples/api/java/Uf.java
  examples/api/java/UnsatCores.java
Labels: normal, simple

#11185 Use smt2 printer for skolems when printing cpc proofs
  contrib/get-ethos-checker
  src/api/cpp/cvc5.cpp
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/printer/let_binding.cpp
  src/printer/let_binding.h
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/proof/alf/alf_node_converter.cpp
  src/proof/alf/alf_print_channel.cpp
  src/proof/alf/alf_printer.cpp
Labels: major, moderate

#11234 More cases to proof elimination of mixed arithmetic
  src/expr/subtype_elim_node_converter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/subtype-elim-1.smt2
  test/regress/cli/regress0/proofs/subtype-elim-2.smt2
Labels: normal, simple

#11210 [proofs] [alethe] Update doc, remove experimental option
  docs/proofs/output_alethe.rst
  src/options/proof_options.toml
  src/smt/set_defaults.cpp
  test/regress/cli/regress0/proofs/alethe-res-need-or-step.smt2
  test/regress/cli/regress0/proofs/issue9393-optResReconstruction-alethebug.smt2
  test/regress/cli/regress0/proofs/issue9515-alethe-skolems-crash.smt2
  test/regress/cli/regress0/proofs/issue9516-alethe-skolems-undef-in-proof.smt2
  test/regress/cli/regress0/proofs/issue9531-alethe-resolution.smt2
  test/regress/cli/regress0/proofs/nomerge-alethe-pf.smt2
  test/regress/cli/run_regression.py
Labels: normal, simple

#11225 bounded integers: Refactor to not use NodeManager::currentNM()
  src/theory/bags/bag_reduction.cpp
  src/theory/bags/inference_generator.cpp
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/fmf/bounded_integers.h
  src/theory/sets/set_reduction.cpp
  src/theory/strings/regexp_elim.cpp
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/theory_strings_utils.cpp
  src/theory/strings/theory_strings_utils.h
Labels: normal, simple

#11233 Add getNamedTerms to symbol manager API
  NEWS.md
  include/cvc5/c/cvc5_parser.h
  include/cvc5/cvc5_parser.h
  src/api/c/cvc5_parser.cpp
  src/api/cpp/cvc5_parser.cpp
  src/api/java/io/github/cvc5/SymbolManager.java
  src/api/java/jni/symbol_manager.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  test/unit/api/c/capi_symbol_manager_black.cpp
  test/unit/api/cpp/api_symbol_manager_black.cpp
  test/unit/api/java/SymbolManagerTest.java
  test/unit/api/python/test_symbol_manager.py
Labels: normal, moderate

#11159 Remove option `strings-code-elim`
  include/cvc5/cvc5_proof_rule.h
  src/options/strings_options.toml
  src/theory/strings/rewrites
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/theory_strings_type_rules.cpp
  test/regress/cli/regress0/strings/issue5816-re-kind.smt2
  test/regress/cli/regress0/strings/model-code-point.smt2
  test/regress/cli/regress0/strings/simple-nth-fail.smt2
  test/regress/cli/regress1/decision/jh-test1.smt2
  test/regress/cli/regress1/strings/str-code-sat.smt2
  test/regress/cli/regress1/strings/strings-code-elim-min.smt2
  test/regress/cli/regress1/strings/to_upper_12.smt2
  test/regress/cli/regress1/strings/to_upper_over_concat.smt2
Labels: normal, simple

#11193 Make RARE rewrites static in CPC signature
  contrib/install-rare-rewrites
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/rules/Rewrites.eo
  proofs/eo/cpc/theories/BitVectors.eo
  src/proof/alf/alf_printer.cpp
  src/proof/alf/alf_printer.h
  src/rewriter/README.md
Labels: major, moderate
