Repository cvc5/cvc5, pull requests merged in 2024-12, with the labels that each got.

#11398 Alethe: add name of trust rule as argument to alethe hole rules
  src/proof/alethe/alethe_post_processor.cpp
Labels: minor, simple

#11368 Create self-contained JARs for cvc5 Java bindings
  .github/actions/add-jar/action.yml
  .github/actions/add-package/action.yml
  .github/actions/store-to-latest/action.yml
  .github/actions/store-to-release/action.yml
  .github/workflows/ci.yml
  src/api/java/io/github/cvc5/Utils.java
Labels: normal, moderate

#11375 Minor simplifications to theory interfaces
  src/smt/expand_definitions.cpp
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_rewriter.h
  src/theory/arrays/theory_arrays.cpp
  src/theory/arrays/theory_arrays.h
  src/theory/arrays/theory_arrays_rewriter.cpp
  src/theory/arrays/theory_arrays_rewriter.h
  src/theory/booleans/theory_bool.cpp
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv_rewriter.cpp
  src/theory/bv/theory_bv_rewriter.h
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/datatypes_rewriter.h
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/fp/fp_expand_defs.cpp
  src/theory/fp/fp_expand_defs.h
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp_rewriter.cpp
  src/theory/fp/theory_fp_rewriter.h
  src/theory/quantifiers/theory_quantifiers.cpp
  src/theory/sets/theory_sets.cpp
  src/theory/theory.cpp
  src/theory/theory.h
  src/theory/theory_rewriter.cpp
  src/theory/theory_rewriter.h
Labels: minor, simple

#11384 Fix some typos in the documentation of two proof rules
  include/cvc5/cvc5_proof_rule.h
Labels: minor, simple

#11364 Add infrastructure for proofs for witness terms
  src/CMakeLists.txt
  src/expr/elim_witness_converter.cpp
  src/proof/trust_id.cpp
  src/proof/trust_id.h
  src/proof/valid_witness_proof_generator.cpp
  src/proof/valid_witness_proof_generator.h
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.h
Labels: normal, moderate

#11400 Make QUANT_MERGE_PRENEX not eliminate duplicate variables, update QUANT_UNUSED_VARS
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Quantifiers.eo
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/rewriter/rewrite_db_proof_cons.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/quantifiers/merge-shadow.smt2
Labels: normal, moderate

#11391 Add generic macro for rewriting body of quantified formulas
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/theory/arrays/rewrites
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
  src/theory/uf/rewrites
Labels: normal, moderate

#11404 Add proper interface for skolem information in Node
  src/api/cpp/cvc5.cpp
  src/expr/CMakeLists.txt
  src/expr/dtype_cons.cpp
  src/expr/internal_skolem_id.cpp
  src/expr/internal_skolem_id.h
  src/expr/node.cpp
  src/expr/node.h
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/expr/sygus_grammar.cpp
  src/theory/datatypes/sygus_datatype_utils.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
Labels: normal, moderate

#11405 Disable cpc on regression
  test/regress/cli/regress1/quantifiers/cdt-0208-to.smt2
Labels: major, simple

#11394 sygus: Refactor to not use NodeManager::currentNM()
  src/preprocessing/passes/synth_rew_rules.cpp
  src/smt/abduction_solver.cpp
  src/smt/env.cpp
  src/smt/env.h
  src/theory/quantifiers/sygus/cegis_core_connective.cpp
  src/theory/quantifiers/sygus/cegis_core_connective.h
  src/theory/quantifiers/sygus/example_infer.cpp
  src/theory/quantifiers/sygus/rcons_obligation.cpp
  src/theory/quantifiers/sygus/rcons_type_info.cpp
  src/theory/quantifiers/sygus/sygus_abduct.cpp
  src/theory/quantifiers/sygus/sygus_abduct.h
  src/theory/quantifiers/sygus/sygus_explain.cpp
  src/theory/quantifiers/sygus/sygus_explain.h
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.h
  src/theory/quantifiers/sygus/sygus_grammar_norm.cpp
  src/theory/quantifiers/sygus/sygus_grammar_norm.h
  src/theory/quantifiers/sygus/sygus_invariance.cpp
  src/theory/quantifiers/sygus/sygus_repair_const.cpp
  src/theory/quantifiers/sygus/sygus_unif_io.cpp
  src/theory/quantifiers/sygus/sygus_unif_io.h
  src/theory/quantifiers/sygus/sygus_unif_rl.cpp
  src/theory/quantifiers/sygus/sygus_utils.cpp
Labels: normal, moderate

#11407 Refactoring set defaults for safe options, full strict proofs
  src/options/arith_options.toml
  src/options/uf_options.toml
  src/smt/set_defaults.cpp
Labels: normal, moderate

#11408 Fix reconstruction for MACRO_NNF_NORM
  src/expr/term_context.cpp
  src/expr/term_context.h
  src/rewriter/basic_rewrite_rcons.cpp
  src/theory/booleans/theory_bool_rewriter.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/dd_pf_739.smt2
  test/regress/cli/regress0/proofs/dd_spark_nnf_pf.smt2
Labels: normal, moderate

#11413 Make macro reconstruction robust to partial failures
  src/rewriter/basic_rewrite_rcons.cpp
  src/smt/proof_post_processor_dsl.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/dd_ada_open.smt2
Labels: normal, simple

#11414 [proofs] [alethe] Remove from node converter unsupported quantifier kinds
  src/proof/alethe/alethe_node_converter.cpp
Labels: normal, simple

#11411 Handle INST_CONSTANT properly in cpc proofs
  src/proof/alf/alf_node_converter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/dd_ic_pf_764.smt2
  test/regress/cli/regress0/proofs/dd_spark_nnf_pf.smt2
Labels: normal, simple

#11389 Minor changes to Bool RARE rewrites
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/theory/booleans/rewrites
Labels: normal, simple

#11419 Fix evaluator for prefixof in Eunoia
  proofs/eo/cpc/Cpc.eo
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/pfcheck_rw_441.smt2
Labels: normal, simple

#11422 Fix corner case in arithmetic congruence manager proofs
  src/theory/arith/linear/congruence_manager.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/t3_rw903.smt2
Labels: normal, simple

#11417 Fix negative pow 2 RARE rewrites for bvmul
  proofs/eo/cpc/rules/Rewrites.eo
  src/theory/bv/rewrites-simplification
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/bv-mul-pow2-neg-middle.smt2
Labels: normal, moderate

#11297 Add ProofRule::ARITH_MULT_ABS_COMPARISON
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/CMakeLists.txt
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/proof/trust_id.cpp
  src/proof/trust_id.h
  src/theory/arith/arith_utilities.cpp
  src/theory/arith/arith_utilities.h
  src/theory/arith/nl/ext/arith_nl_compare_proof_gen.cpp
  src/theory/arith/nl/ext/arith_nl_compare_proof_gen.h
  src/theory/arith/nl/ext/ext_state.cpp
  src/theory/arith/nl/ext/monomial.cpp
  src/theory/arith/nl/ext/monomial_check.cpp
  src/theory/arith/nl/ext/monomial_check.h
  src/theory/arith/nl/ext/proof_checker.cpp
  src/theory/arith/rewrites
Labels: normal, moderate

#11416 Fix RARE reconstruction strategy for preprocessed terms
  src/rewriter/rewrite_db_proof_cons.cpp
  src/rewriter/rewrite_db_proof_cons.h
Labels: normal, moderate

#11421 Add macro and elaboration for quantifiers prenex
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/theory/quantifiers/quantifiers_preprocess.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/macro-quant-prenex-simple.smt2
Labels: normal, moderate

#11432 Replace calls to currentNM with calls to NM static methods
  src/expr/annotation_elim_node_converter.cpp
  src/expr/bound_var_manager.cpp
  src/proof/trust_node.cpp
  src/smt/print_benchmark.cpp
  src/theory/arith/arith_msum.h
  src/theory/arith/arith_utilities.cpp
  src/theory/arith/arith_utilities.h
  src/theory/arith/linear/normal_form.cpp
  src/theory/arith/nl/coverings/cdcac.cpp
  src/theory/arith/nl/iand_utils.cpp
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/arith/rewriter/node_utils.cpp
  src/theory/arith/rewriter/rewrite_atom.cpp
  src/theory/bags/bags_utils.cpp
  src/theory/bv/bitblast/bitblast_utils.h
  src/theory/bv/theory_bv_rewrite_rules_normalization.h
  src/theory/bv/theory_bv_rewrite_rules_operator_elimination.h
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
  src/theory/bv/theory_bv_utils.cpp
  src/theory/datatypes/theory_datatypes_utils.cpp
  src/theory/fp/fp_word_blaster.cpp
  src/theory/quantifiers/bv_inverter.cpp
  src/theory/quantifiers/bv_inverter_utils.cpp
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_utils.h
  src/theory/quantifiers/cegqi/nested_qe.cpp
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/ematching/ho_trigger.cpp
  src/theory/quantifiers/ematching/pattern_term_selector.cpp
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/term_util.cpp
  src/theory/sets/normal_form.h
  src/theory/sets/rels_utils.cpp
  src/theory/strings/arith_entail.cpp
  src/theory/strings/strings_entail.cpp
  src/theory/strings/term_registry.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/theory_strings_utils.cpp
  src/theory/theory_engine.cpp
Labels: normal, simple

#11435 node/type_node/flatten: Eliminate calls to NodeManager::currentNM()
  src/expr/algorithm/flatten.h
  src/expr/node.h
  src/expr/type_node.cpp
  src/expr/type_node.h
  src/theory/arith/arith_rewriter.cpp
  src/theory/ff/theory_ff_rewriter.cpp
  test/unit/node/node_algorithms_black.cpp
Labels: normal, simple

#11428 Move definition of ACI_NORM to own file
  src/expr/CMakeLists.txt
  src/expr/aci_norm.cpp
  src/expr/aci_norm.h
  src/expr/nary_term_util.cpp
  src/expr/nary_term_util.h
  src/proof/alf/alf_node_converter.cpp
  src/proof/lfsc/lfsc_node_converter.cpp
  src/proof/lfsc/lfsc_node_converter.h
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/rewrite_db_proof_cons.cpp
  src/rewriter/rewrite_db_term_process.cpp
  src/rewriter/rewrite_proof_rule.cpp
  src/theory/builtin/proof_checker.cpp
Labels: minor, simple

#11437 Fix within-kind term context
  src/expr/term_context.cpp
Labels: major, simple

#11438 Use standard ground term skolem in quant term database
  src/theory/quantifiers/term_database.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/quantifiers/inst-ground-term.smt2
Labels: minor, simple

#11439 Do not handle ENCODE_EQ_INTRO in LFSC
  src/proof/lfsc/lfsc_printer.cpp
  src/smt/proof_post_processor_dsl.cpp
Labels: major, simple

#11440 Add two macro rewrites for arrays
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/theory/arrays/theory_arrays_rewriter.cpp
Labels: minor, simple

#11431 Refactor and extend quantifiers miniscope proof rules
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Quantifiers.eo
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/proof/alf/alf_printer.cpp
  src/rewriter/basic_rewrite_rcons.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/quantifiers/miniscope-ite.smt2
Labels: normal, moderate

#11409 Add infrastructure for proofs for DIAMONDS ppStaticLearn
  src/CMakeLists.txt
  src/proof/trust_id.cpp
  src/proof/trust_id.h
  src/theory/uf/diamonds_proof_generator.cpp
  src/theory/uf/diamonds_proof_generator.h
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf.h
Labels: normal, simple

#11348 Support empty set and sequence in RARE
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/programs/Strings.eo
  proofs/eo/cpc/rules/Rewrites.eo
  proofs/eo/cpc/theories/Strings.eo
  src/expr/nary_term_util.cpp
  src/printer/smt2/smt2_printer.cpp
  src/proof/alf/alf_list_node_converter.cpp
  src/proof/alf/alf_list_node_converter.h
  src/proof/alf/alf_printer.cpp
  src/proof/alf/alf_printer.h
  src/rewriter/node.py
  src/rewriter/rewrite_proof_rule.cpp
  src/rewriter/rewrite_proof_rule.h
  src/theory/builtin/kinds
  src/theory/builtin/theory_builtin_type_rules.cpp
  src/theory/builtin/theory_builtin_type_rules.h
  src/theory/sets/kinds
  src/theory/sets/rewrites
  src/theory/sets/theory_sets_type_rules.cpp
  src/theory/sets/theory_sets_type_rules.h
  src/theory/strings/kinds
  src/theory/strings/rewrites
  src/theory/strings/theory_strings_type_rules.cpp
  src/theory/strings/theory_strings_type_rules.h
Labels: normal, moderate

#11436 Eliminate some calls to NodeManager::{currentNM,getSkolemManager}
  src/expr/subs.cpp
  src/expr/subtype_elim_node_converter.cpp
  src/expr/sygus_term_enumerator.cpp
  src/preprocessing/passes/ackermann.cpp
  src/preprocessing/passes/fun_def_fmf.cpp
  src/preprocessing/passes/ho_elim.cpp
  src/preprocessing/passes/int_to_bv.cpp
  src/preprocessing/passes/miplib_trick.cpp
  src/preprocessing/passes/nl_ext_purify.cpp
  src/preprocessing/passes/sep_skolem_emp.cpp
  src/preprocessing/passes/unconstrained_simplifier.cpp
  src/preprocessing/util/ite_utilities.cpp
  src/rewriter/rewrite_db_term_process.cpp
  src/smt/term_formula_removal.cpp
  src/theory/arith/linear/callbacks.cpp
  src/theory/arith/linear/dio_solver.cpp
  src/theory/arith/linear/theory_arith_private.cpp
  src/theory/arith/nl/coverings_solver.cpp
  src/theory/bags/solver_state.cpp
  src/theory/bv/theory_bv_utils.cpp
  src/theory/datatypes/sygus_extension.cpp
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/fp/fp_word_blaster.cpp
  src/theory/quantifiers/bv_inverter.cpp
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/dynamic_rewrite.cpp
  src/theory/quantifiers/expr_miner.cpp
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/quantifiers/fmf/first_order_model_fmc.cpp
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/single_inv_partition.cpp
  src/theory/quantifiers/skolemize.cpp
  src/theory/quantifiers/sygus/ce_guided_single_inv.cpp
  src/theory/quantifiers/sygus/cegis_unif.cpp
  src/theory/quantifiers/sygus/rcons_type_info.cpp
  src/theory/quantifiers/sygus/sygus_abduct.cpp
  src/theory/quantifiers/sygus/sygus_qe_preproc.cpp
  src/theory/quantifiers/sygus/sygus_random_enumerator.cpp
  src/theory/quantifiers/sygus/sygus_unif_rl.cpp
  src/theory/quantifiers/sygus/sygus_unif_strat.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  src/theory/quantifiers/sygus/template_infer.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/quantifiers/sygus/transition_inference.cpp
  src/theory/quantifiers/sygus_inst.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/sets/cardinality_extension.cpp
  src/theory/sets/skolem_cache.cpp
  src/theory/sets/theory_sets_rels.cpp
  src/theory/sort_inference.cpp
  src/theory/strings/regexp_operation.cpp
  src/theory/strings/skolem_cache.cpp
  src/theory/uf/cardinality_extension.cpp
  src/theory/uf/ho_extension.cpp
Labels: normal, simple

#11423 theory/uf: Refactor to not use NodeManager::currentNM()
  src/expr/node_manager_template.cpp
  src/expr/node_manager_template.h
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/theory/uf/cardinality_extension.cpp
  src/theory/uf/conversions_solver.cpp
  src/theory/uf/eq_proof.cpp
  src/theory/uf/function_const.cpp
  src/theory/uf/lambda_lift.cpp
  src/theory/uf/theory_uf_model.cpp
  src/theory/uf/theory_uf_rewriter.cpp
  src/theory/uf/theory_uf_type_rules.cpp
  src/theory/uf/type_enumerator.cpp
Labels: normal, moderate

#11450 Generalize elaboration for quant prenex to handle nested cases
  src/rewriter/basic_rewrite_rcons.cpp
Labels: normal, moderate

#11443 Add Eunoia definitions of 3 datatype ad-hoc rewrites
  proofs/eo/cpc/programs/Datatypes.eo
  proofs/eo/cpc/programs/Utils.eo
  proofs/eo/cpc/rules/Datatypes.eo
  src/proof/alf/alf_printer.cpp
  test/regress/cli/regress1/quantifiers/stream-x2014-09-18-unsat.smt2
Labels: normal, moderate

#11449 Add Eunoia definitions for 3 simple theory rewrites
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/programs/Arith.eo
  proofs/eo/cpc/programs/BitVectors.eo
  proofs/eo/cpc/rules/Arith.eo
  proofs/eo/cpc/rules/BitVectors.eo
  proofs/eo/cpc/rules/Sets.eo
  src/proof/alf/alf_printer.cpp
  src/theory/sets/theory_sets_rewriter.cpp
Labels: normal, moderate

#11455 Fix Eunoia definition of ARRAYS_READ_OVER_WRITE_CONTRA
  proofs/eo/cpc/rules/Arrays.eo
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/ios_np_sf.smt2
Labels: major, simple

#11457 Eliminate more calls to NodeManager::{currentNM,getSkolemManager}
  src/expr/bound_var_manager.h
  src/expr/elim_shadow_converter.cpp
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/printer/let_binding.cpp
  src/proof/alethe/alethe_node_converter.cpp
  src/smt/proof_post_processor_dsl.cpp
  src/theory/arith/arith_utilities.cpp
  src/theory/arith/linear/normal_form.h
  src/theory/arith/nl/coverings/proof_generator.cpp
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/arith/nl/transcendental/taylor_generator.cpp
  src/theory/arrays/theory_arrays_type_rules.cpp
  src/theory/bags/theory_bags_type_rules.cpp
  src/theory/conflict_processor.cpp
  src/theory/datatypes/sygus_datatype_utils.cpp
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/quantifiers/cegqi/nested_qe.cpp
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/ematching/ho_trigger.cpp
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/quantifiers/ho_term_database.cpp
  src/theory/quantifiers/inst_strategy_sub_conflict.cpp
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/mbqi_fast_sygus.cpp
  src/theory/quantifiers/oracle_engine.cpp
  src/theory/quantifiers/skolemize.cpp
  src/theory/quantifiers/sygus/sygus_enumerator.cpp
  src/theory/quantifiers/sygus/transition_inference.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_rels.cpp
  src/theory/strings/infer_proof_cons.cpp
  src/theory/strings/term_registry.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/word.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_model_builder.cpp
Labels: normal, simple

#11458 Disable unsat-core tester on t3_rw903
  test/regress/cli/regress0/proofs/t3_rw903.smt2
Labels: major, simple

#11456 Several fixes for quantifiers rewrite proofs
  proofs/eo/cpc/rules/Quantifiers.eo
  src/rewriter/basic_rewrite_rcons.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/quantifiers/dd_spark2014-pat.smt2
  test/regress/cli/regress1/quantifiers/quick-sort-q-rew.smt2
Labels: major, simple

#11459 preprocessing/proof: Refactor to not use NodeManager::currentNM()
  src/preprocessing/passes/synth_rew_rules.cpp
  src/preprocessing/passes/synth_rew_rules.h
  src/proof/lazy_proof.cpp
  src/proof/lazy_tree_proof_generator.cpp
  src/proof/method_id.cpp
  src/proof/method_id.h
  src/proof/proof.cpp
  src/proof/proof_node_algorithm.cpp
  src/proof/proof_node_manager.cpp
  src/proof/proof_rule_checker.cpp
  src/proof/proof_rule_checker.h
  src/proof/proof_step_buffer.cpp
  src/proof/resolution_proofs_util.cpp
  src/proof/resolution_proofs_util.h
  src/proof/rewrite_proof_generator.cpp
  src/proof/subtype_elim_proof_converter.cpp
  src/proof/theory_proof_step_buffer.cpp
  src/proof/trust_id.cpp
  src/proof/trust_id.h
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/rewrite_db_proof_cons.cpp
  src/smt/proof_post_processor.cpp
  src/smt/solver_engine.cpp
  src/theory/arrays/inference_manager.cpp
  src/theory/datatypes/infer_proof_cons.cpp
  src/theory/quantifiers/alpha_equivalence.cpp
  src/theory/rewriter.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/sets/inference_manager.cpp
  src/theory/strings/infer_proof_cons.cpp
  src/theory/theory_preprocessor.cpp
  src/theory/uf/eq_proof.cpp
Labels: normal, simple

#11464 Disable lfsc tester on t3_rw903
  test/regress/cli/regress0/proofs/t3_rw903.smt2
Labels: major, simple

#11388 Only try to use basic rewriter to automatically reconstruct trust steps
  src/smt/proof_post_processor.cpp
Labels: minor, simple

#11454 Add proof support for quantifiers term indexing conflicts
  src/theory/quantifiers/ho_term_database.cpp
  src/theory/quantifiers/term_database.cpp
  src/theory/quantifiers/term_database.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/quantifiers/pivc-deq-cong.smt2
Labels: normal, simple

#11415 Fix issues with shared selectors in proofs
  proofs/eo/cpc/theories/Datatypes.eo
  src/proof/alf/alf_node_converter.cpp
  src/smt/set_defaults.cpp
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/proof_checker.cpp
  src/theory/datatypes/proof_checker.h
  src/theory/datatypes/theory_datatypes.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/datatypes/pf-v2l60078.smt2
Labels: major, simple

#11430 Minor fixes for printers
  src/printer/ast/ast_printer.cpp
  src/printer/smt2/smt2_printer.cpp
Labels: minor, simple

#11377 Do not print BITVECTOR_EAGER_ATOM in cpc proofs
  proofs/eo/cpc/theories/BitVectors.eo
  src/proof/alf/alf_node_converter.cpp
  src/proof/alf/alf_printer.cpp
Labels: minor, simple

#11465 Do not rewrite datatype inferences prior to proof reconstruction
  src/theory/datatypes/inference_manager.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/quantifiers/dd_SA10-027-dt-ipc.smt2
Labels: normal, simple

#11468 Fix LFSC in nightlies
  src/proof/lfsc/lfsc_printer.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/sep/theory_sep.h
  test/regress/cli/run_regression.py
Labels: major, simple

#11470 Disable timeout regression
  test/regress/cli/CMakeLists.txt
Labels: major, simple
