Repository cvc5/cvc5, pull requests merged in 2024-04, with the labels that each got.

#10569 ci: Set up Python virtual environment
  .github/actions/install-dependencies/action.yml
  .github/actions/run-tests/action.yml
Labels: major, simple, ci

#10567 Fix more issues with uncovered methods in nightlies
  test/regress/cli/regress0/fp/rti_3_5_bug.smt2
  test/unit/api/cpp/api_skolem_id_black.cpp
  test/unit/api/java/UncoveredTest.cpp
  test/unit/api/python/test_uncovered.cpp
Labels: major, simple

#10554 ci: Build Python wheels for arm64 Linux
  .github/workflows/package_pypi.yml
Labels: normal, simple, ci

#10519 Add rewrites for new internal BV operators
  src/theory/bv/theory_bv_rewrite_rules.h
  src/theory/bv/theory_bv_rewrite_rules_constant_evaluation.h
  src/theory/bv/theory_bv_rewrite_rules_operator_elimination.h
  src/theory/bv/theory_bv_rewriter.cpp
  src/theory/bv/theory_bv_rewriter.h
Labels: normal, simple

#10530 c++ API: Refactor statistics handling.
  docs/api/cpp/cpp.rst
  docs/api/cpp/statistics.rst
  docs/api/python/base/statistics.rst
  docs/conf.py.in
  include/cvc5/cvc5.h
  src/api/cpp/cvc5.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/expr/node_manager_template.h
  src/main/command_executor.cpp
  test/unit/api/cpp/CMakeLists.txt
  test/unit/api/cpp/api_term_manager_black.cpp
  test/unit/api/cpp/solver_black.cpp
  test/unit/api/java/SolverTest.java
  test/unit/api/python/test_solver.py
  test/unit/api/python/test_term_manager.py
Labels: normal, moderate

#10545 Add node manager to node converter
  src/expr/annotation_elim_node_converter.cpp
  src/expr/annotation_elim_node_converter.h
  src/expr/elim_shadow_converter.cpp
  src/expr/elim_shadow_converter.h
  src/expr/node_converter.cpp
  src/expr/node_converter.h
  src/expr/subtype_elim_node_converter.cpp
  src/expr/subtype_elim_node_converter.h
  src/proof/alethe/alethe_node_converter.cpp
  src/proof/alethe/alethe_node_converter.h
  src/proof/alf/alf_node_converter.cpp
  src/proof/alf/alf_node_converter.h
  src/proof/lfsc/lfsc_list_sc_node_converter.cpp
  src/proof/lfsc/lfsc_list_sc_node_converter.h
  src/proof/lfsc/lfsc_node_converter.cpp
  src/proof/lfsc/lfsc_node_converter.h
  src/proof/lfsc/lfsc_printer.cpp
  src/proof/proof_rule_checker.cpp
  src/proof/proof_rule_checker.h
  src/proof/subtype_elim_proof_converter.cpp
  src/rewriter/rewrite_db_proof_cons.cpp
  src/rewriter/rewrite_db_term_process.cpp
  src/rewriter/rewrite_db_term_process.h
  src/smt/proof_manager.cpp
  src/smt/quant_elim_solver.cpp
  src/smt/solver_engine.cpp
  src/theory/builtin/proof_checker.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/oracle_checker.cpp
  src/theory/quantifiers/oracle_checker.h
  src/theory/quantifiers/sygus/sygus_reconstruct.cpp
  src/theory/theory_rewriter.cpp
  src/theory/theory_rewriter.h
  src/theory/uf/theory_uf_rewriter.cpp
Labels: minor, simple

#10524 Fix model soundness with `--sygus-inst --no-cegqi`
  src/theory/quantifiers/ematching/inst_match_generator_simple.cpp
  src/theory/quantifiers/instantiate.cpp
  src/theory/quantifiers/quant_conflict_find.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/quantifiers/ari-syqi.smt2
Labels: normal, simple

#10531 Java API: Refactor to expose TermManager.
  docs/api/java/index.rst
  docs/api/java/java.rst
  src/api/java/CMakeLists.txt
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/io/github/cvc5/TermManager.java
  src/api/java/jni/solver.cpp
  src/api/java/jni/term_manager.cpp
  test/unit/api/cpp/api_term_manager_black.cpp
  test/unit/api/java/DatatypeTest.java
  test/unit/api/java/FiniteFieldTest.java
  test/unit/api/java/GrammarTest.java
  test/unit/api/java/OpTest.java
  test/unit/api/java/ParserTest.java
  test/unit/api/java/ProofTest.java
  test/unit/api/java/ResultTest.java
  test/unit/api/java/SolverTest.java
  test/unit/api/java/SortTest.java
  test/unit/api/java/SynthResultTest.java
  test/unit/api/java/TermManagerTest.java
  test/unit/api/java/TermTest.java
  test/unit/api/java/UncoveredTest.cpp
Labels: normal, moderate

#10523 Fix usage of purify skolems in MBQI
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/theory/quantifiers/inst_strategy_mbqi.cpp
  src/theory/quantifiers/inst_strategy_mbqi.h
Labels: normal, moderate

#10525 ci: Set macOS version with MACOSX_DEPLOYMENT_TARGET
  .github/actions/configure-and-build/action.yml
  .github/actions/install-dependencies/action.yml
  .github/workflows/ci.yml
  cmake/FindGMP.cmake
Labels: minor, simple, ci

#10479 Update names for internal BV operators
  proofs/alf/cvc5/theories/BitVectors.smt3
  src/printer/smt2/smt2_printer.cpp
  src/proof/alf/alf_node_converter.cpp
  src/proof/lfsc/lfsc_node_converter.cpp
Labels: normal, simple

#10526 Fixes for HO model building
  src/theory/theory_model.cpp
  src/theory/theory_model.h
  src/theory/theory_model_builder.cpp
  src/theory/uf/ho_extension.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/ho/model-lam-simple.smt2
Labels: normal, moderate

#10577 Add value-based refinement for arith/bv conversion
  src/options/uf_options.toml
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/uf/conversions_solver.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/bv-conv-value-refine.smt2
Labels: normal, simple

#10511 Remove spurious check for incremental with unsat core assumptions
  src/api/cpp/cvc5.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/issue10489.smt2
Labels: normal, simple

#10570 PyPi: Set up Python virtual environment
  .github/workflows/package_pypi.yml
  contrib/cibw/before_all_macos.sh
Labels: normal, simple, ci

#10579 Add portfolio config option
  src/base/configuration.cpp
  src/base/configuration.h
  src/base/configuration_private.h
  src/options/options_handler.cpp
  test/regress/cli/regress0/printer/portfolio-out.smt2
Labels: normal, simple

#10580 Ensure ACI_NORM is deterministic wrt ordering
  src/expr/nary_term_util.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/RF-11-aci-norm-ndet.smt2
Labels: normal, simple

#10572 Silence test regress3/issue4170.smt
  test/regress/cli/regress3/issue4170.smt2
Labels: normal, simple

#10571 Replace CVC5_FATAL with Exception for unexpected results
  src/smt/solver_engine_state.cpp
  test/regress/cli/regress0/smtlib/set-info-status.smt2
Labels: normal, simple

#10247 Add internal infrastructure for user plugins
  src/CMakeLists.txt
  src/expr/CMakeLists.txt
  src/expr/plugin.cpp
  src/expr/plugin.h
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
  src/smt/env.cpp
  src/smt/env.h
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/plugin_module.cpp
  src/theory/plugin_module.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: normal, moderate

#10588 Make binaries and libraries relocatable
  CMakeLists.txt
Labels: normal, simple

#10589 fp: Fix getEqualityStatus() for non-const values.
  src/theory/fp/theory_fp.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/fp/issue10144.smt2
  test/regress/cli/regress0/fp/issue10507.smt2
  test/regress/cli/regress0/fp/issue9854.smt2
  test/regress/cli/regress0/fp/issue9966.smt2
  test/regress/cli/regress0/fp/issue9972-2.smt2
  test/regress/cli/regress0/fp/issue9972.smt2
Labels: major, simple

#10590 fp: Refactor skolem handling of FpExpandDefs.
  include/cvc5/cvc5_skolem_id.h
  src/expr/skolem_manager.cpp
  src/printer/enum_to_string.cpp
  src/theory/fp/fp_expand_defs.cpp
  src/theory/fp/fp_expand_defs.h
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp_rewriter.cpp
Labels: normal, simple, do not merge

#10593 Add tests for uncovered functions in nightlies.
  test/unit/api/cpp/api_term_manager_black.cpp
  test/unit/api/java/UncoveredTest.cpp
  test/unit/api/python/test_uncovered.cpp
Labels: normal, simple

#10595 More tests for uncovered functions in nightlies.
  test/unit/api/cpp/datatype_api_black.cpp
  test/unit/api/java/DatatypeTest.java
  test/unit/api/java/UncoveredTest.cpp
  test/unit/api/python/test_datatype_api.py
Labels: normal, simple

#10594 java api: Add missing @Deprecated annotations.
  src/api/java/io/github/cvc5/Solver.java
Labels: normal, simple

#10596 java api: Enable TermManagerTest.
  test/unit/api/java/CMakeLists.txt
  test/unit/api/java/TermManagerTest.java
Labels: normal, simple

#10566 Update ALF signatures to parameterized nil terminators
  contrib/get-alf-checker
  proofs/alf/cvc5/Cvc5.smt3
  proofs/alf/cvc5/programs/Nary.smt3
  proofs/alf/cvc5/programs/Strings.smt3
  proofs/alf/cvc5/rules/Strings.smt3
  proofs/alf/cvc5/rules/Uf.smt3
  proofs/alf/cvc5/theories/BitVectors.smt3
  proofs/alf/cvc5/theories/FiniteFields.smt3
  proofs/alf/cvc5/theories/Ints.smt3
  proofs/alf/cvc5/theories/Strings.smt3
  src/proof/alf/alf_node_converter.cpp
Labels: normal, moderate

#10544 Remove most uses of `NodeManager::currentNM` in theory rewriters and proof checkers
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_rewriter.h
  src/theory/arith/nl/ext/proof_checker.cpp
  src/theory/arith/nl/transcendental/proof_checker.cpp
  src/theory/arith/nl/transcendental/proof_checker.h
  src/theory/arith/proof_checker.cpp
  src/theory/arith/theory_arith.cpp
  src/theory/arrays/proof_checker.cpp
  src/theory/arrays/theory_arrays_rewriter.cpp
  src/theory/arrays/theory_arrays_rewriter.h
  src/theory/booleans/proof_checker.cpp
  src/theory/booleans/theory_bool_rewriter.cpp
  src/theory/booleans/theory_bool_rewriter.h
  src/theory/builtin/proof_checker.cpp
  src/theory/builtin/theory_builtin_rewriter.cpp
  src/theory/builtin/theory_builtin_rewriter.h
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/datatypes_rewriter.h
  src/theory/datatypes/proof_checker.cpp
  src/theory/ff/theory_ff_rewriter.cpp
  src/theory/ff/theory_ff_rewriter.h
  src/theory/quantifiers/proof_checker.cpp
  src/theory/quantifiers/quantifiers_preprocess.cpp
  src/theory/quantifiers/quantifiers_preprocess.h
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
  src/theory/sep/theory_sep_rewriter.cpp
  src/theory/sep/theory_sep_rewriter.h
  src/theory/sets/theory_sets_rewriter.cpp
  src/theory/strings/proof_checker.cpp
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/sequences_rewriter.h
  src/theory/strings/strings_rewriter.cpp
  src/theory/uf/proof_checker.cpp
  src/theory/uf/theory_uf_rewriter.cpp
  src/theory/uf/theory_uf_rewriter.h
Labels: minor, simple

#10527 ci: Fix path of contrib cache
  .github/actions/setup-cache/action.yml
Labels: minor, simple, ci

#10603 test: Only register unit tests as white when really required.
  test/unit/api/cpp/CMakeLists.txt
  test/unit/test_api.h
Labels: normal, simple

#10608 Add skolem id for arbitrary ground term
  include/cvc5/cvc5_skolem_id.h
  src/expr/skolem_manager.cpp
  src/printer/enum_to_string.cpp
  src/theory/builtin/theory_builtin_type_rules.cpp
Labels: minor, simple

#10599 Fixes and improvements for skolem documentation
  include/cvc5/cvc5_skolem_id.h
Labels: normal, simple

#10604 Call `notifySatClause` callback in minisat for learned sat clauses
  src/prop/minisat/core/Solver.cc
Labels: normal, moderate

#10602 Track inference ids into prop engine
  src/prop/prop_engine.cpp
  src/prop/prop_engine.h
  src/prop/prop_proof_manager.cpp
  src/prop/prop_proof_manager.h
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/theory_engine.cpp
  test/regress/cli/regress0/printer/print_sat_lemmas.smt2
Labels: normal, simple

#10565 Refactor internal unsat core manager interface
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  src/smt/unsat_core_manager.cpp
  src/smt/unsat_core_manager.h
Labels: normal, moderate

#10614 Separate proof status from DSL proof rule identifiers
  src/proof/lfsc/lfsc_printer.cpp
  src/rewriter/CMakeLists.txt
  src/rewriter/rewrite_db_proof_cons.cpp
  src/rewriter/rewrite_db_proof_cons.h
  src/rewriter/rewrite_proof_rule.cpp
  src/rewriter/rewrite_proof_status.cpp
  src/rewriter/rewrite_proof_status.h
  src/rewriter/rewrites_template.cpp
  src/rewriter/rewrites_template.h
Labels: normal, moderate

#10612 datatypes: Refactor hashing, add hashing and operator== on C++ API level.
  include/cvc5/cvc5.h
  src/api/cpp/cvc5.cpp
  src/expr/dtype.cpp
  src/expr/dtype.h
  src/expr/dtype_cons.cpp
  src/expr/dtype_cons.h
  src/expr/dtype_selector.cpp
  src/expr/dtype_selector.h
Labels: normal, simple

#10610 c api: Some fixes in header, add documentation.
  include/cvc5/c/cvc5.h
Labels: normal, simple

#10625 Replace references to CVC4 with cvc5
  cmake/ConfigDebug.cmake
  cmake/FindEditline.cmake
  configure.sh
  src/context/default_clean_up.h
  src/expr/annotation_elim_node_converter.h
  src/expr/elim_shadow_converter.h
  src/expr/nary_term_util.h
  src/expr/node_converter.h
  src/expr/subtype_elim_node_converter.h
  src/proof/alf/alf_node_converter.h
  src/proof/alf/alf_print_channel.h
  src/proof/lfsc/lfsc_list_sc_node_converter.h
  src/proof/lfsc/lfsc_node_converter.h
  src/proof/lfsc/lfsc_post_processor.h
  src/proof/lfsc/lfsc_print_channel.h
  src/proof/lfsc/lfsc_printer.h
  src/rewriter/rewrite_db.h
  src/rewriter/rewrite_db_term_process.h
  src/rewriter/rewrite_proof_rule.h
Labels: moderate

#10622 Fix auto-generated doc for `-o block-models` and `-o portfolio`
  src/options/base_options.toml
  src/parser/smt2/smt2_cmd_parser.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/printer/block_model_out.smt2
  test/regress/cli/regress0/printer/portfolio-out-err.smt2
  test/regress/cli/regress0/printer/portfolio-out.smt2
Labels: normal, simple

#10618 Implement conversion from approximate to dependent types
  src/CMakeLists.txt
  src/proof/alf/alf_dependent_type_converter.cpp
  src/proof/alf/alf_dependent_type_converter.h
  src/proof/alf/alf_node_converter.h
Labels: normal, moderate

#10581 Add utility to extract witness terms for DSL_REWRITE applications
  src/expr/nary_term_util.cpp
  src/expr/nary_term_util.h
  src/rewriter/rewrite_proof_rule.cpp
  src/rewriter/rewrite_proof_rule.h
Labels: normal, moderate

#10597 Fix use of CONG for binder kinds in DSL reconstruction
  src/proof/conv_proof_generator.cpp
  src/proof/proof_node_algorithm.cpp
  src/rewriter/rewrite_db_proof_cons.cpp
Labels: normal, simple

#10626 Enable win64_native on MSYS environments
  .github/workflows/ci.yml
  configure.sh
  contrib/cibw/before_all_windows.sh
Labels: normal, simple

#10598 Allow evaluation when concretizing generic ops
  src/theory/builtin/generic_op.cpp
Labels: normal, simple

#10556 Generate consistent variables when parsing quantified formulas
  src/expr/node_algorithm.h
  src/parser/parser_state.cpp
  src/parser/parser_state.h
  src/parser/smt2/smt2_term_parser.cpp
  src/proof/alf/alf_node_converter.cpp
  src/proof/alf/alf_printer.cpp
  src/smt/assertions.cpp
  src/smt/print_benchmark.cpp
  src/smt/solver_engine.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
Labels: normal, moderate

#10450 Move DSL rewrite rule reconstruction to separate module
  src/CMakeLists.txt
  src/smt/proof_post_processor.cpp
  src/smt/proof_post_processor.h
  src/smt/proof_post_processor_dsl.cpp
  src/smt/proof_post_processor_dsl.h
Labels: normal, moderate

#10633 Add regressions for fixed issues
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/proj-issue696.smt2
  test/regress/cli/regress0/proofs/proj-issue698.smt2
Labels: minor, simple

#10558 Support ACI_NORM in ALF
  proofs/alf/cvc5/Cvc5.smt3
  proofs/alf/cvc5/programs/Strings.smt3
  proofs/alf/cvc5/programs/Utils.smt3
  src/proof/alf/alf_printer.cpp
Labels: normal, moderate

#10634 Rewrite substitutions stored in assertions with incremental mode
  src/preprocessing/assertion_pipeline.cpp
  src/preprocessing/passes/non_clausal_simp.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/push-pop/proj-issue694-subs-in-assert.smt2
Labels: minor, simple

#10629 Do not apply global negation if there are symbols that are not first class
  src/expr/type_node.cpp
  src/preprocessing/passes/global_negate.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/quantifiers/proj-issue706-gn-dt.smt2
Labels: minor, simple

#10637 bv: Rewrite equalities in ppStaticRewrite only.
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv.h
  src/theory/bv/theory_bv_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/bv/issue10057.smt2
  test/regress/cli/regress0/bv/issue8106.smt2
  test/regress/cli/regress0/bv/issue8106_2.smt2
  test/regress/cli/regress0/bv/issue8274.smt2
  test/regress/cli/regress0/bv/issue8809.smt2
  test/regress/cli/regress0/bv/issue9518.smt2
  test/regress/cli/regress0/bv/issue9518_2.smt2
  test/regress/cli/regress0/bv/issue9519.smt2
  test/regress/cli/regress0/bv/proj-issue320.smt2
  test/regress/cli/regress0/bv/proj-issue321.smt2
Labels: major, simple

#10640 Remove Boost dependency
  examples/CMakeLists.txt
  src/base/cvc5config.h.in
Labels: normal, simple

#10642 Do not install CaDiCaL static library
  cmake/FindCaDiCaL.cmake
Labels: normal, simple

#10621 Add `-o unsat-core-lemmas-benchmark`
  src/options/base_options.toml
  src/prop/prop_proof_manager.cpp
  src/smt/solver_engine.cpp
  src/smt/unsat_core_manager.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/printer/print_unsat_core_lemmas.smt2
Labels: major, simple

#10635 Fail to set match when ieval finds a term indexing conflict
  src/theory/quantifiers/inst_match.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/quantifiers/issue10346-ieval-index-conflict.smt2
Labels: minor, simple

#10632 ff: fix rewriter
  src/theory/ff/theory_ff_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/ff/proj-issue704.smt2
Labels: bug, simple

#10611 Support `ProofRule::CONCAT_SPLIT` in ALF
  include/cvc5/cvc5_proof_rule.h
  proofs/alf/cvc5/programs/Strings.smt3
  proofs/alf/cvc5/rules/Strings.smt3
  src/proof/alf/alf_printer.cpp
Labels: normal, moderate

#10613 Add suggestions for how to avoid option exception with `--safe-options`
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/options/safe-options1.smt2
  test/regress/cli/regress0/options/safe-options2.smt2
  test/regress/cli/regress0/options/safe-opts-warn.smt2
Labels: normal, simple

#10609 ci: Run tests on Windows
  .github/actions/run-tests/action.yml
  .github/workflows/ci.yml
  test/CMakeLists.txt
  test/api/cpp/CMakeLists.txt
  test/regress/cli/CMakeLists.txt
  test/regress/cli/run_regression.py
Labels: normal, moderate

#10568 Expose DSL Proof Rules.
  include/cvc5/c/cvc5.h
  include/cvc5/cvc5.h
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_proof_rule.cpp
  src/api/java/io/github/cvc5/Proof.java
  src/api/java/jni/proof.cpp
  src/api/python/cvc5.pxd
  src/api/python/cvc5.pxi
  src/proof/alf/alf_print_channel.cpp
  src/proof/lfsc/lfsc_print_channel.cpp
  src/proof/lfsc/lfsc_print_channel.h
  src/proof/lfsc/lfsc_printer.cpp
  src/proof/lfsc/lfsc_printer.h
  src/proof/proof_node_to_sexpr.cpp
  src/proof/proof_node_to_sexpr.h
  src/rewriter/CMakeLists.txt
  src/rewriter/mkrewrites.py
  src/rewriter/rewrite_db.cpp
  src/rewriter/rewrite_db.h
  src/rewriter/rewrite_db_proof_cons.cpp
  src/rewriter/rewrite_db_proof_cons.h
  src/rewriter/rewrite_proof_rule.cpp
  src/rewriter/rewrite_proof_rule.h
  src/rewriter/rewrites.h
  src/rewriter/rewrites_template.cpp
  src/rewriter/util.py
  src/smt/proof_final_callback.cpp
  src/smt/proof_final_callback.h
  src/theory/builtin/proof_checker.cpp
  test/unit/api/cpp/api_proof_rule_black.cpp
  test/unit/api/cpp/proof_black.cpp
  test/unit/api/java/ProofTest.java
  test/unit/api/java/UncoveredTest.cpp
  test/unit/api/python/test_proof.py
  test/unit/api/python/test_uncovered.cpp
Labels: normal, moderate

#10645 Support evaluation of more operators in ALF
  proofs/alf/cvc5/Cvc5.smt3
  proofs/alf/cvc5/programs/Arith.smt3
  proofs/alf/cvc5/programs/Utils.smt3
  src/proof/alf/alf_printer.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/str-term-276-indexof-eval.smt2
Labels: minor, simple

#10647 Fix output for unsat-core-lemmas-benchmark
  test/regress/cli/regress0/printer/print_unsat_core_lemmas.smt2
Labels: normal, simple

#10652 Turn `cvc5_proof_rule.cpp` into a template.
  src/CMakeLists.txt
  src/api/cpp/cvc5_proof_rule.cpp
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/rewriter/CMakeLists.txt
  src/rewriter/mkrewrites.py
Labels: normal, simple

#10644 ff: bugfix: field-specific CoCoA translation
  src/theory/ff/cocoa_encoder.cpp
  src/theory/ff/sub_theory.cpp
  src/theory/ff/util.cpp
  src/theory/ff/util.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/ff/proj-issue705.smt2
Labels: bug, minor, moderate

#10616 Updates to the BV theory in ALF
  include/cvc5/cvc5_skolem_id.h
  proofs/alf/cvc5/theories/BitVectors.smt3
  src/expr/nary_term_util.cpp
  src/expr/skolem_manager.cpp
  src/printer/enum_to_string.cpp
Labels: normal, moderate

#10643 Fix RARE fixed point matching under contexts
  src/expr/node_algorithm.cpp
  src/rewriter/rewrite_db_proof_cons.cpp
Labels: normal, moderate

#10657 Add proofs for static rewrite preprocessing pass
  src/preprocessing/passes/static_rewrite.cpp
  src/preprocessing/passes/static_rewrite.h
  src/proof/trust_id.cpp
  src/proof/trust_id.h
Labels: normal, simple

#10617 Add conversion method for RARE in ALF involving `:list` variables
  src/CMakeLists.txt
  src/proof/alf/alf_list_node_converter.cpp
  src/proof/alf/alf_list_node_converter.h
  src/proof/alf/alf_node_converter.cpp
  src/proof/alf/alf_node_converter.h
Labels: normal, moderate

#10433 Add rel.join operator for relations.
  include/cvc5/cvc5_kind.h
  src/api/cpp/cvc5.cpp
  src/parser/smt2/smt2_state.cpp
  src/printer/smt2/smt2_printer.cpp
  src/theory/bags/bags_utils.cpp
  src/theory/builtin/generic_op.cpp
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/quantifiers/term_util.cpp
  src/theory/sets/kinds
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/sets/theory_sets_rels.cpp
  src/theory/sets/theory_sets_rels.h
  src/theory/sets/theory_sets_rewriter.cpp
  src/theory/sets/theory_sets_rewriter.h
  src/theory/sets/theory_sets_type_rules.cpp
  src/theory/sets/theory_sets_type_rules.h
  src/theory/theory_engine.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/rels/relation_join1.smt2
Labels: normal, moderate

#10649 Install DLL libraries in the runtime path
  .github/actions/run-tests/action.yml
  cmake/FindPoly.cmake
  cmake/deps-helper.cmake
  src/CMakeLists.txt
  src/parser/CMakeLists.txt
Labels: normal, simple

#10658 [alethe] Update new proof rules
  src/proof/alethe/alethe_proof_rule.cpp
  src/proof/alethe/alethe_proof_rule.h
Labels: normal, simple

#10620 Add `-o options-auto`
  src/api/cpp/cvc5.cpp
  src/options/base_options.toml
  src/options/mkoptions.py
  src/options/options_handler.cpp
  src/smt/abduction_solver.cpp
  src/smt/interpolation_solver.cpp
  src/smt/set_defaults.cpp
  src/smt/solver_engine.cpp
  src/smt/sygus_solver.cpp
  src/theory/quantifiers/inst_strategy_sub_conflict.cpp
  src/theory/quantifiers/query_generator_unsat.cpp
  src/theory/quantifiers/sygus/sygus_interpol.cpp
  src/theory/quantifiers/sygus/synth_verify.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/printer/print_options_auto.smt2
  test/unit/theory/theory_arith_coverings_white.cpp
Labels: major, moderate

#10662 Add proof infrastructure for ad-hoc rewrites THEORY_REWRITE
  include/cvc5/cvc5.h
  include/cvc5/cvc5_proof_rule.h
  src/CMakeLists.txt
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/api/java/io/github/cvc5/Proof.java
  src/api/python/cvc5.pxi
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/rewriter/rewrite_db_proof_cons.cpp
  src/smt/proof_final_callback.cpp
  src/theory/builtin/proof_checker.cpp
  src/theory/builtin/proof_checker.h
  src/theory/builtin/theory_rewrite_proof_checker.cpp
  src/theory/builtin/theory_rewrite_proof_checker.h
Labels: major, moderate

#10669 Support more cases of evaluation and skolems in ALF
  proofs/alf/cvc5/Cvc5.smt3
  proofs/alf/cvc5/programs/Utils.smt3
  src/proof/alf/alf_node_converter.cpp
  src/proof/alf/alf_printer.cpp
Labels: minor, simple

#10668 Handle case where list context occurs in condition for ALF+RARE
  src/rewriter/rewrite_proof_rule.cpp
Labels: normal, simple

#10667 ci: Use native build for Windows package
  .github/actions/add-package/action.yml
  .github/actions/install-dependencies/action.yml
  .github/workflows/ci.yml
Labels: normal, simple, ci

#10664 ci: Set new path to DLL libraries in PyPi packaging
  .github/workflows/package_pypi.yml
Labels: normal, simple, ci

#10605 Add special case for quantifier elimination of closed formulas
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
  src/smt/quant_elim_solver.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/quantifiers/qe-closed-str-re.smt2
Labels: normal, moderate

#10600 Add `--uf-lambda-qe` to eagerly eliminate quantifiers in HO lambda equivalence
  src/options/uf_options.toml
  src/theory/uf/ho_extension.cpp
  src/theory/uf/ho_extension.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/sets/filter-qe-simple-bv.smt2
  test/regress/cli/regress0/sets/filter-qe-simple.smt2
Labels: normal, moderate

#10586 Set incomplete when combining set cardinality and fmf bound
  src/theory/incomplete_id.cpp
  src/theory/incomplete_id.h
  src/theory/quantifiers/fmf/bounded_integers.cpp
  src/theory/sets/theory_sets_private.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/sets/issue10584-card-fmf-bound.smt2
  test/regress/cli/regress0/sets/proj-issue501-choose-bool-term-var.smt2
  test/regress/cli/regress1/fmf/ko-bound-set.cvc.smt2
Labels: normal, simple

#10673 Add support for SMT-LIB option random-seed.
  src/options/main_options.toml
Labels: normal, simple

#10562 Remove type exceptions from type checker for bags
  src/theory/bags/theory_bags_type_rules.cpp
Labels: minor, moderate

#10641 Use standard order for equality rewriting in BV
  src/theory/bv/theory_bv_rewrite_rules_core.h
Labels: major, simple

#10683 [proofs] Fix handling of cycles in LazyProofChain
  src/proof/lazy_proof_chain.cpp
  src/prop/minisat/sat_proof_manager.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/issue9770-open-sat-proof.smt2
  test/regress/cli/regress0/proofs/proj-issue711-open-sat-proof.smt2
Labels: normal, moderate

#10666 Support DSL_REWRITE in ALF proofs
  proofs/alf/cvc5/programs/Utils.smt3
  src/options/proof_options.toml
  src/proof/alf/alf_printer.cpp
  src/proof/alf/alf_printer.h
  src/smt/proof_manager.cpp
Labels: normal, moderate

#10687 pythonic docs: is_tautology
  docs/api/python/pythonic/solver.rst
Labels: simple

#10671 Add infrastructure to rewriter for THEORY_REWRITE
  include/cvc5/cvc5_proof_rule.h
  src/CMakeLists.txt
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/rewriter/basic_rewrite_rcons.cpp
  src/smt/proof_final_callback.cpp
  src/smt/proof_final_callback.h
  src/theory/builtin/proof_checker.cpp
  src/theory/builtin/proof_checker.h
  src/theory/builtin/theory_rewrite_proof_checker.cpp
  src/theory/builtin/theory_rewrite_proof_checker.h
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
  src/theory/rewriter.cpp
  src/theory/rewriter.h
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/sequences_rewriter.h
  src/theory/theory_rewriter.cpp
  src/theory/theory_rewriter.h
Labels: normal, moderate

#10691 Improve policy for proving rewrites involving quantified formulas
  src/rewriter/rewrite_db_proof_cons.cpp
Labels: normal, moderate

#10692 Use new THEORY_REWRITE infrastructure for the theory of datatypes
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/proof/proof.cpp
  src/proof/proof.h
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/datatypes_rewriter.h
  src/theory/datatypes/infer_proof_cons.cpp
  src/theory/datatypes/proof_checker.cpp
  src/theory/datatypes/theory_datatypes.cpp
Labels: normal, moderate

#10630 Ensure arguments of sine are real in rewriter
  src/theory/arith/arith_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/nl/nta/proj-issue701-sine-rr-int-arg.smt2
Labels: minor, simple

#10693 Install Python bindings in interpreter default location
  src/api/python/CMakeLists.txt
Labels: normal, simple

#10695 Add distinct elimination THEORY_REWRITE
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/theory/builtin/theory_builtin_rewriter.cpp
  src/theory/builtin/theory_builtin_rewriter.h
  test/regress/cli/regress1/quantifiers/AdditiveMethods_OwnedResults.Mz.smt2
  test/regress/cli/regress2/quantifiers/AdditiveMethods_AdditiveMethods..ctor.smt2
  test/regress/cli/regress2/strings/strings-alpha-card-65.smt2
Labels: normal, moderate

#10601 Make String comparable to abstract sequence for RARE
  src/expr/type_node.cpp
  src/theory/strings/rewrites
Labels: normal, simple

#10689 Notify plugins of SAT clauses only when solving by default
  src/options/prop_options.toml
  src/prop/theory_proxy.cpp
  src/prop/theory_proxy.h
Labels: minor, simple

#10679 Add length entailment rewrites to extended rewriter, more cases to foreign theory rewrite
  src/preprocessing/passes/foreign_theory_rewrite.cpp
  src/preprocessing/passes/foreign_theory_rewrite.h
  src/theory/quantifiers/extended_rewrite.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/strings/foreign-theory-rew-simple.smt2
Labels: normal, moderate

#10670 Update the semantics of sqrt
  include/cvc5/cvc5_kind.h
  src/theory/arith/operator_elim.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/nl/nta/issue10655-sqrt-semantics.smt2
  test/regress/cli/regress0/nl/sqrt.smt2
Labels: normal, simple

#10631 Fix skolem reference from arithmetic operator elimination
  src/theory/arith/operator_elim.cpp
  src/theory/skolem_lemma.cpp
  test/regress/cli/regress0/nl/nta/proj-issue699-op-elim-k.smt2
Labels: normal, simple

#10701 Do not mark a few BV rules as fixed point
  src/theory/bv/rewrites
Labels: minor, simple

#10699 Demote BETA_REDUCE and ARRAYS_EQ_RANGE_EXPAND to ProofRewriteRules
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/proof/eager_proof_generator.cpp
  src/proof/eager_proof_generator.h
  src/proof/lfsc/lfsc_post_processor.cpp
  src/rewriter/basic_rewrite_rcons.cpp
  src/theory/arrays/proof_checker.cpp
  src/theory/arrays/theory_arrays_rewriter.cpp
  src/theory/arrays/theory_arrays_rewriter.h
  src/theory/uf/proof_checker.cpp
  src/theory/uf/theory_uf_rewriter.cpp
  src/theory/uf/theory_uf_rewriter.h
Labels: minor, simple

#10684 Flatten quantified formulas introduced for negative REGEXP unfolding
  src/theory/strings/regexp_operation.cpp
Labels: normal, simple

#10704 Rename REMOVE_TERM_FORMULA_AXIOM to ITE_EQ
  include/cvc5/cvc5_proof_rule.h
  proofs/alf/cvc5/rules/Builtin.smt3
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/proof/alethe/alethe_post_processor.cpp
  src/proof/alf/alf_printer.cpp
  src/smt/term_formula_removal.cpp
  src/theory/builtin/proof_checker.cpp
Labels: normal, simple

#10703 Export documentation for Rewrite Proof rules.
  docs/proofs/proof_rules.rst
  include/cvc5/cvc5_proof_rule.h
Labels: simple, moderate
