Repository cvc5/cvc5, pull requests merged in 2025-08, with the labels that each got.

#12035 Add missing Java API docs for the Op, Sort, and Term classes
  src/api/java/io/github/cvc5/Op.java
  src/api/java/io/github/cvc5/Sort.java
  src/api/java/io/github/cvc5/Term.java
Labels: normal, simple

#12037 Add Java API docs for enumeration types
  src/api/java/genenums.py.in
Labels: normal, simple

#12059 Fix possible non-idempotency in rewriter
  src/theory/arith/arith_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arith/issue12058.smt2
Labels: normal, simple

#12063 Update Doxyfile from 1.9.1 to 1.9.8
  docs/api/Doxyfile.in
Labels: normal, simple

#12066 doc: Fix invalid escape sequences in Sphinx config files
  docs/conf.py.in
  docs/ext/smtliblexer.py
Labels: normal, simple

#12060 Fix unsound proof rule str-indexof-find-emp
  proofs/eo/cpc/rules/Rewrites.eo
  src/theory/strings/rewrites
Labels: normal, simple

#12075 Fix assertion related to printing lemma count
  src/theory/quantifiers/quantifiers_inference_manager.cpp
Labels: minor, simple

#12081 Add `re.^` to CPC
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  proofs/eo/cpc/theories/Strings.eo
  src/rewriter/mkrewrites.py
  src/rewriter/node.py
  src/rewriter/rw_parser.py
  src/theory/builtin/generic_op.cpp
  src/theory/strings/rewrites
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/strings/regexp-repeat.smt2
Labels: normal, simple

#12091 Fix LFSC for regexp repeat
  proofs/lfsc/signatures/theory_def.plf
Labels: major, simple

#11962 Make NL more careful wrt theory combination
  src/theory/arith/nl/nonlinear_extension.cpp
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arrays/issue12026.smt2
  test/regress/cli/regress0/nl/issue10140-nl-tc.smt2
  test/regress/cli/regress0/nl/issue9661.smt2
  test/regress/cli/regress1/quantifiers/sygus-inst-nia-psyco-060.smt2
Labels: normal, moderate, do not merge

#11921 Also send ensured atom equalities to THEORY_BUILTIN with ee central
  src/theory/theory_engine.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arrays/issue11908-eec-ensure-atom.smt2
Labels: normal, simple
