Repository cvc5/cvc5, pull requests merged in 2025-07, with the labels that each got.

#12015 Remove old references and add missing one in COPYING file
  COPYING
Labels: normal, simple

#12014 doc: Update references to deprecated Solver methods
  include/cvc5/cvc5.h
  include/cvc5/cvc5_kind.h
  src/api/java/genenums.py.in
  src/api/java/io/github/cvc5/Solver.java
  src/api/java/io/github/cvc5/Sort.java
  src/api/java/io/github/cvc5/TermManager.java
  src/api/python/cvc5.pxi
Labels: normal, moderate

#11709 prop: cadical: Add support for getProof via CaDiCaL's proof tracer.
  cmake/FindCaDiCaL.cmake
  src/prop/cadical.cpp
  src/prop/cadical.h
  src/smt/set_defaults.cpp
Labels: moderate

#12020 cmake: Install Sphinx if not available
  .github/actions/install-dependencies/action.yml
  INSTALL.rst
  cmake/FindRepairwheel.cmake
  cmake/FindSphinx.cmake
  cmake/python-scripts-paths.cmake
  docs/CMakeLists.txt
Labels: normal, moderate

#12022 doc: Update steps for testing cvc5
  INSTALL.rst
Labels: normal, simple

#12019 cmake: Enforce C11 standard
  CMakeLists.txt
Labels: minor, simple

#12018 Minor simplifications to Eunoia CPC signature
  proofs/eo/cpc/expert/CpcExpert.eo
  proofs/eo/cpc/expert/theories/Nullables.eo
  proofs/eo/cpc/theories/Arith.eo
  proofs/eo/cpc/theories/ArithBvConv.eo
  proofs/eo/cpc/theories/Datatypes.eo
  proofs/eo/cpc/theories/Strings.eo
  src/smt/illegal_checker.cpp
Labels: minor, simple

#12025 Use new NFA regular expression test whenever possible in CPC rules
  proofs/eo/cpc/programs/Nfa.eo
  proofs/eo/cpc/programs/Strings.eo
  test/regress/cli/regress0/strings/re-mem-eval-large.smt2
Labels: normal, simple

#12033 Introduce naming convention in CPC for internal data declarations
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/expert/CpcExpert.eo
  proofs/eo/cpc/programs/AciNorm.eo
  proofs/eo/cpc/programs/Nfa.eo
  proofs/eo/cpc/programs/PolyNorm.eo
  proofs/eo/cpc/programs/Strings.eo
  proofs/eo/cpc/programs/Utils.eo
Labels: normal, simple

#12039 Fix resource limit setup in get-value
  src/smt/solver_engine.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/issue12038-model-get-value.smt2
Labels: major, simple
