Repository cvc5/cvc5, pull requests merged in 2025-02, with the labels that each got.

#11581 Add Eunoia definitions of extended RE evaluation
  proofs/eo/cpc/programs/Strings.eo
  proofs/eo/cpc/rules/Strings.eo
  src/proof/alf/alf_printer.cpp
  src/theory/strings/sequences_rewriter.cpp
Labels: normal, moderate

#11334 Add support for `str.replace_all` in evaluator
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/programs/Strings.eo
  src/proof/alf/alf_printer.cpp
  src/theory/evaluator.cpp
Labels: normal, moderate

#11494 Add proof support for arithmetic static learning
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/theory/arith/arith_proof_utilities.cpp
  src/theory/arith/arith_proof_utilities.h
  src/theory/arith/linear/arith_static_learner.cpp
  src/theory/arith/linear/arith_static_learner.h
  src/theory/arith/rewrites
Labels: normal, moderate

#11583 Split expert portions of Cpc.eo to own subdirectory
  contrib/install-rare-rewrites
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/expert/CpcExpert.eo
  proofs/eo/cpc/expert/rules/Sets.eo
  proofs/eo/cpc/expert/rules/Transcendentals.eo
  proofs/eo/cpc/expert/theories/Arith.eo
  proofs/eo/cpc/expert/theories/Bags.eo
  proofs/eo/cpc/expert/theories/FiniteFields.eo
  proofs/eo/cpc/expert/theories/FloatingPoints.eo
  proofs/eo/cpc/expert/theories/SepLogic.eo
  proofs/eo/cpc/expert/theories/Sets.eo
  proofs/eo/cpc/expert/theories/Transcendentals.eo
  proofs/eo/cpc/rules/Rewrites.eo
  proofs/eo/cpc/rules/Sets.eo
  proofs/eo/cpc/theories/Arrays.eo
  proofs/eo/cpc/theories/Builtin.eo
  proofs/eo/cpc/theories/Datatypes.eo
  proofs/eo/cpc/theories/Ints.eo
  proofs/eo/cpc/theories/Quantifiers.eo
  proofs/eo/cpc/theories/Reals.eo
  proofs/eo/cpc/theories/Sets.eo
Labels: normal, simple

#11584 Eunoia definition of arith BV conversions
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/rules/ArithBvConv.eo
  proofs/eo/cpc/theories/ArithBvConv.eo
  proofs/eo/cpc/theories/BitVectors.eo
  src/proof/alf/alf_printer.cpp
Labels: normal, moderate

#11586 Add more cases of STRING_REDUCTION in Eunoia
  proofs/eo/cpc/programs/Strings.eo
  src/proof/alf/alf_printer.cpp
  src/theory/strings/theory_strings_preprocess.cpp
Labels: normal, moderate

#11585 Fix corner case in Eo signature for replace_re_all
  proofs/eo/cpc/rules/Strings.eo
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress2/strings/replace-re-all-unsat.smt2
Labels: normal, simple

#11580 Add CPC and Eunoia definitions for string theory rewrites involving overlap reasoning
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/programs/Strings.eo
  proofs/eo/cpc/rules/Strings.eo
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/proof/alf/alf_printer.cpp
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/sequences_rewriter.h
Labels: normal, moderate

#11573 ci: Update Ubuntu runners to 22.04
  .github/actions/configure-and-build/action.yml
  .github/actions/install-dependencies/action.yml
  .github/workflows/ci.yml
Labels: normal, simple, ci

#11578 Simplify CPC and Eunoia definition of ARITH_POLY_NORM_REL
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/programs/PolyNorm.eo
  src/proof/alf/alf_printer.cpp
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/rewrite_db_proof_cons.cpp
  src/theory/arith/proof_checker.cpp
Labels: minor, moderate

#11530 Add proof elaboration for MACRO_ARRAYS_NORMALIZE_OP
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/theory/arrays/theory_arrays_rewriter.cpp
  src/theory/arrays/theory_arrays_rewriter.h
Labels: normal, moderate

#11590 Make RE_INTER_UNION_INCLUSION a macro, elaborate to simpler version
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/programs/Strings.eo
  proofs/eo/cpc/rules/Strings.eo
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/proof/alf/alf_printer.cpp
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/sequences_rewriter.h
Labels: normal, moderate

#11576 More updates to classifications of options
  src/options/decision_options.toml
  src/options/quantifiers_options.toml
  src/options/smt_options.toml
  src/theory/quantifiers/quantifiers_rewriter.cpp
  test/regress/cli/regress1/quantifiers/issue2970-string-var-elim.smt2
Labels: normal, simple

#11487 Two fixes for quantifiers prenex proofs
  src/rewriter/basic_rewrite_rcons.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
Labels: major, moderate

#11497 Add Eunoia definitions of ARITH_MULT_SIGN and ARITH_MULT_ABS_COMPARISION
  proofs/eo/cpc/programs/Utils.eo
  proofs/eo/cpc/rules/Arith.eo
  src/proof/alf/alf_printer.cpp
Labels: major, moderate

#11442 Refactor proof post processor DSL to avoid subgoal tracking
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/rewriter/rewrite_db_proof_cons.cpp
  src/rewriter/rewrite_db_proof_cons.h
  src/smt/proof_post_processor_dsl.cpp
  src/smt/proof_post_processor_dsl.h
Labels: major, moderate

#11574 Add more regressions demonstrating tricky proof cases
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arith/dd_cs_dekker.smt2
  test/regress/cli/regress0/quantifiers/dd_p15_dio_lemma.smt2
  test/regress/cli/regress0/quantifiers/dd_psyco_186-ineq-elim.smt2
  test/regress/cli/regress0/quantifiers/var-elim-ineq-simple.smt2
  test/regress/cli/regress0/strings/dd_slog_stranger_2020.smt2
  test/regress/cli/regress0/strings/prefix-multi-var-emp.smt2
  test/regress/cli/regress0/strings/prefix-multi-var.smt2
  test/regress/cli/regress0/strings/re-str-inference-missing.smt2
  test/regress/cli/regress2/quantifiers/dd10_sdlx-fix-4.smt2
Labels: normal, simple

#11441 Add macros and elaboration for arithmetic integer relation rewrites
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/rewriter/rewrite_atom.cpp
  src/theory/arith/rewriter/rewrite_atom.h
  src/theory/arith/rewrites
Labels: major, moderate

#11613 [proofs] Remove eager check for SAT proof closedness
  src/prop/minisat/sat_proof_manager.cpp
Labels: normal, simple

#11577 Update CPC signature and output to fully support parametric datatypes
  contrib/get-ethos-checker
  proofs/eo/cpc/programs/Datatypes.eo
  proofs/eo/cpc/rules/Datatypes.eo
  proofs/eo/cpc/theories/Datatypes.eo
  src/proof/alf/alf_node_converter.cpp
  src/proof/alf/alf_node_converter.h
  test/regress/cli/regress0/datatypes/dt-param-simple-unsat.smt2
  test/regress/cli/regress0/datatypes/issue8883-sort-inf.smt2
  test/regress/cli/regress0/quantifiers/dd_SA10-027-dt-ipc.smt2
  test/regress/cli/regress0/quantifiers/dd_TwoSquares.z3.611901.smt2
  test/regress/cli/regress1/datatypes/nullables/nullable-lift-unsat.smt2
  test/regress/cli/regress1/datatypes/nullables/nullables2.smt2
  test/regress/cli/regress1/datatypes/nullables/nullables3.smt2
  test/regress/cli/regress1/quantifiers/parametric-lists.smt2
  test/regress/cli/regress1/quantifiers/seqa-unsat-unknown-110921.smt2
Labels: normal, moderate

#11601 Make unit tests for proofs more robust wrt rewrite rules
  test/unit/api/c/capi_proof_black.cpp
  test/unit/api/cpp/api_proof_black.cpp
  test/unit/api/java/ProofTest.java
  test/unit/api/python/test_proof.py
Labels: minor, simple

#11529 bitblast_utils: Refactor to not use NodeManager::currentNM()
  src/theory/bv/bitblast/bitblast_strategies_template.h
  src/theory/bv/bitblast/bitblast_utils.h
Labels: normal, simple

#11598 Fix printer for user patterns and annotations
  src/printer/smt2/smt2_printer.cpp
Labels: normal, simple

#11607 Updates for string entail utility
  proofs/eo/cpc/rules/Strings.eo
  src/theory/quantifiers/extended_rewrite.cpp
  src/theory/strings/strings_entail.cpp
  src/theory/strings/strings_entail.h
  test/regress/cli/regress0/strings/rewrites-v2.smt2
Labels: normal, simple

#11610 Handle more cases in arith string pred entail
  src/theory/arith/arith_rewriter.cpp
Labels: minor, simple

#11611 Minor modifications to expert signature
  contrib/install-rare-rewrites
  proofs/eo/cpc/expert/CpcExpert.eo
  proofs/eo/cpc/expert/rules/SetsExt.eo
  proofs/eo/cpc/expert/theories/ArithExt.eo
  proofs/eo/cpc/expert/theories/Bags.eo
  proofs/eo/cpc/expert/theories/SepLogic.eo
  proofs/eo/cpc/expert/theories/SetsExt.eo
  proofs/eo/cpc/rules/Rewrites.eo
Labels: minor, simple

#11602 Guard more cases of constant arrays in assertions
  src/expr/node_algorithm.cpp
  src/expr/node_algorithm.h
  src/smt/smt_solver.cpp
  src/smt/smt_solver.h
  src/smt/solver_engine.cpp
  test/regress/cli/regress0/array-const-real-parse.smt2
  test/regress/cli/regress0/arrays/constarr.cvc.smt2
  test/regress/cli/regress0/arrays/constarr.smt2
  test/regress/cli/regress0/arrays/constarr2.cvc.smt2
  test/regress/cli/regress0/arrays/constarr2.smt2
  test/regress/cli/regress0/arrays/issue4414-2.smt2
  test/regress/cli/regress0/arrays/issue7596-define-array-uminus.smt2
  test/regress/cli/regress1/bug590.smt2
  test/regress/cli/regress1/datatypes/cee-prs-small-dd2.smt2
  test/regress/cli/regress1/datatypes/nested-rec-array-aa.smt2
  test/regress/cli/regress1/push-pop/cee-prs-small.smt2
Labels: minor, simple

#11595 ci: Use the minimum required CMake version on Linux runners
  .github/actions/install-dependencies/action.yml
Labels: normal, moderate, ci

#11566 Update policy on options exceptions
  src/options/option_exception.cpp
  src/options/option_exception.h
  src/smt/set_defaults.cpp
  src/smt/solver_engine.cpp
  src/theory/bv/int_blaster.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/options/safe-options-fatal.smt2
  test/regress/cli/regress0/options/safe-options1.smt2
  test/regress/cli/regress0/options/safe-options2.smt2
  test/regress/cli/regress0/options/safe-opts-warn.smt2
  test/regress/cli/regress0/sygus/interpolant-gn.smt2
  test/regress/cli/regress2/bv_to_int_quantifiers_bvand.smt2
  test/unit/options/options_black.cpp
Labels: normal, moderate

#11620 NodeBuilder: Assert that NodeManagers match.
  src/expr/node_builder.cpp
Labels: normal, simple

#11600 Add ProofRule::RE_CONCAT
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Strings.eo
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/proof/alf/alf_printer.cpp
  src/theory/strings/proof_checker.cpp
Labels: normal, simple

#11619 Split RARE rewrites for expert extensions to own files
  src/CMakeLists.txt
  src/theory/arith/rewrites
  src/theory/arith/rewrites-transcendentals
  src/theory/sets/rewrites
  src/theory/sets/rewrites-card
Labels: normal, simple

#11615 Fix documentation for transcendentals, make proof checker more pedantic
  include/cvc5/cvc5_proof_rule.h
  src/theory/arith/nl/transcendental/proof_checker.cpp
Labels: minor, simple

#11447 Add proof elaboration for diamonds preprocessing
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/theory/booleans/rewrites
  src/theory/uf/diamonds_proof_generator.cpp
Labels: normal, moderate

#11596 Add ProofRule::DISTINCT_VALUES
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/programs/DistinctValues.eo
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/proof/alf/alf_printer.cpp
  src/proof/alf/alf_printer.h
  src/theory/builtin/proof_checker.cpp
Labels: major, moderate

#11630 Add remaining cases of STRING_REDUCTION in Eunoia
  proofs/eo/cpc/programs/Strings.eo
  src/proof/alf/alf_printer.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress2/strings/sred-cases.smt2
Labels: normal, moderate

#11467 Add unused variables to RARE preprocess tactic
  src/rewriter/rewrite_db_proof_cons.cpp
Labels: normal, moderate

#11605 Simplify quantifiers variable elimination inequality rewrite
  include/cvc5/cvc5_proof_rule.h
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
Labels: normal, moderate

#11632 Generalize BV poly norm eq to odd coefficients
  proofs/eo/cpc/rules/BitVectors.eo
  src/theory/arith/arith_poly_norm.cpp
  src/theory/bv/proof_checker.cpp
Labels: normal, moderate

#11478 Miscellaneous refactoring of arithmetic RARE rewrites
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/theory/arith/rewrites
Labels: normal, moderate

#11627 Add regressions for fixed issues
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/quantifiers/issue9070-syqi-model.smt2
  test/regress/cli/regress1/issue10042.smt2
  test/regress/cli/regress1/issue9407-4.smt2
Labels: minor, simple

#11634 Add regressions for proofs
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/bv/bv-term-small-rw-228.smt2
  test/regress/cli/regress0/datatypes/tuple-update-elim.smt2
  test/regress/cli/regress0/proofs/dd_issue2031-bv-var-elim.smt2
  test/regress/cli/regress0/quantifiers/dd_small_pipeline_3.smt2
  test/regress/cli/regress0/quantifiers/var-elim-bv-partial.smt2
  test/regress/cli/regress0/strings/com-ctn.smt2
  test/regress/cli/regress0/strings/cprop-splice.smt2
  test/regress/cli/regress0/strings/nctn-concat-eq.smt2
  test/regress/cli/regress0/strings/nctn-concat.smt2
  test/regress/cli/regress0/strings/re-const-elim-rewrite-test.smt2
  test/regress/cli/regress0/strings/soundness-split-ctn.smt2
  test/regress/cli/regress0/strings/str-term-small-rw_1005.smt2
  test/regress/cli/regress0/strings/string-endpoint-rewrite-test.smt2
  test/regress/cli/regress1/quantifiers/dd_RNDPRE_4_28-subtype-elim.smt2
Labels: normal, simple

#11466 Add macro rewrite MACRO_BV_EQ_SOLVE
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/theory/bv/theory_bv_rewriter.cpp
Labels: minor, moderate

#11646 Add rewrite level (normal/expert for rewrite rules)
  src/CMakeLists.txt
  src/rewriter/CMakeLists.txt
  src/rewriter/mkrewrites.py
  src/rewriter/rewrite_db.cpp
  src/rewriter/rewrite_db.h
Labels: normal, simple

#11612 Add Eunoia signature defining translation from sequences to strings
  proofs/eo/cpc/programs/SeqToString.eo
Labels: normal, moderate

#11618 Add macros for (non-splitting) string overlap rules
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/sequences_rewriter.h
Labels: normal, moderate

#11638 Add Eunoia definition for ProofRewriteRule::DISTINCT_CARD_CONFLICT
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/programs/Utils.eo
  proofs/eo/cpc/rules/Uf.eo
  src/proof/alf/alf_printer.cpp
  src/theory/builtin/theory_builtin_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/bv/bv-card-conflict.smt2
Labels: normal, moderate

#11591 Add macros for string contains split overlap rule
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/sequences_rewriter.h
Labels: normal, moderate

#11649 Fix several Eunoia rules for sequences
  proofs/eo/cpc/programs/Strings.eo
  proofs/eo/cpc/rules/Strings.eo
  src/proof/alf/alf_printer.cpp
Labels: normal, moderate

#11496 arith: Refactor to not use NodeManager::currentNM()
  src/api/cpp/cvc5.cpp
  src/rewriter/basic_rewrite_rcons.cpp
  src/smt/proof_post_processor.cpp
  src/theory/arith/arith_msum.cpp
  src/theory/arith/arith_msum.h
  src/theory/arith/arith_proof_utilities.cpp
  src/theory/arith/arith_proof_utilities.h
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_utilities.h
  src/theory/arith/linear/arith_static_learner.cpp
  src/theory/arith/linear/callbacks.cpp
  src/theory/arith/linear/congruence_manager.cpp
  src/theory/arith/linear/constraint.cpp
  src/theory/arith/linear/constraint.h
  src/theory/arith/linear/normal_form.cpp
  src/theory/arith/linear/normal_form.h
  src/theory/arith/linear/theory_arith_private.cpp
  src/theory/arith/linear/theory_arith_private.h
  src/theory/arith/nl/coverings/cdcac.cpp
  src/theory/arith/nl/coverings/proof_generator.cpp
  src/theory/arith/nl/iand_solver.cpp
  src/theory/arith/nl/iand_utils.cpp
  src/theory/arith/nl/iand_utils.h
  src/theory/arith/nl/poly_conversion.cpp
  src/theory/arith/nl/poly_conversion.h
  src/theory/arith/nl/transcendental/proof_checker.cpp
  src/theory/arith/nl/transcendental/taylor_generator.cpp
  src/theory/arith/nl/transcendental/taylor_generator.h
  src/theory/arith/nl/transcendental/transcendental_state.cpp
  src/theory/arith/operator_elim.cpp
  src/theory/arith/rewriter/addition.cpp
  src/theory/arith/rewriter/addition.h
  src/theory/arith/rewriter/node_utils.cpp
  src/theory/arith/rewriter/node_utils.h
  src/theory/arith/rewriter/rewrite_atom.cpp
  src/theory/arith/rewriter/rewrite_atom.h
  src/theory/bv/int_blaster.cpp
Labels: normal, simple

#11636 Add distinct values to RARE reconstruction strategy
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/rewriter/basic_rewrite_rcons.cpp
  src/theory/arrays/theory_arrays_rewriter.cpp
  src/theory/sets/theory_sets_rewriter.cpp
Labels: normal, simple

#11653 Do not include expert Eunoia signature from main signature
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/expert/CpcExpert.eo
  proofs/eo/cpc/programs/AciNorm.eo
  proofs/eo/cpc/programs/Utils.eo
  src/proof/alf/alf_printer.cpp
Labels: minor, simple

#11628 Simplify internal proof checker for strings to not splice constants
  include/cvc5/cvc5_proof_rule.h
  src/theory/strings/proof_checker.cpp
Labels: major, moderate

#11652 Add helper functions to proof elaborator
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
Labels: normal, moderate

#11594 Simplifications to the core rules of the strings calculus
  proofs/eo/cpc/programs/Strings.eo
  proofs/eo/cpc/rules/Strings.eo
Labels: major, moderate

#11650 Add proof elaboration for string overlap macro rules
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
Labels: normal, moderate

#11642 Fixes for BV RARE rules
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/theory/bv/rewrites
  src/theory/bv/rewrites-elimination
  src/theory/bv/rewrites-simplification
Labels: normal, moderate

#11603 Improvements and optimizations for Eunoia quantifiers signature
  proofs/eo/cpc/programs/Quantifiers.eo
  proofs/eo/cpc/rules/Quantifiers.eo
Labels: normal, moderate

#11659 Add elaboration for MACRO_STR_EQ_LEN_UNIFY
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
Labels: normal, moderate

#11657 Add proof rewrite rule SEQ_EVAL_OP
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/programs/SeqToString.eo
  proofs/eo/cpc/programs/Utils.eo
  proofs/eo/cpc/rules/Quantifiers.eo
  proofs/eo/cpc/rules/Strings.eo
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/proof/alf/alf_printer.cpp
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings_utils.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/seq/seq-evals.smt2
Labels: normal, moderate

#11658 Add elaboration for MACRO_STR_EQ_LEN_UNIFY_PREFIX
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/theory/booleans/rewrites
Labels: normal, moderate

#11654 Do not purify ground Boolean subterms in quantifier bodies
  src/theory/quantifiers/ematching/trigger.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/quantifiers/proj-issue763-no-gt-purify-bool.smt2
Labels: normal, simple

#11666 Small Cosmetic Changes to RARE rules
  proofs/eo/cpc/rules/Rewrites.eo
  src/theory/booleans/rewrites
Labels: minor, simple

#11625 Add support for datatypes updater elimination rules in Eunoia
  proofs/eo/cpc/programs/Datatypes.eo
  proofs/eo/cpc/rules/Datatypes.eo
  proofs/eo/cpc/theories/Datatypes.eo
  src/proof/alf/alf_node_converter.cpp
  src/proof/alf/alf_printer.cpp
  src/theory/datatypes/datatypes_rewriter.cpp
Labels: normal, moderate

#11655 Do not use array constants in sygus grammars unless arraysExp is true
  src/preprocessing/passes/synth_rew_rules.cpp
  src/preprocessing/passes/synth_rew_rules.h
  src/smt/solver_engine.cpp
  src/theory/incomplete_id.cpp
  src/theory/incomplete_id.h
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/quantifiers/sygus/embedding_converter.cpp
  src/theory/quantifiers/sygus/embedding_converter.h
  src/theory/quantifiers/sygus/sygus_grammar_cons.cpp
  src/theory/quantifiers/sygus/sygus_grammar_cons.h
  src/theory/quantifiers/sygus/sygus_grammar_norm.cpp
  src/theory/quantifiers/sygus/synth_conjecture.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/quantifiers/issue8912-syqi-arr-const.smt2
  test/regress/cli/regress1/quantifiers/issue8456-2-syqi-ic.smt2
  test/regress/cli/regress1/sygus/issue3635.smt2
  test/regress/cli/regress2/quantifiers/issue10805-syqi-no-arr-const.smt2
Labels: normal, simple

#11668 Miscellaneous changes from proof dev branch
  src/expr/elim_shadow_converter.cpp
  src/printer/smt2/smt2_printer.cpp
  src/proof/proof.h
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv_rewrite_rules.h
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
Labels: minor, simple

#11672 Minor fix for quantifiers preprocessing pass
  src/options/quantifiers_options.toml
  src/preprocessing/passes/quantifiers_preprocess.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/quantifiers/proj-issue722-qpre.smt2
Labels: normal, simple

#11673 ci: Use separate GitHub Action to set up CMake
  .github/actions/install-dependencies/action.yml
  .github/actions/setup-cmake/action.yml
  .github/workflows/ci.yml
Labels: normal, simple, ci

#11674 Add bitvector concat and xor to ACI_NORM
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/expert/CpcExpert.eo
  proofs/eo/cpc/programs/AciNorm.eo
  src/expr/aci_norm.cpp
  src/expr/aci_norm.h
Labels: normal, moderate

#11671 Add regressions for fixed issues
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/theory/sets/rewrites
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arrays/issue8241-bad-model.smt2
  test/regress/cli/regress0/proofs/proj-issue544-nassume.smt2
  test/regress/cli/regress0/proofs/proj-issue606.smt2
  test/regress/cli/regress0/proofs/proj-issue669-nassume.smt2
  test/regress/cli/regress0/quantifiers/proj-issue688.smt2
  test/regress/cli/regress0/sets/sets-ising-elim-pf.smt2
Labels: minor, simple

#11681 Add macro and elaboration for MACRO_STR_COMPONENT_CTN
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/theory/strings/sequences_rewriter.cpp
Labels: normal, moderate

#11677 Add RARE rule for divisible
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/printer/smt2/smt2_printer.cpp
  src/rewriter/mkrewrites.py
  src/rewriter/node.py
  src/theory/arith/rewrites
  src/theory/builtin/generic_op.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arith/divisible-unsat.smt2
Labels: normal, simple

#11604 Introduce MACRO_QUANT_DT_VAR_EXPAND and its elaboration
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/theory/quantifiers/quant_split.cpp
  src/theory/quantifiers/quant_split.h
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
Labels: normal, moderate, do not merge

#11678 Refactor RE inter/union rewriter, add macro rewrite for RE inter/union constant elimination
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/theory/strings/rewrites.cpp
  src/theory/strings/rewrites.h
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/sequences_rewriter.h
Labels: normal, moderate

#11679 Add proof elaboration for MACRO_STR_CONST_NCTN_CONCAT
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
Labels: normal, moderate

#11682 Disable LFSC on regression
  test/regress/cli/regress0/seq/seq-evals.smt2
Labels: major, simple

#11680 Add proof elaboration for MACRO_STR_IN_RE_INCLUSION
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
Labels: normal, moderate

#11684 More fixes for LFSC + nightlies
  proofs/lfsc/signatures/theory_def.plf
  src/proof/lfsc/lfsc_node_converter.cpp
  test/regress/cli/regress2/quantifiers/issue10805-syqi-no-arr-const.smt2
Labels: major, simple

#11656 Eliminate use of LinearRewriteStrategy in cases where proofs can not be elaborated
  src/theory/bv/theory_bv_rewriter.cpp
Labels: normal, moderate

#11444 Only support datatype match if datatypesExp is true
  src/options/datatypes_options.toml
  src/theory/datatypes/datatypes_rewriter.cpp
  src/theory/datatypes/theory_datatypes.cpp
Labels: minor, simple

#11691 cmake: Introduce max version check for CaDiCaL.
  cmake/FindCaDiCaL.cmake
  cmake/deps-helper.cmake
Labels: normal, simple

#11692 cmake: Remove workaround that got addressed on CMS side.
  CMakeLists.txt
  INSTALL.rst
  cmake/FindCryptoMiniSat.cmake
Labels: normal, simple

#11633 Guard another case where variable elimination is not equivalence preserving
  src/theory/quantifiers/bv_inverter.cpp
  src/theory/quantifiers/bv_inverter.h
  src/theory/quantifiers/quantifiers_rewriter.cpp
  test/regress/cli/CMakeLists.txt
Labels: minor, simple

#11695 cadical: Make modelValue more robust.
  src/prop/cadical.cpp
Labels: major, simple

#11694 java: Remove reference to non-existent API function.
  src/api/java/io/github/cvc5/Utils.java
Labels: normal, simple
