Repository cvc5/cvc5, pull requests merged in 2025-06, with the labels that each got.

#11952 Remove deprecated table-based license key from pyproject.toml
  .github/workflows/package_pypi.yml
  src/api/python/pyproject.toml
Labels: normal, simple

#11953 cmake: Always set --build option when building GMP, CLN, and GLPK
  cmake/FindCLN.cmake
  cmake/FindGLPK.cmake
  cmake/FindGMP.cmake
  cmake/Helpers.cmake
Labels: normal, moderate

#11929 Ensure constant folding on BV overflow predicates
  src/theory/bv/theory_bv_rewriter.cpp
  src/theory/bv/theory_bv_rewriter.h
Labels: normal, simple

#11925 ci: Use the lowest supported Java version for each platform
  .github/workflows/ci.yml
  src/api/java/CMakeLists.txt
  test/unit/api/java/TermTest.java
Labels: normal, moderate, ci

#11958 Fix GPL arm64 macOS builds
  .github/workflows/ci.yml
  cmake/Helpers.cmake
  cmake/Toolchain-aarch64.cmake
Labels: major, simple

#11957 Modify regression
  test/regress/cli/regress0/proofs/issue8983-trust-subs.smt2
Labels: minor, simple

#11959 Remove spurious assertion for HO models
  src/theory/theory_model.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/push-pop/issue11934-ho-uf.smt2
Labels: minor, simple

#11955 Fix issue in HO solver with finite types
  src/theory/theory_model_builder.cpp
  src/theory/uf/ho_extension.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/ho/issue11923-2-finite-ho-deq.smt2
  test/regress/cli/regress0/ho/issue11923-finite-ho-deq.smt2
Labels: normal, moderate

#11963 Modify CPC definition of quantifiers rules to avoid eo::match
  proofs/eo/cpc/rules/Quantifiers.eo
Labels: normal, simple

#11954 Fix performance bug in RARE fixed point rules
  src/expr/term_context.cpp
  src/expr/term_context.h
  src/rewriter/rewrite_db_proof_cons.cpp
  src/rewriter/rewrite_db_proof_cons.h
  src/rewriter/rewrite_proof_rule.cpp
  src/rewriter/rewrite_proof_rule.h
  src/rewriter/rewrite_proof_status.cpp
  src/rewriter/rewrite_proof_status.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/bv/dd_bug787_dsl_fixed_pt.smt2
Labels: normal, moderate

#11977 Add portfolio-dry-run option
  src/main/portfolio_driver.cpp
  src/options/main_options.toml
Labels: normal, moderate

#11978 Eagerly eliminate duplicates in CPC+Eunoia definition of ACI_NORM
  proofs/eo/cpc/programs/AciNorm.eo
Labels: major, simple

#11980 Update CPC+Eunoia bitblast signature to avoid eo::match, use type checkable terms
  proofs/eo/cpc/programs/Bitblasting.eo
Labels: normal, moderate

#11985 Do not merge relevant domains of different type
  src/theory/quantifiers/relevant_domain.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/quantifiers/issue11968-rd-typed.smt2
Labels: normal, simple

#11983 Fix docs in preparation for upcoming release.
  docs/api/c/types/cvc5sort.rst
  docs/api/c/types/cvc5term.rst
  docs/api/python/base/kind.rst
  docs/ext/smtliblexer.py
  include/cvc5/c/cvc5.h
  include/cvc5/c/cvc5_parser.h
  include/cvc5/cvc5.h
  include/cvc5/cvc5_kind.h
  include/cvc5/cvc5_proof_rule.h
  src/api/python/cvc5.pxi
Labels: major, simple

#11979 More miscellaneous changes to Eunoia+CPC to ensure terms can be type checked
  proofs/eo/cpc/programs/BitVectors.eo
  proofs/eo/cpc/programs/Datatypes.eo
  proofs/eo/cpc/programs/Nary.eo
  proofs/eo/cpc/programs/Quantifiers.eo
  proofs/eo/cpc/programs/Utils.eo
  proofs/eo/cpc/rules/Uf.eo
Labels: normal, moderate

#11993 ci: Auto-populate release message.
  .github/actions/store-to-release/action.yml
Labels: major, simple

#11995 ci: Fix auto-population of release message.
  .github/actions/store-to-release/action.yml
Labels: major, simple

#11992 Take into account component types to compute well foundedness of dt constructors
  src/expr/dtype_cons.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/issue11991-nwf.smt2
Labels: normal, simple

#11999 ci: Tag latest as prerelease.
  .github/actions/store-to-latest/action.yml
Labels: minor, simple

#11998 cadical: Do not notifySatLiteral on renotify_fixed.
  src/prop/cadical.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/prop/issue11867.smt2
Labels: normal, simple

#12004 Add Editline setup steps in INSTALL.rst
  INSTALL.rst
Labels: minor, simple

#12011 OptionCategory: Add missing implementations, uncovered tests.
  src/api/c/cvc5.cpp
  src/api/c/cvc5_checks.h
  src/api/cpp/cvc5_types.cpp
  test/unit/api/c/CMakeLists.txt
  test/unit/api/c/capi_types_black.cpp
  test/unit/api/c/capi_uncovered_black.cpp
  test/unit/api/cpp/api_types_black.cpp
  test/unit/api/java/UncoveredTest.cpp
  test/unit/api/python/test_uncovered.cpp
Labels: major, simple

#12012 Do not filter output for the model-validation and unsat-cores tracks
  contrib/competitions/smt-comp/run-script-smtcomp-current-model-validation
  contrib/competitions/smt-comp/run-script-smtcomp-current-unsat-cores
Labels: normal, simple
