Repository cvc5/cvc5, pull requests merged in 2025-01, with the labels that each got.

#11480 Extend regex consume rewrite to incorporate star
  proofs/eo/cpc/programs/Strings.eo
  src/theory/strings/rewrites.cpp
  src/theory/strings/rewrites.h
  src/theory/strings/sequences_rewriter.cpp
Labels: normal, moderate

#11489 Fix regex consume for star
  proofs/eo/cpc/programs/Strings.eo
  src/theory/strings/sequences_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/strings/re-consume-star.smt2
Labels: major, moderate

#11424 Reorganize final proof callback
  src/smt/proof_final_callback.cpp
  src/smt/proof_final_callback.h
  src/smt/proof_manager.cpp
  src/smt/proof_manager.h
  src/smt/proof_post_processor.cpp
  src/smt/proof_post_processor.h
  src/smt/solver_engine.cpp
  test/regress/cli/regress0/printer/print_trusted_proof_steps.smt2
Labels: major, moderate

#11300 Initialize the rewriter based on safe-options
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/arith_rewriter.h
  src/theory/arith/arith_utilities.cpp
  src/theory/arith/theory_arith.cpp
  src/theory/bags/theory_bags.cpp
  src/theory/ff/theory_ff.cpp
  src/theory/fp/theory_fp.cpp
  src/theory/rewriter.cpp
  src/theory/rewriter.h
  src/theory/rewriter_tables_template.h
  src/theory/sep/theory_sep.cpp
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets_rewriter.cpp
  src/theory/sets/theory_sets_rewriter.h
  src/theory/theory_rewriter.h
Labels: major, moderate

#11462 Fixes for ARITH_MULT_ABS_COMPARISON
  src/proof/trust_id.cpp
  src/proof/trust_id.h
  src/smt/proof_post_processor.cpp
  src/theory/arith/nl/ext/arith_nl_compare_proof_gen.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/nl/dd.polypaver-bench-exp-3d-chunk-0067.smt2
  test/regress/cli/regress0/nl/dd.sin-cos-346-b-chunk-0210.smt2
  test/regress/cli/regress0/nl/dd.sin-cos-346-b-chunk-0210_unsat.smt2
Labels: major, moderate

#11382 Make arith static learning compatible with proofs and unsat cores
  src/proof/trust_id.cpp
  src/proof/trust_id.h
  src/smt/set_defaults.cpp
  src/theory/arith/linear/arith_static_learner.cpp
  src/theory/arith/linear/arith_static_learner.h
  src/theory/arith/linear/theory_arith_private.cpp
Labels: normal, moderate

#11482 Explicitly add nl-cov to regressions that require it
  test/regress/cli/regress0/arith/arith-rewrite-with-ran.smt2
  test/regress/cli/regress0/nl/issue3003.smt2
  test/regress/cli/regress0/nl/issue3652.smt2
  test/regress/cli/regress0/nl/issue3719.smt2
  test/regress/cli/regress0/nl/issue6547-ran-model.smt2
  test/regress/cli/regress0/nl/issue6619-ran-model.smt2
  test/regress/cli/regress0/nl/issue8226-ran-refinement.smt2
  test/regress/cli/regress0/nl/proj-issue-444-memout-eqelim.smt2
  test/regress/cli/regress0/nl/real-as-int.smt2
  test/regress/cli/regress0/nl/sin-cos-346-b-chunk-0169.smt2
  test/regress/cli/regress0/nl/sqrt2-value.smt2
  test/regress/cli/regress1/nl/approx-sqrt.smt2
  test/regress/cli/regress1/nl/issue3300-approx-sqrt-witness.smt2
Labels: normal, simple

#11401 Simplify interface for ppAssert
  src/preprocessing/passes/miplib_trick.cpp
  src/preprocessing/passes/non_clausal_simp.cpp
  src/prop/zero_level_learner.cpp
  src/theory/arith/linear/linear_solver.cpp
  src/theory/arith/linear/linear_solver.h
  src/theory/arith/linear/theory_arith_private.cpp
  src/theory/arith/linear/theory_arith_private.h
  src/theory/arith/theory_arith.cpp
  src/theory/arith/theory_arith.h
  src/theory/arrays/theory_arrays.cpp
  src/theory/arrays/theory_arrays.h
  src/theory/booleans/theory_bool.cpp
  src/theory/booleans/theory_bool.h
  src/theory/bv/theory_bv.cpp
  src/theory/bv/theory_bv.h
  src/theory/quantifiers/theory_quantifiers.cpp
  src/theory/quantifiers/theory_quantifiers.h
  src/theory/sets/theory_sets.cpp
  src/theory/sets/theory_sets.h
  src/theory/theory.cpp
  src/theory/theory.h
  src/theory/theory_engine.cpp
  src/theory/theory_engine.h
Labels: minor, simple

#11434 Add a 'safe' build profile that enables safe-options by default
  CMakeLists.txt
  configure.sh
  src/options/options_template.cpp
Labels: normal, simple

#11426 Fix possible invalid model construction in datatypes
  src/theory/datatypes/theory_datatypes.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/quantifiers/ufdt-solve-model-built.smt2
Labels: major, moderate

#11492 More missing cases of EVALUATE in CPC+Eunoia
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/programs/Strings.eo
  src/proof/alf/alf_printer.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/strings/from-int-eval.smt2
Labels: normal, moderate

#11500 Fix updated re consume
  src/theory/strings/sequences_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/strings/norn-153-consume.smt2
Labels: major, simple

#11402 Remove nested rewrite calls during preRewrite from arrays rewriter
  src/theory/arrays/theory_arrays_rewriter.cpp
  src/theory/arrays/theory_arrays_rewriter.h
Labels: normal, simple

#11499 strings: Refactor to not use NodeManager::currentNM()
  src/theory/strings/base_solver.cpp
  src/theory/strings/core_solver.cpp
  src/theory/strings/eager_solver.cpp
  src/theory/strings/infer_info.cpp
  src/theory/strings/infer_info.h
  src/theory/strings/inference_manager.cpp
  src/theory/strings/regexp_entail.cpp
  src/theory/strings/regexp_entail.h
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/theory_strings_utils.cpp
  src/theory/strings/theory_strings_utils.h
  src/theory/strings/type_enumerator.cpp
  src/theory/strings/type_enumerator.h
Labels: normal, simple

#11504 Make RE derive conflicts an expert option
  src/options/strings_options.toml
  src/theory/strings/regexp_solver.cpp
  test/regress/cli/regress0/strings/issue4662-consume-nterm.smt2
Labels: normal, simple

#11503 Minor fixes for Eunoia signature and output
  contrib/get-ethos-checker
  proofs/eo/cpc/programs/Utils.eo
  proofs/eo/cpc/theories/Builtin.eo
  proofs/eo/cpc/theories/Datatypes.eo
  src/proof/alf/alf_printer.cpp
Labels: minor, simple

#11452 Simplifications and fixes for strings infer proof cons
  src/proof/conv_proof_generator.cpp
  src/smt/proof_post_processor.cpp
  src/theory/strings/infer_proof_cons.cpp
  src/theory/strings/infer_proof_cons.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/strings/issue11197-str-ipc.smt2
Labels: normal, moderate

#11505 ci: Update cibuildwheel to v2.22.0
  .github/workflows/package_pypi.yml
Labels: normal, simple, ci

#11474 Add trust proof generator utility
  src/CMakeLists.txt
  src/proof/trust_id.cpp
  src/proof/trust_id.h
  src/proof/trust_proof_generator.cpp
  src/proof/trust_proof_generator.h
  src/theory/quantifiers/instantiate.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
Labels: minor, simple

#11475 Miscelleanous minor changes related to proofs
  src/theory/arith/pp_rewrite_eq.cpp
  src/theory/theory_engine.cpp
  src/theory/theory_preprocessor.cpp
  src/theory/theory_preprocessor.h
Labels: minor, simple

#11484 Add macro rewrite and RARE rewrite for arrays
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/theory/arrays/rewrites
  src/theory/arrays/theory_arrays_rewriter.cpp
Labels: normal, moderate

#11445 Setup callbacks to proof logging
  src/prop/cadical.cpp
  src/prop/cadical.h
  src/prop/minisat/minisat.cpp
  src/prop/minisat/minisat.h
  src/prop/prop_engine.cpp
  src/prop/prop_proof_manager.cpp
  src/prop/prop_proof_manager.h
  src/prop/sat_solver.h
  src/prop/theory_proxy.cpp
  src/smt/env.cpp
  src/smt/env.h
  src/smt/proof_manager.cpp
  src/smt/proof_manager.h
Labels: normal, moderate

#11506 ci: Provide project description for the PyPI packages
  .github/workflows/package_pypi.yml
  src/api/python/pyproject.toml
Labels: normal, simple, ci

#11329 Eliminate nested call to rewriter for beta reduction, generalize `ProofRule::BETA_REDUCE`
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/programs/Quantifiers.eo
  src/rewriter/rewrite_db_term_process.cpp
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf.h
  src/theory/uf/theory_uf_rewriter.cpp
  test/regress/cli/regress0/bv/holes/smod-eliminate-fewer-bitwise-ops.smt2
  test/regress/cli/regress0/cores/dd.uc-min-wrong.smt2
  test/regress/cli/regress0/proofs/dd_bug787_beta_reduce.smt2
  test/regress/cli/regress0/proofs/dd_fv-bvl.smt2
  test/regress/cli/regress0/proofs/define-fun-shadow.smt2
  test/regress/cli/regress0/proofs/issue9770-open-sat-proof.smt2
  test/regress/cli/regress1/bv/bug787.smt2
  test/regress/cli/regress1/bv2int-isabelle.smt2
  test/regress/cli/regress1/proofs/add_two_base.smt2
  test/regress/cli/regress1/quantifiers/example10714-core-no-miniscope-user.smt2
  test/regress/cli/regress1/quantifiers/proj-issue155.smt2
Labels: major, moderate

#11509 Move several string rewrites to extended rewrites
  src/theory/quantifiers/extended_rewrite.cpp
  src/theory/strings/rewrites.cpp
  src/theory/strings/rewrites.h
  src/theory/strings/sequences_rewriter.cpp
Labels: normal, moderate

#11508 More cases and fixes for strings infer proof constructor
  src/theory/strings/infer_proof_cons.cpp
Labels: normal, moderate

#11510 Add Eunoia definitions for 3 datatypes proof rules
  proofs/eo/cpc/programs/Datatypes.eo
  proofs/eo/cpc/rules/Datatypes.eo
  src/proof/alf/alf_printer.cpp
  test/regress/cli/regress1/datatypes/nullables/nullables2.smt2
Labels: minor, moderate

#11517 Define EVALUATE for more BV operators in Eunoia
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/programs/BitVectors.eo
  src/proof/alf/alf_printer.cpp
Labels: normal, moderate

#11518 Define EVALUATE for more string operators in Eunoia
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/programs/Strings.eo
  src/proof/alf/alf_printer.cpp
Labels: normal, moderate

#11515 Add more regressions that demonstrate proof holes
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arith/arith-min-max-static-learn-real.smt2
  test/regress/cli/regress0/arith/arith-min-max-static-learn.smt2
  test/regress/cli/regress0/arith/dd_59_static_learn.smt2
  test/regress/cli/regress0/cores/dd.uc-min-wrong.smt2
  test/regress/cli/regress0/proofs/proj-issue430-coverings-double-negation.smt2
  test/regress/cli/regress0/strings/eval-leading-zeroes.smt2
  test/regress/cli/regress0/strings/replace-find-base.smt2
  test/regress/cli/regress0/strings/slent_dio_lemma.smt2
  test/regress/cli/regress1/ho/dd.seu-mbqi.smt2
  test/regress/cli/regress1/quantifiers/dd_full_xor-rcons-open.smt2
  test/regress/cli/regress1/quantifiers/dd_ghc_macro_quant_prenex.smt2
Labels: normal, simple

#11483 Add proof rules for extended operators regex evaluation
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/sequences_rewriter.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/strings/ext-op-re-eval-simple-test.smt2
Labels: normal, moderate

#11491 Add 3 macro theory rewrites and a theory rewrite for sets
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/theory/sets/theory_sets_rewriter.cpp
Labels: normal, moderate

#11522 booleans/builtin: Refactor to not use NodeManager::currentNM()
  src/smt/proof_post_processor.cpp
  src/theory/arith/pp_rewrite_eq.cpp
  src/theory/booleans/circuit_propagator.cpp
  src/theory/booleans/proof_circuit_propagator.cpp
  src/theory/booleans/proof_circuit_propagator.h
  src/theory/builtin/generic_op.cpp
  src/theory/builtin/generic_op.h
  src/theory/builtin/proof_checker.cpp
  src/theory/builtin/proof_checker.h
  src/theory/ff/cocoa_encoder.cpp
  src/theory/ff/cocoa_encoder.h
  src/theory/ff/split_gb.cpp
  src/theory/ff/sub_theory.cpp
  src/theory/ff/util.cpp
  src/theory/ff/util.h
  src/theory/rewriter.cpp
  src/theory/theory_engine.cpp
  src/theory/uf/symmetry_breaker.cpp
  src/theory/uf/symmetry_breaker.h
Labels: normal, simple

#11525 List theories in check model failures
  src/smt/check_models.cpp
Labels: normal, moderate

#11521 Add elaboration for remaining case of macro-dt-cons-eq
  src/rewriter/basic_rewrite_rcons.cpp
  src/theory/datatypes/theory_datatypes_utils.cpp
  src/theory/datatypes/theory_datatypes_utils.h
  test/regress/cli/regress1/datatypes/nullables/nullable-lift-unsat.smt2
Labels: normal, moderate

#11479 Add new skolem ids for proof rules involving witness terms
  include/cvc5/cvc5_skolem_id.h
  src/expr/skolem_manager.cpp
  src/printer/enum_to_string.cpp
Labels: normal, simple

#11528 proof_node_to_sexpr: Refactor to not use NodeManager::currentNM()
  src/proof/proof_node.cpp
  src/proof/proof_node_to_sexpr.cpp
  src/proof/proof_node_to_sexpr.h
Labels: normal, simple

#11524 Ensure trust id for solve-int-as-real
  src/preprocessing/passes/real_to_int.cpp
  src/proof/trust_id.cpp
  src/proof/trust_id.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proj-issue750-real-to-int-safe.smt2
Labels: minor, simple

#11429 Add three new ad-hoc rewrites for strings
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Strings.eo
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/proof/alf/alf_printer.cpp
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/sequences_rewriter.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/strings/rw_65.smt2
Labels: normal, moderate

#11501 Refactor congruence proof rules
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Uf.eo
  src/proof/alethe/alethe_node_converter.h
  src/proof/alf/alf_node_converter.cpp
  src/proof/alf/alf_node_converter.h
  src/proof/alf/alf_printer.cpp
  src/proof/conv_proof_generator.cpp
  src/proof/proof_node_algorithm.cpp
  src/proof/proof_node_to_sexpr.cpp
  src/proof/subtype_elim_proof_converter.cpp
  src/proof/theory_proof_step_buffer.cpp
  src/theory/datatypes/infer_proof_cons.cpp
  src/theory/uf/eq_proof.cpp
  src/theory/uf/proof_checker.cpp
  test/regress/cli/regress0/datatypes/dt-sel-2.6.smt2
  test/regress/cli/regress0/datatypes/par-updater-type-rule.smt2
  test/regress/cli/regress1/fmf/agree467.smt2
  test/regress/cli/regress1/quantifiers/bug_743.smt2
  test/regress/cli/regress1/quantifiers/cdt-0208-to.smt2
  test/regress/cli/regress1/quantifiers/inst-max-level-segf.smt2
  test/regress/cli/regress1/quantifiers/issue4400-2-already-conf.smt2
  test/regress/cli/regress1/quantifiers/set3.smt2
  test/regress/cli/regress1/quantifiers/set8.smt2
  test/regress/cli/regress1/quantifiers/seu169+1.smt2
  test/regress/cli/regress2/bags/pull_null.smt2
  test/regress/cli/regress2/bug812.smt2
  test/regress/cli/regress2/issue6495-dup-pat-term.smt2
Labels: normal, moderate

#11541 Disable cpc on regression
  test/regress/cli/regress1/quantifiers/cdt-0208-to.smt2
Labels: major, simple

#11493 Add option to disallow overloading of terms and sorts
  src/api/cpp/cvc5_parser.cpp
  src/options/parser_options.toml
  src/parser/commands.cpp
  src/parser/parser_state.cpp
  src/parser/parser_state.h
  src/parser/smt2/smt2_cmd_parser.cpp
  src/parser/smt2/smt2_state.cpp
  src/parser/sym_manager.cpp
  src/parser/sym_manager.h
  src/parser/symbol_table.cpp
  src/parser/symbol_table.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/datatypes/issue9042-rel-irrel-cons-model.smt2
  test/regress/cli/regress0/datatypes/pf-v2l60078.smt2
  test/regress/cli/regress0/dd.bad-conv-rewrite.smt2
  test/regress/cli/regress0/ho/dd.shadowing-defs.smt2
  test/regress/cli/regress0/parser/issue9568-dt-multi-line.smt2
  test/regress/cli/regress0/parser/sort-term-overload-simple-unsat.smt2
  test/regress/cli/regress0/parser/term-sort-overload.smt2
  test/regress/cli/regress0/proofs/nomerge-alethe-pf.smt2
  test/regress/cli/regress0/proofs/pfcheck-ufdt-distro.smt2
  test/regress/cli/regress0/quantifiers/dd_german169_semi_eval.smt2
  test/regress/cli/regress0/seq/shared-term-registration.smt2
  test/regress/cli/regress0/sygus/dt-sel-parse1.sy
  test/regress/cli/regress1/bug296.smt2
  test/regress/cli/regress1/bug507.smt2
  test/regress/cli/regress1/cee-bug0909-dd-scope.smt2
  test/regress/cli/regress1/fmf/issue916-fmf-or.smt2
  test/regress/cli/regress1/quantifiers/seqa-unsat-unknown-110921.smt2
  test/regress/cli/regress1/sygus/clock-inc-tuple.sy
  test/regress/cli/regress1/sygus/error1-dt.sy
  test/regress/cli/regress1/sygus/issue3109-share-sel.sy
Labels: normal, moderate

#11539 More updates to safe options
  src/options/quantifiers_options.toml
  src/options/smt_options.toml
  src/options/strings_options.toml
  src/options/uf_options.toml
  src/proof/trust_id.cpp
  src/proof/trust_id.h
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.h
  src/theory/quantifiers/inst_strategy_sub_conflict.cpp
  src/theory/quantifiers/inst_strategy_sub_conflict.h
Labels: normal, simple

#11532 Fix theory mismatch in expand definitions
  src/smt/expand_definitions.cpp
  src/theory/datatypes/datatypes_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/datatypes/proj-issue754-check-model.smt2
Labels: major, simple

#11513 Add macro rule for capture avoidance in beta redexes and its elaboration
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/expr/node_algorithm.cpp
  src/expr/node_algorithm.h
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf_rewriter.cpp
  src/theory/uf/theory_uf_rewriter.h
  test/regress/cli/regress0/bv/holes/smod-eliminate-fewer-bitwise-ops.smt2
  test/regress/cli/regress0/cores/dd.uc-min-wrong.smt2
  test/regress/cli/regress0/proofs/dd_bug787_beta_reduce.smt2
  test/regress/cli/regress0/proofs/dd_fv-bvl.smt2
  test/regress/cli/regress0/proofs/issue9770-open-sat-proof.smt2
  test/regress/cli/regress1/bv/bug787.smt2
  test/regress/cli/regress1/bv2int-isabelle.smt2
  test/regress/cli/regress1/proofs/add_two_base.smt2
  test/regress/cli/regress1/quantifiers/example10714-core-no-miniscope-user.smt2
  test/regress/cli/regress1/quantifiers/proj-issue155.smt2
Labels: major, moderate

#11549 Do not set dag-thresh to 0 when printing unsat cores
  src/proof/unsat_core.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/printer/unsat-core-dagify.smt2
Labels: normal, simple

#11538 Simplify the behavior of the arithmetic entail utility in strings
  src/options/strings_options.toml
  src/theory/quantifiers/extended_rewrite.cpp
  src/theory/strings/arith_entail.cpp
  src/theory/strings/arith_entail.h
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/sequences_rewriter.h
  src/theory/strings/strings_rewriter.cpp
  src/theory/strings/strings_rewriter.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/strings/dd_1302_str_rewrite.smt2
  test/regress/cli/regress2/strings/proj-439-cyclic-str-ipc.smt2
  test/unit/theory/sequences_rewriter_white.cpp
Labels: normal, moderate

#11544 Fix case of collect model info in strings related to cardinality
  src/theory/strings/theory_strings.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/seq/proj-issue747-cmi-len-split.smt2
Labels: normal, simple

#11547 Add Eunoia definition of QUANT_DT_SPLIT
  proofs/eo/cpc/rules/Quantifiers.eo
  src/proof/alf/alf_printer.cpp
Labels: minor, moderate

#11552 More fixes and improvements for strings infer proof cons
  src/theory/strings/infer_proof_cons.cpp
Labels: normal, moderate

#11512 Change syntax for const/var in cpc proofs
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/theories/Builtin.eo
  src/proof/alf/alf_node_converter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/quantifiers/dd_verisec-dt-sygus.smt2
Labels: normal, simple

#11555 doc: Explain how to use self-contained Java API JAR
  docs/api/java/java.rst
Labels: normal, simple

#11551 Clarify misleading wording in bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: minor, simple

#11545 Ensure lemmas from static learning are rewritten
  src/preprocessing/assertion_pipeline.cpp
  src/preprocessing/assertion_pipeline.h
  src/preprocessing/passes/static_learning.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/preprocess/proj-issue749-ensureRew.smt2
Labels: normal, simple

#11534 Make constant arrays require array-exp
  src/smt/set_defaults.cpp
  src/theory/arrays/theory_arrays.cpp
  test/regress/cli/regress0/arrays/issue4414.smt2
  test/regress/cli/regress0/arrays/issue5925-2.smt2
  test/regress/cli/regress0/arrays/issue5925.smt2
  test/regress/cli/regress0/parser/fp_value.smt2
  test/regress/cli/regress1/bug681.smt2
  test/regress/cli/regress1/constarr3.cvc.smt2
  test/regress/cli/regress1/constarr3.smt2
  test/regress/cli/regress1/sygus/array-uc.sy
  test/regress/cli/regress1/sygus/node-discrete.sy
  test/regress/cli/regress1/sygus/qf_abv.smt2
Labels: normal, simple

#11546 ci: Use GHA-native Linux arm64 runners
  .github/actions/store-to-latest/action.yml
  .github/workflows/ci.yml
  .github/workflows/gpl-linux-arm64.yml
  .github/workflows/package_pypi.yml
  CMakeLists.txt
  contrib/arm64-gpl.Dockerfile
Labels: normal, moderate, ci

#11553 [alethe] Remove deleted option from contrib script
  contrib/get-carcara-checker
Labels: normal, simple

#11523 Further restrictions on theory rewriters related to safe options
  src/smt/solver_engine.cpp
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp_rewriter.cpp
  src/theory/fp/theory_fp_rewriter.h
  src/theory/fp/theory_fp_utils.cpp
  src/theory/fp/theory_fp_utils.h
  src/theory/rewriter.cpp
  src/theory/rewriter.h
  src/theory/rewriter_tables_template.h
  src/theory/theory_rewriter.cpp
  src/theory/theory_rewriter.h
  test/api/cpp/issues/proj-issue567.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/ff/proj-issue748-safe.smt2
  test/regress/cli/regress0/fp/issue5511.smt2
  test/regress/cli/regress0/fp/issue6164.smt2
  test/regress/cli/regress0/fp/proj-issue744-safe.smt2
  test/regress/cli/regress0/fp/proj-issue745-safe.smt2
  test/regress/cli/regress0/fp/proj-issue746-safe.smt2
  test/regress/cli/regress0/options/safe-opts-warn.smt2
  test/regress/cli/regress1/sygus/temp_input_to_synth_ic-error-121418.sy
Labels: normal, moderate

#11562 Fix corner case in lfsc node conversion
  src/proof/lfsc/lfsc_node_converter.cpp
Labels: major, simple

#11477 Catch cases where list terms are used with illegal kinds in RARE rules
  src/expr/nary_term_util.cpp
  src/rewriter/rewrite_proof_rule.cpp
Labels: minor, simple

#11560 java: Change search order for native libraries
  .github/actions/add-jar/action.yml
  docs/api/java/java.rst
  src/api/java/io/github/cvc5/Utils.java
Labels: normal, moderate

#11476 Simplifications and improvements for ARITH_MULT_SIGN
  include/cvc5/cvc5_proof_rule.h
  src/theory/arith/nl/ext/monomial_check.cpp
  src/theory/arith/nl/ext/proof_checker.cpp
Labels: normal, simple

#11554 Preparation for 1.2.1 release
  NEWS.md
  contrib/get-ethos-checker
Labels: normal, simple

#11564 Another fix for LFSC
  src/proof/lfsc/lfsc_node_converter.cpp
Labels: major, simple

#11567 Disable unstable regression
  test/regress/cli/CMakeLists.txt
Labels: major, simple

#11558 Update the list of build types
  CMakeLists.txt
  configure.sh
Labels: normal, simple

#11556 More preparation for eliminating nested calls to rewriter in strings rewriter
  src/rewriter/basic_rewrite_rcons.cpp
  src/theory/quantifiers/extended_rewrite.cpp
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/sequences_rewriter.h
  src/theory/strings/strings_entail.cpp
  src/theory/strings/strings_entail.h
  src/theory/strings/strings_rewriter.cpp
  src/theory/strings/strings_rewriter.h
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings.h
  test/unit/theory/sequences_rewriter_white.cpp
Labels: normal, simple

#11571 ci: Add option to choose the Python versions to build
  .github/workflows/package_pypi.yml
Labels: major, simple, ci

#11570 Demote more string rewrites to the extended rewriter
  src/theory/quantifiers/extended_rewrite.cpp
  src/theory/strings/sequences_rewriter.cpp
Labels: normal, moderate

#11511 Add default proof logger to log cpc proofs
  src/options/proof_options.toml
  src/proof/trust_id.cpp
  src/proof/trust_id.h
  src/smt/proof_logger.cpp
  src/smt/proof_logger.h
  src/smt/proof_manager.cpp
  src/smt/set_defaults.cpp
  src/smt/smt_solver.cpp
Labels: normal, moderate
