Repository cvc5/cvc5, pull requests merged in 2025-09, with the labels that each got.

#12096 ci: Update code to clean up artifacts from latest
  .github/actions/store-to-latest/action.yml
  .github/workflows/ci.yml
Labels: normal, moderate, ci

#12076 ci: Change the GH job that builds the documentation
  .github/workflows/ci.yml
Labels: normal, simple, ci

#12093 Do not do congruence over ordinary kinds in the model equality engine
  src/theory/theory_model.cpp
  src/theory/theory_model_builder.cpp
  src/theory/uf/ho_extension.cpp
  src/theory/uf/ho_extension.h
  src/theory/uf/theory_uf.cpp
  src/theory/uf/theory_uf.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/datatypes/nullables/dd_nullables8-m-add-term.smt2
  test/regress/cli/regress1/fmf/dd_nun-0208-to-nmc.smt2
  test/regress/cli/regress1/ho/mbqi-nmc-no-app-cmp.smt2
  test/regress/cli/regress2/quantifiers/dd_net_policy.smt2
Labels: normal, moderate

#12097 doc: Avoid duplicate indexing of cvc5.pythonic.Length
  docs/api/python/pythonic/string.rst
Labels: normal, simple

#12114 Disable timeout regression
  test/regress/cli/CMakeLists.txt
Labels: normal, simple

#12115 Ensure secant planes for exp don't cross zero
  src/theory/arith/nl/transcendental/exponential_solver.cpp
  src/theory/arith/nl/transcendental/proof_checker.cpp
Labels: normal, simple

#12104 ci: Use single job to set up release pages
  .github/actions/add-jar/action.yml
  .github/actions/add-package/action.yml
  .github/actions/add-wasm/action.yml
  .github/actions/setup-latest/action.yml
  .github/actions/setup-new-version/action.yml
  .github/actions/store-to-latest/action.yml
  .github/actions/store-to-release/action.yml
  .github/workflows/ci.yml
Labels: normal, moderate, ci

#12111 Add support for compilation on Windows ARM64
  INSTALL.rst
  docs/api/python/python.rst
  examples/api/c/quickstart.c
  include/cvc5/cvc5_parser.h
  src/api/c/cvc5.cpp
  src/api/python/setup.py.in
  src/base/exception.h
  src/expr/metakind_template.h
  src/expr/type_node.cpp
  src/expr/type_node.h
  src/printer/printer.cpp
  src/printer/printer.h
Labels: normal, simple

#12116 cmake: Update versioning scheme
  cmake/version.cmake
Labels: normal, moderate

#12119 ci: Add Windows ARM64 build job
  .github/actions/add-package/action.yml
  .github/actions/install-dependencies/action.yml
  .github/actions/run-tests/action.yml
  .github/workflows/ci.yml
  .github/workflows/package_pypi.yml
Labels: normal, simple

#12112 ci: Treat all Sphinx warnings as errors
  INSTALL.rst
  docs/CMakeLists.txt
  docs/api/java/quickstart.rst
Labels: normal, simple

#12118 Move distinct to theory UF
  src/theory/builtin/kinds.toml
  src/theory/builtin/theory_builtin_rewriter.cpp
  src/theory/builtin/theory_builtin_rewriter.h
  src/theory/builtin/theory_builtin_type_rules.cpp
  src/theory/builtin/theory_builtin_type_rules.h
  src/theory/uf/kinds.toml
  src/theory/uf/theory_uf_rewriter.cpp
  src/theory/uf/theory_uf_rewriter.h
  src/theory/uf/theory_uf_type_rules.cpp
  src/theory/uf/theory_uf_type_rules.h
Labels: normal, moderate

#12088 Add SMT-LIB command to print model domain elements.
  src/api/cpp/cvc5.cpp
  src/parser/commands.cpp
  src/parser/commands.h
  src/parser/smt2/smt2_cmd_parser.cpp
  src/parser/tokens.h
  src/printer/printer.cpp
  src/printer/printer.h
  src/printer/smt2/smt2_printer.cpp
  src/printer/smt2/smt2_printer.h
  src/theory/uf/cardinality_extension.cpp
  src/util/uninterpreted_sort_value.cpp
  src/util/uninterpreted_sort_value.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/fmf/get-model-domain-elements.smt2
Labels: normal, moderate

#12126 Fix type in macro elaboration of var-elim-ineq
  src/rewriter/basic_rewrite_rcons.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/typeerror.smt2
Labels: normal, simple

#12129 Fix sort reps printing bug in get-model command.
  src/theory/theory_model.cpp
  src/theory/uf/cardinality_extension.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/fmf/get-model-domain-elements.smt2
  test/regress/cli/regress0/fmf/get-model.smt2
Labels: normal, moderate

#12130 Fix nightly failure.
  test/regress/cli/regress0/fmf/get-model-domain-elements.smt2
Labels: major, simple

#12128 Add stable as a build type
  .github/workflows/ci.yml
  CMakeLists.txt
  NEWS.md
  cmake/cvc5Config.cmake.in
  configure.sh
  examples/api/cpp/CMakeLists.txt
  examples/api/java/CMakeLists.txt
  examples/api/python/CMakeLists.txt
  src/base/configuration.cpp
  src/base/configuration.h
  src/base/configuration_private.h
  src/options/options_handler.cpp
  src/options/options_template.cpp
  src/smt/illegal_checker.cpp
  src/smt/logic_exception.h
  src/theory/theory_rewriter.cpp
  test/api/c/CMakeLists.txt
  test/api/cpp/CMakeLists.txt
  test/api/cpp/issues/CMakeLists.txt
  test/api/python/CMakeLists.txt
  test/regress/cli/run_regression.py
Labels: major, moderate

#12134 Document missing change from 1.3.0 in NEWS
  NEWS.md
Labels: major, simple

#12132 Minor updates for printing CPC proofs
  NEWS.md
  contrib/get-ethos-checker
  src/printer/smt2/smt2_printer.cpp
  src/proof/alf/alf_printer.cpp
Labels: major, simple

#12146 ci: Add option to choose release version to build
  .github/actions/setup-new-version/action.yml
  .github/workflows/ci.yml
Labels: major, simple

#12150 [alethe] Update names of proof-specific BV operators
  contrib/get-carcara-checker
  src/proof/alethe/alethe_node_converter.cpp
Labels: normal, simple
