Repository cvc5/cvc5, pull requests merged in 2025-03, with the labels that each got.

#11686 Guard another case of expert extensions of arithmetic
  src/theory/arith/operator_elim.cpp
Labels: normal, simple

#11687 Add proof rewrite rule MACRO_BOOL_BV_INVERT_SOLVE
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/options/quantifiers_options.toml
  src/theory/booleans/theory_bool_rewriter.cpp
  src/theory/booleans/theory_bool_rewriter.h
  src/theory/quantifiers/bv_inverter.cpp
  src/theory/quantifiers/bv_inverter.h
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/term_registry.cpp
Labels: normal, moderate

#11685 Add proof elaboration for MACRO_RE_INTER_UNION_CONST_ELIM
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
Labels: normal, moderate

#11697 Add regressions for fixed issues.
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arrays/proj-issue322-has-term.smt2
  test/regress/cli/regress0/arrays/proj-issue391-minisat-elim.smt2
  test/regress/cli/regress0/arrays/proj-issue467-cm.smt2
  test/regress/cli/regress0/proj-issue614-minisat.smt2
  test/regress/cli/regress0/quantifiers/proj-issue411-bv-as-int.smt2
  test/regress/cli/regress1/proj-issue255-2-interpol.smt2
  test/regress/cli/regress1/proj-issue255-3-interpol.smt2
Labels: minor, simple

#11688 Fix elaboration of MACRO_SR_PRED_TRANSFORM
  src/smt/proof_post_processor.cpp
  src/smt/witness_form.cpp
  src/smt/witness_form.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress4/swap_t1_pp_nf_ai_00010_004.cvc.smt2
Labels: major, moderate

#11663 Add regressions for more proof holes
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/aufbv/dd_644_ph7.smt2
  test/regress/cli/regress0/bv/bitwise-and-simp.smt2
  test/regress/cli/regress0/bv/bitwise-or-simp.smt2
  test/regress/cli/regress0/bv/holes/bv-ite-width-one.smt2
  test/regress/cli/regress0/quantifiers/dd_check-cc_bvxor-mpath.smt2
  test/regress/cli/regress0/quantifiers/dd_check-cc_bvxor.smt2
  test/regress/cli/regress0/quantifiers/dd_check_eq_bvnot_32bit.smt2
  test/regress/cli/regress0/quantifiers/dd_water_tank-node25619.smt2
  test/regress/cli/regress1/quantifiers/inv-conds.smt2
  test/regress/cli/regress1/strings/ss-combine-large-substr.smt2
Labels: normal, simple

#11683 Improve recursion limit heuristic in RARE
  src/rewriter/rewrite_db_proof_cons.cpp
Labels: normal, simple

#11690 Improve warnings and errors for sygus-inference
  src/preprocessing/passes/sygus_inference.cpp
  test/regress/cli/regress1/quantifiers/issue4021-ind-opts.smt2
Labels: minor, simple

#11637 Add proof rule ABSORB
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/Cpc.eo
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/expr/aci_norm.cpp
  src/expr/aci_norm.h
  src/proof/alf/alf_printer.cpp
  src/rewriter/rewrite_db_proof_cons.cpp
  src/rewriter/rewrite_proof_status.cpp
  src/rewriter/rewrite_proof_status.h
  src/theory/builtin/proof_checker.cpp
Labels: normal, moderate

#11701 Add proof elaboration for MACRO_BOOL_BV_INVERT_SOLVE
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/theory/booleans/theory_bool_rewriter.cpp
Labels: normal, moderate

#11702 Print the result to the most recent solver's output stream
  src/main/command_executor.cpp
  src/main/command_executor.h
  src/parser/commands.cpp
  src/parser/commands.h
Labels: normal, moderate

#11693 Fix JNI string conversion to handle Unicode surrogate pairs
  src/api/java/jni/term.cpp
  test/unit/api/java/TermTest.java
Labels: normal, moderate

#11706 Add more regressions for proof holes
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/bv/bvult-large-triv.smt2
  test/regress/cli/regress0/bv/concat-extract-merge-adj-ex.smt2
  test/regress/cli/regress0/bv/dd.773_sqlite3.smt2
  test/regress/cli/regress0/bv/dd.kmdf_osrusbfx2_exe_testapp.c.smt2
  test/regress/cli/regress0/bv/dd.try_small_difret.smt2
  test/regress/cli/regress0/bv/dd_run_0000-and-or-pullup-2.smt2
  test/regress/cli/regress0/bv/dd_run_0000-and-or-pullup.smt2
  test/regress/cli/regress0/bv/dd_run_0000.smt2
  test/regress/cli/regress0/bv/holes/bvcomp-hole-qurt.smt2
  test/regress/cli/regress0/bv/macro-rewrites.smt2
  test/regress/cli/regress0/bv/overflow/smulo1b.smt2
  test/regress/cli/regress0/dd_arith_bv_conv-rpf.smt2
  test/regress/cli/regress0/quantifiers/dd_check_cc_bvxor_x_s_4.smt2
  test/regress/cli/regress0/quantifiers/dd_check_ic_sext_4_4.smt2
  test/regress/cli/regress0/quantifiers/dd_kmdf_osrubvfx2.smt2
  test/regress/cli/regress0/strings/large-unify.smt2
  test/regress/cli/regress2/nl/ufnia-factor-open-proof.smt2
  test/regress/cli/regress2/strings/strings-alpha-card-65.smt2
  test/regress/cli/regress3/bags/reduce_constants_dup.smt2
  test/regress/cli/regress3/bv_to_int_and_or.smt2
Labels: normal, moderate

#11707 Setup infrastructure for necessary BV macro rewrites
  include/cvc5/cvc5_proof_rule.h
  src/CMakeLists.txt
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
  src/theory/bv/macro_rewrite_elaborator.cpp
  src/theory/bv/macro_rewrite_elaborator.h
  src/theory/bv/theory_bv_rewrite_rules_core.h
  src/theory/bv/theory_bv_rewriter.cpp
Labels: normal, moderate

#11705 Fix check for whether a regular expression is constant, guard cases of RegLan in constraints
  src/theory/quantifiers/sygus/cegis.cpp
  src/theory/quantifiers/sygus/cegis.h
  src/theory/strings/regexp_entail.cpp
  src/theory/strings/theory_strings.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/strings/issue11703-re-uf.smt2
Labels: major, simple

#11662 Add necessary BV rewrites
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/rewriter/node.py
  src/theory/bv/rewrites
  src/theory/bv/rewrites-elimination
  src/theory/bv/rewrites-simplification
Labels: normal, moderate

#11711 quantifiers: Eliminate calls to NodeManager::currentNM()
  src/expr/node_manager_template.cpp
  src/expr/node_manager_template.h
  src/expr/type_node.h
  src/theory/quantifiers/bv_inverter.cpp
  src/theory/quantifiers/bv_inverter_utils.cpp
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.cpp
  src/theory/quantifiers/dynamic_rewrite.cpp
  src/theory/quantifiers/ematching/ho_trigger.cpp
  src/theory/quantifiers/ematching/pattern_term_selector.cpp
  src/theory/quantifiers/ematching/trigger.cpp
  src/theory/quantifiers/fmf/full_model_check.cpp
  src/theory/quantifiers/ho_term_database.cpp
  src/theory/quantifiers/oracle_engine.cpp
  src/theory/quantifiers/quantifiers_attributes.cpp
  src/theory/quantifiers/skolemize.cpp
  src/theory/quantifiers/sygus/sygus_enumerator.cpp
  src/theory/quantifiers/sygus/sygus_unif_io.cpp
  src/theory/quantifiers/sygus_inst.cpp
  src/theory/quantifiers/term_util.cpp
Labels: normal, moderate

#11714 Simple fixes for projects issues
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/quantifiers/sygus/sygus_interpol.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/datatypes/proj-issue620-inst-const-no-rew.smt2
  test/regress/cli/regress0/seq/proj-issue708-explain.smt2
  test/regress/cli/regress1/proj-issue410-subs-dt-interpol.smt2
Labels: minor, simple

#11614 Consolidate sets evaluation rules, implement in Eunoia
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Sets.eo
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/proof/alf/alf_printer.cpp
  src/theory/sets/theory_sets_rewriter.cpp
Labels: normal, moderate

#11712 bv: Eliminate calls to NodeManager::currentNM()
  src/theory/bv/theory_bv_rewrite_rules_normalization.h
  src/theory/bv/theory_bv_rewrite_rules_operator_elimination.h
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
  src/theory/bv/theory_bv_utils.cpp
Labels: normal, simple

#11713 Fix numeric overflow case in strings rewriter
  src/theory/strings/sequences_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/strings/issue11710-numeric-max.smt2
Labels: normal, simple

#11629 Remove DT_CLASH proof rule
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/theory/datatypes/infer_proof_cons.cpp
  src/theory/datatypes/proof_checker.cpp
Labels: normal, moderate

#11720 Add proof elaboration for And/Or/Xor simplify rules
  src/theory/bv/macro_rewrite_elaborator.cpp
  src/theory/bv/macro_rewrite_elaborator.h
Labels: normal, simple

#11723 Avoid deadlock in HO model construction
  src/theory/theory_model_builder.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/quantifiers/choice-unk-ho-no-deadlock.smt2
Labels: normal, simple

#11719 Minor fixes and improvements for CPC Eunoia signature
  proofs/eo/cpc/expert/theories/ArithExt.eo
  proofs/eo/cpc/programs/PolyNorm.eo
  proofs/eo/cpc/rules/Datatypes.eo
  proofs/eo/cpc/theories/Arith.eo
  proofs/eo/cpc/theories/Reals.eo
Labels: minor, simple

#11664 More updates to safe options
  src/options/datatypes_options.toml
  src/options/quantifiers_options.toml
  src/options/smt_options.toml
  src/smt/set_defaults.cpp
Labels: normal, simple

#11717 strings: Refactor to not use NodeManager::currentNM()
  src/preprocessing/passes/foreign_theory_rewrite.cpp
  src/rewriter/basic_rewrite_rcons.cpp
  src/theory/arith/arith_rewriter.cpp
  src/theory/quantifiers/extended_rewrite.cpp
  src/theory/strings/arith_entail.cpp
  src/theory/strings/arith_entail.h
  src/theory/strings/eager_solver.cpp
  src/theory/strings/eqc_info.cpp
  src/theory/strings/infer_proof_cons.cpp
  src/theory/strings/regexp_elim.cpp
  src/theory/strings/regexp_entail.cpp
  src/theory/strings/regexp_enumerator.cpp
  src/theory/strings/regexp_eval.cpp
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/strings_entail.cpp
  src/theory/strings/term_registry.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings_preprocess.cpp
  src/theory/strings/theory_strings_type_rules.cpp
  src/theory/strings/theory_strings_utils.cpp
  src/theory/strings/type_enumerator.cpp
  src/theory/strings/word.cpp
  test/unit/theory/sequences_rewriter_white.cpp
Labels: normal, moderate

#11729 Move bitblasting to its own file in Eunoia signature
  proofs/eo/cpc/programs/BitVectors.eo
  proofs/eo/cpc/programs/Bitblasting.eo
  proofs/eo/cpc/rules/BitVectors.eo
Labels: normal, simple

#11728 Add proof elaboration for BV concat extract rule
  src/theory/bv/macro_rewrite_elaborator.cpp
  src/theory/bv/macro_rewrite_elaborator.h
Labels: normal, moderate

#11565 Do not throw an assertion failure when arithmetic model construction fails and a lemma has been sent.
  src/theory/arith/theory_arith.cpp
Labels: major, simple

#11708 Use arith substitution context for case of congruence manager conflicts
  src/theory/arith/arith_subs.cpp
  src/theory/arith/arith_subs.h
  src/theory/arith/linear/congruence_manager.cpp
Labels: major, moderate

#11716 Bump CaDiCaL to version 2.1.3.
  INSTALL.rst
  NEWS.md
  cmake/FindCaDiCaL.cmake
  src/prop/cadical.cpp
Labels: normal, moderate

#11732 Add proof elaboration for MultSltMult BV rewrite
  src/theory/bv/macro_rewrite_elaborator.cpp
  src/theory/bv/macro_rewrite_elaborator.h
Labels: normal, moderate

#11735 Fix type rule for nested lambda, add regression
  src/expr/node_manager_template.cpp
  src/parser/parser_state.cpp
  src/theory/quantifiers/skolemize.cpp
  src/theory/uf/theory_uf_rewriter.cpp
  src/theory/uf/theory_uf_type_rules.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/ho/issue11734-nested-lambda.smt2
Labels: normal, simple

#11588 Refactor bound variable manager to use identifiers instead of attributes
  src/expr/CMakeLists.txt
  src/expr/bound_var_id.cpp
  src/expr/bound_var_id.h
  src/expr/bound_var_manager.cpp
  src/expr/bound_var_manager.h
  src/expr/elim_shadow_converter.cpp
  src/expr/internal_skolem_id.h
  src/smt/solver_engine.cpp
  src/theory/arith/operator_elim.cpp
  src/theory/arrays/skolem_cache.cpp
  src/theory/bags/bag_reduction.cpp
  src/theory/bags/inference_generator.cpp
  src/theory/quantifiers/quant_split.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/sygus/term_database_sygus.cpp
  src/theory/sets/set_reduction.cpp
  src/theory/strings/regexp_elim.cpp
  src/theory/strings/skolem_cache.cpp
  src/theory/strings/theory_strings.cpp
  src/theory/strings/theory_strings_utils.cpp
  src/theory/uf/function_const.cpp
Labels: major, moderate

#11741 Disable proof tester for regression.
  test/regress/cli/regress2/quantifiers/issue10805-syqi-no-arr-const.smt2
Labels: major, simple

#11738 Allow quoted symbols in indexed operators
  src/parser/smt2/smt2_term_parser.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/issue11763-quoted-dt-cons.smt2
Labels: normal, simple

#11739 Add more regressions from proof branch
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/bv/dd_fuzz26-hole.smt2
  test/regress/cli/regress0/proofs/dd_int_check_rec_elim_shadow.smt2
  test/regress/cli/regress0/strings/652-substr-len-norm.smt2
  test/regress/cli/regress0/strings/dd_rw_91.smt2
Labels: normal, simple

#11730 Add a static build option for the JNI library
  .github/actions/add-jar/action.yml
  .github/actions/add-package/action.yml
  .github/actions/configure-and-build/action.yml
  .github/workflows/ci.yml
  src/api/java/CMakeLists.txt
  src/api/java/io/github/cvc5/Utils.java
Labels: normal, moderate

#11745 Improve documentation of SatSolver interface.
  src/prop/sat_solver.h
Labels: normal, simple

#11746 cadical: Add more trace messages.
  src/prop/cadical.cpp
Labels: normal, simple

#11747 cadical: Add more stats.
  src/prop/cadical.cpp
Labels: normal, simple

#11676 Add macro elaboration for MACRO_BV_AND_OR_XOR_CONCAT_PULLUP
  src/theory/bv/macro_rewrite_elaborator.cpp
  src/theory/bv/macro_rewrite_elaborator.h
Labels: normal, moderate, work in progress

#11737 moved code that prints unproven conjectures to a separate function
  src/theory/quantifiers/conjecture_generator.cpp
  src/theory/quantifiers/conjecture_generator.h
Labels: normal, simple

#11754 Add bitblasting utils to Eunoia signature
  proofs/eo/cpc/programs/Bitblasting.eo
Labels: normal, moderate

#11755 Fix prenex quant norm
  proofs/eo/cpc/rules/Arith.eo
  src/theory/quantifiers/quantifiers_preprocess.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/quantifiers/issue11751-prenex-norm.smt2
  test/regress/cli/regress0/quantifiers/issue11752-prenex-norm.smt2
Labels: normal, simple

#11704 More minor changes to BV rewriter for proofs
  src/theory/bv/theory_bv_rewrite_rules_normalization.h
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
  src/theory/bv/theory_bv_rewriter.cpp
  src/theory/bv/theory_bv_utils.cpp
  src/theory/bv/theory_bv_utils.h
Labels: normal, simple

#11757 Include MinGW-w64 libraries in static JNI library
  .github/actions/add-jar/action.yml
  .github/actions/add-package/action.yml
  src/api/java/CMakeLists.txt
  src/api/java/io/github/cvc5/Utils.java
Labels: normal, moderate

#11759 Add bv (un)signed inequality to bitblasting signature
  proofs/eo/cpc/programs/Bitblasting.eo
Labels: normal, moderate

#11763 Add side conditions for bitblasting addition and bitwise operators
  proofs/eo/cpc/programs/Bitblasting.eo
Labels: normal, moderate

#11766 Treat higher-order equality as define-fun in non-incremental
  src/smt/assertions.cpp
Labels: normal, moderate

#11748 arith: Refactor to not use NodeManager::currentNM()
  src/theory/arith/arith_msum.cpp
  src/theory/arith/arith_poly_norm.cpp
  src/theory/arith/arith_subs.cpp
  src/theory/arith/arith_utilities.cpp
  src/theory/arith/arith_utilities.h
  src/theory/arith/linear/arith_static_learner.cpp
  src/theory/arith/linear/callbacks.cpp
  src/theory/arith/linear/callbacks.h
  src/theory/arith/linear/constraint.cpp
  src/theory/arith/linear/constraint.h
  src/theory/arith/linear/dio_solver.cpp
  src/theory/arith/linear/infer_bounds.cpp
  src/theory/arith/linear/linear_equality.cpp
  src/theory/arith/linear/linear_equality.h
  src/theory/arith/linear/normal_form.cpp
  src/theory/arith/linear/normal_form.h
  src/theory/arith/linear/simplex.cpp
  src/theory/arith/linear/soi_simplex.cpp
  src/theory/arith/linear/theory_arith_private.cpp
  src/theory/arith/nl/coverings/cdcac.cpp
  src/theory/arith/nl/ext/monomial.cpp
  src/theory/arith/nl/iand_utils.cpp
  src/theory/arith/nl/poly_conversion.cpp
  src/theory/arith/nl/transcendental/sine_solver.cpp
  src/theory/arith/rewriter/addition.cpp
  src/theory/arith/rewriter/node_utils.cpp
  src/theory/arith/rewriter/node_utils.h
  src/theory/arith/rewriter/rewrite_atom.cpp
  src/theory/arith/type_enumerator.h
Labels: normal, moderate
