Repository cvc5/cvc5, pull requests merged in 2025-04, with the labels that each got.

#11765 Add Eunoia side conditions for bitblasting multiplication
  proofs/eo/cpc/programs/Bitblasting.eo
Labels: normal, moderate

#11770 Add Eunoia definitions for bitblasting udiv/urem
  proofs/eo/cpc/programs/Bitblasting.eo
Labels: normal, moderate

#11753 [proofs] [alethe] Fix handling of Alethe skolem definitions
  src/proof/alethe/alethe_node_converter.cpp
  src/proof/alethe/alethe_node_converter.h
  src/proof/alethe/alethe_printer.cpp
Labels: normal, moderate

#11569 Add remaining RARE rewrites for strings
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/theory/strings/rewrites
Labels: normal, moderate

#11773 Add NodeManager pointer to SkolemManager
  src/expr/node_manager_template.cpp
  src/expr/skolem_manager.cpp
  src/expr/skolem_manager.h
Labels: normal, moderate

#11631 [proof log] Make sure we log lemmas from presolve()
  src/prop/prop_engine.cpp
  src/prop/prop_proof_manager.cpp
  src/prop/prop_proof_manager.h
Labels: normal, simple

#11777 expr: Refactor to not use NodeManager::currentNM()
  src/expr/aci_norm.cpp
  src/expr/bound_var_manager.cpp
  src/expr/bound_var_manager.h
  src/expr/dtype.cpp
  src/expr/dtype_cons.cpp
  src/expr/elim_shadow_converter.cpp
  src/expr/nary_match_trie.cpp
  src/expr/nary_term_util.cpp
  src/expr/node_algorithm.cpp
  src/expr/oracle_caller.cpp
  src/expr/sygus_datatype.cpp
  src/expr/sygus_datatype.h
  src/expr/sygus_grammar.cpp
  src/expr/term_canonize.cpp
  src/expr/term_context_node.cpp
Labels: normal, moderate

#11698 Add fine grained proof support for quantifiers variable eliminations
  src/rewriter/basic_rewrite_rcons.cpp
  src/theory/quantifiers/quantifiers_rewriter.cpp
  src/theory/quantifiers/quantifiers_rewriter.h
Labels: major, moderate

#11675 Add Eunoia definitions for BV multiplication overflow predicates
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/BitVectors.eo
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/proof/alf/alf_printer.cpp
  src/theory/bv/theory_bv_rewriter.cpp
Labels: normal, moderate

#11774 Add Eunoia bitblast signature for bvite, refactor constant
  proofs/eo/cpc/programs/Bitblasting.eo
  proofs/eo/cpc/rules/BitVectors.eo
Labels: normal, moderate

#11776 Minor changes and fixes to RARE rules
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/expert/rules/RewritesExpert.eo
  proofs/eo/cpc/rules/Rewrites.eo
  src/theory/arith/rewrites
  src/theory/arith/rewrites-transcendentals
  src/theory/strings/rewrites
  src/theory/strings/rewrites-regexp-membership
Labels: normal, moderate

#11780 preprocessing/printer/proof: Refactor to not use NodeManager::currentNM()
  src/preprocessing/util/boolean_simplification.h
  src/printer/let_binding.cpp
  src/printer/smt2/smt2_printer.cpp
  src/proof/proof_node.cpp
  src/proof/proof_node_manager.cpp
  src/proof/proof_node_manager.h
  src/proof/proof_step_buffer.cpp
  src/proof/resolution_proofs_util.cpp
  src/proof/theory_proof_step_buffer.cpp
  src/smt/proof_manager.cpp
Labels: normal, moderate

#11781 Pass NodeManager pointer to getNullTerminator
  src/expr/aci_norm.cpp
  src/expr/aci_norm.h
  src/expr/nary_term_util.cpp
  src/proof/lfsc/lfsc_list_sc_node_converter.cpp
  src/proof/lfsc/lfsc_node_converter.cpp
  src/proof/lfsc/lfsc_node_converter.h
  src/proof/lfsc/lfsc_post_processor.cpp
  src/proof/lfsc/lfsc_printer.cpp
  src/rewriter/rewrite_proof_rule.cpp
Labels: major, moderate

#11779 Miscellaneous changes to string rewriter
  src/theory/strings/arith_entail.cpp
  src/theory/strings/sequences_rewriter.cpp
  src/theory/strings/theory_strings.cpp
Labels: normal, simple

#11641 Extend evaluator for applications of symbolic indexed operators
  src/proof/alf/alf_printer.cpp
  src/theory/builtin/theory_builtin_rewriter.h
  src/theory/evaluator.cpp
Labels: normal, simple

#11788 Add Eunoia signature for (forthcoming) rule exists string length
  proofs/eo/cpc/rules/Strings.eo
  proofs/eo/cpc/theories/Strings.eo
Labels: minor, moderate

#11536 Infrastructure and proof rules involving witness terms
  src/expr/bound_var_id.cpp
  src/expr/bound_var_id.h
  src/proof/valid_witness_proof_generator.cpp
  src/proof/valid_witness_proof_generator.h
Labels: normal, moderate

#11722 Refactor and minor improvements to MBQI
  src/theory/inference_id.cpp
  src/theory/inference_id.h
  src/theory/quantifiers/inst_strategy_mbqi.cpp
  src/theory/quantifiers/inst_strategy_mbqi.h
  src/theory/quantifiers/mbqi_enum.cpp
Labels: normal, moderate

#11761 More updates to safe options
  src/options/arith_options.toml
  src/options/base_options.toml
  src/options/proof_options.toml
  src/options/quantifiers_options.toml
  src/options/theory_options.toml
Labels: normal, simple

#11794 Add two rewrites to the string rewriter
  src/theory/strings/rewrites.cpp
  src/theory/strings/rewrites.h
  src/theory/strings/sequences_rewriter.cpp
Labels: normal, moderate

#11791 Minor fix and addition to theory rewrite reconstruction
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
Labels: normal, simple

#11784 Ensure BV inequality mode is uniformly handled in CEGQI
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.cpp
  src/theory/quantifiers/cegqi/ceg_bv_instantiator.h
Labels: minor, simple

#11786 Add Eunoia signature for (forthcoming) proof rule for invertibility conditions
  proofs/eo/cpc/rules/Quantifiers.eo
  proofs/eo/cpc/theories/Quantifiers.eo
Labels: minor, moderate

#11793 Add more proof regressions, focused on RARE coverage
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arith/arith-missing-dsl-rew.smt2
  test/regress/cli/regress0/bv/bv-missing-dsl-rew.smt2
  test/regress/cli/regress0/bv/dd_check_bvugt_bvneg.smt2
  test/regress/cli/regress0/nl/nta/nta-dsl-rew.smt2
  test/regress/cli/regress0/seq/seq-eval-bug.smt2
  test/regress/cli/regress0/sets/sets-dsl-rew.smt2
  test/regress/cli/regress0/strings/concat-emp-dsl-rew.smt2
  test/regress/cli/regress0/strings/concat-none-dsl-rew.smt2
  test/regress/cli/regress0/strings/dd_str_term_208.smt2
  test/regress/cli/regress0/strings/dd_str_term_529.smt2
  test/regress/cli/regress0/strings/digit-mem-dsl-rew.smt2
  test/regress/cli/regress0/strings/re-inter-all.smt2
  test/regress/cli/regress0/strings/str-dsl-missing-rew.smt2
Labels: normal, moderate

#11798 Fix use of EVALUATE in proof elaboration
  src/rewriter/basic_rewrite_rcons.cpp
Labels: major, simple

#11804 [proofs] [alethe] Support symbolic indexed operators
  src/proof/alethe/alethe_node_converter.cpp
  test/regress/cli/regress0/nl/pow2-native-0.smt2
  test/regress/cli/regress0/nl/pow2-native-2.smt2
  test/regress/cli/regress0/nl/pow2-native-3.smt2
  test/regress/cli/regress0/nl/pow2-pow.smt2
  test/regress/cli/regress2/bv_to_int_ashr.smt2
  test/regress/cli/regress2/bv_to_int_bitwise.smt2
Labels: normal, simple

#11787 Fix a few missing cases of EVALUATE and ABSORB
  proofs/eo/cpc/Cpc.eo
  src/expr/aci_norm.cpp
  src/proof/alf/alf_printer.cpp
  src/rewriter/rewrite_db_proof_cons.cpp
  src/theory/evaluator.cpp
Labels: normal, simple

#11803 Use standard Eunoia list in CPC utils
  contrib/get-ethos-checker
  proofs/eo/cpc/programs/Utils.eo
Labels: minor, simple

#11802 fp_word_blaster: Refactor to not use NodeManager::currentNM()
  src/theory/fp/fp_word_blaster.cpp
  src/theory/fp/fp_word_blaster.h
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp_rewriter.cpp
Labels: normal, moderate

#11799 type_properties: Refactor to not use NodeManager::currentNM()
  src/expr/type_properties_template.cpp
  src/expr/type_properties_template.h
  src/theory/arith/kinds
  src/theory/booleans/kinds
  src/theory/fp/kinds
  src/theory/strings/kinds
Labels: normal, simple

#11805 theory: Eliminate calls to NodeManager::currentNM()
  src/theory/arrays/theory_arrays_type_rules.cpp
  src/theory/arrays/type_enumerator.cpp
  src/theory/booleans/type_enumerator.h
  src/theory/builtin/generic_op.cpp
  src/theory/builtin/proof_checker.cpp
  src/theory/builtin/theory_builtin_type_rules.cpp
  src/theory/builtin/type_enumerator.cpp
  src/theory/bv/type_enumerator.h
  src/theory/evaluator.cpp
  src/theory/ff/parse.cpp
  src/theory/ff/type_enumerator.h
  src/theory/fp/type_enumerator.h
  src/theory/inference_id.cpp
  src/theory/valuation.cpp
Labels: normal, simple

#11806 smt: Refactor to not use NodeManager::currentNM()
  src/api/cpp/cvc5.cpp
  src/smt/abduction_solver.cpp
  src/smt/difficulty_post_processor.cpp
  src/smt/difficulty_post_processor.h
  src/smt/interpolation_solver.cpp
  src/smt/proof_manager.cpp
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  src/theory/quantifiers/cegqi/nested_qe.cpp
  src/theory/quantifiers/expr_miner.cpp
  src/theory/quantifiers/inst_strategy_mbqi.cpp
  src/theory/quantifiers/inst_strategy_sub_conflict.cpp
  src/theory/quantifiers/sygus/sygus_interpol.cpp
  src/theory/quantifiers/sygus/sygus_repair_const.cpp
  src/theory/smt_engine_subsolver.cpp
  src/theory/smt_engine_subsolver.h
  test/unit/node/node_black.cpp
  test/unit/node/type_node_white.cpp
  test/unit/test_smt.h
Labels: normal, moderate

#11236 [proofs] [alethe] Generalize ALPHA_EQUIV translation
  src/proof/alethe/alethe_post_processor.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/proofs/alpha-eq-var-shadow-name-only.smt2
  test/regress/cli/regress1/proofs/alpha-eq-var-shadow-name-only2.smt2
Labels: normal, moderate

#11764 Refactor arithmetic rewriter for ADD
  src/theory/arith/arith_rewriter.cpp
  src/theory/arith/rewriter/addition.cpp
  src/theory/arith/rewriter/addition.h
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/arith/issue9126-nb-alloc.smt2
Labels: normal, moderate

#11807 Clean up uses of quantifiers TermUtil
  src/expr/node_algorithm.cpp
  src/expr/node_algorithm.h
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/cegqi/inst_strategy_cegqi.cpp
  src/theory/quantifiers/ematching/pattern_term_selector.cpp
  src/theory/quantifiers/ematching/pattern_term_selector.h
  src/theory/quantifiers/term_util.cpp
  src/theory/quantifiers/term_util.h
  src/theory/sep/theory_sep.cpp
Labels: minor, simple

#11813 Remove obsolete fixmes.
  src/context/cdhashmap.h
  src/expr/node_manager_template.cpp
  src/expr/node_value.h
Labels: normal, simple

#11815 Add missing check in oracle checker.
  src/theory/quantifiers/oracle_checker.cpp
Labels: normal, simple

#11814 api: Add missing/refactor API checks.
  src/api/cpp/cvc5.cpp
  src/api/cpp/cvc5_checks.h
Labels: normal, simple

#11816 NodeManager as a static thread_local singleton is no more.
  examples/api/python/parser.py
  examples/api/python/sygus-fun.py
  include/cvc5/cvc5.h
  src/api/cpp/cvc5.cpp
  src/expr/node_manager_template.cpp
  src/expr/node_manager_template.h
  test/api/python/sep_log_api.py
  test/unit/api/c/capi_solver_black.cpp
  test/unit/api/c/capi_symbol_manager_black.cpp
  test/unit/api/c/capi_term_manager_black.cpp
  test/unit/api/cpp/api_solver_black.cpp
  test/unit/api/cpp/api_term_manager_black.cpp
  test/unit/api/java/InputParserTest.java
  test/unit/api/java/SolverTest.java
  test/unit/api/java/TermManagerTest.java
  test/unit/api/python/test_input_parser.py
  test/unit/api/python/test_solver.py
  test/unit/api/python/test_term_manager.py
  test/unit/node/attrhash_white.cpp
  test/unit/node/node_algorithms_black.cpp
  test/unit/node/node_black.cpp
  test/unit/node/node_builder_black.cpp
  test/unit/node/node_manager_white.cpp
  test/unit/node/node_type_rules.cpp
  test/unit/node/node_white.cpp
  test/unit/node/type_node_white.cpp
  test/unit/preprocessing/pass_bv_gauss_white.cpp
  test/unit/test_env.h
  test/unit/test_node.h
  test/unit/test_smt.h
  test/unit/theory/regexp_operation_black.cpp
  test/unit/theory/sequences_rewriter_white.cpp
  test/unit/theory/theory_arith_coverings_white.cpp
  test/unit/theory/theory_bags_normal_form_white.cpp
  test/unit/theory/theory_bags_rewriter_white.cpp
  test/unit/theory/theory_bags_type_rules_white.cpp
  test/unit/theory/theory_quantifiers_bv_instantiator_white.cpp
  test/unit/theory/theory_quantifiers_bv_inverter_white.cpp
  test/unit/theory/theory_sets_rewriter_white.cpp
  test/unit/theory/theory_strings_skolem_cache_black.cpp
  test/unit/util/boolean_simplification_black.cpp
Labels: normal, simple, moderate

#11818 Fix declarePool test in api_solver_black
  test/unit/api/cpp/api_solver_black.cpp
Labels: major, simple

#11453 Add arithmetic lemma proof reconstruction utility
  src/CMakeLists.txt
  src/theory/arith/arith_proof_rcons.cpp
  src/theory/arith/arith_proof_rcons.h
  src/theory/arith/linear/theory_arith_private.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/dd_textbook-sumeven-arith-rcons.smt2
Labels: major, moderate

#11808 Update Eunoia/CPC to new interface for declare-parameterized-const
  contrib/get-ethos-checker
  proofs/eo/cpc/expert/theories/FiniteFields.eo
  proofs/eo/cpc/programs/Bitblasting.eo
  proofs/eo/cpc/rules/Strings.eo
  proofs/eo/cpc/theories/BitVectors.eo
  proofs/eo/cpc/theories/Strings.eo
Labels: normal, simple

#11589 Eliminate singleton_elim from heads of RARE rules
  proofs/eo/cpc/rules/Rewrites.eo
  src/proof/alf/alf_list_node_converter.cpp
  src/proof/alf/alf_list_node_converter.h
  src/proof/alf/alf_printer.cpp
Labels: normal, simple

#11822 Fix evaluator for BV repeat
  src/theory/evaluator.cpp
Labels: major, simple

#11792 Remove 100 unecessary RARE rules
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/theory/arith/rewrites
  src/theory/booleans/rewrites
  src/theory/bv/rewrites
  src/theory/bv/rewrites-simplification
  src/theory/strings/rewrites
  src/theory/strings/rewrites-regexp-membership
Labels: major, moderate

#11820 Do subproof merging when all processing RARE rewrites
  src/proof/proof_node_updater.cpp
  src/proof/proof_node_updater.h
  src/smt/proof_post_processor_dsl.cpp
  src/smt/proof_post_processor_dsl.h
Labels: normal, moderate

#11769 Add utilities for reconstructing MACRO_QUANT_VAR_ELIM_INEQ
  src/rewriter/basic_rewrite_rcons.cpp
  src/rewriter/basic_rewrite_rcons.h
Labels: major, moderate

#11825 Add proof rule EXISTS_STRING_LENGTH
  include/cvc5/cvc5_proof_rule.h
  src/api/cpp/cvc5_proof_rule_template.cpp
  src/proof/alf/alf_printer.cpp
  src/proof/valid_witness_proof_generator.cpp
  src/theory/strings/theory_strings_utils.cpp
Labels: normal, moderate

#11817 Catch all mixed arithmetic cases with --strict-parsing
  src/expr/subtype_elim_node_converter.cpp
  src/parser/smt2/smt2_state.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/strict-parsing-mixed-arith-1.smt2
  test/regress/cli/regress0/parser/strict-parsing-mixed-arith-2.smt2
  test/regress/cli/regress0/parser/strict-parsing-mixed-arith-3.smt2
  test/regress/cli/regress0/parser/strict-parsing-mixed-arith-3b.smt2
Labels: normal, simple

#11812 Fix label of trust step when proof-mode=pp-only
  src/proof/trust_id.cpp
  src/proof/trust_id.h
  src/smt/solver_engine.cpp
Labels: minor, simple

#11823 Modifications to RARE rules to avoid singleton elim
  proofs/eo/cpc/rules/Rewrites.eo
  src/theory/arith/rewrites
  src/theory/booleans/rewrites
  src/theory/bv/rewrites
  src/theory/strings/rewrites
Labels: normal, simple

#11836 Export ParserEndOfFileException class
  include/cvc5/cvc5_parser.h
  test/binary/CMakeLists.txt
Labels: normal, simple

#11832 Fix proof checking failure in lambda lifting
  src/theory/uf/lambda_lift.cpp
Labels: normal, simple

#11838 java: Fix cast of TermManager pointer in addPlugin
  src/api/java/jni/api_plugin.cpp
  src/api/java/jni/api_plugin.h
  src/api/java/jni/solver.cpp
Labels: minor, simple

#11835 Use proof rule EXISTS_STRING_LENGTH in cex-guided instantiation
  src/expr/elim_witness_converter.cpp
  src/expr/elim_witness_converter.h
  src/proof/alf/alf_node_converter.cpp
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
Labels: normal, simple

#11829 Optimizations for RARE reconstruction
  src/rewriter/rewrite_db_proof_cons.cpp
  src/rewriter/rewrite_db_proof_cons.h
Labels: normal, moderate

#11839 java: Enhance concurrency by tracking global refs per solver instance
  src/api/java/CMakeLists.txt
  src/api/java/jni/api_solver.cpp
  src/api/java/jni/api_solver.h
  src/api/java/jni/api_utilities.cpp
  src/api/java/jni/api_utilities.h
  src/api/java/jni/solver.cpp
  src/api/java/jni/term_manager.cpp
Labels: normal, moderate

#11811 Update CPC/Eunoia to use declare-parameterized-const instead of :var annotation
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/expert/CpcExpert.eo
  proofs/eo/cpc/expert/theories/ArithExt.eo
  proofs/eo/cpc/expert/theories/Bags.eo
  proofs/eo/cpc/expert/theories/FiniteFields.eo
  proofs/eo/cpc/expert/theories/FloatingPoints.eo
  proofs/eo/cpc/expert/theories/SepLogic.eo
  proofs/eo/cpc/expert/theories/SetsExt.eo
  proofs/eo/cpc/programs/PolyNorm.eo
  proofs/eo/cpc/programs/Utils.eo
  proofs/eo/cpc/theories/Arith.eo
  proofs/eo/cpc/theories/ArithBvConv.eo
  proofs/eo/cpc/theories/Arrays.eo
  proofs/eo/cpc/theories/BitVectors.eo
  proofs/eo/cpc/theories/Builtin.eo
  proofs/eo/cpc/theories/Datatypes.eo
  proofs/eo/cpc/theories/Quantifiers.eo
  proofs/eo/cpc/theories/Reals.eo
  proofs/eo/cpc/theories/Sets.eo
  proofs/eo/cpc/theories/Strings.eo
Labels: major, moderate

#11840 Remove spurious handling of witness in model values
  src/theory/quantifiers/cegqi/ceg_instantiator.cpp
  src/theory/quantifiers/proof_checker.cpp
Labels: major, simple

#11853 Fix corner case of block models
  src/smt/model_blocker.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress1/proj-issue764-block-model.smt2
Labels: normal, simple
