Repository cvc5/cvc5, pull requests merged in 2025-05, with the labels that each got.

#11866 Use macro NNF prior to RARE DSL reconstruction
  src/theory/booleans/theory_bool_rewriter.cpp
Labels: normal, simple

#11870 Remove two unecessary RARE rules for arith+ITE lifting
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/theory/arith/rewrites
Labels: normal, simple

#11869 Add CI for safe-mode builds
  .github/workflows/ci.yml
  CMakeLists.txt
  cmake/cvc5Config.cmake.in
  examples/api/cpp/CMakeLists.txt
  examples/api/java/CMakeLists.txt
  examples/api/python/CMakeLists.txt
  src/base/configuration.cpp
  src/base/configuration.h
  src/base/configuration_private.h
  src/options/options_handler.cpp
  src/options/proof_options.toml
  src/options/smt_options.toml
  src/smt/logic_exception.h
  src/smt/smt_solver.cpp
  src/smt/solver_engine.cpp
  src/theory/arith/theory_arith.cpp
  src/theory/datatypes/theory_datatypes.cpp
  src/theory/ff/theory_ff.cpp
  src/theory/fp/theory_fp.cpp
  src/theory/fp/theory_fp_utils.cpp
  src/theory/sep/theory_sep.cpp
  src/theory/sets/theory_sets_private.cpp
  src/theory/theory_rewriter.cpp
  src/theory/uf/theory_uf.cpp
  test/api/c/CMakeLists.txt
  test/api/cpp/CMakeLists.txt
  test/api/cpp/issues/CMakeLists.txt
  test/api/python/CMakeLists.txt
  test/regress/cli/regress0/options/safe-options-fatal.smt2
  test/regress/cli/regress0/options/safe-options1.smt2
  test/regress/cli/regress0/options/safe-options2.smt2
  test/regress/cli/regress0/options/safe-opts-warn.smt2
  test/regress/cli/regress1/proj-issue476-theoryOf-no-uf.smt2
  test/regress/cli/run_regression.py
Labels: major, moderate

#11863 Make proof granularity DSL_REWRITE by default, if proofs are enabled
  src/smt/set_defaults.cpp
  test/regress/cli/regress0/printer/print_trusted_proof_steps.smt2
Labels: normal, simple

#11855 ci: Update cibuildwheel to v2.23.3
  .github/workflows/package_pypi.yml
Labels: minor, simple

#11884 Use Cython < 3.1.0 with PyPy < 3.9
  src/api/python/pyproject.toml
Labels: major, simple

#11885 Restore patch for cross-compiling Libpoly
  cmake/FindPoly.cmake
  cmake/deps-utils/Poly-windows-patch.sh
Labels: major, moderate

#11887 Remove obsolete Python requirements files
  contrib/requirements_build.txt
  contrib/requirements_python_dev.txt
Labels: minor, simple

#11882 Reuse the single-query smtcomp script for unsat-cores and model-validation
  contrib/competitions/smt-comp/run-script-smtcomp-current-model-validation
  contrib/competitions/smt-comp/run-script-smtcomp-current-unsat-cores
Labels: normal, simple

#11860 Fixing types in CPC signature based on new Eunoia type system
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/programs/Bitblasting.eo
  proofs/eo/cpc/programs/Datatypes.eo
  proofs/eo/cpc/programs/SeqToString.eo
  proofs/eo/cpc/programs/Strings.eo
  proofs/eo/cpc/programs/Utils.eo
  proofs/eo/cpc/rules/Arith.eo
  proofs/eo/cpc/rules/ArithBvConv.eo
  proofs/eo/cpc/rules/BitVectors.eo
  proofs/eo/cpc/rules/Datatypes.eo
  proofs/eo/cpc/rules/Quantifiers.eo
  proofs/eo/cpc/rules/Strings.eo
  proofs/eo/cpc/theories/Quantifiers.eo
Labels: normal, simple

#11875 Fix model construction for parameteric datatypes + u sorts + FMF
  src/expr/dtype.cpp
  src/theory/theory_model_builder.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/fmf/proj-issue622-fmf-dt-u-orig.smt2
  test/regress/cli/regress0/fmf/proj-issue622-fmf-dt-u.smt2
Labels: major, simple

#11845 Properly handle ambiguous constants in CPC
  contrib/get-ethos-checker
  proofs/eo/cpc/expert/CpcExpert.eo
  proofs/eo/cpc/expert/rules/ArraysExt.eo
  proofs/eo/cpc/expert/rules/RewritesExpert.eo
  proofs/eo/cpc/expert/theories/ArraysExt.eo
  proofs/eo/cpc/expert/theories/Bags.eo
  proofs/eo/cpc/expert/theories/SepLogic.eo
  proofs/eo/cpc/expert/theories/SetsExt.eo
  proofs/eo/cpc/programs/DistinctValues.eo
  proofs/eo/cpc/programs/SeqToString.eo
  proofs/eo/cpc/programs/Strings.eo
  proofs/eo/cpc/rules/Arrays.eo
  proofs/eo/cpc/rules/Rewrites.eo
  proofs/eo/cpc/rules/Strings.eo
  proofs/eo/cpc/theories/Arrays.eo
  proofs/eo/cpc/theories/Sets.eo
  proofs/eo/cpc/theories/Strings.eo
  src/proof/alf/alf_list_node_converter.cpp
  src/proof/alf/alf_node_converter.cpp
Labels: normal, simple

#11837 Add "no_support" field in options toml, generalize safe options
  NEWS.md
  configure.sh
  include/cvc5/c/cvc5.h
  include/cvc5/cvc5.h
  src/api/c/cvc5.cpp
  src/api/cpp/cvc5.cpp
  src/options/arith_options.toml
  src/options/base_options.toml
  src/options/bv_options.toml
  src/options/mkoptions.py
  src/options/option_exception.h
  src/options/options_public.h
  src/options/options_public_template.cpp
  src/options/options_template.cpp
  src/options/quantifiers_options.toml
  src/options/smt_options.toml
  src/options/uf_options.toml
  src/smt/set_defaults.cpp
  src/smt/solver_engine.cpp
  src/smt/solver_engine.h
  test/api/cpp/issues/CMakeLists.txt
  test/regress/cli/regress0/ff/proj-issue748-safe.smt2
  test/regress/cli/regress0/fp/proj-issue744-safe.smt2
  test/regress/cli/regress0/fp/proj-issue745-safe.smt2
  test/regress/cli/regress0/fp/proj-issue746-safe.smt2
  test/regress/cli/regress0/options/safe-options-fatal.smt2
  test/regress/cli/regress0/options/safe-options1.smt2
  test/regress/cli/regress0/options/safe-options2.smt2
  test/regress/cli/regress0/options/safe-options3.smt2
  test/regress/cli/regress0/options/safe-opts-warn.smt2
  test/regress/cli/regress1/nl/nra-cad-performance.smt2
  test/unit/options/options_black.cpp
Labels: major, moderate

#11888 Bump version of googletest if not installed in system.
  cmake/FindGTest.cmake
Labels: normal, simple

#11878 Improve model construction for uninterpreted sorts + FMF
  src/theory/theory_model_builder.cpp
Labels: minor, moderate

#11873 Use generic FLATTEN tactic in RARE reconstruction, remove 5 RARE rules
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/rewriter/rewrite_db_proof_cons.cpp
  src/rewriter/rewrite_db_proof_cons.h
  src/rewriter/rewrite_proof_status.cpp
  src/rewriter/rewrite_proof_status.h
  src/theory/arith/arith_poly_norm.cpp
  src/theory/arith/arith_poly_norm.h
  src/theory/arith/rewrites
  src/theory/booleans/rewrites
  src/theory/bv/rewrites
  src/theory/strings/sequences_rewriter.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/proofs/big-rec-len.smt2
  test/regress/cli/regress0/proofs/big-ss-len-include.smt2
  test/regress/cli/regress0/strings/long-easy-clash.smt2
Labels: normal, moderate

#11721 Fix round robin branching in arithmetic
  src/theory/arith/linear/theory_arith_private.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arith/dd-10890-round-robin.smt2
Labels: normal, moderate

#11883 Print parenthesis around proofs in any format
  NEWS.md
  src/smt/solver_engine.cpp
  test/regress/cli/run_regression.py
Labels: major, simple

#11898 Fix issue with ee-mode central with arrays
  src/theory/theory.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/arrays/issue11889-eec-unsat.smt2
Labels: major, simple

#11844 Remove dead code from BV rewriter, remove 10 BV RARE rules
  include/cvc5/cvc5_proof_rule.h
  proofs/eo/cpc/rules/Rewrites.eo
  src/theory/bv/rewrites
  src/theory/bv/rewrites-elimination
  src/theory/bv/rewrites-simplification
  src/theory/bv/theory_bv_rewrite_rules.h
  src/theory/bv/theory_bv_rewrite_rules_normalization.h
  src/theory/bv/theory_bv_rewrite_rules_operator_elimination.h
  src/theory/bv/theory_bv_rewrite_rules_simplification.h
Labels: normal, moderate

#11895 Update set defaults to ensure proofs do not impact safe mode builds
  src/smt/set_defaults.cpp
Labels: normal, simple

#11900 cmake: Ensure the Python API is built when build-tests is invoked
  test/api/python/CMakeLists.txt
Labels: normal, simple

#11399 Add infrastructure to translate THEORY_LEMMAS that have a ProofRewriteRule + two distinct rules
  src/proof/alethe/alethe_post_processor.cpp
  src/proof/alethe/alethe_post_processor.h
Labels: normal, simple

#11821 Improvements to the proof post-processor
  src/smt/proof_post_processor.cpp
  src/smt/proof_post_processor.h
Labels: normal, moderate

#11857 Add Alethe translation of ENCODE_EQ_INTRO
  src/proof/alethe/alethe_post_processor.cpp
Labels: normal, simple

#11899 Update proof checker scripts
  contrib/get-carcara-checker
  contrib/get-ethos-checker
  contrib/get-lfsc-checker
Labels: major, simple

#11868 Parse empty patterns
  src/parser/smt2/smt2_term_parser.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/parser/empty-pat.smt2
Labels: normal, simple

#11856 Print theory id name for theory trust rewrites
  src/proof/alethe/alethe_post_processor.cpp
Labels: normal, simple

#11849 Translation of QUANT_UNUSED_VARS to Alethe
  src/proof/alethe/alethe_post_processor.cpp
Labels: normal, simple

#11905 Catch type errors for nullary relations in join
  src/theory/sets/theory_sets_type_rules.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/rels/issue11903-join-unit-tuple.smt2
Labels: normal, simple

#11907 [proofs] [alethe] Generalize legal type checking in Alethe backend
  src/proof/alethe/alethe_node_converter.cpp
Labels: normal, simple

#11880 Remove DSL proof tester
  NEWS.md
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/ff/tlimit_per.smt2
  test/regress/cli/regress0/fp/rti_3_5_bug.smt2
  test/regress/cli/regress0/fp/word-blast.smt2
  test/regress/cli/regress1/bv/divtest.smt2
  test/regress/cli/regress1/quantifiers/bug802.smt2
  test/regress/cli/regress1/quantifiers/eqrange_ex_1.smt2
  test/regress/cli/regress1/quantifiers/qcft-smtlib3dbc51.smt2
  test/regress/cli/regress1/quantifiers/smtlibe99bbe.smt2
  test/regress/cli/run_regression.py
Labels: normal, simple

#11881 Add `--check-proofs-complete` option
  .github/workflows/ci.yml
  src/options/proof_options.toml
  src/proof/proof_node_updater.cpp
  src/proof/proof_node_updater.h
  src/smt/proof_final_callback.cpp
  src/smt/proof_final_callback.h
  src/smt/set_defaults.cpp
  src/theory/bv/proof_checker.cpp
  test/regress/cli/run_regression.py
Labels: normal, moderate

#11904 cmake: Enforce C17 for building GMP.
  cmake/FindGMP.cmake
Labels: normal, simple

#11910 cmake: Use C99 for GMP compilation.
  cmake/FindGMP.cmake
Labels: major, simple

#11915 Update portfolio to support get-model and get-unsat-core
  src/main/portfolio_driver.cpp
  src/main/portfolio_driver.h
Labels: major, moderate

#11918 Print portfolio config string even when strategy is a single config
  src/main/portfolio_driver.cpp
Labels: normal, moderate

#11892 Update CPC to use eo::eq instead of eo::is_eq when applicable
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/expert/CpcExpert.eo
  proofs/eo/cpc/programs/AciNorm.eo
  proofs/eo/cpc/programs/Arith.eo
  proofs/eo/cpc/programs/BitVectors.eo
  proofs/eo/cpc/programs/Datatypes.eo
  proofs/eo/cpc/programs/DistinctValues.eo
  proofs/eo/cpc/programs/Nary.eo
  proofs/eo/cpc/programs/PolyNorm.eo
  proofs/eo/cpc/programs/Quantifiers.eo
  proofs/eo/cpc/programs/Strings.eo
  proofs/eo/cpc/programs/Utils.eo
  proofs/eo/cpc/rules/Arith.eo
  proofs/eo/cpc/rules/BitVectors.eo
  proofs/eo/cpc/rules/Booleans.eo
  proofs/eo/cpc/rules/Datatypes.eo
  proofs/eo/cpc/rules/Quantifiers.eo
  proofs/eo/cpc/rules/Sets.eo
  proofs/eo/cpc/rules/Strings.eo
  proofs/eo/cpc/theories/Strings.eo
Labels: normal, simple

#11874 Eliminate term attributes from the CPC signature
  proofs/eo/cpc/expert/theories/Bags.eo
  proofs/eo/cpc/expert/theories/SetsExt.eo
  proofs/eo/cpc/expert/theories/Transcendentals.eo
  proofs/eo/cpc/theories/Arith.eo
  proofs/eo/cpc/theories/Arrays.eo
  proofs/eo/cpc/theories/Builtin.eo
  proofs/eo/cpc/theories/Reals.eo
  proofs/eo/cpc/theories/Sets.eo
  proofs/eo/cpc/theories/Strings.eo
Labels: major, moderate

#11919 Add `--help-option-categories`
  src/main/driver_unified.cpp
  src/main/options.h
  src/main/options_template.cpp
  src/options/main_options.toml
  src/options/mkoptions.py
Labels: normal, moderate

#11920 More updates to options categories
  src/options/mkoptions.py
  src/options/quantifiers_options.toml
  src/options/smt_options.toml
  src/options/strings_options.toml
Labels: normal, simple

#11897 Refactor distinct values program for datatypes and definition of DT_CONS_EQ_CLASH
  proofs/eo/cpc/programs/DistinctValues.eo
  proofs/eo/cpc/rules/Datatypes.eo
Labels: normal, moderate

#11927 Disable another timeout regression
  test/regress/cli/regress0/fp/word-blast.smt2
  test/regress/cli/regress1/quantifiers/bug802.smt2
Labels: major, simple

#11896 Refactor arithmetic signature to simplify types for Eunoia programs
  proofs/eo/cpc/rules/Arith.eo
Labels: normal, moderate

#11930 Do not evaluate semi-evaluated operators applied to unevaluated terms
  src/theory/theory_model.cpp
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/seq/issue11924-semi-eval-unk.smt2
Labels: normal, moderate

#11894 More type fixes for CPC signature
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/expert/theories/SetsExt.eo
  proofs/eo/cpc/programs/AciNorm.eo
  proofs/eo/cpc/programs/Arith.eo
  proofs/eo/cpc/programs/BitVectors.eo
  proofs/eo/cpc/programs/Bitblasting.eo
  proofs/eo/cpc/programs/Nary.eo
  proofs/eo/cpc/programs/PolyNorm.eo
  proofs/eo/cpc/programs/Quantifiers.eo
  proofs/eo/cpc/programs/SeqToString.eo
  proofs/eo/cpc/programs/Strings.eo
  proofs/eo/cpc/programs/Utils.eo
  proofs/eo/cpc/rules/ArithBvConv.eo
  proofs/eo/cpc/rules/BitVectors.eo
  proofs/eo/cpc/rules/Datatypes.eo
  proofs/eo/cpc/rules/Quantifiers.eo
  proofs/eo/cpc/rules/Strings.eo
  proofs/eo/cpc/theories/Arith.eo
  proofs/eo/cpc/theories/BitVectors.eo
  proofs/eo/cpc/theories/Reals.eo
  proofs/eo/cpc/theories/Strings.eo
Labels: major, moderate

#11938 Update usages of eo::nil to new syntax
  contrib/get-ethos-checker
  proofs/eo/cpc/programs/AciNorm.eo
  proofs/eo/cpc/programs/BitVectors.eo
  proofs/eo/cpc/programs/Nary.eo
  proofs/eo/cpc/programs/Utils.eo
  proofs/eo/cpc/rules/BitVectors.eo
Labels: major, simple

#11914 Update CPC signature to use new list primitives
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/expert/CpcExpert.eo
  proofs/eo/cpc/expert/theories/SetsExt.eo
  proofs/eo/cpc/programs/AciNorm.eo
  proofs/eo/cpc/programs/Bitblasting.eo
  proofs/eo/cpc/programs/Nary.eo
  proofs/eo/cpc/programs/Strings.eo
  proofs/eo/cpc/rules/BitVectors.eo
  proofs/eo/cpc/rules/Booleans.eo
  proofs/eo/cpc/rules/Quantifiers.eo
  proofs/eo/cpc/rules/Sets.eo
  proofs/eo/cpc/rules/Strings.eo
  proofs/eo/cpc/rules/Uf.eo
  test/regress/cli/CMakeLists.txt
  test/regress/cli/regress0/sets/set-eval-dup.smt2
Labels: major, moderate

#11946 Annotate signatures of programs in CPC using :signature
  contrib/get-ethos-checker
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/expert/theories/SetsExt.eo
  proofs/eo/cpc/programs/AciNorm.eo
  proofs/eo/cpc/programs/Arith.eo
  proofs/eo/cpc/programs/BitVectors.eo
  proofs/eo/cpc/programs/Bitblasting.eo
  proofs/eo/cpc/programs/Datatypes.eo
  proofs/eo/cpc/programs/DistinctValues.eo
  proofs/eo/cpc/programs/Nary.eo
  proofs/eo/cpc/programs/PolyNorm.eo
  proofs/eo/cpc/programs/Quantifiers.eo
  proofs/eo/cpc/programs/SeqToString.eo
  proofs/eo/cpc/programs/Strings.eo
  proofs/eo/cpc/programs/Utils.eo
  proofs/eo/cpc/rules/Arith.eo
  proofs/eo/cpc/rules/ArithBvConv.eo
  proofs/eo/cpc/rules/BitVectors.eo
  proofs/eo/cpc/rules/Booleans.eo
  proofs/eo/cpc/rules/Builtin.eo
  proofs/eo/cpc/rules/Datatypes.eo
  proofs/eo/cpc/rules/Quantifiers.eo
  proofs/eo/cpc/rules/Sets.eo
  proofs/eo/cpc/rules/Strings.eo
  proofs/eo/cpc/rules/Uf.eo
  proofs/eo/cpc/theories/Arith.eo
  proofs/eo/cpc/theories/Builtin.eo
  proofs/eo/cpc/theories/Datatypes.eo
  proofs/eo/cpc/theories/Quantifiers.eo
Labels: normal, simple

#11943 Refactor CPC Booleans and UF to avoid eo::match
  proofs/eo/cpc/rules/Booleans.eo
  proofs/eo/cpc/rules/Uf.eo
Labels: normal, moderate

#11944 Refactor CPC utilities to avoid programs that cannot be type checked
  proofs/eo/cpc/Cpc.eo
  proofs/eo/cpc/programs/Nary.eo
  proofs/eo/cpc/programs/Utils.eo
  proofs/eo/cpc/rules/Uf.eo
  proofs/eo/cpc/theories/Quantifiers.eo
Labels: normal, moderate

#11945 Refactor CPC definition of string RE consume to avoid eo::match
  proofs/eo/cpc/programs/Strings.eo
Labels: normal, moderate

#11947 Refactor CPC arithmetic signature to avoid eo::match, fix types
  proofs/eo/cpc/programs/Arith.eo
  proofs/eo/cpc/rules/Arith.eo
Labels: normal, moderate
